import{describe,expect,it,vi}from'vitest';import{parseSupabaseStoragePath,SupabaseAssetStore,validateStorageSecret}from'./asset-store.js';
function legacyServiceRole(){const part=(value:unknown)=>Buffer.from(JSON.stringify(value)).toString('base64url');return`${part({alg:'HS256',typ:'JWT'})}.${part({role:'service_role'})}.signature`}
type FetchArgs=[RequestInfo|URL,RequestInit?];
const call=(mock:ReturnType<typeof vi.fn>,index=0)=>mock.mock.calls[index]as unknown as FetchArgs;
describe('Supabase asset storage',()=>{
 it('accepts only server-side secret credentials',()=>{expect(validateStorageSecret('sb_secret_server_only')).toBe('sb_secret_server_only');const jwt=legacyServiceRole();expect(validateStorageSecret(jwt)).toBe(jwt);for(const bad of['','sb_publishable_public','sbp_management_pat','abc.def.ghi'])expect(()=>validateStorageSecret(bad)).toThrow(/asset_storage_secret/)});
 it('checks the private bucket without exposing the secret in the URL',async()=>{const fetchImpl=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>new Response(null,{status:200})),store=new SupabaseAssetStore({url:'https://project.supabase.co',secretKey:'sb_secret_hidden',bucket:'question-assets',fetchImpl:fetchImpl as typeof fetch});await store.checkReady();expect(fetchImpl).toHaveBeenCalledTimes(1);const[url,init]=call(fetchImpl);expect(url).toBe('https://project.supabase.co/storage/v1/bucket/question-assets');expect(init).toMatchObject({method:'HEAD',headers:{apikey:'sb_secret_hidden',authorization:'Bearer sb_secret_hidden'}});expect(String(url)).not.toContain('sb_secret_hidden')});
 it('uploads an immutable content-addressed PNG with idempotent upsert',async()=>{const fetchImpl=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>new Response(JSON.stringify({Key:'question-assets/papers/p1/q1/a.png'}),{status:200,headers:{'content-type':'application/json'}})),store=new SupabaseAssetStore({url:'https://project.supabase.co/',secretKey:'sb_secret_hidden',bucket:'question-assets',fetchImpl:fetchImpl as typeof fetch}),bytes=new Uint8Array([1,2,3,4]);const result=await store.putPng({objectPath:'papers/p1/q 1/a.png',bytes,contentHash:'abc123'});expect(result).toEqual({storagePath:'supabase://question-assets/papers/p1/q 1/a.png',objectPath:'papers/p1/q 1/a.png',sizeBytes:4,contentHash:'abc123'});const[url,init]=call(fetchImpl);expect(url).toBe('https://project.supabase.co/storage/v1/object/question-assets/papers/p1/q%201/a.png');expect(init).toMatchObject({method:'POST',headers:expect.objectContaining({'content-type':'image/png','x-upsert':'true','cache-control':'max-age=31536000'})});expect(init?.body).toBe(bytes)});
 it('creates a short-lived browser URL for a private supabase:// asset',async()=>{const fetchImpl=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>new Response(JSON.stringify({signedURL:'/object/sign/question-assets/papers/p1/q%201/a.png?token=temporary'}),{status:200,headers:{'content-type':'application/json'}})),store=new SupabaseAssetStore({url:'https://project.supabase.co',secretKey:'sb_secret_hidden',bucket:'question-assets',fetchImpl:fetchImpl as typeof fetch});const url=await store.signStoragePath('supabase://question-assets/papers/p1/q 1/a.png',300);expect(url).toBe('https://project.supabase.co/storage/v1/object/sign/question-assets/papers/p1/q%201/a.png?token=temporary');const[requestUrl,init]=call(fetchImpl);expect(requestUrl).toBe('https://project.supabase.co/storage/v1/object/sign/question-assets/papers/p1/q%201/a.png');expect(init).toMatchObject({method:'POST',headers:expect.objectContaining({'content-type':'application/json'}),body:JSON.stringify({expiresIn:300})});expect(String(requestUrl)).not.toContain('sb_secret_hidden')});
 it('returns null for a non-Supabase storage path instead of trying to sign it',async()=>{const fetchImpl=vi.fn(),store=new SupabaseAssetStore({url:'https://project.supabase.co',secretKey:'sb_secret_hidden',bucket:'question-assets',fetchImpl:fetchImpl as typeof fetch});await expect(store.signStoragePath('/legacy/local/file.png')).resolves.toBeNull();expect(fetchImpl).not.toHaveBeenCalled()});
 it('rejects cross-bucket signing and unreasonable expiry windows',async()=>{const fetchImpl=vi.fn(),store=new SupabaseAssetStore({url:'https://project.supabase.co',secretKey:'sb_secret_hidden',bucket:'question-assets',fetchImpl:fetchImpl as typeof fetch});await expect(store.signStoragePath('supabase://other-bucket/a.png')).rejects.toThrow('asset_storage_bucket_mismatch:other-bucket');await expect(store.signStoragePath('supabase://question-assets/a.png',5)).rejects.toThrow('asset_storage_signed_url_expiry_invalid');expect(fetchImpl).not.toHaveBeenCalled()});
 it('parses internal Supabase storage URIs without accepting traversal',()=>{expect(parseSupabaseStoragePath('supabase://question-assets/papers/p1/a.png')).toEqual({bucket:'question-assets',objectPath:'papers/p1/a.png'});expect(()=>parseSupabaseStoragePath('supabase://question-assets/papers/../secret.png')).toThrow('asset_storage_object_path_invalid')});
 it('fails closed when the bucket, upload or signing endpoint is unavailable',async()=>{const fetchImpl=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>new Response('denied',{status:403})),store=new SupabaseAssetStore({url:'https://project.supabase.co',secretKey:'sb_secret_hidden',bucket:'question-assets',fetchImpl:fetchImpl as typeof fetch});await expect(store.checkReady()).rejects.toThrow('asset_storage_bucket_unavailable:403:denied');await expect(store.putPng({objectPath:'a.png',bytes:new Uint8Array([1]),contentHash:'h'})).rejects.toThrow('asset_storage_upload_failed:403:denied');await expect(store.signStoragePath('supabase://question-assets/a.png')).rejects.toThrow('asset_storage_sign_failed:403:denied')});
 it('rejects path traversal before making a network request',async()=>{const fetchImpl=vi.fn(async(_input:RequestInfo|URL,_init?:RequestInit)=>new Response(null,{status:200})),store=new SupabaseAssetStore({url:'https://project.supabase.co',secretKey:'sb_secret_hidden',bucket:'question-assets',fetchImpl:fetchImpl as typeof fetch});await expect(store.putPng({objectPath:'paper/../secret.png',bytes:new Uint8Array([1]),contentHash:'h'})).rejects.toThrow('asset_storage_object_path_invalid');expect(fetchImpl).not.toHaveBeenCalled()});
});
