import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import{loadCorpusReadiness}from'./corpus-readiness.js';
const tables:Record<string,string[]>={source_papers:['storage_path','sha256','page_count'],jobs:['idempotency_key','ref_table','ref_id'],ingestion_runs:['attempt_no','run_key'],question_assets:['source_page','source_bbox','crop_status','crop_error','size_bytes','content_hash'],question_dependencies:['kind','strength','evidence','confidence'],validation_findings:['rule_code','severity','ref_table','ref_id'],cross_checks:['checker_prompt_version','agrees','confidence'],component_topics:['component_id','topic_id','is_primary'],component_learning_objectives:['component_id','learning_objective_id']};
const allMigrations=['0018_question_asset_source_bbox.sql','0019_ingestion_run_attempt.sql','0020_question_asset_storage_metadata.sql','0024_component_topic_coverage.sql','0025_component_learning_objective_coverage.sql'];
const readyEnv={ANTHROPIC_API_KEY:'anthropic-configured',SUPABASE_URL:'https://project.supabase.co',SUPABASE_STORAGE_SECRET_KEY:'sb_secret_configured',ASSET_STORAGE_BUCKET:'question-assets'};
function pool(input:{drop?:[string,string];migrations?:string[];schemaError?:boolean}={}){const rows=Object.entries(tables).flatMap(([table,columns])=>columns.filter(column=>!input.drop||input.drop[0]!==table||input.drop[1]!==column).map(column=>({table_name:table,column_name:column})));const query=vi.fn(async(sql:string)=>{if(input.schemaError&&sql.startsWith('select table_name'))throw new Error('db down');if(sql.startsWith('select table_name'))return{rowCount:rows.length,rows};if(sql.startsWith('select name from schema_migrations')){const names=input.migrations??allMigrations;return{rowCount:names.length,rows:names.map(name=>({name}))}}throw new Error(`unexpected ${sql}`)});return{query}as unknown as Pool}
const probes={probeBinary:vi.fn().mockResolvedValue(true),probeStorage:vi.fn().mockResolvedValue(undefined)};
describe('corpus readiness',()=>{
 it('is ready only when schema, taxonomy crosswalk, binaries, AI and durable storage are all available',async()=>{const result=await loadCorpusReadiness(pool(),{env:readyEnv,...probes});expect(result.ready).toBe(true);expect(result.blocked).toBe(0);expect(result.warnings).toBe(1);expect(result.checks).toEqual(expect.arrayContaining([expect.objectContaining({code:'schema.component_topics',status:'ready'}),expect.objectContaining({code:'schema.component_learning_objectives',status:'ready'}),expect.objectContaining({code:'schema.migrations',status:'ready'}),expect.objectContaining({code:'ai.anthropic',status:'ready'}),expect.objectContaining({code:'storage.supabase',status:'ready'})]))});
 it('blocks when a required migration column is absent',async()=>{const result=await loadCorpusReadiness(pool({drop:['question_assets','content_hash']}),{env:readyEnv,...probes});expect(result.ready).toBe(false);expect(result.checks).toContainEqual(expect.objectContaining({code:'schema.question_assets',status:'blocked',message:expect.stringContaining('content_hash')}))});
 it('blocks when topic or LO component coverage is absent',async()=>{const topic=await loadCorpusReadiness(pool({drop:['component_topics','is_primary']}),{env:readyEnv,...probes});expect(topic.ready).toBe(false);const lo=await loadCorpusReadiness(pool({drop:['component_learning_objectives','learning_objective_id']}),{env:readyEnv,...probes});expect(lo.ready).toBe(false);expect(lo.checks).toContainEqual(expect.objectContaining({code:'schema.component_learning_objectives',status:'blocked'}))});
 it('blocks when migration history is incomplete',async()=>{const result=await loadCorpusReadiness(pool({migrations:allMigrations.slice(0,-1)}),{env:readyEnv,...probes});expect(result.checks).toContainEqual(expect.objectContaining({code:'schema.migrations',status:'blocked',message:expect.stringContaining('0025_component_learning_objective_coverage.sql')}))});
 it('blocks on missing Poppler or Anthropic configuration without exposing secrets',async()=>{const probe=vi.fn(async(command:string)=>command==='pdftoppm');const result=await loadCorpusReadiness(pool(),{env:{SUPABASE_URL:'https://project.supabase.co',SUPABASE_STORAGE_SECRET_KEY:'sb_secret_hidden'},probeBinary:probe,probeStorage:vi.fn().mockResolvedValue(undefined)});expect(result.ready).toBe(false);expect(result.checks).toEqual(expect.arrayContaining([expect.objectContaining({code:'binary.pdftotext',status:'blocked'}),expect.objectContaining({code:'ai.anthropic',status:'blocked'})]));expect(JSON.stringify(result)).not.toContain('sb_secret_hidden')});
 it('blocks when private asset storage is not reachable',async()=>{const result=await loadCorpusReadiness(pool(),{env:readyEnv,probeBinary:vi.fn().mockResolvedValue(true),probeStorage:vi.fn().mockRejectedValue(new Error('bucket unavailable'))});expect(result.ready).toBe(false);expect(result.checks).toContainEqual(expect.objectContaining({code:'storage.supabase',status:'blocked',message:expect.stringContaining('bucket unavailable')}))});
 it('returns a blocked diagnostic instead of crashing when schema inspection fails',async()=>{const result=await loadCorpusReadiness(pool({schemaError:true}),{env:readyEnv,...probes});expect(result.ready).toBe(false);expect(result.checks).toContainEqual(expect.objectContaining({code:'schema.inspect',status:'blocked',message:expect.stringContaining('db down')}))});
});
