import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import{loadCorpusStatus}from'./corpus-status.js';
function pool(rows:Record<string,unknown>[]){return{query:vi.fn().mockResolvedValue({rowCount:rows.length,rows})}as unknown as Pool}
const row=(overrides:Record<string,unknown>={})=>({run_id:'run-1',year:2025,series:'MJ',paper_code:11,status:'needs_review',attempt_no:1,run_key:'rk',qp_paper_id:'qp',ms_paper_id:'ms',updated_at:'2026-08-14T15:00:00Z',leaf_count:12,approved_leaf_count:10,needs_review_leaf_count:2,pending_asset_count:1,failed_asset_count:0,error_finding_count:1,warning_finding_count:2,ai_calls:14,ai_failures:1,input_tokens:1000,output_tokens:500,known_cost_usd:'0.123',failed_job_kind:null,failed_job_error:null,...overrides});
describe('corpus status',()=>{
 it('aggregates rollout status, findings, assets and AI usage',async()=>{const result=await loadCorpusStatus(pool([row(),row({run_id:'run-2',paper_code:12,status:'approved',leaf_count:11,approved_leaf_count:11,needs_review_leaf_count:0,pending_asset_count:0,error_finding_count:0,warning_finding_count:0,ai_calls:10,ai_failures:0,input_tokens:800,output_tokens:300,known_cost_usd:'0.100'})]));expect(result.totals).toEqual({runs:2,approved:1,needsReview:1,failed:0,processing:0,queued:0,leafCount:23,approvedLeafCount:21,pendingAssets:1,failedAssets:0,errorFindings:1,warningFindings:2,aiCalls:24,aiFailures:1,inputTokens:1800,outputTokens:800,knownCostUsd:.223});expect(result.runs[0]).toMatchObject({year:2025,paperCode:11,status:'needs_review',knownCostUsd:.123})});
 it('returns unknown aggregate cost if any run contains unpriced AI calls',async()=>{const result=await loadCorpusStatus(pool([row({known_cost_usd:null})]));expect(result.totals.knownCostUsd).toBeNull()});
 it('preserves the most recent failed job diagnostic',async()=>{const result=await loadCorpusStatus(pool([row({status:'failed',failed_job_kind:'ingest-crosscheck',failed_job_error:'provider timeout'})]));expect(result.totals.failed).toBe(1);expect(result.runs[0]).toMatchObject({failedJobKind:'ingest-crosscheck',failedJobError:'provider timeout'})});
 it('rejects unsafe report limits and year ranges before querying',async()=>{const p=pool([]);await expect(loadCorpusStatus(p,{limit:0})).rejects.toThrow('corpus_status_limit_invalid');await expect(loadCorpusStatus(p,{yearFrom:2026,yearTo:2025})).rejects.toThrow('corpus_status_year_range_invalid')});
});
