import type{Pool}from'pg';
export interface CorpusStatusRun{runId:string;year:number;series:string;paperCode:number;status:string;attemptNo:number;runKey:string|null;qpPaperId:string|null;msPaperId:string|null;leafCount:number;approvedLeafCount:number;needsReviewLeafCount:number;pendingAssetCount:number;failedAssetCount:number;errorFindingCount:number;warningFindingCount:number;aiCalls:number;aiFailures:number;inputTokens:number;outputTokens:number;knownCostUsd:number|null;failedJobKind:string|null;failedJobError:string|null;updatedAt:string}
export interface CorpusStatusReport{filters:{yearFrom:number;yearTo:number;syllabusCode:string};totals:{runs:number;approved:number;needsReview:number;failed:number;processing:number;queued:number;leafCount:number;approvedLeafCount:number;pendingAssets:number;failedAssets:number;errorFindings:number;warningFindings:number;aiCalls:number;aiFailures:number;inputTokens:number;outputTokens:number;knownCostUsd:number|null};runs:CorpusStatusRun[]}
export async function loadCorpusStatus(pool:Pool,input:{yearFrom?:number;yearTo?:number;syllabusCode?:string;limit?:number}={}):Promise<CorpusStatusReport>{const yearFrom=input.yearFrom??2021,yearTo=input.yearTo??2025,syllabusCode=input.syllabusCode??'9618',limit=input.limit??200;if(!Number.isInteger(yearFrom)||!Number.isInteger(yearTo)||yearFrom>yearTo)throw new Error('corpus_status_year_range_invalid');if(!Number.isInteger(limit)||limit<1||limit>1000)throw new Error('corpus_status_limit_invalid');const result=await pool.query(`select ir.id run_id,ir.year,ir.series::text series,c.number*10+ir.variant paper_code,ir.status,ir.attempt_no,ir.run_key,ir.qp_paper_id,ir.ms_paper_id,ir.updated_at,
  coalesce(qs.leaf_count,0)::int leaf_count,coalesce(qs.approved_leaf_count,0)::int approved_leaf_count,coalesce(qs.needs_review_leaf_count,0)::int needs_review_leaf_count,
  coalesce(ast.pending_asset_count,0)::int pending_asset_count,coalesce(ast.failed_asset_count,0)::int failed_asset_count,
  coalesce(vf.error_finding_count,0)::int error_finding_count,coalesce(vf.warning_finding_count,0)::int warning_finding_count,
  coalesce(ai.ai_calls,0)::int ai_calls,coalesce(ai.ai_failures,0)::int ai_failures,coalesce(ai.input_tokens,0)::bigint input_tokens,coalesce(ai.output_tokens,0)::bigint output_tokens,ai.known_cost_usd,
  fj.kind failed_job_kind,fj.error failed_job_error
 from ingestion_runs ir join components c on c.id=ir.component_id join syllabi s on s.id=ir.syllabus_id
 left join lateral(select count(*) filter(where q.marks is not null)::int leaf_count,count(*) filter(where q.marks is not null and q.status='approved')::int approved_leaf_count,count(*) filter(where q.marks is not null and q.status='needs_review')::int needs_review_leaf_count from questions q where q.source_paper_id=ir.qp_paper_id)qs on true
 left join lateral(select count(*) filter(where qa.crop_status='pending')::int pending_asset_count,count(*) filter(where qa.crop_status='failed')::int failed_asset_count from question_assets qa join questions q on q.id=qa.question_id where q.source_paper_id=ir.qp_paper_id)ast on true
 left join lateral(select count(*) filter(where v.severity='error')::int error_finding_count,count(*) filter(where v.severity='warning')::int warning_finding_count from validation_findings v where v.ref_table='source_papers' and v.ref_id=ir.qp_paper_id)vf on true
 left join lateral(select count(*)::int ai_calls,count(*) filter(where ac.ok=false)::int ai_failures,coalesce(sum(ac.input_tokens),0)::bigint input_tokens,coalesce(sum(ac.output_tokens),0)::bigint output_tokens,case when count(*) filter(where ac.cost_usd is null)>0 then null else coalesce(sum(ac.cost_usd),0) end known_cost_usd from ai_calls ac where (ac.ref_table='source_papers' and ac.ref_id in(ir.qp_paper_id,ir.ms_paper_id)) or (ac.ref_table='ingestion_runs' and ac.ref_id=ir.id))ai on true
 left join lateral(select j.kind,j.error from jobs j where j.ref_table='ingestion_runs' and j.ref_id=ir.id and j.status='failed' order by j.finished_at desc nulls last,j.created_at desc limit 1)fj on true
 where s.code=$1 and ir.year between $2 and $3 order by ir.year desc,ir.series desc,c.number,ir.variant limit $4`,[syllabusCode,yearFrom,yearTo,limit]);const runs:CorpusStatusRun[]=result.rows.map(row=>({runId:String(row.run_id),year:Number(row.year),series:String(row.series),paperCode:Number(row.paper_code),status:String(row.status),attemptNo:Number(row.attempt_no??0),runKey:row.run_key===null?null:String(row.run_key),qpPaperId:row.qp_paper_id===null?null:String(row.qp_paper_id),msPaperId:row.ms_paper_id===null?null:String(row.ms_paper_id),leafCount:Number(row.leaf_count),approvedLeafCount:Number(row.approved_leaf_count),needsReviewLeafCount:Number(row.needs_review_leaf_count),pendingAssetCount:Number(row.pending_asset_count),failedAssetCount:Number(row.failed_asset_count),errorFindingCount:Number(row.error_finding_count),warningFindingCount:Number(row.warning_finding_count),aiCalls:Number(row.ai_calls),aiFailures:Number(row.ai_failures),inputTokens:Number(row.input_tokens),outputTokens:Number(row.output_tokens),knownCostUsd:row.known_cost_usd===null?null:Number(row.known_cost_usd),failedJobKind:row.failed_job_kind===null?null:String(row.failed_job_kind),failedJobError:row.failed_job_error===null?null:String(row.failed_job_error).slice(0,1000),updatedAt:new Date(row.updated_at).toISOString()}));const knownCosts=runs.map(run=>run.knownCostUsd),knownCostUsd=knownCosts.some(value=>value===null)?null:knownCosts.reduce((sum,value)=>sum+(value??0),0);return{filters:{yearFrom,yearTo,syllabusCode},totals:{runs:runs.length,approved:runs.filter(run=>run.status==='approved').length,needsReview:runs.filter(run=>run.status==='needs_review').length,failed:runs.filter(run=>run.status==='failed').length,processing:runs.filter(run=>run.status==='processing').length,queued:runs.filter(run=>run.status==='queued').length,leafCount:sum(runs,'leafCount'),approvedLeafCount:sum(runs,'approvedLeafCount'),pendingAssets:sum(runs,'pendingAssetCount'),failedAssets:sum(runs,'failedAssetCount'),errorFindings:sum(runs,'errorFindingCount'),warningFindings:sum(runs,'warningFindingCount'),aiCalls:sum(runs,'aiCalls'),aiFailures:sum(runs,'aiFailures'),inputTokens:sum(runs,'inputTokens'),outputTokens:sum(runs,'outputTokens'),knownCostUsd},runs}}
function sum(runs:CorpusStatusRun[],key:keyof CorpusStatusRun){return runs.reduce((total,run)=>total+Number(run[key]??0),0)}
