import{pool}from'../database/client.js';import{loadCorpusReadiness}from'./corpus-readiness.js';import{loadCorpusPreflight}from'./corpus-preflight.js';import{buildCorpusQueuePlan}from'./corpus-queue-plan.js';import{enqueueCorpusPlan}from'./corpus-enqueue.js';
if(!pool)throw new Error('DATABASE_URL is required');
const args=process.argv.slice(2),apply=args.includes('--apply'),allowPartial=args.includes('--allow-partial');
const value=(name:string)=>args.find(arg=>arg.startsWith(`--${name}=`))?.slice(name.length+3);
const yearFrom=Number(value('year-from')??2021),yearTo=Number(value('year-to')??2025),syllabusCode=value('syllabus')??'9618',pipelineVersion=value('pipeline')??'real-paper-v2',limitRaw=value('limit'),limit=limitRaw?Number(limitRaw):null;
if(!Number.isInteger(yearFrom)||!Number.isInteger(yearTo)||yearFrom>yearTo)throw new Error('Invalid --year-from/--year-to');if(limit!==null&&(!Number.isInteger(limit)||limit<=0))throw new Error('--limit must be a positive integer');
const[readiness,preflight]=await Promise.all([loadCorpusReadiness(pool),loadCorpusPreflight(pool,{yearFrom,yearTo,syllabusCode})]),fullPlan=buildCorpusQueuePlan(preflight.rows),plan={...fullPlan,items:limit===null?fullPlan.items:fullPlan.items.slice(0,limit)};
const preview={mode:apply?'APPLY':'DRY_RUN',filters:{yearFrom,yearTo,syllabusCode,pipelineVersion,limit},readiness:{ready:readiness.ready,blocked:readiness.blocked,warnings:readiness.warnings,checks:readiness.checks},preflight:{total:preflight.total,complete:preflight.complete,ready:preflight.ready,sourceMissing:preflight.sourceMissing,knownMinimumExtractionCalls:preflight.knownMinimumExtractionCalls},plan:{queueCount:plan.items.length,skippedComplete:plan.skippedComplete.length,blockedSources:plan.blockedSources.length,firstKeys:plan.items.slice(0,10).map(item=>item.key)}};
if(!apply){console.log(JSON.stringify(preview,null,2));await pool.end();process.exit(0)}
if(process.env.CONFIRM_CORPUS_ENQUEUE!=='YES')throw new Error('Set CONFIRM_CORPUS_ENQUEUE=YES to use --apply');if(!readiness.ready)throw new Error(`Refusing corpus enqueue: worker readiness has ${readiness.blocked} blocking check(s). Run corpus:readiness and fix them first.`);if(plan.blockedSources.length&&!allowPartial)throw new Error(`Refusing partial corpus enqueue: ${plan.blockedSources.length} source pair(s) are blocked. Fix staging or pass --allow-partial explicitly.`);if(!plan.items.length){console.log(JSON.stringify({...preview,result:{queued:0,skippedActive:0}},null,2));await pool.end();process.exit(0)}
const result=await enqueueCorpusPlan(pool,plan,{pipelineVersion});console.log(JSON.stringify({...preview,result:{queued:result.queued.length,skippedActive:result.skippedActive.length,queuedRuns:result.queued,activeRuns:result.skippedActive}},null,2));await pool.end();
