import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import{loadCorpusReadiness}from'./corpus-readiness.js';
const tables:Record<string,string[]>={source_papers:['storage_path','sha256','page_count'],jobs:['idempotency_key','ref_table','ref_id'],ingestion_runs:['attempt_no','run_key'],question_assets:['source_page','source_bbox','crop_status','crop_error'],question_dependencies:['kind','strength','evidence','confidence'],validation_findings:['rule_code','severity','ref_table','ref_id'],cross_checks:['checker_prompt_version','agrees','confidence']};
function pool(input:{drop?:[string,string];migrations?:string[];schemaError?:boolean}={}){const rows=Object.entries(tables).flatMap(([table,columns])=>columns.filter(column=>!input.drop||input.drop[0]!==table||input.drop[1]!==column).map(column=>({table_name:table,column_name:column})));const query=vi.fn(async(sql:string)=>{if(input.schemaError&&sql.startsWith('select table_name'))throw new Error('db down');if(sql.startsWith('select table_name'))return{rowCount:rows.length,rows};if(sql.startsWith('select name from schema_migrations')){const names=input.migrations??['0018_question_asset_source_bbox.sql','0019_ingestion_run_attempt.sql'];return{rowCount:names.length,rows:names.map(name=>({name}))}}throw new Error(`unexpected ${sql}`)});return{query}as unknown as Pool}
describe('corpus readiness',()=>{
 it('is ready only when schema, migrations, binaries and AI key are all available',async()=>{const result=await loadCorpusReadiness(pool(),{env:{ANTHROPIC_API_KEY:'secret'},probeBinary:vi.fn().mockResolvedValue(true)});expect(result.ready).toBe(true);expect(result.blocked).toBe(0);expect(result.warnings).toBe(1);expect(result.checks).toEqual(expect.arrayContaining([expect.objectContaining({code:'schema.migrations',status:'ready'}),expect.objectContaining({code:'ai.anthropic',status:'ready'})]))});
 it('blocks when a required migration column is absent',async()=>{const result=await loadCorpusReadiness(pool({drop:['ingestion_runs','run_key']}),{env:{ANTHROPIC_API_KEY:'secret'},probeBinary:vi.fn().mockResolvedValue(true)});expect(result.ready).toBe(false);expect(result.checks).toContainEqual(expect.objectContaining({code:'schema.ingestion_runs',status:'blocked',message:expect.stringContaining('run_key')}))});
 it('blocks when migration history is incomplete',async()=>{const result=await loadCorpusReadiness(pool({migrations:['0018_question_asset_source_bbox.sql']}),{env:{ANTHROPIC_API_KEY:'secret'},probeBinary:vi.fn().mockResolvedValue(true)});expect(result.checks).toContainEqual(expect.objectContaining({code:'schema.migrations',status:'blocked',message:expect.stringContaining('0019_ingestion_run_attempt.sql')}))});
 it('blocks on missing Poppler or Anthropic configuration without exposing secrets',async()=>{const probe=vi.fn(async(command:string)=>command==='pdftoppm');const result=await loadCorpusReadiness(pool(),{env:{},probeBinary:probe});expect(result.ready).toBe(false);expect(result.checks).toEqual(expect.arrayContaining([expect.objectContaining({code:'binary.pdftotext',status:'blocked'}),expect.objectContaining({code:'ai.anthropic',status:'blocked'})]));expect(JSON.stringify(result)).not.toContain('secret')});
 it('returns a blocked diagnostic instead of crashing when schema inspection fails',async()=>{const result=await loadCorpusReadiness(pool({schemaError:true}),{env:{ANTHROPIC_API_KEY:'x'},probeBinary:vi.fn().mockResolvedValue(true)});expect(result.ready).toBe(false);expect(result.checks).toContainEqual(expect.objectContaining({code:'schema.inspect',status:'blocked',message:expect.stringContaining('db down')}))});
});
