import{describe,expect,it,vi}from'vitest';import type{Pool,PoolClient}from'pg';import{buildSourceRunKey,enqueueCorpusPlan}from'./corpus-enqueue.js';import type{CorpusQueuePlan}from'./corpus-queue-plan.js';
const plan:CorpusQueuePlan={items:[{key:'2025-MJ-11',qpPaperId:'qp-1',msPaperId:'ms-1',reason:'incomplete_or_unreviewed'}],blockedSources:[],skippedComplete:[]};
const pair={syllabus_id:'syllabus-1',component_id:'component-1',year:2025,series:'MJ',variant:1,qp_kind:'QP',qp_sha:'a'.repeat(64),ms_syllabus_id:'syllabus-1',ms_component_id:'component-1',ms_year:2025,ms_series:'MJ',ms_variant:1,ms_kind:'MS',ms_sha:'b'.repeat(64)};
function mockPool(existing?:{id:string;status:string;attempt_no:number},mismatch=false){const query=vi.fn(async(sql:string,values?:unknown[])=>{if(sql==='begin'||sql==='commit'||sql==='rollback')return{rowCount:null,rows:[]};if(sql.startsWith('select qp.syllabus_id'))return{rowCount:1,rows:[mismatch?{...pair,ms_variant:2}:pair]};if(sql.startsWith('select id,status,attempt_no'))return{rowCount:existing?1:0,rows:existing?[existing]:[]};if(sql.startsWith('insert into ingestion_runs'))return{rowCount:1,rows:[{id:'run-1',attempt_no:1}]};if(sql.startsWith('update ingestion_runs set qp_paper_id'))return{rowCount:1,rows:[{id:existing?.id??'run-1',attempt_no:(existing?.attempt_no??0)+1}]};if(sql.startsWith('update ingestion_runs set run_key'))return{rowCount:1,rows:[]};if(sql.startsWith('insert into jobs'))return{rowCount:1,rows:[{id:'job-1',status:'queued'}]};throw new Error(`unexpected query: ${sql} ${JSON.stringify(values)}`)});const client={query,release:vi.fn()}as unknown as PoolClient;return{pool:{connect:vi.fn().mockResolvedValue(client)}as unknown as Pool,query,client}}
describe('corpus durable enqueue',()=>{
 it('creates a new ingestion run and one versioned bundle job atomically',async()=>{const p=mockPool();const result=await enqueueCorpusPlan(p.pool,plan,{pipelineVersion:'real-paper-v2'});expect(result.queued).toHaveLength(1);expect(result.queued[0]).toMatchObject({key:'2025-MJ-11',runId:'run-1',attemptNo:1,jobId:'job-1',jobStatus:'queued'});expect(result.queued[0]!.runKey).toBe(`real-paper-v2:${'a'.repeat(20)}:${'b'.repeat(20)}:attempt-1`);const jobCall=p.query.mock.calls.find(([sql])=>String(sql).startsWith('insert into jobs'));expect(jobCall?.[1]).toEqual(expect.arrayContaining(['ingest-bundle',expect.objectContaining({runId:'run-1',runKey:result.queued[0]!.runKey}),`ingest-run:run-1:${result.queued[0]!.runKey}:bundle`]));expect(p.query.mock.calls.map(([sql])=>sql)).toEqual(expect.arrayContaining(['begin','commit']))});
 it('does not duplicate an already queued or processing run',async()=>{const p=mockPool({id:'run-active',status:'processing',attempt_no:3});const result=await enqueueCorpusPlan(p.pool,plan);expect(result.queued).toEqual([]);expect(result.skippedActive).toEqual([{key:'2025-MJ-11',runId:'run-active',status:'processing'}]);expect(p.query.mock.calls.some(([sql])=>String(sql).startsWith('insert into jobs'))).toBe(false)});
 it('increments attempt number when explicitly retrying a failed run',async()=>{const p=mockPool({id:'run-retry',status:'failed',attempt_no:3});const result=await enqueueCorpusPlan(p.pool,plan);expect(result.queued[0]).toMatchObject({runId:'run-retry',attemptNo:4});expect(result.queued[0]!.runKey).toMatch(/:attempt-4$/)});
 it('rolls back when QP and MS metadata do not describe the same variant',async()=>{const p=mockPool(undefined,true);await expect(enqueueCorpusPlan(p.pool,plan)).rejects.toThrow('source_pair_metadata_mismatch');expect(p.query.mock.calls.map(([sql])=>sql)).toContain('rollback');expect(p.client.release).toHaveBeenCalled()});
 it('sanitizes the durable source run key',()=>{expect(buildSourceRunKey('Real Paper/V2','AA++','BB??')).toBe('real-paper-v2:aa--:bb--')});
});
