import{execFile}from'node:child_process';import{promisify}from'node:util';import type{Pool}from'pg';import{SupabaseAssetStore}from'./asset-store.js';
const run=promisify(execFile);
export type ReadinessStatus='ready'|'warning'|'blocked';
export interface ReadinessCheck{code:string;status:ReadinessStatus;message:string}
export interface CorpusReadiness{ready:boolean;blocked:number;warnings:number;checks:ReadinessCheck[]}
type Env=Record<string,string|undefined>;type BinaryProbe=(command:string)=>Promise<boolean>;type StorageProbe=(env:Env)=>Promise<void>;
const requiredColumns:Record<string,string[]>={
 source_papers:['storage_path','sha256','page_count'],jobs:['idempotency_key','ref_table','ref_id'],ingestion_runs:['attempt_no','run_key'],question_assets:['source_page','source_bbox','crop_status','crop_error','size_bytes','content_hash'],question_dependencies:['kind','strength','evidence','confidence'],validation_findings:['rule_code','severity','ref_table','ref_id'],cross_checks:['checker_prompt_version','agrees','confidence'],component_topics:['component_id','topic_id','is_primary'],
};
const requiredMigrations=['0018_question_asset_source_bbox.sql','0019_ingestion_run_attempt.sql','0020_question_asset_storage_metadata.sql','0021_component_topic_coverage.sql'];
export async function loadCorpusReadiness(pool:Pool,input:{env?:Env;probeBinary?:BinaryProbe;probeStorage?:StorageProbe}={}):Promise<CorpusReadiness>{const env=input.env??process.env,probe=input.probeBinary??probeBinary,storageProbe=input.probeStorage??probeSupabaseStorage,checks:ReadinessCheck[]=[];const add=(code:string,status:ReadinessStatus,message:string)=>checks.push({code,status,message});
 try{const tables=Object.keys(requiredColumns),result=await pool.query(`select table_name,column_name from information_schema.columns where table_schema='public' and table_name=any($1::text[])`,[tables]);const existing=new Map<string,Set<string>>();for(const row of result.rows){const table=String(row.table_name),column=String(row.column_name);if(!existing.has(table))existing.set(table,new Set());existing.get(table)!.add(column)}for(const[table,columns]of Object.entries(requiredColumns)){const missing=columns.filter(column=>!existing.get(table)?.has(column));missing.length?add(`schema.${table}`,'blocked',`Missing column(s): ${missing.join(', ')}`):add(`schema.${table}`,'ready',`${table} ingestion columns are present.`)}}catch(error){add('schema.inspect','blocked',`Cannot inspect database schema: ${message(error)}`)}
 try{const result=await pool.query(`select name from schema_migrations where name=any($1::text[])`,[requiredMigrations]);const applied=new Set(result.rows.map(row=>String(row.name)));const missing=requiredMigrations.filter(name=>!applied.has(name));missing.length?add('schema.migrations','blocked',`Required migration(s) not recorded: ${missing.join(', ')}`):add('schema.migrations','ready','Required ingestion migrations are recorded.')}catch(error){add('schema.migrations','blocked',`Cannot verify migration history: ${message(error)}`)}
 const pdftoppm=env.PDFTOPPM_PATH?.trim()||'pdftoppm',pdftotext=env.PDFTOTEXT_PATH?.trim()||'pdftotext';for(const[code,command]of[['binary.pdftoppm',pdftoppm],['binary.pdftotext',pdftotext]]as const){(await probe(command))?add(code,'ready',`${command} is executable.`):add(code,'blocked',`${command} is not executable on this worker.`)}
 env.ANTHROPIC_API_KEY?.trim()?add('ai.anthropic','ready','Anthropic API key is configured.'):add('ai.anthropic','blocked','ANTHROPIC_API_KEY is not configured.');
 env.ANTHROPIC_MODEL?.trim()?add('ai.model','ready',`Anthropic model override is configured (${env.ANTHROPIC_MODEL}).`):add('ai.model','warning','ANTHROPIC_MODEL is not set; the ingestion client default will be used.');
 try{await storageProbe(env);add('storage.supabase','ready',`Private Supabase Storage bucket ${env.ASSET_STORAGE_BUCKET?.trim()||'question-assets'} is reachable with a server-only credential.`)}catch(error){add('storage.supabase','blocked',`Durable asset storage is not ready: ${message(error)}`)}
 const blocked=checks.filter(check=>check.status==='blocked').length,warnings=checks.filter(check=>check.status==='warning').length;return{ready:blocked===0,blocked,warnings,checks}}
export async function probeBinary(command:string){try{await run(command,['-v'],{timeout:5000});return true}catch(error){const code=(error as NodeJS.ErrnoException).code;return code!=='ENOENT'&&code!=='EACCES'&&Boolean((error as any).stdout||(error as any).stderr)}}
export async function probeSupabaseStorage(env:Env){const url=env.SUPABASE_URL?.trim(),secretKey=env.SUPABASE_STORAGE_SECRET_KEY?.trim(),bucket=env.ASSET_STORAGE_BUCKET?.trim()||'question-assets';if(!url)throw new Error('SUPABASE_URL is not configured.');if(!secretKey)throw new Error('SUPABASE_STORAGE_SECRET_KEY is not configured.');const store=new SupabaseAssetStore({url,secretKey,bucket});await store.checkReady()}
function message(error:unknown){return error instanceof Error?error.message:String(error)}
