import{describe,expect,it}from'vitest';import{assessReferenceGolden}from'./reference-golden.js';
const identity={year:2025,series:'M/J',componentNumber:1,variant:1};
const leaves=[['1.a',2],['1.b',2],['2.a',4],['2.b.i',4],['2.b.ii',3],['2.c',2],['3.a',3],['3.b.i',2],['3.b.ii',1],['3.b.iii',1],['4.a',4],['4.b',2],['5.a',3],['5.b',1],['5.c',2],['5.d',3],['5.e',4],['6.a.i',4],['6.a.ii',3],['6.a.iii',2],['6.b',5],['7.a',3],['7.b',5],['7.c',3],['8.a',4],['8.b.i',1],['8.b.ii',1],['8.b.iii',1]]as const;
const artifact=()=>({questions:[{path:'1',marks:null},...leaves.map(([path,marks])=>({path,marks}))],markSchemes:leaves.map(([path])=>({path}))});
describe('reference structural golden',()=>{
 it('passes the verified 2025 M/J Paper 11 leaf/mark/MS structure',()=>{const result=assessReferenceGolden(identity,artifact());expect(result).toMatchObject({key:'9618-s25-11',available:true,pass:true,expectedLeafCount:28,actualLeafCount:28,expectedTotalMarks:75,actualTotalMarks:75,missingPaths:[],extraPaths:[],markMismatches:[],missingMarkSchemes:[],extraMarkSchemes:[]})});
 it('reports missing, extra and wrong-mark leaves without guessing a repair',()=>{const value=artifact();value.questions=value.questions.filter(item=>item.path!=='2.b.ii');value.questions.push({path:'9.a',marks:2});const target=value.questions.find(item=>item.path==='5.e')!;target.marks=3;value.markSchemes=value.markSchemes.filter(item=>item.path!=='7.c');value.markSchemes.push({path:'9.a'});const result=assessReferenceGolden(identity,value);expect(result.pass).toBe(false);expect(result.missingPaths).toContain('2.b.ii');expect(result.extraPaths).toContain('9.a');expect(result.markMismatches).toContainEqual({path:'5.e',expected:4,actual:3});expect(result.missingMarkSchemes).toContain('7.c');expect(result.extraMarkSchemes).toContain('9.a')});
 it('returns available=false for a paper that has no registered structural golden',()=>{const result=assessReferenceGolden({...identity,componentNumber:2},artifact());expect(result).toMatchObject({key:null,available:false,pass:null,actualLeafCount:28,actualTotalMarks:75})});
 it('normalizes common series labels for lookup',()=>{expect(assessReferenceGolden({...identity,series:'May/June'},artifact()).pass).toBe(true);expect(assessReferenceGolden({...identity,series:'MJ'},artifact()).pass).toBe(true)});
});
