import{pool}from'../database/client.js';import{config}from'../config.js';import{ClaudeIngestionClient}from'../lib/ai/claude.js';import{SupabaseAssetStore}from'./asset-store.js';import{loadCorpusReadiness}from'./corpus-readiness.js';import{assessReferenceGolden}from'./reference-golden.js';import{assertReferencePair,prepareReferencePaper}from'./reference-prepare.js';import{extractQuestionsV2Stage}from'./processors/ai-extract-qp-v2.js';import{extractMarkSchemesStage,detectDependenciesStage}from'./processors/ai-ingestion.js';import{classifyQuestionsV2Stage}from'./processors/ai-classify-v2.js';import{crossCheckStage}from'./processors/ai-crosscheck.js';import{cropAndStoreAssets}from'./processors/asset-crop-store.js';import{validateAssetMetadata}from'./processors/asset-metadata.js';import{matchLeafMarkSchemes}from'./processors/match-leaves.js';import{validateIngestionArtifact}from'./processors/ingestion.js';import{persistPaperArtifact}from'./processors/persist-paper.js';

if(!pool)throw new Error('DATABASE_URL is required');if(!config.ANTHROPIC_API_KEY)throw new Error('ANTHROPIC_API_KEY is required');
const args=process.argv.slice(2),qpPaperId=args.find(value=>value.startsWith('--qp='))?.slice(5),msPaperId=args.find(value=>value.startsWith('--ms='))?.slice(5),shouldPersist=args.includes('--persist');
if(!qpPaperId||!msPaperId)throw new Error('Usage: reference-ingest-cli --qp=<uuid> --ms=<uuid> [--persist]');
if(shouldPersist&&process.env.CONFIRM_REAL_PAPER_PERSIST!=='YES')throw new Error('Set CONFIRM_REAL_PAPER_PERSIST=YES to use --persist');
let assetStore:SupabaseAssetStore|null=null;if(shouldPersist){const readiness=await loadCorpusReadiness(pool);if(!readiness.ready)throw new Error(`Reference persist readiness blocked by ${readiness.blocked} check(s).`);if(!config.SUPABASE_URL||!config.SUPABASE_STORAGE_SECRET_KEY)throw new Error('Supabase private asset storage configuration is required for reference persist');assetStore=new SupabaseAssetStore({url:config.SUPABASE_URL,secretKey:config.SUPABASE_STORAGE_SECRET_KEY,bucket:config.ASSET_STORAGE_BUCKET})}
const pair=await assertReferencePair(pool,qpPaperId,msPaperId),ai=new ClaudeIngestionClient({apiKey:config.ANTHROPIC_API_KEY,model:config.ANTHROPIC_MODEL});
const started=Date.now();let artifact:Record<string,unknown>={qp:await prepareReferencePaper(pool,qpPaperId),ms:await prepareReferencePaper(pool,msPaperId)};
artifact=await extractQuestionsV2Stage(pool,ai,artifact);artifact=await extractMarkSchemesStage(pool,ai,artifact);artifact=matchLeafMarkSchemes(artifact);artifact=validateAssetMetadata(artifact);if(assetStore)artifact=await cropAndStoreAssets(artifact,assetStore);artifact=await classifyQuestionsV2Stage(pool,ai,artifact);artifact=await detectDependenciesStage(pool,ai,artifact);artifact=await validateIngestionArtifact(artifact,pool);artifact=await crossCheckStage(pool,ai,artifact);
const golden=assessReferenceGolden(pair,artifact);if(shouldPersist&&golden.available&&golden.pass!==true)throw new Error(`reference_golden_mismatch:${golden.key}`);if(shouldPersist)artifact=await persistPaperArtifact(pool,artifact);
const questions=Array.isArray(artifact.questions)?artifact.questions as Array<Record<string,unknown>>:[],schemes=Array.isArray(artifact.markSchemes)?artifact.markSchemes as Array<Record<string,unknown>>:[],findings=Array.isArray(artifact.validationFindings)?artifact.validationFindings as Array<Record<string,unknown>>:[],checks=Array.isArray(artifact.crossChecks)?artifact.crossChecks as Array<Record<string,unknown>>:[],assets=Array.isArray(artifact.assetCandidates)?artifact.assetCandidates:[],storedAssets=Array.isArray(artifact.storedAssets)?artifact.storedAssets:[];
console.log(JSON.stringify({pair,elapsedMs:Date.now()-started,persisted:shouldPersist,golden,qpExtraction:(artifact.qp as any)?.extraction??null,questionNodes:questions.length,leafQuestions:questions.filter(item=>item.marks!==null&&item.marks!==undefined).length,markSchemes:schemes.length,assetCandidates:assets.length,storedAssets:storedAssets.length,assetStoreReport:artifact.assetStoreReport??null,validation:{status:artifact.reviewStatus,findings:findings.map(item=>({code:item.code,severity:item.severity,message:item.message}))},crossCheck:{count:checks.length,disagreed:checks.filter(item=>item.agrees===false).length,lowConfidence:checks.filter(item=>typeof item.confidence==='number'&&Number(item.confidence)<.8).length},persistResult:artifact.persistResult??null},null,2));await pool.end();
