import{mkdtemp,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{afterEach,describe,expect,it,vi}from'vitest';import type{Pool,PoolClient}from'pg';import{parsePaperCode,registerStagedSources,validateStageManifest}from'./source-stage-manifest.js';
const dirs:string[]=[];afterEach(async()=>Promise.all(dirs.splice(0).map(path=>rm(path,{recursive:true,force:true}))));async function source(size=2048,fill=7){const dir=await mkdtemp(join(tmpdir(),'campath-source-'));dirs.push(dir);const path=join(dir,'9618_s25_qp_11.pdf');await writeFile(path,Buffer.alloc(size,fill));return path}
describe('source staging manifest',()=>{
 it('parses component and variant from Cambridge paper code',()=>{expect(parsePaperCode(11)).toEqual({component:1,variant:1});expect(parsePaperCode(43)).toEqual({component:4,variant:3});expect(()=>parsePaperCode(49)).toThrow('invalid_paper_code:49')});
 it('hashes and validates a canonical local source without writing the DB',async()=>{const path=await source();const rows=await validateStageManifest([{syllabusCode:'9618',year:2025,series:'MJ',paperCode:11,kind:'QP',path}]);expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({component:1,variant:1,absolutePath:path});expect(rows[0]!.sha256).toHaveLength(64)});
 it('rejects duplicate canonical manifest keys and tiny files',async()=>{const path=await source();const item={syllabusCode:'9618'as const,year:2025,series:'MJ'as const,paperCode:11,kind:'QP'as const,path};await expect(validateStageManifest([item,item])).rejects.toThrow('duplicate_manifest_key');const tiny=await source(20);await expect(validateStageManifest([{...item,path:tiny}])).rejects.toThrow('invalid_source_file')});
 it('registers validated new sources atomically with the active syllabus component',async()=>{const path=await source();const query=vi.fn(async(sql:string)=>{if(sql==='begin'||sql==='commit'||sql==='rollback')return{rowCount:null,rows:[]};if(sql.startsWith('select s.id syllabus_id'))return{rowCount:1,rows:[{syllabus_id:'s1',component_id:'c1'}]};if(sql.startsWith('select id,sha256 from source_papers'))return{rowCount:0,rows:[]};if(sql.startsWith('insert into source_papers'))return{rowCount:1,rows:[{id:'paper1'}]};throw new Error(`unexpected ${sql}`)});const client={query,release:vi.fn()}as unknown as PoolClient,pool={connect:vi.fn().mockResolvedValue(client)}as unknown as Pool;const result=await registerStagedSources(pool,[{syllabusCode:'9618',year:2025,series:'MJ',paperCode:11,kind:'QP',path}]);expect(result[0]).toMatchObject({key:'2025-MJ-11-QP',sourcePaperId:'paper1'});expect(query).toHaveBeenCalledWith('commit')});
 it('updates only the local path when the staged bytes are unchanged',async()=>{const path=await source(),validated=await validateStageManifest([{syllabusCode:'9618',year:2025,series:'MJ',paperCode:11,kind:'QP',path}]);const sha=validated[0]!.sha256;const query=vi.fn(async(sql:string)=>{if(sql==='begin'||sql==='commit'||sql==='rollback')return{rowCount:null,rows:[]};if(sql.startsWith('select s.id syllabus_id'))return{rowCount:1,rows:[{syllabus_id:'s1',component_id:'c1'}]};if(sql.startsWith('select id,sha256 from source_papers'))return{rowCount:1,rows:[{id:'paper1',sha256:sha}]};if(sql.startsWith('update source_papers set storage_path=$2 where'))return{rowCount:1,rows:[{id:'paper1'}]};throw new Error(`unexpected ${sql}`)});const client={query,release:vi.fn()}as unknown as PoolClient,pool={connect:vi.fn().mockResolvedValue(client)}as unknown as Pool;await expect(registerStagedSources(pool,[{syllabusCode:'9618',year:2025,series:'MJ',paperCode:11,kind:'QP',path}])).resolves.toHaveLength(1);expect(query.mock.calls.some(([sql])=>String(sql).startsWith('select count(*)::int in_use'))).toBe(false)});
 it('refuses a changed source revision when existing questions are already in use',async()=>{const path=await source(2048,9);const query=vi.fn(async(sql:string)=>{if(sql==='begin'||sql==='commit'||sql==='rollback')return{rowCount:null,rows:[]};if(sql.startsWith('select s.id syllabus_id'))return{rowCount:1,rows:[{syllabus_id:'s1',component_id:'c1'}]};if(sql.startsWith('select id,sha256 from source_papers'))return{rowCount:1,rows:[{id:'paper-used',sha256:'old-sha'}]};if(sql.startsWith('select count(*)::int in_use'))return{rowCount:1,rows:[{in_use:3}]};throw new Error(`unexpected ${sql}`)});const client={query,release:vi.fn()}as unknown as PoolClient,pool={connect:vi.fn().mockResolvedValue(client)}as unknown as Pool;await expect(registerStagedSources(pool,[{syllabusCode:'9618',year:2025,series:'MJ',paperCode:11,kind:'QP',path}])).rejects.toThrow('source_paper_revision_required:paper-used:3');expect(query).toHaveBeenCalledWith('rollback');expect(query.mock.calls.some(([sql])=>String(sql).startsWith('update source_papers set storage_path=$2,sha256'))).toBe(false)});
});
