import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import{loadSyllabusCoverage}from'./syllabus-coverage.js';
const row=(overrides:Record<string,unknown>={})=>({id:'s1',code:'9618',subject:'Computer Science',version_label:'2021-2023',valid_from:2021,valid_to:2023,component_count:4,topic_count:20,subtopic_count:44,learning_objective_count:215,component_topic_count:22,component_learning_objective_count:237,...overrides});
function pool(rows:unknown[]){const query=vi.fn().mockResolvedValue({rowCount:rows.length,rows});return{value:{query}as unknown as Pool,query}}
describe('syllabus coverage auditor',()=>{
 it('reports complete historical versions as covered only for their exact exam years',async()=>{const p=pool([row(),row({id:'s2',version_label:'2024-2025',valid_from:2024,valid_to:2025,learning_objective_count:217,component_learning_objective_count:239})]);const result=await loadSyllabusCoverage(p.value,{yearFrom:2021,yearTo:2025});expect(result.ready).toBe(true);expect(result.years).toHaveLength(5);expect(result.years.every(item=>item.status==='covered')).toBe(true);expect(result.years[0]?.matches[0]?.title).toBe('Computer Science 2021-2023');expect(result.years[4]?.matches[0]?.title).toBe('Computer Science 2024-2025');const sql=String(p.query.mock.calls[0]?.[0]??'');expect(sql).toContain('s.subject,s.version_label');expect(sql).not.toContain('s.title');expect(sql).toContain('component_topics ct');expect(sql).toContain('component_learning_objectives clo')});
 it('reports missing years instead of falling through to a current syllabus',async()=>{const p=pool([row({valid_from:2026,valid_to:2028,version_label:'2026-2028'})]);const result=await loadSyllabusCoverage(p.value,{yearFrom:2025,yearTo:2026});expect(result.ready).toBe(false);expect(result.years).toEqual([expect.objectContaining({year:2025,status:'missing'}),expect.objectContaining({year:2026,status:'covered'})])});
 it('fails closed when two versions overlap in the same exam year',async()=>{const p=pool([row({id:'old',valid_from:2021,valid_to:2025}),row({id:'new',valid_from:2025,valid_to:2028,version_label:'2025-2028'})]);const result=await loadSyllabusCoverage(p.value,{yearFrom:2025,yearTo:2025});expect(result.ready).toBe(false);expect(result.years[0]).toMatchObject({status:'ambiguous',matches:expect.arrayContaining([expect.objectContaining({syllabusId:'old'}),expect.objectContaining({syllabusId:'new'})])})});
 it('requires the full 20/44 taxonomy and both component crosswalks for 9618',async()=>{for(const overrides of[{topic_count:19},{subtopic_count:43},{component_topic_count:20},{component_learning_objective_count:100}]){const p=pool([row(overrides)]);const result=await loadSyllabusCoverage(p.value,{yearFrom:2022,yearTo:2022});expect(result.ready).toBe(false);expect(result.years[0]).toMatchObject({status:'incomplete',message:expect.stringContaining('taxonomy/crosswalk is incomplete')})}});
 it('rejects invalid ranges before querying the database',async()=>{const p=pool([]);await expect(loadSyllabusCoverage(p.value,{yearFrom:2026,yearTo:2025})).rejects.toThrow('syllabus_coverage_year_range_invalid');expect(p.query).not.toHaveBeenCalled()});
});
