import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import{loadSyllabusCoverage}from'./syllabus-coverage.js';
const row=(overrides:Record<string,unknown>={})=>({id:'s1',code:'9618',title:'Cambridge 9618 2021-2025',valid_from:2021,valid_to:2025,component_count:4,topic_count:20,subtopic_count:44,learning_objective_count:120,...overrides});
const pool=(rows:unknown[])=>({query:vi.fn().mockResolvedValue({rowCount:rows.length,rows})}as unknown as Pool);
describe('syllabus coverage auditor',()=>{
 it('reports a fully populated historical version as covered for every requested year',async()=>{const result=await loadSyllabusCoverage(pool([row()]),{yearFrom:2021,yearTo:2025});expect(result.ready).toBe(true);expect(result.years).toHaveLength(5);expect(result.years.every(item=>item.status==='covered')).toBe(true);expect(result.years[4]).toMatchObject({year:2025,status:'covered'})});
 it('reports missing years instead of falling through to a current syllabus',async()=>{const result=await loadSyllabusCoverage(pool([row({valid_from:2026,valid_to:2028,title:'Cambridge 9618 2026-2028'})]),{yearFrom:2025,yearTo:2026});expect(result.ready).toBe(false);expect(result.years).toEqual([expect.objectContaining({year:2025,status:'missing'}),expect.objectContaining({year:2026,status:'covered'})])});
 it('fails closed when two versions overlap in the same exam year',async()=>{const result=await loadSyllabusCoverage(pool([row({id:'old',valid_from:2021,valid_to:2025}),row({id:'new',valid_from:2025,valid_to:2028,title:'New'})]),{yearFrom:2025,yearTo:2025});expect(result.ready).toBe(false);expect(result.years[0]).toMatchObject({status:'ambiguous',matches:expect.arrayContaining([expect.objectContaining({syllabusId:'old'}),expect.objectContaining({syllabusId:'new'})])})});
 it('reports a version with no populated taxonomy as incomplete',async()=>{const result=await loadSyllabusCoverage(pool([row({component_count:4,topic_count:0,subtopic_count:0,learning_objective_count:0})]),{yearFrom:2024,yearTo:2024});expect(result.ready).toBe(false);expect(result.years[0]).toMatchObject({status:'incomplete',message:expect.stringContaining('taxonomy is incomplete')})});
 it('rejects invalid ranges before querying the database',async()=>{const p=pool([]);await expect(loadSyllabusCoverage(p,{yearFrom:2026,yearTo:2025})).rejects.toThrow('syllabus_coverage_year_range_invalid');expect((p.query as ReturnType<typeof vi.fn>)).not.toHaveBeenCalled()});
});
