import type{Pool}from'pg';import type{Actor}from'../lib/actor.js';import{DomainError}from'./assignments-service.js';import{JobQueue}from'../jobs/job-queue.js';
export class IngestionService{constructor(private pool:Pool){}private owner(a:Actor){if(a.role!=='owner')throw new DomainError('owner_only',403)}
async register(a:Actor,input:{syllabusId:string;componentId:string;year:number;series:'MJ'|'ON'|'FM';variant:number;kind:'QP'|'MS'|'IN'|'ER'|'GT';storagePath:string;sha256:string}){this.owner(a);const c=await this.pool.connect();let run:any=null,committed=false;try{await c.query('begin');const paper=await c.query(`insert into source_papers(syllabus_id,component_id,year,series,variant,kind,storage_path,sha256,uploaded_by)values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(sha256)do update set storage_path=excluded.storage_path returning id,sha256`,[input.syllabusId,input.componentId,input.year,input.series,input.variant,input.kind,input.storagePath,input.sha256,a.id]);if(input.kind==='QP'||input.kind==='MS'){run=(await c.query(`insert into ingestion_runs(syllabus_id,component_id,year,series,variant,qp_paper_id,ms_paper_id)
values($1,$2,$3,$4,$5,case when $6='QP' then $7::uuid end,case when $6='MS' then $7::uuid end)
on conflict(component_id,year,series,variant)do update set qp_paper_id=coalesce(excluded.qp_paper_id,ingestion_runs.qp_paper_id),ms_paper_id=coalesce(excluded.ms_paper_id,ingestion_runs.ms_paper_id),updated_at=now()
returning id,qp_paper_id,ms_paper_id`,[input.syllabusId,input.componentId,input.year,input.series,input.variant,input.kind,paper.rows[0].id])).rows[0]}await c.query('commit');committed=true;if(run?.qp_paper_id&&run?.ms_paper_id){await new JobQueue(this.pool).enqueue({kind:'ingest-bundle',payload:{runId:run.id,qpPaperId:run.qp_paper_id,msPaperId:run.ms_paper_id},idempotencyKey:`ingest-run:${run.id}`,refTable:'ingestion_runs',refId:run.id});await this.pool.query(`update ingestion_runs set status='queued',updated_at=now() where id=$1 and status='waiting_for_pair'`,[run.id])}else if(!run)await new JobQueue(this.pool).enqueue({kind:'ingest-paper',payload:{paperId:paper.rows[0].id},idempotencyKey:`ingest:${input.sha256}`,refTable:'source_papers',refId:paper.rows[0].id});return{...paper.rows[0],ingestionRunId:run?.id??null,waitingForPair:Boolean(run&&(!run.qp_paper_id||!run.ms_paper_id))}}catch(e){if(!committed)await c.query('rollback');throw e}finally{c.release()}}
async jobs(a:Actor){this.owner(a);const r=await this.pool.query(`select j.id,j.kind,j.status,j.attempts,j.max_attempts,j.error,j.created_at,j.finished_at,sp.storage_path from jobs j left join source_papers sp on sp.id=j.ref_id where j.ref_table='source_papers' order by j.created_at desc limit 100`);return r.rows}
async review(a:Actor){this.owner(a);const r=await this.pool.query(`select q.id,q.display_ref,q.stem_md,q.marks,q.command_word,q.status,q.extract_confidence,sp.storage_path,coalesce(json_agg(json_build_object('code',vf.rule_code,'severity',vf.severity,'message',vf.message))filter(where vf.id is not null),'[]')findings from questions q join source_papers sp on sp.id=q.source_paper_id left join validation_findings vf on vf.ref_table='questions' and vf.ref_id=q.id and vf.resolved_at is null where q.status='needs_review' group by q.id,sp.id order by q.created_at limit 100`);return r.rows}
async decide(a:Actor,id:string,status:'approved'|'rejected'){this.owner(a);const r=await this.pool.query(`update questions set status=$2,reviewed_by=$3,reviewed_at=now(),updated_at=now() where id=$1 and status='needs_review' returning id,status`,[id,status,a.id]);if(!r.rowCount)throw new DomainError('not_found',404);return r.rows[0]}}
