import { randomInt } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import type { Actor } from '../lib/actor.js';
import { PgQuestionsRepository } from '../repositories/questions-repository.js';
import type { PortableQuestion } from './selection-review.js';
import { DomainError } from './assignments-service.js';
import { assertExpectedLiveExamVersion } from './live-exam-transition-guard.js';

export type LiveExamBuilderMarkingMode='teacher'|'peer'|'self';
export interface LiveExamBuilderSettings{
 questionOrder:'fixed'|'shuffled';timingMode:'teacher'|'per_question';defaultTimeLimitSeconds:number|null;
 allowLateJoin:boolean;autoCloseWhenAllSubmitted:boolean;peerMarkingEnabled:boolean;teacherOverrideEnabled:boolean;
 displayNameMode:'first_name'|'full_name'|'anonymous';
}
export const DEFAULT_LIVE_EXAM_BUILDER_SETTINGS:LiveExamBuilderSettings={
 questionOrder:'fixed',timingMode:'teacher',defaultTimeLimitSeconds:null,allowLateJoin:false,
 autoCloseWhenAllSubmitted:true,peerMarkingEnabled:true,teacherOverrideEnabled:true,displayNameMode:'first_name',
};
type Queryable=Pick<Pool,'query'>|PoolClient;
type DraftScope={id:string;classId:string;syllabusId:string;topicId:string;subtopicId:string|null;version:number};
type MarkSchemeSnapshot={id:string;schemeType:string;maxMarks:number;guidanceMd:string|null;points:Array<Record<string,unknown>>;groups:Array<Record<string,unknown>>};

function storedPortable(portable:PortableQuestion):PortableQuestion{return{
 ...portable,contextBlocks:portable.contextBlocks.map(block=>({...block,assets:block.assets.map(asset=>({...asset,url:null}))})),
};}
function firstString(value:unknown){return Array.isArray(value)&&typeof value[0]==='string'?value[0]:null;}
function normalizeSettings(patch?:Partial<LiveExamBuilderSettings>):LiveExamBuilderSettings{
 const merged={...DEFAULT_LIVE_EXAM_BUILDER_SETTINGS,...(patch??{})};
 if(merged.defaultTimeLimitSeconds!==null&&(!Number.isInteger(merged.defaultTimeLimitSeconds)||merged.defaultTimeLimitSeconds<30||merged.defaultTimeLimitSeconds>7200))throw new DomainError('live_builder_invalid_time_limit',400);
 return merged;
}

export class LiveExamBuilderService{
 private readonly questions:PgQuestionsRepository;
 constructor(private readonly pool:Pool,questions?:PgQuestionsRepository){this.questions=questions??new PgQuestionsRepository(pool);}
 private assertStaff(actor:Actor){if(actor.role==='student')throw new DomainError('staff_only',403);}
 private async controlledClasses(actor:Actor){this.assertStaff(actor);return this.pool.query(
  `select c.id,c.name,c.grade,c.level::text level,c.academic_year,c.syllabus_id,s.code syllabus_code,s.subject
   from classes c join syllabi s on s.id=c.syllabus_id where c.archived_at is null and (
    ($1='owner' and c.school_id=$2) or ($1='teacher' and (c.owner_id=$3 or exists(select 1 from class_teachers ct where ct.class_id=c.id and ct.teacher_id=$3)))
   ) order by c.academic_year desc,c.name`,[actor.role,actor.schoolId,actor.id]);}
 private async requireClassControl(executor:Queryable,actor:Actor,classId:string){this.assertStaff(actor);const r=await executor.query(
  `select c.id,c.syllabus_id,s.code syllabus_code from classes c join syllabi s on s.id=c.syllabus_id
   where c.id=$1 and c.archived_at is null and (($2='owner' and c.school_id=$3) or ($2='teacher' and (c.owner_id=$4 or exists(select 1 from class_teachers ct where ct.class_id=c.id and ct.teacher_id=$4))))`,
  [classId,actor.role,actor.schoolId,actor.id]);if(!r.rowCount)throw new DomainError('not_found',404);return{id:String(r.rows[0].id),syllabusId:String(r.rows[0].syllabus_id),syllabusCode:String(r.rows[0].syllabus_code)};}
 private async validateTaxonomy(executor:Queryable,syllabusId:string,topicId:string,subtopicId:string|null){const r=await executor.query(
  `select s.code syllabus_code,t.number topic_number,st.code subtopic_code from syllabi s join topics t on t.syllabus_id=s.id and t.id=$2
   left join subtopics st on st.topic_id=t.id and ($3::uuid is null or st.id=$3)
   where s.id=$1 and ($3::uuid is null or st.id is not null)`,[syllabusId,topicId,subtopicId]);if(!r.rowCount)throw new DomainError('live_builder_invalid_taxonomy',400);return r.rows[0];}
 private async lockDraft(client:PoolClient,actor:Actor,id:string):Promise<DraftScope>{this.assertStaff(actor);const r=await client.query(
  `select les.id,les.class_id,les.status::text,les.version,les.settings,c.syllabus_id from live_exam_sessions les join classes c on c.id=les.class_id
   where les.id=$1 and (($2='owner' and c.school_id=$3) or ($2='teacher' and (c.owner_id=$4 or exists(select 1 from class_teachers ct where ct.class_id=c.id and ct.teacher_id=$4)))) for update of les`,
  [id,actor.role,actor.schoolId,actor.id]);if(!r.rowCount)throw new DomainError('not_found',404);const row=r.rows[0];if(row.status!=='draft')throw new DomainError('live_invalid_state',409);
  const settings=row.settings&&typeof row.settings==='object'&&!Array.isArray(row.settings)?row.settings as Record<string,unknown>:{};const topicId=firstString(settings.topicIds);if(!topicId)throw new DomainError('live_builder_invalid_taxonomy',409);
  return{id:String(row.id),classId:String(row.class_id),syllabusId:String(row.syllabus_id),topicId,subtopicId:firstString(settings.subtopicIds),version:Number(row.version)};}
 private async bump(client:PoolClient,id:string,actorId:string,eventType:string,payload:Record<string,unknown>={}){const changed=await client.query(`update live_exam_sessions set version=version+1,updated_at=now() where id=$1 returning version`,[id]);const version=Number(changed.rows[0].version);await client.query(`insert into live_exam_events(session_id,actor_id,event_type,session_version,payload) values($1,$2,$3,$4,$5::jsonb)`,[id,actorId,eventType,version,JSON.stringify(payload)]);return version;}
 private async markScheme(executor:Queryable,questionId:string):Promise<MarkSchemeSnapshot>{const r=await executor.query(
  `select jsonb_build_object('id',ms.id,'schemeType',ms.scheme_type,'maxMarks',ms.max_marks,'guidanceMd',ms.guidance_md,
   'points',coalesce((select jsonb_agg(jsonb_build_object('id',msp.id,'code',msp.code,'text',msp.text,'marks',msp.marks,'accept',msp.accept,'reject',msp.reject,'requires',msp.requires,'isBod',msp.is_bod,'groupId',msp.group_id) order by msp.sort_order,msp.id) from mark_scheme_points msp where msp.mark_scheme_id=ms.id),'[]'::jsonb),
   'groups',coalesce((select jsonb_agg(jsonb_build_object('id',msg.id,'label',msg.label,'nRequired',msg.n_required,'marksPerPoint',msg.marks_per_point,'maxMarks',msg.max_marks,'awardMode',msg.award_mode) order by msg.sort_order,msg.id) from mark_scheme_groups msg where msg.mark_scheme_id=ms.id),'[]'::jsonb)) scheme
   from mark_schemes ms where ms.question_id=$1 and ms.status='approved'`,[questionId]);if(!r.rows[0]?.scheme)throw new DomainError('live_question_not_ready',409);return r.rows[0].scheme as MarkSchemeSnapshot;}
 private async eligibleRows(executor:Queryable,input:{syllabusId:string;topicId:string;subtopicId:string|null;ids?:string[];limit:number;seed?:string}){const t=await this.validateTaxonomy(executor,input.syllabusId,input.topicId,input.subtopicId);const values:unknown[]=[t.syllabus_code,t.topic_number,t.subtopic_code,input.syllabusId];const conditions=[`q.status='approved'`,`q.marks>0`,`q.parent_id is not null`,`ms.status='approved'`,`not exists(select 1 from question_dependencies qd where qd.question_id=q.id)`,`source_syllabus.code=$1`,
  `exists(select 1 from question_subtopics qst join subtopics mst on mst.id=qst.subtopic_id join topics mt on mt.id=mst.topic_id join syllabi msy on msy.id=mt.syllabus_id where qst.question_id=q.id and msy.code=$1 and mt.number=$2 and ($3::text is null or mst.code=$3))`,
  `exists(select 1 from question_learning_objectives qlo join learning_objectives slo on slo.id=qlo.lo_id join subtopics sst on sst.id=slo.subtopic_id join topics st on st.id=sst.topic_id where qlo.question_id=q.id and (st.syllabus_id=$4::uuid or exists(select 1 from learning_objective_compatibility compat join learning_objectives tlo on tlo.id=compat.target_lo_id join subtopics tst on tst.id=tlo.subtopic_id join topics tt on tt.id=tst.topic_id where compat.source_lo_id=qlo.lo_id and compat.relation in('equivalent','subtopic_compatible') and tt.syllabus_id=$4::uuid)))`];
  if(input.ids){values.push(input.ids);conditions.push(`q.id=any($${values.length}::uuid[])`);}let order=`sp.year desc,sp.series,c.number,sp.variant,q.display_ref`;if(input.seed){values.push(input.seed);order=`md5(q.id::text || $${values.length}::text),${order}`;}values.push(input.limit);
  return (await executor.query(`select distinct q.id,q.display_ref,q.stem_md,q.command_word::text command_word,q.marks,q.answer_kind::text answer_kind,q.ao::text ao,sp.year,sp.series::text series,sp.variant,c.number component from questions q join mark_schemes ms on ms.question_id=q.id join source_papers sp on sp.id=q.source_paper_id join syllabi source_syllabus on source_syllabus.id=sp.syllabus_id join components c on c.id=q.component_id where ${conditions.join(' and ')} order by ${order} limit $${values.length}`,values)).rows;}
 private async snapshotQuestion(actor:Actor,executor:Queryable,questionId:string){const [portable,scheme]=await Promise.all([this.questions.portable(actor,questionId),this.markScheme(executor,questionId)]);if(!portable)throw new DomainError('live_question_not_ready',409);if(portable.contextBlocks.some(block=>block.assets.some(asset=>!asset.contentMd&&!asset.storagePath&&!asset.url)))throw new DomainError('live_assets_unavailable',409);return{portable:storedPortable(portable),scheme};}

 async builderOptions(actor:Actor,syllabusId?:string){const classes=await this.controlledClasses(actor);const ids=[...new Set(classes.rows.map(r=>String(r.syllabus_id)))];const selected=syllabusId??ids[0]??null;if(syllabusId&&!ids.includes(syllabusId))throw new DomainError('not_found',404);const taxonomy=selected?await this.pool.query(`select t.id topic_id,t.number topic_number,t.title topic_title,st.id subtopic_id,st.code subtopic_code,st.title subtopic_title from topics t left join subtopics st on st.topic_id=t.id where t.syllabus_id=$1 order by t.sort_order,t.number,st.sort_order,st.code`,[selected]):{rows:[] as Record<string,unknown>[]};const syllabi=[...new Map(classes.rows.map(r=>[String(r.syllabus_id),{id:String(r.syllabus_id),code:String(r.syllabus_code),subject:String(r.subject)}])).values()];const topics=new Map<string,{id:string;number:number;title:string;subtopics:Array<{id:string;code:string;title:string}>}>();for(const r of taxonomy.rows){const id=String(r.topic_id);if(!topics.has(id))topics.set(id,{id,number:Number(r.topic_number),title:String(r.topic_title),subtopics:[]});if(r.subtopic_id)topics.get(id)!.subtopics.push({id:String(r.subtopic_id),code:String(r.subtopic_code),title:String(r.subtopic_title)});}return{syllabi,selectedSyllabusId:selected,topics:[...topics.values()],classes:classes.rows.map(r=>({id:String(r.id),name:String(r.name),grade:r.grade,level:r.level,academicYear:r.academic_year,syllabusId:String(r.syllabus_id),syllabusCode:String(r.syllabus_code)})),defaultSettings:DEFAULT_LIVE_EXAM_BUILDER_SETTINGS};}
 async eligibleQuestions(actor:Actor,input:{syllabusId:string;topicId:string;subtopicId?:string;limit:number}){const classes=await this.controlledClasses(actor);if(!classes.rows.some(r=>String(r.syllabus_id)===input.syllabusId))throw new DomainError('not_found',404);const rows=await this.eligibleRows(this.pool,{syllabusId:input.syllabusId,topicId:input.topicId,subtopicId:input.subtopicId??null,limit:input.limit});return rows.map(r=>({id:String(r.id),displayRef:String(r.display_ref),stem:r.stem_md,commandWord:r.command_word,marks:Number(r.marks),answerKind:r.answer_kind,ao:r.ao,year:Number(r.year),series:r.series,variant:Number(r.variant),component:Number(r.component)}));}
 async createDraft(actor:Actor,input:{classId:string;title:string;topicId:string;subtopicId?:string;markingMode:LiveExamBuilderMarkingMode;settings?:Partial<LiveExamBuilderSettings>}){const client=await this.pool.connect();try{await client.query('begin');const controlled=await this.requireClassControl(client,actor,input.classId);await this.validateTaxonomy(client,controlled.syllabusId,input.topicId,input.subtopicId??null);const settings=normalizeSettings(input.settings);const stored={topicIds:[input.topicId],subtopicIds:input.subtopicId?[input.subtopicId]:[],...settings};const created=await client.query(`insert into live_exam_sessions(class_id,host_id,title,join_code,status,marking_mode,question_time_limit_s,settings) values($1,$2,$3,null,'draft',$4,$5,$6::jsonb) returning id,class_id,title,status::text,marking_mode::text,version,created_at`,[input.classId,actor.id,input.title,input.markingMode,settings.defaultTimeLimitSeconds,JSON.stringify(stored)]);const row=created.rows[0];await client.query(`insert into live_exam_events(session_id,actor_id,event_type,session_version,payload) values($1,$2,'draft.created',1,$3::jsonb)`,[row.id,actor.id,JSON.stringify({topicId:input.topicId,subtopicId:input.subtopicId??null})]);await client.query('commit');return{id:String(row.id),classId:String(row.class_id),title:String(row.title),status:String(row.status),markingMode:String(row.marking_mode),version:Number(row.version),questionCount:0,settings,createdAt:row.created_at};}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
 async draft(actor:Actor,id:string){this.assertStaff(actor);const r=await this.pool.query(`select les.id,les.class_id,les.title,les.status::text,les.marking_mode::text,les.version,les.settings,c.name class_name,c.syllabus_id,s.code syllabus_code from live_exam_sessions les join classes c on c.id=les.class_id join syllabi s on s.id=c.syllabus_id where les.id=$1 and les.status='draft' and (($2='owner' and c.school_id=$3) or ($2='teacher' and (c.owner_id=$4 or exists(select 1 from class_teachers ct where ct.class_id=c.id and ct.teacher_id=$4))))`,[id,actor.role,actor.schoolId,actor.id]);if(!r.rowCount)throw new DomainError('not_found',404);const qs=await this.pool.query(`select leq.question_id,leq.position,leq.marks,coalesce(leq.question_snapshot->>'sourceRef',leq.question_snapshot->'leaf'->>'displayRef','') display_ref from live_exam_questions leq where leq.session_id=$1 order by leq.position`,[id]);const row=r.rows[0];return{id:String(row.id),classId:String(row.class_id),className:String(row.class_name),syllabusId:String(row.syllabus_id),syllabusCode:String(row.syllabus_code),title:String(row.title),status:String(row.status),markingMode:String(row.marking_mode),version:Number(row.version),settings:row.settings,questions:qs.rows.map(q=>({id:String(q.question_id),position:Number(q.position),marks:Number(q.marks),displayRef:String(q.display_ref)}))};}
 private async replaceQuestionsLocked(client:PoolClient,actor:Actor,draft:DraftScope,questionIds:string[]){const unique=[...new Set(questionIds)];if(unique.length!==questionIds.length)throw new DomainError('live_builder_duplicate_question',400);if(unique.length>20)throw new DomainError('live_builder_question_limit',400);if(!unique.length){await client.query('delete from live_exam_questions where session_id=$1',[draft.id]);return 0;}const eligible=await this.eligibleRows(client,{syllabusId:draft.syllabusId,topicId:draft.topicId,subtopicId:draft.subtopicId,ids:unique,limit:unique.length});const allowed=new Set(eligible.map(r=>String(r.id)));if(allowed.size!==unique.length||unique.some(id=>!allowed.has(id)))throw new DomainError('live_builder_questions_ineligible',409);const snapshots=await Promise.all(unique.map(async questionId=>({questionId,...await this.snapshotQuestion(actor,client,questionId)})));await client.query('delete from live_exam_questions where session_id=$1',[draft.id]);for(const [position,s] of snapshots.entries())await client.query(`insert into live_exam_questions(session_id,question_id,position,marks,question_snapshot,mark_scheme_snapshot) values($1,$2,$3,$4,$5::jsonb,$6::jsonb)`,[draft.id,s.questionId,position,s.portable.leaf.marks,JSON.stringify(s.portable),JSON.stringify(s.scheme)]);return snapshots.length;}
 async replaceQuestions(actor:Actor,id:string,questionIds:string[],expectedVersion:number){const client=await this.pool.connect();try{await client.query('begin');const draft=await this.lockDraft(client,actor,id);assertExpectedLiveExamVersion(draft,expectedVersion);const questionCount=await this.replaceQuestionsLocked(client,actor,draft,questionIds);const version=await this.bump(client,id,actor.id,'draft.questions_replaced',{questionCount,selectionMode:'manual'});await client.query('commit');return{id,status:'draft' as const,questionCount,selectionMode:'manual' as const,version};}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
 async autoSelect(actor:Actor,id:string,count:number,expectedVersion:number){const client=await this.pool.connect();try{await client.query('begin');const draft=await this.lockDraft(client,actor,id);assertExpectedLiveExamVersion(draft,expectedVersion);const rows=await this.eligibleRows(client,{syllabusId:draft.syllabusId,topicId:draft.topicId,subtopicId:draft.subtopicId,limit:count,seed:id});if(rows.length<count)throw new DomainError('live_question_pool_small',409);const questionIds=rows.map(r=>String(r.id));const questionCount=await this.replaceQuestionsLocked(client,actor,draft,questionIds);const version=await this.bump(client,id,actor.id,'draft.questions_replaced',{questionCount,selectionMode:'auto'});await client.query('commit');return{id,status:'draft' as const,questionCount,selectionMode:'auto' as const,questionIds,version};}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
 async publish(actor:Actor,id:string,expectedVersion:number){const client=await this.pool.connect();try{await client.query('begin');const draft=await this.lockDraft(client,actor,id);assertExpectedLiveExamVersion(draft,expectedVersion);const selected=await client.query(`select question_id,position from live_exam_questions where session_id=$1 order by position`,[id]);if(!selected.rowCount)throw new DomainError('live_builder_questions_required',409);const questionIds=selected.rows.map(r=>String(r.question_id));const eligible=await this.eligibleRows(client,{syllabusId:draft.syllabusId,topicId:draft.topicId,subtopicId:draft.subtopicId,ids:questionIds,limit:questionIds.length});const allowed=new Set(eligible.map(r=>String(r.id)));if(allowed.size!==questionIds.length||questionIds.some(q=>!allowed.has(q)))throw new DomainError('live_builder_questions_ineligible',409);for(const row of selected.rows){const questionId=String(row.question_id);const snapshot=await this.snapshotQuestion(actor,client,questionId);await client.query(`update live_exam_questions set marks=$3,question_snapshot=$4::jsonb,mark_scheme_snapshot=$5::jsonb where session_id=$1 and question_id=$2`,[id,questionId,snapshot.portable.leaf.marks,JSON.stringify(snapshot.portable),JSON.stringify(snapshot.scheme)]);}let joinCode:string|null=null;for(let attempt=0;attempt<8;attempt+=1){const candidate=String(randomInt(100000,1000000));await client.query('savepoint live_publish_code');try{const updated=await client.query(`update live_exam_sessions set status='published',join_code=$2,published_at=coalesce(published_at,now()),updated_at=now() where id=$1 and status='draft' returning join_code`,[id,candidate]);if(!updated.rowCount)throw new DomainError('live_invalid_state',409);joinCode=String(updated.rows[0].join_code);await client.query('release savepoint live_publish_code');break;}catch(error){await client.query('rollback to savepoint live_publish_code');if(typeof error==='object'&&error&&'code'in error&&error.code==='23505')continue;throw error;}}if(!joinCode)throw new DomainError('live_join_code_conflict',409);const version=await this.bump(client,id,actor.id,'challenge.published',{questionCount:questionIds.length});await client.query('commit');return{id,status:'published' as const,joinCode,questionCount:questionIds.length,version};}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
}
