const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export interface ExportQuestion{displayRef:string;stem:string;context?:string;marks:number;points?:Array<{code:string;text:string;marks:number}>}

export function renderPaperHtml(title:string,questions:ExportQuestion[],includeScheme=false,watermark?:string){
  const total=questions.reduce((sum,question)=>sum+question.marks,0);
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    @page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#111;font-size:11pt}
    h1{font-size:18pt;border-bottom:2px solid #111;padding-bottom:8px}.meta{display:flex;justify-content:space-between}
    .question{break-inside:avoid;margin:18px 0}.ref{font-weight:bold}.marks{float:right}.context{white-space:pre-wrap}
    .scheme{margin:8px 0 0 24px}.scheme li{margin:5px 0}footer{position:fixed;bottom:0;font-size:9pt}
    .watermark{position:fixed;inset:45% 0 auto;z-index:-1;text-align:center;transform:rotate(-28deg);font-size:34pt;font-weight:bold;color:rgba(50,50,50,.08);white-space:nowrap}
  </style></head><body>${watermark?`<div class="watermark">${esc(watermark)}</div>`:''}
  <h1>${esc(title)}</h1><div class="meta"><span>Cambridge International AS & A Level Computer Science</span><strong>Total: ${total}</strong></div>
  ${questions.map(question=>`<section class="question"><div><span class="ref">${esc(question.displayRef)}</span><span class="marks">[${question.marks}]</span></div>${question.context?`<p class="context">${esc(question.context)}</p>`:''}<p>${esc(question.stem)}</p>${includeScheme?`<ol class="scheme">${(question.points??[]).map(point=>`<li>${esc(point.code)} ${esc(point.text)} [${point.marks}]</li>`).join('')}</ol>`:''}</section>`).join('')}
  <footer>${watermark?esc(watermark):'Generated by CamPath'}</footer></body></html>`;
}
