import{describe,expect,it}from'vitest';import{assertPaperTotal,assertPortableAssetCoverage,renderPaperHtml}from'./export-html.js';
describe('paper HTML',()=>{
  it('shows total marks',()=>expect(renderPaperHtml('Test',[{displayRef:'Q1',stem:'A',marks:2},{displayRef:'Q2',stem:'B',marks:3}])).toContain('Total: 5'));
  it('excludes context-only items from the authoritative total',()=>{const q=[{displayRef:'Q1',stem:'A',marks:2,role:'graded' as const},{displayRef:'Q1(b)',stem:'Printed support',marks:0,role:'context_only' as const}];expect(assertPaperTotal(q,2)).toBe(2);expect(renderPaperHtml('T',q)).toContain('Total: 2')});
  it('rejects an export whose questions do not match the authoritative total',()=>{expect(assertPaperTotal([{displayRef:'Q1',stem:'A',marks:2}],2)).toBe(2);expect(()=>assertPaperTotal([{displayRef:'Q1',stem:'A',marks:2}],3)).toThrow('export_total_mismatch:2/3')});
  it('keeps question in a non-breaking section',()=>expect(renderPaperHtml('T',[{displayRef:'Q1',stem:'A',marks:1}])).toContain('break-inside:avoid'));
  it('escapes untrusted text',()=>expect(renderPaperHtml('<script>',[{displayRef:'Q',stem:'<img>',marks:1}])).not.toContain('<script>'));
  it('includes scheme only for graded questions when requested',()=>{const q=[{displayRef:'Q',stem:'A',marks:1,role:'graded' as const,points:[{code:'MP1',text:'Point',marks:1}]},{displayRef:'Q2',stem:'Context',marks:0,role:'context_only' as const,points:[{code:'BAD',text:'Must not render',marks:1}]}];const withScheme=renderPaperHtml('T',q,true);expect(withScheme).toContain('MP1');expect(withScheme).not.toContain('BAD');expect(renderPaperHtml('T',q,false)).not.toContain('MP1')});
  it('renders fresh refs, original source refs and portable text assets',()=>{const html=renderPaperHtml('T',[{displayRef:'Q1(a)',sourceRef:'9618/11/M/J/23 Q3(b)(i)',stem:'Explain.',marks:3,contextBlocks:[{displayRef:'Q3',context:'Shared scenario',assets:[{kind:'table',altText:'Customers table',contentMd:'| id | name |'}]}]}]);expect(html).toContain('Q1(a)');expect(html).toContain('9618/11/M/J/23 Q3(b)(i)');expect(html).toContain('Shared scenario');expect(html).toContain('Customers table');expect(html).toContain('| id | name |')});
  it('renders SVG content as an image rather than escaped source code',()=>{const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 50"><rect width="100" height="50"/></svg>';const html=renderPaperHtml('T',[{displayRef:'Q1',stem:'Use diagram.',marks:2,contextBlocks:[{assets:[{kind:'diagram',altText:'Logic diagram',contentMd:svg}]}]}]);expect(html).toContain('class="asset-image"');expect(html).toContain('data:image/svg+xml;base64,');expect(html).not.toContain('&lt;svg xmlns=')});
  it('renders context-only items as context rather than zero-mark questions',()=>{const html=renderPaperHtml('T',[{displayRef:'Q1(a)',sourceRef:'old Q3(a)',stem:'Printed prerequisite.',marks:0,role:'context_only'}]);expect(html).toContain('context-only');expect(html).toContain('Context');expect(html).not.toContain('[0]')});
  it('refuses to silently omit a storage-only asset',()=>{const q=[{displayRef:'Q1',sourceRef:'old Q1',stem:'Use the diagram.',marks:2,contextBlocks:[{assets:[{kind:'diagram',storagePath:'private/diagram.png',altText:'Network diagram'}]}]}];expect(()=>assertPortableAssetCoverage(q)).toThrow('export_asset_unavailable:old Q1:Network diagram');expect(()=>renderPaperHtml('T',q)).toThrow('export_asset_unavailable')});
  it('prints and escapes the internal-use watermark',()=>{const html=renderPaperHtml('T',[{displayRef:'Q',stem:'A',marks:1}],false,'School <One> · 2026-08-14 · Ichki foydalanish uchun');expect(html).toContain('class="watermark"');expect(html).toContain('Ichki foydalanish uchun');expect(html).not.toContain('School <One>')});
  it('separates pseudocode and the final task in exported question papers',()=>{const stem='Data types can be defined using pseudocode.\nTYPE LibraryRecord\nDECLARE Title : STRING\nDECLARE NumberOfCopies : INTEGER\nENDTYPE\nThe value for NumberOfCopies must be between 1 and 10 inclusive.\nWrite the updated line of pseudocode to implement the change.';const html=renderPaperHtml('T',[{displayRef:'Q1',stem,marks:1}]);expect(html).toContain('class="stem-code"');expect(html).toContain('TYPE LibraryRecord\nDECLARE Title : STRING');expect(html).toContain('class="stem-task"');expect(html).toContain('TASK');});
});
