import{describe,expect,it}from'vitest';import{buildDocx}from'./export-docx.js';import{assertPaperTotal,renderPaperHtml,type ExportQuestion}from'./export-html.js';

describe('Question Bank PDF/Word milestone matrix',()=>{
  it('renders text, pseudocode and a real matching table without changing marks',()=>{const questions:ExportQuestion[]=[
    {displayRef:'Q1',sourceRef:'9618/11/M/J/23 Q1(a)',stem:'Explain virtual memory.',marks:3,answerLines:5},
    {displayRef:'Q2',sourceRef:'9618/22/O/N/24 Q7(b)',stem:'Complete the algorithm.',marks:4,contextBlocks:[{assets:[{kind:'pseudocode',contentMd:'FOR i ← 1 TO 3\n  OUTPUT i\nNEXT i'}]}]},
    {displayRef:'Q3',sourceRef:'9618/11/M/J/21 Q2(a)',stem:'Draw one line from each utility software to its correct description.',marks:4,contextBlocks:[{assets:[{kind:'diagram',storagePath:'supabase://question-assets/q2a.png',altText:'Utility matching options',contentMd:'| Utility software | Description |\n| --- | --- |\n| Disk formatter | Scans software for errors and repairs the problems |\n| Defragmentation | Moves parts of files so that each file is contiguous in memory |'}]}]},
  ];expect(assertPaperTotal(questions,11)).toBe(11);const pdf=renderPaperHtml('Mixed practice',questions,'question_paper');expect(pdf).toContain('<table>');expect(pdf).toContain('FOR i ← 1 TO 3');expect(pdf).toContain('Name:');const word=buildDocx('Mixed practice',questions,'question_paper').toString('utf8');expect(word).toContain('<w:tbl>');expect(word).toContain('Courier New');expect(word).toContain('9618/11/M/J/21 Q2(a)')});

  it('handles a 21-question worksheet with exact total and stable fresh refs',()=>{const questions:ExportQuestion[]=Array.from({length:21},(_,index)=>({displayRef:`Q${index+1}`,sourceRef:`9618/1${(index%3)+1}/M/J/23 Q${(index%8)+1}`,stem:`Practice question ${index+1}`,marks:(index%4)+1,answerLines:2}));const expected=questions.reduce((sum,q)=>sum+q.marks,0);expect(assertPaperTotal(questions,expected)).toBe(expected);const pdf=renderPaperHtml('Long worksheet',questions,'question_paper');expect(pdf).toContain(`Total: ${expected}`);expect(pdf).toContain('Q21');const docx=buildDocx('Long worksheet',questions,'question_paper');expect(docx.subarray(0,2).toString()).toBe('PK');expect(docx.toString('utf8')).toContain('Q21')});

  it('keeps combined and mark-scheme-only outputs semantically separate',()=>{const questions:ExportQuestion[]=[{displayRef:'Q1',sourceRef:'9618/12/M/J/23 Q4(c)',stem:'Describe two benefits.',marks:2,points:[{code:'MP1',text:'Benefit one',marks:1},{code:'MP2',text:'Benefit two',marks:1}]}];const combined=renderPaperHtml('Practice',questions,'combined'),scheme=renderPaperHtml('Practice',questions,'mark_scheme');expect(combined).toContain('Describe two benefits.');expect(combined).toContain('MP1');expect(scheme).toContain('Mark Scheme');expect(scheme).toContain('MP2');expect(scheme).not.toContain('Describe two benefits.');const wordScheme=buildDocx('Practice',questions,'mark_scheme').toString('utf8');expect(wordScheme).toContain('MP1');expect(wordScheme).not.toContain('Describe two benefits.')});

  it('fails closed rather than dropping an unavailable visual',()=>{const questions:ExportQuestion[]=[{displayRef:'Q1',sourceRef:'source Q1',stem:'Use the diagram.',marks:2,contextBlocks:[{assets:[{kind:'diagram',storagePath:'supabase://question-assets/missing.png',altText:'Required diagram'}]}]}];expect(()=>renderPaperHtml('T',questions)).toThrow('export_asset_unavailable');expect(()=>buildDocx('T',questions)).toThrow('export_asset_unavailable')});
});
