import express from'express';import request from'supertest';import{describe,expect,it,vi}from'vitest';import type{PgSelectionsRepository}from'../repositories/selections-repository.js';import type{SelectionAssignmentService}from'../services/selection-assignment-service.js';import{createSelectionsRouter}from'./selections.js';
const selectionId='11111111-1111-4111-8111-111111111111',classId='22222222-2222-4222-8222-222222222222';
const teacher={id:'teacher',role:'teacher'as const,schoolId:'school',fullName:'Teacher'},student={id:'student',role:'student'as const,schoolId:'school',fullName:'Student'};
function appFor(actor:typeof teacher|typeof student,create=vi.fn().mockResolvedValue({id:'assignment-1'})){const app=express();app.use(express.json());app.use((req,_res,next)=>{req.actor=actor;next()});app.use('/selections',createSelectionsRouter({}as PgSelectionsRepository,{create}as unknown as SelectionAssignmentService));return{app,create}}
describe('selection assignment route',()=>{
 it('blocks students before the handoff service is called',async()=>{const{app,create}=appFor(student);await request(app).post(`/selections/${selectionId}/assignment`).send({classId,title:'Revision'}).expect(403);expect(create).not.toHaveBeenCalled()});
 it('parses a staff handoff and defaults to an unpublished online assignment',async()=>{const{app,create}=appFor(teacher);const response=await request(app).post(`/selections/${selectionId}/assignment`).send({classId,title:'Revision'}).expect(201);expect(response.body).toEqual({id:'assignment-1'});expect(create).toHaveBeenCalledWith(teacher,selectionId,{classId,title:'Revision',mode:'online',publish:false})});
 it('passes explicit PDF options without publishing student submissions',async()=>{const{app,create}=appFor(teacher);await request(app).post(`/selections/${selectionId}/assignment`).send({classId,title:'Worksheet',mode:'pdf',publish:false,instructions:'Use black ink.'}).expect(201);expect(create).toHaveBeenCalledWith(teacher,selectionId,{classId,title:'Worksheet',mode:'pdf',publish:false,instructions:'Use black ink.'})});
 it('returns 503 when handoff wiring is unavailable',async()=>{const app=express();app.use(express.json());app.use((req,_res,next)=>{req.actor=teacher;next()});app.use('/selections',createSelectionsRouter({}as PgSelectionsRepository));await request(app).post(`/selections/${selectionId}/assignment`).send({classId,title:'Revision'}).expect(503)});
});
