-- Source-backed C1 normalization for explicit section caps and linked Cambridge mark points.
-- One-point/no-group manual wrappers only; usage-gated. Expansion points preserve dependencies.

create temp table t59(year int,series text,component int,variant int,path text,expected_marks int,family text) on commit drop;
insert into t59 values
(2021,'ON',1,2,'5.b.i',4,'bitmapdiff'),(2021,'ON',1,2,'5.b.ii',4,'imagemethods'),(2021,'ON',1,2,'8.a.i',4,'registers'),
(2023,'ON',1,1,'5.c.ii',5,'multicore'),(2023,'ON',1,1,'8.b.ii',2,'addrcompare'),(2023,'ON',1,3,'5.a',4,'idefeatures'),
(2024,'ON',1,1,'3.d.i',4,'optical'),(2024,'ON',1,2,'5.a',4,'ethics');
create temp table g59(family text,label text,n_required int,marks_per_point int,max_marks int,award_mode text,sort_order int) on commit drop;
insert into g59 values
('bitmapdiff','representation',2,1,2,'fixed',1),('bitmapdiff','scaling',2,1,2,'fixed',2),('bitmapdiff','filesize',2,1,2,'fixed',3),('bitmapdiff','compression',2,1,2,'fixed',4),
('imagemethods','bit_depth',2,1,2,'fixed',1),('imagemethods','palette',2,1,2,'fixed',2),('imagemethods','resolution',2,1,2,'fixed',3),
('registers','MAR',2,1,2,'fixed',1),('registers','MDR',2,1,2,'fixed',2),('multicore','limitations',5,1,5,'fixed',1),
('idefeatures','context_prompt',2,1,2,'fixed',1),('idefeatures','single_step',2,1,2,'fixed',2),('optical','process',4,1,4,'fixed',1),
('ethics','colleagues',2,1,2,'fixed',1),('ethics','public',2,1,2,'fixed',2);
create temp table p59(family text,code text,txt text,gl text,marks int,requires jsonb,sort_order int) on commit drop;
insert into p59 values
('bitmapdiff','REP_B','Bitmap is made up of pixels / stores colours for individual pixels.','representation',1,'[]',1),('bitmapdiff','REP_V','Vector graphic stores instructions for drawing shapes.','representation',1,'[]',2),('bitmapdiff','SCALE_B','When enlarged, bitmap pixels get bigger and the image pixelates.','scaling',1,'[]',3),('bitmapdiff','SCALE_V','When enlarged, vector graphics are recalculated and do not pixelate.','scaling',1,'[]',4),('bitmapdiff','SIZE_B','Bitmap files are usually larger because data is stored for individual pixels.','filesize',1,'[]',5),('bitmapdiff','SIZE_V','Vector graphics are smaller because they primarily store drawing instructions.','filesize',1,'[]',6),('bitmapdiff','COMP_B','Bitmap images can be compressed with significant reduction in file size.','compression',1,'[]',7),('bitmapdiff','COMP_V','Vector graphics do not compress well because they contain little redundant data.','compression',1,'[]',8),
('imagemethods','BD','Reduce bit depth.','bit_depth',1,'[]',1),('imagemethods','BDX','Reducing bit depth means fewer bits are stored per colour/pixel.','bit_depth',1,'["BD"]',2),('imagemethods','PAL','Reduce the colour palette / number of colours.','palette',1,'[]',3),('imagemethods','PALX','Fewer colours require fewer bits to store each colour.','palette',1,'["PAL"]',4),('imagemethods','RES','Reduce image resolution.','resolution',1,'[]',5),('imagemethods','RESX','Fewer pixels per unit measurement means less binary data to store.','resolution',1,'["RES"]',6),
('registers','MAR1','MAR stores the next address to be fetched.','MAR',1,'[]',1),('registers','MAR2','That next address is held in the Program Counter (PC).','MAR',1,'["MAR1"]',2),('registers','MAR3','The data at the address in MAR is then fetched.','MAR',1,'[]',3),('registers','MDR1','MDR stores data from the address pointed to by MAR.','MDR',1,'[]',4),('registers','MDR2','The data in MDR is copied to the Current Instruction Register (CIR).','MDR',1,'[]',5),
('multicore','O1','Multiple cores introduce additional overheads.','limitations',1,'[]',1),('multicore','O2','The overhead is caused by communication between cores.','limitations',1,'["O1"]',2),('multicore','S1','Software may not be designed to use multiple cores.','limitations',1,'[]',3),('multicore','S2','Consequently one of the cores may be left idle.','limitations',1,'["S1"]',4),('multicore','M1','Memory access speed may not match the speed of the cores.','limitations',1,'[]',5),('multicore','M2','The memory-speed mismatch can cause delay.','limitations',1,'["M1"]',6),('multicore','D1','The two computers may differ in ways other than the number of cores.','limitations',1,'[]',7),('multicore','D2','One computer may have more RAM, allowing faster multitasking.','limitations',1,'["D1"]',8),('multicore','D3','One computer may have a GPU.','limitations',1,'["D1"]',9),
('addrcompare','SIM','Both direct and indexed addressing load the contents of an address into the Accumulator.',null,1,'[]',1),('addrcompare','DIFF','Direct addressing accesses the operand address; indexed addressing adds IX to the operand and accesses the calculated address.',null,1,'[]',2),
('idefeatures','CP1','Context-sensitive prompts operate while code is being written.','context_prompt',1,'[]',1),('idefeatures','CP2','They show options that can complete the current statement.','context_prompt',1,'["CP1"]',2),('idefeatures','SS1','Single stepping executes the program one line at a time.','single_step',1,'[]',3),('idefeatures','SS2','This allows the effect of each statement to be observed.','single_step',1,'["SS1"]',4),
('optical','O1','The disc is spun at high speed.','process',1,'[]',1),('optical','O2','A laser is shone onto the disc to read/write.','process',1,'[]',2),('optical','O3','An optical head moves the laser into position.','process',1,'["O2"]',3),('optical','O4','The optical head follows the spiral track from the centre outwards.','process',1,'["O3"]',4),('optical','O5','When writing, the laser burns pits to represent data.','process',1,'[]',5),('optical','O6','When reading, the laser reflects from pits and lands.','process',1,'[]',6),('optical','O7','Reflection from a pit and a land is different.','process',1,'["O6"]',7),('optical','O8','The reflection differences are interpreted as 1 or 0.','process',1,'["O7"]',8),
('ethics','C1','Treat colleagues fairly and avoid discrimination.','colleagues',1,'[]',1),('ethics','C2','Be prepared to accept or offer critique.','colleagues',1,'[]',2),('ethics','C3','Critique allows technical work to be improved.','colleagues',1,'["C2"]',3),('ethics','C4','Credit the contributions of colleagues.','colleagues',1,'[]',4),('ethics','C5','Crediting contributions helps colleagues feel valued/respected.','colleagues',1,'["C4"]',5),('ethics','C6','Help or train colleagues.','colleagues',1,'[]',6),('ethics','P1','Maintain the health, safety and welfare of the public.','public',1,'[]',7),('ethics','P2','Do so in order not to endanger anyone.','public',1,'["P1"]',8),('ethics','P3','Be honest/realistic when making claims about software.','public',1,'[]',9),('ethics','P4','Honest claims maintain public trust.','public',1,'["P3"]',10),('ethics','P5','Maintain the security of the public’s data.','public',1,'[]',11);
create temp table r59 on commit drop as select t.*,q.id qid,ms.id msid from t59 t join source_papers sp on sp.year=t.year and sp.series::text=t.series and sp.variant=t.variant and sp.kind='QP'::paper_kind join components c on c.id=sp.component_id and c.number=t.component join questions q on q.source_paper_id=sp.id and q.path=t.path and q.marks=t.expected_marks join mark_schemes ms on ms.question_id=q.id and ms.max_marks=t.expected_marks;
create temp table e59 on commit drop as select r.* from r59 r where (select count(*) from mark_scheme_points p where p.mark_scheme_id=r.msid)=1 and (select count(*) from mark_scheme_groups g where g.mark_scheme_id=r.msid)=0 and exists(select 1 from mark_schemes ms where ms.id=r.msid and ms.scheme_type='manual_only'::scheme_type) and not exists(select 1 from assignment_questions aq where aq.question_id=r.qid) and not exists(select 1 from answers a where a.question_id=r.qid) and not exists(select 1 from grading_points gp join mark_scheme_points p on p.id=gp.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from error_patterns ep join mark_scheme_points p on p.id=ep.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from flashcards f join mark_scheme_points p on p.id=f.source_mark_scheme_point_id where p.mark_scheme_id=r.msid);
delete from mark_scheme_points p using e59 e where p.mark_scheme_id=e.msid;
create temp table ig59 on commit drop as with x as (insert into mark_scheme_groups(mark_scheme_id,label,n_required,marks_per_point,max_marks,sort_order,award_mode) select e.msid,g.label,g.n_required,g.marks_per_point,g.max_marks,g.sort_order,g.award_mode from e59 e join g59 g on g.family=e.family returning id,mark_scheme_id,label) select * from x;
insert into mark_scheme_points(mark_scheme_id,group_id,code,text,marks,accept,reject,requires,is_bod,sort_order) select e.msid,ig.id,p.code,p.txt,p.marks,'[]','[]',p.requires,false,p.sort_order from e59 e join p59 p on p.family=e.family left join ig59 ig on ig.mark_scheme_id=e.msid and ig.label=p.gl;
update mark_schemes ms set scheme_type=case when e.family='addrcompare' then 'all_required'::scheme_type else 'any_n_from_m'::scheme_type end,prompt_version='atomic-source-c1-sections-0059-v1',updated_at=now() from e59 e where ms.id=e.msid;
