-- Source-backed normalization for explicit capped/dependency-aware C1-C3 rubrics.
-- Usage-gated one-point/no-group manual wrappers only. Alternative/spatial schemes remain manual.

create temp table t60(year int,series text,component int,variant int,path text,expected_marks int,family text) on commit drop;
insert into t60 values
(2021,'ON',1,3,'2.c',3,'malware'),(2022,'ON',1,1,'9.b',2,'eeprom'),(2022,'ON',1,3,'7.b',3,'satellite'),(2023,'ON',1,1,'5.a',4,'register4'),(2023,'ON',1,2,'2.a',3,'dbterms'),(2023,'ON',1,2,'2.b',4,'dbsecurity'),(2023,'ON',1,2,'7.b.iii',4,'subnet'),(2023,'ON',1,2,'8.c.ii',3,'buscomponents'),(2023,'ON',1,3,'3.a.ii',4,'cloud_disadv'),(2024,'MJ',1,2,'3.a.ii',3,'encryption'),(2024,'MJ',1,2,'6',4,'osmanagement'),(2024,'ON',1,2,'8.b.ii',3,'oddmask'),
(2021,'ON',2,2,'2.b.ii',3,'design_decisions'),(2022,'ON',2,3,'5.c',3,'readability'),(2023,'MJ',2,2,'7.a.i',3,'info_relevant'),(2023,'MJ',2,2,'7.a.ii',2,'info_unneeded'),(2023,'MJ',2,3,'7.a.iii',2,'return_actions'),(2024,'MJ',2,1,'7.a.iii',2,'sms_actions'),(2024,'ON',2,1,'4.b',2,'subroutine_reason'),
(2023,'MJ',3,1,'7.c',2,'bool_acbc'),(2023,'MJ',3,3,'7.c',2,'bool_acbc'),(2023,'MJ',3,2,'9.d',2,'bool_abac'),(2024,'ON',3,1,'7.d.i',2,'bool_adbd'),(2024,'ON',3,3,'7.d.i',2,'bool_adbd');

create temp table g60(family text,label text,n_required int,marks_per_point int,max_marks int,award_mode text,sort_order int) on commit drop;
insert into g60 values
('malware','similarities',2,1,2,'fixed',1),('malware','difference',1,1,1,'fixed',2),('eeprom','benefit_points',2,1,2,'fixed',1),('satellite','advantage',1,1,1,'fixed',1),('satellite','disadvantages',2,1,2,'fixed',2),
('register4','PC',2,1,2,'fixed',1),('register4','MAR',2,1,2,'fixed',2),('register4','CIR',2,1,2,'fixed',3),('register4','STATUS',2,1,2,'fixed',4),
('dbterms','entity',1,1,1,'fixed',1),('dbterms','primary_key',1,1,1,'fixed',2),('dbterms','referential_integrity',1,1,1,'fixed',3),('dbsecurity','feature_names',2,1,2,'fixed',1),('dbsecurity','descriptions',2,1,2,'fixed',2),('subnet','uses',2,1,2,'fixed',1),('subnet','expansions',2,1,2,'fixed',2),
('cloud_disadv','control',2,1,2,'fixed',1),('cloud_disadv','internet',2,1,2,'fixed',2),('cloud_disadv','cost',2,1,2,'fixed',3),('encryption','descriptions',2,1,2,'fixed',1),('osmanagement','memory',3,1,3,'fixed',1),('osmanagement','process',3,1,3,'fixed',2),('oddmask','explanation',2,1,2,'fixed',1),
('design_decisions','decisions',3,1,3,'fixed',1),('readability','examples',2,1,2,'fixed',1),('info_relevant','pairs',3,1,3,'fixed',1),('info_unneeded','pairs',2,1,2,'fixed',1),('return_actions','actions',2,1,2,'fixed',1),('sms_actions','actions',2,1,2,'fixed',1),('subroutine_reason','reason',1,1,1,'fixed',1),('subroutine_reason','avoided',1,1,1,'fixed',2);

create temp table p60(family text,code text,txt text,gl text,marks int,requires jsonb,sort_order int) on commit drop;
insert into p60 values
('malware','S1','Both virus and spyware are malicious software.','similarities',1,'[]',1),('malware','S2','Both can be downloaded/installed/run without the user’s knowledge.','similarities',1,'[]',2),('malware','S3','Both can masquerade as / be embedded in legitimate software or try to avoid a firewall.','similarities',1,'[]',3),('malware','S4','Both can run in the background.','similarities',1,'[]',4),('malware','D1','Virus can damage data whereas spyware records/accesses data.','difference',1,'[]',5),('malware','D2','Virus does not send recorded data out; spyware can send recorded data to a third party.','difference',1,'[]',6),('malware','D3','Virus replicates itself whereas spyware does not.','difference',1,'[]',7),
('eeprom','B1','No additional equipment is needed to change the EEPROM.','benefit_points',1,'[]',1),('eeprom','B1X','This enables firmware updates by non-technical users.','benefit_points',1,'["B1"]',2),('eeprom','B2','EEPROM can be erased and reprogrammed several times.','benefit_points',1,'[]',3),('eeprom','B2X','This allows firmware to be updated.','benefit_points',1,'["B2"]',4),('eeprom','B2Y','A particular byte or the whole EEPROM can be erased.','benefit_points',1,'["B2"]',5),('eeprom','B3','EEPROM can be reprogrammed/updated.','benefit_points',1,'[]',6),('eeprom','B3X','It can be updated without removing it from the device.','benefit_points',1,'["B3"]',7),
('satellite','A1','Satellite access is not fixed to a single location.','advantage',1,'[]',1),('satellite','A2','Satellite access can reach remote/rural areas.','advantage',1,'[]',2),('satellite','D1','High latency / lag / slow connection.','disadvantages',1,'[]',3),('satellite','D2','More expensive than wired methods because extra equipment is needed.','disadvantages',1,'[]',4),('satellite','D3','Signal can be affected by bad weather.','disadvantages',1,'[]',5),('satellite','D4','Transmission speed is slower than fixed-line broadband.','disadvantages',1,'[]',6),('satellite','D5','Direct line of sight is needed.','disadvantages',1,'[]',7),
('register4','PCN','Identifies the Program Counter (PC).','PC',1,'[]',1),('register4','PCR','PC stores the address from which the next instruction is read.','PC',1,'["PCN"]',2),('register4','MARN','Identifies the Memory Address Register (MAR).','MAR',1,'[]',3),('register4','MARR','MAR stores the address of the memory location / I/O component being read or written.','MAR',1,'["MARN"]',4),('register4','CIRN','Identifies the Current Instruction Register (CIR).','CIR',1,'[]',5),('register4','CIRR','CIR holds the instruction currently being decoded and/or executed.','CIR',1,'["CIRN"]',6),('register4','SRN','Identifies the Status Register.','STATUS',1,'[]',7),('register4','SRR','Status Register contains individually addressable status bits set/cleared by operations, e.g. overflow/underflow.','STATUS',1,'["SRN"]',8),
('dbterms','E','Entity: an object about which data can be stored.','entity',1,'[]',1),('dbterms','PK','Primary key: unique attribute/combination used to identify a record/tuple.','primary_key',1,'[]',2),('dbterms','RI1','Referential integrity propagates related changes, e.g. cascading update/delete.','referential_integrity',1,'[]',3),('dbterms','RI2','Referential integrity prevents references to data that does not exist.','referential_integrity',1,'[]',4),('dbterms','RI3','Every foreign key has a corresponding primary key / logical FK dependency on PK.','referential_integrity',1,'[]',5),('dbterms','RI4','Referential integrity keeps database data consistent/up to date.','referential_integrity',1,'[]',6),('dbterms','RI5','It prevents records being added/deleted/modified incorrectly.','referential_integrity',1,'[]',7),('dbterms','RI6','It helps queries return accurate and complete results.','referential_integrity',1,'[]',8),
('dbsecurity','BK','Backup/recovery procedures.','feature_names',1,'[]',1),('dbsecurity','AR','Access rights.','feature_names',1,'[]',2),('dbsecurity','VW','Views.','feature_names',1,'[]',3),('dbsecurity','LK','Record/table locking.','feature_names',1,'[]',4),('dbsecurity','EN','Encryption.','feature_names',1,'[]',5),('dbsecurity','BK1','Automatically takes database copies and stores them off-site regularly.','descriptions',1,'["BK"]',6),('dbsecurity','BK2','Backups allow lost data to be recovered.','descriptions',1,'["BK"]',7),('dbsecurity','AR1','Different users receive different permissions to tables.','descriptions',1,'["AR"]',8),('dbsecurity','AR2','Permissions can include read/write, read-only or full access.','descriptions',1,'["AR"]',9),('dbsecurity','VW1','Different users can see different parts of the database.','descriptions',1,'["VW"]',10),('dbsecurity','VW2','Views restrict users to data they need to see.','descriptions',1,'["VW"]',11),('dbsecurity','LK1','Locking prevents simultaneous access to data.','descriptions',1,'["LK"]',12),('dbsecurity','LK2','Locking prevents updates being lost / data overwritten.','descriptions',1,'["LK"]',13),('dbsecurity','EN1','Encryption converts data into ciphertext.','descriptions',1,'["EN"]',14),('dbsecurity','EN2','Ciphertext cannot be understood without the decryption key.','descriptions',1,'["EN"]',15),
('subnet','U1','Improve LAN security.','uses',1,'[]',1),('subnet','U2','Make network management easier.','uses',1,'[]',2),('subnet','U3','Make the network easier to expand / improve control of network growth.','uses',1,'[]',3),('subnet','U4','Improve network performance.','uses',1,'[]',4),('subnet','U5','Reduce network congestion.','uses',1,'[]',5),('subnet','U1A','Devices do not receive unintended data.','expansions',1,'["U1"]',6),('subnet','U1B','A compromised device does not expose the whole network.','expansions',1,'["U1"]',7),('subnet','U1C','Not all devices can access all segments.','expansions',1,'["U1"]',8),('subnet','U2A','Faults can be isolated more efficiently.','expansions',1,'["U2"]',9),('subnet','U2B','Provides an appropriate fault-isolation example.','expansions',1,'["U2"]',10),('subnet','U3A','Allows a greater range of IP addresses to be available.','expansions',1,'["U3"]',11),('subnet','U5A','Localises communications / divides data between segments.','expansions',1,'["U5"]',12),('subnet','U5B','Devices are not flooded with data.','expansions',1,'["U5"]',13),('subnet','U5C','Data between devices on the same subnet remains within that subnet.','expansions',1,'["U5"]',14),
('buscomponents','BUF','A buffer temporarily holds data until it is ready to be transmitted to the device.',null,1,'[]',1),('buscomponents','AB','The address bus carries the address of the data to be written to the device.',null,1,'[]',2),('buscomponents','DB','The data bus carries data to be written to the device/buffer.',null,1,'[]',3),
('cloud_disadv','C1','Possible loss of control compared with a LAN.','control',1,'[]',1),('cloud_disadv','C2','Data is stored on someone else’s / remote infrastructure.','control',1,'["C1"]',2),('cloud_disadv','C3','Relies on an external agency for tasks such as backups/security.','control',1,'["C1"]',3),('cloud_disadv','I1','Requires a reliable Internet connection.','internet',1,'[]',4),('cloud_disadv','I2','Reliable Internet is needed to ensure access to remote data.','internet',1,'["I1"]',5),('cloud_disadv','K1','Cloud use can have increased recurring costs.','cost',1,'[]',6),('cloud_disadv','K2','Cloud-provider charges recur whereas LAN costs may be one-off.','cost',1,'["K1"]',7),
('encryption','M','Identifies encryption as the security measure.',null,1,'[]',1),('encryption','D1','Encryption encodes/scrambles data.','descriptions',1,'[]',2),('encryption','D2','If encrypted data is intercepted it cannot be understood.','descriptions',1,'["D1"]',3),('encryption','D3','An algorithm/key is required to decode the data.','descriptions',1,'[]',4),
('osmanagement','M1','Stores data from currently running programs concurrently in RAM.','memory',1,'[]',1),('osmanagement','M2','Prevents process data overwriting other data in RAM/primary storage.','memory',1,'[]',2),('osmanagement','M3','Decides which processes should be in main memory.','memory',1,'[]',3),('osmanagement','M4','Makes efficient use of memory.','memory',1,'[]',4),('osmanagement','P1','Allows one process to pause while another is actioned.','process',1,'[]',5),('osmanagement','P2','Decides which process runs next.','process',1,'[]',6),('osmanagement','P3','Switches between processes so they share the processor.','process',1,'[]',7),('osmanagement','P4','Identifies/describes scheduling.','process',1,'[]',8),
('oddmask','E1','An odd binary number has 1 in the least significant bit (LSB).','explanation',1,'[]',1),('oddmask','E2','Use a bit-manipulation operation to mask/access only the LSB and clear other bits.','explanation',1,'[]',2),('oddmask','E3','Compare the masking result with denary 1.','explanation',1,'[]',3),('oddmask','E4','The comparison is true when the number is odd.','explanation',1,'["E3"]',4),('oddmask','INST','Correct instruction: AND B00000001 / AND #1 / AND &01.',null,1,'[]',5),
('design_decisions','D1','Decision about data structures.','decisions',1,'[]',1),('design_decisions','D2','Decision about algorithms / flowcharts / pseudocode.','decisions',1,'[]',2),('design_decisions','D3','Decision about program structure/modules/library routines/team allocation.','decisions',1,'[]',3),('design_decisions','D4','Decision about user interface / web-page layout/content.','decisions',1,'[]',4),('design_decisions','D5','Decision about testing method/plan.','decisions',1,'[]',5),('design_decisions','D6','Decision about programming language/environment.','decisions',1,'[]',6),
('readability','REASON','Reason: readability/understanding or describing identifier purpose or easier debug/test/maintain.',null,1,'[]',1),('readability','E1','Uses white space.','examples',1,'[]',2),('readability','E2','Uses indentation.','examples',1,'[]',3),('readability','E3','Uses keywords in capitals.','examples',1,'[]',4),('readability','E4','Uses comments.','examples',1,'[]',5),('readability','E5','Uses local variables / parameters.','examples',1,'[]',6),
('info_relevant','P1','Customer name with justification: personalise/address the email.','pairs',1,'[]',1),('info_relevant','P2','Email address with justification: deliver the email correctly.','pairs',1,'[]',2),('info_relevant','P3','Product-category preference with justification: check customer interest.','pairs',1,'[]',3),('info_relevant','P4','Contact preference with justification: check customer accepts email contact.','pairs',1,'[]',4),('info_relevant','P5','Order history with justification: recommend similar products / identify frequent shoppers.','pairs',1,'[]',5),('info_relevant','P6','New-product information with justification: include it in the email.','pairs',1,'[]',6),
('info_unneeded','P1','Postal address with justification: sending email, not a letter.','pairs',1,'[]',1),('info_unneeded','P2','Payment details with justification: nothing is being bought/sold at this stage.','pairs',1,'[]',2),('info_unneeded','P3','Order history with justification: customer preference is used to decide relevance.','pairs',1,'[]',3),
('return_actions','A1','Clear/update the loan to show the book has been returned.','actions',1,'[]',1),('return_actions','A2','Remove the student from block / allow further borrowing.','actions',1,'[]',2),('return_actions','A3','Send acknowledgement to the student when the book is returned.','actions',1,'[]',3),
('sms_actions','A1','Add the member to a list of those interested in the new class.','actions',1,'[]',1),('sms_actions','A2','Remove the member from future SMS messages.','actions',1,'[]',2),('sms_actions','A3','Read/process Message.','actions',1,'[]',3),('sms_actions','A4','Identify who the message is from.','actions',1,'[]',4),
('subroutine_reason','R1','This algorithm part performs a specific task / changes need be made once only.','reason',1,'[]',1),('subroutine_reason','R2','A similar subroutine/library routine is already available.','reason',1,'[]',2),('subroutine_reason','R3','A subroutine simplifies the program / improves understandability/design/code/test/debug/maintenance.','reason',1,'[]',3),('subroutine_reason','A1','Avoids unnecessary code duplication.','avoided',1,'[]',4),('subroutine_reason','A2','Avoids errors caused by differences between multiple copies of the same check/calculation.','avoided',1,'[]',5),
('bool_acbc','MP1','Contains any correct Boolean term.',null,1,'[]',1),('bool_acbc','MP2','All Boolean terms and operators are correct with no extra terms: Z = AC + BC.',null,1,'["MP1"]',2),('bool_abac','MP1','Contains any correct Boolean term.',null,1,'[]',1),('bool_abac','MP2','All Boolean terms and operators are correct with no extra terms: Z = AB + AC.',null,1,'["MP1"]',2),('bool_adbd','MP1','Contains any correct Boolean term.',null,1,'[]',1),('bool_adbd','MP2','All Boolean terms and operators are correct with no extra terms: T = A.D + B.D.',null,1,'["MP1"]',2);

create temp table r60 on commit drop as select t.*,q.id qid,ms.id msid from t60 t join source_papers sp on sp.year=t.year and sp.series::text=t.series and sp.variant=t.variant and sp.kind='QP'::paper_kind join components c on c.id=sp.component_id and c.number=t.component join questions q on q.source_paper_id=sp.id and q.path=t.path and q.marks=t.expected_marks join mark_schemes ms on ms.question_id=q.id and ms.max_marks=t.expected_marks;
create temp table e60 on commit drop as select r.* from r60 r where (select count(*) from mark_scheme_points p where p.mark_scheme_id=r.msid)=1 and (select count(*) from mark_scheme_groups g where g.mark_scheme_id=r.msid)=0 and exists(select 1 from mark_schemes ms where ms.id=r.msid and ms.scheme_type='manual_only'::scheme_type) and not exists(select 1 from assignment_questions aq where aq.question_id=r.qid) and not exists(select 1 from answers a where a.question_id=r.qid) and not exists(select 1 from grading_points gp join mark_scheme_points p on p.id=gp.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from error_patterns ep join mark_scheme_points p on p.id=ep.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from flashcards f join mark_scheme_points p on p.id=f.source_mark_scheme_point_id where p.mark_scheme_id=r.msid);
delete from mark_scheme_points p using e60 e where p.mark_scheme_id=e.msid;
create temp table ig60 on commit drop as with x as (insert into mark_scheme_groups(mark_scheme_id,label,n_required,marks_per_point,max_marks,sort_order,award_mode) select e.msid,g.label,g.n_required,g.marks_per_point,g.max_marks,g.sort_order,g.award_mode from e60 e join g60 g on g.family=e.family returning id,mark_scheme_id,label) select * from x;
insert into mark_scheme_points(mark_scheme_id,group_id,code,text,marks,accept,reject,requires,is_bod,sort_order) select e.msid,ig.id,p.code,p.txt,p.marks,'[]','[]',p.requires,false,p.sort_order from e60 e join p60 p on p.family=e.family left join ig60 ig on ig.mark_scheme_id=e.msid and ig.label=p.gl;
update mark_schemes ms set scheme_type=case when e.family in ('buscomponents','bool_acbc','bool_abac','bool_adbd') then 'all_required'::scheme_type else 'any_n_from_m'::scheme_type end,prompt_version='atomic-source-capped-batch-0060-v1',updated_at=now() from e60 e where ms.id=e.msid;
