-- Source-backed low-mark C1 normalization for exact textual/table rubrics.
-- Source-summary-only, ambiguous spatial and mutually-exclusive rubrics are excluded.

create temp table t62(year int,series text,component int,variant int,path text,expected_marks int,family text,scheme_kind text) on commit drop;
insert into t62 values
(2021,'MJ',1,2,'4.b.iii',2,'and15','all_required'),(2021,'MJ',1,3,'1.a.i',2,'pixel_header','any_n_from_m'),(2021,'ON',1,2,'1',2,'security_integrity','all_required'),(2021,'ON',1,2,'2.a',2,'truth_nor_nand','all_required'),(2021,'ON',1,2,'3.b.i',2,'star','all_required'),(2021,'ON',1,2,'4.e.i',2,'add61','all_required'),(2021,'ON',1,2,'4.e.ii',2,'sub61','all_required'),(2021,'ON',1,2,'6.a.i',2,'norm_ticks','any_n_from_m'),(2021,'ON',1,2,'8.b.iii',2,'addr_mode','any_n_from_m'),(2022,'MJ',1,2,'1.a',3,'term_match','any_n_from_m'),(2022,'MJ',1,2,'7',2,'truth22mj','all_required'),(2022,'ON',1,2,'10.b.i',2,'device_reason','any_n_from_m'),(2022,'ON',1,2,'3.a',3,'boolean3','all_required'),(2022,'ON',1,2,'3.b',2,'truth22on2','all_required'),(2022,'ON',1,2,'5.d.i',2,'data_dict','any_n_from_m'),(2022,'ON',1,3,'1.b',2,'calc120','all_required'),(2022,'ON',1,3,'10.b.i',2,'sensor_reason','any_n_from_m'),(2022,'ON',1,3,'4.c',2,'upgrade_reason','any_n_from_m'),(2022,'ON',1,3,'5.b',2,'truth22on3','all_required'),(2022,'ON',1,3,'8.b',2,'impact_reason','any_n_from_m'),(2023,'ON',1,1,'4.a',2,'truth23on1','all_required'),(2023,'ON',1,1,'4.b',2,'gate23on1','all_required'),(2023,'ON',1,2,'3.c',2,'bcd_app','any_n_from_m'),(2023,'ON',1,2,'4.b',2,'truth23on2','all_required'),(2023,'ON',1,2,'6.c',2,'calc25','all_required'),(2023,'ON',1,2,'7.b.i',2,'router_layout','all_required'),(2023,'ON',1,3,'1.b',2,'sampling_terms','any_n_from_m'),(2023,'ON',1,3,'2.b',2,'calc4096','all_required'),(2023,'ON',1,3,'4.a',2,'truth23on3','all_required'),(2023,'ON',1,3,'4.b',2,'gate23on3','all_required'),(2023,'ON',1,3,'8.b',2,'pharm','any_n_from_m'),(2023,'ON',1,3,'9.d',3,'letters3','all_required'),(2024,'MJ',1,2,'1.b',2,'gate24mj2','all_required'),(2024,'MJ',1,2,'7.c',2,'calc3087','all_required'),(2024,'MJ',1,3,'7.a',2,'robot_sensor','any_n_from_m'),(2024,'ON',1,1,'1.c',2,'sub74_23','all_required'),(2024,'ON',1,1,'2.c',3,'dbdefs24','all_required'),(2024,'ON',1,1,'3.a',2,'clock_cu','any_n_from_m'),(2024,'ON',1,1,'3.b.i',2,'perf_feature','any_n_from_m'),(2024,'ON',1,1,'5.b',2,'expr2','all_required'),(2024,'ON',1,2,'1.a',2,'truth24on2','all_required'),(2024,'ON',1,2,'1.b',2,'gate24on2','all_required'),(2024,'ON',1,2,'9.a',2,'vehicle_sensor','any_n_from_m'),(2024,'ON',1,3,'1.c',2,'gate24on3','all_required'),(2024,'ON',1,3,'5.a',3,'licence3','all_required'),(2024,'ON',1,3,'6.a',2,'charset_pair','any_n_from_m');

create temp table g62(family text,label text,n_required int,marks_per_point int,max_marks int,award_mode text,sort_order int) on commit drop;
insert into g62 values
('pixel_header','pixel',1,1,1,'fixed',1),('pixel_header','header',1,1,1,'fixed',2),('norm_ticks','accuracy',1,1,2,'point_marks',1),('addr_mode','name',1,1,1,'fixed',1),('addr_mode','description',1,1,1,'fixed',2),('term_match','accuracy',1,1,3,'point_marks',1),('device_reason','device',1,1,1,'fixed',1),('device_reason','reason',1,1,1,'fixed',2),('data_dict','example',1,1,1,'fixed',1),('sensor_reason','sensor',1,1,1,'fixed',1),('sensor_reason','reason',1,1,1,'fixed',2),('upgrade_reason','upgrade',1,1,1,'fixed',1),('upgrade_reason','reason',1,1,1,'fixed',2),('impact_reason','impact',1,1,1,'fixed',1),('impact_reason','reason',1,1,1,'fixed',2),('bcd_app','application',1,1,1,'fixed',1),('bcd_app','reason',1,1,1,'fixed',2),('sampling_terms','accuracy',1,1,2,'point_marks',1),('pharm','difference',1,1,1,'fixed',1),('pharm','similarity',1,1,1,'fixed',2),('robot_sensor','pairs',2,1,2,'fixed',1),('clock_cu','clock',1,1,1,'fixed',1),('clock_cu','control_unit',1,1,1,'fixed',2),('perf_feature','feature',1,1,1,'fixed',1),('perf_feature','reason',1,1,1,'fixed',2),('vehicle_sensor','pairs',2,1,2,'fixed',1),('charset_pair','charset',1,1,1,'fixed',1),('charset_pair','description',1,1,1,'fixed',2);

create temp table p62(family text,code text,txt text,gl text,marks int,requires jsonb,sort_order int) on commit drop;
insert into p62 values
('and15','OP','Uses the AND instruction.',null,1,'[]',1),('and15','OPERAND','Uses immediate operand #15.',null,1,'[]',2),
('pixel_header','PIX1','Pixel: a single square of one colour.','pixel',1,'[]',1),('pixel_header','PIX2','Pixel: the smallest addressable element in an image.','pixel',1,'[]',2),('pixel_header','HDR','File header: stores metadata about the bitmap image, e.g. number of colours.','header',1,'[]',3),
('security_integrity','SEC','All Data Security classifications are correct: Firewall, Access rights and Password.',null,1,'[]',1),('security_integrity','INT','All Data Integrity classifications are correct: Double entry and Presence check.',null,1,'[]',2),
('truth_nor_nand','NOR','Complete NOR truth table is correct: 1,0,0,0.',null,1,'[]',1),('truth_nor_nand','NAND','Complete NAND truth table is correct: 1,1,1,0.',null,1,'[]',2),
('star','NAME','Identifies the topology as star.',null,1,'[]',1),('star','WHY','Justifies star: devices connect independently/directly to the router; devices are only connected to the router.',null,1,'[]',2),
('add61','WORK','Shows valid binary working for 0011 1101 + 0010 1101.',null,1,'[]',1),('add61','ANS','Correct result: 0110 1010.',null,1,'[]',2),('sub61','WORK','Shows valid subtraction/two’s-complement working using 0011 1101 and 1101 0011.',null,1,'[]',1),('sub61','ANS','Correct result: 0001 0000.',null,1,'[]',2),
('norm_ticks','PART','At least one but fewer than all three normalisation-stage ticks are correct.','accuracy',1,'[]',1),('norm_ticks','FULL','All three normalisation-stage ticks are correct.','accuracy',2,'[]',2),
('addr_mode','IND','Identifies indirect addressing.','name',1,'[]',1),('addr_mode','REL','Identifies relative addressing.','name',1,'[]',2),('addr_mode','IDX','Identifies indexed addressing.','name',1,'[]',3),('addr_mode','INDR','Indirect: the address to use is stored at the given address.','description',1,'["IND"]',4),('addr_mode','RELR','Relative: address is an offset from the current-instruction address.','description',1,'["REL"]',5),('addr_mode','IDXR','Indexed: address is formed from the given address plus index-register contents.','description',1,'["IDX"]',6),
('term_match','ONE','At least one of the four term-definition mappings is correct.','accuracy',1,'[]',1),('term_match','TWO','At least two of the four mappings are correct.','accuracy',2,'[]',2),('term_match','ALL','All four mappings are correct: Pixel→smallest identifiable component; Bit depth→bits per colour; Image resolution→pixels wide×high; File header→image metadata.','accuracy',3,'[]',3),
('truth22mj','TOP','First four outputs are correct: 0,0,1,0.',null,1,'[]',1),('truth22mj','BOTTOM','Last four outputs are correct: 1,0,0,0.',null,1,'[]',2),
('device_reason','SERVER','Identifies Server.','device',1,'[]',1),('device_reason','SWITCH','Identifies Switch.','device',1,'[]',2),('device_reason','SERVERR','Server processes/authorises requests or acts as firewall/proxy.','reason',1,'["SERVER"]',3),('device_reason','SWITCHR','Switch connects the computers so they can share router/network access.','reason',1,'["SWITCH"]',4),
('boolean3','P1','Correct first term: T AND NOT W.',null,1,'[]',1),('boolean3','P2','Correct second term: NOT R OR NOT M.',null,1,'[]',2),('boolean3','P3','Correct final AND combining the two terms.',null,1,'[]',3),('truth22on2','TOP','First four truth-table outputs are correct: 1,0,0,0.',null,1,'[]',1),('truth22on2','BOTTOM','Last four truth-table outputs are correct: 0,0,0,0.',null,1,'[]',2),
('data_dict','DESC','Data dictionary stores metadata about the database.',null,1,'[]',1),('data_dict','EX1','Valid example: field/attribute names.','example',1,'[]',2),('data_dict','EX2','Valid example: table name.','example',1,'[]',3),('data_dict','EX3','Valid example: validation rules.','example',1,'[]',4),('data_dict','EX4','Valid example: data types.','example',1,'[]',5),('data_dict','EX5','Valid example: primary/foreign keys.','example',1,'[]',6),('data_dict','EX6','Valid example: relationships.','example',1,'[]',7),
('calc120','WORK','Shows valid file-size working: 50 kHz × 1200 s × 16 bits, with correct unit conversion.',null,1,'[]',1),('calc120','ANS','Correct answer: 120 megabytes.',null,1,'[]',2),
('sensor_reason','SOUND','Identifies sound sensor.','sensor',1,'[]',1),('sensor_reason','IR','Identifies infra-red sensor.','sensor',1,'[]',2),('sensor_reason','PRESS','Identifies pressure sensor.','sensor',1,'[]',3),('sensor_reason','SOUNDR','Sound sensor activates alarm when sound occurs inside car.','reason',1,'["SOUND"]',4),('sensor_reason','IRR','Infra-red senses body heat / broken IR beams.','reason',1,'["IR"]',5),('sensor_reason','PRESSR','Pressure sensor detects an intruder sitting in driver’s seat.','reason',1,'["PRESS"]',6),
('upgrade_reason','RAM','Identifies increasing RAM.','upgrade',1,'[]',1),('upgrade_reason','CACHE','Identifies increasing cache size.','upgrade',1,'[]',2),('upgrade_reason','CLOCK','Identifies increasing clock speed.','upgrade',1,'[]',3),('upgrade_reason','CORE','Identifies increasing processors/cores.','upgrade',1,'[]',4),('upgrade_reason','RAMR','More RAM lets more applications reside in memory, reducing disk access.','reason',1,'["RAM"]',5),('upgrade_reason','CACHER','More cache lets CPU continue without waiting for data.','reason',1,'["CACHE"]',6),('upgrade_reason','CLOCKR','Higher clock speed executes more instructions per time period.','reason',1,'["CLOCK"]',7),('upgrade_reason','CORER','More processors/cores execute more instructions in parallel.','reason',1,'["CORE"]',8),
('truth22on3','TOP','First four outputs are correct: 0,0,1,1.',null,1,'[]',1),('truth22on3','BOTTOM','Last four outputs are correct: 0,0,1,0.',null,1,'[]',2),
('impact_reason','I1','Economic impact: reduce garage costs.','impact',1,'[]',1),('impact_reason','I2','Economic impact: increase garage profits.','impact',1,'[]',2),('impact_reason','I3','Economic impact: decrease costs passed to customer.','impact',1,'[]',3),('impact_reason','I4','Economic impact: profit margins can be reduced.','impact',1,'[]',4),('impact_reason','R1','Less time is taken for diagnosis.','reason',1,'["I1"]',5),('impact_reason','R2','Technicians can repair more jobs per day.','reason',1,'["I2"]',6),('impact_reason','R3','Lower customer costs may attract customers.','reason',1,'["I3"]',7),('impact_reason','R4','Diagnostic program may be expensive to buy/maintain/update.','reason',1,'["I4"]',8),
('truth23on1','TOP','First four outputs are correct: 1,0,0,0.',null,1,'[]',1),('truth23on1','BOTTOM','Last four outputs are correct: 1,0,1,1.',null,1,'[]',2),('gate23on1','G1','Both AND gates are correct.',null,1,'[]',1),('gate23on1','G2','NOT, OR and NOR gates are all correct.',null,1,'[]',2),
('bcd_app','FIN','Identifies a financial/banking calculation application.','application',1,'[]',1),('bcd_app','DISP','Identifies an electronic digit display such as calculator/clock.','application',1,'[]',2),('bcd_app','BIOS','Identifies BIOS date/time storage.','application',1,'[]',3),('bcd_app','FINR','Financial values need exact two-decimal representation; normal binary cannot represent many decimal fractions exactly.','reason',1,'["FIN"]',4),('bcd_app','DISPR','Digit displays only need individual denary digits / BCD-denary conversion is easy.','reason',1,'["DISP"]',5),('bcd_app','BIOSR','BCD makes conversion to/from denary date/time digits easier.','reason',1,'["BIOS"]',6),
('truth23on2','TOP','First four outputs are correct: 0,0,1,0.',null,1,'[]',1),('truth23on2','BOTTOM','Last four outputs are correct: 1,1,1,1.',null,1,'[]',2),('calc25','WORK','Shows valid file-size working: (2048×1024×10)/(8×1024×1024).',null,1,'[]',1),('calc25','ANS','Correct answer: 2.5 mebibytes.',null,1,'[]',2),('router_layout','SERVER','Server is connected only to the router.',null,1,'[]',1),('router_layout','LAPTOPS','Both laptop computers are connected only to the router.',null,1,'[]',2),
('sampling_terms','PART','At least one but fewer than all three term-description mappings are correct.','accuracy',1,'[]',1),('sampling_terms','FULL','All three mappings are correct: sampling→measurements at regular intervals; sampling rate→samples per second; sampling resolution→bits per sample.','accuracy',2,'[]',2),('calc4096','WORK','Shows valid file-size working: (2048×1024×16)/(8×1024).',null,1,'[]',1),('calc4096','ANS','Correct answer: 4096 kibibytes.',null,1,'[]',2),
('truth23on3','TOP','First four outputs are correct: 1,1,0,1.',null,1,'[]',1),('truth23on3','BOTTOM','Last four outputs are correct: 0,0,0,0.',null,1,'[]',2),('gate23on3','G1','P AND Q and NOT Q OR R are correct.',null,1,'[]',1),('gate23on3','G2','NOT gate, AND gate and XOR gate are correct.',null,1,'[]',2),
('pharm','D1','Difference: pharming redirects automatically via malicious code; phishing uses an email to prompt user action.','difference',1,'[]',1),('pharm','D2','Difference: pharming is automatic; phishing requires user action.','difference',1,'[]',2),('pharm','S1','Similarity: both try to obtain financial/personal information.','similarity',1,'[]',3),('pharm','S2','Similarity: both falsely represent an official organisation.','similarity',1,'[]',4),('pharm','S3','Similarity: both make use of fake websites.','similarity',1,'[]',5),('letters3','L2','Correct letter in position 2: D.',null,1,'[]',1),('letters3','L4','Correct letter in position 4: A.',null,1,'[]',2),('letters3','L6','Correct letter in position 6: B.',null,1,'[]',3),
('gate24mj2','G1','Both AND gates have correct inputs.',null,1,'[]',1),('gate24mj2','G2','OR and NOT gates have correct inputs with no superfluous gates.',null,1,'[]',2),('calc3087','WORK','Shows correct binary/hexadecimal working leading to 3087.',null,1,'[]',1),('calc3087','ANS','Correct answer: 3087.',null,1,'[]',2),('robot_sensor','P1','Pressure sensor with matching purpose: detect collision/obstacle or detect food placed/removed from tray.','pairs',1,'[]',1),('robot_sensor','P2','Infra-red sensor with matching purpose: detect obstacle or desired table.','pairs',1,'[]',2),('robot_sensor','P3','Sound sensor with matching purpose: detect speech for AI interpretation/stop instruction.','pairs',1,'[]',3),
('sub74_23','WORK','Shows valid direct subtraction or two’s-complement working for 74 − 23.',null,1,'[]',1),('sub74_23','ANS','Correct answer: 0011 0011.',null,1,'[]',2),('dbdefs24','RI','Referential integrity: foreign-key references match primary keys / duplicate linked data stays consistent.',null,1,'[]',1),('dbdefs24','CK','Candidate key: field/minimal attribute set that could uniquely identify a tuple but is not the primary key.',null,1,'[]',2),('dbdefs24','TUP','Tuple: a row/record, one instance of an entity in a table.',null,1,'[]',3),
('clock_cu','CLK1','System clock synchronises operations.','clock',1,'[]',1),('clock_cu','CLK2','System clock creates/transmits timing signals on the control bus.','clock',1,'[]',2),('clock_cu','CU1','Control Unit sends/receives control signals along the control bus.','control_unit',1,'[]',3),('clock_cu','CU2','Control Unit reads an instruction from the memory location addressed by PC.','control_unit',1,'[]',4),('clock_cu','CU3','Control Unit coordinates/synchronises other CPU components.','control_unit',1,'[]',5),('clock_cu','CU4','Control Unit manages execution of instructions.','control_unit',1,'[]',6),('clock_cu','CU5','Control Unit controls communication between CPU components.','control_unit',1,'[]',7),
('perf_feature','CLOCK','Identifies clock speed.','feature',1,'[]',1),('perf_feature','BUS','Identifies bus width.','feature',1,'[]',2),('perf_feature','CLOCKR','Higher clock speed executes more F-E cycles per second / increases throughput.','reason',1,'["CLOCK"]',3),('perf_feature','BUSR','Larger bus width transfers more data at the same time.','reason',1,'["BUS"]',4),('expr2','X','Correct expression: X = E AND A AND C.',null,1,'[]',1),('expr2','Y','Correct expression: Y = E AND (B OR C OR D).',null,1,'[]',2),
('truth24on2','TOP','First four outputs are correct: 1,1,1,1.',null,1,'[]',1),('truth24on2','BOTTOM','Last four outputs are correct: 1,0,1,1.',null,1,'[]',2),('gate24on2','G1','(P XOR Q) and (Q OR NOT R) are correct.',null,1,'[]',1),('gate24on2','G2','Second XOR gate and final NAND gate have appropriate inputs.',null,1,'[]',2),('vehicle_sensor','IR','Infra-red sensor with matching use: measure/check vehicle height.','pairs',1,'[]',1),('vehicle_sensor','PRESS','Pressure sensor with matching use: measure/check vehicle weight.','pairs',1,'[]',2),
('gate24on3','G1','NOT gate, two correct AND gates and NAND gate are correct.',null,1,'[]',1),('gate24on3','G2','OR gate and final AND gate are correct.',null,1,'[]',2),('licence3','COMM','Commercial licence for paid software with inaccessible source and no free trial.',null,1,'[]',1),('licence3','SHARE','Shareware for try-before-buy / feature-limited trial software.',null,1,'[]',2),('licence3','OPEN','Open Source / free software where source can be accessed and altered.',null,1,'[]',3),('charset_pair','ASCII','Identifies ASCII.','charset',1,'[]',1),('charset_pair','UNI','Identifies Unicode.','charset',1,'[]',2),('charset_pair','ASCIIR','ASCII uses 7/8 bits per character, represents 128/256 characters / Latin alphabet.','description',1,'["ASCII"]',3),('charset_pair','UNIR','Unicode uses 8/16/32 bits per character and can represent very large/all-language character sets.','description',1,'["UNI"]',4);

create temp table r62 on commit drop as select t.*,q.id qid,ms.id msid from t62 t join source_papers sp on sp.year=t.year and sp.series::text=t.series and sp.variant=t.variant and sp.kind='QP'::paper_kind join components c on c.id=sp.component_id and c.number=t.component join questions q on q.source_paper_id=sp.id and q.path=t.path and q.marks=t.expected_marks join mark_schemes ms on ms.question_id=q.id and ms.max_marks=t.expected_marks;
create temp table e62 on commit drop as select r.* from r62 r where (select count(*) from mark_scheme_points p where p.mark_scheme_id=r.msid)=1 and (select count(*) from mark_scheme_groups g where g.mark_scheme_id=r.msid)=0 and exists(select 1 from mark_schemes ms where ms.id=r.msid and ms.scheme_type='manual_only'::scheme_type) and not exists(select 1 from assignment_questions aq where aq.question_id=r.qid) and not exists(select 1 from answers a where a.question_id=r.qid) and not exists(select 1 from grading_points gp join mark_scheme_points p on p.id=gp.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from error_patterns ep join mark_scheme_points p on p.id=ep.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from flashcards f join mark_scheme_points p on p.id=f.source_mark_scheme_point_id where p.mark_scheme_id=r.msid);
delete from mark_scheme_points p using e62 e where p.mark_scheme_id=e.msid;
create temp table ig62 on commit drop as with x as (insert into mark_scheme_groups(mark_scheme_id,label,n_required,marks_per_point,max_marks,sort_order,award_mode) select e.msid,g.label,g.n_required,g.marks_per_point,g.max_marks,g.sort_order,g.award_mode from e62 e join g62 g on g.family=e.family returning id,mark_scheme_id,label) select * from x;
insert into mark_scheme_points(mark_scheme_id,group_id,code,text,marks,accept,reject,requires,is_bod,sort_order) select e.msid,ig.id,p.code,p.txt,p.marks,'[]','[]',p.requires,false,p.sort_order from e62 e join p62 p on p.family=e.family left join ig62 ig on ig.mark_scheme_id=e.msid and ig.label=p.gl;
update mark_schemes ms set scheme_type=e.scheme_kind::scheme_type,prompt_version='atomic-source-c1-lowmark-0062-v1',updated_at=now() from e62 e where ms.id=e.msid;
