-- Source-backed Component 3 normalization for repeated explicit rubrics.
-- Usage-gated one-point/no-group manual wrappers only.

create temp table t66(year int,series text,component int,variant int,path text,expected_marks int,family text,scheme_kind text) on commit drop;
insert into t66 values
(2021,'MJ',3,1,'7.c',4,'halfadder4','all_required'),(2021,'MJ',3,2,'7.c',4,'halfadder4','all_required'),(2021,'MJ',3,3,'7.c',4,'halfadder4','all_required'),(2022,'MJ',3,1,'5.b.ii',4,'rpnprocess','any_n_from_m'),(2022,'MJ',3,3,'5.b.ii',4,'rpnprocess','any_n_from_m'),(2022,'MJ',3,1,'6',6,'vm6','any_n_from_m'),(2022,'MJ',3,3,'6',6,'vm6','any_n_from_m'),(2022,'MJ',3,2,'3.a',4,'protocol4','any_n_from_m'),(2022,'MJ',3,2,'3.b',4,'layer4','any_n_from_m'),(2022,'MJ',3,2,'5',6,'arch6','all_required'),(2022,'MJ',3,2,'8.a',4,'searchblanks4','all_required'),(2022,'MJ',3,2,'9',4,'exception4','all_required'),(2022,'MJ',3,3,'9.b',7,'assembly7','all_required'),(2024,'ON',3,2,'5.a',4,'protocol24','any_n_from_m');

create temp table g66(family text,label text,n_required int,marks_per_point int,max_marks int,award_mode text,sort_order int) on commit drop;
insert into g66 values ('rpnprocess','process_points',4,1,4,'fixed',1),('vm6','benefits',4,1,4,'fixed',1),('vm6','limitations',2,1,2,'fixed',2),('protocol4','names',2,1,2,'fixed',1),('protocol4','descriptions',2,1,2,'fixed',2),('layer4','names',2,1,2,'fixed',1),('layer4','descriptions',2,1,2,'fixed',2),('protocol24','names',2,1,2,'fixed',1),('protocol24','expansions',2,1,2,'fixed',2);

create temp table p66(family text,code text,txt text,gl text,marks int,requires jsonb,sort_order int) on commit drop;
insert into p66 values
('halfadder4','YEXPR','Correct published Boolean expression for Y (Sum bit).',null,1,'[]',1),('halfadder4','YPUR','Correct purpose of Y: Sum bit.',null,1,'[]',2),('halfadder4','ZEXPR','Correct published Boolean expression for Z (Carry output).',null,1,'[]',3),('halfadder4','ZPUR','Correct purpose of Z: Carry output.',null,1,'[]',4),
('rpnprocess','P1','Works from left to right through the RPN expression.','process_points',1,'[]',1),('rpnprocess','P2','Pushes 10/m onto the stack.','process_points',1,'[]',2),('rpnprocess','P3','Pushes the following operands 10/m, 3/j and 2/k onto the stack.','process_points',1,'[]',3),('rpnprocess','P4','Recognises the first operator * when it is reached.','process_points',1,'[]',4),('rpnprocess','P5','Pops the top two numbers 2/k and 3/j.','process_points',1,'["P4"]',5),('rpnprocess','P6','Applies the multiplication operation to the popped values.','process_points',1,'["P5"]',6),('rpnprocess','P7','Pushes the result back onto the stack.','process_points',1,'["P6"]',7),('rpnprocess','P8','Continues processing to the end of the expression.','process_points',1,'[]',8),
('vm6','B1','A new system can be tried on different virtual hardware.','benefits',1,'[]',1),('vm6','B1X','No purchase of the physical hardware is required.','benefits',1,'["B1"]',2),('vm6','B2','Recovery is easier if the emulation software causes a system crash.','benefits',1,'[]',3),('vm6','B2X','The VM protects other host software from that failure.','benefits',1,'["B2"]',4),('vm6','B3','Programs for the new computer can be emulated even when incompatible with the host OS.','benefits',1,'[]',5),('vm6','B3X','This is possible by using a guest operating system on the old computer.','benefits',1,'["B3"]',6),('vm6','B4','More than one new computer system can be emulated.','benefits',1,'[]',7),('vm6','B4X','Multiple operating systems can coexist on one physical computer.','benefits',1,'["B4"]',8),('vm6','L1','A VM may not emulate newly developed hardware.','limitations',1,'[]',9),('vm6','L1X','The new hardware may have appeared after the VM was developed.','limitations',1,'["L1"]',10),('vm6','L2','VM execution adds overhead / shares processor or memory resources / may be less efficient.','limitations',1,'[]',11),('vm6','L2X','This increases processing time / degrades performance.','limitations',1,'["L2"]',12),('vm6','L3','Using a VM increases maintenance overhead.','limitations',1,'[]',13),('vm6','L3X','Both the host system and the VM must be maintained.','limitations',1,'["L3"]',14),
('protocol4','HTTP','Identifies HTTP/HTTPS.','names',1,'[]',1),('protocol4','FTP','Identifies FTP.','names',1,'[]',2),('protocol4','SMTP','Identifies SMTP.','names',1,'[]',3),('protocol4','POP','Identifies POP3.','names',1,'[]',4),('protocol4','IMAP','Identifies IMAP.','names',1,'[]',5),('protocol4','HTTPX','HTTP/HTTPS is used to send/receive web pages or hypertext documents.','descriptions',1,'["HTTP"]',6),('protocol4','FTPX','FTP is used to send/receive files over a network or between devices.','descriptions',1,'["FTP"]',7),('protocol4','SMTPX','SMTP is a push protocol used to send/upload email.','descriptions',1,'["SMTP"]',8),('protocol4','POPX','POP3 is a pull protocol used to receive/download email.','descriptions',1,'["POP"]',9),('protocol4','IMAPX','IMAP is a pull protocol used to receive/download email.','descriptions',1,'["IMAP"]',10),
('layer4','TRANS','Identifies the Transport layer.','names',1,'[]',1),('layer4','INET','Identifies the Internet layer.','names',1,'[]',2),('layer4','LINK','Identifies Network Access / Data Link / Physical layer.','names',1,'[]',3),('layer4','TRANSX','Transport layer handles packets.','descriptions',1,'["TRANS"]',4),('layer4','INETX','Internet layer handles IP-addressed transmission / selects a route.','descriptions',1,'["INET"]',5),('layer4','LINKX','Network Access/Data Link/Physical layer handles how data is physically sent.','descriptions',1,'["LINK"]',6),
('arch6','SIMD','Identifies SIMD.',null,1,'[]',1),('arch6','SIMDX','SIMD uses many/array processors executing the same instruction on different data sets.',null,1,'["SIMD"]',2),('arch6','MISD','Identifies MISD.',null,1,'[]',3),('arch6','MISDX','MISD uses many processors with different instructions on the same data set.',null,1,'["MISD"]',4),('arch6','MIMD','Identifies MIMD.',null,1,'[]',5),('arch6','MIMDX','MIMD uses many processors with different instructions on different data sets.',null,1,'["MIMD"]',6),
('searchblanks4','TYPE','Correct missing data type: INTEGER.',null,1,'[]',1),('searchblanks4','LEN','Correct bound/expression: 9 or LENGTH(MyList) - 1.',null,1,'[]',2),('searchblanks4','INDEX','Correct update/expression: Index + 1.',null,1,'[]',3),('searchblanks4','MSG','Correct not-found message, e.g. "Value not found".',null,1,'[]',4),('exception4','TRAP','Exception handling traps some runtime errors.',null,1,'[]',1),('exception4','HALT','It prevents a program halting unexpectedly.',null,1,'[]',2),('exception4','MSG','It can produce meaningful error messages.',null,1,'[]',3),('exception4','EX','Gives a valid exception example such as divide-by-zero, EOF or file-not-found.',null,1,'[]',4),
('assembly7','LDM','Uses LDM #20.',null,1,'[]',1),('assembly7','STO20','Stores 20 at a data address.',null,1,'[]',2),('assembly7','LAB20','Labels that address, e.g. Twenty, away from program code.',null,1,'["STO20"]',3),('assembly7','LABYZ','Labels data addresses Y and Z away from program code.',null,1,'[]',4),('assembly7','LDI','Uses LDI Y correctly.',null,1,'["LABYZ"]',5),('assembly7','STOZ','Uses STO Z correctly.',null,1,'["LABYZ"]',6),('assembly7','ADD','Uses ADD with the labelled Twenty address.',null,1,'["LAB20"]',7),
('protocol24','HTTP','MP1: HTTP/HTTPS.','names',1,'[]',1),('protocol24','HTTPX','MP2: sending/receiving web pages or hypertext.','expansions',1,'["HTTP"]',2),('protocol24','FTP','MP3: FTP.','names',1,'[]',3),('protocol24','FTPX','MP4: sending/receiving files over a network/between devices.','expansions',1,'["FTP"]',4),('protocol24','POP','MP5: POP3.','names',1,'[]',5),('protocol24','POPX','MP6: pull protocol / receiving/downloading email.','expansions',1,'["POP"]',6),('protocol24','IMAP','MP7: IMAP.','names',1,'[]',7),('protocol24','IMAPX','MP8: pull protocol / receiving/downloading email.','expansions',1,'["IMAP"]',8),('protocol24','SMTP','MP9: SMTP.','names',1,'[]',9),('protocol24','SMTPX','MP10: push protocol / sending/uploading email.','expansions',1,'["SMTP"]',10),('protocol24','BT','MP11: BitTorrent.','names',1,'[]',11),('protocol24','BTX','MP12: peer-to-peer file sharing over a network.','expansions',1,'["BT"]',12);

create temp table r66 on commit drop as select t.*,q.id qid,ms.id msid from t66 t join source_papers sp on sp.year=t.year and sp.series::text=t.series and sp.variant=t.variant and sp.kind='QP'::paper_kind join components c on c.id=sp.component_id and c.number=t.component join questions q on q.source_paper_id=sp.id and q.path=t.path and q.marks=t.expected_marks join mark_schemes ms on ms.question_id=q.id and ms.max_marks=t.expected_marks;
create temp table e66 on commit drop as select r.* from r66 r where (select count(*) from mark_scheme_points p where p.mark_scheme_id=r.msid)=1 and (select count(*) from mark_scheme_groups g where g.mark_scheme_id=r.msid)=0 and exists(select 1 from mark_schemes ms where ms.id=r.msid and ms.scheme_type='manual_only'::scheme_type) and not exists(select 1 from assignment_questions aq where aq.question_id=r.qid) and not exists(select 1 from answers a where a.question_id=r.qid) and not exists(select 1 from grading_points gp join mark_scheme_points p on p.id=gp.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from error_patterns ep join mark_scheme_points p on p.id=ep.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from flashcards f join mark_scheme_points p on p.id=f.source_mark_scheme_point_id where p.mark_scheme_id=r.msid);
delete from mark_scheme_points p using e66 e where p.mark_scheme_id=e.msid;
create temp table ig66 on commit drop as with x as (insert into mark_scheme_groups(mark_scheme_id,label,n_required,marks_per_point,max_marks,sort_order,award_mode) select e.msid,g.label,g.n_required,g.marks_per_point,g.max_marks,g.sort_order,g.award_mode from e66 e join g66 g on g.family=e.family returning id,mark_scheme_id,label) select * from x;
insert into mark_scheme_points(mark_scheme_id,group_id,code,text,marks,accept,reject,requires,is_bod,sort_order) select e.msid,ig.id,p.code,p.txt,p.marks,'[]','[]',p.requires,false,p.sort_order from e66 e join p66 p on p.family=e.family left join ig66 ig on ig.mark_scheme_id=e.msid and ig.label=p.gl;
update mark_schemes ms set scheme_type=e.scheme_kind::scheme_type,prompt_version='atomic-source-c3-repeated-0066-v1',updated_at=now() from e66 e where ms.id=e.msid;
