-- Source-backed special Component 3 normalization:
-- OOP term matching and mutually-exclusive graduated binary-tree table accuracy.

create temp table t67(year int,series text,component int,variant int,path text,expected_marks int,family text,scheme_kind text) on commit drop;
insert into t67 values (2023,'MJ',3,2,'4',4,'oopmatch','all_required'),(2024,'ON',3,2,'11.b',4,'treeaccuracy','any_n_from_m');
create temp table g67(family text,label text,n_required int,marks_per_point int,max_marks int,award_mode text,sort_order int) on commit drop;
insert into g67 values ('treeaccuracy','first_eight_rows',1,1,3,'point_marks',1);
create temp table p67(family text,code text,txt text,gl text,marks int,requires jsonb,sort_order int) on commit drop;
insert into p67 values
('oopmatch','GET','Correct match: Getters → methods used to return the value of a property.',null,1,'[]',1),('oopmatch','ENC','Correct match: Encapsulation → process of putting data and methods together as a single unit.',null,1,'[]',2),('oopmatch','SET','Correct match: Setters → methods used to update the value of a property.',null,1,'[]',3),('oopmatch','POLY','Correct match: Polymorphism → allows methods to be redefined for derived classes.',null,1,'[]',4),('treeaccuracy','R3_5','Exactly three, four or five of the first eight table rows are correct.','first_eight_rows',1,'[]',1),('treeaccuracy','R6_7','Exactly six or seven of the first eight table rows are correct.','first_eight_rows',2,'[]',2),('treeaccuracy','R8','All first eight table rows are correct.','first_eight_rows',3,'[]',3),('treeaccuracy','FREE','FreePtr is correct and the last row of the table is completely blank.',null,1,'[]',4);
create temp table r67 on commit drop as select t.*,q.id qid,ms.id msid from t67 t join source_papers sp on sp.year=t.year and sp.series::text=t.series and sp.variant=t.variant and sp.kind='QP'::paper_kind join components c on c.id=sp.component_id and c.number=t.component join questions q on q.source_paper_id=sp.id and q.path=t.path and q.marks=t.expected_marks join mark_schemes ms on ms.question_id=q.id and ms.max_marks=t.expected_marks;
create temp table e67 on commit drop as select r.* from r67 r where (select count(*) from mark_scheme_points p where p.mark_scheme_id=r.msid)=1 and (select count(*) from mark_scheme_groups g where g.mark_scheme_id=r.msid)=0 and exists(select 1 from mark_schemes ms where ms.id=r.msid and ms.scheme_type='manual_only'::scheme_type) and not exists(select 1 from assignment_questions aq where aq.question_id=r.qid) and not exists(select 1 from answers a where a.question_id=r.qid) and not exists(select 1 from grading_points gp join mark_scheme_points p on p.id=gp.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from error_patterns ep join mark_scheme_points p on p.id=ep.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from flashcards f join mark_scheme_points p on p.id=f.source_mark_scheme_point_id where p.mark_scheme_id=r.msid);
delete from mark_scheme_points p using e67 e where p.mark_scheme_id=e.msid;
create temp table ig67 on commit drop as with x as (insert into mark_scheme_groups(mark_scheme_id,label,n_required,marks_per_point,max_marks,sort_order,award_mode) select e.msid,g.label,g.n_required,g.marks_per_point,g.max_marks,g.sort_order,g.award_mode from e67 e join g67 g on g.family=e.family returning id,mark_scheme_id,label) select * from x;
insert into mark_scheme_points(mark_scheme_id,group_id,code,text,marks,accept,reject,requires,is_bod,sort_order) select e.msid,ig.id,p.code,p.txt,p.marks,'[]','[]',p.requires,false,p.sort_order from e67 e join p67 p on p.family=e.family left join ig67 ig on ig.mark_scheme_id=e.msid and ig.label=p.gl;
update mark_schemes ms set scheme_type=e.scheme_kind::scheme_type,prompt_version='atomic-source-c3-special-0067-v1',updated_at=now() from e67 e where ms.id=e.msid;
