-- Source-backed C2 normalization for textual algorithm/reuse/capped rubrics.
-- Alternative-solution and spatial/trace layouts are intentionally excluded.

create temp table t72(year int,series text,component int,variant int,path text,expected_marks int,family text,scheme_kind text) on commit drop;
insert into t72 values
(2021,'MJ',2,2,'6',8,'countvowels','all_required'),(2021,'ON',2,2,'5.a',7,'makenewfile','all_required'),(2022,'MJ',2,3,'2',4,'maintenance4','all_required'),(2022,'ON',2,2,'1.b',4,'beta4','any_n_from_m'),(2022,'ON',2,2,'5',4,'ifclauses4','all_required'),(2023,'MJ',2,1,'3.b',5,'loyalty5','any_n_from_m'),(2023,'MJ',2,3,'6.b',4,'checknum4','any_n_from_m'),(2024,'ON',2,3,'7.b',4,'submodulepairs4','any_n_from_m');
create temp table g72(family text,label text,n_required int,marks_per_point int,max_marks int,award_mode text,sort_order int) on commit drop;
insert into g72 values ('beta4','description',3,1,3,'fixed',1),('loyalty5','algorithm_points',5,1,5,'fixed',1),('checknum4','advantages',2,1,2,'fixed',1),('submodulepairs4','valid_pairs',4,1,4,'fixed',1);
create temp table p72(family text,code text,txt text,gl text,marks int,requires jsonb,sort_order int) on commit drop;
insert into p72 values
('countvowels','MP1','Procedure heading CountVowels with ThisString : STRING parameter and correct procedure ending.',null,1,'[]',1),('countvowels','MP2','Declares a local INTEGER loop-counter variable such as Index, but does not redeclare the global CharCount array.',null,1,'[]',2),('countvowels','MP3','Initialises all CharCount array elements to zero.',null,1,'[]',3),('countvowels','MP4','Loops through all characters in ThisString.',null,1,'[]',4),('countvowels','MP5','Uses MID() to extract a single character from ThisString.',null,1,'[]',5),('countvowels','MP6','Tests for each vowel and increments the associated count in CharCount.',null,1,'[]',6),('countvowels','MP7','Tests for consonants and increments the associated count in CharCount.',null,1,'[]',7),('countvowels','MP8','Outputs the CharCount results after the character-processing loop.',null,1,'[]',8),
('makenewfile','MP1','Procedure heading MakeNewFile with OldFile, NewFile and Status parameters and correct ending.',null,1,'[]',1),('makenewfile','MP2','Opens OldFile for READ and NewFile for WRITE, and subsequently closes both files.',null,1,'[]',2),('makenewfile','MP3','Uses a conditional loop until EOF(OldFile).',null,1,'[]',3),('makenewfile','MP4','Reads the three lines of each employee record from OldFile inside the loop.',null,1,'[]',4),('makenewfile','MP5','Compares the third line with Status and, when different, writes all three lines to NewFile inside the loop.',null,1,'[]',5),('makenewfile','MP6','Counts both records read and records copied; both counters are declared and initialised.',null,1,'[]',6),('makenewfile','MP7','After the loop outputs both counts and the relevant file names with suitable text.',null,1,'[]',7),
('maintenance4','ADAPT','Identifies Adaptive maintenance.',null,1,'[]',1),('maintenance4','ADAPT_R','Adaptive maintenance is needed to accommodate changed requirements, technology or legislation, e.g. a new HTML version.',null,1,'["ADAPT"]',2),('maintenance4','CORR','Identifies Corrective maintenance.',null,1,'[]',3),('maintenance4','CORR_R','Corrective maintenance is needed because the program does not operate as expected / contains a bug, e.g. passwords are not hidden.',null,1,'["CORR"]',4),
('beta4','STAGE','Identifies the test stage as Beta testing.',null,1,'[]',1),('beta4','D1','Beta testing is carried out by a small group of potential/actual users.','description',1,'[]',2),('beta4','D2','Users check that the software works as required in the real world / does not contain errors.','description',1,'[]',3),('beta4','D3','Users feed back problems or suggestions for improvement.','description',1,'[]',4),('beta4','D4','Problems/suggestions identified during beta testing are addressed before sale/release.','description',1,'[]',5),
('ifclauses4','C1','Correct IF clause for A AND B AND C calling Sub1().',null,1,'[]',1),('ifclauses4','C2','Correct IF clause for A AND B AND NOT C calling Sub2().',null,1,'[]',2),('ifclauses4','C3','Correct IF clause for NOT A AND NOT C calling Sub3().',null,1,'[]',3),('ifclauses4','C4','Correct IF clause for NOT A AND C calling Sub4().',null,1,'[]',4),
('loyalty5','P1','Uses constants/variables for threshold values 10 and 100, or inputs amount spent into a numeric variable.','algorithm_points',1,'[]',1),('loyalty5','P2','Determines one band that the amount maps to.','algorithm_points',1,'[]',2),('loyalty5','P3','Determines all bands that the amount maps to.','algorithm_points',1,'[]',3),('loyalty5','P4','Calculates a rounded/whole-number value of the amount.','algorithm_points',1,'[]',4),('loyalty5','P5','Calculates points using the rounded amount and appropriate band value(s).','algorithm_points',1,'[]',5),('loyalty5','P6','Outputs the number of points.','algorithm_points',1,'[]',6),
('checknum4','MP1','CheckNum takes two INTEGER parameters: the number and required total.',null,1,'[]',1),('checknum4','MP2','CheckNum returns BOOLEAN.',null,1,'[]',2),('checknum4','A1','CheckNum can be called repeatedly whenever required.','advantages',1,'[]',3),('checknum4','A2','CheckNum is designed/tested once and then reused.','advantages',1,'[]',4),('checknum4','A3','Later changes need be made once only / maintenance is easier.','advantages',1,'[]',5),
('submodulepairs4','PAIR1','ScanCard()/GetID() — read loyalty-card barcode / obtain customer ID.','valid_pairs',1,'[]',1),('submodulepairs4','PAIR2','GetPoints() — get current loyalty points.','valid_pairs',1,'[]',2),('submodulepairs4','PAIR3','ExchangePoints()/UpdateCard() — reduce loyalty points.','valid_pairs',1,'[]',3),('submodulepairs4','PAIR4','GetDiscount()/CalculateDiscount() — calculate discount.','valid_pairs',1,'[]',4),('submodulepairs4','PAIR5','CalculatePoints() — calculate points following a purchase.','valid_pairs',1,'[]',5),('submodulepairs4','PAIR6','UpdatePoints() — update total points following a purchase.','valid_pairs',1,'[]',6),('submodulepairs4','PAIR7','ShowDiscount() — display discount.','valid_pairs',1,'[]',7);
create temp table r72 on commit drop as select t.*,q.id qid,ms.id msid from t72 t join source_papers sp on sp.year=t.year and sp.series::text=t.series and sp.variant=t.variant and sp.kind='QP'::paper_kind join components c on c.id=sp.component_id and c.number=t.component join questions q on q.source_paper_id=sp.id and q.path=t.path and q.marks=t.expected_marks join mark_schemes ms on ms.question_id=q.id and ms.max_marks=t.expected_marks;
create temp table e72 on commit drop as select r.* from r72 r where (select count(*) from mark_scheme_points p where p.mark_scheme_id=r.msid)=1 and (select count(*) from mark_scheme_groups g where g.mark_scheme_id=r.msid)=0 and exists(select 1 from mark_schemes ms where ms.id=r.msid and ms.scheme_type='manual_only'::scheme_type and ms.prompt_version='source-backed-oidc-backfill-v1') and not exists(select 1 from assignment_questions aq where aq.question_id=r.qid) and not exists(select 1 from answers a where a.question_id=r.qid) and not exists(select 1 from grading_points gp join mark_scheme_points p on p.id=gp.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from error_patterns ep join mark_scheme_points p on p.id=ep.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from flashcards f join mark_scheme_points p on p.id=f.source_mark_scheme_point_id where p.mark_scheme_id=r.msid);
delete from mark_scheme_points p using e72 e where p.mark_scheme_id=e.msid;
create temp table ig72 on commit drop as with x as (insert into mark_scheme_groups(mark_scheme_id,label,n_required,marks_per_point,max_marks,sort_order,award_mode) select e.msid,g.label,g.n_required,g.marks_per_point,g.max_marks,g.sort_order,g.award_mode from e72 e join g72 g on g.family=e.family returning id,mark_scheme_id,label) select * from x;
insert into mark_scheme_points(mark_scheme_id,group_id,code,text,marks,accept,reject,requires,is_bod,sort_order) select e.msid,ig.id,p.code,p.txt,p.marks,'[]','[]',p.requires,false,p.sort_order from e72 e join p72 p on p.family=e.family left join ig72 ig on ig.mark_scheme_id=e.msid and ig.label=p.gl;
update mark_schemes ms set scheme_type=e.scheme_kind::scheme_type,prompt_version='atomic-source-c2-textual-0072-v1',updated_at=now() from e72 e where ms.id=e.msid;
