-- Source-backed C2 normalization for mixed textual/table/capped rubrics.
-- Alternative-solution and spatial/conditional-cap schemes are excluded.

create temp table t73(year int,series text,component int,variant int,path text,expected_marks int,family text,scheme_kind text) on commit drop;
insert into t73 values
(2021,'MJ',2,2,'5.a.ii',3,'unique_random','any_n_from_m'),(2021,'ON',2,2,'4.a',5,'analysis_table','all_required'),(2022,'MJ',2,1,'7.b',4,'flow_labels4','all_required'),(2022,'MJ',2,1,'8.d',2,'password_examples','any_n_from_m'),(2022,'ON',2,3,'3',5,'sums5','all_required'),(2022,'ON',2,3,'4.b.i',4,'queue_ops4','all_required'),(2023,'MJ',2,1,'3.a.i',4,'record_adv4','all_required'),(2023,'MJ',2,3,'1.d',4,'ipo_rows4','all_required'),(2023,'MJ',2,3,'7.a.ii',2,'required_not2','all_required'),(2023,'ON',2,3,'1.a',4,'assignment_types4','all_required'),(2023,'ON',2,3,'1.b',4,'expression_values4','all_required');
create temp table g73(family text,label text,n_required int,marks_per_point int,max_marks int,award_mode text,sort_order int) on commit drop;
insert into g73 values ('unique_random','valid_points',3,1,3,'fixed',1),('password_examples','examples',2,1,2,'fixed',1);
create temp table p73(family text,code text,txt text,gl text,marks int,requires jsonb,sort_order int) on commit drop;
insert into p73 values
('unique_random','INIT','Initialises the array to a rogue/unassigned value.','valid_points',1,'[]',1),('unique_random','LOOP','Adds a conditional loop.','valid_points',1,'[]',2),('unique_random','GEN','Generates and stores a random number in the correct range.','valid_points',1,'["LOOP"]',3),('unique_random','CHECK','Checks the stored number against values already in the array.','valid_points',1,'["LOOP"]',4),('unique_random','RETRY','If the stored number is already found, generates another random value.','valid_points',1,'["LOOP"]',5),('unique_random','ADD','Otherwise adds the value to the array and exits the loop.','valid_points',1,'["LOOP"]',6),
('analysis_table','INC','A line containing an incremented variable: 19, 21 or 23.',null,1,'[]',1),('analysis_table','LOOP','Loop structure type: pre-condition.',null,1,'[]',2),('analysis_table','FUNCS','Number of functions used: 3.',null,1,'[]',3),('analysis_table','PARAM','Number of parameters passed to STR_TO_NUM(): 1.',null,1,'[]',4),('analysis_table','PROC','Procedure name other than Check(): Result.',null,1,'[]',5),
('flow_labels4','B','Correct label B: Is Index > LENGTH(InString)?',null,1,'[]',1),('flow_labels4','D','Correct label D: Set OutString to OutString & MID(InString, Index, 1).',null,1,'[]',2),('flow_labels4','C','Correct label C: Is MID(InString, Index, 1) = " "?',null,1,'[]',3),('flow_labels4','FG','Correct YES/NO labels F and G, dependent on a reasonable attempt at C.',null,1,'["C"]',4),
('password_examples','LEN','Valid password example that violates the length rule (too long or too short).','examples',1,'[]',1),('password_examples','CHAR','Valid password example containing an invalid character.','examples',1,'[]',2),('password_examples','GROUP','Valid password example with incorrect grouping / number of hyphens.','examples',1,'[]',3),('password_examples','DUP','Valid password example containing duplicated characters.','examples',1,'[]',4),
('sums5','P1','Declares two REAL variables for positive and negative sums and initialises both to zero.',null,1,'[]',1),('sums5','P2','Prompts for and inputs a number.',null,1,'[]',2),('sums5','P3','Adds positive numbers to the positive sum and negative numbers to the negative sum.',null,1,'[]',3),('sums5','P4','Repeats input/processing until zero is entered.',null,1,'[]',4),('sums5','P5','After the loop outputs SumPos and SumNeg.',null,1,'[]',5),
('queue_ops4','ENQ','Operation for adding an item: Add / Enqueue.',null,1,'[]',1),('queue_ops4','ENQCHK','Check before enqueue: unused array elements exist / queue is not full.',null,1,'["ENQ"]',2),('queue_ops4','DEQ','Operation for removing an item: Remove / Dequeue.',null,1,'[]',3),('queue_ops4','DEQCHK','Check before dequeue: queue contains items / queue is not empty.',null,1,'["DEQ"]',4),
('record_adv4','STRUCT','Identifies the structure as a Record.',null,1,'[]',1),('record_adv4','A1','A set of data / all data related to one customer can be held together.',null,1,'[]',2),('record_adv4','A2','The fields may have different data types.',null,1,'[]',3),('record_adv4','A3','The related data is held under a single identifier/entity.',null,1,'[]',4),
('ipo_rows4','R2','OUTPUT FirstName & LastName is classified as Process and Output.',null,1,'[]',1),('ipo_rows4','R3','WRITEFILE OutputFile, TextLine is classified as Output.',null,1,'[]',2),('ipo_rows4','R4','READFILE MyFile, TextLine is classified as Input.',null,1,'[]',3),('ipo_rows4','R5','Result ← SQRT(NextNum) is classified as Process.',null,1,'[]',4),
('required_not2','REQ','Gives a valid required item: Student name/email, Loan return/issue date, or Book title.',null,1,'[]',1),('required_not2','NOT','Gives a valid not-required item: Student home address/DoB/tutor/subject choices, or Book library location/category/author.',null,1,'[]',2),
('assignment_types4','R1','MyVar1 ← Total1 / Total2 has data type REAL.',null,1,'[]',1),('assignment_types4','R2','MyVar2 ← 27/10/2023 has data type DATE.',null,1,'[]',2),('assignment_types4','R3','MyVar3 ← "Sum1 / Sum2" has data type STRING.',null,1,'[]',3),('assignment_types4','R4','MyVar4 ← Result1 AND Result2 has data type BOOLEAN.',null,1,'[]',4),
('expression_values4','E1','Fraction >= 0.2 AND NOT Active evaluates to FALSE.',null,1,'[]',1),('expression_values4','E2','INT((Fraction1 * 100) + 13.3) evaluates to 33.',null,1,'[]',2),('expression_values4','E3','STR_TO_NUM(MID(Code, 4, 2)) + 5 evaluates to 28.',null,1,'[]',3),('expression_values4','E4','LENGTH("TRUE" & Code) evaluates to 11.',null,1,'[]',4);
create temp table r73 on commit drop as select t.*,q.id qid,ms.id msid from t73 t join source_papers sp on sp.year=t.year and sp.series::text=t.series and sp.variant=t.variant and sp.kind='QP'::paper_kind join components c on c.id=sp.component_id and c.number=t.component join questions q on q.source_paper_id=sp.id and q.path=t.path and q.marks=t.expected_marks join mark_schemes ms on ms.question_id=q.id and ms.max_marks=t.expected_marks;
create temp table e73 on commit drop as select r.* from r73 r where (select count(*) from mark_scheme_points p where p.mark_scheme_id=r.msid)=1 and (select count(*) from mark_scheme_groups g where g.mark_scheme_id=r.msid)=0 and exists(select 1 from mark_schemes ms where ms.id=r.msid and ms.scheme_type='manual_only'::scheme_type and ms.prompt_version='source-backed-oidc-backfill-v1') and not exists(select 1 from assignment_questions aq where aq.question_id=r.qid) and not exists(select 1 from answers a where a.question_id=r.qid) and not exists(select 1 from grading_points gp join mark_scheme_points p on p.id=gp.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from error_patterns ep join mark_scheme_points p on p.id=ep.mark_scheme_point_id where p.mark_scheme_id=r.msid) and not exists(select 1 from flashcards f join mark_scheme_points p on p.id=f.source_mark_scheme_point_id where p.mark_scheme_id=r.msid);
delete from mark_scheme_points p using e73 e where p.mark_scheme_id=e.msid;
create temp table ig73 on commit drop as with x as (insert into mark_scheme_groups(mark_scheme_id,label,n_required,marks_per_point,max_marks,sort_order,award_mode) select e.msid,g.label,g.n_required,g.marks_per_point,g.max_marks,g.sort_order,g.award_mode from e73 e join g73 g on g.family=e.family returning id,mark_scheme_id,label) select * from x;
insert into mark_scheme_points(mark_scheme_id,group_id,code,text,marks,accept,reject,requires,is_bod,sort_order) select e.msid,ig.id,p.code,p.txt,p.marks,'[]','[]',p.requires,false,p.sort_order from e73 e join p73 p on p.family=e.family left join ig73 ig on ig.mark_scheme_id=e.msid and ig.label=p.gl;
update mark_schemes ms set scheme_type=e.scheme_kind::scheme_type,prompt_version='atomic-source-c2-mixed-0073-v1',updated_at=now() from e73 e where ms.id=e.msid;
