import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import type{AiUsage}from'../../lib/ai/claude.js';import{classifyQuestionsStage,detectDependenciesStage}from'./ai-ingestion.js';

const usage=(purpose:string):AiUsage=>({purpose,model:'claude-sonnet-4-20250514',promptVersion:purpose==='classify'?'classify-question.v1':'detect-dependencies.v1',inputTokens:10,outputTokens:5,cacheReadTokens:0,cacheWriteTokens:0,costUsd:.000105,latencyMs:12});
const root={path:'1',label:'1',parentPath:null,displayRef:'1',stemMd:null,contextMd:'A processor executes instructions.',commandWord:null,marks:null,answerKind:'text',answerLines:null,sourcePages:[1],assets:[],issues:[],confidence:.96};
const leafA={path:'1.a',label:'a',parentPath:'1',displayRef:'1(a)',stemMd:'State one register.',contextMd:null,commandWord:'State',marks:1,answerKind:'text',answerLines:1,sourcePages:[1],assets:[],issues:[],confidence:.95};
const leafB={path:'1.b',label:'b',parentPath:'1',displayRef:'1(b)',stemMd:'Using your answer to part (a), explain why the value changes.',contextMd:null,commandWord:'Explain',marks:2,answerKind:'text',answerLines:2,sourcePages:[1],assets:[],issues:[],confidence:.94};
const scheme={path:'1.a',displayRef:'1(a)',questionRef:'1(a)',schemeType:'all_required',maxMarks:1,guidanceMd:null,groups:[],points:[{code:'MP1',groupLabel:null,marks:1,text:'Register named',accept:[],reject:[],requires:[],isBod:false}],levels:[],confidence:.95,issues:[]};
function catalogPool(){const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select st.id'))return{rowCount:2,rows:[
 {subtopic_id:'st-1',subtopic_code:'1.2',subtopic_title:'Processor fundamentals',topic_number:1,topic_title:'Information representation',lo_id:'lo-1',lo_code:'1.2.1',lo_text:'Describe processor registers'},
 {subtopic_id:'st-1',subtopic_code:'1.2',subtopic_title:'Processor fundamentals',topic_number:1,topic_title:'Information representation',lo_id:'lo-2',lo_code:'1.2.2',lo_text:'Explain register use'},
]};if(sql.startsWith('insert into ai_calls'))return{rowCount:1,rows:[]};throw new Error(`unexpected ${sql}`)});return{pool:{query}as unknown as Pool,query}}

describe('classification stage',()=>{
 it('maps only codes that exist in the DB syllabus catalog and reports hallucinated codes',async()=>{const p=catalogPool(),prompts:string[]=[];const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async(input:{prompt:{body:string}})=>{prompts.push(input.prompt.body);return{data:{subtopics:[{code:'1.2',is_primary:true,confidence:.91,reason:'register question'},{code:'99.9',is_primary:false,confidence:.7,reason:'hallucinated'}],learning_objectives:[{code:'1.2.1',confidence:.9},{code:'99.9.1',confidence:.7}],ao:'AO1',ao_confidence:.88},usage:usage('classify'),raw:{}}})};const result=await classifyQuestionsStage(p.pool,client as never,{qp:{paperId:'qp-paper',batches:[]},questions:[root,leafA],markSchemes:[scheme]});const classification=(result.classifications as any[])[0];expect(classification).toMatchObject({path:'1.a',ao:'AO1',subtopics:[{id:'st-1',code:'1.2',isPrimary:true}],learningObjectives:[{id:'lo-1',code:'1.2.1'}]});expect(classification.issues).toEqual(expect.arrayContaining(['unknown_subtopic:99.9','unknown_learning_objective:99.9.1']));expect(prompts[0]).toContain('State one register.');expect(prompts[0]).toContain('1.2.1');expect(prompts[0]).not.toContain('{{question_stem_and_context}}')});
 it('flags a classification with no valid subtopic instead of persisting an invented tag',async()=>{const p=catalogPool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{subtopics:[{code:'9.9',is_primary:true,confidence:.9,reason:'bad'}],learning_objectives:[],ao:null,ao_confidence:.5},usage:usage('classify'),raw:{}}))};const result=await classifyQuestionsStage(p.pool,client as never,{qp:{paperId:'qp-paper',batches:[]},questions:[root,leafA],markSchemes:[]});expect((result.classifications as any[])[0]).toMatchObject({subtopics:[],issues:['unknown_subtopic:9.9','classification_has_no_valid_subtopic']})});
});

describe('dependency stage',()=>{
 it('normalizes answer_ref to required and preserves the evidence for selection safety',async()=>{const query=vi.fn(async(sql:string)=>sql.startsWith('insert into ai_calls')?{rowCount:1,rows:[]}:{rowCount:0,rows:[]});const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{dependencies:[{from_path:'1.b',to_path:'1.a',kind:'answer_ref',strength:'context_only',evidence:'Using your answer to part (a)',confidence:.97,note:null}]},usage:usage('depends'),raw:{}}))};const result=await detectDependenciesStage({query}as unknown as Pool,client as never,{qp:{paperId:'qp-paper',batches:[]},questions:[root,leafA,leafB]});expect(result.dependencyCandidates).toHaveLength(1);expect(result.dependencies).toEqual([expect.objectContaining({fromPath:'1.b',toPath:'1.a',kind:'answer_ref',strength:'required',evidence:'Using your answer to part (a)',issues:['answer_ref_strength_normalized_to_required']})])});
 it('drops a dependency path that is not present in the extracted tree',async()=>{const query=vi.fn(async(sql:string)=>sql.startsWith('insert into ai_calls')?{rowCount:1,rows:[]}:{rowCount:0,rows:[]});const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{dependencies:[{from_path:'1.b',to_path:'1.z',kind:'text_ref',strength:'required',evidence:'part (a)',confidence:.8,note:null}]},usage:usage('depends'),raw:{}}))};const result=await detectDependenciesStage({query}as unknown as Pool,client as never,{qp:{paperId:'qp-paper',batches:[]},questions:[root,leafA,leafB]});expect(result.dependencies).toEqual([]);expect(result.dependencyIssues).toEqual(['invalid_dependency_path:1.b->1.z'])});
 it('does not call AI for ordinary prose with no sibling reference',async()=>{const query=vi.fn();const client={model:'claude-sonnet-4-20250514',complete:vi.fn()};const plain={...leafA,stemMd:'Describe one part of the fetch-execute cycle.'};const result=await detectDependenciesStage({query}as unknown as Pool,client as never,{qp:{paperId:'qp-paper',batches:[]},questions:[root,plain]});expect(result.dependencies).toEqual([]);expect(result.dependencyCandidates).toEqual([]);expect(client.complete).not.toHaveBeenCalled()});
});
