import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import type{AiUsage}from'../../lib/ai/claude.js';import{crossCheckStage}from'./ai-crosscheck.js';
const usage:AiUsage={purpose:'crosscheck',model:'claude-sonnet-4-20250514',promptVersion:'cross-check.v2',inputTokens:10,outputTokens:5,cacheReadTokens:0,cacheWriteTokens:0,costUsd:.000105,latencyMs:10};
const root={path:'1',label:'1',parentPath:null,displayRef:'1',stemMd:null,contextMd:'Shared scenario.',commandWord:null,marks:null,answerKind:'text',answerLines:null,sourcePages:[1],assets:[],issues:[],confidence:.97};
const leaf={path:'1.a',label:'a',parentPath:'1',displayRef:'1(a)',stemMd:'Explain the result.',contextMd:null,commandWord:'Explain',marks:2,answerKind:'text',answerLines:2,sourcePages:[1],assets:[],issues:[],confidence:.95};
const scheme={path:'1.a',displayRef:'1(a)',questionRef:'1(a)',schemeType:'all_required',maxMarks:2,guidanceMd:null,groups:[],points:[{code:'MP1',groupLabel:null,marks:1,text:'A',accept:[],reject:[],requires:[],isBod:false},{code:'MP2',groupLabel:null,marks:1,text:'B',accept:[],reject:[],requires:[],isBod:false}],levels:[],confidence:.95,issues:[]};
function pool(){const query=vi.fn(async(sql:string)=>sql.startsWith('insert into ai_calls')?{rowCount:1,rows:[]}:{rowCount:0,rows:[]});return{pool:{query}as unknown as Pool,query}}
describe('cross-check stage',()=>{
 it('sends inherited context plus matched scheme and preserves a clean approved candidate',async()=>{const p=pool(),messages:string[]=[];const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async(input:{content:Array<{type:string;text?:string}>})=>{messages.push(input.content[0]?.text??'');return{data:{agrees:true,confidence:.94,disagreements:[]},usage,raw:{}}})};const result=await crossCheckStage(p.pool,client as never,{qp:{paperId:'qp-paper'},questions:[root,leaf],markSchemes:[scheme],classifications:[],dependencies:[],reviewStatus:'approved_candidate'});expect(result.reviewStatus).toBe('approved_candidate');expect(result.crossChecks).toEqual([expect.objectContaining({path:'1.a',agrees:true,confidence:.94,promptVersion:'cross-check.v2'})]);expect(messages[0]).toContain('Shared scenario.');expect(messages[0]).toContain('MP1')});
 it('keeps a disagreement in review rather than auto-approving it',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{agrees:false,confidence:.9,disagreements:[{field:'mark_scheme.max_marks',severity:'error',message:'Mismatch'}]},usage,raw:{}}))};const result=await crossCheckStage(p.pool,client as never,{qp:{paperId:'qp-paper'},questions:[root,leaf],markSchemes:[scheme],reviewStatus:'approved_candidate'});expect(result.reviewStatus).toBe('needs_review');expect(result.crossChecks).toEqual([expect.objectContaining({agrees:false,disagreements:[expect.objectContaining({severity:'error'})]})])});
 it('creates a deterministic disagreement when a leaf has no matched mark scheme without calling AI',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn()};const result=await crossCheckStage(p.pool,client as never,{qp:{paperId:'qp-paper'},questions:[root,leaf],markSchemes:[],reviewStatus:'approved_candidate'});expect(client.complete).not.toHaveBeenCalled();expect(result.reviewStatus).toBe('needs_review');expect(result.crossChecks).toEqual([expect.objectContaining({path:'1.a',agrees:false,confidence:1})])});
 it('records provider failure and does not manufacture a verdict',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>{throw new Error('crosscheck unavailable')})};await expect(crossCheckStage(p.pool,client as never,{qp:{paperId:'qp-paper'},questions:[root,leaf],markSchemes:[scheme],reviewStatus:'approved_candidate'})).rejects.toThrow('crosscheck unavailable');expect(p.query.mock.calls.some(([sql])=>String(sql).startsWith('insert into ai_calls'))).toBe(true)});
});
