import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import type{AiUsage}from'../../lib/ai/claude.js';import{classifyQuestionsV2Stage}from'./ai-classify-v2.js';
const usage:AiUsage={purpose:'classify',model:'claude-sonnet-4-20250514',promptVersion:'classify-question.v2',inputTokens:20,outputTokens:10,cacheReadTokens:0,cacheWriteTokens:0,costUsd:.00021,latencyMs:10};
const root={path:'1',label:'1',parentPath:null,displayRef:'1',stemMd:null,contextMd:'Shared context.',commandWord:null,marks:null,answerKind:'text',answerLines:null,sourcePages:[1],assets:[],issues:[],confidence:.98};
const leaf={path:'1.a',label:'a',parentPath:'1',displayRef:'1(a)',stemMd:'Explain the combined design.',contextMd:null,commandWord:'Explain',marks:5,answerKind:'text',answerLines:5,sourcePages:[1],assets:[],issues:[],confidence:.96};
function makePool(){const rows=Array.from({length:5},(_,index)=>({subtopic_id:`st-${index+1}`,subtopic_code:`1.${index+1}`,subtopic_title:`Subtopic ${index+1}`,topic_number:1,topic_title:'Topic 1',lo_id:`lo-${index+1}`,lo_code:`1.${index+1}.1`,lo_text:`LO ${index+1}`}));const query=vi.fn(async(sql:string)=>sql.startsWith('select st.id')?{rowCount:rows.length,rows}:sql.startsWith('insert into ai_calls')?{rowCount:1,rows:[]}:{rowCount:0,rows:[]});return{pool:{query}as unknown as Pool,query}}
describe('classification v2',()=>{
 it('loads the catalogue through component_topics so shared Paper 3/Paper 4 topics are visible',async()=>{const p=makePool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{subtopics:[{code:'1.1',is_primary:true,confidence:.9,reason:'R'}],learning_objectives:[],ao:'AO2',ao_confidence:.9},usage,raw:{}}))};await classifyQuestionsV2Stage(p.pool,client as never,{qp:{paperId:'qp'},questions:[root,leaf],markSchemes:[]});const catalogSql=String(p.query.mock.calls.find(([sql])=>String(sql).startsWith('select st.id'))?.[0]??'');expect(catalogSql).toContain('join component_topics ct on ct.component_id=sp.component_id');expect(catalogSql).not.toContain('t.component_id=sp.component_id')});
 it('accepts and maps five materially assessed subtopics',async()=>{const p=makePool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{subtopics:Array.from({length:5},(_,index)=>({code:`1.${index+1}`,is_primary:index===0,confidence:.9-index*.02,reason:`Reason ${index+1}`})),learning_objectives:Array.from({length:5},(_,index)=>({code:`1.${index+1}.1`,confidence:.85})),ao:'AO2',ao_confidence:.9},usage,raw:{}}))};const result=await classifyQuestionsV2Stage(p.pool,client as never,{qp:{paperId:'qp'},questions:[root,leaf],markSchemes:[]});const classification=(result.classifications as any[])[0];expect(classification.subtopics).toHaveLength(5);expect(classification.learningObjectives).toHaveLength(5);expect(classification.subtopics.filter((item:any)=>item.isPrimary)).toHaveLength(1)});
 it('repairs a missing primary tag deterministically and records the repair',async()=>{const p=makePool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{subtopics:[{code:'1.1',is_primary:false,confidence:.9,reason:'R'},{code:'1.2',is_primary:false,confidence:.8,reason:'R'}],learning_objectives:[],ao:null,ao_confidence:.5},usage,raw:{}}))};const result=await classifyQuestionsV2Stage(p.pool,client as never,{qp:{paperId:'qp'},questions:[root,leaf]});const classification=(result.classifications as any[])[0];expect(classification.subtopics[0].isPrimary).toBe(true);expect(classification.issues).toContain('classification_primary_repaired')});
 it('keeps only one primary when model returns several',async()=>{const p=makePool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{subtopics:[{code:'1.1',is_primary:true,confidence:.9,reason:'R'},{code:'1.2',is_primary:true,confidence:.8,reason:'R'}],learning_objectives:[],ao:'AO1',ao_confidence:.8},usage,raw:{}}))};const result=await classifyQuestionsV2Stage(p.pool,client as never,{qp:{paperId:'qp'},questions:[root,leaf]});const classification=(result.classifications as any[])[0];expect(classification.subtopics.filter((item:any)=>item.isPrimary)).toHaveLength(1);expect(classification.issues).toContain('classification_multiple_primary_repaired')});
 it('drops a real LO code when its owning subtopic was not selected',async()=>{const p=makePool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{subtopics:[{code:'1.1',is_primary:true,confidence:.9,reason:'R'}],learning_objectives:[{code:'1.2.1',confidence:.88}],ao:'AO1',ao_confidence:.8},usage,raw:{}}))};const result=await classifyQuestionsV2Stage(p.pool,client as never,{qp:{paperId:'qp'},questions:[root,leaf]});const classification=(result.classifications as any[])[0];expect(classification.learningObjectives).toEqual([]);expect(classification.issues).toContain('learning_objective_without_selected_subtopic:1.2.1')});
});
