import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import type{AiUsage,ClaudeUserBlock}from'../../lib/ai/claude.js';import{crossCheckStage}from'./ai-crosscheck.js';
const usage:AiUsage={purpose:'crosscheck',model:'claude-sonnet-4-20250514',promptVersion:'cross-check.v3',inputTokens:10,outputTokens:5,cacheReadTokens:0,cacheWriteTokens:0,costUsd:.000105,latencyMs:10};
const qpSha='a'.repeat(64),msSha='b'.repeat(64);
const root={path:'1',label:'1',parentPath:null,displayRef:'1',stemMd:null,contextMd:'Shared scenario.',commandWord:null,marks:null,answerKind:'text',answerLines:null,sourcePages:[1],assets:[],issues:[],confidence:.97};
const leaf={path:'1.a',label:'a',parentPath:'1',displayRef:'1(a)',stemMd:'Explain the result.',contextMd:null,commandWord:'Explain',marks:2,answerKind:'text',answerLines:2,sourcePages:[1],assets:[],issues:[],confidence:.95};
const scheme={path:'1.a',displayRef:'1(a)',questionRef:'1(a)',schemeType:'all_required',maxMarks:2,guidanceMd:null,groups:[],points:[{code:'MP1',groupLabel:null,marks:1,text:'A',accept:[],reject:[],requires:[],isBod:false},{code:'MP2',groupLabel:null,marks:1,text:'B',accept:[],reject:[],requires:[],isBod:false}],levels:[],confidence:.95,issues:[]};
const prepared={qp:{paperId:'qp-paper',batches:[{pageNumbers:[1],images:['qp-1.png'],text:'1 (a) Explain the result. [2]'}]},ms:{paperId:'ms-paper',batches:[{pageNumbers:[2],images:['ms-2.png'],text:'1(a) A; B 2'}]}};
const imageLoader=vi.fn(async(path:string):Promise<ClaudeUserBlock>=>({type:'text',text:`IMAGE:${path}`}));
function pool(hashes=true){const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select id,sha256 from source_papers'))return{rowCount:hashes?2:1,rows:hashes?[{id:'qp-paper',sha256:qpSha},{id:'ms-paper',sha256:msSha}]:[{id:'qp-paper',sha256:qpSha}]};if(sql.startsWith('insert into ai_calls'))return{rowCount:1,rows:[]};return{rowCount:0,rows:[]}});return{pool:{query}as unknown as Pool,query}}
describe('cross-check stage',()=>{
 it('sends inherited candidate plus exact-hash QP/MS source evidence and preserves a clean approved candidate',async()=>{const p=pool(),messages:string[]=[];const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async(input:{content:Array<{type:string;text?:string}>})=>{messages.push(input.content.map(block=>block.text??'').join('\n'));return{data:{agrees:true,confidence:.94,disagreements:[]},usage,raw:{}}})};const result=await crossCheckStage(p.pool,client as never,{...prepared,questions:[root,leaf],markSchemes:[scheme],classifications:[],dependencies:[],reviewStatus:'approved_candidate'},imageLoader);expect(result.reviewStatus).toBe('approved_candidate');expect(result.crossChecks).toEqual([expect.objectContaining({path:'1.a',agrees:true,confidence:.94,promptVersion:'cross-check.v3',evidence:{sourceMode:'page_image+text_layer',qpPaperId:'qp-paper',qpSha256:qpSha,msPaperId:'ms-paper',msSha256:msSha,qpPages:[1],msPages:[2]}})]);expect(messages[0]).toContain('Shared scenario.');expect(messages[0]).toContain(qpSha);expect(messages[0]).toContain(msSha);expect(messages[0]).toContain('ORIGINAL QUESTION PAPER');expect(messages[0]).toContain('IMAGE:qp-1.png');expect(messages[0]).toContain('ORIGINAL MARK SCHEME');expect(messages[0]).toContain('IMAGE:ms-2.png')});
 it('keeps a source disagreement in review rather than auto-approving it',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>({data:{agrees:false,confidence:.9,disagreements:[{field:'source.mark_scheme',severity:'error',message:'Mismatch'}]},usage,raw:{}}))};const result=await crossCheckStage(p.pool,client as never,{...prepared,questions:[root,leaf],markSchemes:[scheme],reviewStatus:'approved_candidate'},imageLoader);expect(result.reviewStatus).toBe('needs_review');expect(result.crossChecks).toEqual([expect.objectContaining({agrees:false,disagreements:[expect.objectContaining({severity:'error'})]})])});
 it('fails closed without calling AI when exact source SHA provenance is incomplete',async()=>{const p=pool(false);const client={model:'claude-sonnet-4-20250514',complete:vi.fn()};const result=await crossCheckStage(p.pool,client as never,{...prepared,questions:[root,leaf],markSchemes:[scheme],reviewStatus:'approved_candidate'},imageLoader);expect(client.complete).not.toHaveBeenCalled();expect(result.reviewStatus).toBe('needs_review');expect(result.crossChecks).toEqual([expect.objectContaining({disagreements:[expect.objectContaining({field:'source.sha256'})]})])});
 it('fails closed without calling AI when the MS source reference cannot be located',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn()};const bad={...prepared,ms:{paperId:'ms-paper',batches:[{pageNumbers:[2],images:['ms-2.png'],text:'2(a) unrelated mark scheme 2'}]}};const result=await crossCheckStage(p.pool,client as never,{...bad,questions:[root,leaf],markSchemes:[scheme],reviewStatus:'approved_candidate'},imageLoader);expect(client.complete).not.toHaveBeenCalled();expect(result.reviewStatus).toBe('needs_review');expect(result.crossChecks).toEqual([expect.objectContaining({path:'1.a',agrees:false,confidence:1,disagreements:[expect.objectContaining({field:'source.mark_scheme'})]})])});
 it('fails closed without calling AI when a required QP source page is missing',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn()};const bad={...prepared,qp:{paperId:'qp-paper',batches:[{pageNumbers:[2],images:['qp-2.png'],text:'other page'}]}};const result=await crossCheckStage(p.pool,client as never,{...bad,questions:[root,leaf],markSchemes:[scheme],reviewStatus:'approved_candidate'},imageLoader);expect(client.complete).not.toHaveBeenCalled();expect(result.crossChecks).toEqual([expect.objectContaining({disagreements:[expect.objectContaining({field:'source.question'})]})])});
 it('creates a deterministic disagreement when a leaf has no matched mark scheme without calling AI',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn()};const result=await crossCheckStage(p.pool,client as never,{...prepared,questions:[root,leaf],markSchemes:[],reviewStatus:'approved_candidate'},imageLoader);expect(client.complete).not.toHaveBeenCalled();expect(result.reviewStatus).toBe('needs_review');expect(result.crossChecks).toEqual([expect.objectContaining({path:'1.a',agrees:false,confidence:1})])});
 it('records provider failure and does not manufacture a verdict',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>{throw new Error('crosscheck unavailable')})};await expect(crossCheckStage(p.pool,client as never,{...prepared,questions:[root,leaf],markSchemes:[scheme],reviewStatus:'approved_candidate'},imageLoader)).rejects.toThrow('crosscheck unavailable');expect(p.query.mock.calls.some(([sql])=>String(sql).startsWith('insert into ai_calls'))).toBe(true)});
});
