import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import type{AiUsage,ClaudeUserBlock}from'../../lib/ai/claude.js';import{extractQuestionsV2Stage}from'./ai-extract-qp-v2.js';
const usage:AiUsage={purpose:'extract_qp',model:'claude-sonnet-4-20250514',promptVersion:'extract-question.v2',inputTokens:10,outputTokens:10,cacheReadTokens:0,cacheWriteTokens:0,costUsd:null,latencyMs:10};
const raw=(path:string,stem:string,pages:number[],confidence=.9)=>({path,label:path.split('.').at(-1)!,parent_path:path.includes('.')?path.split('.').slice(0,-1).join('.'):null,stem_md:stem,context_md:null,command_word:'Explain',marks:2,answer_kind:'text',answer_lines:2,source_pages:pages,assets:[],issues:[],confidence});
function harness(){const query=vi.fn(async(sql:string)=>sql.startsWith('select sp.id')?{rowCount:1,rows:[{kind:'QP',year:2025,series:'MJ',variant:1,syllabus:'9618',component:1,component_name:'Theory',level:'AS',total_marks:75}]}:sql.startsWith('insert into ai_calls')?{rowCount:1,rows:[]}:(() =>{throw new Error(`unexpected ${sql}`)})());return{pool:{query}as unknown as Pool,query}}
const imageLoader=vi.fn(async(path:string):Promise<ClaudeUserBlock>=>({type:'image',source:{type:'base64',media_type:'image/png',data:path}}));
describe('QP extraction v2 carry-over',()=>{
 it('excludes truncated paths from prior_refs and replaces the partial copy without a false overlap conflict',async()=>{const h=harness(),headers:string[]=[];let n=0;const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async(input:{content:ClaudeUserBlock[]})=>{headers.push((input.content[0]as{type:'text';text:string}).text);n++;return{data:n===1?{questions:[raw('1.a','Stable question',[1]),raw('2.a','Partial wording',[3],.7)],truncated:true,page_total_marks:4}:{questions:[raw('2.a','Complete wording after page turn',[3,4],.97),raw('3.a','Next question',[4])],truncated:false,page_total_marks:4},usage,raw:{}}})};const result=await extractQuestionsV2Stage(h.pool,client as never,{qp:{paperId:'qp',batches:[{pageNumbers:[1,2,3],images:['1','2','3'],text:'a\n\f\nb\n\f\nc'},{pageNumbers:[3,4,5],images:['3','4','5'],text:'c\n\f\nd\n\f\ne'}]}},imageLoader);expect(headers[1]).toContain('"prior_refs":["1.a"]');expect(headers[1]).toContain('"carryover_refs":["2.a"]');const questions=result.questions as Array<{path:string;stemMd:string;issues:string[]}>;expect(questions.find(question=>question.path==='2.a')?.stemMd).toBe('Complete wording after page turn');expect(questions.find(question=>question.path==='2.a')?.issues).not.toContain('overlap_conflict');expect((result.qp as any).extraction).toMatchObject({promptVersion:'extract-question.v2',overlapConflicts:[],unresolvedCarryoverPaths:[]})});
 it('keeps an unreturned carry-over visibly blocked for human review',async()=>{const h=harness();let n=0;const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>{n++;return{data:n===1?{questions:[raw('2.a','Still incomplete',[3],.96)],truncated:true,page_total_marks:2}:{questions:[raw('3.a','Different question',[4])],truncated:false,page_total_marks:2},usage,raw:{}}})};const result=await extractQuestionsV2Stage(h.pool,client as never,{qp:{paperId:'qp',batches:[{pageNumbers:[1,2,3],images:['1','2','3'],text:'a'},{pageNumbers:[3,4,5],images:['3','4','5'],text:'b'}]}},imageLoader);expect((result.qp as any).extraction.unresolvedCarryoverPaths).toEqual(['2.a']);expect((result.questions as any[]).find(question=>question.path==='2.a')).toMatchObject({confidence:.79,issues:['unresolved_truncated_carryover']})});
});
