import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import type{AiUsage,ClaudeUserBlock}from'../../lib/ai/claude.js';import{extractMarkSchemesStage,extractQuestionsStage}from'./ai-ingestion.js';

const usage=(purpose:string):AiUsage=>({purpose,model:'claude-sonnet-4-20250514',promptVersion:purpose==='extract_qp'?'extract-question.v1':'extract-markscheme.v1',inputTokens:100,outputTokens:20,cacheReadTokens:0,cacheWriteTokens:0,costUsd:.0006,latencyMs:25});
const qp=(path:string,stem:string,confidence=.9)=>({path,label:path.split('.').at(-1)!,parent_path:path.includes('.')?path.split('.').slice(0,-1).join('.'):null,stem_md:stem,context_md:null,command_word:path.includes('.')?'Explain':null,marks:path.includes('.')?2:null,answer_kind:'text',answer_lines:path.includes('.')?2:null,source_pages:[1],assets:[],issues:[],confidence});
const scheme=(path:string,confidence=.9)=>({question_ref:path==='1.a'?'1(a)':path,path,scheme_type:'all_required',max_marks:2,guidance_md:null,groups:[],points:[{code:'MP1',group_label:null,marks:1,text:'One',accept:[],reject:[],requires:[],is_bod:false},{code:'MP2',group_label:null,marks:1,text:'Two',accept:[],reject:[],requires:[],is_bod:false}],levels:[],confidence,issues:[]});

function pool(){const query=vi.fn(async(sql:string,values?:unknown[])=>{if(sql.startsWith('select sp.id')){const id=String(values?.[0]);return{rowCount:1,rows:[{kind:id.includes('ms')?'MS':'QP',year:2025,series:'MJ',variant:11,syllabus:'9618',component:1,component_name:'Written Paper 1',level:'AS',total_marks:75}]}}if(sql.startsWith('insert into ai_calls'))return{rowCount:1,rows:[]};throw new Error(`unexpected query ${sql}`)});return{pool:{query}as unknown as Pool,query}}
const imageLoader=vi.fn(async(path:string):Promise<ClaudeUserBlock>=>({type:'image',source:{type:'base64',media_type:'image/png',data:`base64:${path}`}}));

describe('AI ingestion stages',()=>{
 it('sends real page image blocks plus text and carries prior refs into overlapping QP batches',async()=>{const p=pool(),calls:Array<Record<string,unknown>>=[];let n=0;const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async(input:Record<string,unknown>)=>{calls.push(input);n++;return{data:n===1?{questions:[qp('1','Context'),qp('1.a','Explain A')],truncated:true,page_total_marks:2}:{questions:[qp('1.a','Explain A'),qp('2','Context 2'),qp('2.a','Explain B')],truncated:false,page_total_marks:2},usage:usage('extract_qp'),raw:{}}})};const input={qp:{paperId:'qp-paper',batches:[{pageNumbers:[1,2,3],images:['p1.png','p2.png','p3.png'],text:'one\n\f\ntwo\n\f\nthree'},{pageNumbers:[3,4],images:['p3.png','p4.png'],text:'three\n\f\nfour'}]}};const result=await extractQuestionsStage(p.pool,client as never,input,imageLoader);expect((result.questions as unknown[])).toHaveLength(4);expect((result.qp as any).extraction).toMatchObject({questionCount:4,overlapConflicts:[]});const content=calls[0]!.content as ClaudeUserBlock[];expect(content.filter(block=>block.type==='image')).toHaveLength(3);expect(content).toEqual(expect.arrayContaining([expect.objectContaining({type:'image'}),expect.objectContaining({type:'text',text:expect.stringContaining('Text layer, page 1')})]));const secondHeader=((calls[1]!.content as ClaudeUserBlock[])[0]as{type:'text';text:string}).text;expect(secondHeader).toContain('prior_refs');expect(secondHeader).toContain('1.a');expect(client.complete).toHaveBeenCalledTimes(2);expect(p.query.mock.calls.filter(([sql])=>String(sql).startsWith('insert into ai_calls'))).toHaveLength(2)});
 it('flags conflicting QP overlap for review',async()=>{const p=pool();let n=0;const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>{n++;return{data:{questions:[qp('1.a',n===1?'First extraction':'Changed extraction',n===1?.8:.95)],truncated:false,page_total_marks:2},usage:usage('extract_qp'),raw:{}}})};const result=await extractQuestionsStage(p.pool,client as never,{qp:{paperId:'qp-paper',batches:[{pageNumbers:[1],images:['1.png'],text:'a'},{pageNumbers:[1],images:['1.png'],text:'a'}]}},imageLoader);expect((result.qp as any).extraction.overlapConflicts).toEqual(['1.a']);expect((result.questions as any[])[0].issues).toContain('overlap_conflict')});
 it('extracts and deduplicates mark-scheme batches independently from QP data',async()=>{const p=pool();let n=0;const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>{n++;return{data:{schemes:n===1?[scheme('1.a')]:[scheme('1.a'),scheme('2.a')]},usage:usage('extract_ms'),raw:{}}})};const result=await extractMarkSchemesStage(p.pool,client as never,{questions:[{path:'1.a'}],ms:{paperId:'ms-paper',batches:[{pageNumbers:[1],images:['m1.png'],text:'ms1'},{pageNumbers:[2],images:['m2.png'],text:'ms2'}]}},imageLoader);expect((result.markSchemes as any[]).map(item=>item.path)).toEqual(['1.a','2.a']);expect((result.ms as any).extraction).toMatchObject({schemeCount:2,overlapConflicts:[]});expect(client.complete).toHaveBeenCalledTimes(2)});
 it('records a failed AI call and rethrows the provider error',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn(async()=>{throw new Error('provider down')})};await expect(extractQuestionsStage(p.pool,client as never,{qp:{paperId:'qp-paper',batches:[{pageNumbers:[1],images:['1.png'],text:'x'}]}},imageLoader)).rejects.toThrow('provider down');const failure=p.query.mock.calls.find(([sql])=>String(sql).startsWith('insert into ai_calls'));expect(failure?.[1]).toEqual(expect.arrayContaining(['extract_qp','claude-sonnet-4-20250514','extract-question.v1','source_papers','qp-paper','provider down']))});
 it('skips the wrong paper kind rather than running an MS prompt against a QP',async()=>{const p=pool();const client={model:'claude-sonnet-4-20250514',complete:vi.fn()};const input={ms:{paperId:'qp-paper',batches:[]}};await expect(extractMarkSchemesStage(p.pool,client as never,input,imageLoader)).resolves.toEqual(input);expect(client.complete).not.toHaveBeenCalled()});
});
