import{execFile}from'node:child_process';import{createHash}from'node:crypto';import{mkdir,readFile,rm}from'node:fs/promises';import{resolve}from'node:path';import{promisify}from'node:util';import{config}from'../../config.js';import type{AssetStore,StoredAsset}from'../asset-store.js';import type{IngestionStageHandler}from'./ingestion.js';import{validateAssetMetadata,type AssetCandidate}from'./asset-metadata.js';
type Artifact=Record<string,unknown>;type Prepared={paperId:string;sourcePath:string;outputDir:string;pageCount?:number;[key:string]:unknown};export interface StoredAssetRecord extends StoredAsset{questionPath:string;assetIndex:number;sourcePage:number;bbox:[number,number,number,number]}
type CropRunner=(command:string,args:string[])=>Promise<void>;const run=promisify(execFile);
export function createAssetCropStoreHandler(store:AssetStore,runner:CropRunner=defaultRunner):IngestionStageHandler{return async(_refId,input)=>cropAndStoreAssets(validateAssetMetadata(input),store,runner)}
export async function cropAndStoreAssets(input:Artifact,store:AssetStore,runner:CropRunner=defaultRunner):Promise<Artifact>{const prepared=preparedQp(input);if(!prepared)throw new Error('asset_crop_qp_prepare_artifact_missing');const candidates=Array.isArray(input.assetCandidates)?input.assetCandidates as AssetCandidate[]:[];if(!candidates.length)return{...input,storedAssets:[],assetStoreReport:{candidateCount:0,storedCount:0,totalBytes:0}};const outputDir=resolve(prepared.outputDir,'..','assets');await mkdir(outputDir,{recursive:true});const storedAssets:StoredAssetRecord[]=[];for(const candidate of candidates){if(prepared.pageCount&&candidate.sourcePage>prepared.pageCount)throw new Error(`asset_crop_page_out_of_range:${candidate.questionPath}:${candidate.sourcePage}/${prepared.pageCount}`);const[x1,y1,x2,y2]=candidate.bbox,x=Math.floor(x1),y=Math.floor(y1),width=Math.ceil(x2)-x,height=Math.ceil(y2)-y;if(width<=0||height<=0)throw new Error(`asset_crop_invalid_rectangle:${candidate.questionPath}:${candidate.assetIndex}`);const prefix=resolve(outputDir,`${safeName(candidate.questionPath)}-${candidate.assetIndex}-p${candidate.sourcePage}`),pngPath=`${prefix}.png`;try{await runner(config.PDFTOPPM_PATH,['-f',String(candidate.sourcePage),'-l',String(candidate.sourcePage),'-singlefile','-png','-r','200','-x',String(x),'-y',String(y),'-W',String(width),'-H',String(height),prepared.sourcePath,prefix]);const bytes=await readFile(pngPath);if(!bytes.length)throw new Error('empty_crop');const contentHash=createHash('sha256').update(bytes).digest('hex'),objectPath=`papers/${prepared.paperId}/${safeName(candidate.questionPath)}/${candidate.assetIndex}-${contentHash}.png`,stored=await store.putPng({objectPath,bytes:new Uint8Array(bytes),contentHash});storedAssets.push({...stored,questionPath:candidate.questionPath,assetIndex:candidate.assetIndex,sourcePage:candidate.sourcePage,bbox:candidate.bbox})}catch(error){throw new Error(`asset_crop_store_failed:${candidate.questionPath}:${candidate.assetIndex}:${error instanceof Error?error.message:String(error)}`)}finally{await rm(pngPath,{force:true})}}
 return{...input,storedAssets,assetStoreReport:{candidateCount:candidates.length,storedCount:storedAssets.length,totalBytes:storedAssets.reduce((sum,item)=>sum+item.sizeBytes,0)}}}
function preparedQp(input:Artifact):Prepared|null{const value=input.qp;return value&&typeof value==='object'&&typeof(value as Prepared).paperId==='string'&&typeof(value as Prepared).sourcePath==='string'&&typeof(value as Prepared).outputDir==='string'?value as Prepared:null}
function safeName(value:string){const name=value.trim().replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^[-.]+|[-.]+$/g,'');if(!name||name==='.'||name==='..')throw new Error('asset_crop_invalid_question_path');return name}
async function defaultRunner(command:string,args:string[]){await run(command,args,{maxBuffer:10*1024*1024})}
