import{mkdtemp,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{afterEach,describe,expect,it,vi}from'vitest';import type{AssetStore}from'../asset-store.js';import{cropAndStoreAssets,createAssetCropStoreHandler}from'./asset-crop-store.js';
const dirs:string[]=[];afterEach(async()=>Promise.all(dirs.splice(0).map(path=>rm(path,{recursive:true,force:true}))));async function prepared(){const dir=await mkdtemp(join(tmpdir(),'campath-crop-'));dirs.push(dir);const sourcePath=join(dir,'paper.pdf');await writeFile(sourcePath,'fake pdf source');return{paperId:'paper-1',sourcePath,outputDir:join(dir,'prepared'),pageCount:20}}
function store(){const putPng=vi.fn(async(input:{objectPath:string;bytes:Uint8Array;contentHash:string})=>({storagePath:`supabase://question-assets/${input.objectPath}`,objectPath:input.objectPath,sizeBytes:input.bytes.byteLength,contentHash:input.contentHash}));return{value:{checkReady:vi.fn(),putPng}as unknown as AssetStore,putPng}}
describe('asset crop + durable store',()=>{
 it('converts x1/y1/x2/y2 to pdftoppm x/y/width/height and uploads content-addressed PNG',async()=>{const qp=await prepared(),s=store(),runner=vi.fn(async(_command:string,args:string[])=>{const prefix=args.at(-1)!;await writeFile(`${prefix}.png`,Buffer.from('this is a deterministic png payload'))});const input={qp,assetCandidates:[{questionPath:'3.b.ii',assetIndex:0,kind:'diagram',sourcePage:4,bbox:[10.2,20.8,110.7,221.1],altText:'Diagram'}]};const result=await cropAndStoreAssets(input,s.value,runner);expect(runner).toHaveBeenCalledTimes(1);const args=runner.mock.calls[0]![1];expect(args).toEqual(expect.arrayContaining(['-f','4','-l','4','-singlefile','-png','-r','200','-x','10','-y','20','-W','101','-H','202',qp.sourcePath]));expect(s.putPng).toHaveBeenCalledTimes(1);const upload=s.putPng.mock.calls[0]![0];expect(upload.objectPath).toMatch(/^papers\/paper-1\/3\.b\.ii\/0-[a-f0-9]{64}\.png$/);expect(upload.contentHash).toMatch(/^[a-f0-9]{64}$/);expect((result.storedAssets as any[])[0]).toMatchObject({questionPath:'3.b.ii',assetIndex:0,sourcePage:4,bbox:[10.2,20.8,110.7,221.1],storagePath:expect.stringMatching(/^supabase:\/\/question-assets\//)});expect(result.assetStoreReport).toMatchObject({candidateCount:1,storedCount:1,totalBytes:35})});
 it('runs metadata validation before cropping in the composed handler',async()=>{const qp=await prepared(),s=store(),runner=vi.fn(async(_command:string,args:string[])=>{await writeFile(`${args.at(-1)!}.png`,Buffer.from('binary image'))}),handler=createAssetCropStoreHandler(s.value,runner);const question={path:'1.a',label:'a',parentPath:'1',displayRef:'1(a)',stemMd:'Study the diagram.',contextMd:null,commandWord:'Describe',marks:2,answerKind:'diagram',answerLines:0,sourcePages:[2],assets:[{kind:'diagram',contentMd:null,altText:'Diagram',bbox:[5,6,105,206],page:2}],issues:[],confidence:.95};const result=await handler('run',{qp,questions:[question]});expect(result.assetCandidates).toHaveLength(1);expect(result.storedAssets).toHaveLength(1);expect((result.questions as any[])[0].confidence).toBe(.95)});
 it('does not invoke Poppler when there are no binary crop candidates',async()=>{const qp=await prepared(),s=store(),runner=vi.fn();const result=await cropAndStoreAssets({qp,assetCandidates:[]},s.value,runner);expect(runner).not.toHaveBeenCalled();expect(s.putPng).not.toHaveBeenCalled();expect(result.assetStoreReport).toEqual({candidateCount:0,storedCount:0,totalBytes:0})});
 it('fails before upload when the source page is outside the prepared paper',async()=>{const qp=await prepared(),s=store(),runner=vi.fn();await expect(cropAndStoreAssets({qp,assetCandidates:[{questionPath:'9.a',assetIndex:0,kind:'diagram',sourcePage:21,bbox:[1,1,10,10],altText:'x'}]},s.value,runner)).rejects.toThrow('asset_crop_page_out_of_range:9.a:21/20');expect(runner).not.toHaveBeenCalled();expect(s.putPng).not.toHaveBeenCalled()});
});
