import{describe,expect,it,vi}from'vitest';import type{Pool}from'pg';import{buildValidationInput,validateIngestionArtifact}from'./ingestion.js';

const root={path:'1',parentPath:null,marks:null,stemMd:null,contextMd:'Shared processor context.',commandWord:null,answerKind:'text',answerLines:null,assets:[],confidence:.95,issues:[]};
const leaf={path:'1.a',parentPath:'1',marks:2,stemMd:'Explain a valid technical reason.',contextMd:null,commandWord:'Explain',answerKind:'text',answerLines:2,assets:[],confidence:.94,issues:[]};
const scheme={path:'1.a',questionPath:'1.a',schemeType:'all_required',maxMarks:2,groups:[],points:[{marks:1},{marks:1}],levels:[],issues:[]};
const classification={path:'1.a',subtopics:[{id:'st1',code:'1.1',confidence:.91}],learningObjectives:[],ao:'AO2',aoConfidence:.9,issues:[]};
function pool(total=2){return{query:vi.fn(async(sql:string)=>sql.startsWith('select c.total_marks')?{rowCount:1,rows:[{total_marks:total}]}:{rowCount:0,rows:[]})}as unknown as Pool}

describe('validation artifact builder',()=>{
 it('builds the existing deterministic validator contract from normalized QP/MS/classification/dependency data',async()=>{const validation=await buildValidationInput(pool(),{qp:{paperId:'paper-qp'},questions:[root,leaf],markSchemes:[scheme],classifications:[classification],dependencies:[{fromPath:'1.a',toPath:'1',kind:'text_ref'}]});expect(validation).toMatchObject({componentTotal:2,questions:[expect.objectContaining({id:'1',parentId:null,marks:null}),expect.objectContaining({id:'1.a',parentId:'1',marks:2,subtopicConfidences:[.91],extractConfidence:.94})],schemes:[expect.objectContaining({questionId:'1.a',type:'all_required',maxMarks:2,points:[1,1]})],dependencies:[{fromPath:'1.a',kind:'text_ref'}]})});
 it('feeds durable storage path and byte size into V11 validation',async()=>{const diagramLeaf={...leaf,answerKind:'diagram',assets:[{kind:'diagram',contentMd:null,altText:'Diagram',bbox:[10,20,110,220],page:1}]},storedAssets=[{questionPath:'1.a',assetIndex:0,storagePath:'supabase://question-assets/a.png',sizeBytes:4096,contentHash:'abc'}];const validation=await buildValidationInput(pool(),{qp:{paperId:'paper-qp'},questions:[root,diagramLeaf],markSchemes:[scheme],classifications:[classification],storedAssets});expect(validation.assets).toEqual([{storagePath:'supabase://question-assets/a.png',size:4096}]);const result=await validateIngestionArtifact({qp:{paperId:'paper-qp'},questions:[root,diagramLeaf],markSchemes:[scheme],classifications:[classification],storedAssets},pool());expect((result.validationFindings as Array<{code:string}>).some(item=>item.code==='V11')).toBe(false)});
 it('flags a suspiciously tiny durable crop through V11',async()=>{const storedAssets=[{questionPath:'1.a',assetIndex:0,storagePath:'supabase://question-assets/tiny.png',sizeBytes:100,contentHash:'tiny'}];const result=await validateIngestionArtifact({qp:{paperId:'paper-qp'},questions:[root,leaf],markSchemes:[scheme],classifications:[classification],storedAssets},pool());expect(result.validationFindings).toEqual(expect.arrayContaining([expect.objectContaining({code:'V11',severity:'error'})]))});
 it('passes a clean normalized paper through deterministic validation as an approved candidate',async()=>{const result=await validateIngestionArtifact({qp:{paperId:'paper-qp'},questions:[root,leaf],markSchemes:[scheme],classifications:[classification],dependencies:[],matchReport:{duplicateQuestionRefs:[],unmatchedQuestions:[],unmatchedSchemes:[]}},pool());expect(result.reviewStatus).toBe('approved_candidate');expect(result.validationFindings).toEqual([])});
 it('turns extraction overlap, classification hallucination and QP/MS mismatch into explicit review findings',async()=>{const result=await validateIngestionArtifact({qp:{paperId:'paper-qp'},questions:[root,{...leaf,issues:['overlap_conflict']}],markSchemes:[scheme],classifications:[{...classification,issues:['unknown_subtopic:99.9']}],dependencyIssues:['invalid_dependency_path:1.a->1.z'],matchReport:{duplicateQuestionRefs:['1.a'],unmatchedQuestions:['2.a'],unmatchedSchemes:['3.a']}},pool());expect(result.reviewStatus).toBe('needs_review');expect(result.validationFindings).toEqual(expect.arrayContaining([
  expect.objectContaining({code:'V24',severity:'error'}),expect.objectContaining({code:'V25',severity:'error'}),expect.objectContaining({code:'V26',severity:'warning'}),expect.objectContaining({code:'V28',severity:'error'}),expect.objectContaining({code:'V29',severity:'error'}),
 ]))});
 it('turns invalid binary crop metadata into explicit V27 review evidence',async()=>{const result=await validateIngestionArtifact({qp:{paperId:'paper-qp'},questions:[root,{...leaf,confidence:.79,issues:['asset_invalid_crop_coordinates:0']}],markSchemes:[scheme],classifications:[classification]},pool());expect(result.validationFindings).toEqual(expect.arrayContaining([expect.objectContaining({code:'V18',severity:'error'}),expect.objectContaining({code:'V27',severity:'error'})]))});
 it('uses the official component total from the database, so a 74/75 extraction fails V02',async()=>{const result=await validateIngestionArtifact({qp:{paperId:'paper-qp'},questions:[root,leaf],markSchemes:[scheme],classifications:[classification]},pool(75));expect(result.validationFindings).toEqual(expect.arrayContaining([expect.objectContaining({code:'V02',severity:'error'})]))});
});
