import{describe,expect,it}from'vitest';import{mergeQuestions,mergeSchemes,normalizeMs,normalizeQp,refFromPath}from'./ingestion-contract.js';

const q=(overrides:Record<string,unknown>={})=>({path:'3.b.i',label:'i',parent_path:'3.b',stem_md:'Explain the result.',context_md:null,command_word:'Explain',marks:2,answer_kind:'text',answer_lines:2,source_pages:[4],assets:[],issues:[],confidence:.92,...overrides});
const ms=(overrides:Record<string,unknown>={})=>({question_ref:'3(b)(i)',path:'3.b.i',scheme_type:'all_required',max_marks:2,guidance_md:null,groups:[],points:[{code:'MP1',group_label:null,marks:1,text:'First point',accept:[],reject:[],requires:[],is_bod:false},{code:'MP2',group_label:null,marks:1,text:'Second point',accept:[],reject:[],requires:[],is_bod:false}],levels:[],confidence:.94,issues:[],...overrides});

describe('ingestion contracts',()=>{
 it('normalizes question extraction without losing hierarchy or asset metadata',()=>{const result=normalizeQp({questions:[q({assets:[{kind:'table',content_md:'|a|b|',alt_text:'Data table',bbox:[10,20,100,80],page:4}]})],truncated:false,page_total_marks:2});expect(result.pageTotalMarks).toBe(2);expect(result.questions[0]).toMatchObject({path:'3.b.i',parentPath:'3.b',displayRef:'3(b)(i)',stemMd:'Explain the result.',marks:2,answerKind:'text',sourcePages:[4],confidence:.92});expect(result.questions[0]!.assets[0]).toEqual({kind:'table',contentMd:'|a|b|',altText:'Data table',bbox:[10,20,100,80],page:4})});
 it('normalizes mark schemes into one-point-per-award internal structure',()=>{const result=normalizeMs({schemes:[ms()]});expect(result[0]).toMatchObject({path:'3.b.i',displayRef:'3(b)(i)',questionRef:'3(b)(i)',schemeType:'all_required',maxMarks:2});expect(result[0]!.points.map(point=>point.code)).toEqual(['MP1','MP2'])});
 it('builds Cambridge-style references from tree paths',()=>{expect(refFromPath('1')).toBe('1');expect(refFromPath('3.b.ii')).toBe('3(b)(ii)')});
 it('deduplicates identical overlap and flags conflicting question overlap',()=>{const first=normalizeQp({questions:[q()],truncated:false,page_total_marks:2}).questions[0]!;const same={...first};const identical=mergeQuestions([first],[same]);expect(identical.questions).toHaveLength(1);expect(identical.conflicts).toEqual([]);const changed={...first,stemMd:'A different extraction.',confidence:.95};const conflict=mergeQuestions([first],[changed]);expect(conflict.conflicts).toEqual(['3.b.i']);expect(conflict.questions[0]).toMatchObject({stemMd:'A different extraction.',issues:['overlap_conflict']})});
 it('flags mark-scheme overlap conflicts rather than silently overwriting them',()=>{const first=normalizeMs({schemes:[ms()]})[0]!;const changed={...first,guidanceMd:'Changed guidance',confidence:.96};const result=mergeSchemes([first],[changed]);expect(result.conflicts).toEqual(['3.b.i']);expect(result.schemes[0]!.issues).toContain('overlap_conflict')});
 it('rejects structurally invalid model output',()=>{expect(()=>normalizeQp({questions:[q({marks:-1})],truncated:false,page_total_marks:0})).toThrow();expect(()=>normalizeMs({schemes:[ms({scheme_type:'invented'})]})).toThrow()});
});
