import{describe,expect,it,vi}from'vitest';import type{Pool,PoolClient}from'pg';import{persistPaperArtifact}from'./persist-paper.js';

const root={path:'1',label:'1',parentPath:null,displayRef:'1',stemMd:null,contextMd:'Shared context.',commandWord:null,marks:null,answerKind:'text',answerLines:null,sourcePages:[1],assets:[],issues:[],confidence:.97};
const leaf={path:'1.a',label:'a',parentPath:'1',displayRef:'1(a)',stemMd:'Explain why this is valid.',contextMd:null,commandWord:'Explain',marks:2,answerKind:'text',answerLines:2,sourcePages:[1],assets:[{kind:'table',contentMd:'|a|b|',altText:'Data table',bbox:[10,20,100,80]as[number,number,number,number],page:1}],issues:[],confidence:.96};
const classification={path:'1.a',subtopics:[{id:'11111111-1111-4111-8111-111111111111',code:'1.1',isPrimary:true,confidence:.92,reason:'tested'}],learningObjectives:[{id:'22222222-2222-4222-8222-222222222222',code:'1.1.1',confidence:.9}],ao:'AO2'as const,aoConfidence:.9,issues:[]};
const scheme={path:'1.a',displayRef:'1(a)',questionRef:'1(a)',schemeType:'all_required',maxMarks:2,guidanceMd:null,groups:[],points:[{code:'MP1',groupLabel:null,marks:1,text:'Point one',accept:[],reject:[],requires:[],isBod:false},{code:'MP2',groupLabel:null,marks:1,text:'Point two',accept:[],reject:[],requires:[],isBod:false}],levels:[],confidence:.95,issues:[]};
const dependency={fromPath:'1.a',toPath:'1',kind:'text_ref'as const,strength:'required'as const,evidence:'shared context',confidence:.9,note:null,issues:[]};

function harness(inUse=0){let questionNo=0,markSchemeNo=0;const clientQuery=vi.fn(async(sql:string,values?:unknown[])=>{
 if(sql==='begin'||sql==='commit'||sql==='rollback')return{rowCount:null,rows:[]};
 if(sql.startsWith('select count(*)::int in_use'))return{rowCount:1,rows:[{in_use:inUse}]};
 if(sql.startsWith('insert into questions'))return{rowCount:1,rows:[{id:`00000000-0000-4000-8000-${String(++questionNo).padStart(12,'0')}`}]};
 if(sql.startsWith('insert into mark_schemes'))return{rowCount:1,rows:[{id:`10000000-0000-4000-8000-${String(++markSchemeNo).padStart(12,'0')}`}]};
 if(sql.startsWith('insert into mark_scheme_groups'))return{rowCount:1,rows:[{id:'20000000-0000-4000-8000-000000000001'}]};
 return{rowCount:1,rows:[]};
 });const client={query:clientQuery,release:vi.fn()}as unknown as PoolClient;const query=vi.fn(async(sql:string)=>{if(sql.startsWith('select sp.id qp_paper_id'))return{rowCount:1,rows:[{component_id:'33333333-3333-4333-8333-333333333333',year:2025,series:'MJ',variant:1,syllabus_code:'9618',component:1}]};throw new Error(`unexpected pool SQL: ${sql}`)});const connect=vi.fn().mockResolvedValue(client);return{pool:{query,connect}as unknown as Pool,clientQuery,connect,client}}
const artifact=(overrides:Record<string,unknown>={})=>({qp:{paperId:'44444444-4444-4444-8444-444444444444',extraction:{promptVersion:'extract-question.v2'}},ms:{paperId:'55555555-5555-4555-8555-555555555555'},questions:[root,leaf],markSchemes:[scheme],classifications:[classification],dependencies:[dependency],validationFindings:[],reviewStatus:'approved_candidate',crossChecks:[{path:'1.a',agrees:true,confidence:.95,promptVersion:'cross-check.v1'}],...overrides});

const markSchemeFindingCodes=(h:ReturnType<typeof harness>)=>h.clientQuery.mock.calls.filter(([sql])=>String(sql).startsWith('insert into validation_findings')&&String(sql).includes("'mark_schemes'" )).map(([,values])=>String((values as unknown[])[0]));

describe('paper persistence',()=>{
 it('upserts the tree, preserves prompt provenance and atomically rewrites every derived child relation',async()=>{const h=harness();const result=await persistPaperArtifact(h.pool,artifact());expect(result).toMatchObject({reviewStatus:'approved_candidate',persistResult:{questionCount:2,leafCount:1,approvedCount:1,needsReviewCount:0,findingCount:0,pendingAssetCount:0,readyAssetCount:0,failedAssetCount:0}});const sqls=h.clientQuery.mock.calls.map(([sql])=>String(sql));expect(sqls).toEqual(expect.arrayContaining(['begin','commit']));for(const table of['question_assets','question_subtopics','question_learning_objectives','question_dependencies','mark_schemes'])expect(sqls.some(sql=>sql.includes(`delete from ${table}`))).toBe(true);expect(sqls.find(sql=>sql.startsWith('delete from validation_findings'))).toContain("ref_table='mark_schemes'");expect(sqls.some(sql=>sql.includes('on conflict(source_paper_id,path) do update'))).toBe(true);expect(sqls.some(sql=>sql.startsWith('insert into question_dependencies'))).toBe(true);expect(sqls.some(sql=>sql.startsWith('insert into mark_scheme_points'))).toBe(true);const questionCalls=h.clientQuery.mock.calls.filter(([sql])=>String(sql).startsWith('insert into questions'));expect(questionCalls).toHaveLength(2);for(const call of questionCalls)expect(call[1]).toContain('extract-question.v2');expect(markSchemeFindingCodes(h)).toEqual([])});
 it('preserves source page/bbox and queues a binary-only crop instead of approving an incomplete asset',async()=>{const h=harness();const imageLeaf={...leaf,assets:[{kind:'diagram',contentMd:null,altText:'Network diagram',bbox:[12,24,220,140]as[number,number,number,number],page:3}]};const result=await persistPaperArtifact(h.pool,artifact({questions:[root,imageLeaf]}));expect(result).toMatchObject({reviewStatus:'needs_review',persistResult:{approvedCount:0,needsReviewCount:1,pendingAssetCount:1,readyAssetCount:0,failedAssetCount:0}});const assetCall=h.clientQuery.mock.calls.find(([sql])=>String(sql).startsWith('insert into question_assets'))!;expect(assetCall[1]).toEqual(expect.arrayContaining([3,JSON.stringify([12,24,220,140]),'pending']));const leafInsert=h.clientQuery.mock.calls.filter(([sql])=>String(sql).startsWith('insert into questions'))[1]!;expect(leafInsert[1]).toContain('needs_review');expect(markSchemeFindingCodes(h)).toContain('MS_REVIEW_ASSET')});
 it('persists a durably stored binary asset as ready and allows clean auto-approval',async()=>{const h=harness(),bbox=[12,24,220,140]as[number,number,number,number],imageLeaf={...leaf,assets:[{kind:'diagram',contentMd:null,altText:'Network diagram',bbox,page:3}]},stored={questionPath:'1.a',assetIndex:0,sourcePage:3,bbox,storagePath:'supabase://question-assets/papers/paper/1.a/0-hash.png',objectPath:'papers/paper/1.a/0-hash.png',sizeBytes:4096,contentHash:'abc123'};const result=await persistPaperArtifact(h.pool,artifact({questions:[root,imageLeaf],storedAssets:[stored]}));expect(result).toMatchObject({reviewStatus:'approved_candidate',persistResult:{approvedCount:1,needsReviewCount:0,pendingAssetCount:0,readyAssetCount:1,failedAssetCount:0}});const assetCall=h.clientQuery.mock.calls.find(([sql])=>String(sql).startsWith('insert into question_assets'))!;expect(assetCall[0]).toContain('size_bytes');expect(assetCall[0]).toContain('content_hash');expect(assetCall[1]).toEqual(expect.arrayContaining([stored.storagePath,3,JSON.stringify(bbox),'ready',4096,'abc123']));const leafInsert=h.clientQuery.mock.calls.filter(([sql])=>String(sql).startsWith('insert into questions'))[1]!;expect(leafInsert[1]).toContain('approved');const msInsert=h.clientQuery.mock.calls.find(([sql])=>String(sql).startsWith('insert into mark_schemes'))!;expect(msInsert[1]).toContain('approved');expect(markSchemeFindingCodes(h)).toEqual([])});
 it('marks an asset without text or crop coordinates as failed for human review',async()=>{const h=harness();const broken={...leaf,assets:[{kind:'diagram',contentMd:null,altText:'Missing coordinates',bbox:null,page:2}]};const result=await persistPaperArtifact(h.pool,artifact({questions:[root,broken]}));expect(result).toMatchObject({reviewStatus:'needs_review',persistResult:{failedAssetCount:1}});const assetCall=h.clientQuery.mock.calls.find(([sql])=>String(sql).startsWith('insert into question_assets'))!;expect(assetCall[1]).toEqual(expect.arrayContaining(['failed','missing_source_bbox_or_content']));expect(markSchemeFindingCodes(h)).toContain('MS_REVIEW_ASSET')});
 it('rejects orphan stored-asset metadata before opening a destructive transaction',async()=>{const h=harness(),stored={questionPath:'9.z',assetIndex:0,sourcePage:1,bbox:[1,1,10,10],storagePath:'supabase://question-assets/x.png',objectPath:'x.png',sizeBytes:100,contentHash:'h'};await expect(persistPaperArtifact(h.pool,artifact({storedAssets:[stored]}))).rejects.toThrow('ingestion_persist_stored_asset_orphan:9.z:0');expect(h.connect).not.toHaveBeenCalled()});
 it('does not auto-approve when cross-check evidence is absent even if deterministic validation was clean',async()=>{const h=harness();const result=await persistPaperArtifact(h.pool,artifact({crossChecks:[]}));expect(result).toMatchObject({reviewStatus:'needs_review',persistResult:{approvedCount:0,needsReviewCount:1}});expect(markSchemeFindingCodes(h)).toContain('MS_REVIEW_PAPER_GATE');const gate=h.clientQuery.mock.calls.find(([sql,values])=>String(sql).startsWith('insert into validation_findings')&&Array.isArray(values)&&values[0]==='MS_REVIEW_PAPER_GATE')!;expect(JSON.parse(String(gate[1]![3]))).toMatchObject({path:'1.a',source:'paper',globalError:false,crossCheckReady:false})});
 it('records scheme, question and classification review causes against the mark scheme itself',async()=>{const h=harness();const flaggedLeaf={...leaf,issues:['question extraction needs review']},flaggedClassification={...classification,issues:['taxonomy classification needs review']},flaggedScheme={...scheme,issues:['scheme wording needs review']};await persistPaperArtifact(h.pool,artifact({questions:[root,flaggedLeaf],markSchemes:[flaggedScheme],classifications:[flaggedClassification]}));expect(markSchemeFindingCodes(h)).toEqual(expect.arrayContaining(['MS_REVIEW_SCHEME_ISSUE','MS_REVIEW_QUESTION_ISSUE','MS_REVIEW_CLASSIFICATION_ISSUE']));const rows=h.clientQuery.mock.calls.filter(([sql])=>String(sql).startsWith('insert into validation_findings')&&String(sql).includes("'mark_schemes'"));expect(rows).toHaveLength(3);for(const[,values]of rows){expect(values?.[1]).toMatch(/^10000000-/);expect(JSON.parse(String(values?.[3]))).toMatchObject({path:'1.a'})}});
 it('refuses destructive re-ingestion after any question entered an assignment or answer',async()=>{const h=harness(2);await expect(persistPaperArtifact(h.pool,artifact())).rejects.toThrow('ingestion_persist_question_in_use:2');expect(h.clientQuery).toHaveBeenCalledWith('rollback');expect(h.clientQuery.mock.calls.some(([sql])=>String(sql).startsWith('insert into questions'))).toBe(false);expect(h.clientQuery.mock.calls.some(([sql])=>String(sql).startsWith('delete from mark_schemes'))).toBe(false)});
 it('rolls back instead of committing a child whose parent is missing',async()=>{const h=harness();await expect(persistPaperArtifact(h.pool,artifact({questions:[leaf]}))).rejects.toThrow('ingestion_persist_missing_parent');expect(h.clientQuery).toHaveBeenCalledWith('rollback');expect(h.clientQuery).not.toHaveBeenCalledWith('commit')});
 it('writes validation and cross-check evidence as durable audit rows',async()=>{const h=harness();const result=await persistPaperArtifact(h.pool,artifact({validationFindings:[{code:'V24',severity:'error',message:'Overlap conflict',details:{path:'1.a'}}]}));expect(result.reviewStatus).toBe('needs_review');expect(h.clientQuery.mock.calls.some(([sql])=>String(sql).startsWith('insert into validation_findings'))).toBe(true);expect(h.clientQuery.mock.calls.some(([sql])=>String(sql).startsWith('insert into cross_checks'))).toBe(true);expect(markSchemeFindingCodes(h)).toContain('MS_REVIEW_PAPER_GATE')});
});