import type { LessonPresentationBeat } from './lesson-experience-model';
import './chapter2-internet-visuals.css';

export const CHAPTER_2_INTERNET_VISUAL_SLIDES=[
  'h2-218-ethernet','h2-218-conflicts','h2-218-collisions','h2-218-csma-cd',
  'h2-219-bitstreaming','h2-219-buffering','h2-219-pros-cons','h2-219-on-demand','h2-219-real-time',
  'h2-221-internet','h2-221-web','h2-221-comparison','h2-222-hardware','h2-222-pstn','h2-222-voip','h2-222-pstn-voip','h2-222-satellites',
  'h2-223-ipv4','h2-223-classes','h2-223-binary','h2-223-cidr','h2-223-ipv6','h2-223-ipv6-compression','h2-224-urls','h2-225-dns'
] as const;
export function hasChapter2InternetVisual(beat:LessonPresentationBeat){return CHAPTER_2_INTERNET_VISUAL_SLIDES.includes(beat.slideId as never)}
const Box=({title,children}:{title:string;children:React.ReactNode})=><section className="h2iv-box"><b>{title}</b>{children}</section>;

function Csma(){return <div className="h2iv-csma"><div className="wire"><span>A</span><i/><span>B</span><i/><span>C</span></div><ol>{['assemble frame','is line idle?','start to send frame','collision detected?','stop transmission + send jam signal','increment transmission counter','max transmission counter?','wait allocated random time','retry transmission'].map((x,i)=><li key={x}><span>{i+1}</span>{x}</li>)}</ol><footer>Figure 2.20 logic: a collision causes a voltage change on the Ethernet cable; CSMA/CD then stops transmission, sends a jam signal and retries after a random wait.</footer></div>}
function Ethernet(){return <div className="h2iv-ethernet"><Box title="NODE"><strong>device on the LAN</strong></Box><i>↔</i><Box title="MEDIUM"><strong>shared cable</strong><small>IEEE 802.3</small></Box><i>↔</i><Box title="FRAME"><strong>source + destination address</strong></Box></div>}
function Collisions(){return <div className="h2iv-collision"><div className="lane"><span>DEVICE A</span><b>FRAME A →</b><b className="other">← FRAME B</b><span>DEVICE B</span></div><div className="burst">COLLISION</div><footer>Two frames on the same shared channel at the same time corrupt the transmission.</footer></div>}
function IpConflict(){return <div className="h2iv-conflict"><Box title="DEVICE A"><code>192.168.1.14</code><small>dynamic address</small></Box><div className="warning">IP CONFLICT</div><Box title="DEVICE B"><code>192.168.1.14</code><small>static address</small></Box><footer>Every device on the LAN needs a unique IP address; the coursebook notes restarting the router as one resolution.</footer></div>}
function Streaming(){return <div className="h2iv-stream"><Box title="FILE SERVER"><p>compressed media stream</p></Box><i>→</i><Box title="NETWORK"><p>incoming rate must sustain playback</p></Box><i>→</i><div className="buffer"><span>HIGH WATER MARK</span><strong>BUFFER</strong><span>LOW WATER MARK</span></div><i>→</i><Box title="MEDIA PLAYER"><p>continuous playback</p></Box></div>}
function Buffer(){return <div className="h2iv-buffer"><header><span>100%</span><b>temporary storage area</b><span>0%</span></header><div className="tank"><i className="high"/><i className="low"/><span>HIGH WATER MARK</span><span>LOW WATER MARK</span></div><footer>The coursebook places the low and high water marks about 80% of total buffer capacity apart.</footer></div>}
function StreamCompare(){return <div className="h2iv-compare"><Box title="ON-DEMAND"><p>stored file → encode → server → user chooses when</p><strong>pause · rewind · fast forward</strong></Box><Box title="REAL-TIME"><p>camera/microphone → encode → streaming server → live user</p><strong>live footage cannot be paused, rewound or fast-forwarded</strong></Box></div>}
function ProsCons(){return <div className="h2iv-pros"><Box title="BENEFITS"><p>start before whole file downloads</p><p>no need to store large media locally</p><p>on-demand playback</p><p>piracy protection</p></Box><Box title="DRAWBACKS"><p>connection loss stops stream</p><p>slow connection / insufficient buffer causes pauses</p><p>uses high bandwidth</p><p>copyright and security issues</p></Box></div>}
function InternetWeb({mode}:{mode:'internet'|'web'|'compare'}){if(mode==='compare')return <div className="h2iv-webcompare"><Box title="INTERNET"><strong>massive network of networks</strong><p>uses TCP/IP</p><small>infrastructure carrying many services</small></Box><i>supports</i><Box title="WORLD WIDE WEB"><strong>collection of multimedia web pages/documents</strong><p>uses the internet to reach servers</p><small>accessed through browsers, URLs and HTTP(S)</small></Box></div>;return <div className="h2iv-websolo"><div className="globe">{mode==='internet'?'INTERNET':'WWW'}</div><div>{mode==='internet'?<><p>interconnected network</p><p>network of networks</p><p>TCP/IP communication</p><p>computers + electronic devices</p></>:<><p>multimedia web pages</p><p>stored on websites</p><p>URLs locate resources</p><p>browsers access and interpret pages</p></>}</div></div>}
function Hardware(){return <div className="h2iv-path">{['DEVICE','ROUTER / MODEM','ISP','INTERNET BACKBONE','DESTINATION SERVER'].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div>}
function PstnVoip({mode}:{mode:'pstn'|'voip'|'compare'}){if(mode==='compare')return <div className="h2iv-compare"><Box title="PSTN"><p>circuit switching</p><p>dedicated line stays open</p><p>~10 MB for a 10-minute call in the source example</p></Box><Box title="VOIP"><p>packet switching</p><p>link active only while data is transmitted</p><p>~3 MB for the same 10-minute conversation example</p></Box></div>;return <div className="h2iv-call"><span>{mode==='pstn'?'PHONE A':'MIC / WEBCAM'}</span><div><strong>{mode==='pstn'?'DEDICATED CIRCUIT':'DIGITAL PACKETS'}</strong><small>{mode==='pstn'?'connection maintained for whole call':'packets can travel through many possible routes'}</small></div><span>{mode==='pstn'?'PHONE B':'REMOTE USER'}</span></div>}
function Satellites(){return <div className="h2iv-orbits"><div className="earth">EARTH</div>{[['LEO','500–2500 km','80 min–2 h','mobile phone networks'],['MEO','5000–12 000 km','2–12 h','GPS systems'],['GEO','35 800 km','24 h','long-distance telephone + computer networks']].map(([a,b,c,d],i)=><section className={`orbit o${i+1}`} key={a}><strong>{a}</strong><span>{b}</span><small>{c} · {d}</small></section>)}</div>}
function Ipv4(){return <div className="h2iv-ipv4"><header><strong>254</strong><i>.</i><strong>0</strong><i>.</i><strong>128</strong><i>.</i><strong>77</strong></header><footer><span>8 bits</span><span>8 bits</span><span>8 bits</span><span>8 bits</span><b>32 bits → 2³² possible addresses</b></footer></div>}
function Classes(){return <div className="h2iv-classes">{[['A','0.0.0.0 → 127.255.255.255','8 / 24'],['B','128.0.0.0 → 191.255.255.255','16 / 16'],['C','192.0.0.0 → 223.255.255.255','24 / 8'],['D','224.0.0.0 → 239.255.255.255','multicast'],['E','240.0.0.0 → 255.255.255.255','experimental']].map(([c,r,b])=><Box title={`CLASS ${c}`} key={c}><code>{r}</code><small>{b}</small></Box>)}</div>}
function BinaryIp(){return <div className="h2iv-binary"><code>10111110</code><code>00001111</code><code>00011001</code><code>11110000</code><footer><b>190 . 15 . 25 . 240</b><span>source example: netID 190.15.25 · hostID 240</span></footer></div>}
function Cidr(){return <div className="h2iv-cidr"><code>192.30.250.00/18</code><div><span className="net">18 bits · netID</span><span className="host">14 bits · hostID</span></div><footer>CIDR moves the netID/hostID boundary instead of being locked to the normal class allocation.</footer></div>}
function Ipv6(){return <div className="h2iv-ipv6"><code>A8FB</code><i>:</i><code>7A88</code><i>:</i><code>FFF0</code><i>:</i><code>0FFF</code><i>:</i><code>3D21</code><i>:</i><code>2085</code><i>:</i><code>66FB</code><i>:</i><code>F0FA</code><footer>8 × 16-bit hexadecimal chunks = 128 bits</footer></div>}
function Compression(){return <div className="h2iv-compress"><code>900B:3E4A:AE41:<b>0000:0000</b>:AFF7:DD44:F1FF</code><i>↓ zero compression</i><code>900B:3E4A:AE41::<b>AFF7:DD44:F1FF</b></code><footer>:: can be applied only once in one IPv6 address, otherwise the result is ambiguous.</footer></div>}
function Url(){return <div className="h2iv-url"><code><span>http</span>://<b>www.hoddereducation.co.uk</b>/<i>computerscience</i></code><div><span>PROTOCOL</span><span>WEBSITE ADDRESS</span><span>PATH / RESOURCE</span></div></div>}
function Dns(){return <div className="h2iv-dns">{['USER + BROWSER','DNS SERVER 1','DNS SERVER 2','DNS SERVER 1 CACHE','WEBSITE SERVER'].map((x,i)=><section key={x}><span>{i+1}</span><strong>{x}</strong><small>{i===0?'type www.hoddereducation.co.uk':i===1?'local lookup; forward if absent':i===2?'map → 107.162.140.19':i===3?'return IP to user':'connect, download page, browser interprets HTML'}</small></section>)}</div>}

export function Chapter2InternetVisual({beat}:{beat:LessonPresentationBeat;reveal:number}){switch(beat.slideId){
case'h2-218-ethernet':return <Ethernet/>;case'h2-218-conflicts':return <IpConflict/>;case'h2-218-collisions':return <Collisions/>;case'h2-218-csma-cd':return <Csma/>;
case'h2-219-bitstreaming':return <Streaming/>;case'h2-219-buffering':return <Buffer/>;case'h2-219-pros-cons':return <ProsCons/>;case'h2-219-on-demand':return <StreamCompare/>;case'h2-219-real-time':return <StreamCompare/>;
case'h2-221-internet':return <InternetWeb mode="internet"/>;case'h2-221-web':return <InternetWeb mode="web"/>;case'h2-221-comparison':return <InternetWeb mode="compare"/>;case'h2-222-hardware':return <Hardware/>;case'h2-222-pstn':return <PstnVoip mode="pstn"/>;case'h2-222-voip':return <PstnVoip mode="voip"/>;case'h2-222-pstn-voip':return <PstnVoip mode="compare"/>;case'h2-222-satellites':return <Satellites/>;
case'h2-223-ipv4':return <Ipv4/>;case'h2-223-classes':return <Classes/>;case'h2-223-binary':return <BinaryIp/>;case'h2-223-cidr':return <Cidr/>;case'h2-223-ipv6':return <Ipv6/>;case'h2-223-ipv6-compression':return <Compression/>;case'h2-224-urls':return <Url/>;case'h2-225-dns':return <Dns/>;default:return null}}
