import type { LessonPresentationBeat } from './lesson-experience-model';
import './chapter2-presentation-visuals.css';

const VISUAL_IDS=['h2-overview','h2-21-infra','h2-21-benefits','h2-21-drawbacks','h2-212-client-server','h2-212-p2p','h2-212-comparison','h2-213-topologies','h2-214-sizes','h2-215-cloud','h2-215-cloud-storage','h2-216-wired','h2-216-attenuation','h2-216-fibre-modes','h2-216-wireless','h2-216-spread-spectrum','h2-216-wnic','h2-217-devices'] as const;
const FRAME_IDS=['h2n-l1-cover','h2n-l1-objectives','h2n-l1-starter','h2n-l1-recap','h2n-l2-cover','h2n-l2-objectives','h2n-l2-starter','h2n-l2-recap','h2n-l3-cover','h2n-l3-objectives','h2n-l3-starter','h2n-l3-recap','h2n-l4-cover','h2n-l4-objectives','h2n-l4-starter','h2n-l4-recap','h2n-reference-appendix'] as const;
export const CHAPTER_2_SOURCE_VISUAL_SLIDES=[...VISUAL_IDS];
export function hasChapter2PresentationVisual(beat:LessonPresentationBeat){return FRAME_IDS.includes(beat.id as never)||CHAPTER_2_SOURCE_VISUAL_SLIDES.includes(beat.slideId as never);}
const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="h2pv-panel"><b>{title}</b>{children}</section>;
function NetworkScale(){return <div className="h2pv-scale"><section><strong>PAN</strong><span>1–10 m</span></section><i>→</i><section><strong>LAN</strong><span>10 m–1000 m</span></section><i>→</i><section><strong>MAN</strong><span>1–100 km</span></section><i>→</i><section><strong>WAN</strong><span>100 km–1000+ km</span></section></div>}
function ClientServer(){return <div className="h2pv-client"><div className="clients"><span>CLIENT A</span><span>CLIENT B</span><span>CLIENT C</span></div><div className="links"><i/><i/><i/></div><section><small>DEDICATED</small><strong>SERVER</strong><p>central files · access control · security database · backup</p></section><footer>request → process → response</footer></div>}
function Peer(){return <div className="h2pv-peer">{['PEER A','PEER B','PEER C','PEER D','PEER E'].map((x,i)=><section key={x} data-i={i}><strong>{x}</strong><small>supplier + consumer</small></section>)}<svg viewBox="0 0 600 250" aria-hidden="true"><path d="M120 60L300 35L480 60L455 195L300 220L145 195Z M120 60L455 195 M480 60L145 195 M300 35L300 220"/></svg><footer>no central server · Hodder: normally no more than 10 nodes</footer></div>}
function Topologies(){return <div className="h2pv-topologies"><Panel title="BUS"><div className="bus"><i/><i/><i/><i/><span/></div><small>one central cable · terminators · one transmitter at a time</small></Panel><Panel title="STAR"><div className="star"><strong>SWITCH</strong>{[1,2,3,4].map(n=><i key={n}/>)}</div><small>dedicated links · central hub/switch</small></Panel><Panel title="MESH"><div className="mesh">{[1,2,3,4,5].map(n=><i key={n}/>)}</div><small>routing = shortest route · flooding = all routes</small></Panel><Panel title="HYBRID"><div className="hybrid"><span>BUS</span><span>STAR</span><span>MESH</span></div><small>combination of topologies</small></Panel></div>}
function Infrastructure(){return <div className="h2pv-infra"><Panel title="HARDWARE"><strong>LAN cards · routers · switches</strong><span>wireless routers · cabling</span></Panel><Panel title="SOFTWARE"><strong>network management</strong><span>firewall · security utilities</span></Panel><Panel title="SERVICES"><strong>DSL · satellite · wireless</strong><span>IP addressing</span></Panel></div>}
function Pros({negative=false}:{negative?:boolean}){const items=negative?['initial cabling/server cost','complex management','server failure can affect whole network','malware/hacking can spread']:['share printers/devices','cheaper network licences','share files + central reliable data','central backup','email + instant messaging','manager applies access rights'];return <div className={`h2pv-pros ${negative?'negative':''}`}>{items.map((x,i)=><section key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></section>)}</div>}
function Overview(){return <div className="h2pv-overview"><div className="core"><strong>COMMUNICATION</strong><small>CHAPTER 2</small></div>{['NETWORKS','MODELS','TOPOLOGIES','CLOUD','WIRED / WIRELESS','ETHERNET','STREAMING','INTERNET','IP · URL · DNS'].map(x=><span key={x}>{x}</span>)}</div>}
function Cloud(){return <div className="h2pv-cloud"><div className="cloud-core"><small>OFF-SITE SERVERS</small><strong>CLOUD</strong><span>storage · software · networking</span></div><div className="cloud-branches"><Panel title="PUBLIC"><p>customer and provider are separate</p><small>provider controls infrastructure</small></Panel><Panel title="PRIVATE"><p>dedicated environment</p><small>behind organisation firewall</small></Panel><Panel title="HYBRID"><p>sensitive → private</p><small>less sensitive → public</small></Panel></div><footer>data redundancy → copies on several servers → availability during repair / maintenance</footer></div>}
function CloudStorage(){return <div className="h2pv-balance"><Panel title="BENEFITS"><p>any device + any location</p><p>remote backup / disaster recovery</p><p>no single external storage device</p><p>very large storage capacity</p></Panel><div className="axis">CLOUD<br/>STORAGE</div><Panel title="RISKS"><p>depends on stable internet</p><p>large capacity can cost more</p><p>provider failure threatens backups</p><p>security control passes to provider</p></Panel></div>}
function Wired(){return <div className="h2pv-media"><Panel title="TWISTED PAIR"><div className="cable copper"/><p>electrical signal</p><small>cheap · more interference</small></Panel><Panel title="COAXIAL"><div className="cable coax"/><p>shielded copper</p><small>higher capacity · greater attenuation</small></Panel><Panel title="FIBRE OPTIC"><div className="cable fibre"/><p>light pulses</p><small>highest rate · lowest attenuation · long distance</small></Panel></div>}
function Attenuation(){return <div className="h2pv-spectrum"><header><span>RADIO WAVES</span><span>MICROWAVES</span><span>INFRARED</span></header><div className="meter"><b>bandwidth</b><i/><i/><i className="best"/></div><div className="meter reverse"><b>penetration</b><i className="best"/><i/><i/></div><div className="meter reverse"><b>attenuation</b><i className="best"/><i/><i/></div><footer>Hodder compares bandwidth, penetration and attenuation separately — do not treat them as the same property.</footer></div>}
function FibreModes(){return <div className="h2pv-fibre"><Panel title="SINGLE-MODE"><div className="ray single"><i/></div><p>smaller core · less reflection</p><strong>faster + further</strong><small>CATV / telecommunications</small></Panel><Panel title="MULTI-MODE"><div className="ray multi"><i/><i/><i/></div><p>more reflection in core</p><strong>shorter distance</strong><small>LAN connections</small></Panel></div>}
function Wireless(){return <div className="h2pv-wireless"><div className="wap"><small>IEEE 802.11</small><strong>WiFi / WAP</strong><i/><i/><i/></div><div className="devices"><span>LAPTOP</span><span>PHONE</span><span>TABLET</span></div><footer><b>Bluetooth · 2.45 GHz</b><span>79 channels · automatic connection</span></footer></div>}
function FrequencyHop(){return <div className="h2pv-hop"><header>spread spectrum frequency hopping</header>{['f₁','f₂','f₃','f₄','f₅'].map((f,i)=><div key={f}><b>{f}</b><span style={{width:`${20+i*14}%`}}/></div>)}<footer>rapid channel changes → reduced interference between nearby Bluetooth pairs</footer></div>}
function Wnic(){return <div className="h2pv-mode"><Panel title="INFRASTRUCTURE MODE"><div className="mode-map"><span>DEVICE</span><i>→</i><strong>WAP</strong><i>→</i><span>HUB / SWITCH</span></div><small>same security + authentication · WAP required</small></Panel><Panel title="AD-HOC MODE"><div className="mode-map"><span>DEVICE</span><i>↔</i><span>DEVICE</span></div><small>direct communication · no WAP</small></Panel></div>}
function Devices(){return <div className="h2pv-devices">{[['HUB','broadcasts to every port'],['SWITCH','forwards using destination'],['ROUTER','connects networks / chooses route'],['BRIDGE','connects LAN segments'],['GATEWAY','connects unlike systems'],['NIC / WNIC','device network interface']].map(([a,b])=><Panel key={a} title={a}><p>{b}</p></Panel>)}</div>}
const lessonNames=['Network foundations','Cloud, media and wireless','Network hardware','Ethernet and streaming'];
function LessonFrame({beat}:{beat:LessonPresentationBeat}){
  const match=beat.id.match(/^h2n-l(\d)-/);const active=match?Number(match[1]):0;const stage=beat.id.split('-').at(-1);
  return <div className={`h2pv-session h2pv-session--${stage}`}>
    <div className="h2pv-session-map">{lessonNames.map((name,index)=><section className={active===index+1?'active':''} key={name}><span>{index+1}</span><div><small>LESSON {index+1}</small><strong>{name}</strong></div></section>)}</div>
    <div className="h2pv-session-network" aria-hidden="true"><span className="computer">CLIENT</span><i/><span className="switch">SWITCH</span><i/><span className="router">ROUTER</span><i/><span className="cloud">NETWORK</span><b className="packet">DATA</b></div>
    <footer>{beat.id==='h2n-reference-appendix'?'Optional source-completeness reference':'45–55 minutes · explanation · guided practice · retrieval'}</footer>
  </div>;
}
export function Chapter2PresentationVisual({beat}:{beat:LessonPresentationBeat;reveal:number}){if(FRAME_IDS.includes(beat.id as never))return <LessonFrame beat={beat}/>;switch(beat.slideId){case'h2-overview':return <Overview/>;case'h2-21-infra':return <Infrastructure/>;case'h2-21-benefits':return <Pros/>;case'h2-21-drawbacks':return <Pros negative/>;case'h2-212-client-server':return <ClientServer/>;case'h2-212-p2p':return <Peer/>;case'h2-212-comparison':return <div className="h2pv-compare"><ClientServer/><Peer/></div>;case'h2-213-topologies':return <Topologies/>;case'h2-214-sizes':return <NetworkScale/>;case'h2-215-cloud':return <Cloud/>;case'h2-215-cloud-storage':return <CloudStorage/>;case'h2-216-wired':return <Wired/>;case'h2-216-attenuation':return <Attenuation/>;case'h2-216-fibre-modes':return <FibreModes/>;case'h2-216-wireless':return <Wireless/>;case'h2-216-spread-spectrum':return <FrequencyHop/>;case'h2-216-wnic':return <Wnic/>;case'h2-217-devices':return <Devices/>;default:return <NetworkScale/>;}}
