const emphasis=(reveal:number,step:number)=>({opacity:reveal>=step?1:.32,transition:'opacity .2s ease'});
const mono={fontFamily:'var(--font-mono)'} as const;

/** Hodder p.340. Hop count prevents lost packets bouncing indefinitely through routers. */
export function Chapter14HopHero({reveal}:{reveal:number}){
  const routers=[['R1','3'],['R2','2'],['R3','1'],['R4','0'] ] as const;
  return <div className="h14m-content-v2" aria-label="Hop number decreases at every router until the packet is delivered or deleted" style={{display:'grid',gap:20,minHeight:430,alignContent:'center'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',paddingBottom:10,borderBottom:'2px solid var(--h14-cyan)'}}><div><b style={{...mono,color:'var(--h14-cyan)',fontSize:11}}>HODDER p.340 · HOPPING</b><strong style={{display:'block',marginTop:5,fontSize:24}}>STOP LOST PACKETS BOUNCING FOREVER</strong></div><small style={{color:'var(--h14-muted)'}}>finite router-to-router lifetime</small></header>
    <main style={{display:'grid',gridTemplateColumns:'150px repeat(4,1fr) 180px',gap:12,alignItems:'center'}}>
      <section style={{...emphasis(reveal,1),padding:'18px 14px',textAlign:'center',border:'1px solid var(--h14-blue)',background:'rgba(84,166,255,.05)'}}><b style={{...mono,color:'var(--h14-cyan)',fontSize:10}}>PACKET HEADER</b><strong style={{display:'block',marginTop:8,fontSize:25}}>HOP = 4</strong><small style={{display:'block',marginTop:7,color:'var(--h14-muted)'}}>initial finite value</small></section>
      {routers.map(([router,hop],i)=><section key={router} style={{...emphasis(reveal,i+1),minHeight:155,padding:'16px 12px',display:'grid',placeItems:'center',textAlign:'center',borderTop:`4px solid ${hop==='0'?'var(--h14-red)':'var(--h14-cyan)'}`,borderBottom:'1px solid var(--h14-line)',background:hop==='0'?'rgba(255,100,100,.04)':'rgba(82,224,210,.04)'}}><b style={{...mono,color:'var(--h14-muted)',fontSize:10}}>{router}</b><strong style={{fontSize:34,color:hop==='0'?'var(--h14-red)':'var(--h14-cyan)'}}>{hop}</strong><small style={{color:'var(--h14-muted)'}}>after router: hop − 1</small>{i<routers.length-1?<span style={{position:'absolute',opacity:0}}>→</span>:null}</section>)}
      <section style={{...emphasis(reveal,4),padding:'18px 14px',textAlign:'center',border:'1px solid var(--h14-red)',background:'rgba(255,100,100,.04)'}}><b style={{...mono,color:'var(--h14-red)',fontSize:10}}>IF NOT AT DESTINATION</b><strong style={{display:'block',marginTop:8,fontSize:23}}>DELETE PACKET</strong><small style={{display:'block',marginTop:7,color:'var(--h14-muted)'}}>when hop number = 0 at the next router</small></section>
    </main>
    <footer style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><span style={{...emphasis(reveal,3),padding:'11px 13px',borderLeft:'3px solid var(--h14-amber)',background:'rgba(255,200,87,.04)',fontSize:11.5,color:'var(--h14-muted)'}}><b style={{color:'var(--h14-ink)'}}>Why:</b> a lost packet could otherwise keep moving from router to router and clog the network.</span><span style={{...emphasis(reveal,4),padding:'11px 13px',borderLeft:'3px solid var(--h14-cyan)',background:'rgba(82,224,210,.04)',fontSize:11.5,color:'var(--h14-muted)'}}><b style={{color:'var(--h14-ink)'}}>Where the limit comes from:</b> the finite hop number is determined by the network protocol and routing table being used.</span></footer>
  </div>;
}

/** Hodder p.340. Three packet-control ideas: hop limit, error check and optional priority. */
export function Chapter14PacketControlHero({reveal}:{reveal:number}){
  const controls=[
    {title:'HOP NUMBER',accent:'var(--h14-cyan)',flow:['HEADER: hop = N','each router: N − 1','hop = 0 → delete'],note:'Prevents lost packets circulating indefinitely and clogging the network.'},
    {title:'CHECKSUM / PARITY',accent:'var(--h14-amber)',flow:['sender calculates check value','value travels in packet header','destination recalculates','different values → request re-send'],note:'The source names checksum or parity check as packet error-checking techniques.'},
    {title:'PRIORITY',accent:'var(--h14-blue)',flow:['priority value may be added','router reads priority','value indicates packet queue'],note:'A high priority value indicates which packet queue should be used.'},
  ] as const;
  return <div className="h14m-content-v2" aria-label="Packet control using hop number checksum parity and priority" style={{display:'grid',gap:18,minHeight:430,alignContent:'center'}}>
    <header style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',paddingBottom:10,borderBottom:'2px solid var(--h14-cyan)'}}><div><b style={{...mono,color:'var(--h14-cyan)',fontSize:11}}>HODDER p.340 · PACKET CONTROL</b><strong style={{display:'block',marginTop:5,fontSize:24}}>LIFETIME · ERROR CHECK · QUEUE</strong></div><small style={{color:'var(--h14-muted)'}}>all travel as header/control information</small></header>
    <main style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:16}}>{controls.map((control,i)=><section key={control.title} style={{...emphasis(reveal,i+1),minHeight:300,padding:'18px 18px',display:'grid',gridTemplateRows:'auto 1fr auto',gap:13,borderTop:`4px solid ${control.accent}`,borderBottom:'1px solid var(--h14-line)',background:'linear-gradient(180deg,rgba(84,166,255,.055),rgba(8,21,36,.18))'}}><header><b style={{...mono,color:control.accent,fontSize:12}}>{control.title}</b></header><div style={{display:'grid',alignContent:'start',gap:8}}>{control.flow.map((step,j)=><div key={step} style={{display:'grid',gridTemplateColumns:'28px 1fr',gap:9,alignItems:'center',padding:'8px 0',borderBottom:'1px solid var(--h14-line)'}}><span style={{display:'grid',placeItems:'center',width:26,height:26,borderRadius:'50%',border:`1px solid ${control.accent}`,color:control.accent,...mono,fontSize:9}}>{j+1}</span><p style={{margin:0,fontSize:11.2,lineHeight:1.38,color:'var(--h14-muted)'}}>{step}</p></div>)}</div><footer style={{paddingTop:9,borderTop:`1px solid ${control.accent}`,fontSize:10.8,lineHeight:1.42,color:'var(--h14-muted)'}}>{control.note}</footer></section>)}</main>
    <div style={{...emphasis(reveal,3),padding:'10px 13px',borderLeft:'3px solid var(--h14-amber)',background:'rgba(255,200,87,.04)',fontSize:11.5,color:'var(--h14-muted)'}}>Exam connection: <b style={{color:'var(--h14-ink)'}}>hop number controls lifetime; checksum/parity checks integrity; priority influences queue selection.</b></div>
  </div>;
}
