import type { LessonPresentationBeat } from './lesson-experience-model';
import './chapter20-further-programming-visuals.css';

export const CHAPTER_20_FURTHER_PROGRAMMING_VISUAL_IDS = [
  'h20-2011-low-level','h20-2012-imperative','h20-2013-oop-foundations','h20-2013-class-implementations',
  'h20-2013-data-hiding','h20-2013-inheritance','h20-2013-polymorphism-overloading','h20-2013-containment',
  'h20-2013-accessors-lifecycle','h20-2013-binary-tree-oop','h20-2014-declarative','h20-2014-prolog-facts-queries',
  'h20-2014-prolog-rules','h20-2021-record-files','h20-2021-put-get-record','h20-2021-sequential-update',
  'h20-2021-random-write','h20-2021-random-read','h20-2022-exception-concept','h20-2022-language-handlers','h20-2022-file-exceptions',
] as const;

export function hasChapter20FurtherProgrammingVisual(beat:LessonPresentationBeat){return CHAPTER_20_FURTHER_PROGRAMMING_VISUAL_IDS.includes(beat.slideId as never);}
const state=(reveal:number,step:number)=>reveal>=step?'is-active':'is-upcoming';

function Paradigm({reveal,kind}:{reveal:number;kind:'low'|'imperative'|'declarative'}){
  const data=kind==='low'
    ?[['MACHINE / ASSEMBLY','hardware-oriented instructions'],['REGISTERS + ADDRESSES','explicit storage locations'],['FAST / COMPACT','but processor-specific and harder to maintain']]
    :kind==='imperative'
      ?[['STATE','variables hold changing program data'],['STATEMENTS','assignments change state step-by-step'],['CONTROL FLOW','sequence · selection · iteration']]
      :[['KNOWLEDGE / FACTS','describe what is true'],['RULES','describe relationships'],['QUERY','ask what follows from the knowledge base']];
  return <div className="h20fp h20fp-paradigm" aria-label={`${kind} programming paradigm`}>{data.map(([a,b],i)=><section key={a} className={state(reveal,i+1)}><b>{a}</b><span>{b}</span></section>)}</div>;
}

function OopFoundations({reveal}:{reveal:number}){return <div className="h20fp h20fp-oop" aria-label="OOP class object encapsulation"><section className={state(reveal,1)}><b>CLASS</b><span>template / user-defined type</span></section><i>→</i><section className={state(reveal,2)}><b>OBJECT</b><span>instance with attributes + methods</span></section><i>→</i><section className={state(reveal,3)}><b>ENCAPSULATION</b><span>data and operations grouped together</span></section></div>}
function ClassImplementation({reveal}:{reveal:number}){return <div className="h20fp h20fp-class" aria-label="Class implementation"><div className={`h20fp-classbox ${state(reveal,1)}`}><b>CLASS BankAccount</b><span>balance : REAL</span><span>deposit(amount)</span><span>withdraw(amount)</span><span>getBalance()</span></div><section className={state(reveal,2)}><b>OBJECT A</b><span>balance = 120</span></section><section className={state(reveal,3)}><b>OBJECT B</b><span>balance = 450</span></section></div>}
function DataHiding({reveal}:{reveal:number}){return <div className="h20fp h20fp-hide" aria-label="Data hiding private state public methods"><div className={`h20fp-private ${state(reveal,1)}`}><b>PRIVATE DATA</b><span>internal attributes hidden from direct external access</span></div><i>⇄</i><section className={state(reveal,2)}><b>PUBLIC METHODS</b><span>controlled interface</span><small>validation can protect invariants</small></section><footer className={state(reveal,3)}>DATA HIDING supports encapsulation by controlling how object state is read or changed.</footer></div>}
function Inheritance({reveal}:{reveal:number}){return <div className="h20fp h20fp-inherit" aria-label="Inheritance superclass subclass"><div className={`h20fp-parent ${state(reveal,1)}`}><b>SUPERCLASS Vehicle</b><span>speed · move()</span></div><div className="h20fp-children"><section className={state(reveal,2)}><b>Car</b><span>inherits Vehicle</span></section><section className={state(reveal,2)}><b>Bicycle</b><span>inherits Vehicle</span></section><section className={state(reveal,3)}><b>Bus</b><span>inherits + extends</span></section></div><footer className={state(reveal,3)}>INHERITANCE reuses common attributes/methods while subclasses add or specialise behaviour.</footer></div>}
function Polymorphism({reveal}:{reveal:number}){return <div className="h20fp h20fp-poly" aria-label="Polymorphism and overloading"><section className={state(reveal,1)}><b>POLYMORPHISM</b><span>same method call → behaviour depends on object type</span><code>shape.draw()</code></section><section className={state(reveal,2)}><b>OVERLOADING</b><span>same method name → different parameter lists</span><code>print(x) / print(x,y)</code></section><footer className={state(reveal,3)}>Both reduce interface complexity while supporting different implementations.</footer></div>}
function Containment({reveal}:{reveal:number}){return <div className="h20fp h20fp-contain" aria-label="Object containment composition"><div className={`h20fp-parent ${state(reveal,1)}`}><b>Car OBJECT</b></div><div className="h20fp-children"><section className={state(reveal,2)}><b>Engine object</b></section><section className={state(reveal,2)}><b>Wheel objects</b></section><section className={state(reveal,3)}><b>Navigation object</b></section></div><footer className={state(reveal,3)}>CONTAINMENT / composition: one object stores or owns other objects as parts.</footer></div>}
function Lifecycle({reveal}:{reveal:number}){return <div className="h20fp h20fp-life" aria-label="Getter setter constructor destructor"><section className={state(reveal,1)}><b>CONSTRUCTOR</b><span>initialise new object</span></section><i>→</i><section className={state(reveal,2)}><b>GETTER / SETTER</b><span>controlled read/write access</span></section><i>→</i><section className={state(reveal,3)}><b>DESTRUCTOR</b><span>clean up when object lifecycle ends</span></section></div>}
function TreeOop({reveal}:{reveal:number}){return <div className="h20fp h20fp-tree" aria-label="Binary tree represented with node objects"><div className={`h20fp-node root ${state(reveal,1)}`}>42</div><div className="h20fp-tree-row"><div className={`h20fp-node ${state(reveal,2)}`}>19</div><div className={`h20fp-node ${state(reveal,2)}`}>67</div></div><div className="h20fp-tree-row"><div className={`h20fp-node ${state(reveal,3)}`}>left/right refs</div><div className={`h20fp-node ${state(reveal,3)}`}>left/right refs</div></div><footer className={state(reveal,3)}>A Node class can contain data plus references to left/right child Node objects.</footer></div>}

function PrologFacts({reveal}:{reveal:number}){return <div className="h20fp h20fp-prolog" aria-label="Prolog facts and queries"><section className={state(reveal,1)}><b>FACTS</b><code>parent(ali, sara).</code><code>parent(sara, kamol).</code></section><i>→</i><section className={state(reveal,2)}><b>QUERY</b><code>?- parent(ali, sara).</code><span>true</span></section><footer className={state(reveal,3)}>PROLOG stores a KNOWLEDGE BASE of facts/rules and tries to satisfy a query logically.</footer></div>}
function PrologRules({reveal}:{reveal:number}){return <div className="h20fp h20fp-prolog" aria-label="Prolog rule reasoning"><section className={state(reveal,1)}><b>RULE</b><code>grandparent(X,Z) :- parent(X,Y), parent(Y,Z).</code></section><i>→</i><section className={state(reveal,2)}><b>QUERY</b><code>?- grandparent(ali, kamol).</code></section><i>→</i><section className={state(reveal,3)}><b>MATCH FACTS</b><span>true when a value for Y satisfies both goals</span></section></div>}

function FileTypes({reveal}:{reveal:number}){return <div className="h20fp h20fp-files" aria-label="Serial sequential and random record files"><section className={state(reveal,1)}><b>SERIAL</b><span>records stored in arrival order</span></section><section className={state(reveal,2)}><b>SEQUENTIAL</b><span>records stored in key order</span></section><section className={state(reveal,3)}><b>RANDOM</b><span>record address calculated / accessed directly</span></section></div>}
function PutGet({reveal}:{reveal:number}){return <div className="h20fp h20fp-putget" aria-label="PUTRECORD GETRECORD record file operations"><section className={state(reveal,1)}><b>PUTRECORD</b><span>write complete record to file</span></section><i>⇄</i><section className={state(reveal,2)}><b>RECORD FILE</b><span>fixed structured records</span></section><i>⇄</i><section className={state(reveal,3)}><b>GETRECORD</b><span>read complete record into record variable</span></section></div>}
function SequentialUpdate({reveal}:{reveal:number}){return <div className="h20fp h20fp-seq" aria-label="Sequential file update using master transaction and new file"><section className={state(reveal,1)}><b>OLD MASTER</b><span>read current record</span></section><section className={state(reveal,1)}><b>TRANSACTION</b><span>matching key contains update</span></section><i>→</i><section className={state(reveal,2)}><b>MERGE / UPDATE</b><span>compare keys in order</span></section><i>→</i><section className={state(reveal,3)}><b>NEW MASTER</b><span>write updated sequence</span></section></div>}
function RandomAccess({reveal,read=false}:{reveal:number;read?:boolean}){return <div className="h20fp h20fp-random" aria-label={`Random file ${read?'read':'write'}`}><section className={state(reveal,1)}><b>KEY</b><span>e.g. customer ID</span></section><i>→</i><section className={state(reveal,2)}><b>HASH</b><span>calculate record location</span></section><i>→</i><section className={state(reveal,2)}><b>SEEK</b><span>move directly to location</span></section><i>→</i><section className={state(reveal,3)}><b>{read?'GETRECORD':'PUTRECORD'}</b><span>{read?'retrieve record':'store record'}</span></section></div>}

function ExceptionConcept({reveal}:{reveal:number}){return <div className="h20fp h20fp-exception" aria-label="Exception handling try raise catch finally"><section className={state(reveal,1)}><b>TRY</b><span>run code that may fail</span></section><i>→</i><section className={state(reveal,2)}><b>EXCEPTION</b><span>run-time problem such as divide by zero</span></section><i>→</i><section className={state(reveal,3)}><b>HANDLER</b><span>catch / except and recover or report</span></section></div>}
function LanguageHandlers({reveal}:{reveal:number}){return <div className="h20fp h20fp-handlers" aria-label="Exception handler syntax across languages"><section className={state(reveal,1)}><b>PYTHON</b><code>try: ... except ...</code></section><section className={state(reveal,2)}><b>VB.NET</b><code>Try ... Catch ... Finally</code></section><section className={state(reveal,3)}><b>JAVA</b><code>try { } catch (...) { }</code></section></div>}
function FileExceptions({reveal}:{reveal:number}){return <div className="h20fp h20fp-fileex" aria-label="File processing exception handling"><section className={state(reveal,1)}><b>OPEN / READ / WRITE</b><span>file operation attempted</span></section><i>→</i><section className={state(reveal,2)}><b>FILE EXCEPTION?</b><span>missing file · access problem · invalid data</span></section><i>→</i><section className={state(reveal,3)}><b>HANDLE + CLOSE SAFELY</b><span>report / recover and release resource</span></section></div>}

export function Chapter20FurtherProgrammingVisual({beat,reveal}:{beat:LessonPresentationBeat;reveal:number}){
  switch(beat.slideId){
    case 'h20-2011-low-level':return <Paradigm reveal={reveal} kind="low"/>; case 'h20-2012-imperative':return <Paradigm reveal={reveal} kind="imperative"/>;
    case 'h20-2013-oop-foundations':return <OopFoundations reveal={reveal}/>; case 'h20-2013-class-implementations':return <ClassImplementation reveal={reveal}/>;
    case 'h20-2013-data-hiding':return <DataHiding reveal={reveal}/>; case 'h20-2013-inheritance':return <Inheritance reveal={reveal}/>;
    case 'h20-2013-polymorphism-overloading':return <Polymorphism reveal={reveal}/>; case 'h20-2013-containment':return <Containment reveal={reveal}/>;
    case 'h20-2013-accessors-lifecycle':return <Lifecycle reveal={reveal}/>; case 'h20-2013-binary-tree-oop':return <TreeOop reveal={reveal}/>;
    case 'h20-2014-declarative':return <Paradigm reveal={reveal} kind="declarative"/>; case 'h20-2014-prolog-facts-queries':return <PrologFacts reveal={reveal}/>; case 'h20-2014-prolog-rules':return <PrologRules reveal={reveal}/>;
    case 'h20-2021-record-files':return <FileTypes reveal={reveal}/>; case 'h20-2021-put-get-record':return <PutGet reveal={reveal}/>; case 'h20-2021-sequential-update':return <SequentialUpdate reveal={reveal}/>;
    case 'h20-2021-random-write':return <RandomAccess reveal={reveal}/>; case 'h20-2021-random-read':return <RandomAccess reveal={reveal} read/>;
    case 'h20-2022-exception-concept':return <ExceptionConcept reveal={reveal}/>; case 'h20-2022-language-handlers':return <LanguageHandlers reveal={reveal}/>; case 'h20-2022-file-exceptions':return <FileExceptions reveal={reveal}/>;
    default:return null;
  }
}
