import type { LessonSlide } from './lesson-content-full';

/**
 * Classroom-presenter adaptation of Hodder Cambridge IGCSE/O Level Computer Science,
 * Chapter 7 (pp. 258–298 in the supplied chapter extract).
 *
 * Important: these slides are appended AFTER the existing 15-slide guided-discovery
 * lesson. They do not replace or reorder the discovery sequence.
 */
export const CHAPTER_7_BOOK_SLIDES: LessonSlide[] = [
  {
    id: 'ch7-book-00-route', section: 'Book Deep Dive · 7.1', subtopicCode: '7.1',
    eyebrow: 'BOOK DEEP DIVE · CHAPTER 7 · AFTER THE DISCOVERY LESSON',
    title: 'Now build the complete Chapter 7 toolkit',
    lead: 'The challenge you completed introduced the development process. The next screens extend that experience with every concept, example, activity and exam skill in the supplied Chapter 7 extract.',
    bullets: ['7.1 Program development life cycle','7.2 Systems, sub-systems and decomposition','7.3 Explaining an algorithm','7.4 Standard methods','7.5 Validation and verification','7.6 Test data','7.7 Trace tables','7.8 Identifying errors','7.9 Writing and amending algorithms'],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-71-abstraction-maps', section: 'Book Deep Dive · 7.1', subtopicCode: '7.1',
    eyebrow: '7.1.1 · ANALYSIS · FIGURE 7.1',
    title: 'The same place can need different information',
    lead: 'A road map and a rail map represent the same area, but each keeps only the information needed for a different journey.',
    bullets: ['Road map: roads, junctions and routes matter.','Rail map: stations, lines and connections matter.','Information that does not help the chosen task can be removed.'],
    activity: { title: 'Choose what matters', prompt: 'For a walking map of your school, write four details to KEEP and four details to IGNORE. Every KEEP item must help a person reach a destination.', reveal: 'Possible KEEP items: buildings, paths, entrances, room labels. Possible IGNORE items: wall colours, teacher birthdays, desk brands, ceiling height.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-71-decompose-dressed', section: 'Book Deep Dive · 7.1', subtopicCode: '7.1',
    eyebrow: '7.1.1 · ANALYSIS · FIND OUT MORE',
    title: 'Break “getting dressed” into smaller actions',
    lead: 'Start with the three broad actions from the book, then refine each one until every final action is simple enough to perform directly.',
    bullets: ['Select items to wear.','Remove any clothes already being worn.','Put the selected items on in order.'],
    activity: { title: 'Refine the task', prompt: 'Expand the three actions into at least eight smaller actions. Number them in the order they must be completed.', reveal: 'There is no single correct decomposition. A strong answer creates smaller actions that are clear, ordered and individually manageable.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-71-cycle-consolidation', section: 'Book Deep Dive · 7.1', subtopicCode: '7.1',
    eyebrow: '7.1.2–7.1.4 · CONSOLIDATE THE FOUR STAGES',
    title: 'Connect specification, design, implementation and checking',
    lead: 'The book separates the development cycle into analysis, design, coding with iterative testing, and testing of the completed program.',
    bullets: ['Analysis produces a clear requirements specification.','Design decides the tasks, how each task will work and how tasks fit together.','Coding develops program modules in a suitable programming language.','Iterative testing repeats module test → amend → retest.','Final testing runs the completed program with different sets of test data.'],
    activity: { title: 'Put five statements in order', prompt: 'Write 1–5 beside: create requirements · plan tasks · write a module · amend after a failed module test · run the completed system with several data sets.', reveal: '1 requirements · 2 plan tasks · 3 write module · 4 amend/retest module · 5 test completed system.' },
    accent: 'amber',
  },

  {
    id: 'ch7-book-72-system', section: '7.2 Systems & Decomposition', subtopicCode: '7.2',
    eyebrow: '7.2 · COMPUTER SYSTEMS AND SUB-SYSTEMS',
    title: 'A computer system is built from interacting parts',
    lead: 'A computer system can include software, data, hardware, communications and people. Large or small systems can be divided into sub-systems.',
    bullets: ['A sub-system can be divided again.','Continue until a final sub-system performs one clear action.','Different programmers can develop and test separate sub-systems in parallel.'],
    activity: { title: 'Find five systems', prompt: 'List five computer systems you use in a normal day. Label each one SMALL, MEDIUM or LARGE and give one reason for each label.' },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-72-top-down', section: '7.2 Systems & Decomposition', subtopicCode: '7.2',
    eyebrow: '7.2.1 · TOP-DOWN DESIGN',
    title: 'Refine a system until each final part performs one action',
    lead: 'Top-down design repeatedly breaks a system into smaller sub-systems. The repeated breakdown is called stepwise refinement.',
    keyTerms: [
      {term:'Top-down design',definition:'Break a computer system into sub-systems, then keep breaking each sub-system into smaller sub-systems.'},
      {term:'Stepwise refinement',definition:'Continue the breakdown until each final sub-system performs a single action.'},
    ],
    activity: { title: 'Refine one system', prompt: 'Choose one system from the previous screen. Draw level 1, level 2 and level 3. Every level-3 box must name one action only.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-72-ipos', section: '7.2 Systems & Decomposition', subtopicCode: '7.2',
    eyebrow: '7.2.2 · COMPONENT PARTS',
    title: 'Decompose a problem into Input, Process, Output and Storage',
    lead: 'The book uses four component types to describe what a computer system receives, does, produces and keeps for future use.',
    keyTerms: [
      {term:'Input',definition:'Data entered while the system is active.'},
      {term:'Process',definition:'Tasks performed using input data and any stored data.'},
      {term:'Output',definition:'Information displayed or printed for users.'},
      {term:'Storage',definition:'Data saved for future use.'},
    ],
    accent: 'emerald',
  },
  {
    id: 'ch7-book-72-alarm-ipos', section: '7.2 Systems & Decomposition', subtopicCode: '7.2',
    eyebrow: 'EXAMPLE 1 · ALARM APP · ACTIVITY 7.1',
    title: 'Classify the parts of an alarm app',
    lead: 'Use the four component types to describe the alarm app.',
    bullets: ['Possible inputs: set an alarm time, remove an alarm, switch off, press snooze.','Processes: compare current time with stored alarm times, manage snooze, add/remove alarms.','Output: alarm sound or tune.','Storage: saved alarm time(s).'],
    activity: { title: 'Activity 7.1', prompt: 'Choose one of the five computer systems you listed earlier. Create four headings — INPUT, PROCESS, OUTPUT, STORAGE — and place at least two correct items under each heading.' },
    accent: 'amber',
  },

  {
    id: 'ch7-book-72-structure-basic', section: '7.2 Structure Diagrams', subtopicCode: '7.2',
    eyebrow: '7.2.3 · STRUCTURE DIAGRAMS · FIGURE 7.2',
    title: 'Show a system as a hierarchy',
    lead: 'A structure diagram shows top-down design. Each lower level gives a more detailed breakdown of the level above.',
    bullets: ['The top box represents the whole system.','The next row contains its main sub-systems.','Lower rows refine selected sub-systems further.','The diagram shows hierarchy, not execution order.'],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-72-alarm-tree', section: '7.2 Structure Diagrams', subtopicCode: '7.2',
    eyebrow: 'EXAMPLE 2 · FIGURE 7.3',
    title: 'Read the alarm-app structure diagram',
    lead: 'The alarm app is divided into Set alarm, Check time and Sound alarm, then those parts are refined again.',
    activity: { title: 'Activity 7.2', prompt: 'Break the CHECK TIME sub-system into at least three smaller sub-systems. Each final box must describe one action.', reveal: 'Possible boxes: get current time · compare current time with alarm time · decide whether to wait or sound the alarm.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-72-teeth', section: '7.2 Structure Diagrams', subtopicCode: '7.2',
    eyebrow: 'FIND OUT MORE · STRUCTURE DIAGRAM PRACTICE',
    title: 'Create a structure diagram for cleaning your teeth',
    lead: 'Build a hierarchy first; do not draw the execution sequence yet.',
    activity: { title: 'Draw and test the hierarchy', prompt: 'Create at least three main sub-systems and refine each one. Give your diagram to another student and ask them to identify any missing action.' },
    accent: 'emerald',
  },

  {
    id: 'ch7-book-72-flow-purpose', section: '7.2 Flowcharts', subtopicCode: '7.2',
    eyebrow: 'FLOWCHARTS · FIGURE 7.4',
    title: 'A flowchart shows the steps and their execution order',
    lead: 'The ordered steps that complete a task form an algorithm. A flowchart communicates the algorithm visually.',
    activity: { title: 'Read the alarm-time flow', prompt: 'Trace this logic: get the current time → compare it with the alarm time → if they match, sound the alarm; otherwise wait 30 seconds and check again. State which step repeats.' },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-72-flow-symbols-a', section: '7.2 Flowcharts', subtopicCode: '7.2',
    eyebrow: 'FIGURES 7.5–7.7 · STANDARD SYMBOLS',
    title: 'Use the correct symbol for Begin/End, Process and Input/Output',
    keyTerms: [
      {term:'Terminator',definition:'Used at the beginning and end of a flowchart.'},
      {term:'Process',definition:'Shows an action or assignment; can also name a process defined elsewhere.'},
      {term:'Input/Output',definition:'The same parallelogram symbol is used for input data and output information.'},
    ],
    activity: { title: 'Label three statements', prompt: 'Choose the correct symbol for each: START · Total ← Total + Mark · OUTPUT "Error".' , reveal: 'START → terminator · assignment → process · OUTPUT → input/output.'},
    accent: 'cyan',
  },
  {
    id: 'ch7-book-72-flow-symbols-b', section: '7.2 Flowcharts', subtopicCode: '7.2',
    eyebrow: 'FIGURES 7.8–7.9 · DECISIONS AND FLOW LINES',
    title: 'A decision must have two labelled exits',
    lead: 'Decision symbols select the next action. Flow lines use arrows to show direction, normally top-to-bottom and left-to-right.',
    bullets: ['A decision is drawn as a diamond.','It has two outputs.','Label both outputs clearly, for example YES and NO.','Arrows show the direction of control.'],
    activity: { title: 'Fix the diagram', prompt: 'Draw a decision “X > B?”. Add exactly two outgoing arrows and label them YES and NO. On the YES path add the process B ← X.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-72-ticket-flow', section: '7.2 Flowcharts', subtopicCode: '7.2',
    eyebrow: 'EXAMPLE 4 · CONCERT TICKETS · FIGURE 7.10',
    title: 'Follow a flowchart with validation and three discount bands',
    lead: 'Tickets cost $20 each. 10–19 tickets receive 10% discount, 20–25 receive 20%, and a transaction must contain 1–25 tickets.',
    bullets: ['Reject values outside 1–25 and ask again.','For 1–9 tickets: discount = 0.','For 10–19 tickets: discount = 0.1.','For 20–25 tickets: discount = 0.2.','Calculate and output the final cost.'],
    activity: { title: 'Trace three purchases', prompt: 'Calculate the output for 5 tickets, 12 tickets and 22 tickets.', reveal: '5 → $100 · 12 → $216 · 22 → $352.' },
    accent: 'amber',
  },

  {
    id: 'ch7-book-72-pseudo-rules', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'PSEUDOCODE · BOOK CONVENTIONS',
    title: 'Write pseudocode consistently so other people can read it',
    lead: 'Pseudocode uses programming-like English without being bound to one programming language.',
    bullets: ['Use a non-proportional/monospace style for code.','Write keywords such as INPUT and IF in capital letters.','Start data-item and subroutine names with a capital letter.','Indent selected or repeated statements consistently.'],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-72-operators', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'TABLE 7.1 · ASSIGNMENT AND MATHEMATICAL OPERATORS',
    title: 'Use ← to assign a value',
    lead: 'The variable on the left receives the value of the expression on the right.',
    bullets: ['+ add','− subtract','* multiply','/ divide','^ raise to a power','( ) group an expression'],
    example: { title: 'Assignment chain', lines: ['Cost ← 10','Price ← Cost * 2','Tax ← Price * 0.12','SellingPrice ← Price + Tax'], answer: 'SellingPrice becomes 22.4.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-72-activity73', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'ACTIVITY 7.3 · FOLLOW ASSIGNMENTS',
    title: 'Calculate every variable value',
    example: { title: 'Run these statements in order', lines: ['Amount ← 100','TotalPrice ← Amount * 3.5','Discount ← 0.2','FinalPrice ← TotalPrice - TotalPrice * Discount','Name ← "Nikki"','Message ← "Hello " + Name'] },
    activity: { title: 'Activity 7.3', prompt: 'Write the final value of Amount, TotalPrice, Discount, FinalPrice, Name and Message.', reveal: 'Amount=100 · TotalPrice=350 · Discount=0.2 · FinalPrice=280 · Name="Nikki" · Message="Hello Nikki".' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-72-if-case', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'CONDITIONAL STATEMENTS',
    title: 'Choose between two paths or several values',
    keyTerms: [
      {term:'IF … THEN … ELSE … ENDIF',definition:'Use when a condition is TRUE or FALSE. ELSE may be omitted when no false-path action is needed.'},
      {term:'CASE OF … OTHERWISE … ENDCASE',definition:'Use when one value selects between several named alternatives.'},
    ],
    example: { title: 'Two-path choice', lines: ['IF Age < 18','  THEN OUTPUT "Child"','  ELSE OUTPUT "Adult"','ENDIF'] },
    accent: 'amber',
  },
  {
    id: 'ch7-book-72-comparison', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'TABLE 7.2 · COMPARISON AND LOGICAL OPERATORS',
    title: 'Build precise conditions',
    bullets: ['> greater than','< less than','= equal','>= greater than or equal','<= less than or equal','<> not equal','AND both conditions','OR either condition','NOT reverses a Boolean condition'],
    activity: { title: 'Write one compound condition', prompt: 'Write a condition that is true only when Age is greater than 5 and less than 70, and either Height is greater than 1 or Weight is greater than 20.', reveal: '((Height > 1) OR (Weight > 20)) AND (Age < 70) AND (Age > 5)' },
    accent: 'rose',
  },
  {
    id: 'ch7-book-72-nested-if', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'NESTED IF · ACTIVITY 7.4',
    title: 'Validate a mark, then decide pass or fail',
    example: { title: 'Original rule', lines: ['Reject a percentage below 0 or above 100.','If the valid percentage is greater than 49, output Pass.','Otherwise output Fail.'] },
    activity: { title: 'Activity 7.4', prompt: 'Rewrite the logic for a mark from 0 to 20 inclusive with a pass mark of 10. Invalid marks must be rejected before pass/fail is checked.', reveal: 'Reject Mark < 0 OR Mark > 20. For a valid mark, Pass when Mark >= 10; otherwise Fail.' },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-72-case-day', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'CASE OF · ACTIVITY 7.5',
    title: 'Map a whole-number value to a day of the week',
    activity: { title: 'Activity 7.5', prompt: 'Write a CASE statement for Day = 1 to 7. Output a day name for each valid value and an error message for every other value.', reveal: 'Use seven labelled cases and an OTHERWISE error path, then ENDCASE.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-72-loops', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'ITERATION · THREE LOOP STRUCTURES',
    title: 'Choose a loop from what you know about repetition',
    keyTerms: [
      {term:'FOR … TO … NEXT',definition:'Use when the number of repetitions is known.'},
      {term:'REPEAT … UNTIL',definition:'Use when repetitions are not known in advance and the body must run at least once.'},
      {term:'WHILE … DO … ENDWHILE',definition:'Use when repetitions are not known in advance and the body may run zero times.'},
    ],
    activity: { title: 'Choose the best loop', prompt: 'Choose FOR, REPEAT or WHILE for: print 10 stars · ask for a mark until -1 is entered · process records only while more records exist. Write one reason for each choice.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-72-loop-examples', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'FOR · REPEAT · WHILE',
    title: 'Compare three ways to repeat an action',
    example: { title: 'Display ten stars', lines: ['FOR Counter ← 1 TO 10 … NEXT Counter','REPEAT … Counter ← Counter + 1 … UNTIL Counter > 9','WHILE Counter < 10 DO … Counter ← Counter + 1 … ENDWHILE'] },
    bullets: ['FOR manages the loop counter automatically.','REPEAT is post-condition: its test is at the end.','WHILE is pre-condition: its test is at the beginning.'],
    accent: 'amber',
  },
  {
    id: 'ch7-book-72-input-output', section: '7.2 Pseudocode', subtopicCode: '7.2',
    eyebrow: 'INPUT AND OUTPUT STATEMENTS',
    title: 'Store entered data and display information',
    lead: 'INPUT is followed by the variable that receives entered data. OUTPUT displays strings, variables or lists of values.',
    example: { title: 'Examples', lines: ['INPUT Name','INPUT StudentMark','OUTPUT Name','OUTPUT "Your name is ", Name','OUTPUT Name1, "Ali", Name3'] },
    bullets: ['READ may be used for data read from files.','PRINT may be used when hard-copy output is intended.'],
    accent: 'rose',
  },

  {
    id: 'ch7-book-73-purpose', section: '7.3 Algorithm Purpose', subtopicCode: '7.3',
    eyebrow: '7.3 · EXPLAINING THE PURPOSE OF AN ALGORITHM',
    title: 'State the overall purpose, then name the processes',
    lead: 'An algorithm sets out the ordered steps for a task. When explaining it, separate what the whole algorithm achieves from the individual processes it performs.',
    example: { title: 'Alarm-sound example', lines: ['Wait 10 seconds.','Get the current time.','Repeat until current time = alarm time.','Output the alarm sound.'], answer: 'Purpose: output the alarm sound at the appropriate time.' },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-73-activity76', section: '7.3 Algorithm Purpose', subtopicCode: '7.3',
    eyebrow: 'ACTIVITY 7.6 · FIGURE 7.11',
    title: 'Explain an algorithm before calculating its output',
    lead: 'The flowchart and pseudocode both input Num1 and Num2, compare them and print the larger value.',
    activity: { title: 'Activity 7.6', prompt: '1) State the purpose. 2) List the processes. 3) State the output when Num1=7 and Num2=18.', reveal: 'Purpose: output the larger of two numbers. Processes: input two values, compare them, select/output the larger. Output: 18 is largest.' },
    accent: 'cyan',
  },

  {
    id: 'ch7-book-74-overview', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: '7.4 · STANDARD METHODS OF SOLUTION',
    title: 'Recognise five reusable algorithm patterns',
    bullets: ['Totalling','Counting','Finding maximum/minimum/average','Linear search','Bubble sort'],
    lead: 'These methods recur in many different programs. Learn the pattern so you can adapt it to a new scenario.',
    accent: 'indigo',
  },
  {
    id: 'ch7-book-74-total-count', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: '7.4.1–7.4.2 · TOTALLING AND COUNTING',
    title: 'Update an accumulator or a counter',
    example: { title: 'Core patterns', lines: ['Total ← 0','Total ← Total + Value','','Count ← 0','IF condition THEN Count ← Count + 1'] },
    activity: { title: 'Identify the pattern', prompt: 'For each scenario write TOTAL or COUNT: sum all class marks · record how many students passed · reduce stock by one for each sale · add all item prices.' , reveal: 'TOTAL · COUNT · COUNT/update · TOTAL.'},
    accent: 'cyan',
  },
  {
    id: 'ch7-book-74-max-min', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: '7.4.3 · MAXIMUM AND MINIMUM',
    title: 'Replace the stored extreme when a better value appears',
    lead: 'When a known range exists, initialise to safe extreme values. When the range is unknown, initialise both maximum and minimum from the first list item.',
    example: { title: 'Unknown range pattern', lines: ['Maximum ← List[1]','Minimum ← List[1]','FOR Counter ← 2 TO Length','  compare List[Counter] with Maximum and Minimum','NEXT Counter'] },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-74-average', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: '7.4.3 · AVERAGE',
    title: 'Average extends the totalling pattern',
    example: { title: 'Mean of a list', lines: ['Total ← 0','FOR Counter ← 1 TO ClassSize','  Total ← Total + StudentMark[Counter]','NEXT Counter','Average ← Total / ClassSize'] },
    activity: { title: 'Calculate the result', prompt: 'Use the pattern for marks 12, 16, 10, 18, 14. Write Total and Average.', reveal: 'Total = 70 · Average = 14.' },
    accent: 'amber',
  },
  {
    id: 'ch7-book-74-linear-search', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: '7.4.4 · LINEAR SEARCH',
    title: 'Inspect list items one at a time until a match is found or the list ends',
    bullets: ['Set a Found flag to FALSE.','Start at the first item.','Compare the search value with the current item.','If equal, set Found to TRUE; otherwise move to the next item.','Stop when found or when all items have been checked.'],
    activity: { title: 'Trace a search', prompt: 'Search [Ava, Ben, Chen, Diyor, Eva] for Diyor. Write the positions checked and the first position where Found becomes TRUE.', reveal: 'Positions 1, 2, 3, 4 are checked; Found becomes TRUE at position 4.' },
    accent: 'rose',
  },
  {
    id: 'ch7-book-74-count-matches', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: 'LINEAR PASS · COUNT MULTIPLE MATCHES',
    title: 'Sometimes the search must inspect every item',
    lead: 'If duplicate values are allowed and the goal is to count every match, do not stop after the first match.',
    example: { title: 'Favourite dessert', lines: ['ChoiceCount ← 0','FOR each item','  IF item = "ice cream" THEN ChoiceCount ← ChoiceCount + 1','NEXT','OUTPUT ChoiceCount'] },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-74-bubble', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: '7.4.5 · BUBBLE SORT',
    title: 'Compare neighbours and swap values that are in the wrong order',
    lead: 'A bubble sort makes repeated passes. After each pass, at least one item has moved to its final position. Stop when no swaps occur or no unchecked items remain.',
    bullets: ['Compare item 1 with item 2, then item 2 with item 3, and so on.','Swap adjacent items when they are in the wrong order.','After a pass, reduce the unchecked end of the list.','Use a Swap flag to detect a pass with no swaps.'],
    activity: { title: 'Perform one pass', prompt: 'Perform one ascending bubble-sort pass on [6, 3, 8, 2, 5]. Write the list after each comparison.', reveal: '[3,6,8,2,5] → [3,6,8,2,5] → [3,6,2,8,5] → [3,6,2,5,8].' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-74-bubble-code', section: '7.4 Standard Methods', subtopicCode: '7.4',
    eyebrow: 'BUBBLE SORT · BOOK PSEUDOCODE',
    title: 'Track the Swap flag and the last unchecked position',
    example: { title: 'Core control structure', lines: ['First ← 1','Last ← 10','REPEAT','  Swap ← FALSE','  FOR Index ← First TO Last - 1','    compare adjacent values and swap when needed','  NEXT Index','  Last ← Last - 1','UNTIL (NOT Swap) OR Last = 1'] },
    accent: 'emerald',
  },

  {
    id: 'ch7-book-75-difference', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: '7.5 · VALIDATION VS VERIFICATION',
    title: 'Reasonable data and accurately copied data are different checks',
    keyTerms: [
      {term:'Validation',definition:'Automated checking that input data is reasonable before the system accepts it.'},
      {term:'Verification',definition:'Checking that data has been copied accurately from its source.'},
    ],
    activity: { title: 'Choose the purpose', prompt: 'Write VALIDATION or VERIFICATION: “Is 120 a reasonable percentage mark?” · “Was 62 copied as 62?”', reveal: '120 as a percentage → validation · checking that 62 was copied as 62 → verification.' },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-75-validation-list', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: '7.5.1 · SIX VALIDATION CHECKS',
    title: 'Select a check that matches the rule',
    bullets: ['Range check','Length check','Type check','Presence check','Format check','Check digit'],
    lead: 'More than one validation check can be applied to the same item of data.',
    accent: 'cyan',
  },
  {
    id: 'ch7-book-75-range', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: 'RANGE CHECK',
    title: 'Accept a number only when it lies between allowed limits',
    example: { title: 'Percentage mark', lines: ['Valid range: 0 to 100 inclusive','Reject when StudentMark < 0 OR StudentMark > 100','Repeat input until StudentMark >= 0 AND StudentMark <= 100'] },
    activity: { title: 'Classify inputs', prompt: 'For the range 0–100 inclusive, label -1, 0, 42, 100, 101 as ACCEPT or REJECT.', reveal: '-1 reject · 0 accept · 42 accept · 100 accept · 101 reject.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-75-length', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: 'LENGTH CHECK',
    title: 'Check an exact length or an allowed length interval',
    bullets: ['Exact example: password must contain exactly 8 characters.','Interval example: family name must contain 2–30 characters inclusive.','LENGTH(String) returns the number of characters.'],
    activity: { title: 'Write the condition', prompt: 'Write the rejection condition for a password that must contain between 8 and 12 characters inclusive.', reveal: 'LENGTH(Password) < 8 OR LENGTH(Password) > 12' },
    accent: 'amber',
  },
  {
    id: 'ch7-book-75-type-presence', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: 'TYPE CHECK AND PRESENCE CHECK',
    title: 'Check the kind of data and whether any data was entered',
    bullets: ['Type check: confirm that an entered value has the required data type.','Presence check: confirm that the data item is not blank.','The book demonstrates whole-number checking and a required email field.'],
    activity: { title: 'Choose the check', prompt: 'Choose TYPE or PRESENCE: “Number of brothers must be an integer” · “Email address must not be empty”.', reveal: 'Number of brothers → type check · email not empty → presence check.' },
    accent: 'rose',
  },
  {
    id: 'ch7-book-75-format-checkdigit', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: 'FORMAT CHECK AND CHECK DIGIT · FIGURES 7.12–7.13',
    title: 'Check a pattern or detect likely entry errors in a code',
    bullets: ['Format check: confirm that characters match a predefined pattern, such as XXX999.','Check digit: an additional calculated digit used in codes such as barcodes, ISBNs and VINs.','Check digits can detect many mistyped digits, transpositions and missing/extra digits.'],
    activity: { title: 'Match rule to check', prompt: 'Choose FORMAT or CHECK DIGIT: product code must look like ABC123 · scanned ISBN should be checked for a likely digit-entry error.', reveal: 'ABC123 pattern → format check · ISBN calculated final digit → check digit.' },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-75-findout-isbn', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: 'FIND OUT MORE · ISBN INVESTIGATION',
    title: 'Investigate what a check digit can and cannot detect',
    activity: { title: 'ISBN task', prompt: 'Take two valid ISBNs. Copy one correctly and introduce one transposition error into the other. Exchange them with another student and identify the altered code. Then state one kind of error a check-digit method might fail to identify.' },
    bullets: ['Chapter 2 contains the ISBN/modulo-11 calculation details.','Also investigate limit checks and consistency checks as an extension.'],
    accent: 'cyan',
  },
  {
    id: 'ch7-book-75-activity77', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: 'ACTIVITY 7.7 · APPLY VALIDATION',
    title: 'Choose checks and write validation algorithms',
    activity: { title: 'Activity 7.7', prompt: 'Complete all three tasks: 1) choose and justify validation checks for a telephone number, pupil name and XXX999 part number; 2) write pseudocode to accept age >7 and <12 AND height >110 cm and <150 cm; 3) write pseudocode to accept password length 8–12 inclusive.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-75-verification', section: '7.5 Validation & Verification', subtopicCode: '7.5',
    eyebrow: '7.5.2 · VERIFICATION · FIGURE 7.14',
    title: 'Use double entry or a screen/visual check',
    keyTerms: [
      {term:'Double entry',definition:'Enter the data twice. The system compares both copies and asks for re-entry if they differ.'},
      {term:'Screen/visual check',definition:'Display the entered data so the user can compare it with the source or confirm it from their own knowledge.'},
    ],
    accent: 'amber',
  },
  {
    id: 'ch7-book-76-activity78', section: '7.6 Test Data', subtopicCode: '7.6',
    eyebrow: 'ACTIVITY 7.8 · BRIDGE FROM VERIFICATION TO TESTING',
    title: 'Explain why valid-looking data can still need verification',
    activity: { title: 'Activity 7.8', prompt: 'For each item — telephone number, pupil name, XXX999 part number — write one sentence explaining why validation alone cannot prove that the value was copied correctly.' },
    accent: 'rose',
  },

  {
    id: 'ch7-book-76-testdata', section: '7.6 Test Data', subtopicCode: '7.6',
    eyebrow: '7.6.1 · TEST DATA',
    title: 'Test sub-systems first, then test the complete solution',
    lead: 'Algorithms can be worked through manually; programs can be run on a computer. Thorough checking requires several different data sets and expected results.',
    bullets: ['A set of test data contains all values needed to work through a solution.','Record the expected result before running the test.','Compare actual result with expected result.'],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-76-normal', section: '7.6 Test Data', subtopicCode: '7.6',
    eyebrow: 'NORMAL DATA · ACTIVITY 7.9',
    title: 'Use data the solution should normally accept',
    lead: 'Normal data should be accepted and should produce the expected result.',
    example: { title: 'Book example', lines: ['Ten percentage marks, each 50','Expected average = 50'] },
    activity: { title: 'Activity 7.9', prompt: 'Provide a more realistic set of ten valid percentage marks and calculate the expected average before running the algorithm.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-76-abnormal', section: '7.6 Test Data', subtopicCode: '7.6',
    eyebrow: 'ABNORMAL / ERRONEOUS DATA · ACTIVITY 7.10',
    title: 'Use data the solution should reject',
    example: { title: 'Percentage-mark examples', lines: ['-12 → reject','"eleven" → reject'] },
    activity: { title: 'Activity 7.10', prompt: 'Create four more abnormal values for a whole-number percentage mark. For each one, write the expected result.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-76-extreme-boundary', section: '7.6 Test Data', subtopicCode: '7.6',
    eyebrow: 'EXTREME AND BOUNDARY DATA · ACTIVITY 7.11',
    title: 'Test the limits and the values immediately around them',
    bullets: ['Extreme data: smallest and largest accepted values.','Boundary data: an accepted value and the adjacent rejected value at each boundary.','For 0–100 whole-number marks: extremes 0 and 100; lower boundary pair -1 and 0.'],
    activity: { title: 'Activity 7.11', prompt: '1) Give the upper boundary pair for 0–100 whole-number marks. 2) For marks out of 20, provide two normal sets, abnormal values, lower boundary data and upper boundary data with expected results.', reveal: 'Upper boundary for 0–100: 100 accepted, 101 rejected. For 0–20 boundaries: -1/0 and 20/21.' },
    accent: 'amber',
  },

  {
    id: 'ch7-book-77-trace-intro', section: '7.7 Trace Tables', subtopicCode: '7.7',
    eyebrow: '7.7 · DRY RUNS · FIGURE 7.15 · TABLE 7.3',
    title: 'Record every variable change in a trace table',
    lead: 'A dry run means working through an algorithm manually, step by step. A trace table records each variable when its value changes and records every output.',
    bullets: ['Create one column for each variable.','Add an OUTPUT column when the algorithm produces output.','Enter a new value only when that variable changes.','Use the supplied test data in the exact order.'],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-77-trace-worked', section: '7.7 Trace Tables', subtopicCode: '7.7',
    eyebrow: 'WORKED EXAMPLE · TABLE 7.4',
    title: 'Trace the highest-and-lowest algorithm',
    lead: 'The flowchart starts A=0, B=0, C=100, then processes 9, 7, 3, 12, 6, 4, 15, 2, 8, 5.',
    activity: { title: 'Complete the table before reveal', prompt: 'Create columns A, B, C, X, OUTPUT. Work through all ten values. Record each change and the final two outputs.', reveal: 'Final B=15 and C=2, so the algorithm outputs 15 and 2.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-77-activity712', section: '7.7 Trace Tables', subtopicCode: '7.7',
    eyebrow: 'ACTIVITY 7.12',
    title: 'Dry-run the same algorithm with a new data set',
    activity: { title: 'Activity 7.12', prompt: 'Use A, B, C, X and OUTPUT columns. Dry-run: 400, 800, 190, 170, 300, 110, 600, 150, 130, 900. State the final output and what the algorithm appears to do.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-77-same-pseudo', section: '7.7 Trace Tables', subtopicCode: '7.7',
    eyebrow: 'FLOWCHART ↔ PSEUDOCODE',
    title: 'The same trace table can be used for equivalent pseudocode',
    example: { title: 'Core algorithm', lines: ['A ← 0','B ← 0','C ← 100','REPEAT','  INPUT X','  IF X > B THEN B ← X ENDIF','  IF X < C THEN C ← X ENDIF','  A ← A + 1','UNTIL A = 10','OUTPUT B, C'] },
    bullets: ['A question may use short variable names.','You may be asked to infer the purpose from the trace.','Prompts and outputs belong in the OUTPUT column when required.'],
    accent: 'amber',
  },

  {
    id: 'ch7-book-78-activity71314', section: '7.8 Finding Errors', subtopicCode: '7.8',
    eyebrow: 'ACTIVITIES 7.13–7.14 · TABLES 7.5–7.6',
    title: 'Use trace tables to expose errors',
    activity: { title: 'Two dry runs', prompt: 'Activity 7.13: dry-run the highest/lowest pseudocode with 4,8,19,17,3,11,6,1,13,9. Activity 7.14: build a trace table for the bubble sort and dry-run 35,31,32,36,39,37,42,38.' },
    bullets: ['A trace table does more than calculate an answer; it exposes where state changes incorrectly.','The book’s later example shows a failure to identify 110 as the smallest value in a different test set.'],
    accent: 'rose',
  },
  {
    id: 'ch7-book-78-negative', section: '7.8 Finding Errors', subtopicCode: '7.8',
    eyebrow: 'ACTIVITY 7.15 · FIGURE 7.16',
    title: 'A test set can reveal a hidden assumption',
    lead: 'Initialising B=0 and C=100 only works when every input is expected to lie in that range.',
    activity: { title: 'Activity 7.15', prompt: 'Choose ten negative test values and dry-run the algorithm. Identify why the current initial values cause a wrong maximum or minimum.' },
    bullets: ['The book improves the provisional values to very large positive/negative limits.','That improves the range but still does not guarantee correctness for every possible number set.'],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-78-activity716', section: '7.8 Finding Errors', subtopicCode: '7.8',
    eyebrow: 'ACTIVITY 7.16',
    title: 'Find values that still break the “very large limit” approach',
    activity: { title: 'Activity 7.16', prompt: 'The improved version starts Maximum at -1,000,000 and Minimum at 1,000,000. Give two legal input values that would still cause the algorithm to fail and explain why.', reveal: 'Any value above 1,000,000 can break the provisional minimum logic; any value below -1,000,000 can break the provisional maximum logic. The exact failing set depends on how the values are arranged.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-78-first-value', section: '7.8 Finding Errors', subtopicCode: '7.8',
    eyebrow: 'FIGURE 7.17 · ROBUST INITIALISATION',
    title: 'Initialise maximum and minimum from the first input value',
    lead: 'A robust solution reads the first value first, assigns it to both current maximum and current minimum, then processes the remaining values.',
    bullets: ['Read first X.','Set B ← X and C ← X.','Process nine more values.','Compare each value with B and C.','Output B and C.'],
    accent: 'emerald',
  },
  {
    id: 'ch7-book-78-activity717', section: '7.8 Finding Errors', subtopicCode: '7.8',
    eyebrow: 'ACTIVITY 7.17',
    title: 'Rewrite and test the robust highest/lowest algorithm',
    activity: { title: 'Activity 7.17', prompt: 'Write pseudocode that sets maximum and minimum from the first input, then test it with -97, 12390, 0, 77, 359, -2, -89, 5000, 21, 67.', reveal: 'Expected final maximum = 12390 and minimum = -97.' },
    accent: 'amber',
  },

  {
    id: 'ch7-book-79-eight-stages', section: '7.9 Writing Algorithms', subtopicCode: '7.9',
    eyebrow: '7.9 · EIGHT-STAGE ALGORITHM WORKFLOW',
    title: 'Use a repeatable process when you write an algorithm',
    bullets: ['1 Specify the purpose and tasks clearly.','2 Break the problem into sub-problems.','3 Decide how data is obtained, stored, processed and displayed.','4 Design the structure using a structure diagram.','5 Choose flowchart or pseudocode.','6 Construct a precise, readable algorithm with meaningful names.','7 Dry-run several normal, abnormal and boundary data sets using trace tables.','8 Correct errors and repeat until the algorithm behaves correctly.'],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-79-fig1819', section: '7.9 Writing Algorithms', subtopicCode: '7.9',
    eyebrow: 'FIGURES 7.18–7.19 · MAX AND MIN',
    title: 'Compare structure and flow views of the same solution',
    lead: 'The structure diagram separates Enter values, Check all values and Output Max/Min. The flowchart then shows the executable order and decisions.',
    activity: { title: 'Compare the diagrams', prompt: 'Write two sentences: one thing the structure diagram communicates better, and one thing the flowchart communicates better.', reveal: 'Structure diagram: hierarchy/modules. Flowchart: execution order, decisions and repetition.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-79-example1', section: '7.9 Writing Algorithms', subtopicCode: '7.9',
    eyebrow: 'EXAMPLE 1 · CONCERT TICKETS · ACTIVITY 7.18',
    title: 'Write, validate and test the ticket-cost algorithm',
    lead: 'Use the same ticket rules from Figure 7.10, but now express the full solution in pseudocode and plan test data.',
    bullets: ['Accept only 1–25 tickets.','Use 0%, 10% and 20% discount bands.','Calculate Cost = NumberOfTickets × 20 × (1 − Discount).'],
    activity: { title: 'Activity 7.18', prompt: 'Classify the book test values 0, 26, 1, 25, 9, 10, 19, 20 by test-data type. Add at least four more useful values and dry-run them.', reveal: '0/26 are rejected outside the valid range; 1/25 are valid extremes; 9/10 and 19/20 test discount boundaries.' },
    accent: 'emerald',
  },
  {
    id: 'ch7-book-79-example2', section: '7.9 Writing Algorithms', subtopicCode: '7.9',
    eyebrow: 'EXAMPLE 2 · SCHOOL TEST RESULTS',
    title: 'Combine loops, validation, CASE, totals and extremes',
    lead: 'A school has 600 students and four tests: Maths, Science, English and IT. The algorithm outputs highest, lowest and average for each subject and overall.',
    bullets: ['Outer loop selects each test.','CASE assigns the subject name.','Inner loop processes 600 students.','Each mark is validated in the range 0–100.','Subject and overall totals/highest/lowest are updated.','Subject average is output after each subject; overall statistics are output at the end.'],
    accent: 'amber',
  },
  {
    id: 'ch7-book-79-activity719', section: '7.9 Writing Algorithms', subtopicCode: '7.9',
    eyebrow: 'ACTIVITY 7.19',
    title: 'Shrink the school algorithm so it can be dry-run manually',
    activity: { title: 'Activity 7.19', prompt: '1) Change Example 2 from 600 students / 4 subjects to 5 students / 2 subjects. 2) Choose complete test data. 3) Calculate expected results. 4) Build a trace table and compare expected with actual results.' },
    accent: 'rose',
  },
  {
    id: 'ch7-book-79-activity720', section: '7.9 Writing Algorithms', subtopicCode: '7.9',
    eyebrow: 'ACTIVITY 7.20',
    title: 'Choose loops for two total-and-average algorithms',
    activity: { title: 'Activity 7.20', prompt: 'Write pseudocode for: A) exactly ten positive numbers → total and average; B) any number of positive numbers, terminated by -1 → total and average. Then explain why you chose each loop structure.', reveal: 'A naturally fits a FOR loop because the count is known. B needs a condition-controlled loop because the number of values is not known in advance.' },
    accent: 'indigo',
  },

  {
    id: 'ch7-book-ext-stackqueue', section: 'Extension', subtopicCode: '7.9',
    eyebrow: 'EXTENSION · FIGURE 7.20',
    title: 'Preview Abstract Data Types: stack and queue',
    keyTerms: [
      {term:'Stack',definition:'A LIFO structure: the last item added is the first item removed. Operations include push and pop.'},
      {term:'Queue',definition:'A FIFO structure: the first item added is the first item removed. Operations include enqueue and dequeue.'},
    ],
    bullets: ['The book illustrates 27 as the first item added and 79 as the last item added.','Stacks use a Top Pointer and Base Pointer.','Queues use Front Pointer and End Pointer.'],
    accent: 'cyan',
  },
  {
    id: 'ch7-book-ext-operations', section: 'Extension', subtopicCode: '7.9',
    eyebrow: 'FIGURES 7.21–7.22 · STACK AND QUEUE OPERATIONS',
    title: 'Track how the pointers move',
    bullets: ['Stack pop removes the current top item; push adds a new top item.','The stack Base Pointer stays fixed during these operations.','Queue dequeue removes the front item; enqueue adds an item at the end.','Both Front and End pointers can change during queue operations.'],
    activity: { title: 'Extension activity', prompt: 'Starting from the displayed stack and queue, draw the stack after one pop and the queue after one dequeue. Label all pointers.' },
    accent: 'emerald',
  },

  {
    id: 'ch7-book-review', section: 'Chapter Review', subtopicCode: '7.9',
    eyebrow: 'CHAPTER 7 · COMPLETE REVIEW',
    title: 'Check that every Chapter 7 skill is connected',
    bullets: ['Program development life cycle','Decomposition into systems/sub-systems and sub-problems','Structure diagrams, flowcharts and pseudocode','Explaining an algorithm’s purpose','Standard solution methods','Validation and verification','Suitable test data','Trace tables and dry runs','Writing, amending and identifying algorithm errors'],
    activity: { title: 'Traffic-light check', prompt: 'For every line, mark GREEN if you can explain it and complete a task without help, AMBER if you need one example, or RED if you need reteaching.' },
    accent: 'amber',
  },
  {
    id: 'ch7-book-keyterms-a', section: 'Chapter Review', subtopicCode: '7.9',
    eyebrow: 'KEY TERMS · PART 1',
    title: 'Development and algorithm vocabulary',
    keyTerms: [
      {term:'Analysis',definition:'Investigation that leads to a specification of what the program must do.'},
      {term:'Design',definition:'Uses the specification to show how the program should be developed.'},
      {term:'Coding',definition:'Writing the program or suite of programs.'},
      {term:'Testing',definition:'Systematic checks to make sure a program works under the required conditions.'},
      {term:'Abstraction',definition:'Keep required elements and discard unnecessary detail.'},
      {term:'Decomposition',definition:'Break a complex problem into smaller, easier parts.'},
      {term:'Top-down design',definition:'Break a system into progressively smaller sub-systems until each final part performs one action.'},
      {term:'Structure diagram',definition:'Hierarchical diagram showing system breakdown into sub-systems.'},
      {term:'Flowchart',definition:'Diagram showing task steps and execution order.'},
      {term:'Algorithm',definition:'An ordered set of steps to solve a problem.'},
      {term:'Pseudocode',definition:'Programming-like English for expressing an algorithm without strict language syntax.'},
    ],
    accent: 'indigo',
  },
  {
    id: 'ch7-book-keyterms-b', section: 'Chapter Review', subtopicCode: '7.9',
    eyebrow: 'KEY TERMS · PART 2',
    title: 'Data checking, testing and standard-method vocabulary',
    keyTerms: [
      {term:'Linear search',definition:'Inspect list items in turn until the required value is found or the list ends.'},
      {term:'Bubble sort',definition:'Repeatedly compare adjacent items and swap them until no further swaps are needed.'},
      {term:'Validation',definition:'Automated check that data is reasonable before acceptance.'},
      {term:'Verification',definition:'Check that data was copied accurately from a source.'},
      {term:'Normal data',definition:'Data that should be accepted.'},
      {term:'Abnormal data',definition:'Data that should be rejected.'},
      {term:'Extreme data',definition:'Largest/smallest accepted values.'},
      {term:'Boundary data',definition:'Accepted boundary values paired with adjacent rejected values.'},
      {term:'Range / length / type / presence / format checks',definition:'Common validation methods that test a numeric interval, character count, data type, non-blank entry or required pattern.'},
      {term:'Check digit',definition:'Additional calculated digit used to detect likely data-entry errors in a code.'},
    ],
    accent: 'cyan',
  },

  {
    id: 'ch7-book-exam-1-2', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTIONS · 1–2',
    title: 'Decomposition and structure diagrams',
    activity: { title: 'Question 1 · [8]', prompt: 'A solution is decomposed into component parts. Name and describe the four component types used in this chapter.' },
    bullets: ['Question 2 · [6]: Design a structure diagram for a system that creates a modulo-11 check digit for numbers containing 4–20 digits.'],
    accent: 'emerald',
  },
  {
    id: 'ch7-book-exam-3', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTION · 3',
    title: 'Restaurant-bill app: validation and test data',
    lead: 'The app splits a restaurant bill between up to 12 diners. Valid bills are $10–$500.',
    bullets: ['a [2] Choose validation checks for diners and bill size.','b [4] Give two normal data sets and expected results.','c [1] Give abnormal/erroneous data.','d [4] Give required boundary data and expected results.'],
    accent: 'amber',
  },
  {
    id: 'ch7-book-exam-4-5', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTIONS · 4–5',
    title: 'Validation and verification',
    bullets: ['Question 4 · [4]: Explain validation and verification.','Question 5 · [8]: For Name, Date of birth, Password and Phone number, state suitable validation and verification checks and give reasons.'],
    accent: 'rose',
  },
  {
    id: 'ch7-book-exam-6a', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTION · 6 · FIGURE ON BOOK p. 296',
    title: 'Parcel algorithm: dry run the flowchart',
    lead: 'The algorithm checks ten parcels using Length, Breadth and Size = Length × Breadth, then counts accepted and rejected parcels.',
    activity: { title: 'Question 6a · [5]', prompt: 'Complete a trace table using the 20 values as ten Length/Breadth pairs: 15,10, 20,17, 32,10, 30,35, 30,15, 30,28, 25,25, 20,15, 40,20, 12,10.' },
    accent: 'indigo',
  },
  {
    id: 'ch7-book-exam-6bc', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTION · 6 · CONTINUED',
    title: 'Explain the parcel algorithm',
    bullets: ['b [3] State the processes included in the algorithm.','c [3] Identify the rules a parcel must satisfy to be accepted.'],
    activity: { title: 'Answer from the flowchart', prompt: 'Do not guess from the real world. Use only the decisions and processes shown in the algorithm.' },
    accent: 'cyan',
  },
  {
    id: 'ch7-book-exam-7', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTION · 7',
    title: 'Find every error in a faulty total algorithm',
    example: { title: 'Faulty outline', lines: ['Counter ← 1','FOR Counter ← 1 TO 10','  REPEAT','    INPUT Number','  UNTIL Number < 0','  Total ← Total + Counter','  Counter ← Counter + 1','  OUTPUT Total','NEXT Number'] },
    bullets: ['a [5] Identify all errors.','b [4] Rewrite the algorithm correctly.','c [4] Create a trace table and test data.','d [3] Classify your test data as normal, erroneous and extreme.'],
    accent: 'emerald',
  },
  {
    id: 'ch7-book-exam-8', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTION · 8 · 0478/22 JUNE 2018 Q3',
    title: 'Trace and improve a calculator algorithm',
    lead: 'The algorithm repeatedly inputs two non-zero numbers and an operator, performs +, −, × or ÷, and stops when the first number is zero.',
    activity: { title: 'Question 8a · [3]', prompt: 'Complete the trace table for: 5,7,+ · 6,2,- · 4,3,* · 7,8,? · 0,0,/.' },
    bullets: ['b [3] Replace the repeated IF statements with a more suitable alternative conditional structure in pseudocode.'],
    accent: 'amber',
  },
  {
    id: 'ch7-book-exam-9', section: 'Exam-style Questions', subtopicCode: '7.9',
    eyebrow: 'EXAM-STYLE QUESTION · 9 · 0478/22 JUNE 2018 Q4',
    title: 'Validate and verify contributor details',
    bullets: ['a [4] Explain why Name, Email address and Password are verified, and describe how verification can be performed.','b [2] Describe validation checks suitable for Email address and Password.'],
    activity: { title: 'Answer with purpose + method', prompt: 'For each part, separate WHY the check is needed from HOW the check is performed.' },
    accent: 'rose',
  },
];

export const CHAPTER_7_BOOK_SOURCE_COVERAGE = {
  sections: ['7.1','7.2','7.3','7.4','7.5','7.6','7.7','7.8','7.9'],
  activities: Array.from({ length: 20 }, (_, index) => `7.${index + 1}`),
  figures: Array.from({ length: 22 }, (_, index) => `7.${index + 1}`),
  tables: Array.from({ length: 6 }, (_, index) => `7.${index + 1}`),
  examQuestions: ['1','2','3','4','5','6','7','8','9'],
} as const;
