import type { LessonSlide } from './lesson-content-full';

type SlideInput = Omit<LessonSlide, 'lead'> & { lead?: string };
const s = (slide: SlideInput): LessonSlide => ({ lead: '', ...slide });
const a = (title:string, prompt:string, reveal?:string) => ({ title, prompt, ...(reveal ? { reveal } : {}) });

/**
 * Presenter adaptation of the supplied Hodder Cambridge IGCSE/O Level Computer Science
 * Chapter 7 extract (printed pp. 258–298). This sequence is appended after the existing
 * 15-slide discovery lesson and never replaces or reorders those slides.
 */
export const CHAPTER_7_BOOK_SLIDES: LessonSlide[] = [
  s({id:'ch7-book-00-route',section:'Book Deep Dive · 7.1',subtopicCode:'7.1',eyebrow:'BOOK DEEP DIVE · CHAPTER 7',title:'Now build the complete Chapter 7 toolkit',lead:'Continue after the discovery lesson. Work through every numbered section, activity, worked example, diagram skill and exam-style task from the supplied chapter.',bullets:['7.1 Program development life cycle','7.2 Systems, sub-systems and decomposition','7.3 Explaining the purpose of an algorithm','7.4 Standard methods of solution','7.5 Validation and verification','7.6 Test data','7.7 Trace tables and dry runs','7.8 Identifying errors','7.9 Writing and amending algorithms'],accent:'indigo'}),

  s({id:'ch7-book-71-five-stages',section:'Book Deep Dive · 7.1',subtopicCode:'7.1',eyebrow:'7.1 · PROGRAM DEVELOPMENT LIFE CYCLE',title:'The full life cycle has five stages',lead:'The coursebook names analysis, design, coding, testing and maintenance. Chapter 7 and Chapter 8 focus on the first four stages.',bullets:['Analysis','Design','Coding','Testing','Maintenance'],activity:a('Connect to the first lesson','Write one action you completed earlier beside Analysis, Design, Coding and Testing. Leave Maintenance for later study.'),accent:'indigo'}),
  s({id:'ch7-book-71-abstraction-maps',section:'Book Deep Dive · 7.1',subtopicCode:'7.1',eyebrow:'7.1.1 · ANALYSIS · FIGURE 7.1',title:'Keep only the information needed for the purpose',lead:'A road map and a rail map can represent the same area but keep different details because they solve different travel problems.',bullets:['Road map: roads, junctions and routes matter.','Rail map: stations, lines and connections matter.','Remove information that cannot help solve the chosen problem.'],activity:a('Choose what matters','For a walking map of your school, write four details to KEEP and four details to IGNORE. Every KEEP item must help a person reach a destination.','Possible KEEP: buildings, paths, entrances, room labels. Possible IGNORE: wall colours, teacher birthdays, desk brands, ceiling height.'),accent:'cyan'}),
  s({id:'ch7-book-71-decompose-dressed',section:'Book Deep Dive · 7.1',subtopicCode:'7.1',eyebrow:'7.1.1 · DECOMPOSITION · FIND OUT MORE',title:'Break “getting dressed” into smaller actions',lead:'The book begins with three broad actions. Refine them until the final actions are simple enough to perform directly.',bullets:['Select items to wear.','Remove any clothes already being worn.','Put selected items on in order.'],activity:a('Refine the task','Expand the three actions into at least eight smaller actions. Number them in the order they must be completed.','There is no single correct decomposition. A strong answer creates small, clear and manageable actions.'),accent:'emerald'}),
  s({id:'ch7-book-71-design',section:'Book Deep Dive · 7.1',subtopicCode:'7.1',eyebrow:'7.1.2 · DESIGN',title:'Turn the program specification into a complete plan',lead:'By the end of design, the programmer should know every task, how each task will be performed and how the tasks work together.',bullets:['Use the specification produced during analysis.','Identify all tasks.','Decide how each task works.','Show how the tasks connect.','Document the design with structure diagrams, flowcharts and pseudocode.'],accent:'amber'}),
  s({id:'ch7-book-71-coding',section:'Book Deep Dive · 7.1',subtopicCode:'7.1',eyebrow:'7.1.3 · CODING AND ITERATIVE TESTING',title:'Write a module, test it, amend it and test it again',lead:'Each module is written in a suitable programming language. Iterative testing repeats until the module performs as required.',bullets:['Write one module.','Test the module.','Amend the code when a test exposes a problem.','Repeat the test.','Continue until the module behaves as required.'],accent:'rose'}),
  s({id:'ch7-book-71-testing',section:'Book Deep Dive · 7.1',subtopicCode:'7.1',eyebrow:'7.1.4 · TESTING',title:'Test the completed program with different data sets',lead:'Final testing checks that the completed tasks work together as specified in the program design.',activity:a('Differentiate the two checks','Write ITERATIVE or FINAL beside each statement: “test one module after changing its code” · “run the complete program with several data sets”.','Module after amendment → iterative testing. Complete program with several data sets → final testing.'),accent:'cyan'}),

  s({id:'ch7-book-72-system',section:'7.2 Systems & Decomposition',subtopicCode:'7.2',eyebrow:'7.2 · COMPUTER SYSTEMS AND SUB-SYSTEMS',title:'A computer system is built from interacting parts',lead:'A computer system can include software, data, hardware, communications and people. Systems can be very small or extremely large.',bullets:['A system can be divided into sub-systems.','A sub-system can be divided again.','Continue until a final sub-system performs one clear action.'],activity:a('Find five systems','List five computer systems you use in a normal day. Label each SMALL, MEDIUM or LARGE and give one reason.'),accent:'indigo'}),
  s({id:'ch7-book-72-top-down',section:'7.2 Systems & Decomposition',subtopicCode:'7.2',eyebrow:'7.2.1 · TOP-DOWN DESIGN',title:'Refine a system until each final part performs one action',lead:'Top-down design repeatedly decomposes a computer system. The repeated breakdown is called stepwise refinement.',keyTerms:[{term:'Top-down design',definition:'Break a system into sub-systems, then keep breaking each sub-system into smaller sub-systems.'},{term:'Stepwise refinement',definition:'Continue the breakdown until each final sub-system performs a single action.'}],bullets:['Separate programmers can develop and test different sub-systems in parallel.','This structured approach can reduce development and testing time on larger systems.'],activity:a('Refine one system','Choose one system from the previous screen. Draw three levels. Every level-3 box must name one action only.'),accent:'cyan'}),
  s({id:'ch7-book-72-ipos',section:'7.2 Systems & Decomposition',subtopicCode:'7.2',eyebrow:'7.2.2 · COMPONENT PARTS',title:'Describe a system using Input, Process, Output and Storage',lead:'These four component types describe what a system receives, does, produces and keeps for later use.',keyTerms:[{term:'Input',definition:'Data entered while the system is active.'},{term:'Process',definition:'Tasks performed using input data and any previously stored data.'},{term:'Output',definition:'Information displayed or printed for users.'},{term:'Storage',definition:'Data stored on an appropriate medium for future use.'}],accent:'emerald'}),
  s({id:'ch7-book-72-alarm-ipos',section:'7.2 Systems & Decomposition',subtopicCode:'7.2',eyebrow:'EXAMPLE 1 · ALARM APP · ACTIVITY 7.1',title:'Classify the parts of an alarm app',lead:'The alarm example includes inputs, processes, output and stored alarm times.',bullets:['Inputs: set an alarm time, remove an alarm, switch off, press snooze.','Processes: compare current time with alarm times, add/remove alarms, manage snooze.','Output: alarm sound or tune.','Storage: saved alarm time(s).'],activity:a('Activity 7.1','Choose one computer system from your earlier list. Create INPUT, PROCESS, OUTPUT and STORAGE headings and place at least two items under each.'),accent:'amber'}),

  s({id:'ch7-book-72-structure-basic',section:'7.2 Structure Diagrams',subtopicCode:'7.2',eyebrow:'7.2.3 · STRUCTURE DIAGRAMS · FIGURE 7.2',title:'Show top-down design as a hierarchy',lead:'A structure diagram divides the complete system into sub-systems. Each lower level gives a more detailed breakdown.',bullets:['Top box = whole system.','Next level = main sub-systems.','Lower levels = further refinement.','It shows hierarchy, not execution order.'],accent:'indigo'}),
  s({id:'ch7-book-72-alarm-tree',section:'7.2 Structure Diagrams',subtopicCode:'7.2',eyebrow:'EXAMPLE 2 · FIGURE 7.3 · ACTIVITY 7.2',title:'Read and extend the alarm-app structure diagram',lead:'The book divides the alarm app into Set alarm, Check time and Sound alarm, then refines those parts.',activity:a('Activity 7.2','Break the CHECK TIME sub-system into at least three smaller sub-systems. Each final box must describe one action.','Possible boxes: get current time · compare current time with alarm time · decide whether to wait or sound the alarm.'),accent:'cyan'}),
  s({id:'ch7-book-72-teeth',section:'7.2 Structure Diagrams',subtopicCode:'7.2',eyebrow:'FIND OUT MORE · STRUCTURE DIAGRAM PRACTICE',title:'Create a structure diagram for cleaning your teeth',lead:'Build a hierarchy of sub-systems before thinking about detailed execution order.',activity:a('Draw and test the hierarchy','Create at least three main sub-systems and refine each one. Give your diagram to another student and ask them to identify one missing or unclear action.'),accent:'emerald'}),

  s({id:'ch7-book-72-flow-purpose',section:'7.2 Flowcharts',subtopicCode:'7.2',eyebrow:'FLOWCHARTS · FIGURE 7.4',title:'A flowchart shows the steps and their execution order',lead:'The ordered steps required to complete a task form an algorithm. A flowchart communicates that algorithm visually.',activity:a('Read the alarm-time flow','Trace: Get Time → Is Time = Alarm Time? → YES: Sound Alarm / NO: Wait 30 seconds and check again. State which steps repeat.'),accent:'indigo'}),
  s({id:'ch7-book-72-flow-symbols-a',section:'7.2 Flowcharts',subtopicCode:'7.2',eyebrow:'FIGURES 7.5–7.7 · STANDARD SYMBOLS',title:'Use the correct symbol for Begin/End, Process and Input/Output',lead:'Standard symbols make a flowchart readable to other people.',keyTerms:[{term:'Terminator',definition:'Used at the beginning and end of a flowchart.'},{term:'Process',definition:'Shows an action or assignment; it can also name a process defined elsewhere.'},{term:'Input/Output',definition:'The same parallelogram symbol shows input data and output information.'}],activity:a('Label three statements','Choose the correct symbol for START · Total ← Total + Mark · OUTPUT "Error".','START → terminator · assignment → process · OUTPUT → input/output.'),accent:'cyan'}),
  s({id:'ch7-book-72-flow-symbols-b',section:'7.2 Flowcharts',subtopicCode:'7.2',eyebrow:'FIGURES 7.8–7.9 · DECISIONS AND FLOW LINES',title:'A decision must have two clearly labelled exits',lead:'A decision chooses the next action; arrows show the direction of flow, usually top-to-bottom and left-to-right.',bullets:['Decision symbol = diamond.','There are always two outputs from a decision.','Label both outputs clearly, for example YES and NO.','Flow lines use arrows.'],activity:a('Fix the diagram','Draw X > B? as a decision. Add exactly two outgoing arrows labelled YES and NO. On the YES path add B ← X.'),accent:'emerald'}),
  s({id:'ch7-book-72-ticket-flow',section:'7.2 Flowcharts',subtopicCode:'7.2',eyebrow:'EXAMPLE 4 · CONCERT TICKETS · FIGURE 7.10',title:'Follow validation and three discount bands',lead:'Tickets cost $20 each. A transaction accepts 1–25 tickets; 10–19 receives 10% discount and 20–25 receives 20%.',bullets:['1–9 → 0% discount.','10–19 → 10% discount.','20–25 → 20% discount.','Reject any value outside 1–25 and ask again.'],activity:a('Trace three purchases','Calculate the cost for 5 tickets, 12 tickets and 22 tickets.','5 → $100 · 12 → $216 · 22 → $352.'),accent:'amber'}),

  s({id:'ch7-book-72-pseudo-rules',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'PSEUDOCODE · BOOK CONVENTIONS',title:'Write pseudocode consistently so another person can read it',lead:'Pseudocode uses programming-like English without the strict syntax rules of one programming language.',bullets:['Use a non-proportional/monospace font.','Write keywords such as INPUT in capital letters.','Start data-item and subroutine names with a capital letter.','Indent statements inside selection and loops consistently.'],accent:'indigo'}),
  s({id:'ch7-book-72-operators',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'TABLE 7.1 · ASSIGNMENT AND MATHEMATICAL OPERATORS',title:'Use ← to assign the value on the right to the item on the left',lead:'Expressions can combine values using the mathematical operators listed in the chapter.',bullets:['+ Add','− Subtract','* Multiply','/ Divide','^ Raise to the power','( ) Group'],example:{title:'Assignment chain',lines:['Cost ← 10','Price ← Cost * 2','Tax ← Price * 0.12','SellingPrice ← Price + Tax'],answer:'SellingPrice becomes 22.4.'},accent:'cyan'}),
  s({id:'ch7-book-72-activity73',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'ACTIVITY 7.3 · FOLLOW ASSIGNMENTS',title:'Calculate every variable value in order',lead:'Execute each assignment only after the previous assignment has updated its variable.',example:{title:'Statements',lines:['Amount ← 100','TotalPrice ← Amount * 3.5','Discount ← 0.2','FinalPrice ← TotalPrice - TotalPrice * Discount','Name ← "Nikki"','Message ← "Hello " + Name']},activity:a('Activity 7.3','Write the final value of Amount, TotalPrice, Discount, FinalPrice, Name and Message.','Amount=100 · TotalPrice=350 · Discount=0.2 · FinalPrice=280 · Name="Nikki" · Message="Hello Nikki".'),accent:'emerald'}),
  s({id:'ch7-book-72-if-case',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'CONDITIONAL STATEMENTS',title:'Choose between two paths or several values',lead:'Use IF for a true/false condition and CASE when one value selects among several alternatives.',keyTerms:[{term:'IF … THEN … ELSE … ENDIF',definition:'Follow THEN when the condition is true; follow ELSE when it is false. ELSE may be omitted.'},{term:'CASE OF … OTHERWISE … ENDCASE',definition:'Use the value of one item to choose among several named paths; OTHERWISE handles other values.'}],example:{title:'Two-path choice',lines:['IF Age < 18','  THEN OUTPUT "Child"','  ELSE OUTPUT "Adult"','ENDIF']},accent:'amber'}),
  s({id:'ch7-book-72-comparison',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'TABLE 7.2 · COMPARISON AND LOGICAL OPERATORS',title:'Build precise conditions',lead:'Comparisons can be combined with AND, OR and NOT.',bullets:['> greater than','< less than','= equal','>= greater than or equal','<= less than or equal','<> not equal','AND both','OR either','NOT not'],activity:a('Write one compound condition','Write a condition that is true only when Age is greater than 5 and less than 70, and either Height is greater than 1 or Weight is greater than 20.','((Height > 1) OR (Weight > 20)) AND (Age < 70) AND (Age > 5)'),accent:'rose'}),
  s({id:'ch7-book-72-nested-if',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'NESTED IF · ACTIVITY 7.4',title:'Validate a mark before deciding pass or fail',lead:'The book places a second IF inside the ELSE path of the first IF. Indentation makes the nested structure clear.',activity:a('Activity 7.4','Rewrite the logic for marks 0–20 inclusive with a pass mark of 10. Reject invalid marks before checking pass/fail.','Reject Mark < 0 OR Mark > 20. For valid data, output Pass when Mark >= 10; otherwise output Fail.'),accent:'indigo'}),
  s({id:'ch7-book-72-case-day',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'CASE OF · ACTIVITY 7.5',title:'Map the values 1–7 to days of the week',lead:'Use one CASE path for each valid value and OTHERWISE for every invalid value.',activity:a('Activity 7.5','Write a CASE statement for Day = 1 to 7. Output a day name for each valid value and an error message for every other value.','Use seven labelled cases, an OTHERWISE error path and ENDCASE.'),accent:'cyan'}),
  s({id:'ch7-book-72-loops',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'ITERATION · THREE LOOP STRUCTURES',title:'Choose the loop from what you know about repetition',lead:'All three loop structures can repeat actions, but the most suitable one depends on when the condition is known and checked.',keyTerms:[{term:'FOR … TO … NEXT',definition:'Use when the number of repetitions is known.'},{term:'REPEAT … UNTIL',definition:'Use when repetitions are not known in advance and the body must run at least once.'},{term:'WHILE … DO … ENDWHILE',definition:'Use when repetitions are not known in advance and the body may run zero times.'}],activity:a('Choose the best loop','Choose FOR, REPEAT or WHILE for: display ten stars · enter marks until -1 · process records only while another record exists. Give one reason each.'),accent:'emerald'}),
  s({id:'ch7-book-72-loop-examples',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'FOR · REPEAT · WHILE',title:'Compare three ways to repeat the same action',lead:'The book demonstrates all three structures by displaying ten stars.',example:{title:'Three control structures',lines:['FOR Counter ← 1 TO 10 … NEXT Counter','REPEAT … Counter ← Counter + 1 … UNTIL Counter > 9','WHILE Counter < 10 DO … Counter ← Counter + 1 … ENDWHILE']},bullets:['FOR manages a known counter automatically.','REPEAT is a post-condition loop: test at the end.','WHILE is a pre-condition loop: test at the beginning.'],accent:'amber'}),
  s({id:'ch7-book-72-repeat-detail',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'REPEAT … UNTIL',title:'A REPEAT loop always executes its body at least once',lead:'The exit condition is checked after the repeated statements.',example:{title:'Sentinel example',lines:['Total ← 0','Mark ← 0','REPEAT','  Total ← Total + Mark','  INPUT Mark','UNTIL Mark = -1']},accent:'cyan'}),
  s({id:'ch7-book-72-while-detail',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'WHILE … DO … ENDWHILE',title:'A WHILE loop may execute zero times',lead:'The condition is tested before the body. If it is false initially, the repeated statements are skipped.',example:{title:'Sentinel example',lines:['INPUT Mark','WHILE Mark <> -1 DO','  Total ← Total + Mark','  INPUT Mark','ENDWHILE']},accent:'emerald'}),
  s({id:'ch7-book-72-input-output',section:'7.2 Pseudocode',subtopicCode:'7.2',eyebrow:'INPUT AND OUTPUT STATEMENTS',title:'Store entered data and display information',lead:'INPUT is normally followed by the variable that receives data. OUTPUT can display a string, variable or comma-separated values.',example:{title:'Examples',lines:['INPUT Name','INPUT StudentMark','OUTPUT Name','OUTPUT "Your name is ", Name','OUTPUT Name1, "Ali", Name3']},bullets:['READ may be used for reading from files.','PRINT may be used when hard-copy output is required.'],accent:'rose'}),

  s({id:'ch7-book-73-purpose',section:'7.3 Algorithm Purpose',subtopicCode:'7.3',eyebrow:'7.3 · EXPLAINING THE PURPOSE OF AN ALGORITHM',title:'State the overall purpose, then identify the processes',lead:'An algorithm is an ordered set of steps to complete a task. Explain what the whole algorithm achieves separately from the individual actions.',example:{title:'Alarm-sound example',lines:['Wait 10 seconds.','Get current time.','Repeat until current time = alarm time.','Output alarm sound.'],answer:'Purpose: output the alarm sound at the appropriate time.'},accent:'indigo'}),
  s({id:'ch7-book-73-activity76',section:'7.3 Algorithm Purpose',subtopicCode:'7.3',eyebrow:'ACTIVITY 7.6 · FIGURE 7.11',title:'Explain the algorithm before calculating its output',lead:'The flowchart and pseudocode input two numbers, compare them and output the larger value.',activity:a('Activity 7.6','1) State the purpose. 2) List the processes. 3) State the output when Num1=7 and Num2=18.','Purpose: output the larger of two numbers. Processes: input, compare, select/output. Output: 18 is largest.'),accent:'cyan'}),

  s({id:'ch7-book-74-overview',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'7.4 · STANDARD METHODS OF SOLUTION',title:'Recognise reusable algorithm patterns',lead:'The chapter requires totalling, counting, maximum/minimum/average, linear search and bubble sort.',bullets:['Totalling','Counting','Maximum, minimum and average','Linear search','Bubble sort'],accent:'indigo'}),
  s({id:'ch7-book-74-total-count',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'7.4.1–7.4.2 · TOTALLING AND COUNTING',title:'Update an accumulator or a counter',lead:'A total adds data values; a count records how many times a condition or action occurs.',example:{title:'Core patterns',lines:['Total ← 0','Total ← Total + Value','','PassCount ← 0','IF StudentMark > 50 THEN PassCount ← PassCount + 1']},activity:a('Identify the pattern','Write TOTAL or COUNT: sum all class marks · record how many students passed · add all item prices.','TOTAL · COUNT · TOTAL.'),accent:'cyan'}),
  s({id:'ch7-book-74-countdown',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'COUNTING DOWN',title:'A counter can decrease as well as increase',lead:'The book uses stock as an example: reduce NumberInStock by one and call a reorder routine when stock becomes low.',example:{title:'Stock check',lines:['NumberInStock ← NumberInStock - 1','IF NumberInStock < 20','  THEN CALL Reorder()']},accent:'amber'}),
  s({id:'ch7-book-74-max-min',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'7.4.3 · MAXIMUM AND MINIMUM',title:'Replace the stored extreme when a better value appears',lead:'If a safe numeric range is known, initialise maximum and minimum to suitable limits. If the range is unknown, initialise from the first list item.',example:{title:'Unknown-range pattern',lines:['Maximum ← List[1]','Minimum ← List[1]','FOR Counter ← 2 TO Length','  compare List[Counter] with Maximum and Minimum','NEXT Counter']},accent:'emerald'}),
  s({id:'ch7-book-74-average',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'7.4.3 · AVERAGE',title:'Average extends the totalling method',lead:'First total every value, then divide the final total by the number of values.',example:{title:'Mean of a list',lines:['Total ← 0','FOR Counter ← 1 TO ClassSize','  Total ← Total + StudentMark[Counter]','NEXT Counter','Average ← Total / ClassSize']},activity:a('Calculate the result','Use marks 12, 16, 10, 18, 14. Write Total and Average.','Total = 70 · Average = 14.'),accent:'amber'}),
  s({id:'ch7-book-74-linear-search',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'7.4.4 · LINEAR SEARCH',title:'Inspect items one at a time until a match is found or the list ends',lead:'A linear search systematically checks each list item against the required value.',bullets:['Set Found ← FALSE.','Start at the first item.','Compare search value with current item.','If equal, set Found ← TRUE; otherwise move to the next position.','Stop when Found is true or every item has been checked.'],activity:a('Trace a search','Search [Ava, Ben, Chen, Diyor, Eva] for Diyor. Write the positions checked and the first position where Found becomes TRUE.','Positions 1, 2, 3 and 4 are checked; Found becomes TRUE at position 4.'),accent:'rose'}),
  s({id:'ch7-book-74-count-matches',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'LINEAR PASS · MULTIPLE MATCHES',title:'Inspect the full list when every match must be counted',lead:'If duplicate values are possible and the goal is to count all matches, continue to the end instead of stopping after the first match.',example:{title:'Favourite dessert',lines:['ChoiceCount ← 0','FOR Counter ← 1 TO Length','  IF Dessert[Counter] = "ice cream" THEN ChoiceCount ← ChoiceCount + 1','NEXT Counter','OUTPUT ChoiceCount']},accent:'indigo'}),
  s({id:'ch7-book-74-bubble',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'7.4.5 · BUBBLE SORT',title:'Compare neighbours and swap values that are in the wrong order',lead:'Bubble sort makes repeated passes through a list. Each pass compares adjacent items and swaps them when needed.',bullets:['Compare item 1 with item 2, then item 2 with item 3, and so on.','Swap adjacent values when they are in the wrong order.','Reduce the unchecked end after a pass.','Stop when no swaps are made or only one unchecked item remains.'],activity:a('Perform one pass','Perform one ascending pass on [6,3,8,2,5]. Write the list after each comparison.','[3,6,8,2,5] → [3,6,8,2,5] → [3,6,2,8,5] → [3,6,2,5,8].'),accent:'cyan'}),
  s({id:'ch7-book-74-bubble-code',section:'7.4 Standard Methods',subtopicCode:'7.4',eyebrow:'BUBBLE SORT · BOOK PSEUDOCODE',title:'Track a Swap flag and the last unchecked position',lead:'The supplied algorithm sets Swap to FALSE at the beginning of a pass and changes it to TRUE whenever a swap occurs.',example:{title:'Core control structure',lines:['First ← 1','Last ← 10','REPEAT','  Swap ← FALSE','  FOR Index ← First TO Last - 1','    compare adjacent values and swap when needed','  NEXT Index','  Last ← Last - 1','UNTIL (NOT Swap) OR Last = 1']},accent:'emerald'}),

  s({id:'ch7-book-75-difference',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'7.5 · VALIDATION VS VERIFICATION',title:'Reasonable data and accurately copied data are different checks',lead:'Validation checks reasonableness before acceptance. Verification checks that data has not changed while being copied or entered.',keyTerms:[{term:'Validation',definition:'Automated checking that input data is reasonable before the system accepts it.'},{term:'Verification',definition:'Checking that data has been copied accurately from its source.'}],activity:a('Choose the purpose','Write VALIDATION or VERIFICATION: “Is 120 a reasonable percentage mark?” · “Was 62 copied as 62?”.','120 as a percentage → validation · copied 62 → verification.'),accent:'indigo'}),
  s({id:'ch7-book-75-validation-list',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'7.5.1 · SIX VALIDATION CHECKS',title:'Select a validation check that matches the rule',lead:'More than one check can be used on the same input item.',bullets:['Range check','Length check','Type check','Presence check','Format check','Check digit'],accent:'cyan'}),
  s({id:'ch7-book-75-range',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'RANGE CHECK',title:'Accept a number only when it lies between allowed limits',lead:'A range check compares the value with a lower and upper limit.',example:{title:'Percentage mark',lines:['Allowed: 0 to 100 inclusive','Reject when StudentMark < 0 OR StudentMark > 100','Repeat until StudentMark >= 0 AND StudentMark <= 100']},activity:a('Classify inputs','Label -1, 0, 42, 100 and 101 as ACCEPT or REJECT.','-1 reject · 0 accept · 42 accept · 100 accept · 101 reject.'),accent:'emerald'}),
  s({id:'ch7-book-75-length',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'LENGTH CHECK',title:'Check an exact length or an allowed interval of lengths',lead:'LENGTH returns the number of characters in a string.',bullets:['Exact example: password must be exactly 8 characters.','Interval example: family name must contain 2–30 characters inclusive.'],activity:a('Write the rejection condition','A password must contain 8–12 characters inclusive. Write the condition that identifies an invalid length.','LENGTH(Password) < 8 OR LENGTH(Password) > 12'),accent:'amber'}),
  s({id:'ch7-book-75-type-presence',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'TYPE CHECK AND PRESENCE CHECK',title:'Check the kind of data and whether anything was entered',lead:'A type check confirms the required data type; a presence check confirms that an input has not been left blank.',activity:a('Choose the check','Write TYPE or PRESENCE: “Number of brothers must be a whole number” · “Email address must not be empty”.','Number of brothers → type check · email not empty → presence check.'),accent:'rose'}),
  s({id:'ch7-book-75-format-checkdigit',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'FORMAT CHECK AND CHECK DIGIT · FIGURES 7.12–7.13',title:'Check a pattern or detect likely data-entry errors in a code',lead:'A format check tests a predefined pattern. A check digit is calculated from other digits and added to a code.',bullets:['Format example: XXX999.','Check digits are used in barcodes, product codes, ISBNs and VINs.','They can detect many mistyped digits, transpositions and missing/extra digits.'],activity:a('Match rule to check','Choose FORMAT or CHECK DIGIT: product code must look like ABC123 · scanned ISBN should be checked for a likely digit-entry error.','ABC123 → format check · ISBN calculated final digit → check digit.'),accent:'indigo'}),
  s({id:'ch7-book-75-findout-isbn',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'FIND OUT MORE · ISBN INVESTIGATION',title:'Investigate what a check digit can and cannot detect',lead:'Use real ISBNs to explore a transposition error and the limits of a check-digit system.',activity:a('ISBN task','Take two valid ISBNs. Copy one correctly and introduce one transposition error into the other. Exchange them with another student and identify the altered code. Then state one possible error a check-digit system may fail to identify.'),bullets:['The chapter links the ISBN/modulo-11 calculation details to Chapter 2.','Extension: investigate limit checks and consistency checks.'],accent:'cyan'}),
  s({id:'ch7-book-75-activity77',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'ACTIVITY 7.7 · APPLY VALIDATION',title:'Choose checks and write validation algorithms',lead:'Complete all three tasks using the rules exactly as stated.',activity:a('Activity 7.7','1) Choose and justify checks for a telephone number, pupil name and XXX999 part number. 2) Write pseudocode to accept age >7 and <12 AND height >110 cm and <150 cm. 3) Write pseudocode to accept password length 8–12 inclusive.'),accent:'emerald'}),
  s({id:'ch7-book-75-verification',section:'7.5 Validation & Verification',subtopicCode:'7.5',eyebrow:'7.5.2 · VERIFICATION · FIGURE 7.14',title:'Use double entry or a screen/visual check',lead:'Verification checks that entered or transferred data matches its source.',keyTerms:[{term:'Double entry',definition:'Enter the data twice. The system compares both copies and requests re-entry if they differ.'},{term:'Screen/visual check',definition:'Display the entered data so the user can compare it with the source or confirm it from their own knowledge.'}],bullets:['Parity checks and checksums are used for transferred/network data and are covered in Chapter 2.'],accent:'amber'}),

  s({id:'ch7-book-76-activity78',section:'7.6 Test Data',subtopicCode:'7.6',eyebrow:'ACTIVITY 7.8 · VERIFICATION BRIDGE',title:'Explain why valid-looking data can still need verification',lead:'Validation cannot prove that a reasonable value was copied from the source without an entry error.',activity:a('Activity 7.8','For telephone number, pupil name and XXX999 part number, write one sentence explaining why validation alone cannot prove the value was copied correctly.'),accent:'rose'}),
  s({id:'ch7-book-76-testdata',section:'7.6 Test Data',subtopicCode:'7.6',eyebrow:'7.6.1 · HOW TO SUGGEST AND APPLY TEST DATA',title:'Test sub-systems first, then the complete solution',lead:'Algorithms can be dry-run manually; programs can be executed on a computer. Thorough testing uses several data sets and known expected results.',bullets:['A set of test data contains all values needed to work through a solution.','Write the expected result before running the test.','Record the actual result.','Compare actual with expected.'],accent:'indigo'}),
  s({id:'ch7-book-76-normal',section:'7.6 Test Data',subtopicCode:'7.6',eyebrow:'NORMAL DATA · ACTIVITY 7.9',title:'Use data the solution should normally accept',lead:'Normal data represents valid input the solution is expected to process successfully.',example:{title:'Book example',lines:['Ten valid percentage marks, each 50','Expected average = 50']},activity:a('Activity 7.9','Provide a more realistic set of ten valid whole-number percentage marks and calculate the expected average before running the algorithm.'),accent:'cyan'}),
  s({id:'ch7-book-76-abnormal',section:'7.6 Test Data',subtopicCode:'7.6',eyebrow:'ABNORMAL / ERRONEOUS DATA · ACTIVITY 7.10',title:'Use data the solution should reject',lead:'Abnormal data is deliberately unsuitable and should be rejected if the validation is working correctly.',example:{title:'Percentage-mark examples',lines:['-12 → reject','"eleven" → reject']},activity:a('Activity 7.10','Create four more abnormal values for a whole-number percentage mark. For each value, write the expected result.'),accent:'emerald'}),
  s({id:'ch7-book-76-extreme-boundary',section:'7.6 Test Data',subtopicCode:'7.6',eyebrow:'EXTREME AND BOUNDARY DATA · ACTIVITY 7.11',title:'Test the limits and the values immediately around them',lead:'Extreme values are the smallest and largest accepted values. Boundary tests pair an accepted value with the adjacent rejected value.',bullets:['0–100 whole-number marks: extremes are 0 and 100.','Lower boundary pair: -1 rejected, 0 accepted.','Upper boundary pair: 100 accepted, 101 rejected.'],activity:a('Activity 7.11','1) Give the upper boundary pair for 0–100. 2) For marks out of 20, provide two normal sets, abnormal values, and both boundary pairs with expected results.','For 0–20, boundary pairs are -1/0 and 20/21.'),accent:'amber'}),

  s({id:'ch7-book-77-trace-intro',section:'7.7 Trace Tables',subtopicCode:'7.7',eyebrow:'7.7 · DRY RUNS · FIGURE 7.15 · TABLE 7.3',title:'Record every variable change in a trace table',lead:'A dry run is a manual, step-by-step execution of an algorithm. A trace table records state changes and output.',bullets:['Create one column for each variable.','Add an OUTPUT column when output occurs.','Enter a value whenever that variable changes.','Use test data in the exact given order.'],accent:'indigo'}),
  s({id:'ch7-book-77-trace-worked',section:'7.7 Trace Tables',subtopicCode:'7.7',eyebrow:'WORKED EXAMPLE · TABLE 7.4',title:'Trace the highest-and-lowest flowchart',lead:'Start A=0, B=0, C=100, then process 9, 7, 3, 12, 6, 4, 15, 2, 8, 5.',activity:a('Complete the table','Create A, B, C, X and OUTPUT columns. Work through all ten values. Record each change and the final outputs.','Final B=15 and C=2, so the output is 15 and 2.'),accent:'cyan'}),
  s({id:'ch7-book-77-activity712',section:'7.7 Trace Tables',subtopicCode:'7.7',eyebrow:'ACTIVITY 7.12',title:'Dry-run the same algorithm with a new data set',lead:'Use the same trace-table structure with a different set of ten positive numbers.',activity:a('Activity 7.12','Dry-run 400, 800, 190, 170, 300, 110, 600, 150, 130, 900. State the final output and what the algorithm appears to do.','The intended purpose is to select the largest and smallest values. This data exposes a problem with the original initial minimum value.'),accent:'emerald'}),
  s({id:'ch7-book-77-same-pseudo',section:'7.7 Trace Tables',subtopicCode:'7.7',eyebrow:'FLOWCHART ↔ PSEUDOCODE',title:'Equivalent pseudocode can use the same trace table',lead:'The representation can change while the variables, state changes and outputs being traced remain the same.',example:{title:'Core algorithm',lines:['A ← 0','B ← 0','C ← 100','REPEAT','  INPUT X','  IF X > B THEN B ← X ENDIF','  IF X < C THEN C ← X ENDIF','  A ← A + 1','UNTIL A = 10','OUTPUT B, C']},bullets:['Exam questions may use single-letter identifiers.','You may need to infer the purpose of the algorithm from its behaviour.'],accent:'amber'}),

  s({id:'ch7-book-78-activity71314',section:'7.8 Finding Errors',subtopicCode:'7.8',eyebrow:'ACTIVITIES 7.13–7.14 · TABLES 7.5–7.6',title:'Use trace tables and test data to expose errors',lead:'A trace table shows where state changes differ from the expected behaviour.',activity:a('Two dry runs','Activity 7.13: dry-run the highest/lowest pseudocode with 4,8,19,17,3,11,6,1,13,9. Activity 7.14: build a trace table for the bubble sort and dry-run 35,31,32,36,39,37,42,38.'),bullets:['The chapter demonstrates a later data set where 110 is not identified as the smallest value because of the initial assumptions.'],accent:'rose'}),
  s({id:'ch7-book-78-negative',section:'7.8 Finding Errors',subtopicCode:'7.8',eyebrow:'ACTIVITY 7.15 · FIGURE 7.16',title:'Negative test data exposes a hidden range assumption',lead:'Initialising B=0 and C=100 assumes input values lie within a narrow range.',activity:a('Activity 7.15','Choose ten negative values and dry-run the algorithm. Identify why the current initial values cause an incorrect maximum or minimum.'),bullets:['The book next tries much larger provisional limits: -1,000,000 and 1,000,000.','That increases the range but still does not make the algorithm correct for every possible data set.'],accent:'indigo'}),
  s({id:'ch7-book-78-activity716',section:'7.8 Finding Errors',subtopicCode:'7.8',eyebrow:'ACTIVITY 7.16',title:'Find values that still break fixed provisional limits',lead:'Any chosen fixed “very large” values can still be exceeded by legal input unless the problem specification guarantees a range.',activity:a('Activity 7.16','The revised version starts Maximum at -1,000,000 and Minimum at 1,000,000. Give two input values that can still make the approach fail and explain why.','Values above 1,000,000 or below -1,000,000 can invalidate those provisional assumptions.'),accent:'cyan'}),
  s({id:'ch7-book-78-first-value',section:'7.8 Finding Errors',subtopicCode:'7.8',eyebrow:'FIGURE 7.17 · ROBUST INITIALISATION',title:'Initialise maximum and minimum from the first input',lead:'A robust version reads one value first, copies it into both current maximum and current minimum, then compares the remaining nine values.',bullets:['INPUT X.','B ← X and C ← X.','Process nine more inputs.','Update B when X is larger.','Update C when X is smaller.'],accent:'emerald'}),
  s({id:'ch7-book-78-activity717',section:'7.8 Finding Errors',subtopicCode:'7.8',eyebrow:'ACTIVITY 7.17',title:'Rewrite and test the robust highest/lowest algorithm',lead:'Translate Figure 7.17 into pseudocode and test it with the supplied mixed data.',activity:a('Activity 7.17','Test with -97, 12390, 0, 77, 359, -2, -89, 5000, 21, 67.','Expected final maximum = 12390 and minimum = -97.'),accent:'amber'}),

  s({id:'ch7-book-79-eight-stages',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'7.9 · EIGHT-STAGE ALGORITHM WORKFLOW',title:'Use a repeatable process when writing an algorithm',lead:'The chapter brings the earlier tools together into an eight-stage workflow.',bullets:['1 Specify the purpose and tasks.','2 Break the problem into sub-problems.','3 Decide how data is obtained, stored, processed and displayed.','4 Design the structure with a structure diagram.','5 Choose flowchart or pseudocode.','6 Construct a precise, readable algorithm using meaningful names.','7 Dry-run normal, abnormal and boundary data with trace tables.','8 Correct errors and repeat until the algorithm works correctly.'],accent:'indigo'}),
  s({id:'ch7-book-79-fig1819',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'FIGURES 7.18–7.19 · MAX AND MIN',title:'Compare structure and flow views of the same solution',lead:'The structure diagram separates Enter values, Check all values and Output Max/Min; the flowchart shows execution order and decisions.',activity:a('Compare the diagrams','Write one thing the structure diagram communicates better and one thing the flowchart communicates better.','Structure diagram → hierarchy/modules. Flowchart → execution order, decisions and repetition.'),accent:'cyan'}),
  s({id:'ch7-book-79-example1',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'EXAMPLE 1 · CONCERT TICKETS · ACTIVITY 7.18',title:'Write, validate and test the ticket-cost algorithm',lead:'Express the earlier ticket flowchart as pseudocode, then choose data that targets the limits and discount thresholds.',bullets:['Accept only 1–25 tickets.','Use 0%, 10% and 20% discount bands.','Cost ← NumberOfTickets * 20 * (1 - Discount).'],activity:a('Activity 7.18','Classify 0, 26, 1, 25, 9, 10, 19 and 20 by test-data type. Add four useful values and dry-run them.','0/26 are rejected outside the valid range; 1/25 are valid extremes; 9/10 and 19/20 target discount boundaries.'),accent:'emerald'}),
  s({id:'ch7-book-79-example2',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'EXAMPLE 2 · SCHOOL TEST RESULTS',title:'Combine loops, validation, CASE, totals and extremes',lead:'The school example processes 600 students across Maths, Science, English and IT and outputs subject and overall statistics.',bullets:['Outer loop selects each of four tests.','CASE sets SubjectName.','Inner loop processes 600 students.','Marks are repeatedly entered until 0–100.','Subject and overall totals/highest/lowest are updated.','Calculate subject averages and then overall average.'],accent:'amber'}),
  s({id:'ch7-book-79-comments',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'READABILITY · COMMENTS AND MEANINGFUL NAMES',title:'Write algorithms that another person can understand',lead:'The coursebook annotates Example 2 to show that comments make the algorithm more understandable. The eight-stage workflow also requires clear layout and meaningful data-store names.',bullets:['Use meaningful identifiers.','Use comments to explain sections when useful.','Indent nested control structures clearly.','Write precise conditions such as Counter >= 10 rather than informal wording.'],accent:'cyan'}),
  s({id:'ch7-book-79-activity719',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'ACTIVITY 7.19',title:'Shrink the school algorithm so it can be dry-run manually',lead:'Reduce the data size without changing the algorithmic structure.',activity:a('Activity 7.19','1) Change Example 2 from 600 students / 4 subjects to 5 students / 2 subjects. 2) Choose complete test data. 3) Calculate expected results. 4) Build a trace table and compare expected with actual results.'),accent:'rose'}),
  s({id:'ch7-book-79-activity720',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'ACTIVITY 7.20',title:'Choose loops for two total-and-average algorithms',lead:'The first task has a known number of inputs; the second stops only when a sentinel value is entered.',activity:a('Activity 7.20','Write pseudocode for A) exactly ten positive numbers → total and average; B) any number of positive numbers, terminated by -1 → total and average. Explain each loop choice.','A naturally uses FOR because the count is known. B needs a condition-controlled loop because the count is not known in advance.'),accent:'indigo'}),
  s({id:'ch7-book-79-ch8-link',section:'7.9 Writing Algorithms',subtopicCode:'7.9',eyebrow:'COURSEBOOK LINK · CHAPTER 8',title:'Turn these algorithms into programs when programming begins',lead:'The chapter repeatedly links pseudocode examples to Chapter 8, where programming and further algorithm-writing practice continue.',bullets:['Write and test programs for the validation examples after programming is introduced.','Write and test programs for the concert-ticket and school-results examples.','Arrays and some operations referenced here are developed further in Chapter 8.'],accent:'amber'}),

  s({id:'ch7-book-ext-stackqueue',section:'Extension',subtopicCode:'7.9',eyebrow:'EXTENSION · FIGURE 7.20',title:'Preview Abstract Data Types: stack and queue',lead:'This extension is intended for learners interested in A Level Computer Science.',keyTerms:[{term:'Stack',definition:'A LIFO structure: the last item added is the first item removed. Operations include push and pop.'},{term:'Queue',definition:'A FIFO structure: the first item added is the first item removed. Operations include enqueue and dequeue.'}],bullets:['Stack uses Top Pointer and Base Pointer.','Queue uses Front Pointer and End Pointer.','In the book example, 27 is added first and 79 is added last.'],accent:'cyan'}),
  s({id:'ch7-book-ext-operations',section:'Extension',subtopicCode:'7.9',eyebrow:'FIGURES 7.21–7.22 · STACK AND QUEUE OPERATIONS',title:'Track how stack and queue pointers move',lead:'The diagrams show pop/push and dequeue/enqueue on the example data.',bullets:['Stack pop removes the current top item.','Stack push adds a new top item.','The Base Pointer remains fixed during stack operations.','Queue dequeue removes the front item.','Queue enqueue adds at the end.','Both Front and End pointers can change in queue operations.'],activity:a('Extension activity','Starting from the displayed structures, draw a stack after one pop and a queue after one dequeue. Label all pointers.'),accent:'emerald'}),

  s({id:'ch7-book-review',section:'Chapter Review',subtopicCode:'7.9',eyebrow:'CHAPTER 7 · COMPLETE REVIEW',title:'Check that every Chapter 7 skill is connected',lead:'Use the chapter summary as a final mastery checklist.',bullets:['Program development life cycle','Decomposition of systems and problems','Structure diagrams, flowcharts and pseudocode','Explaining algorithm purpose','Standard methods of solution','Validation and verification','Suitable test data','Trace tables and dry runs','Writing, amending and identifying errors'],activity:a('Traffic-light check','Mark each line GREEN if you can explain it and complete a task without help, AMBER if you need one example, or RED if you need reteaching.'),accent:'amber'}),
  s({id:'ch7-book-keyterms-a',section:'Chapter Review',subtopicCode:'7.9',eyebrow:'KEY TERMS · PART 1',title:'Development and system vocabulary',lead:'Use these definitions to consolidate the terminology from the chapter.',keyTerms:[{term:'Analysis',definition:'Investigation leading to a specification of what a program is required to do.'},{term:'Design',definition:'Uses the specification to show how the program should be developed.'},{term:'Coding',definition:'Writing the program or suite of programs.'},{term:'Testing',definition:'Systematic checks to make sure a program works under required conditions.'},{term:'Abstraction',definition:'Keep required elements and discard unnecessary detail.'},{term:'Decomposition',definition:'Break a complex problem into smaller, easier parts.'},{term:'Top-down design',definition:'Break a system into smaller sub-systems until each final part performs one action.'}],accent:'indigo'}),
  s({id:'ch7-book-keyterms-b',section:'Chapter Review',subtopicCode:'7.9',eyebrow:'KEY TERMS · PART 2',title:'Algorithm and component vocabulary',lead:'Match each term to the role it plays in a solution.',keyTerms:[{term:'Input',definition:'Data entered while the system is active.'},{term:'Process',definition:'Tasks performed using input and stored data.'},{term:'Output',definition:'Information displayed or printed for users.'},{term:'Storage',definition:'Data kept for future use.'},{term:'Structure diagram',definition:'Hierarchical diagram showing system breakdown.'},{term:'Flowchart',definition:'Diagram showing task steps and their order.'},{term:'Algorithm',definition:'An ordered set of steps to solve a problem.'},{term:'Pseudocode',definition:'Programming-like English used to express an algorithm without strict language syntax.'}],accent:'cyan'}),
  s({id:'ch7-book-keyterms-c',section:'Chapter Review',subtopicCode:'7.9',eyebrow:'KEY TERMS · PART 3',title:'Testing, validation and standard-method vocabulary',lead:'Use the final vocabulary set to distinguish similar concepts precisely.',keyTerms:[{term:'Linear search',definition:'Inspect each list item in turn for the required value.'},{term:'Bubble sort',definition:'Repeatedly compare and swap adjacent items until sorted.'},{term:'Set of test data',definition:'All items of data required to work through a solution.'},{term:'Normal data',definition:'Data that should be accepted.'},{term:'Abnormal data',definition:'Data that should be rejected.'},{term:'Extreme data',definition:'Smallest/largest accepted values.'},{term:'Boundary data',definition:'Boundary accepted values paired with adjacent rejected values.'},{term:'Validation',definition:'Automated check that data is reasonable before acceptance.'},{term:'Verification',definition:'Check that data was copied accurately.'},{term:'Range / length / type / presence / format',definition:'Validation checks for numeric limits, character count, data type, non-blank entry and required pattern.'},{term:'Check digit',definition:'An additional calculated digit used to detect likely data-entry errors in a code.'}],accent:'emerald'}),

  s({id:'ch7-book-exam-1-2',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTIONS · 1–2',title:'Decomposition and structure diagrams',lead:'Answer using the terminology and diagram rules from this chapter.',activity:a('Question 1 · [8]','A solution is decomposed into component parts. Name and describe the four component types used in this chapter.'),bullets:['Question 2 · [6]: Provide a structure diagram for a system that creates a modulo-11 check digit for numbers containing 4–20 digits.'],accent:'emerald'}),
  s({id:'ch7-book-exam-3',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTION · 3',title:'Restaurant-bill app: validation and test data',lead:'The app splits a bill between up to 12 diners and accepts bill values from $10 to $500.',bullets:['a [2] Choose validation checks for number of diners and bill size.','b [4] Give two normal data sets and expected results.','c [1] Give abnormal/erroneous data.','d [4] Give boundary data and expected results.'],accent:'amber'}),
  s({id:'ch7-book-exam-4-5',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTIONS · 4–5',title:'Validation and verification',lead:'Distinguish the two purposes, then apply suitable checks to form data.',bullets:['Question 4 · [4]: Explain validation and verification.','Question 5 · [8]: For Name, Date of birth, Password and Phone number, state suitable validation and verification checks and give reasons.'],accent:'rose'}),
  s({id:'ch7-book-exam-6a',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTION · 6 · BOOK p. 296',title:'Parcel algorithm: dry-run the flowchart',lead:'The algorithm checks ten parcels from Length and Breadth, calculates Size, and counts accepted and rejected parcels.',activity:a('Question 6a · [5]','Complete a trace table using ten Length/Breadth pairs: 15,10 · 20,17 · 32,10 · 30,35 · 30,15 · 30,28 · 25,25 · 20,15 · 40,20 · 12,10.'),accent:'indigo'}),
  s({id:'ch7-book-exam-6bc',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTION · 6 · CONTINUED',title:'Explain the parcel algorithm',lead:'Base every answer on the decisions and processes in the supplied flowchart.',bullets:['b [3] State the processes included in the algorithm.','c [3] Identify the rules required to accept a parcel.'],activity:a('Use the algorithm only','Do not add real-world parcel rules that are not shown in the flowchart.'),accent:'cyan'}),
  s({id:'ch7-book-exam-7',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTION · 7',title:'Find every error in a faulty total algorithm',lead:'The supplied pseudocode is intended to add ten positive numbers and output the total, but several statements are wrong.',example:{title:'Faulty outline',lines:['Counter ← 1','FOR Counter ← 1 TO 10','  REPEAT','    INPUT Number','  UNTIL Number < 0','  Total ← Total + Counter','  Counter ← Counter + 1','  OUTPUT Total','NEXT Number']},bullets:['a [5] Identify all errors.','b [4] Rewrite it correctly.','c [4] Create a trace table and test data.','d [3] Classify test data as normal, erroneous and extreme.'],accent:'emerald'}),
  s({id:'ch7-book-exam-8',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTION · 8 · 0478/22 JUNE 2018 Q3',title:'Trace and improve a calculator algorithm',lead:'The pseudocode repeatedly inputs two non-zero numbers and a sign, performs the selected arithmetic operation, and terminates when the first number is zero.',activity:a('Question 8a · [3]','Complete the trace table for: 5,7,+ · 6,2,- · 4,3,* · 7,8,? · 0,0,/.'),bullets:['b [3] Replace the repeated IF statements with a more suitable alternative conditional structure in pseudocode.'],accent:'amber'}),
  s({id:'ch7-book-exam-9',section:'Exam-style Questions',subtopicCode:'7.9',eyebrow:'EXAM-STYLE QUESTION · 9 · 0478/22 JUNE 2018 Q4',title:'Validate and verify contributor details',lead:'A routine stores a contributor’s name, email address and password.',bullets:['a [4] Explain why the three items are verified and describe how verification can be performed.','b [2] Describe validation checks suitable for email address and password.'],activity:a('Answer with purpose + method','For each part, separate WHY the check is needed from HOW it is performed.'),accent:'rose'}),
];

export const CHAPTER_7_BOOK_SOURCE_COVERAGE = {
  sections: ['7.1','7.2','7.3','7.4','7.5','7.6','7.7','7.8','7.9'],
  activities: Array.from({ length: 20 }, (_, index) => `7.${index + 1}`),
  figures: Array.from({ length: 22 }, (_, index) => `7.${index + 1}`),
  tables: Array.from({ length: 6 }, (_, index) => `7.${index + 1}`),
  examQuestions: ['1','2','3','4','5','6','7','8','9'],
} as const;
