import type { LessonPresentationBeat } from './lesson-experience-model';

const visible=(reveal:number,step:number)=>reveal>=step?'is-visible':'';
const Step=({n,title,text,reveal}:{n:number;title:string;text:string;reveal:number})=><div className={`h14m-step ${visible(reveal,n)}`}><b>{String(n).padStart(2,'0')}</b><div><strong>{title}</strong><p>{text}</p></div></div>;
const Pill=({children}:{children:React.ReactNode})=><span className="h14m-pill">{children}</span>;

function Hero({kicker,statement,detail}:{kicker:string;statement:string;detail:string}){return <div className="h14m-hero"><span>{kicker}</span><strong>{statement}</strong><p>{detail}</p><i aria-hidden="true"/></div>}
function Flow({items,reveal}:{items:Array<[string,string]>;reveal:number}){return <div className="h14m-flow">{items.map(([title,text],index)=><Step key={title} n={index+1} title={title} text={text} reveal={reveal}/>)}</div>}
function Split({leftTitle,rightTitle,left,right,reveal}:{leftTitle:string;rightTitle:string;left:string[];right:string[];reveal:number}){return <div className="h14m-split"><section><header>{leftTitle}</header>{left.map((item,i)=><p className={visible(reveal,i+1)} key={item}>{item}</p>)}</section><div className="h14m-vs">VS</div><section><header>{rightTitle}</header>{right.map((item,i)=><p className={visible(reveal,i+1)} key={item}>{item}</p>)}</section></div>}
function Network({mode,reveal}:{mode:'circuit'|'packet';reveal:number}){
  const nodes=[['A',60,170],['R2',210,95],['R1',210,245],['R5',375,95],['R6',375,245],['R8',540,95],['R3',540,245],['R7',705,95],['R9',705,245],['R10',870,95],['R4',870,245],['B',1010,170]] as const;
  const edges=[[0,1],[0,2],[1,3],[1,4],[2,3],[2,4],[3,5],[3,6],[4,5],[4,6],[5,7],[5,8],[6,7],[6,8],[7,9],[7,10],[8,9],[8,10],[9,11],[10,11]];
  const route=[0,1,3,5,7,9,11];
  return <div className={`h14m-network h14m-network--${mode}`}><svg viewBox="0 0 1070 340" role="img" aria-label={mode==='circuit'?'Dedicated circuit route A R2 R5 R8 R7 R10 B':'Four packets use independent routes'}>{edges.map(([a,b],i)=><line key={i} x1={nodes[a][1]} y1={nodes[a][2]} x2={nodes[b][1]} y2={nodes[b][2]} className="base"/>)}{mode==='circuit'&&route.slice(0,-1).map((a,i)=><line key={`r${i}`} x1={nodes[a][1]} y1={nodes[a][2]} x2={nodes[route[i+1]][1]} y2={nodes[route[i+1]][2]} className={`route ${visible(reveal,i+1)}`}/>)}{mode==='packet'&&[
    'M60 170 L210 95 L375 95 L540 95 L705 95 L870 95 L1010 170',
    'M60 170 L210 245 L375 95 L540 245 L705 95 L870 245 L1010 170',
    'M60 170 L210 95 L375 245 L540 95 L705 245 L870 95 L1010 170',
    'M60 170 L210 245 L375 245 L540 245 L705 245 L870 245 L1010 170',
  ].map((d,i)=><path d={d} key={d} className={`packet-route p${i+1} ${visible(reveal,i+1)}`}/>)}{nodes.map(([name,x,y])=><g key={name} transform={`translate(${x} ${y})`}><circle r={name==='A'||name==='B'?29:22}/><text y="5">{name}</text></g>)}{mode==='packet'&&[1,2,3,4].map((p,i)=><g key={p} className={visible(reveal,p)} transform={`translate(${150+i*35} ${165+i%2*28-14})`}><rect width="32" height="22" rx="6"/><text x="16" y="15">P{p}</text></g>)}</svg><footer>{mode==='circuit'?<><Pill>A → R2 → R5 → R8 → R7 → R10 → B</Pill><span>One dedicated route remains reserved for the communication.</span></>:<><Pill>4 PACKETS</Pill><span>Each packet can choose its own path; destination reassembles the message.</span></>}</footer></div>
}
function Frame({reveal}:{reveal:number}){const fields=[['PRE-AMBLE','8 B'],['START','1 B'],['DESTINATION','6 B'],['SOURCE','6 B'],['TYPE / LENGTH','2 B'],['ACTUAL MESSAGE','46–1500 B'],['FRAME CHECK','4 B'],['INTERPACKET GAP','12 B']];return <div className="h14m-bitfield"><div>{fields.map(([name,size],i)=><section className={visible(reveal,i+1)} key={name} data-wide={name==='ACTUAL MESSAGE'}><strong>{name}</strong><small>{size}</small></section>)}</div><p>Ethernet data in Figure 14.5 is shown as 64–1518 bytes; the interpacket gap sits outside that data block.</p></div>}
function Header({extended,reveal}:{extended?:boolean;reveal:number}){const core=[['SOURCE IP','32 bits'],['DESTINATION IP','32 bits'],['HOP','8 bits'],['LENGTH','16 bits'],['PACKET COUNT','16 bits'],['SEQUENCE','16 bits'],['CHECKSUM','16 bits']];const more=[['VERSION','4 bits'],['HEADER LENGTH','4 bits · ×4 bytes'],['PRIORITY','8 bits'],['FRAGMENT FLAGS','3 bits · DF/MF'],['FRAGMENT OFFSET','13 bits'],['PROTOCOL','8 bits · TCP/UDP']];const fields=extended?[...more,...core]:core;return <div className="h14m-header"><div>{fields.map(([name,size],i)=><section className={visible(reveal,Math.ceil((i+1)/2))} key={name}><strong>{name}</strong><small>{size}</small></section>)}</div>{extended?<p><b>Header length example:</b> value 6 means 6 × 4 = 24 bytes. DF = do not fragment; MF = more fragments follow.</p>:<p>Core Figure 14.9 fields support addressing, lifetime control, reassembly and error checking.</p>}</div>}
function TcpStack({reveal}:{reveal:number}){const layers=[['4','APPLICATION','Programs and application protocols exchange data.'],['3','TRANSPORT','TCP regulates connections, sequencing, acknowledgement and retransmission.'],['2','INTERNET','IP identifies network/host and supports routing between networks.'],['1','LINK','Frames move across the local segment using MAC/physical addressing.']];return <div className="h14m-stack"><aside><b>↓</b><span>SENDING 4 → 1</span></aside><main>{layers.map(([n,name,text],i)=><section className={visible(reveal,i+1)} key={name}><i>{n}</i><div><strong>{name}</strong><p>{text}</p></div></section>)}</main><aside><span>RECEIVING 1 → 4</span><b>↑</b></aside></div>}
function Email({reveal}:{reveal:number}){const items=[['CLIENT','writes email'],['SMTP / MIME','push + attachments'],['ISP MAIL SERVER','sender side'],['INTERNET','transfer'],['DOMAIN MAIL SERVER','recipient side'],['POP / IMAP','pull / synchronise'],['RECIPIENT','reads email']];return <div className="h14m-email">{items.map(([a,b],i)=><section key={a} className={visible(reveal,Math.min(i+1,6))}><strong>{a}</strong><small>{b}</small>{i<items.length-1?<i>→</i>:null}</section>)}</div>}
function Handshake({reveal}:{reveal:number}){return <div className="h14m-handshake"><header><b>HOST X</b><b>HOST Y</b></header><main><i/><i/><Step n={1} title="X → Y" text="Segment includes synchronisation sequence bits so segments can be received in the correct order." reveal={reveal}/><Step n={2} title="Y → X" text="Acknowledgement + Y’s own synchronisation sequence bits." reveal={reveal}/><Step n={3} title="X → Y" text="X acknowledges that Y’s segment was received." reveal={reveal}/><Step n={4} title="DATA" text="Transmission between X and Y can now take place." reveal={reveal}/></main></div>}
function ProtocolMap({reveal}:{reveal:number}){const items=[['HTTP','web-page resources'],['SMTP','send email'],['POP3/4','receive email'],['IMAP','receive/synchronise'],['DNS','domain → IP'],['FTP','file transfer'],['RIP','routing information'],['SNMP','network management']];return <div className="h14m-orbit"><div>APPLICATION<br/>LAYER</div>{items.map(([a,b],i)=><section key={a} className={visible(reveal,Math.ceil((i+1)/2))}><strong>{a}</strong><small>{b}</small></section>)}</div>}
function Torrent({reveal}:{reveal:number}){return <div className="h14m-torrent"><svg viewBox="0 0 1000 390" role="img" aria-label="BitTorrent tracker and swarm"><circle cx="500" cy="195" r="62" className="tracker"/><text x="500" y="201" className="tracker-label">TRACKER</text>{[[160,80,'SEED'],[330,70,'PEER'],[670,70,'LEECH'],[840,95,'NEW'],[850,285,'SEED'],[660,320,'NEW'],[340,320,'LEECH'],[150,280,'SEED']].map(([x,y,label],i)=><g key={`${x}-${y}`} className={visible(reveal,Math.min(4,Math.ceil((i+1)/2)))}><line x1="500" y1="195" x2={Number(x)} y2={Number(y)}/><circle cx={Number(x)} cy={Number(y)} r="33"/><text x={Number(x)} y={Number(y)+5}>{label}</text></g>)}</svg><footer className={visible(reveal,4)}><Pill>20 MiB → 20 × 1 MiB pieces</Pill><span>Peers become sources for pieces they receive; pieces may arrive non-sequentially and are rearranged.</span></footer></div>}
function Routing({reveal}:{reveal:number}){return <div className="h14m-routing"><div className={visible(reveal,1)}><strong>PACKET HEADER</strong><span>destination IP · hop number · checksum</span></div><i className={visible(reveal,2)}>→</i><div className={`table ${visible(reveal,2)}`}><strong>ROUTING TABLE</strong><span>hops · next-router MAC · metrics · network ID · gateway · netmask · interface</span></div><i className={visible(reveal,3)}>→</i><div className={`router ${visible(reveal,3)}`}><strong>ROUTER DECISION</strong><span>select shortest/best route and add next-router MAC</span></div><footer className={visible(reveal,4)}>No route found or hop number = 0 → router deletes the data package.</footer></div>}
function Retrieval({items,reveal}:{items:string[];reveal:number}){return <div className="h14m-retrieval">{items.map((item,i)=><section className={visible(reveal,Math.min(i+1,4))} key={item}><b>{String(i+1).padStart(2,'0')}</b><p>{item}</p></section>)}</div>}

export const CHAPTER_14_MASTER_VISUAL_IDS=[
'h14p-141-hook','h14p-141-objectives','h14p-141-protocol','h14p-141-stack','h14p-141-units','h14p-141-protocol-map','h14p-141-ftp-detail','h14p-141-http','h14p-141-email','h14p-141-email-mechanics','h14p-141-pop-imap','h14p-141-transport-family','h14p-141-tcp','h14p-141-ip-link','h14p-141-ethernet','h14p-141-ethernet-detail','h14p-141-wireless','h14p-141-bittorrent','h14p-141-bittorrent-terms','h14p-141-check','h14p-142-hook','h14p-142-objectives','h14p-142-circuit-stages','h14p-142-circuit-route','h14p-142-circuit-failure','h14p-142-packet-basics','h14p-142-packet-route','h14p-142-compare','h14p-142-circuit-pros-cons','h14p-142-packet-pros-cons','h14p-142-video-example','h14p-142-hop','h14p-142-packet-control','h14p-142-header','h14p-142-header-extended','h14p-142-routing','h14p-142-routing-fields','h14p-142-web-page','h14p-142-exam','h14p-142-activity14a','h14p-142-practice','h14p-142-recap','h14p-142-recap-routing'] as const;
const masterIds=new Set<string>(CHAPTER_14_MASTER_VISUAL_IDS);
export function hasChapter14PresentationMaster(beat:LessonPresentationBeat){return masterIds.has(beat.id)}

export function Chapter14PresentationMaster({beat,reveal}:{beat:LessonPresentationBeat;reveal:number}){
  switch(beat.id){
    case 'h14p-141-hook':return <Hero kicker="COMMUNICATION NEEDS AGREEMENT" statement="Same data. Different rules. Failed communication." detail="If sender and receiver do not agree the protocol, even a simple parity check cannot be interpreted reliably."/>;
    case 'h14p-141-objectives':return <Retrieval reveal={reveal} items={['Explain why communication protocols are required.','Describe the four TCP/IP layers and sending/receiving direction.','Apply HTTP, email, Ethernet, wireless and BitTorrent terminology.']}/>;
    case 'h14p-141-protocol':return <Hero kicker="PROTOCOL" statement="Rules must be agreed at both ends." detail="Coursebook example: parity checking only works when sender and receiver agree whether even or odd parity is being used."/>;
    case 'h14p-141-stack':return <TcpStack reveal={reveal}/>;
    case 'h14p-141-units':return <Flow reveal={reveal} items={[["APPLICATION DATA","The original data begins at the application layer."],["SEGMENT","Transport-layer unit; transport control information is added."],["DATAGRAM","Internet-layer unit; IP addressing/routing information is added."],["FRAME","Data-link unit for local transmission; link-layer information is added."]]}/>;
    case 'h14p-141-protocol-map':return <ProtocolMap reveal={reveal}/>;
    case 'h14p-141-ftp-detail':return <Flow reveal={reveal} items={[["CONNECT","FTP transfers files between computers/devices over the internet or another network."],["ANONYMOUS ACCESS","Coursebook confirmation example: 331 Anonymous access allowed."],["COMMANDS","delete · close · rename · cd (remote directory) · lcd (local directory)."],["SESSION","ftp host_name → user id → password; files are stored on the FTP server."]]}/>;
    case 'h14p-141-http':return <Flow reveal={reveal} items={[["URL","User keys the URL into the browser."],["HTTP(S) → TCP","Application request is passed to the transport layer."],["TCP / PORT 80","TCP creates data packets and sends them via port 80 in the coursebook sequence."],["DNS","Domain name is looked up in the DNS URL/IP database."],["ACKNOWLEDGEMENT","Server TCP sends an acknowledgement once communication is being established."],["HTML RESPONSE","Web server returns the page; browser interprets it or passes media to the media player."]]}/>;
    case 'h14p-141-email':return <Email reveal={reveal}/>;
    case 'h14p-141-email-mechanics':return <Flow reveal={reveal} items={[["SMTP · PUSH","Text-based and connection-based; client keeps the connection active and uploads new email."],["MIME","Used for media/binary attachments; a MIME header helps the client choose the required media player."],["POP / IMAP · PULL","Client periodically connects, checks/downloads email, then closes the connection."],["COURSEBOOK NOTE","The book notes increased HTTP use, while SMTP remains used between email servers."]]}/>;
    case 'h14p-141-pop-imap':return <Split reveal={reveal} leftTitle="POP3/4" rightTitle="IMAP" left={['Server and client are not kept synchronised in the coursebook model.','Downloaded emails are then deleted from the server.']} right={['Server and client stay synchronised.','A copy is downloaded; original remains until the client manually deletes it.']}/>;
    case 'h14p-141-transport-family':return <Flow reveal={reveal} items={[["TCP","Protocol considered in detail by this chapter."],["UDP + SCTP","Named as transport-layer protocols; not developed further here."],["PAR","Positive acknowledgement with retransmission: missing positive acknowledgement causes automatic resend."]]}/>;
    case 'h14p-141-tcp':return <Handshake reveal={reveal}/>;
    case 'h14p-141-ip-link':return <Split reveal={reveal} leftTitle="INTERNET LAYER · IP" rightTitle="NETWORK / DATA-LINK" left={['Identifies intended network and host.','Adds source and recipient IP addresses.','Ensures routing across networks.']} right={['Identifies/moves traffic across local segments.','Encapsulates IP packets into frames.','Maps IP addresses to MAC/physical addresses.']}/>;
    case 'h14p-141-ethernet':return <Frame reveal={reveal}/>;
    case 'h14p-141-ethernet-detail':return <Flow reveal={reveal} items={[["DESTINATION","6-byte destination MAC; FF:FF:FF:FF:FF:FF broadcasts to every device."],["SOURCE","6-byte source MAC address."],["TYPE / LENGTH","Coursebook rule: ≤1539 gives length; >1539 gives Ethernet type such as IPv4/IPv6."],["FRAME CHECK / VLAN","Checksum supports integrity; source notes VLAN can increase frame size to around 9000 bytes."]]}/>;
    case 'h14p-141-wireless':return <Split reveal={reveal} leftTitle="WiFi · IEEE 802.11" rightTitle="Bluetooth / WiMax" left={['CSMA/CA uses DCF.','Transmit only when a free channel is available.','No acknowledgement → random wait → retry.']} right={['Bluetooth: IEEE 802.15, short-range communication.','WiMax: IEEE 802.16 for WMAN.','Fixed 802.16-2004 · mobile 802.16-2005.']}/>;
    case 'h14p-141-bittorrent':return <Torrent reveal={reveal}/>;
    case 'h14p-141-bittorrent-terms':return <Flow reveal={reveal} items={[["SWARM + AVAILABILITY","Swarm = connected peers; availability = number of complete copies distributed among the swarm."],["SEED","Peer makes a downloaded file or pieces available to other peers."],["TRACKER","Central server stores peer details/IP addresses so peers can locate one another."],["LEECH / LURKER","Poor share ratio has negative impact; lurker downloads but contributes no new content. Share ratio = uploaded ÷ downloaded."]]}/>;
    case 'h14p-141-check':return <Retrieval reveal={reveal} items={['Why must sender and receiver agree a protocol?','Name TCP/IP layers in sending order.','Which protocols send and receive email?','Explain one difference between a datagram and a frame.','Define seed and tracker.']}/>;
    case 'h14p-142-hook':return <Hero kicker="ONE MESSAGE · TWO ROUTING MODELS" statement="Reserve one path — or let packets choose independently?" detail="Circuit switching ties up a dedicated channel. Packet switching divides the message and routes packets independently."/>;
    case 'h14p-142-objectives':return <Retrieval reveal={reveal} items={['Explain circuit switching and its three stages.','Explain packet switching and independent routing.','Use headers, hop numbers and routing tables to explain router decisions.']}/>;
    case 'h14p-142-circuit-stages':return <Flow reveal={reveal} items={[["ESTABLISH","Create a dedicated circuit/channel between sender and receiver."],["TRANSFER","Data transfer can be analogue or digital; transmission is usually bi-directional."],["TERMINATE","After transfer, terminate the connection and release the circuit."]]}/>;
    case 'h14p-142-circuit-route':return <Network mode="circuit" reveal={reveal}/>;
    case 'h14p-142-circuit-failure':return <Hero kicker="DEDICATED MEANS INFLEXIBLE" statement="A fault on the reserved line has no alternative route." detail="The circuit is tied up throughout the communication, even when idle; link setup can also take time."/>;
    case 'h14p-142-packet-basics':return <Flow reveal={reveal} items={[["SPLIT","Break the message into packets."],["ROUTE","Each packet travels independently."],["SELECT","Routing depends on queued datagrams; shortest available path is selected."],["REASSEMBLE","Packets may arrive in a different order and must be rebuilt at the destination."]]}/>;
    case 'h14p-142-packet-route':return <Network mode="packet" reveal={reveal}/>;
    case 'h14p-142-compare':return <Split reveal={reveal} leftTitle="CIRCUIT SWITCHING" rightTitle="PACKET SWITCHING" left={['Route is established before transmission.','Dedicated path; frames use same route and arrive in order.','Whole channel bandwidth is reserved.']} right={['Packets can take independent routes.','Shared network; packets can arrive out of order.','Destination reassembles packets.']}/>;
    case 'h14p-142-circuit-pros-cons':return <Split reveal={reveal} leftTitle="BENEFITS" rightTitle="DRAWBACKS" left={['Dedicated transmission only.','Whole bandwidth available.','Frames arrive in order; source says better for real-time.']} right={['Inflexible; idle circuit unavailable to others.','No alternative route after a fault.','Greater bandwidth requirement and setup delay.']}/>;
    case 'h14p-142-packet-pros-cons':return <Split reveal={reveal} leftTitle="BENEFITS" rightTitle="DRAWBACKS" left={['No need to tie up one communication line.','Can re-route around failed/faulty lines.','Traffic can expand; digital data is transmitted directly.']} right={['Protocols are more complex; lost packet must be resent.','Shared bandwidth and destination reassembly cause delay.','Source notes poor real-time performance and large RAM requirements.']}/>;
    case 'h14p-142-video-example':return <Split reveal={reveal} leftTitle="PACKET SWITCHING · COURSEBOOK SYMPTOMS" rightTitle="CIRCUIT · COURSEBOOK IMPROVEMENTS" left={['Picture/sound may lose synchronisation.','Pauses from reassembly delay; degraded quality from competing traffic.','Possible drop-out if packets are lost.']} right={['One route keeps arrival order.','Dedicated channel gives full bandwidth.','Source solution states no loss of synchronisation.']}/>;
    case 'h14p-142-hop':return <Flow reveal={reveal} items={[["SET FINITE HOP NUMBER","The header limits how many routers a packet may traverse."],["DECREMENT","Every router decreases hop number by 1."],["DELETE AT ZERO","If packet has not reached destination and hop reaches 0, it is deleted at the next router."]]}/>;
    case 'h14p-142-packet-control':return <Flow reveal={reveal} items={[["CHECKSUM / PARITY","Error-checking value travels with the packet."],["RECALCULATE","Destination recalculates and compares checksum."],["RE-SEND","Different values trigger a request to resend the packet."],["PRIORITY","Header may contain priority; high priority selects which packet queue is used."]]}/>;
    case 'h14p-142-header':return <Header reveal={reveal}/>;
    case 'h14p-142-header-extended':return <Header extended reveal={reveal}/>;
    case 'h14p-142-routing':return <Routing reveal={reveal}/>;
    case 'h14p-142-routing-fields':return <Retrieval reveal={reveal} items={['number of hops','MAC address of next router','metrics / route cost','network destination / network ID','gateway / next hop','netmask','interface']}/>;
    case 'h14p-142-web-page':return <Flow reveal={reveal} items={[["DIVIDE PAGE","Web page is divided into data packets."],["READ HEADER","Each packet header includes destination IP."],["LOOK UP ROUTE","Router compares header with routing table and selects next router."],["UPDATE + CHECK","Add next-router MAC; check hop value is not zero."],["INDEPENDENT ROUTES","Packets may travel by different routes."],["REASSEMBLE","Destination computer rebuilds the final web page."]]}/>;
    case 'h14p-142-exam':return <Retrieval reveal={reveal} items={['Explain why a routing table is needed.','State what happens when hop number reaches zero before destination.','Explain why a checksum may cause retransmission.','Describe how next-router MAC is used.']}/>;
    case 'h14p-142-activity14a':return <Retrieval reveal={reveal} items={['TCP/IP layers + one protocol per layer + email protocols / SMTP vs MIME.','Ethernet definition, frame contents and how IP enables external communication.','BitTorrent peer, swarm, tracker, leech, seed and dealing with leeches.','Packet header vs routing table and how both route a packet.','VoIP packet switching and possible problems.']}/>;
    case 'h14p-142-practice':return <Retrieval reveal={reveal} items={['Q1 — protocols / TCP-IP / email and Ethernet terminology.','Q2 — BitTorrent metadata, pieces, tracker/swarm/seed/leech concepts.','Q3 — circuit switching, packet switching and routing application.','Q4 — circuit vs packet statements; hop/checksum; packet headers and routing tables.']}/>;
    case 'h14p-142-recap':return <Hero kicker="CHAPTER 14 · RETRIEVAL" statement="Protocols define the rules. Headers carry control data. Routers choose the next hop." detail="Be able to connect the whole journey: application protocol → TCP/IP layers → frame/packet → switching method → routing table → destination."/>;
    case 'h14p-142-recap-routing':return <Retrieval reveal={reveal} items={beat.bullets??['Explain why a sequence number is required.','Explain what happens when a hop number reaches zero before the destination.']}/>;
    default:return null;
  }
}
