import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 6 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

const sourceRange = (from: number, to: number, elements: string[] = []) => ({
  sourcePages: Array.from({ length: to - from + 1 }, (_, index) => from + index),
  sourceLabel: `Hodder Chapter 6 · pp.${from}–${to}`,
  sourceElements: [`Hodder pp.${from}–${to}`, ...elements],
});

export const CHAPTER_6_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h6-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 6 · SECURITY, PRIVACY AND DATA INTEGRITY',
    title: 'Protecting data means controlling access, reducing loss and checking correctness',
    lead: 'Chapter 6 separates three related ideas: data security, data privacy and data integrity, then connects them to practical controls, threats, recovery, validation and verification.',
    richBlocks: [{ kind: 'steps', title: 'Chapter route', items: [
      'Define security, privacy and integrity and explain why each matters.',
      'Apply access controls, passwords, signatures, firewalls, anti-malware, encryption and biometrics.',
      'Recognise hacking, malware, phishing and pharming and choose suitable countermeasures.',
      'Plan recovery from accidental, hardware, software and operational failures.',
      'Use validation and verification during data entry and transfer.',
    ] }],
    activity: { title: 'Prior-knowledge check', prompt: 'Explain hacking, compare hacking with cracking, discuss contactless-card security, and state why removable storage must be disconnected correctly.' },
    visual: 'types', accent: 'indigo', ...source(159, ['Chapter 6 learning objectives', 'What you should already know', 'Key terms']),
  },
  {
    id: 'h6-611-privacy', section: '6.1 Data security', subtopicCode: '6.1.1', eyebrow: '6.1.1 · DATA PRIVACY · DATA PROTECTION LAWS',
    title: 'Privacy requires personal and organisational data to remain protected from unauthorised access',
    lead: 'The coursebook presents data protection laws as one mechanism for protecting privacy and summarises common principles governing fair, relevant, accurate, secure and time-limited processing.',
    bullets: [
      'Data should be processed lawfully and only for a stated purpose.',
      'Only adequate and relevant data should be collected, and it should be kept accurate.',
      'Data should not be kept longer than necessary and should be handled according to the data subject’s rights.',
      'Data must be secured and should not be transferred to a country without adequate protection.',
      'Legal penalties can deter misuse, although legislation alone cannot guarantee privacy.',
    ],
    keyTerms: [
      { term: 'Data privacy', definition: 'Keeping personal or other sensitive information from unauthorised parties.' },
      { term: 'Data protection laws', definition: 'Laws governing how data should be kept private and secure.' },
    ],
    visual: 'types', accent: 'cyan', ...source(160, ['6.1.1 Data privacy', 'Eight guiding data-protection principles']),
  },
  {
    id: 'h6-612-accounts-passwords', section: '6.1 Data security', subtopicCode: '6.1.2', eyebrow: '6.1.2 · USER ACCOUNTS · ACCESS RIGHTS · PASSWORDS',
    title: 'Authentication identifies a user; access rights decide what that user may reach',
    lead: 'User accounts can link a username and password to a hierarchy of access levels, so different users see only the data appropriate to their role.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Authentication', rightTitle: 'Authorisation / access rights', rows: [
      ['Proves that a user is who they claim to be.', 'Controls which data or system areas an authenticated user can use.'],
      ['Commonly uses a username and password.', 'Can assign different access levels to different roles.'],
      ['Prevents anonymous entry to protected services.', 'Limits unnecessary exposure after a user has logged in.'],
    ] }],
    bullets: [
      'Passwords should be difficult to guess or crack and should be changed regularly.',
      'The coursebook recommends combining upper-case letters, numbers and other keyboard characters.',
      'Anti-spyware can reduce the risk of passwords being captured and relayed by malicious software.',
      'Passwords based on obvious personal information such as birthdays, names or pets are weak choices.',
    ],
    activity: { title: 'Extension Activity 6A', prompt: 'Design access levels for an airport system so senior staff can access all required data while customers can access only public flight and duty-free information.' },
    visual: 'types', accent: 'emerald', ...source(161, ['Figure 6.1 login screen', 'Extension Activity 6A', 'Access-right hierarchy', 'Strong passwords']),
  },
  {
    id: 'h6-612-signatures-firewall', section: '6.1 Data security', subtopicCode: '6.1.2', eyebrow: 'DIGITAL SIGNATURES · FIREWALLS · FIGURE 6.2',
    title: 'Digital signatures identify a sender while firewalls control network traffic',
    lead: 'Digital signatures provide a way to identify the sender of an electronic message. A firewall sits between a computer or internal network and an external network and filters incoming and outgoing communication.',
    bullets: [
      'A firewall examines traffic and checks it against configured criteria.',
      'Traffic that fails the rules can be blocked and a warning can be generated.',
      'Incoming and outgoing traffic can be logged for later investigation.',
      'A firewall can block undesirable destinations or IP addresses and warn when local software attempts an external connection.',
      'Firewalls can be implemented in hardware or software.',
    ],
    activity: { title: 'Extension Activity 6B', prompt: 'Classify several sample passwords as strong or weak and justify each decision from their structure and predictability.' },
    visual: 'networking', accent: 'amber', ...source(162, ['Digital signatures', 'Figure 6.2 Firewall', 'Extension Activity 6B']),
  },
  {
    id: 'h6-612-antimalware-encryption-biometrics', section: '6.1 Data security', subtopicCode: '6.1.2', eyebrow: 'FIREWALL LIMITS · ANTIVIRUS · ANTI-SPYWARE · ENCRYPTION · BIOMETRICS',
    title: 'No single control is sufficient: layered protection covers different attack paths',
    lead: 'The coursebook explicitly notes that firewalls cannot prevent every harmful action, then adds antivirus, anti-spyware, encryption and biometric authentication as complementary controls.',
    richBlocks: [{ kind: 'table', table: { caption: 'Layered controls', headers: ['Control', 'Main role'], rows: [
      ['Firewall', 'filters network traffic but cannot prevent every internal or user-caused security failure'],
      ['Antivirus', 'checks files, compares known signatures, uses heuristic behaviour checks and quarantines suspicious items'],
      ['Anti-spyware', 'detects and removes spyware using rules or known spyware structures'],
      ['Encryption', 'makes stolen data unreadable without the appropriate decryption key'],
      ['Biometrics', 'uses unique human characteristics such as fingerprints, retina patterns, face or voice'],
    ] } }],
    bullets: [
      'Antivirus definitions must be kept current and full scans should be run regularly.',
      'Heuristic checking is useful when suspicious behaviour is not yet represented in the known-virus database.',
      'A false positive occurs when legitimate software is incorrectly identified as infected.',
      'Encryption protects confidentiality but does not stop an attacker from deleting encrypted files.',
    ],
    visual: 'types', accent: 'rose', ...source(163, ['Firewall limitations', 'Antivirus software', 'Anti-spyware software', 'Encryption', 'Biometrics']),
  },
  {
    id: 'h6-613-biometric-hacking-malware', section: '6.1 Data security', subtopicCode: '6.1.3', eyebrow: '6.1.3 · BIOMETRICS · HACKING · MALWARE',
    title: 'Security threats range from unauthorised access to self-replicating malicious code',
    lead: 'Fingerprint and retina scans illustrate biometric authentication, while the chapter distinguishes malicious hacking from authorised ethical hacking before introducing malware.',
    bullets: [
      'Fingerprint systems compare stored and presented ridge-and-valley patterns.',
      'Retina scanning uses the distinctive pattern of blood vessels at the back of the eye.',
      'Malicious hacking is unauthorised access intended to steal, alter, corrupt or delete data.',
      'Ethical hacking is authorised testing used to identify weaknesses in a system’s defences.',
      'Viruses are malicious code that can replicate or copy themselves and damage files, programs or system operation.',
    ],
    visual: 'types', accent: 'indigo', ...source(164, ['Figure 6.3 Fingerprint', 'Figure 6.4 Retina scan', 'Malicious hacking', 'Ethical hacking', 'Viruses']),
  },
  {
    id: 'h6-613-malware-phishing', section: '6.1 Data security', subtopicCode: '6.1.3', eyebrow: 'WORMS · LOGIC BOMBS · TROJANS · BOTS · SPYWARE · PHISHING',
    title: 'Different malware families behave differently, so the defence must match the threat',
    lead: 'The chapter distinguishes several forms of malicious software and then explains phishing as a social-engineering attack that requires the victim to act.',
    richBlocks: [{ kind: 'table', table: { caption: 'Threat families', headers: ['Threat', 'Behaviour'], rows: [
      ['Worm', 'stand-alone malware that replicates and spreads, often by searching networks for weak security'],
      ['Logic bomb', 'code that activates when a trigger condition is met'],
      ['Trojan horse', 'malicious program disguised as legitimate software'],
      ['Bot', 'automated software that can be used legitimately or can take control of systems for attacks'],
      ['Spyware', 'secretly gathers information, for example by key logging'],
      ['Phishing', 'deceptive messages or links that trick a user into revealing information or visiting a fake site'],
    ] } }],
    bullets: [
      'Security awareness training helps users recognise deceptive messages.',
      'Users should avoid untrusted links and attachments and keep browsers and security software up to date.',
      'The chapter also recommends checking secure-site indicators, monitoring online accounts and using firewalls.',
    ],
    visual: 'networking', accent: 'cyan', ...source(165, ['Worms', 'Logic bombs', 'Trojan horses', 'Bots', 'Spyware', 'Phishing']),
  },
  {
    id: 'h6-613-pharming', section: '6.1 Data security', subtopicCode: '6.1.3', eyebrow: 'PHARMING · DNS CACHE POISONING · EXTENSION ACTIVITY 6C',
    title: 'Pharming redirects the user without requiring the same deliberate action as phishing',
    lead: 'Pharming can alter name-resolution information or install malicious code so a legitimate-looking address sends the user to a fraudulent website.',
    bullets: [
      'DNS cache poisoning changes stored address information so a real domain resolves to a fake website.',
      'Malicious code on a user’s computer can also change the returned address and redirect the browser.',
      'Modern browsers, antivirus software, careful spelling checks and secure-site indicators can reduce risk.',
      'If a DNS server itself is compromised, mitigation is more difficult than when only one user device is infected.',
    ],
    activity: { title: 'Phishing versus pharming', prompt: 'State the key difference in user action required by phishing and pharming, then explain how DNS cache poisoning can support a pharming attack.' },
    visual: 'networking', accent: 'emerald', ...source(166, ['Pharming', 'DNS cache poisoning', 'Protection against pharming', 'Extension Activity 6C']),
  },
  {
    id: 'h6-614-recovery', section: '6.1 Data security', subtopicCode: '6.1.4', eyebrow: '6.1.4 · DATA RECOVERY · FIGURE 6.5',
    title: 'Recovery planning matches safeguards to the cause of data loss',
    lead: 'The coursebook compares accidental deletion, hardware faults, software faults and incorrect operation and maps each to appropriate safeguards.',
    richBlocks: [{ kind: 'table', table: { caption: 'Figure 6.5 recovery logic', headers: ['Risk', 'Safeguards'], rows: [
      ['Accidental loss', 'regular saving, backups and access restrictions'],
      ['Hardware fault', 'backups, UPS protection, regular saving and parallel backup hardware where appropriate'],
      ['Software fault', 'backups and frequent saving so a crash loses less work'],
      ['Incorrect operation', 'backups plus training in correct hardware and shutdown procedures'],
    ] } }],
    bullets: [
      'Backups should be stored on another medium and in a separate location from the original data.',
      'Responsibility for regular backups should be assigned rather than assumed.',
      'A backup can be dangerous after malware infection if it also contains the malware that caused the original problem.',
    ],
    visual: 'files', accent: 'amber', ...source(167, ['6.1.4 Data recovery', 'Figure 6.5 Safeguards']),
  },
  {
    id: 'h6-61-activity', section: '6.1 Data security', eyebrow: 'ACTIVITY 6A · APPLY SECURITY CONTROLS',
    title: 'Apply the security model to realistic organisations and users',
    lead: 'The chapter activity asks learners to connect threats, consequences and mitigations rather than memorising isolated definitions.',
    richBlocks: [{ kind: 'steps', title: 'Activity 6A tasks', items: [
      'Identify three security issues for an international company sharing data over the internet.',
      'Explain why each issue is a threat and propose a mitigation.',
      'Define worm, logic bomb and Trojan horse.',
      'Evaluate weak personal passwords and improve password-maintenance practice.',
      'Explain why saving a password on a shared or exposed device can be risky.',
      'Recognise a suspicious order-confirmation message as a phishing scenario and justify the warning signs.',
    ] }],
    visual: 'recap', accent: 'rose', ...source(168, ['Activity 6A']),
  },
  {
    id: 'h6-62-integrity-overview', section: '6.2 Data integrity', eyebrow: '6.2 · DATA INTEGRITY · KEY TERMS',
    title: 'Integrity means keeping data accurate, complete and consistent',
    lead: 'The coursebook identifies data entry, transmission, malicious attack and accidental hardware-related loss as routes by which integrity can be compromised.',
    keyTerms: [
      { term: 'Data integrity', definition: 'The accuracy, completeness and consistency of data.' },
      { term: 'Validation', definition: 'Checking that entered data is reasonable and meets defined input criteria.' },
      { term: 'Verification', definition: 'Checking that data has been entered or transferred correctly.' },
      { term: 'Check digit', definition: 'An extra digit appended to a number to help detect input errors.' },
      { term: 'Checksum', definition: 'A value calculated from a block of data and compared after transmission.' },
      { term: 'Parity check', definition: 'An error-detection method based on an agreed even or odd number of 1-bits.' },
    ],
    activity: { title: 'Prior-knowledge check', prompt: 'Explain why validation is useful, why proofreading is not the same as verification, and how a form can restrict a date to an agreed format.' },
    visual: 'types', accent: 'indigo', ...source(169, ['6.2 Data integrity', 'What you should already know', 'Key terms']),
  },
  {
    id: 'h6-621-validation', section: '6.2 Data integrity', subtopicCode: '6.2.1', eyebrow: '6.2.1 · VALIDATION · TABLE 6.1',
    title: 'Validation checks reasonableness and rule compliance, not factual correctness',
    lead: 'A plausible but wrong value can pass validation. The software only knows whether the value satisfies the rules that have been defined.',
    richBlocks: [{ kind: 'table', table: { caption: 'Common validation checks', headers: ['Check', 'What it tests'], rows: [
      ['Type', 'whether data is of the required type'],
      ['Range', 'whether data lies between lower and upper limits'],
      ['Format', 'whether the structure matches an agreed pattern'],
      ['Length', 'whether the required number of characters or digits is present'],
      ['Presence', 'whether a required field has been completed'],
      ['Existence', 'whether a referenced value or file actually exists'],
      ['Limit', 'whether a value satisfies one boundary condition'],
      ['Consistency', 'whether related fields agree logically'],
      ['Uniqueness', 'whether a value that must be unique has already been used'],
    ] } }],
    teacherPrompt: 'Ask students to design two different validation checks for a school registration form and explain what each cannot guarantee.',
    visual: 'recap', accent: 'cyan', ...source(170, ['Table 6.1 Common validation', '6.2.2 Verification introduction']),
  },
  {
    id: 'h6-622-entry-verification', section: '6.2 Data integrity', subtopicCode: '6.2.2', eyebrow: '6.2.2 · DOUBLE ENTRY · VISUAL CHECK · CHECK DIGIT',
    title: 'Verification during data entry compares the entered value with an independent reference',
    lead: 'The chapter gives three entry-verification approaches: double entry, visual comparison with the source and check digits for structured identifiers.',
    bullets: [
      'Double entry records the data twice, ideally independently, and compares the results.',
      'A visual check compares what is on screen with the original source document.',
      'Check digits are used with identifiers such as barcodes, ISBNs and VINs to detect common entry errors.',
      'Check digits can detect incorrect digits, transpositions, omitted or added digits and some phonetic-number errors.',
    ],
    visual: 'recap', accent: 'emerald', ...source(171, ['Double entry', 'Visual check', 'Check digits', 'Figure 6.6 Barcode']),
  },
  {
    id: 'h6-622-modulo11-checksum', section: '6.2 Data integrity', subtopicCode: '6.2.2', eyebrow: 'MODULO-11 · CHECKSUM · FIGURE 6.7',
    title: 'Check digits verify identifiers; checksums verify transmitted blocks',
    lead: 'Modulo-11 applies weighted arithmetic to an identifier to generate a check digit. A checksum applies arithmetic to a block of transmitted data and is recalculated at the receiver.',
    richBlocks: [
      { kind: 'steps', title: 'Modulo-11 model used in the chapter', items: [
        'Apply descending weights to the digits.',
        'Multiply each digit by its weight and add the products.',
        'Divide the total by 11 and use the remainder to derive the check digit.',
        'Recalculate after entry; a mismatch indicates an error.',
      ] },
      { kind: 'steps', title: 'Checksum verification', items: [
        'Calculate a checksum for the block before transmission.',
        'Send the checksum with the block.',
        'Recalculate the checksum from the received block.',
        'Accept matching values or request retransmission when they differ.',
      ] },
    ],
    activity: { title: 'Extension Activity 6D', prompt: 'Compare the modulo-11 method with ISBN-13 check-digit calculation and identify a practical use of modulo-11.' },
    visual: 'recap', accent: 'amber', ...sourceRange(171, 172, ['Modulo-11', 'Extension Activity 6D', 'Checksums', 'Figure 6.7']),
  },
  {
    id: 'h6-622-parity', section: '6.2 Data integrity', subtopicCode: '6.2.2', eyebrow: 'PARITY CHECK · FIGURES 6.8–6.10 · EXTENSION ACTIVITY 6E',
    title: 'Parity uses an agreed even-or-odd rule to detect changes in a transmitted byte',
    lead: 'A parity bit is added so the number of 1-bits in the transmitted byte matches the agreed parity protocol.',
    bullets: [
      'With even parity, the transmitted byte contains an even number of 1-bits; with odd parity, it contains an odd number.',
      'Sender and receiver must agree the parity convention before transmission.',
      'At the receiver, parity is recalculated. A parity change signals that a transmission error has occurred.',
      'A simple parity check detects that something changed but does not by itself identify which bit is wrong.',
    ],
    activity: { title: 'Extension Activity 6E', prompt: 'Calculate the required parity bit for several bytes using both even and odd parity.' },
    visual: 'recap', accent: 'indigo', ...source(173, ['Figures 6.8–6.10', 'Parity check', 'Parity bit', 'Extension Activity 6E']),
  },
  {
    id: 'h6-622-parity-block', section: '6.2 Data integrity', subtopicCode: '6.2.2', eyebrow: 'PARITY BLOCK · PARITY BYTE · TABLE 6.2',
    title: 'Two-dimensional parity can locate a single-bit error',
    lead: 'A parity block checks rows and columns. The extra parity byte supplies vertical parity information, so the intersection of a failing row and column can identify a changed bit.',
    bullets: [
      'Horizontal parity identifies the byte whose parity is wrong.',
      'Vertical parity identifies the bit position or column whose parity is wrong.',
      'The row-column intersection can locate one erroneous bit so it can be corrected or retransmitted.',
      'Multiple changed bits can preserve parity and therefore escape this method, so parity is often combined with other checks.',
    ],
    activity: { title: 'Extension Activity 6F', prompt: 'Given received bytes and an agreed parity rule, identify which bytes fail parity and discuss whether the exact wrong bit can always be determined.' },
    visual: 'recap', accent: 'cyan', ...source(174, ['Table 6.2', 'Parity block', 'Parity byte', 'Extension Activity 6F']),
  },
  {
    id: 'h6-622-arq', section: '6.2 Data integrity', subtopicCode: '6.2.2', eyebrow: 'AUTOMATIC REPEAT REQUEST · ACKNOWLEDGEMENT · TIMEOUT',
    title: 'ARQ turns error detection into a retransmission protocol',
    lead: 'Automatic repeat request combines acknowledgements and a timeout so the sender knows whether to continue or retransmit.',
    richBlocks: [{ kind: 'steps', title: 'ARQ cycle', items: [
      'Receiver checks the arriving packet for an error.',
      'If the packet is correct, the receiver sends a positive acknowledgement.',
      'If an error is detected, the receiver asks for retransmission.',
      'The sender also retransmits if no acknowledgement arrives before the timeout.',
      'The cycle continues until correct receipt or until the ARQ time limit is reached.',
    ] }],
    bullets: ['The chapter notes mobile-phone networks as an example where ARQ can be used to protect data integrity.'],
    visual: 'networking', accent: 'emerald', ...source(175, ['Automatic repeat request', 'Acknowledgement', 'Timeout']),
  },
  {
    id: 'h6-62-activity', section: '6.2 Data integrity', eyebrow: 'ACTIVITY 6B · INTEGRITY PRACTICE',
    title: 'Validation and verification must be chosen for the field and the error risk',
    lead: 'The activity combines a parity-block error task with form-design questions and asks learners to explain why both validation and verification are required.',
    richBlocks: [{ kind: 'steps', title: 'Activity 6B tasks', items: [
      'Locate a changed bit in a received block that uses odd parity and propose the corrected byte.',
      'Choose suitable validation checks for name, date of birth, telephone number and title/sex fields.',
      'Explain the difference between validation and verification and why both support integrity.',
      'Design verification and validation for item code, stock level, unit cost and supplier telephone number.',
    ] }],
    visual: 'recap', accent: 'amber', ...source(176, ['Activity 6B']),
  },
  {
    id: 'h6-review', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS · p.177',
    title: 'Synthesis: combine controls, validation and transfer checks in exam-style scenarios',
    lead: 'The closing questions test security controls, modulo-11, validation, antivirus, firewalls and parity blocks in applied contexts.',
    activity: { title: 'Exam practice', prompt: 'For a college database, propose security measures, calculate or explain a check-digit method, select validation checks, explain antivirus and firewall protection, and trace a parity-block transmission error.' },
    bullets: [
      'Do not confuse validation with verification: one checks acceptability against rules, the other checks accurate copying or transfer.',
      'Do not name a control without linking it to the threat or failure that it addresses.',
      'For parity-block questions, inspect both the failing row and failing column before identifying the incorrect bit.',
    ],
    visual: 'recap', accent: 'rose', ...source(177, ['End-of-chapter questions']),
  },
];

export const CHAPTER_6_FINAL: HodderLessonChapter = {
  number: 6,
  level: 'AS Level',
  title: 'Security, privacy and data integrity',
  subtitle: 'Data privacy · access control · malware and social engineering · recovery · validation · verification',
  subtopics: ['6.1 Data security', '6.2 Data integrity'],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 Chapter 6, printed pp.159–177, preserving the chapter sequence, terminology, examples and source-page provenance.',
  coverage: '19/19 printed chapter pages represented (pp.159–177): security/privacy/integrity definitions; data protection; accounts, access rights and passwords; digital signatures, firewalls, antivirus, anti-spyware, encryption and biometrics; hacking and malware; phishing/pharming and DNS cache poisoning; data recovery; validation; double entry, visual checks and check digits; modulo-11; checksums; parity and parity blocks; ARQ; activities and end-of-chapter exam practice.',
  slides: CHAPTER_6_DEEP_SLIDES,
};
