import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const pages = (start: number, end = start) => Array.from({ length: end - start + 1 }, (_, i) => start + i);
const source = (start: number, end = start, elements: string[] = []) => ({
  sourcePages: pages(start, end),
  sourceLabel: `Hodder Chapter 18 · pp.${start}${end === start ? '' : `–${end}`}`,
  sourceElements: [`Hodder pp.${start}${end === start ? '' : `–${end}`}`, ...elements],
});

export const CHAPTER_18_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h18-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 18 · ARTIFICIAL INTELLIGENCE (AI)',
    title: 'Shortest-path algorithms and learning systems form the two strands of Chapter 18',
    lead: 'The source moves from Dijkstra and A* to AI, machine learning, deep learning, neural networks, back propagation and regression.',
    bullets: ['Use Dijkstra and A* on graphs and grids.', 'Distinguish AI, machine learning and deep learning.', 'Explain supervised, unsupervised, reinforcement and semi-supervised learning.', 'Explain artificial neural networks, back propagation and regression.'],
    visual: 'recap', accent: 'indigo', ...source(425, 425, ['Chapter objectives', 'Prior knowledge', 'Dijkstra', 'A*', 'Heuristic']),
  },
  {
    id: 'h18-1811-dijkstra-steps', section: '18.1 Shortest path algorithms', subtopicCode: '18.1.1', eyebrow: '18.1.1 · DIJKSTRA’S ALGORITHM',
    title: 'Dijkstra fixes the smallest tentative distance and expands outward from the start vertex',
    lead: 'The source assigns the start vertex final value 0, gives adjacent vertices working values, repeatedly finalises the smallest working value and finally traces the route backward.',
    richBlocks: [{ kind: 'steps', title: 'Source method', items: ['Set the start vertex final value to 0.', 'Assign or improve working values on adjacent vertices.', 'Promote the smallest working value to a final value.', 'Repeat until the destination is reached.', 'Trace backward from the destination to recover the shortest route.'] }],
    visual: 'recap', accent: 'cyan', ...source(425, 426, ['Dijkstra source steps', 'Figures 18.1–18.2']),
  },
  {
    id: 'h18-1811-dijkstra-worked', section: '18.1 Shortest path algorithms', subtopicCode: '18.1.1', eyebrow: 'FIGURES 18.1–18.8 · WORKED ROUTE',
    title: 'The worked graph finishes with A → B → E → G and distance 17',
    lead: 'Pages 426–429 show each working/final-value update and explain why a tentative value changes only when a shorter route is found.',
    bullets: ['B becomes 5, C becomes 6, D becomes 9, E becomes 11, F becomes 12 and G becomes 17.', 'The backward check uses the rule that a route edge length equals the difference between final values at its endpoints.'],
    activity: { title: 'Activity 18A', prompt: 'Apply the same method to the park graph and find the shortest path from A to I.' },
    visual: 'recap', accent: 'emerald', ...source(426, 429, ['Figures 18.3–18.8', 'Activity 18A']),
  },
  {
    id: 'h18-1812-astar-heuristic', section: '18.1 Shortest path algorithms', subtopicCode: '18.1.2', eyebrow: '18.1.2 · A* · h, g, f, n',
    title: 'A* adds a heuristic estimate so the search is guided toward the destination',
    lead: 'The source grid gives each node h for heuristic distance, g for movement cost, f for g+h and n for the previous node.',
    bullets: ['The example uses Manhattan distance for h.', 'Blocked cells are ignored while calculating the heuristic distance.', 'Orthogonal and diagonal movement use source g-costs based on 10, 10 and 14.'],
    visual: 'recap', accent: 'indigo', ...source(429, 430, ['Figures 18.9–18.11', 'Manhattan', 'heuristic']),
  },
  {
    id: 'h18-1812-astar-f-values', section: '18.1 Shortest path algorithms', subtopicCode: '18.1.2', eyebrow: 'f(n) = g(n) + h(n)',
    title: 'A* compares candidate moves with combined movement cost and heuristic estimate',
    lead: 'Figures 18.12–18.16 repeatedly calculate g, h and f values and compare competing partial routes.',
    bullets: ['Compute candidate movement cost g.', 'Add the heuristic h to obtain f.', 'Prefer the smallest candidate while retaining the previous-node relationship.', 'Compare accumulated route possibilities rather than choosing direction alone.'],
    visual: 'recap', accent: 'amber', ...source(431, 432, ['Figures 18.12–18.16', 'g(n)', 'h(n)', 'f(n)']),
  },
  {
    id: 'h18-1812-astar-route-activities', section: '18.1 Shortest path algorithms', subtopicCode: '18.1.2', eyebrow: 'FIGURE 18.17 · ACTIVITY 18B',
    title: 'The source completes the grid route and then applies A* and Dijkstra to new networks',
    lead: 'The worked route reaches (8,6); the following activities ask learners to calculate their own h/g values and solve walking and road-network shortest-path problems.',
    bullets: ['Applications named include GPS, Google Maps, infectious-disease modelling and IP routing.'],
    activity: { title: 'Activity 18B', prompt: 'Solve one A* problem and one Dijkstra problem from pp.432–434, showing intermediate values.' },
    visual: 'recap', accent: 'rose', ...source(432, 434, ['Figure 18.17', 'Activity 18B', 'GPS', 'IP routing']),
  },
  {
    id: 'h18-1821-ai-hierarchy', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.1', eyebrow: '18.2.1 · AI ⊃ ML ⊃ DL',
    title: 'Deep learning is a subset of machine learning, which is a subset of AI',
    lead: 'Figure 18.18 gives the hierarchy and the source classifies AI as narrow AI, general AI or strong AI relative to human performance.',
    richBlocks: [{ kind: 'table', table: { headers: ['Category', 'Source meaning'], rows: [['Narrow AI', 'Superior at one specific task.'], ['General AI', 'Human-like performance across intellectual tasks.'], ['Strong AI', 'Superior performance across many tasks.']] } }],
    activity: { title: 'Extension Activity 18A', prompt: 'Research knowledge representation, automated reasoning, computer vision and robotics.' },
    visual: 'recap', accent: 'indigo', ...source(435, 435, ['Figure 18.18', 'Narrow AI', 'General AI', 'Strong AI']),
  },
  {
    id: 'h18-1822-machine-learning', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.2', eyebrow: '18.2.2 · MACHINE LEARNING',
    title: 'Machine learning uses previous examples and experience to improve later predictions or decisions',
    lead: 'The source uses smart assistants and search-engine success/failure as examples of systems that learn from incoming data and past outcomes.',
    bullets: ['Machine learning can analyse large, complex data sets rapidly.', 'Figure 18.19 shows voice interaction with a smart device.', 'Figure 18.20 treats relevant result placement as success/failure feedback.'],
    visual: 'recap', accent: 'cyan', ...source(436, 436, ['Figures 18.19–18.20', 'Machine learning']),
  },
  {
    id: 'h18-1822-labelled-data', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.2', eyebrow: 'LABELLED VS UNLABELLED DATA',
    title: 'Labelled data has known target information; unlabelled data still needs recognition or categorisation',
    lead: 'The source uses vehicle records and bird features to explain how identified examples can train a model and how unknown objects need classification.',
    bullets: ['Labelled data includes the recognised target information.', 'Unlabelled data contains undefined objects.', 'Bird beak, colour and body size are examples of features used in recognition.'],
    visual: 'types', accent: 'emerald', ...source(437, 438, ['Labelled data', 'Unlabelled data', 'Figure 18.21']),
  },
  {
    id: 'h18-1822-supervised-unsupervised', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.2', eyebrow: 'SUPERVISED VS UNSUPERVISED',
    title: 'Supervised learning trains against known outputs; unsupervised learning searches for hidden structure',
    lead: 'Supervised learning uses labelled input/output examples and compares predictions with expected results; unsupervised learning has no supplied “right answer” and looks for patterns in unlabelled data.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Supervised learning', rightTitle: 'Unsupervised learning', rows: [['Uses labelled data and expected outputs.', 'Uses unlabelled data without a supplied correct answer.'], ['Can perform classification/regression.', 'Finds patterns, similarities and anomalies.'], ['Source example: relevant/spam email.', 'Source methods include density estimation and k-means clustering.']] }],
    visual: 'types', accent: 'indigo', ...source(438, 439, ['Supervised learning', 'Unsupervised learning', 'k-means clustering']),
  },
  {
    id: 'h18-1822-reinforcement-active', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.2', eyebrow: 'REINFORCEMENT · SEMI-SUPERVISED',
    title: 'Reinforcement optimises actions through reward/punishment; active learning mixes labelled and unlabelled data',
    lead: 'The source contrasts trial-and-error optimisation with semi-supervised learning that combines a small labelled set with much larger cheaper unlabelled data.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Reinforcement learning', rightTitle: 'Semi-supervised (active) learning', rows: [['Learns through trial and error.', 'Uses labelled and unlabelled data.'], ['Reward and punishment guide optimisation.', 'Interactively queries source data.'], ['Examples: games, robotics, search engines.', 'Example: web-page classification with a web crawler.']] }],
    visual: 'types', accent: 'amber', ...source(439, 439, ['Reinforcement learning', 'Reward and punishment', 'Semi-supervised', 'Web crawler']),
  },
  {
    id: 'h18-1823-neural-networks', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.3', eyebrow: '18.2.3 · ARTIFICIAL NEURAL NETWORKS',
    title: 'Deep learning uses input, hidden and output layers to learn complex representations',
    lead: 'The source relates artificial neural networks to interconnected neurons and uses facial/object recognition to show how learned features are processed.',
    bullets: ['Hidden layers transform input data.', 'Face recognition uses measurements such as eye distance, nose width, cheekbones, jaw and eyebrows.', 'Figure 18.23 shows two hidden layers.'],
    visual: 'recap', accent: 'rose', ...source(439, 440, ['Artificial neural network', 'Figures 18.22–18.24']),
  },
  {
    id: 'h18-1823-deep-workflow', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.3', eyebrow: 'TRAIN · TEST · REFINE',
    title: 'The source deep-learning workflow trains on large data, tests against known examples and refines the model',
    lead: 'If outputs are not reliable enough, the model is refined repeatedly; the chapter links this to the back-propagation section later.',
    bullets: ['Text mining combines deep-learning categorisation with machine-learning analysis.', 'Computer-assisted translation uses terminology databases and translation memories.'],
    visual: 'recap', accent: 'emerald', ...source(441, 441, ['Figures 18.25–18.26', 'Text mining', 'Computer-assisted translation']),
  },
  {
    id: 'h18-1823-applications', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.3', eyebrow: 'PHOTOS · COLOURISATION · CHATBOTS',
    title: 'Deep-learning applications transform images and support conversational interaction',
    lead: 'The source applies deep learning to improving smartphone photographs, colourising monochrome images and chatbots that respond to typed or spoken input.',
    bullets: ['A smartphone/DSLR pair can provide training examples for enhancement.', 'A trained model maps monochrome features to plausible colours.', 'Chatbots combine scripts and machine learning to simulate conversation.'],
    visual: 'recap', accent: 'cyan', ...source(442, 443, ['Figures 18.27–18.29', 'Chatbot', 'Photo enhancement', 'Colourisation']),
  },
  {
    id: 'h18-1824-comparison', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.4', eyebrow: '18.2.4 · TABLE 18.1',
    title: 'Machine learning and deep learning differ in data volume, feature engineering and explainability',
    lead: 'Table 18.1 contrasts the two approaches by training-data volume, feature engineering, modular versus end-to-end design and how easily their decisions can be explained.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Machine learning', rightTitle: 'Deep learning', rows: [['Can use smaller training sets.', 'Typically needs large training sets.'], ['Features are commonly engineered in advance.', 'Features are learned from data.'], ['More modular problem solving.', 'More end-to-end problem solving.'], ['Decision path can be clearer.', 'Can behave as a black box.']] }],
    visual: 'types', accent: 'indigo', ...source(443, 443, ['Table 18.1', 'Black box']),
  },
  {
    id: 'h18-1825-future', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.5', eyebrow: '18.2.5 · TABLE 18.2',
    title: 'The source presents future AI/ML/DL uses as examples that require ongoing updating',
    lead: 'Table 18.2 lists possible future developments, while Extension Activity 18B explicitly asks learners to research a fast-changing field.',
    bullets: ['AI examples include crime-pattern detection and humanoid tasks.', 'Machine-learning examples include healthcare diagnostics and marketing.', 'Deep-learning examples include personalised treatment and advanced assistants.'],
    activity: { title: 'Extension Activity 18B', prompt: 'Research current and future AI, machine-learning and deep-learning developments.' },
    visual: 'recap', accent: 'amber', ...source(443, 444, ['Table 18.2', 'Extension Activity 18B']),
  },
  {
    id: 'h18-1826-backprop', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.6', eyebrow: '18.2.6 · BACK PROPAGATION',
    title: 'Back propagation adjusts neural weights using the error between actual and expected output',
    lead: 'The source starts with random weightings, calculates error gradients, feeds those errors backward and repeats training until error is sufficiently small.',
    richBlocks: [{ kind: 'steps', title: 'Training loop', items: ['Assign random weights.', 'Run training input.', 'Compare actual output with expected output.', 'Calculate error gradients.', 'Propagate error backward and update weights.', 'Repeat until acceptable.'] }],
    bullets: ['The source distinguishes static and recurrent back propagation.'],
    visual: 'recap', accent: 'rose', ...source(444, 445, ['Figures 18.30–18.31', 'Back propagation', 'Error gradient', 'Static', 'Recurrent']),
  },
  {
    id: 'h18-1826-regression', section: '18.2 Artificial intelligence, machine learning and deep learning', subtopicCode: '18.2.6', eyebrow: 'REGRESSION',
    title: 'Regression learns relationships between inputs and outputs so future values can be predicted',
    lead: 'The source describes regression as a statistical method for finding learning relationships and gives forecasting as an example use.',
    bullets: ['Regression can analyse data before it enters a model.', 'It supports prediction from learned relationships.', 'Weather forecasting is one source example.'],
    activity: { title: 'Activity 18C', prompt: 'Review AI categories, learning types, neural networks, back propagation and regression using the source questions.' },
    visual: 'recap', accent: 'cyan', ...source(445, 445, ['Regression', 'Activity 18C']),
  },
  {
    id: 'h18-review-ai-learning', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER · AI/ML/DL',
    title: 'The first review block checks AI, learning types and neural-network training vocabulary',
    lead: 'Printed review questions test AI/heuristic definitions, ML-versus-DL characteristics, learning types and the vocabulary of neural-network training and regression.',
    bullets: ['Distinguish AI and heuristic search.', 'Compare machine learning and deep learning.', 'Explain reinforcement and supervised learning.', 'Complete the back-propagation/regression cloze task.'],
    visual: 'recap', accent: 'emerald', ...source(446, 447, ['End-of-chapter questions 1–3']),
  },
  {
    id: 'h18-review-pathfinding', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER · DIJKSTRA + A*',
    title: 'The final review returns to weighted-network and grid shortest paths',
    lead: 'The route-based review asks learners to compare Dijkstra and A*, calculate shortest paths, reconstruct routes and explain how A* replans when edges become unavailable.',
    bullets: ['Solve the hotel-network Dijkstra task.', 'Solve the matrix A* task.', 'Explain route recalculation after blocked links.', 'Evaluate route changes from new edges.'],
    activity: { title: 'Route audit', prompt: 'Complete one Dijkstra and one A* review problem with all working.' },
    visual: 'recap', accent: 'indigo', ...source(448, 449, ['End-of-chapter questions 4–7']),
  },
];

export const CHAPTER_18_FINAL: HodderLessonChapter = {
  number: 18,
  level: 'A Level',
  title: 'Artificial intelligence (AI)',
  subtitle: 'Dijkstra and A* · machine learning · deep learning · neural networks · back propagation · regression',
  subtopics: ['18.1 Shortest path algorithms', '18.2 Artificial intelligence, machine learning and deep learning'],
  sourceNote: 'Deep source-backed teaching route from the uploaded Hodder 9618 Chapter 18, printed pp.425–449. Every printed chapter page is represented in slide provenance; worked shortest-path examples, learning types, neural-network applications, back propagation, regression and source review tasks follow the chapter as teaching paraphrase.',
  coverage: '25/25 printed chapter pages represented (pp.425–449): Dijkstra and A*; AI hierarchy; labelled/unlabelled data; supervised, unsupervised, reinforcement and semi-supervised learning; neural networks and deep-learning applications; ML versus DL; future examples; back propagation, error gradients, static/recurrent forms, regression and end-of-chapter review.',
  slides: CHAPTER_18_DEEP_SLIDES,
};
