import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 9 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_9_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h9-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 9 · ALGORITHM DESIGN AND PROBLEM SOLVING',
    title: 'Computational thinking turns a rigorously defined problem into an algorithm that can be tested and programmed',
    lead: 'The chapter links abstraction and decomposition to three algorithm representations — structured English, flowcharts and pseudocode — before using stepwise refinement to develop robust solutions.',
    richBlocks: [{ kind: 'steps', title: 'What this chapter teaches', items: [
      'Use abstraction and decomposition as computational-thinking skills.',
      'Write algorithms using structured English, flowcharts and pseudocode.',
      'Use the chapter’s pseudocode conventions for input, output, assignment, selection and iteration.',
      'Refine complex tasks step by step until each part is implementable.',
      'Trace and program solutions to check that the design actually works.',
    ] }],
    activity: { title: 'Prior-knowledge diagnostic', prompt: 'Define procedure, function, algorithm, structured English, flowchart and pseudocode. Then outline an algorithm that finds the average of a number of input integers.' },
    keyTerms: [
      { term: 'Abstraction', definition: 'Extracting essential information while ignoring detail that is not relevant to the solution.' },
      { term: 'Decomposition', definition: 'Breaking a complex problem into smaller parts.' },
      { term: 'Pattern recognition', definition: 'Identifying similar parts of a problem that could use the same solution.' },
    ],
    visual: 'recap', accent: 'indigo', ...source(217, ['Chapter learning objectives', 'What you should already know', 'Computational thinking key terms', 'Java', 'Python', 'VB.NET']),
  },
  {
    id: 'h9-911-abstraction', section: '9.1 Computational thinking skills', subtopicCode: '9.1.1', eyebrow: '9.1.1 · ABSTRACTION · FIGURE 9.1',
    title: 'Abstraction keeps what the model needs and deliberately removes what it does not',
    lead: 'A model is designed for a particular purpose. The road-map example keeps roads, road numbers and towns while omitting terrain detail that does not help a driver plan a journey.',
    bullets: [
      'First identify the purpose of the model before deciding which information is essential.',
      'Gather information from suitable sources such as observations, potential users and existing models.',
      'Decide which details to include, how to present them and which details are extraneous.',
      'Removing unnecessary characteristics can reduce development time, program size and download time while improving fit to customer requirements.',
      'Different purposes lead to different abstractions: a road map and a rail map do not need the same detail.',
    ],
    activity: { title: 'Model comparison', prompt: 'For a driver’s road map and a rail passenger’s map, identify one essential detail and one detail that can be omitted from each model.' },
    visual: 'recap', accent: 'cyan', ...source(218, ['Figure 9.1 Road map and satellite view', 'Purpose of a model', 'Sources of information', 'Benefits of abstraction']),
  },
  {
    id: 'h9-912-decomposition', section: '9.1 Computational thinking skills', subtopicCode: '9.1.2', eyebrow: '9.1.2 · DECOMPOSITION · FIGURE 9.2',
    title: 'Decomposition repeatedly divides a complex problem until each part is understandable and solvable',
    lead: 'The chapter connects decomposition with pattern recognition and reusable program modules: similar sub-problems can share tested procedures or functions.',
    bullets: [
      'A complex problem is broken into smaller parts, which can be subdivided again when necessary.',
      'Rigorous decomposition can reveal hidden complexity in a problem that initially appears simple.',
      'Pattern recognition identifies parts that are similar and may use the same solution.',
      'Final parts can become separate modules, procedures or functions that are written and tested independently.',
      'Previously written and tested modules can be reused to save development time.',
    ],
    richBlocks: [{ kind: 'steps', title: 'Figure 9.2 decomposition pattern', items: ['Program', 'Modules', 'Sub-modules', 'Further sub-modules where required'] }],
    visual: 'recap', accent: 'emerald', ...source(219, ['Figure 9.2 Decomposition of a program into modules', 'Pattern recognition', 'Structured English', 'Flowchart', 'Algorithm', 'Pseudocode', 'Stepwise refinement']),
  },
  {
    id: 'h9-921-three-representations', section: '9.2 Algorithms', subtopicCode: '9.2.1', eyebrow: '9.2.1 · STRUCTURED ENGLISH · FLOWCHART · PSEUDOCODE',
    title: 'The same solution can be represented in three complementary ways before programming',
    lead: 'Structured English states logical steps using controlled wording, a flowchart shows the order diagrammatically, and pseudocode gives detailed language-independent logical steps.',
    richBlocks: [{ kind: 'table', table: { caption: 'Three ways to communicate an algorithm', headers: ['Representation', 'Source-backed purpose'], rows: [
      ['Structured English', 'Show logical steps with straightforward English commands and mathematical operations; steps may be numbered.'],
      ['Flowchart', 'Show steps and their order using agreed symbols connected by flow lines.'],
      ['Pseudocode', 'Show detailed logical steps with keywords, meaningful identifiers and mathematical operators, without using one programming language’s syntax.'],
    ] } }],
    example: { title: 'Average algorithm — structured-English outline', lines: ['1 Ask for the number of values', '2 Loop that number of times', '3 Enter a value in the loop', '4 Add the value to Total', '5 Calculate and output the average'] },
    activity: { title: 'Activity 9A', prompt: 'Decompose the task of drawing regular polygons, write the solution in structured English, swap algorithms and test whether another learner can follow the instructions.' },
    visual: 'recap', accent: 'indigo', ...source(220, ['9.2.1 Writing algorithms that provide solutions to problems', 'Activity 9A', 'Average algorithm structured English and pseudocode']),
  },
  {
    id: 'h9-921-average-flowchart', section: '9.2 Algorithms', subtopicCode: '9.2.1', eyebrow: 'FIGURE 9.3 · AVERAGE ALGORITHM FLOWCHART',
    title: 'The average algorithm makes sequence, repetition and termination visible in a flowchart',
    lead: 'The flowchart initialises Total and Counter, obtains Number, repeatedly inputs and accumulates Value, tests Counter against Number, then calculates and outputs Average.',
    richBlocks: [{ kind: 'steps', title: 'Trace Figure 9.3', items: [
      'Set Total to 0 and Counter to 1.',
      'Input Number.',
      'Input Value and add it to Total.',
      'Increment Counter and test whether Counter is greater than Number.',
      'When the loop finishes, calculate Average = Total / Number.',
      'Output the number of values and the average.',
    ] }],
    activity: { title: 'Trace the flowchart', prompt: 'Use Number = 3 and values 10, 20 and 30. Record Total and Counter after every loop pass.' },
    visual: 'recap', accent: 'cyan', ...source(221, ['Figure 9.3', '9.2.2 Writing simple algorithms using pseudocode', 'Pseudocode formatting and identifier rules']),
  },
  {
    id: 'h9-922-identifiers-io-assignment', section: '9.2 Algorithms', subtopicCode: '9.2.2', eyebrow: 'IDENTIFIERS · INPUT · OUTPUT · ASSIGNMENT · TABLE 9.1',
    title: 'Pseudocode uses meaningful identifiers and explicit statements for data entering, leaving and changing',
    lead: 'The chapter recommends tracking identifiers in an identifier table and uses a left arrow for assignment so storing a value is visibly different from comparison.',
    richBlocks: [
      { kind: 'table', table: { caption: 'Identifier-table examples', headers: ['Identifier', 'Description'], rows: [['StudentName', 'Store a student name'], ['Counter', 'Store a loop counter'], ['StudentMark', 'Store a student mark']] } },
      { kind: 'code', title: 'Core statement forms', lines: ['INPUT StudentName', 'OUTPUT "Student name is ", StudentName', 'Counter ← 1', 'Counter ← Counter + 1', 'Percentage ← (StudentMark / 80) * 100', 'NewString ← OldString & " ninety-seven"'] },
    ],
    bullets: ['Arithmetic operators shown include +, -, *, /.', 'The ampersand joins strings.', 'The left arrow means assignment.', 'Identifier names should be meaningful and begin with a letter.'],
    activity: { title: 'Activity 9B', prompt: 'Trace the assignment examples and state the final value stored in each variable. Remember that ASC returns the ASCII value of a character.' },
    visual: 'types', accent: 'amber', ...source(222, ['Table 9.1', 'INPUT', 'OUTPUT', 'Assignment', 'Operators', 'Activity 9B']),
  },
  {
    id: 'h9-922-selection', section: '9.2 Algorithms', subtopicCode: '9.2.2', eyebrow: 'IF · CASE · RELATIONAL OPERATORS',
    title: 'Selection uses IF for one/two-way decisions and CASE for multiple choices',
    lead: 'The source shows both forms with and without an alternative path and then lists the relational operators used in selection conditions.',
    richBlocks: [
      { kind: 'code', title: 'IF patterns', lines: ['IF MyValue > YourValue', '  THEN', '    OUTPUT "I win"', '  ELSE', '    OUTPUT "You win"', 'ENDIF'] },
      { kind: 'code', title: 'CASE pattern', lines: ['CASE OF Direction', '  "N": Y ← Y + 1', '  "S": Y ← Y - 1', '  "E": X ← X + 1', '  "W": X ← X - 1', '  OTHERWISE : OUTPUT "Error"', 'ENDCASE'] },
    ],
    bullets: ['Relational operators include =, <>, >, <, >= and <=.', 'Programming-language syntax may differ from pseudocode even when the logical task is the same.'],
    visual: 'types', accent: 'rose', ...source(223, ['IF single choice', 'IF with alternative', 'CASE multiple choices', 'CASE with OTHERWISE', 'Relational operators']),
  },
  {
    id: 'h9-922-selection-languages', section: '9.2 Algorithms', subtopicCode: '9.2.2', eyebrow: 'PYTHON · VB.NET · JAVA · IF COMPARISON',
    title: 'Python, VB.NET and Java express the same IF logic using different syntax',
    lead: 'The chapter compares one single-choice IF across all three prescribed languages to show why an algorithm must be understood independently of programming-language punctuation and block syntax.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Pseudocode idea', rightTitle: 'Programming-language differences', rows: [
      ['Condition controls whether the THEN block runs.', 'Python uses a colon and indentation.'],
      ['A block has a clear beginning and end.', 'VB.NET uses THEN and END IF.'],
      ['The same logical comparison is performed.', 'Java uses parentheses/braces around the condition and block.'],
    ] }],
    activity: { title: 'Language comparison', prompt: 'Identify which syntax detail changes between pseudocode, Python, VB.NET and Java while the logical test MyValue > YourValue remains unchanged.' },
    visual: 'types', accent: 'cyan', ...source(224, ['Python IF example', 'VB IF example', 'Java IF example']),
  },
  {
    id: 'h9-922-iteration', section: '9.2 Algorithms', subtopicCode: '9.2.2', eyebrow: 'FOR · REPEAT–UNTIL · WHILE · ACTIVITY 9C',
    title: 'Choose an iteration construct according to how repetition should stop',
    lead: 'The source distinguishes a fixed-count FOR loop, a post-condition REPEAT loop that runs at least once, and a pre-condition WHILE loop that may not run at all.',
    richBlocks: [{ kind: 'table', table: { caption: 'Iteration constructs', headers: ['Construct', 'Source-backed behaviour'], rows: [
      ['FOR', 'Fixed number of repeats; optional STEP must be a whole number.'],
      ['REPEAT–UNTIL', 'Statements are always executed at least once before the condition is tested.'],
      ['WHILE', 'Condition is tested before the body, so the statements may not be executed.'],
    ] } }],
    example: { title: 'Pseudocode forms', lines: ['FOR Counter ← 1 TO 10 STEP 2 ... NEXT Counter', 'REPEAT ... UNTIL Number > 0', 'WHILE Number >= 0 DO ... ENDWHILE'] },
    activity: { title: 'Activity 9C', prompt: 'Implement the alternative IF and the multi-choice CASE task in one prescribed programming language and compare the program syntax with the pseudocode.' },
    visual: 'types', accent: 'emerald', ...source(225, ['FOR loop', 'REPEAT–UNTIL loop', 'WHILE loop', 'Activity 9C']),
  },
  {
    id: 'h9-922-loop-languages-logic', section: '9.2 Algorithms', subtopicCode: '9.2.2', eyebrow: 'LOOP SYNTAX · RELATIONAL + LOGIC OPERATORS',
    title: 'The loop syntax differs by language, but comparisons still reduce to TRUE or FALSE',
    lead: 'Python, VB.NET and Java use different FOR-loop syntax. The chapter then links iteration and selection to relational comparisons combined with AND, OR and NOT.',
    bullets: [
      'Python demonstrates range-based iteration.',
      'VB.NET demonstrates FOR ... TO ... STEP ... NEXT.',
      'Java demonstrates a loop with initialisation, test and update expressions.',
      'WHILE, REPEAT and IF conditions use relational operators and the logical operators AND, OR and NOT.',
      'The result of a comparison is always true or false.',
    ],
    activity: { title: 'Activity 9D', prompt: 'Translate the remaining loop examples into one prescribed programming language and record how the command words and block structure differ from the pseudocode.' },
    visual: 'types', accent: 'indigo', ...source(226, ['Python/VB/Java FOR examples', 'Activity 9D', 'AND', 'OR', 'NOT']),
  },
  {
    id: 'h9-922-validation-average', section: '9.2 Algorithms', subtopicCode: '9.2.2', eyebrow: 'VALIDATION · INT(x) · TABLE 9.2 · ACTIVITY 9E',
    title: 'A robust average algorithm validates both the count and every value before processing',
    lead: 'The chapter improves the simple average algorithm by requiring a positive whole-number count and integer values, using INT(x) to test whether an input is a whole number.',
    example: { title: 'Validation pattern', lines: ['REPEAT', '  INPUT Number', 'UNTIL (Number > 0) AND (Number = INT(Number))', 'FOR Counter ← 1 TO Number', '  REPEAT', '    INPUT Value', '  UNTIL Value = INT(Value)', '  Total ← Total + Value', 'NEXT Counter'] },
    richBlocks: [{ kind: 'table', table: { caption: 'Identifier table', headers: ['Identifier', 'Purpose'], rows: [['Total', 'Running total'], ['Number', 'Number of integer values to enter'], ['Value', 'Integer value input'], ['Average', 'Average of all values entered']] } }],
    activity: { title: 'Activity 9E', prompt: 'Write a condition that accepts a number between 10 and 20 or a number over 100, using brackets so the order of comparisons is unambiguous.' },
    visual: 'recap', accent: 'amber', ...source(227, ['INT(x)', 'Validated average algorithm', 'Table 9.2', 'Activity 9E']),
  },
  {
    id: 'h9-922-average-language-implementations', section: '9.2 Algorithms', subtopicCode: '9.2.2', eyebrow: 'AVERAGE ALGORITHM · PYTHON + VB.NET',
    title: 'Implementing the same average algorithm exposes language-specific loop behaviour',
    lead: 'The source compares implementations and points out that programming-language loop bounds and available constructs do not exactly mirror pseudocode.',
    bullets: [
      'The Python version uses a WHILE check for the positive count and range(1, Number + 1) so the final count is included.',
      'The VB.NET version uses DO ... LOOP UNTIL for the input validation and FOR ... NEXT for accumulation.',
      'Both implementations preserve the same algorithmic stages: validate count, input values, accumulate Total, calculate Average, output result.',
    ],
    visual: 'types', accent: 'cyan', ...source(228, ['Python average program', 'VB.NET average program', 'Loop-bound comparison']),
  },
  {
    id: 'h9-923-password-and-structured-english', section: '9.2 Algorithms', subtopicCode: '9.2.3', eyebrow: 'ACTIVITY 9F · STRUCTURED ENGLISH → PSEUDOCODE',
    title: 'Structured English must be unambiguous enough to reveal variables, input/output, selection, iteration and processing',
    lead: 'The Java average example closes the language comparison, then Activity 9F moves to a password algorithm before the chapter explains how structured-English wording maps to pseudocode constructs.',
    richBlocks: [{ kind: 'table', table: { caption: 'Clues in structured English', headers: ['Wording', 'What to identify'], rows: [
      ['Enter / Read / Print / Write', 'Input or output'],
      ['If / Then / Choose', 'Selection'],
      ['Loop / Repeat', 'Iteration'],
      ['Set / Calculate', 'Processing'],
    ] } }],
    activity: { title: 'Activity 9F', prompt: 'Design pseudocode that sets a password by entering the same word twice, then allows three attempts to enter the correct password. Complete an identifier table as part of the design.' },
    visual: 'types', accent: 'rose', ...source(229, ['Java average program', 'Activity 9F', '9.2.3 structured English description', 'Identifier/input/output/selection/iteration/process clues']),
  },
  {
    id: 'h9-923-marathon-identifiers', section: '9.2 Algorithms', subtopicCode: '9.2.3', eyebrow: 'MARATHON EXAMPLE · TABLE 9.3',
    title: 'The marathon example turns three structured-English steps into an identifier table and pseudocode',
    lead: 'The first structured-English step requires hours, minutes and seconds; the source makes those variables explicit before writing the corresponding OUTPUT and INPUT statements.',
    richBlocks: [
      { kind: 'steps', title: 'Structured-English algorithm', items: ['Enter time taken in hours, minutes and seconds.', 'Calculate and store marathon time in seconds.', 'Output marathon time in seconds.'] },
      { kind: 'table', table: { caption: 'Table 9.3 identifiers', headers: ['Identifier', 'Meaning'], rows: [['MarathonHours', 'Hours part'], ['MarathonMinutes', 'Minutes part'], ['MarathonSeconds', 'Seconds part'], ['TotalMarathonTimeSeconds', 'Total time in seconds']] } },
    ],
    example: { title: 'Input pseudocode', lines: ['OUTPUT "Enter hours"', 'INPUT MarathonHours', 'OUTPUT "Enter minutes"', 'INPUT MarathonMinutes', 'OUTPUT "Enter seconds"', 'INPUT MarathonSeconds'] },
    visual: 'types', accent: 'indigo', ...source(230, ['Table 9.3', 'Marathon structured English', 'MarathonHours', 'MarathonMinutes', 'MarathonSeconds']),
  },
  {
    id: 'h9-923-marathon-process', section: '9.2 Algorithms', subtopicCode: '9.2.3', eyebrow: 'PROCESS + OUTPUT · ACTIVITY 9G',
    title: 'Preserving the structured-English order makes the translation to pseudocode systematic',
    lead: 'The second marathon step becomes one assignment expression and the third becomes output. Activity 9G then extends the design with a personal-best comparison.',
    example: { title: 'Marathon calculation', lines: ['TotalMarathonTimeSeconds ← (MarathonHours * 3600 + MarathonMinutes) * 60 + MarathonSeconds', 'OUTPUT "Time for marathon in seconds ", TotalMarathonTimeSeconds'] },
    activity: { title: 'Activity 9G', prompt: 'Extend the identifier table and pseudocode to input a personal-best time, compare it with the marathon time, replace the personal best when the new time is shorter and output the result.' },
    visual: 'recap', accent: 'emerald', ...source(231, ['Marathon process and output', 'Activity 9G', '9.2.4 Writing pseudocode from a flowchart']),
  },
  {
    id: 'h9-924-flowchart-symbols', section: '9.2 Algorithms', subtopicCode: '9.2.4', eyebrow: 'TABLE 9.4 · FIGURE 9.4',
    title: 'Flowchart symbols map directly to categories of pseudocode statements',
    lead: 'Table 9.4 links input/output, decision, loop and processing symbols to pseudocode. Figure 9.4 then applies those symbols to an exam-grade algorithm.',
    richBlocks: [{ kind: 'table', table: { caption: 'Flowchart-to-pseudocode mapping', headers: ['Flowchart meaning', 'Pseudocode category'], rows: [
      ['Input/output symbol', 'INPUT or OUTPUT'],
      ['Decision symbol', 'IF or CASE; also loop conditions'],
      ['Loop structure', 'FOR, REPEAT or WHILE with a returning flow line'],
      ['Process symbol', 'Assignment or a predefined process such as INT'],
    ] } }],
    richBlocks: undefined,
    bullets: [
      'The exam-grade flowchart inputs Mark.',
      'Nested decisions classify the mark as Fail, Pass, Merit or Distinction.',
      'The final step outputs the selected Grade.',
      'The flowchart can be used to identify the variables before completing the identifier table.',
    ],
    visual: 'recap', accent: 'cyan', ...source(232, ['Table 9.4', 'Figure 9.4 exam grade flowchart', 'Mark', 'Grade']),
  },
  {
    id: 'h9-924-nested-selection-refinement', section: '9.2 Algorithms', subtopicCode: '9.2.4', eyebrow: 'TABLE 9.5 · NESTED IF · 9.2.5 STEPWISE REFINEMENT',
    title: 'Indentation exposes nested selection; refinement then expands broad steps into implementable detail',
    lead: 'The grade algorithm becomes nested IF statements in pseudocode. The chapter then reuses the marathon problem to introduce stepwise refinement.',
    bullets: [
      'Mark and Grade form the identifier table for the grade algorithm.',
      'Each later IF belongs inside the preceding ELSE branch until the complete selection ends.',
      'Flowchart structure and pseudocode indentation make the nesting visible in different ways.',
      'Stepwise refinement starts by replacing a broad task such as “enter time” with smaller steps for hours, minutes and seconds.',
    ],
    example: { title: 'First refinement', lines: ['1 Enter time taken to run marathon in hours, minutes and seconds', '1.1 Enter the hours', '1.2 Enter the minutes', '1.3 Enter the seconds'] },
    visual: 'types', accent: 'indigo', ...source(233, ['Table 9.5', 'Nested selection', '9.2.5 Stepwise refinement', 'Marathon refinement']),
  },
  {
    id: 'h9-925-repeat-grade-activity', section: '9.2 Algorithms', subtopicCode: '9.2.5', eyebrow: 'ACTIVITY 9H · REPEATED GRADE INPUT',
    title: 'Refinement and control flow can extend a one-value solution into repeated processing',
    lead: 'Activity 9H extends the grade flowchart so another mark can be entered after each result until the user replies that no further mark is required.',
    richBlocks: [{ kind: 'steps', title: 'Extended grade route', items: ['Input and classify one mark.', 'Output the grade.', 'Ask whether another exam mark should be entered.', 'Input Reply.', 'If Reply is Y, return to the mark input; otherwise end.'] }],
    activity: { title: 'Activity 9H', prompt: 'Extend the identifier table and write pseudocode for the repeated-grade flowchart, then test the design by implementing it with the same identifier names.' },
    visual: 'recap', accent: 'amber', ...source(234, ['Activity 9H', 'Repeated grade flowchart', 'Reply']),
  },
  {
    id: 'h9-925-detailed-refinement', section: '9.2 Algorithms', subtopicCode: '9.2.5', eyebrow: 'REFINE UNTIL EACH STEP CAN BE CODED · ACTIVITY 9I',
    title: 'A robust refinement includes validation, rejection and re-input — not just smaller labels',
    lead: 'The source refines each marathon time component into input, range checking, rejection/re-entry and acceptance before showing the seconds routine in pseudocode.',
    richBlocks: [{ kind: 'steps', title: 'Seconds refinement', items: ['Input a value for seconds.', 'Check that it is in the range 0 to 59.', 'Reject and re-input when it is out of range or not a whole number.', 'Accept and store the validated value.'] }],
    example: { title: 'Validated seconds routine', lines: ['REPEAT', '  OUTPUT "Enter seconds"', '  INPUT Value', 'UNTIL (Value >= 0) AND (Value <= 59) AND (Value = INT(Value))', 'MarathonSeconds ← Value'] },
    activity: { title: 'Activity 9I', prompt: 'Use stepwise refinement on the structured-English task that chooses square, triangle or circle, inputs required lengths, calculates the area and outputs the result. Then rewrite the refined design in pseudocode.' },
    visual: 'recap', accent: 'rose', ...source(235, ['Detailed marathon refinement', 'Validated seconds pseudocode', 'Activity 9I']),
  },
  {
    id: 'h9-review-concepts', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS · CONCEPTS + EXPRESSIONS',
    title: 'The first review checks algorithm representations, computational thinking, refinement and expression tracing',
    lead: 'The coursebook review asks for precise explanations of structured English, flowcharts, pseudocode, abstraction, decomposition and pattern recognition before moving to expression evaluation.',
    bullets: [
      'Explain structured English, flowchart and pseudocode.',
      'Explain abstraction, decomposition and pattern recognition.',
      'Describe stepwise refinement using an example.',
      'Trace assignment and Boolean expressions and state the resulting stored values.',
      'The printed expression-tracing question is adapted from an older Cambridge 9608 paper, so it remains coursebook review rather than a current live 9618 checkpoint.',
    ],
    activity: { title: 'Retrieval review', prompt: 'For each of the six key terms, give a definition and a short example without looking back at the lesson.' },
    visual: 'recap', accent: 'cyan', ...source(236, ['End-of-chapter questions 1–4', 'Cambridge 9608 Paper 21 Q1 November 2015']),
  },
  {
    id: 'h9-review-menu', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTION · MENU ALGORITHM',
    title: 'The final review asks you to identify assignment, selection and iteration inside a temperature-conversion algorithm',
    lead: 'The menu algorithm repeatedly offers two conversions plus Exit, uses nested IF statements for the chosen conversion and reports an error for invalid non-exit choices.',
    richBlocks: [{ kind: 'steps', title: 'What the review asks you to do', items: [
      'Give the line number of an assignment statement.',
      'Give the line number of a selection.',
      'Give the line number of an iteration.',
      'Complete an identifier table for the algorithm.',
      'Extend the algorithm so only four attempts are allowed for a correct choice.',
    ] }],
    activity: { title: 'Trace and improve', prompt: 'Trace the menu for one Celsius-to-Fahrenheit conversion, one invalid choice and Exit, then design the four-attempt limit requested by the source.' },
    visual: 'recap', accent: 'indigo', ...source(237, ['End-of-chapter question 5', 'Temperature-conversion menu pseudocode']),
  },
];

export const CHAPTER_9_FINAL: HodderLessonChapter = {
  number: 9,
  level: 'AS Level',
  title: 'Algorithm design and problem solving',
  subtitle: 'Computational thinking · algorithm representation · Cambridge pseudocode conventions · stepwise refinement',
  subtopics: ['9.1 Computational thinking skills', '9.2 Algorithms'],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 Chapter 9 in the connected full coursebook, printed pp.217–237. Every printed chapter page is represented in slide provenance and the source sequence, examples, activities and pseudocode conventions are preserved as teaching paraphrase.',
  coverage: '21/21 printed chapter pages represented (pp.217–237): abstraction and decomposition; road-map and module examples; structured English, flowcharts and pseudocode; identifier tables, input/output, assignment, selection, relational/logical operators and iteration; Python/VB.NET/Java comparison examples; validation with INT(x); password and marathon activities; flowchart-to-pseudocode conversion; nested grade selection; stepwise refinement, validation and chapter-review algorithms.',
  slides: CHAPTER_9_DEEP_SLIDES,
};
