export type LessonVisual =
  | 'binary' | 'bases' | 'arithmetic' | 'characters' | 'pixels' | 'vectors' | 'sound' | 'compression'
  | 'types' | 'files' | 'hashing' | 'floating' | 'precision' | 'recap';

export type LessonSlide = {
  id: string;
  section: string;
  subtopicCode?: string;
  eyebrow: string;
  title: string;
  lead: string;
  bullets?: string[];
  keyTerms?: Array<{ term: string; definition: string }>;
  formula?: string;
  example?: { title: string; lines: string[]; answer?: string };
  teacherPrompt?: string;
  activity?: { title: string; prompt: string; reveal?: string };
  visual?: LessonVisual;
  examPractice?: boolean;
  accent?: 'indigo' | 'cyan' | 'emerald' | 'amber' | 'rose';
};

export type LessonChapter = {
  number: 1 | 13;
  level: 'AS Level' | 'A Level';
  title: string;
  subtitle: string;
  subtopics: string[];
  sourceNote: string;
  coverage: string;
  slides: LessonSlide[];
};

const ch1: LessonSlide[] = [
  {id:'c1-00',section:'Chapter overview',eyebrow:'CHAPTER 01 · AS LEVEL',title:'Information representation and multimedia',lead:'A complete classroom route through the Hodder Chapter 1 concepts: number representation, images, sound, video and compression — aligned to Cambridge 9618.',bullets:['1.1 Data representation','1.2 Multimedia: bitmap, vector, sound and video','1.3 File compression'],teacherPrompt:'Start with one question: “A number, a photo and a song are all stored as bits. What tells the computer how to interpret those bits?”',visual:'binary',accent:'indigo'},
  {id:'c1-01',section:'Chapter overview',eyebrow:'DIAGNOSTIC · BEFORE YOU START',title:'What should learners already know?',lead:'Use this as a five-minute retrieval check before teaching the chapter.',bullets:['Binary column weights and binary-to-denary conversion.','Basic binary addition.','Hexadecimal column weights and A–F values.','Simple hexadecimal addition and conversion to denary.'],activity:{title:'Board starter',prompt:'Ask learners to convert 00110101₂ to denary, then write the same value in hexadecimal.',reveal:'00110101₂ = 53₁₀ = 35₁₆'},visual:'bases',accent:'cyan'},

  {id:'c1-11-01',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · POSITIONAL NUMBER SYSTEMS',title:'Place value depends on the base',lead:'Denary, binary and hexadecimal are positional systems. A digit contributes its digit value multiplied by a power of the base.',bullets:['Denary uses powers of 10.','Binary uses powers of 2 and only the digits 0 and 1.','Hexadecimal uses powers of 16 and symbols 0–9, A–F.','A bit is one binary digit; groups of bits form larger storage units.'],formula:'value = Σ(digit × base^position)',visual:'bases',accent:'indigo'},
  {id:'c1-11-02',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · WHY BINARY?',title:'Why computers use two states',lead:'Electronic switching devices can be designed reliably around two stable states, so the binary model maps naturally to hardware.',bullets:['ON / high / true can be represented by 1.','OFF / low / false can be represented by 0.','Complex data is built by interpreting long patterns of these two states.','The same bit pattern can mean different things depending on its data type or encoding.'],teacherPrompt:'Ask for examples of hardware states that can be treated as two-state decisions.',visual:'binary',accent:'cyan'},
  {id:'c1-11-03',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · BINARY ↔ DENARY',title:'Convert using column weights',lead:'Binary-to-denary means summing the powers of two represented by 1 bits. Denary-to-binary means selecting powers of two whose sum equals the value.',example:{title:'Convert 11010110₂',lines:['128 + 64 + 16 + 4 + 2','= 214'],answer:'11010110₂ = 214₁₀'},activity:{title:'Try it',prompt:'Convert 173₁₀ to 8-bit binary.',reveal:'10101101₂'},visual:'binary',accent:'indigo'},
  {id:'c1-11-04',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · NEGATIVE INTEGERS',title:'Three ways to represent a sign',lead:'The coursebook distinguishes sign-and-magnitude, one’s complement and two’s complement. They do not have the same range or arithmetic behaviour.',keyTerms:[{term:'Sign and magnitude',definition:'Most significant bit stores the sign; remaining bits store the magnitude. It has +0 and −0.'},{term:'One’s complement',definition:'Invert every bit to form the negative representation; it also has two representations of zero.'},{term:'Two’s complement',definition:'Invert every bit and add 1. It has one zero and supports efficient binary arithmetic.'}],visual:'arithmetic',accent:'rose'},
  {id:'c1-11-05',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · TWO’S COMPLEMENT',title:'Read and create negative binary values',lead:'For an n-bit two’s-complement number, the most significant bit has a negative weight and the remaining bits retain positive power-of-two weights.',formula:'8-bit weights: −128, 64, 32, 16, 8, 4, 2, 1',example:{title:'Interpret 11101011₂',lines:['−128 + 64 + 32 + 8 + 2 + 1','= −21'],answer:'11101011₂ = −21₁₀'},activity:{title:'Create a negative value',prompt:'Write −53 as an 8-bit two’s-complement number.',reveal:'53 = 00110101 → invert 11001010 → +1 = 11001011'},visual:'arithmetic',accent:'rose'},
  {id:'c1-11-06',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · RANGE',title:'Bit width fixes the representable range',lead:'A fixed number of bits limits the integers that can be represented.',bullets:['Unsigned n-bit range: 0 to 2ⁿ−1.','Two’s-complement n-bit range: −2ⁿ⁻¹ to 2ⁿ⁻¹−1.','For 8-bit two’s complement: −128 to +127.','Adding more bits increases the available range.'],formula:'signed range = −2^(n−1) … 2^(n−1)−1',visual:'binary',accent:'amber'},
  {id:'c1-11-07',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · BINARY ADDITION',title:'Addition uses carry exactly as place value requires',lead:'The rules are small, but multi-bit additions must track carries carefully.',bullets:['0 + 0 = 0','0 + 1 = 1','1 + 1 = 10','1 + 1 + carry 1 = 11'],example:{title:'37 + 58',lines:['00100101','+00111010','=01011111'],answer:'01011111₂ = 95₁₀'},visual:'arithmetic',accent:'cyan'},
  {id:'c1-11-08',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · SUBTRACTION',title:'Subtraction can borrow — or use two’s complement',lead:'Binary subtraction follows positional borrowing. With fixed-width signed integers, subtraction can also be implemented as addition of a two’s-complement negative value.',example:{title:'95 − 68',lines:['95 = 01011111','68 = 01000100','01011111 − 01000100','=00011011'],answer:'27₁₀'},teacherPrompt:'Ask why hardware designers prefer reusing adder circuitry instead of building completely separate arithmetic paths.',visual:'arithmetic',accent:'indigo'},
  {id:'c1-11-09',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · OVERFLOW',title:'Overflow means the fixed word is too small',lead:'An arithmetic result can be mathematically correct but impossible to store in the allocated number of bits.',bullets:['Unsigned overflow: a carry leaves the available word.','Signed overflow: the result falls outside the signed range.','Overflow is a representation limit, not a rounding issue.','The solution is a wider representation or controlled error handling.'],example:{title:'8-bit unsigned overflow',lines:['11110000','+00110000','=1 00100000'],answer:'The result needs 9 bits.'},visual:'arithmetic',accent:'rose'},
  {id:'c1-11-10',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · STORAGE MAGNITUDES',title:'Decimal and binary prefixes are different systems',lead:'Storage products often use SI decimal prefixes, while memory capacities are naturally related to powers of two. Cambridge expects the distinction.',keyTerms:[{term:'kB / MB / GB / TB',definition:'Decimal prefixes based on powers of 1000.'},{term:'KiB / MiB / GiB / TiB',definition:'IEC binary prefixes based on powers of 1024.'}],formula:'1 kB = 1000 B   ·   1 KiB = 1024 B',bullets:['1 MiB = 2²⁰ bytes.','1 GiB = 2³⁰ bytes.','Always preserve the stated unit in calculations.','RAM is commonly described in binary-aligned capacities; storage marketing often uses decimal capacities.'],visual:'binary',accent:'amber'},
  {id:'c1-11-11',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · HEXADECIMAL',title:'Hexadecimal is a compact view of binary',lead:'Because 16 = 2⁴, each hexadecimal digit maps exactly to one group of four binary bits.',formula:'1 hex digit ↔ 4 bits (one nibble)',bullets:['A=10, B=11, C=12, D=13, E=14, F=15.','Binary → hex: group bits in fours from the right.','Hex → binary: replace each digit with its four-bit pattern.','Hex → denary: apply powers of 16.'],example:{title:'Binary to hex',lines:['1011 1110 0001','1011 = B','1110 = E','0001 = 1'],answer:'BE1₁₆'},visual:'bases',accent:'indigo'},
  {id:'c1-11-12',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · HEX USES',title:'Why people use hexadecimal around machines',lead:'Hex is shorter and less error-prone for humans while preserving a direct mapping to binary.',bullets:['Memory addresses and memory dumps.','Machine-code / assembly debugging.','MAC addresses and other long binary identifiers.','Web colour values such as RGB hex notation.','Any context where long binary strings must be inspected or entered accurately.'],activity:{title:'Board connection',prompt:'Explain why FF₁₆ represents the same number as 11111111₂ without converting through denary.',reveal:'Each F is 1111₂, so FF maps directly to 1111 1111.'},visual:'bases',accent:'cyan'},
  {id:'c1-11-13',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · BCD',title:'BCD encodes each decimal digit separately',lead:'Binary-Coded Decimal does not convert the whole number into binary. Each denary digit is represented by its own four-bit code.',example:{title:'Encode 3165',lines:['3 → 0011','1 → 0001','6 → 0110','5 → 0101'],answer:'0011 0001 0110 0101'},bullets:['Only 0000 to 1001 are valid decimal digit codes.','Two BCD digits can be packed into one byte.','BCD is easy to convert to and from decimal displays.'],visual:'bases',accent:'amber'},
  {id:'c1-11-14',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · BCD IN PRACTICE',title:'Exact decimal digits matter in displays and money',lead:'BCD is useful where decimal digits themselves are important and binary floating-point approximation would be undesirable.',bullets:['Calculator and digital-clock displays map naturally between decimal digits and 4-bit BCD codes.','Fixed-point monetary data can preserve exact decimal digits.','BCD arithmetic may require decimal correction when a 4-bit result is greater than 9.','A common correction is to add 0110 after an invalid BCD digit result.'],example:{title:'Why correction is needed',lines:['7 + 4 = 11₁₀','Binary result 1011 is not a valid single BCD digit','Add 0110 to produce a carry and a valid lower digit'],answer:'BCD arithmetic is digit-oriented, not ordinary unrestricted binary arithmetic.'},visual:'arithmetic',accent:'rose'},
  {id:'c1-11-15',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · CHARACTER SETS',title:'Characters need agreed numeric codes',lead:'A character set assigns a code to each supported character. The code is stored as binary; the interpretation comes from the chosen encoding.',keyTerms:[{term:'ASCII',definition:'Original standard uses 7-bit codes, including printable characters and control codes.'},{term:'Extended ASCII',definition:'8-bit extensions add codes 128–255, but extensions are not one universal language solution.'},{term:'Unicode',definition:'A much larger universal character repertoire designed to cover writing systems and symbols worldwide.'}],visual:'characters',accent:'emerald'},
  {id:'c1-11-16',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · ASCII PATTERNS',title:'ASCII is arranged to make processing practical',lead:'Digits and alphabetic characters occupy ordered ranges, which makes comparison and case conversion efficient.',bullets:['Standard ASCII codes 0–31 are control codes; printable characters follow.','Uppercase and lowercase letters occupy predictable ranges.','For many Latin letters, case conversion follows a consistent bit/code difference.','Numeric digits 0–9 are consecutive, allowing simple validation and ordering.'],activity:{title:'Think like a program',prompt:'Why is it useful that the codes for A–Z and 0–9 are consecutive?',reveal:'Range checks, ordering and conversion can be implemented with simple arithmetic/comparisons.'},visual:'characters',accent:'cyan'},
  {id:'c1-11-17',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'1.1 · UNICODE',title:'A global character repertoire needs more than ASCII',lead:'Unicode provides code points for scripts and symbols far beyond the original ASCII range while retaining compatibility for the first ASCII characters.',bullets:['The first 128 Unicode code points correspond to ASCII.','Unicode separates the character identity (code point) from the byte encoding used to store/transmit it.','UTF encodings represent Unicode code points using one or more bytes.','Incorrect encoding assumptions can turn valid stored bytes into incorrect displayed characters.'],teacherPrompt:'Show a multilingual string and ask why an ASCII-only system cannot represent it faithfully.',visual:'characters',accent:'emerald'},
  {id:'c1-exam-11',section:'1.1 Data Representation',subtopicCode:'1.1',eyebrow:'PAST PAPER · 1.1',title:'Cambridge checkpoint: Data Representation',lead:'Approved 2021–2025 questions are loaded live for this subtopic. Use them after the full representation sequence.',examPractice:true,accent:'indigo'},

  {id:'c1-12-01',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · BITMAP MODEL',title:'A bitmap stores a two-dimensional matrix of pixels',lead:'Every pixel has an encoded colour. The file also needs information that tells software how to interpret the pixel data.',bullets:['Pixel = picture element.','Image resolution = width × height in pixels.','Colour depth = number of bits allocated to each pixel.','With n bits per pixel, up to 2ⁿ distinct values can be encoded.'],visual:'pixels',accent:'cyan'},
  {id:'c1-12-02',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · RGB & TRUE COLOUR',title:'Colour can be built from red, green and blue components',lead:'A common true-colour representation uses three 8-bit components — one each for red, green and blue.',formula:'24-bit colour = 8 bits red + 8 bits green + 8 bits blue',bullets:['Each 8-bit component can take 256 intensity values.','24-bit RGB can encode 256³ = 16,777,216 combinations.','More colour depth generally improves tonal variation but increases raw file size.'],example:{title:'One RGB pixel',lines:['R = 255','G = 128','B = 0'],answer:'The pixel is encoded by three component values; in 24-bit RGB it occupies 3 bytes.'},visual:'pixels',accent:'rose'},
  {id:'c1-12-03',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · FILE HEADER',title:'Pixel bytes alone are not enough',lead:'Software needs metadata to know how the following bytes should be interpreted.',bullets:['Image dimensions.','Colour depth / pixel format.','File type or format identifier.','Compression or other format parameters.','The data payload plus metadata together make the complete file.'],teacherPrompt:'Ask: “If I give you 6 MB of bytes with no width, height or colour format, can you reconstruct the intended image?”',visual:'pixels',accent:'amber'},
  {id:'c1-12-04',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · RAW BITMAP SIZE',title:'Estimate bitmap file size from pixels and colour depth',lead:'Ignoring headers and compression, multiply total pixels by the bits stored per pixel.',formula:'bits = width × height × colour depth',example:{title:'1920 × 1080 at 24 bit',lines:['1920 × 1080 = 2,073,600 pixels','× 24 = 49,766,400 bits','÷ 8 = 6,220,800 bytes'],answer:'≈ 6.22 MB using decimal MB before header/compression.'},visual:'pixels',accent:'indigo'},
  {id:'c1-12-05',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · RESOLUTION & QUALITY',title:'More pixels can preserve more spatial detail',lead:'Changing image resolution changes both potential detail and file size.',bullets:['Higher resolution → more pixels → larger raw file.','If a low-resolution image is enlarged, individual pixels become more visible.','Cropping removes pixels and therefore reduces dimensions/file size.','Rotating usually changes orientation, not the underlying amount of pixel information.'],visual:'pixels',accent:'cyan'},
  {id:'c1-12-06',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · SCREEN RESOLUTION & PIXEL DENSITY',title:'Image pixels and display pixels are related but not identical ideas',lead:'An image has its own pixel dimensions; a screen has a display resolution and physical pixel density.',keyTerms:[{term:'Screen resolution',definition:'The number of addressable display pixels horizontally and vertically.'},{term:'Pixel density',definition:'How many display pixels occupy a physical unit such as an inch.'}],bullets:['A high-resolution image on a lower-resolution display may need scaling or scrolling.','A low-resolution image enlarged across many screen pixels can look pixelated.','Physical size and pixel count together determine pixel density.'],visual:'pixels',accent:'emerald'},
  {id:'c1-12-07',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · COLOUR DEPTH TRADE-OFF',title:'More colour values cost more bits per pixel',lead:'Colour depth changes the number of distinct colour codes that can be stored.',formula:'number of colours = 2^(colour depth)',example:{title:'Compare two images',lines:['4-bit colour → 16 values','8-bit colour → 256 values','24-bit colour → 16,777,216 values'],answer:'Increasing colour depth improves available colour precision but increases raw size.'},visual:'pixels',accent:'amber'},
  {id:'c1-12-08',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · VECTOR MODEL',title:'Vector graphics store drawing instructions',lead:'Instead of storing a colour for every pixel, a vector file describes geometric objects and their properties.',bullets:['Coordinates for start/end/control points.','Object type: line, rectangle, circle, curve, text and so on.','Stroke colour, fill colour and line thickness.','Transformations such as scale, rotation and translation.','The renderer calculates the display pixels when the graphic is shown.'],visual:'vectors',accent:'emerald'},
  {id:'c1-12-09',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · BITMAP VS VECTOR',title:'Choose the representation that matches the task',lead:'Neither format is “better” in every situation; the content and editing needs determine the choice.',keyTerms:[{term:'Bitmap advantage',definition:'Excellent for photographs and continuous complex detail.'},{term:'Bitmap limitation',definition:'Scaling up can reveal pixels; large high-detail images can require many bytes.'},{term:'Vector advantage',definition:'Scales cleanly; individual geometric objects are easy to edit.'},{term:'Vector limitation',definition:'Less natural for detailed photographic scenes.'}],teacherPrompt:'Compare a school logo with a class photograph and require a justified choice for each.',visual:'vectors',accent:'indigo'},
  {id:'c1-12-10',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · SOUND',title:'Digital sound begins as an analogue waveform',lead:'A microphone produces an analogue electrical signal. An analogue-to-digital converter samples the signal and stores numerical approximations of its amplitude.',bullets:['ADC: analogue → digital.','Samples are taken at regular time intervals.','Each sample amplitude is quantised to one of the available binary values.','Playback uses a DAC to reconstruct an analogue output signal for speakers/headphones.'],visual:'sound',accent:'rose'},
  {id:'c1-12-11',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · SAMPLING RATE',title:'Sampling rate controls how often the waveform is measured',lead:'A higher rate records more points per second and can follow faster waveform changes.',bullets:['Measured in samples per second / hertz.','Higher rate can improve fidelity to the original waveform.','Higher rate produces more sample values and therefore a larger raw file.','A rate that is too low can lose important changes in the signal.'],visual:'sound',accent:'cyan'},
  {id:'c1-12-12',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · SAMPLING RESOLUTION',title:'Sampling resolution controls amplitude precision',lead:'The number of bits per sample determines how many discrete amplitude levels are available.',formula:'levels = 2^(bits per sample)',bullets:['More bits → more quantisation levels.','More levels reduce the size of quantisation steps.','More bits per sample increase raw data size.','Sampling rate and sampling resolution affect different dimensions of accuracy.'],visual:'sound',accent:'amber'},
  {id:'c1-12-13',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · SOUND FILE SIZE',title:'Raw sound size depends on four main factors',lead:'For uncompressed PCM-style data, file size scales with samples per second, bits per sample, duration and number of channels.',formula:'bits = sample rate × resolution × seconds × channels',example:{title:'Stereo example',lines:['44,100 samples/s × 16 bits','× 60 s × 2 channels','= 84,672,000 bits'],answer:'≈ 10.584 MB before headers/compression.'},visual:'sound',accent:'indigo'},
  {id:'c1-12-14',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'1.2 · VIDEO',title:'Video combines a sequence of images with time',lead:'A digital video is displayed as frames in rapid succession, usually with a synchronized sound track.',bullets:['Frame rate = number of frames displayed per second.','Higher frame rate can make motion appear smoother but increases raw data.','Each frame has image resolution and colour depth.','Sound adds its own sampled data.','Video files therefore become very large and are strong candidates for compression.'],formula:'video data grows with resolution × colour depth × frame rate × duration',visual:'pixels',accent:'rose'},
  {id:'c1-exam-12',section:'1.2 Multimedia',subtopicCode:'1.2',eyebrow:'PAST PAPER · 1.2',title:'Cambridge checkpoint: Multimedia',lead:'Use approved source-backed questions on bitmap encoding, file size, vector choice and sampled sound.',examPractice:true,accent:'cyan'},

  {id:'c1-13-01',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · WHY COMPRESS?',title:'Compression reduces storage and transmission cost',lead:'The goal is to represent useful information using fewer bits.',bullets:['Less storage space.','Faster upload/download.','Lower bandwidth requirements for streaming.','More efficient backups and transfers.','Potential trade-off: some methods lose information permanently.'],visual:'compression',accent:'indigo'},
  {id:'c1-13-02',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · LOSSLESS',title:'Lossless compression preserves the original exactly',lead:'After decompression, every original bit of information can be reconstructed.',bullets:['Appropriate for text, source code, program files and other data where any change could alter meaning.','Often exploits repetition, predictable structure or statistical redundancy.','Usually achieves a smaller compression ratio than aggressive lossy methods.'],teacherPrompt:'Ask why losing “almost invisible” information is acceptable for a photo but not for executable program code.',visual:'compression',accent:'emerald'},
  {id:'c1-13-03',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · LOSSY',title:'Lossy compression removes information permanently',lead:'Lossy methods target details that are less important to the intended human experience, allowing a much larger size reduction.',bullets:['Common in photographic images, audio and video.','The original cannot be reconstructed exactly.','More aggressive compression usually increases visible/audible artefacts.','Exam answers should justify why the quality loss is acceptable in the stated scenario.'],visual:'compression',accent:'rose'},
  {id:'c1-13-04',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · TEXT',title:'Text can be compressed without changing characters',lead:'Text is semantic data: changing characters changes meaning, so compression is normally lossless.',bullets:['Repeated strings can be represented by references/dictionary entries.','Common symbols can be assigned shorter codes than rare symbols.','Repeated runs can be represented by run length where appropriate.','The decompressor must be able to reproduce the exact original sequence.'],visual:'characters',accent:'cyan'},
  {id:'c1-13-05',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · RLE MODEL',title:'Run-length encoding replaces repeated runs with count + value',lead:'RLE is a reversible technique that works best where adjacent data repeats for long runs.',formula:'AAAAABBBBCC → 5A 4B 2C',bullets:['First value: run length.','Second value: repeated symbol/pixel value.','Long runs compress well.','Rapidly changing data can gain little — or even become larger if every run needs a count.'],visual:'compression',accent:'emerald'},
  {id:'c1-13-06',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · RLE FLAGS',title:'Mixed data may need a flag to distinguish runs from literal bytes',lead:'The coursebook demonstrates a flag mechanism: a reserved value signals that the following values describe a repeated run; otherwise bytes can be treated literally.',bullets:['Useful when some parts contain long runs and others do not.','The flag itself adds overhead.','A compression scheme must define how a literal occurrence of the flag value is escaped.','Compression effectiveness depends on the actual data pattern.'],activity:{title:'Evaluate',prompt:'Would RLE help the string ABCDEFGHIJ? Explain.',reveal:'Probably not: almost every character forms a run of length 1, so count metadata adds overhead.'},visual:'compression',accent:'amber'},
  {id:'c1-13-07',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · RLE IMAGES',title:'RLE can compress flat-colour bitmap regions',lead:'Rows of repeated pixel colours can be replaced by run lengths and colour values.',bullets:['Black/white diagrams with long solid runs compress effectively.','Simple icons and flat graphics often contain repeated neighbouring values.','Detailed photographs have frequent colour changes, so plain RLE is usually less effective.','Colour runs may store a count plus multiple RGB component values.'],visual:'pixels',accent:'cyan'},
  {id:'c1-13-08',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · BITMAP / PHOTO COMPRESSION',title:'Image compression exploits spatial and perceptual redundancy',lead:'Images contain neighbouring pixels with related values, and human vision is less sensitive to some detail than others.',bullets:['Lossless image formats preserve every pixel value.','Lossy photo compression can reduce fine detail or colour information that is less noticeable.','The chosen method depends on whether exact reconstruction or smaller file size matters more.'],visual:'pixels',accent:'rose'},
  {id:'c1-13-09',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · VECTOR COMPRESSION',title:'Vector files can compress their structured drawing data',lead:'Vector graphics are typically structured descriptions of objects; repeated tags, attributes, coordinates and text patterns can be encoded compactly.',bullets:['SVG-style vector data can be represented as text-based structured markup.','General-purpose lossless compression can exploit repeated markup and values.','Simplifying a drawing can also reduce the number of stored objects/points.'],visual:'vectors',accent:'emerald'},
  {id:'c1-13-10',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · AUDIO COMPRESSION',title:'Audio compression can be lossless or perceptual',lead:'Sound contains repeated/predictable patterns, and human hearing has perceptual limits that lossy codecs can exploit.',bullets:['Lossless audio keeps the exact sample sequence.','Lossy audio can discard components that are masked or less perceptible.','Reducing bit rate reduces size but may introduce artefacts.','MP3 is a familiar example of lossy audio compression.'],visual:'sound',accent:'indigo'},
  {id:'c1-13-11',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · VIDEO COMPRESSION',title:'Video compression exploits similarity within and between frames',lead:'Consecutive frames often share large areas of content, while each frame also contains spatial redundancy.',bullets:['Intra-frame compression reduces redundancy within a frame.','Inter-frame compression can store changes between related frames rather than a complete new image every time.','Audio is compressed alongside image data.','MP4 is a common container; the encoded streams inside it may use different codecs.'],visual:'compression',accent:'cyan'},
  {id:'c1-13-12',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · REDUCE DATA AT SOURCE',title:'Not every size reduction requires a compression algorithm',lead:'The coursebook also highlights deliberately collecting or keeping less data.',bullets:['Sound/movie: reduce sampling rate.','Sound/movie: reduce sampling resolution.','Video: reduce frame rate.','Image: crop unused areas.','Image: reduce colour depth.','Image: reduce image resolution.'],teacherPrompt:'For each method, require learners to state both the file-size effect and the likely quality consequence.',visual:'compression',accent:'amber'},
  {id:'c1-13-13',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'1.3 · CHOOSE A METHOD',title:'The correct method follows the purpose of the file',lead:'A strong Cambridge response links the representation, user need and acceptable information loss.',keyTerms:[{term:'Text/source code',definition:'Lossless: exact symbols must survive.'},{term:'Archival master',definition:'Prefer lossless or minimally altered source data.'},{term:'Web photograph',definition:'Lossy may be justified when size and speed matter.'},{term:'Streaming audio/video',definition:'Lossy methods often trade imperceptible detail for bandwidth savings.'}],visual:'recap',accent:'indigo'},
  {id:'c1-exam-13',section:'1.3 Compression',subtopicCode:'1.3',eyebrow:'PAST PAPER · 1.3',title:'Cambridge checkpoint: Compression',lead:'Finish with approved corpus questions on lossy/lossless choice, RLE and media-specific size reduction.',examPractice:true,accent:'emerald'},
  {id:'c1-end',section:'Chapter review',eyebrow:'CHAPTER 01 · REVIEW',title:'One chapter, one representation story',lead:'Every file is bits, but the encoding model determines what those bits mean and the compression model determines how efficiently they are stored.',bullets:['Numbers: base, sign, range and arithmetic.','Characters: agreed codes.','Bitmap: pixel grid + metadata.','Vector: object instructions.','Sound: sampled amplitudes.','Video: timed frames + audio.','Compression: exploit redundancy or remove acceptable detail.'],activity:{title:'Exit ticket',prompt:'Give one example where changing the representation changes file size without changing the underlying human meaning.',reveal:'Examples: same integer in binary/hex notation for humans; lower bitmap colour depth; lower sound sampling resolution; compression of an image/audio file.'},visual:'recap',accent:'indigo'},
];

const ch13: LessonSlide[] = [
  {id:'c13-00',section:'Chapter overview',eyebrow:'CHAPTER 13 · A LEVEL',title:'Data representation',lead:'A complete teaching sequence for user-defined data types, file organisation/access, hashing and binary floating-point representation.',bullets:['13.1 User-defined data types','13.2 File organisation and access','13.3 Floating-point numbers, representation and manipulation'],teacherPrompt:'Ask: “At A Level, why is simply knowing INTEGER, STRING and BOOLEAN no longer enough?”',visual:'types',accent:'emerald'},

  {id:'c13-11-01',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · WHY USER-DEFINED TYPES?',title:'A type can model the problem domain',lead:'Programmers create types when built-in primitive types alone do not express the allowed values, structure or relationships clearly enough.',bullets:['Improve readability: meaningful type names communicate intent.','Restrict values to a valid domain.','Group related fields into one conceptual object.','Create reusable abstractions that match the real-world problem.'],visual:'types',accent:'emerald'},
  {id:'c13-11-02',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · COMPOSITE VS NON-COMPOSITE',title:'Does the definition refer to another data type?',lead:'This distinction is structural, not about whether the type is built-in or user-defined.',keyTerms:[{term:'Non-composite',definition:'The type definition does not reference another data type.'},{term:'Composite',definition:'The type definition includes or references one or more other data types.'}],bullets:['An enumerated type is a user-defined non-composite type.','A pointer type is treated as non-composite in this syllabus context.','Records, sets and classes are composite examples because their definitions depend on other types.'],visual:'types',accent:'indigo'},
  {id:'c13-11-03',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · ENUMERATED TYPES',title:'Enumerations define an ordered list of allowed values',lead:'An enumerated type is useful when a variable must take one value from a fixed, meaningful list.',formula:'TYPE TMonth = (January, February, …, December)',bullets:['The values are identifiers, not string literals.','The list has an implied order.','A variable can be declared using the new type.','Successor/predecessor-style operations can use the ordering where the language/pseudocode model allows it.'],activity:{title:'Board task',prompt:'Define TDay for the days of the week, declare Today and Tomorrow, set Today to Wednesday, then derive Tomorrow.',reveal:'TYPE TDay = (Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday); DECLARE Today, Tomorrow : TDay; Today ← Wednesday; Tomorrow ← Today + 1'},visual:'types',accent:'cyan'},
  {id:'c13-11-04',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · POINTER TYPES',title:'A pointer stores an address, not the data value itself',lead:'A pointer type identifies the type of value expected at the referenced memory location.',formula:'TYPE TIntPointer = ^INTEGER',bullets:['The pointer variable stores a memory address.','The pointed-to type matters because the program needs to interpret the bytes at that address correctly.','Pointers allow structures to refer to dynamically located data.'],visual:'types',accent:'rose'},
  {id:'c13-11-05',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · ADDRESS & DEREFERENCE',title:'Pointing and dereferencing are opposite operations',lead:'One operation obtains/assigns an address; dereferencing follows the pointer to read the value stored at that address.',example:{title:'Pseudocode idea',lines:['TYPE TMonthPointer = ^TMonth','DECLARE P : TMonthPointer','P ← ^ThisMonth','MyMonth ← P^'],answer:'P stores the address of ThisMonth; P^ accesses the value at that address.'},teacherPrompt:'Ask learners to verbalise the difference between “P” and “P^”.',visual:'types',accent:'rose'},
  {id:'c13-11-06',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · RECORDS',title:'A record groups related fields that may have different types',lead:'Records model one entity by placing its attributes under a single structured type.',example:{title:'Book record',lines:['TYPE TBookRecord','  DECLARE Title : STRING','  DECLARE NoPages : INTEGER','  DECLARE Fiction : BOOLEAN','ENDTYPE'],answer:'Different field types belong to one logical record.'},bullets:['Composite because fields reference other data types.','Field names make individual values explicit.','Many variables/records can be created from the same type definition.'],visual:'types',accent:'indigo'},
  {id:'c13-11-07',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · SETS',title:'A set is an unordered collection with a base type',lead:'Set values support operations based on mathematical set theory.',formula:'TYPE SLetter = SET OF CHAR',bullets:['The base type determines the allowed element type.','Elements are conceptually unordered and distinct.','Useful operations include membership, union, intersection and difference.','A variable can be defined with an initial set of values.'],example:{title:'Vowels',lines:["TYPE SLetter = SET OF CHAR","DEFINE Vowel ('a','e','i','o','u') : SLetter"],answer:'Vowel is a set value whose elements are characters.'},visual:'types',accent:'emerald'},
  {id:'c13-11-08',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · CLASSES',title:'A class combines state and behaviour',lead:'A class is a composite type that can contain variables and methods. Objects are instances created from the class definition.',bullets:['Attributes/fields store state.','Methods implement behaviour.','Many objects can be created from one class.','The coursebook introduces the idea here and develops classes/objects more fully later in the OOP chapter.'],visual:'types',accent:'cyan'},
  {id:'c13-11-09',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'13.1 · CHOOSING A TYPE',title:'Choose the type that expresses the problem constraints',lead:'Cambridge questions often provide a scenario and require a justified data-type design.',keyTerms:[{term:'Fixed list of named choices',definition:'Enumerated type.'},{term:'Entity with several attributes',definition:'Record or class, depending on whether behaviour is also modelled.'},{term:'Address of data in memory',definition:'Pointer type.'},{term:'Unordered unique collection',definition:'Set.'}],teacherPrompt:'Give three scenarios and require the type plus one-sentence justification.',visual:'recap',accent:'amber'},
  {id:'c13-exam-131',section:'13.1 User-defined data types',subtopicCode:'13.1',eyebrow:'PAST PAPER · 13.1',title:'Cambridge checkpoint: User-defined data types',lead:'Approved questions are loaded live for definitions, pseudocode declarations and scenario choices.',examPractice:true,accent:'emerald'},

  {id:'c13-12-00',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · BEFORE YOU START',title:'Files store records; programs need a way to find them',lead:'The key distinction is between how records are physically organised and how a program accesses a required record.',bullets:['File organisation = physical arrangement of records.','File access = method used to locate/read a record.','The best design depends on how often records are added, updated and searched.'],visual:'files',accent:'indigo'},
  {id:'c13-12-01',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · SERIAL ORGANISATION',title:'Serial files keep records in arrival order',lead:'New records are appended at the end, so physical order reflects the order in which records were added.',bullets:['Simple and fast to append.','No requirement to keep records sorted by key.','Often suitable for temporary transaction/log files.','Finding one specific record may require reading from the start until it is found.'],example:{title:'Typical use',lines:['Meter readings arrive during the month','Each new reading is appended','The batch is processed later'],answer:'Serial organisation suits chronological transaction collection.'},visual:'files',accent:'cyan'},
  {id:'c13-12-02',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · SEQUENTIAL ORGANISATION',title:'Sequential files keep records in a defined key order',lead:'Records are physically sorted according to a key field.',bullets:['Useful when records are processed in key order.','A sequential search can stop once the current key has passed the target.','Adding a new record may require rewriting/reorganising the file to preserve order.','Well suited to batch processing such as ordered statements or reports.'],visual:'files',accent:'emerald'},
  {id:'c13-12-03',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · RANDOM ORGANISATION',title:'Random files use calculated locations',lead:'A record can be stored in any available position; a hashing algorithm uses the key to calculate the target storage location.',bullets:['Physical records are not kept in arrival or key order.','Direct lookup can be very fast.','The hash function must distribute keys across the available address space.','Collisions must be handled when two keys map to the same location.'],visual:'files',accent:'rose'},
  {id:'c13-12-04',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · SEQUENTIAL ACCESS',title:'Sequential access reads records one after another',lead:'The search starts from the physical beginning and moves through records until the target is found or the search can terminate.',bullets:['Natural match for serial files.','Natural match for sequentially organised files.','Can be inefficient for very large files when one random record is needed.','For ordered files, key order can provide an early stopping condition.'],visual:'files',accent:'cyan'},
  {id:'c13-12-05',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · DIRECT ACCESS',title:'Direct access aims to find a record without reading preceding records',lead:'The program calculates or looks up where the record should be stored and accesses that location directly.',bullets:['Strong match for random organisation using hashing.','Can also be supported by indexes in other file structures.','Useful for interactive systems such as account lookup/login where response time matters.'],visual:'files',accent:'indigo'},
  {id:'c13-12-06',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · MATCH THE DESIGN',title:'Organisation and access must match the workload',lead:'A scenario’s read/write pattern should drive the choice.',keyTerms:[{term:'Append-heavy transaction log',definition:'Serial organisation + sequential processing is often appropriate.'},{term:'Regular whole-file processing in key order',definition:'Sequential organisation is appropriate.'},{term:'Frequent individual lookups',definition:'Random organisation + direct access can be appropriate.'}],teacherPrompt:'Give a payroll file, a login credential file and a sensor-event log. Ask for organisation + access and a justification.',visual:'recap',accent:'amber'},
  {id:'c13-12-07',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · HASH FUNCTION',title:'Hashing converts a key into a storage address',lead:'A hashing algorithm performs a repeatable calculation on the record key to identify its home location.',formula:'address = hash(key)',bullets:['Same key must produce the same home address.','Output must fit the file’s available address range.','A good function spreads typical keys to reduce collisions.','Record size and file start address may be part of the final physical address calculation.'],example:{title:'Simple teaching model',lines:['key = 53821','bucket = key MOD 1000','= 821'],answer:'Bucket 821 is the home location in this simplified model.'},visual:'hashing',accent:'emerald'},
  {id:'c13-12-08',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · COLLISIONS',title:'Different keys can hash to the same location',lead:'A collision is unavoidable in many real hash tables because the key space is larger than the number of storage locations.',bullets:['The second record cannot simply overwrite the first.','The file design needs a defined collision-resolution strategy.','Performance deteriorates if too many records cluster around the same hash locations.'],visual:'hashing',accent:'rose'},
  {id:'c13-12-09',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'13.2 · COLLISION HANDLING',title:'Open and closed strategies resolve occupied home locations',lead:'The coursebook explores storing collided records either in an overflow structure or by searching for another free position.',keyTerms:[{term:'Overflow / open hashing idea',definition:'Store collided records in an associated overflow area/chain.'},{term:'Linear probing / closed hashing idea',definition:'Check subsequent locations until a free slot (or the matching key) is found.'}],activity:{title:'Trace it',prompt:'Hash keys 21 and 31 with key MOD 10. What problem occurs, and how could linear probing resolve it?',reveal:'Both hash to 1. Store the first at slot 1; probe slot 2, then onward, for the second.'},visual:'hashing',accent:'amber'},
  {id:'c13-exam-132',section:'13.2 File organisation and access',subtopicCode:'13.2',eyebrow:'PAST PAPER · 13.2',title:'Cambridge checkpoint: Files and hashing',lead:'Approved questions are loaded live for organisation/access choices and hashing concepts.',examPractice:true,accent:'indigo'},

  {id:'c13-13-00',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · BEFORE YOU START',title:'Floating point builds on binary fractions and two’s complement',lead:'Before the representation makes sense, learners must be comfortable with signed binary values, binary fractions and powers of two.',bullets:['Mantissa is a signed binary fraction.','Exponent is a signed binary integer.','Both are commonly represented in two’s-complement form in Cambridge questions.','The stored value is mantissa × 2^exponent.'],visual:'floating',accent:'indigo'},
  {id:'c13-13-01',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · FORMAT',title:'A floating-point value has mantissa and exponent fields',lead:'The mantissa carries significant digits; the exponent moves the binary point and controls the scale.',formula:'value = M × 2^E',keyTerms:[{term:'Mantissa',definition:'Signed fractional part containing the significant binary digits.'},{term:'Exponent',definition:'Signed power of two that scales the mantissa.'}],visual:'floating',accent:'emerald'},
  {id:'c13-13-02',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · BINARY FRACTIONS',title:'Positions after the binary point have negative powers of two',lead:'The first fractional bit has weight 2⁻¹, the next 2⁻², then 2⁻³ and so on.',formula:'0.1011₂ = 1/2 + 0/4 + 1/8 + 1/16 = 0.6875₁₀',activity:{title:'Quick check',prompt:'Convert 0.01101₂ to denary.',reveal:'1/4 + 1/8 + 1/32 = 0.40625'},visual:'binary',accent:'cyan'},
  {id:'c13-13-03',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · DECODE POSITIVE',title:'Decode a positive floating-point number by applying the exponent',lead:'Interpret the exponent, shift the binary point accordingly, then evaluate the signed binary value.',example:{title:'Conceptual example',lines:['M = 0.10110000₂','E = +3','0.1011 × 2³ = 101.1₂','101.1₂ = 5.5₁₀'],answer:'The exponent changes scale; the mantissa supplies the significant digits.'},visual:'floating',accent:'indigo'},
  {id:'c13-13-04',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · NEGATIVE EXPONENT',title:'A negative exponent moves the binary point left',lead:'Negative powers of two represent values closer to zero.',example:{title:'Small positive number',lines:['M = 0.11000000₂','E = −2','0.11 × 2⁻² = 0.0011₂','0.0011₂ = 0.1875₁₀'],answer:'A negative exponent reduces the magnitude.'},visual:'floating',accent:'cyan'},
  {id:'c13-13-05',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · NEGATIVE MANTISSA',title:'A negative mantissa is itself two’s complement',lead:'Do not treat the sign bit as a separate sign-and-magnitude flag. Decode the entire mantissa using two’s-complement fractional weights.',bullets:['For a mantissa with the binary point after the sign bit, the leading weight is −1.','Following positions are +1/2, +1/4, +1/8 …','Alternatively find the two’s complement magnitude carefully, preserving the fixed width.'],example:{title:'Fractional weights',lines:['M = 1.10100000₂','= −1 + 1/2 + 1/8','= −0.375'],answer:'Then apply 2^E to obtain the final value.'},visual:'floating',accent:'rose'},
  {id:'c13-13-06',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · DENARY → FLOATING POINT',title:'Convert the magnitude first, then normalise and encode the exponent',lead:'A reliable method avoids mixing conversion, sign and normalisation in one step.',bullets:['1. Convert the denary magnitude to binary including its fractional part.','2. Shift the binary point to produce a normalised mantissa.','3. Count the shifts to obtain the exponent.','4. Encode mantissa and exponent to the required fixed widths.','5. For a negative value, use the correct two’s-complement mantissa representation.'],visual:'floating',accent:'emerald'},
  {id:'c13-13-07',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · POSITIVE EXAMPLE',title:'Worked conversion: +4.5',lead:'Use the Cambridge normalised form where a positive mantissa starts 0.1…',example:{title:'+4.5 to normalised binary floating point',lines:['4.5₁₀ = 100.1₂','100.1 = 0.1001 × 2³','Mantissa begins 01 → normalised positive','Exponent = +3'],answer:'Pad mantissa/exponent to the bit widths given in the question.'},visual:'floating',accent:'indigo'},
  {id:'c13-13-08',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · SMALL POSITIVE EXAMPLE',title:'Worked conversion: a value below 1',lead:'When the first 1 is to the right of the normalised point position, the exponent is negative.',example:{title:'+0.171875',lines:['0.171875₁₀ = 0.001011₂','Move point right to obtain 0.1011','0.001011 = 0.1011 × 2⁻²','Exponent = −2'],answer:'Encode −2 in two’s-complement exponent bits.'},visual:'floating',accent:'cyan'},
  {id:'c13-13-09',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · NEGATIVE EXAMPLE',title:'Negative values must normalise to a mantissa beginning 1.0…',lead:'For a negative normalised mantissa, the first two bits are different: 10.',bullets:['Construct the fixed-width two’s-complement negative mantissa.','Shift the binary point while preserving the numeric value with the exponent.','Check the first two mantissa bits: 10 means normalised negative.','If the first two bits are 11, more normalisation is possible.'],teacherPrompt:'Contrast 01 for positive with 10 for negative and ask why 00/11 indicate redundant sign extension.',visual:'floating',accent:'rose'},
  {id:'c13-13-10',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · NORMALISATION',title:'Normalisation maximises useful significant bits',lead:'A normalised mantissa removes redundant leading sign bits so the fixed mantissa field carries as much precision as possible.',formula:'positive normalised: 0.1…   ·   negative normalised: 1.0…',bullets:['00 at the start of a positive mantissa means a redundant leading zero remains.','11 at the start of a negative mantissa means redundant sign extension remains.','Shift mantissa and adjust exponent in the opposite direction to preserve the value.','Normalisation gives a consistent canonical form.'],visual:'precision',accent:'emerald'},
  {id:'c13-13-11',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · NORMALISE A VALUE',title:'Mantissa shifts and exponent adjustments must balance',lead:'Moving the binary point changes the mantissa magnitude, so the exponent must compensate.',example:{title:'Normalisation pattern',lines:['Suppose M begins 0.00101 with exponent +5','Shift mantissa left two places → 0.101…','Decrease exponent by 2 → +3'],answer:'The represented numeric value stays unchanged.'},visual:'precision',accent:'cyan'},
  {id:'c13-13-12',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · PRECISION',title:'More mantissa bits improve precision',lead:'The mantissa determines how many significant binary digits can be retained.',bullets:['More mantissa bits → finer representable steps.','Values that fall between representable patterns must be rounded or truncated.','Losing low-significance mantissa bits creates approximation error.','For a fixed total word size, allocating more bits to mantissa leaves fewer for exponent.'],visual:'precision',accent:'indigo'},
  {id:'c13-13-13',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · RANGE',title:'More exponent bits increase range',lead:'The exponent controls how far the binary point can effectively move.',bullets:['More exponent bits allow larger positive exponents and more negative exponents.','This expands the largest and smallest non-zero magnitudes that can be represented.','For a fixed total word size, range competes with precision.'],formula:'more mantissa bits → precision   ·   more exponent bits → range',visual:'precision',accent:'amber'},
  {id:'c13-13-14',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · APPROXIMATION',title:'Many denary fractions do not have a finite binary representation',lead:'Just as 1/3 repeats forever in denary, some simple denary fractions repeat forever in binary.',bullets:['A finite mantissa must stop after a fixed number of bits.','The stored binary value is therefore sometimes only an approximation.','Repeated arithmetic can accumulate small representation errors.','Comparing floating-point results for exact equality can be unsafe in software.'],example:{title:'Classic idea',lines:['0.1₁₀ has no finite binary fractional expansion','A fixed binary mantissa stores a nearby representable value'],answer:'The difference is small but real.'},visual:'precision',accent:'rose'},
  {id:'c13-13-15',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · ROUNDING ERROR',title:'Rounding and truncation create finite representation error',lead:'When the exact binary expansion does not fit, the stored mantissa must be shortened.',bullets:['Truncation discards remaining bits.','Rounding chooses a nearby representable value.','The error is the difference between the exact mathematical value and the stored approximation.','Increasing mantissa width generally reduces this error.'],visual:'precision',accent:'rose'},
  {id:'c13-13-16',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · OVERFLOW',title:'Floating-point overflow occurs beyond the maximum exponent range',lead:'A result may require a magnitude larger than the representation can encode.',bullets:['Often caused by multiplying large values or repeated growth.','The mantissa may be valid, but the required exponent is too large.','Overflow is a range failure, not a precision failure.'],visual:'floating',accent:'rose'},
  {id:'c13-13-17',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · UNDERFLOW',title:'Underflow occurs when a non-zero magnitude is too close to zero',lead:'A result can require an exponent more negative than the representation supports.',bullets:['The value is non-zero mathematically but cannot be represented at the required tiny magnitude.','It may be rounded to zero or the smallest representable non-zero value depending on the system.','Underflow is also a range limitation.'],visual:'floating',accent:'cyan'},
  {id:'c13-13-18',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'13.3 · ZERO',title:'Zero is a special case for normalised floating point',lead:'The normalisation rule expects a significant leading pattern, but zero has no 1 bit to normalise.',bullets:['Zero cannot satisfy the ordinary positive 01 or negative 10 normalised pattern.','Real floating-point systems reserve a special representation for zero.','In exam reasoning, recognise zero as an exception to the normalised non-zero rule.'],visual:'floating',accent:'amber'},
  {id:'c13-exam-133',section:'13.3 Floating-point numbers',subtopicCode:'13.3',eyebrow:'PAST PAPER · 13.3',title:'Cambridge checkpoint: Floating point',lead:'Approved questions are loaded live for decoding, encoding, normalising and explaining precision/range errors.',examPractice:true,accent:'indigo'},
  {id:'c13-end',section:'Chapter review',eyebrow:'CHAPTER 13 · REVIEW',title:'Structure, location and numeric scale',lead:'Chapter 13 links three deeper A Level ideas: designing richer data types, organising persistent records for efficient access, and representing real numbers within finite binary limits.',bullets:['User-defined types model valid values and structured entities.','File organisation/access choices follow the workload.','Hashing supports direct access but introduces collisions.','Floating point trades fixed bits between precision and range.','Normalisation maximises significant bits; finite storage creates approximation, overflow and underflow.'],activity:{title:'Exit ticket',prompt:'Explain one design trade-off from each subtopic in a single sentence.',reveal:'13.1: expressive type vs complexity; 13.2: append/order/direct-lookup needs; 13.3: mantissa precision vs exponent range.'},visual:'recap',accent:'emerald'},
];

export const LESSON_CHAPTERS: LessonChapter[] = [
  {number:1,level:'AS Level',title:'Information representation and multimedia',subtitle:'Numbers, characters, bitmap/vector graphics, sampled sound, video and compression.',subtopics:['1.1 Data Representation','1.2 Multimedia — Graphics, Sound & Video','1.3 File Compression'],sourceNote:'Instructional coverage derived from the supplied Hodder 9618 Coursebook Chapter 1 and aligned to the live Cambridge 9618 syllabus taxonomy. Text is paraphrased for classroom teaching; past-paper questions remain source-backed and live.',coverage:'Full Chapter 1 instructional coverage',slides:ch1},
  {number:13,level:'A Level',title:'Data representation',subtitle:'User-defined types, file organisation/access, hashing and floating-point representation.',subtopics:['13.1 User-defined data types','13.2 File organisation and access','13.3 Floating-point numbers'],sourceNote:'Instructional coverage derived from the supplied Hodder 9618 Coursebook Chapter 13 and aligned to the live Cambridge 9618 syllabus taxonomy. Text is paraphrased for classroom teaching; past-paper questions remain source-backed and live.',coverage:'Full Chapter 13 instructional coverage',slides:ch13},
];

export const lessonChapter=(number:number)=>LESSON_CHAPTERS.find(chapter=>chapter.number===number)??null;
