import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const pageRange = (start: number, end: number) => Array.from({ length: end - start + 1 }, (_, index) => start + index);
const source = (start: number, end: number = start, elements: string[] = []) => ({
  sourcePages: pageRange(start, end),
  sourceLabel: `Hodder Chapter 16 · pp.${start}${end === start ? '' : `–${end}`}`,
  sourceElements: [`Hodder pp.${start}${end === start ? '' : `–${end}`}`, ...elements],
});

export const CHAPTER_16_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h16-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 16 · SYSTEM SOFTWARE AND VIRTUAL MACHINES',
    title: 'The operating system coordinates scarce resources, while translation software turns source programs into executable work',
    lead: 'Chapter 16 connects advanced operating-system management with virtual machines, compiler stages, formal grammar and Reverse Polish notation.',
    bullets: [
      'Explain CPU, memory and I/O resource management and how an OS hides hardware complexity.',
      'Trace process states, scheduling algorithms, interrupts and context switching.',
      'Compare paging with segmentation and explain virtual memory, page faults, replacement and disk thrashing.',
      'Explain host/guest operating systems and the hypervisor in a virtual machine.',
      'Follow lexical analysis, syntax analysis, code generation and optimisation.',
      'Use syntax diagrams, BNF and RPN to represent and evaluate language constructs and expressions.',
    ],
    activity: { title: 'Prior knowledge', prompt: 'Recall OS management tasks, CLI versus GUI, device drivers and DLLs before starting the A Level extensions.' },
    visual: 'recap', accent: 'indigo', ...source(372, 373, ['Chapter objectives', 'Prior knowledge', 'Chapter key terms']),
  },
  {
    id: 'h16-1611-resource-management', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.1', eyebrow: '16.1.1 · BOOTSTRAP · CPU · MEMORY · I/O',
    title: 'The OS begins at bootstrap and then manages CPU, memory and I/O as shared resources',
    lead: 'BIOS starts a bootstrap program that loads part of the OS into RAM; after startup the OS coordinates CPU time, memory and I/O requests.',
    bullets: [
      'On tablets and phones, flash memory stores the OS and apps while RAM holds currently executing apps and active data.',
      'CPU resource management depends on scheduling.',
      'I/O management must handle requests initiated by the user and requests generated while software is running.',
      'Figure 16.1 links CPU, memory, device controllers and device drivers through the system bus and DMA.',
    ],
    visual: 'types', accent: 'indigo', ...source(374, 374, ['Bootstrap', 'Resource management', 'Figure 16.1']),
  },
  {
    id: 'h16-1611-dma-kernel', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.1', eyebrow: 'DMA · TABLE 16.1 · KERNEL',
    title: 'DMA frees the CPU during slow transfers, while the kernel coordinates core OS services',
    lead: 'The DMA controller transfers data between devices and RAM independently of the CPU, then interrupts the CPU when the transfer is complete.',
    bullets: [
      'DMA initiates the transfer, allowing the CPU to perform other work.',
      'Table 16.1 contrasts slow I/O transfer rates with a GHz-scale processor clock.',
      'The kernel sits between applications and hardware and controls process management, device management, memory management, interrupts and I/O communication.',
    ],
    activity: { title: 'Extension Activity 16A', prompt: 'Estimate data-transfer rate for the source DMA scenario using the given bus width, instruction rate, processor cycles and CPU utilisation.' },
    visual: 'recap', accent: 'cyan', ...source(375, 375, ['DMA', 'Table 16.1', 'Extension Activity 16A', 'Figure 16.2 kernel']),
  },
  {
    id: 'h16-1612-multitasking', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.2', eyebrow: '16.1.2 · MULTITASKING · PREEMPTIVE VS NON-PREEMPTIVE',
    title: 'Multitasking overlaps process execution and relies on scheduling to prevent resource clashes',
    lead: 'The OS gives the appearance of simultaneous execution by sharing hardware resources among processes and monitoring each process state.',
    bullets: [
      'A process is a program that has started execution.',
      'The kernel overlaps execution according to scheduling algorithms.',
      'Preemptive scheduling can interrupt a running process after limited CPU allocation.',
      'Non-preemptive scheduling lets a running process keep resources until its burst completes or it waits for an event.',
      'Table 16.2 compares flexibility and starvation risks in the two approaches.',
    ],
    visual: 'types', accent: 'emerald', ...source(376, 376, ['Hardware abstraction', 'Multitasking', 'Table 16.2']),
  },
  {
    id: 'h16-1612-low-level-scheduling', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.2', eyebrow: 'LOW-LEVEL SCHEDULING · PRIORITY · PCB',
    title: 'Low-level scheduling selects the next ready process using workload, priority and timing information',
    lead: 'The scheduler aims to maximise throughput, keep response time acceptable and maintain stable behaviour when processes compete for resources.',
    bullets: [
      'Priority can depend on batch/online/real-time category, CPU-bound versus I/O-bound behaviour, resource requirements and timing.',
      'Deadlines, CPU time, wait time and memory requirements can further affect scheduling.',
      'A process control block stores state, privileges, register values, priority, scheduling information, required CPU time and process ID.',
      'The three source process states are running, ready and blocked.',
    ],
    visual: 'recap', accent: 'amber', ...source(377, 377, ['Low-level scheduling', 'Process priority', 'Process control block']),
  },
  {
    id: 'h16-1613-process-states', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.3', eyebrow: '16.1.3 · READY · RUNNING · BLOCKED',
    title: 'Process-state transitions explain when CPU work can proceed and when a process must wait',
    lead: 'Figure 16.3 and Table 16.3 show the permitted movements among ready, running and blocked states.',
    bullets: [
      'Running → ready: the time slice ends and an interrupt returns the process to the ready queue.',
      'Ready → running: the scheduler allocates CPU time.',
      'Running → blocked: the process must wait for I/O or another event.',
      'Blocked → ready: the awaited event or I/O resource becomes available.',
      'Figure 16.4 illustrates how ready and blocked queues interact with the CPU and schedulers.',
    ],
    visual: 'recap', accent: 'cyan', ...source(378, 378, ['Figure 16.3', 'Table 16.3', 'Figure 16.4']),
  },
  {
    id: 'h16-1613-context-fcfs', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.3', eyebrow: 'ROUND ROBIN MECHANICS · CONTEXT SWITCHING · FCFS',
    title: 'A time quantum requires state saving; FCFS then provides the simplest queue-based scheduling baseline',
    lead: 'At the end of a quantum, register contents are saved in the PCB so the process can later continue from the same point.',
    bullets: [
      'Context switching restores the saved state when a process regains the CPU.',
      'FCFS follows FIFO order and is non-preemptive.',
      'For the source burst times P1=23, P2=4, P3=9, P4=3 ms, FCFS gives an average wait of 21.5 ms.',
      'The chapter compares FCFS, SJF, SRTF and round robin using the same processes.',
    ],
    visual: 'recap', accent: 'indigo', ...source(379, 379, ['Context switching', 'FCFS', 'Figure 16.5']),
  },
  {
    id: 'h16-1613-sjf-srtf', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.3', eyebrow: 'SJF VS SRTF · TABLE 16.4',
    title: 'SJF minimises waiting without preemption; SRTF can replace the running process when a shorter job arrives',
    lead: 'The source calculates SJF at 6.5 ms average wait and SRTF at 6.25 ms for its four-process example.',
    bullets: [
      'SJF executes the process with the smallest burst time first.',
      'SRTF considers arrival times and preempts when a newly arrived process has a shorter remaining time.',
      'Accurate burst-time knowledge is useful but may not be available in advance.',
      'Figures 16.6 and 16.7 show the resulting ready-queue timelines.',
    ],
    visual: 'recap', accent: 'emerald', ...source(380, 380, ['Figure 16.6', 'Table 16.4', 'Figure 16.7']),
  },
  {
    id: 'h16-1613-round-robin', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.3', eyebrow: 'ROUND ROBIN · FIGURE 16.8 · TABLE 16.5',
    title: 'Round robin rotates a fixed quantum among processes and uses context switching between turns',
    lead: 'In the source example, the 5 ms quantum produces a 13 ms average wait, between FCFS and the shortest-job strategies.',
    bullets: [
      'A process that finishes before its quantum ends gives way immediately to the next process.',
      'Unfinished processes return for later quanta.',
      'Table 16.5 compares average waits: FCFS 21.5, SJF 6.5, SRTF 6.25 and round robin 13.0 ms.',
    ],
    activity: { title: 'Extension Activity 16B', prompt: 'Draw FCFS, SJF, SRTF and round-robin ready queues for processes A–E in the source and calculate each average waiting time.' },
    visual: 'recap', accent: 'rose', ...source(381, 381, ['Figure 16.8', 'Table 16.5', 'Extension Activity 16B']),
  },
  {
    id: 'h16-1613-interrupt-kernel', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.3', eyebrow: 'INTERRUPTS · IDT · IPL · FIGURE 16.9',
    title: 'The kernel classifies and prioritises interrupts, saves process state and dispatches the correct service routine',
    lead: 'Device interrupts, exceptions and traps/software interrupts can enter kernel mode; the interrupt dispatch table identifies the required low-level routine.',
    bullets: [
      'The kernel saves the interrupted task state on the kernel stack.',
      'Interrupt priority levels determine which interrupt can suspend another task.',
      'The source examples include power fail at IPL 31, clock at 24 and I/O devices at 20–23.',
      'After the service routine completes, saved state is restored and the interrupted process continues.',
    ],
    visual: 'recap', accent: 'amber', ...source(382, 382, ['Interrupt dispatch table', 'Interrupt priority levels', 'Figure 16.9']),
  },
  {
    id: 'h16-1614-paging', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.4', eyebrow: '16.1.4 · MEMORY MANAGEMENT · PAGING',
    title: 'Paging maps fixed-size logical pages to fixed-size physical frames through a page table',
    lead: 'Each process has its own page table. The table maps logical addresses to physical frames and stores status information used by memory management.',
    bullets: [
      'Memory management allocates and deallocates memory as processes start and finish.',
      'A page table can include page number, frame address, entry time and flags such as accessed, dirty, user/supervisor, read/write and present.',
      'P=0 indicates a page is not currently in memory; D=1 marks a modified dirty page.',
      'The TLB is a cache used to reduce address-translation time.',
    ],
    visual: 'files', accent: 'indigo', ...source(383, 383, ['Table 16.6 page-table flags', 'Paging', 'TLB']),
  },
  {
    id: 'h16-1614-segmentation', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.4', eyebrow: 'SEGMENTATION · FIGURES 16.10–16.11',
    title: 'Segmentation maps variable-size logical segments through a segment map table',
    lead: 'Segments have a number and an offset/size; the segment map table records the corresponding physical-memory location.',
    bullets: [
      'Paging uses fixed-size blocks, while segmentation uses variable-size logical groupings.',
      'A user-visible segment address includes the segment number and offset.',
      'The source diagrams contrast page-to-frame mapping with segment-to-memory mapping.',
    ],
    visual: 'files', accent: 'cyan', ...source(384, 384, ['Figure 16.10 paging', 'Figure 16.11 segmentation']),
  },
  {
    id: 'h16-1614-paging-vs-segmentation', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.4', eyebrow: 'TABLE 16.7 · PAGING VS SEGMENTATION',
    title: 'Block size, fragmentation, visibility and mapping structures distinguish paging from segmentation',
    lead: 'Table 16.7 provides the source comparison used before introducing virtual memory.',
    bullets: [
      'Paging can cause internal fragmentation; segmentation reduces internal fragmentation but can increase external fragmentation.',
      'Paging is largely invisible to the user/programmer; segmentation is visible in the logical program structure.',
      'Paging uses a page table; segmentation uses a segment map table.',
      'Pages are usually smaller than segments.',
    ],
    visual: 'types', accent: 'emerald', ...source(385, 385, ['Table 16.7', '16.1.5 Virtual memory']),
  },
  {
    id: 'h16-1615-virtual-memory', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.5', eyebrow: '16.1.5 · VIRTUAL MEMORY · SWAP SPACE',
    title: 'Virtual memory extends the usable address space by mapping inactive pages to secondary storage',
    lead: 'The chapter models virtual memory as RAM plus swap space and usually implements it with in-demand paging.',
    bullets: [
      'Programs larger than physical RAM can still execute because only required pages need to be resident.',
      'Unused data does not need to occupy RAM continuously.',
      'The mapping creates the illusion that more memory is available than physical RAM alone provides.',
      'Figures 16.12 and 16.13 contrast paging without and with virtual memory.',
    ],
    visual: 'files', accent: 'indigo', ...source(385, 386, ['Figures 16.12–16.13', 'Swap space', 'In-demand paging']),
  },
  {
    id: 'h16-1615-thrashing-translation', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.5', eyebrow: 'DISK THRASHING · VA → PA · FIGURE 16.14',
    title: 'Virtual-memory performance depends on avoiding excessive page movement and translating virtual addresses efficiently',
    lead: 'When page swapping dominates useful processing, disk thrashing reduces performance and can reach a thrash point.',
    bullets: [
      'More RAM, fewer simultaneous programs or a smaller swap file can reduce thrashing in the source discussion.',
      'A virtual address is translated to a physical address; if the data is absent, the OS loads it from disk and updates the translation map.',
      'Figure 16.14 traces loads through virtual-address and physical-address spaces.',
    ],
    visual: 'files', accent: 'amber', ...source(386, 387, ['Disk thrashing', 'Thrash point', 'Figure 16.14 address translation']),
  },
  {
    id: 'h16-1616-page-replacement', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.6', eyebrow: '16.1.6 · PAGE FAULT · FIFO · OPR · LRU · CLOCK',
    title: 'Page replacement chooses a victim frame when a required page is absent and no free frame is available',
    lead: 'A page fault is a hardware-raised interrupt, not an error condition. Replacement strategies aim to minimise the number of faults.',
    bullets: [
      'FIFO removes the oldest resident page and can suffer Belady’s anomaly.',
      'Optimal page replacement looks into the future and is useful as a comparison benchmark but cannot be implemented generally.',
      'LRU removes the page not used for the longest time.',
      'Clock/second-chance scans a circular queue and uses the R flag to give recently used pages another chance.',
    ],
    visual: 'files', accent: 'rose', ...source(388, 389, ['Figure 16.15 Belady’s anomaly', 'Figure 16.16 clock replacement']),
  },
  {
    id: 'h16-1617-management-review', section: '16.1 Purposes of an operating system (OS)', subtopicCode: '16.1.7', eyebrow: '16.1.7 · PROCESSOR VS MEMORY MANAGEMENT',
    title: 'Processor management decides what runs; memory management decides where code and data reside',
    lead: 'The chapter closes the OS section by separating scheduling/context-switching duties from paging/segmentation/virtual-memory duties.',
    bullets: [
      'Dirty pages must be written back before their frames are reused; unchanged pages need not be rewritten.',
      'Processor management focuses on process order, CPU allocation and interrupt-driven control.',
      'Memory management focuses on allocation, address mapping, replacement and storage location.',
      'The source review questions test both systems together, including paging, thrashing and scheduling.',
    ],
    visual: 'recap', accent: 'cyan', ...source(389, 391, ['Figure 16.17', 'OS multiple-choice review']),
  },
  {
    id: 'h16-1621-vm-features', section: '16.2 Virtual machines (VMs)', subtopicCode: '16.2.1', eyebrow: '16.2 · VIRTUAL MACHINE · HOST · GUEST · HYPERVISOR',
    title: 'A virtual machine emulates hardware so a guest OS can run under a host OS on incompatible physical hardware',
    lead: 'The hypervisor maps virtual CPU, memory, storage and devices to the host machine’s physical resources.',
    bullets: [
      'The host OS controls the actual physical hardware.',
      'The guest OS controls the virtual hardware presented inside the VM.',
      'The guest OS behaves as if it is running on compatible hardware and need not know it is being emulated.',
      'More than one guest OS can run on the same physical host.',
      'Virtual memory and virtual machines are explicitly different concepts.',
    ],
    visual: 'types', accent: 'indigo', ...source(392, 393, ['VM key terms', 'Figure 16.18', 'Host OS', 'Guest OS', 'Hypervisor']),
  },
  {
    id: 'h16-1622-vm-benefits-limitations', section: '16.2 Virtual machines (VMs)', subtopicCode: '16.2.2', eyebrow: '16.2.2 · BENEFITS + LIMITATIONS',
    title: 'VM isolation supports compatibility, legacy systems and safe testing, but with performance and management overhead',
    lead: 'A guest system can fail without necessarily crashing the host and can run software that the host OS itself cannot run.',
    bullets: [
      'Legacy software can be preserved on new hardware by emulating a compatible environment.',
      'New operating systems and applications can be tested inside a VM while protecting the host.',
      'Guest performance is lower than running directly on the original/native system.',
      'Large in-house VM environments can be costly and complex to manage and maintain.',
    ],
    visual: 'types', accent: 'emerald', ...source(393, 394, ['VM benefits', 'VM limitations', 'Translation software prior knowledge']),
  },
  {
    id: 'h16-1631-interpreter-compiler', section: '16.3 Translation software', subtopicCode: '16.3.1', eyebrow: '16.3.1 · INTERPRETER VS COMPILER',
    title: 'An interpreter executes source statements during each run; a compiler produces object code for later execution',
    lead: 'Figures 16.19 and 16.20 contrast the outputs and control flow of the two translation approaches.',
    bullets: [
      'A compiler outputs object code or error messages; the resulting object program can later execute without recompilation.',
      'An interpreter produces program output and error messages but no complete object program.',
      'An interpreter checks one statement, reports/corrects errors, executes it, then returns for the next statement.',
      'Both approaches construct a symbol table.',
    ],
    visual: 'types', accent: 'cyan', ...source(394, 395, ['Figures 16.19–16.20', 'Symbol table']),
  },
  {
    id: 'h16-1632-lexical-analysis', section: '16.3 Translation software', subtopicCode: '16.3.2', eyebrow: 'LEXICAL ANALYSIS · TOKENISATION · TABLE 16.8',
    title: 'Lexical analysis removes unnecessary text and turns source elements into tokens',
    lead: 'Comments and whitespace are removed, reserved words/symbols are looked up in a keyword table and program-specific identifiers are added to a symbol table.',
    bullets: [
      'The source keyword table uses tokens for symbols and reserved words such as DECLARE, INTEGER, INPUT and OUTPUT.',
      'The same keyword table can be reused for programs in the language.',
      'A separate symbol table is built for identifiers and constants in the program being compiled.',
    ],
    visual: 'types', accent: 'indigo', ...source(395, 396, ['Lexical analysis', 'Tokenisation', 'Table 16.8']),
  },
  {
    id: 'h16-1632-syntax-codegen', section: '16.3 Translation software', subtopicCode: '16.3.2', eyebrow: 'TABLE 16.9 · PARSING · CODE GENERATION',
    title: 'Syntax analysis parses the token stream; code generation proceeds only when the program is grammatically valid',
    lead: 'The compiler checks the complete token list against language grammar, reports syntax errors, then produces machine-readable object code when parsing succeeds.',
    bullets: [
      'Table 16.9 illustrates symbol-table entries for variables and constants.',
      'A malformed expression can be detected because the token sequence does not match the required grammar.',
      'Intermediate object code can support relocatable code, library linking and combining programs.',
    ],
    activity: { title: 'Activity 16B', prompt: 'Use the source token tables to write the lexical-analysis output for the final OUTPUT line of the sample program.' },
    visual: 'types', accent: 'emerald', ...source(397, 397, ['Table 16.9', 'Parsing', 'Code generation', 'Activity 16B']),
  },
  {
    id: 'h16-1632-optimisation', section: '16.3 Translation software', subtopicCode: '16.3.2', eyebrow: 'OPTIMISATION · TABLE 16.10',
    title: 'Optimisation reduces resource use without changing the required result',
    lead: 'The source example avoids calculating x + y twice by reusing the value already stored in w/the accumulator.',
    bullets: [
      'Optimisation can target execution time, storage space, memory use and CPU use.',
      'Some optimisation occurs after syntax analysis or during code generation.',
      'Not every compiler can optimise every source pattern.',
    ],
    visual: 'recap', accent: 'amber', ...source(398, 398, ['Table 16.10', 'Optimisation']),
  },
  {
    id: 'h16-1633-syntax-diagrams', section: '16.3 Translation software', subtopicCode: '16.3.3', eyebrow: '16.3.3 · SYNTAX DIAGRAMS · FIGURES 16.21–16.26',
    title: 'Syntax diagrams define valid sequences, alternatives and repetitions graphically',
    lead: 'The chapter builds from a simple letter-plus-digit variable to assignment statements and repeated/optional structures.',
    bullets: [
      'Figures 16.21–16.25 define variables, alternatives and operators.',
      'Figure 16.26 demonstrates both an alternative and a repetition loop.',
      'A source string is valid only if there is a complete path through the diagram from start to finish.',
    ],
    activity: { title: 'Activities 16C–16D', prompt: 'Validate the source variables/assignment statements, then draw a syntax diagram for one or two letters followed by zero or one digit.' },
    visual: 'recap', accent: 'rose', ...source(398, 400, ['Figures 16.21–16.26', 'Activities 16C–16D']),
  },
  {
    id: 'h16-1633-bnf', section: '16.3 Translation software', subtopicCode: '16.3.3', eyebrow: 'BACKUS–NAUR FORM · RECURSION',
    title: 'BNF expresses the same grammar as formal replacement rules and can define recursive structures',
    lead: 'The source uses angle brackets for items, ::= for definition, | for alternatives and ; to end a rule.',
    example: { title: 'Source-style recursive pattern', lines: ['<variable> ::= <letter> | <variable> <letter> ;'] },
    bullets: [
      'A recursive BNF definition can refer to the item being defined.',
      'Formal grammar gives both programmers and compiler writers an unambiguous statement of valid syntax.',
    ],
    activity: { title: 'Activity 16E / Extension 16C', prompt: 'Define an integer made from any number of digits in BNF, then refine it so that it cannot start with zero.' },
    visual: 'recap', accent: 'indigo', ...source(400, 400, ['BNF notation', 'Activity 16E', 'Extension Activity 16C']),
  },
  {
    id: 'h16-1634-rpn-stack', section: '16.3 Translation software', subtopicCode: '16.3.4', eyebrow: '16.3.4 · RPN · POSTFIX · STACK',
    title: 'Reverse Polish notation encodes precedence in token order so expressions can be evaluated left to right with a stack',
    lead: 'Operators follow their operands: A + B becomes A B +, while more complex expressions are converted according to precedence before stack evaluation.',
    bullets: [
      'Push operands onto the stack from left to right.',
      'When an operator is reached, pop the required operands, apply the operator and push the result.',
      'Continue until one result remains.',
      'The source evaluates A B C * – and (A + B) * (C – D) as stack examples.',
    ],
    activity: { title: 'Activity 16F', prompt: 'Convert the source expressions to RPN and show their changing stack contents using the supplied variable values.' },
    visual: 'types', accent: 'cyan', ...source(400, 402, ['Table 16.11', 'Figures 16.27–16.28', 'Activity 16F']),
  },
  {
    id: 'h16-review', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER REVIEW · SOURCE QUESTIONS',
    title: 'The chapter review integrates scheduling, paging, virtual machines, compilation, grammar and RPN',
    lead: 'Printed pages 402–409 contain coursebook review material, including questions adapted from the older Cambridge 9608 syllabus; these are retained as study questions rather than relabelled as current live 9618 past-paper checkpoints.',
    bullets: [
      'Calculate and compare waiting times for scheduling strategies.',
      'Trace page replacement, page-table information and process-state transitions.',
      'Explain virtual machines and translation stages.',
      'Use keyword/symbol tables, syntax diagrams and BNF.',
      'Convert and evaluate RPN with a stack.',
    ],
    activity: { title: 'Mixed retrieval', prompt: 'Choose one OS-management question, one compiler/grammar question and one RPN question from the printed review and solve each with full working.' },
    visual: 'recap', accent: 'emerald', ...source(402, 409, ['End-of-chapter questions', 'Cambridge 9608 source questions', 'Scheduling', 'Paging', 'Compiler stages', 'BNF', 'RPN']),
  },
];

export const CHAPTER_16_FINAL: HodderLessonChapter = {
  number: 16,
  level: 'A Level',
  title: 'System software and virtual machines',
  subtitle: 'Advanced OS management · virtual machines · compilation · formal grammar · Reverse Polish notation',
  subtopics: [
    '16.1 Purposes of an operating system (OS)',
    '16.2 Virtual machines (VMs)',
    '16.3 Translation software',
  ],
  sourceNote: 'Deep source-backed teaching route from the uploaded Hodder 9618 Chapter 16, printed pp.372–409. Every printed chapter page is represented in slide provenance; terminology, worked scheduling/memory examples, VM structure, compiler sequence, syntax/BNF activities and RPN stack work follow the source as teaching paraphrase.',
  coverage: '38/38 printed chapter pages represented (pp.372–409): bootstrap/resource management; DMA and kernel; multitasking, low-level scheduling, PCB/process states, FCFS/SJF/SRTF/round robin and interrupts; paging, segmentation, virtual memory, disk thrashing and page replacement; virtual machines; interpreter/compiler; lexical/syntax analysis, code generation and optimisation; syntax diagrams, BNF, RPN and end-of-chapter review.',
  slides: CHAPTER_16_DEEP_SLIDES,
};
