import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 15 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_15_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h15-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 15 · HARDWARE',
    title: 'Processor architecture and parallelism meet Boolean algebra and digital logic',
    lead: 'The chapter first compares processor architectures and parallel systems, then develops Boolean simplification, adders, flip-flops and Karnaugh maps.',
    richBlocks: [{ kind: 'steps', title: 'Chapter route', items: [
      'Compare RISC and CISC processors.',
      'Explain pipelining, registers and interrupt handling.',
      'Distinguish SISD, SIMD, MISD and MIMD.',
      'Explain clusters and massively parallel systems.',
      'Use Boolean laws including De Morgan’s Laws.',
      'Understand half/full adders and SR/JK flip-flops.',
      'Convert among circuits, truth tables and Boolean expressions.',
      'Simplify logic with Karnaugh maps.',
    ] }],
    visual: 'recap', accent: 'indigo', ...source(346, ['Chapter objectives', '15.1 prior knowledge', 'flags/fetch-execute/buses/clock/interrupts']),
  },
  {
    id: 'h15-1511-risc-cisc', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: '15.1.1 · RISC AND CISC',
    title: 'CISC uses richer complex instructions; RISC uses a smaller optimised instruction set',
    lead: 'CISC aims to do more work per assembly instruction, while RISC breaks operations into simpler instructions that can be executed and optimised more predictably.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'CISC', rightTitle: 'RISC', rows: [
      ['More instruction formats and complex instructions.', 'Fewer, simpler instruction formats.'],
      ['Complex instructions may require internal sub-instructions.', 'Simpler instructions are designed for single-cycle execution.'],
      ['Design emphasis is hardware-oriented.', 'Design emphasis is software/instruction-set oriented.'],
    ] }],
    example: { title: 'Addition idea', lines: ['CISC: one complex ADD A, B instruction', 'RISC: LOAD, LOAD, ADD, STORE as simpler steps'] },
    visual: 'types', accent: 'cyan', ...source(347, ['CISC', 'RISC', 'Key terms', 'ADD A,B example']),
  },
  {
    id: 'h15-1511-comparison-pipeline', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: 'TABLE 15.1 · PIPELINING',
    title: 'RISC characteristics make pipelining easier to implement',
    lead: 'Table 15.1 contrasts instruction formats, addressing modes, cycle count, instruction length, decoding and transistor requirements.',
    richBlocks: [
      { kind: 'table', table: { caption: 'CISC versus RISC highlights', headers: ['CISC', 'RISC'], rows: [
        ['Many formats / more addressing modes', 'Fewer formats / fewer addressing modes'],
        ['Multi-cycle / variable length', 'Single-cycle / fixed length'],
        ['More complex decoding', 'General multi-purpose registers'],
        ['Pipelining is harder', 'Pipelining is easier'],
      ] } },
      { kind: 'steps', title: 'Five pipeline stages', items: ['IF — instruction fetch', 'ID — instruction decode', 'OF — operand fetch', 'IE — instruction execution', 'WB — writeback'] },
    ],
    visual: 'recap', accent: 'emerald', ...source(348, ['Table 15.1', 'Extension Activity 15A', 'Pipelining', 'IF/ID/OF']),
  },
  {
    id: 'h15-1511-pipeline-interrupt', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: 'FIGURE 15.1 · PIPELINE + INTERRUPTS',
    title: 'Pipelining overlaps instruction stages and changes interrupt handling',
    lead: 'In the source example, six five-stage instructions complete in 10 clock cycles rather than 30 sequential cycles.',
    bullets: [
      'Registers hold intermediate pipeline stages.',
      'Each clock can advance several different instructions simultaneously.',
      'An interrupt may arrive while multiple instructions are still in the pipeline.',
      'One approach discards pipeline instructions except the one in writeback; another stores all stage contents before servicing the interrupt.',
    ],
    visual: 'recap', accent: 'amber', ...source(349, ['Figure 15.1', '10 versus 30 cycles', 'Pipeline interrupt handling']),
  },
  {
    id: 'h15-1512-sisd-simd', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: '15.1.2 · SISD + SIMD',
    title: 'SISD is sequential; SIMD applies one instruction to many data items in parallel',
    lead: 'The source uses image-brightness adjustment to show why SIMD suits large sets of independent data that need the same calculation.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'SISD', rightTitle: 'SIMD', rows: [
      ['One processor and one data source.', 'Many processors and different data values.'],
      ['One instruction handled at a time.', 'All processors perform the same instruction.'],
      ['No parallel processing.', 'Useful for graphics pixels, sound samples and array-style workloads.'],
    ] }],
    visual: 'types', accent: 'indigo', ...source(350, ['Figure 15.2 SISD', 'Figure 15.3 SIMD', '4000-pixel brightness example']),
  },
  {
    id: 'h15-1512-misd-mimd', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'MISD + MIMD · PARALLEL FACTORS',
    title: 'MISD shares data across different instructions; MIMD gives processors independent instructions and data',
    lead: 'MISD is uncommon, while MIMD is used in multicore and supercomputer architectures.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'MISD', rightTitle: 'MIMD', rows: [
      ['Several processors, different instructions, shared data source.', 'Several processors, independent instructions and data.'],
      ['Source example: Space Shuttle flight control.', 'Used in multicore systems and supercomputers.'],
    ] }],
    bullets: ['Processors must communicate and transfer results.', 'Software/languages must support multiple processors.', 'Dependent data is less suitable for parallel work.', 'Parallelism can reduce the Von Neumann bottleneck but requires more expensive hardware.'],
    visual: 'types', accent: 'cyan', ...source(351, ['Figure 15.4 MISD', 'Figure 15.5 MIMD', 'Parallel-processing factors', 'Von Neumann bottleneck']),
  },
  {
    id: 'h15-1512-cluster-massive', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'CLUSTERS · MASSIVELY PARALLEL',
    title: 'Clusters retain largely independent computers; massively parallel systems act more like one machine',
    lead: 'Massively parallel computers link thousands of processors through interconnected data pathways so each processor can handle part of a large scientific or mathematical problem.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Cluster', rightTitle: 'Massively parallel'], rows: [
      ['Networked computers combine capacity.', 'Many processors effectively form one machine.'],
      ['Computers remain largely independent.', 'Processors cooperate on parts of the overall computation.'],
      ['Can act like a supercomputer.', 'Communication uses interconnected data pathways.'],
    ] }],
    visual: 'recap', accent: 'emerald', ...source(352, ['Cluster', 'Massively parallel computer', 'Figure 15.6']),
  },
  {
    id: 'h15-151-activity', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'ACTIVITY 15A · EXTENSION 15B',
    title: 'The source consolidates processor architecture with comparison and tracing tasks',
    lead: 'Activity 15A covers RISC/CISC, the Von Neumann bottleneck, clusters versus massive parallelism and a six-instruction pipeline.',
    activity: { title: 'Activity 15A', prompt: 'Draw a pipeline diagram for LOAD A, LOAD B, LOAD C, ADD A,B,C, STORE D, OUT D and compare it with sequential processing.' },
    bullets: ['Extension 15B proposes research into seismology, astronomy, climate modelling, nuclear physics and weather forecasting.', 'Figure 15.7 asks learners to investigate growth in calculations per second.'],
    visual: 'recap', accent: 'rose', ...source(353, ['Activity 15A', 'Extension Activity 15B', 'Figure 15.7']),
  },
  {
    id: 'h15-1521-boolean-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.1', eyebrow: '15.2.1 · BOOLEAN ALGEBRA',
    title: 'Boolean algebra represents logic using TRUE (1) and FALSE (0)',
    lead: 'The section refreshes truth tables and circuits and introduces combination/sequential circuits, adders, flip-flops, sum of products, Gray codes and K-maps.',
    keyTerms: [
      { term: 'Combination circuit', definition: 'Output depends entirely on current input values.' },
      { term: 'Sequential circuit', definition: 'Output depends on current inputs and previous state/output.' },
      { term: 'Sum of products (SoP)', definition: 'AND product terms combined using OR.' },
      { term: 'Gray code', definition: 'Ordering in which adjacent binary values differ by one bit.' },
      { term: 'Karnaugh map', definition: 'Gray-code-based visual method for simplifying Boolean logic.' },
    ],
    visual: 'types', accent: 'indigo', ...source(354, ['15.2 prior knowledge', 'Figures 15.8–15.9', 'Key terms']),
  },
  {
    id: 'h15-1521-laws', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.1', eyebrow: 'TABLES 15.2–15.3 · DE MORGAN',
    title: 'Boolean simplification relies on standard identities and De Morgan’s Laws',
    lead: 'The source lists commutative, associative, distributive, idempotent, identity, null, inverse and absorption laws and proves De Morgan’s Laws by truth table.',
    richBlocks: [{ kind: 'steps', title: 'De Morgan forms', items: ['NOT(A AND B) = (NOT A) OR (NOT B)', 'NOT(A OR B) = (NOT A) AND (NOT B)', 'Matching truth-table columns prove equivalence.'] }],
    visual: 'types', accent: 'cyan', ...source(355, ['Table 15.2 Boolean laws', 'Table 15.3 De Morgan proof', 'Example 15.1']),
  },
  {
    id: 'h15-1521-half-adder', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'EXAMPLE 15.2 · HALF ADDER',
    title: 'A half adder adds two bits and outputs Sum plus Carry',
    lead: 'The source moves from Boolean simplification to a half-adder truth table and logic implementation.',
    richBlocks: [{ kind: 'table', table: { caption: 'Half-adder truth table', headers: ['A','B','S','C'], rows: [['0','0','0','0'],['0','1','1','0'],['1','0','1','0'],['1','1','0','1']] } }],
    activity: { title: 'Activity 15B', prompt: 'Simplify the five Boolean expressions in the source and show every algebraic stage.' },
    visual: 'types', accent: 'emerald', ...source(356, ['Example 15.2', 'Activity 15B', 'Table 15.4', 'Figure 15.10']),
  },
  {
    id: 'h15-1522-full-adder-build', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'FULL ADDER · FIGURES 15.11–15.13',
    title: 'A full adder accepts A, B and carry-in so multi-bit binary addition can continue across columns',
    lead: 'The source joins two half adders and an OR stage, with inputs A, B, Cin and outputs Sum, Cout.',
    bullets: ['Cin is the carry from the previous bit position.', 'Two half adders can form one full adder.', 'One implementation uses XOR, AND and OR gates.'],
    visual: 'recap', accent: 'amber', ...source(357, ['Figure 15.11', 'Figure 15.12', 'Figure 15.13']),
  },
  {
    id: 'h15-1522-full-adder-truth', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'TABLE 15.5 · FIGURE 15.14',
    title: 'Full adders chain together to add multi-bit binary values',
    lead: 'Table 15.5 gives all eight input combinations, and Figure 15.14 shows four full adders used for two 4-bit numbers.',
    activity: { title: 'Activity 15C', prompt: 'Construct half- and full-adder circuits using NAND gates only and verify them against the source truth tables.' },
    visual: 'types', accent: 'indigo', ...source(358, ['Table 15.5', 'Figure 15.14', 'Activity 15C', '15.2.3 flip-flop intro']),
  },
  {
    id: 'h15-1523-sr', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'SR FLIP-FLOP · TABLE 15.6',
    title: 'Cross-coupled NOR gates create feedback so an SR flip-flop can remember one bit',
    lead: 'The source traces set/reset states using Figures 15.15–15.17 and derives the SR truth table.',
    bullets: ['S is set and R is reset.', 'Q and NOT Q should normally be complements.', 'S=0,R=0 preserves the remembered state.', 'Cross-coupling provides positive feedback.'],
    visual: 'recap', accent: 'cyan', ...source(359, ['Figures 15.15–15.17', 'Table 15.6', 'Cross-coupling', 'Positive feedback']),
  },
  {
    id: 'h15-1523-jk-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'SR INVALID STATE → JK',
    title: 'JK adds clocked control to remove the illegal SR condition',
    lead: 'SR can produce conflicting outputs for S=1,R=1 and can be sensitive to asynchronous input arrival; JK introduces a clock and extra gates.',
    bullets: ['SR can act as one-bit storage and as part of memory such as RAM.', 'JK supports no change, set/reset-style behaviour and toggle.', 'The clock synchronises state changes.', 'Toggle replaces the invalid SR condition.'],
    visual: 'types', accent: 'rose', ...source(360, ['SR states and invalid case', 'One-bit storage/RAM', 'JK flip-flop', 'Figure 15.18']),
  },
  {
    id: 'h15-1523-jk-uses', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'TABLE 15.7 · JK USES',
    title: 'JK truth-table behaviour supports shift registers and binary counters',
    lead: 'J=K=0 preserves state; J=1,K=0 sets Q; J=0,K=1 resets Q; J=K=1 toggles Q on the clock.',
    richBlocks: [{ kind: 'table', table: { caption: 'JK behaviour', headers: ['J','K','Effect'], rows: [['0','0','No change'],['1','0','Q becomes 1'],['0','1','Q becomes 0'],['1','1','Toggle']] } }],
    visual: 'types', accent: 'emerald', ...source(361, ['Table 15.7', 'Shift registers', 'Binary counters', '15.2.4 Boolean algebra and circuits']),
  },
  {
    id: 'h15-1524-circuit-expression', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.4', eyebrow: 'EXAMPLES 15.3–15.4 · SoP',
    title: 'Boolean expressions can be derived directly from a circuit or from truth-table rows where output is 1',
    lead: 'The source demonstrates both approaches and then simplifies the sum-of-products expression using Boolean laws.',
    richBlocks: [{ kind: 'steps', title: 'Two methods', items: ['Label intermediate gate outputs and substitute forward.', 'Or select truth-table rows with output 1.', 'Write one product term per selected row.', 'OR the products, then simplify algebraically.'] }],
    visual: 'recap', accent: 'amber', ...source(362, ['Example 15.3', 'Example 15.4', 'Table 15.8', 'SoP']),
  },
  {
    id: 'h15-1525-kmap-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: '15.2.5 · K-MAPS',
    title: 'Karnaugh maps simplify Boolean logic visually using Gray-code adjacency',
    lead: 'Example 15.5 begins with a NAND truth table and maps output-1 combinations into a K-map.',
    activity: { title: 'Activity 15D', prompt: 'Produce simplified Boolean expressions for the source circuits in Figures 15.21 and 15.22.' },
    visual: 'recap', accent: 'indigo', ...source(363, ['Example 15.5 NAND', 'Activity 15D', 'Extension Activity 15E Gray code']),
  },
  {
    id: 'h15-1525-kmap-rules', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'K-MAP RULES · FIGURE 15.23',
    title: 'Group adjacent 1s as broadly as the rules allow and keep only variables that stay constant',
    lead: 'The source simplifies NAND via grouping and lists the formal grouping rules.',
    richBlocks: [{ kind: 'steps', title: 'Rules', items: ['Use Gray-code order.', 'Group only cells containing 1.', 'Use rows, columns or rectangles.', 'Make groups as large as possible.', 'Groups may overlap and may wrap across edges.', 'A single cell may stand alone.', 'A resulting term includes only variables constant within the group.'] }],
    visual: 'recap', accent: 'cyan', ...source(364, ['Figure 15.23', 'K-map rules', 'NAND K-map']),
  },
  {
    id: 'h15-1525-kmap-3var', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'EXAMPLE 15.6 · THREE VARIABLES',
    title: 'A three-variable K-map reduces four minterms to three simpler product terms',
    lead: 'Each group removes any variable that changes inside the group; the source result is A.C + B.C + A.B.',
    visual: 'recap', accent: 'emerald', ...source(365, ['Example 15.6', 'Three-variable K-map', 'A.C + B.C + A.B']),
  },
  {
    id: 'h15-1525-kmap-4var', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'EXAMPLE 15.7 · FOUR VARIABLES',
    title: 'A four-variable K-map can collapse many minterms into a small number of grouped terms',
    lead: 'The source maps six output-1 combinations and uses large groups so changing variables disappear from the simplified result.',
    bullets: ['Both axes use Gray-code ordering.', 'Larger groups produce simpler terms.', 'The map gives the same logical function as the original truth table.'],
    visual: 'recap', accent: 'amber', ...source(366, ['Example 15.7', 'Four-variable K-map', 'SoP column']),
  },
  {
    id: 'h15-1525-kmap-wrap', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'FIGURES 15.19–15.22 · WRAP-AROUND',
    title: 'Opposite K-map edges are adjacent, enabling wrap-around groups and corner groups',
    lead: 'The source illustrates vertical and horizontal wrap-around plus a four-corner group; only the variables constant across a chosen group remain.',
    bullets: ['A large group may leave only one constant variable.', 'Columns at opposite map edges can be adjacent.', 'The four corners can form one valid group.', 'Different valid groups can overlap.'],
    visual: 'recap', accent: 'rose', ...source(367, ['Figures 15.19–15.22', 'Wrap-around groups', 'Corner groups']),
  },
  {
    id: 'h15-activity-15e', section: 'Chapter review', eyebrow: 'ACTIVITY 15E · END-OF-CHAPTER START',
    title: 'The final activity integrates expressions, truth tables, K-maps and circuit design',
    lead: 'Tasks include deriving K-maps from expressions, producing simplified expressions and building efficient circuits from the simplified form.',
    activity: { title: 'Activity 15E', prompt: 'Choose one source expression, construct its truth table and K-map, derive the simplified Boolean expression and draw the corresponding logic circuit.' },
    visual: 'recap', accent: 'indigo', ...source(368, ['Activity 15E', 'End of chapter questions']),
  },
  {
    id: 'h15-review-boolean-sr', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER · BOOLEAN + SR',
    title: 'Review tasks test K-map derivation, Boolean-law simplification and SR invalid-state reasoning',
    lead: 'The source asks for a K-map from a four-input truth table, algebraic simplification and completion/explanation of an SR flip-flop truth table.',
    visual: 'recap', accent: 'cyan', ...source(369, ['Review questions 2–3a', 'K-map', 'Boolean simplification', 'SR flip-flop']),
  },
  {
    id: 'h15-review-parallel-jk', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER · JK + PARALLEL',
    title: 'Review tasks connect JK behaviour with SISD/SIMD/MISD/MIMD, pipelining and massively parallel design',
    lead: 'Learners classify architectures, explain massive/parallel, identify hardware/software issues and compare pipelined with sequential clock cycles.',
    bullets: ['The printed page includes a question adapted from Cambridge 9608 Paper 32 Q4 November 2015.', 'It remains coursebook review here rather than a current live 9618 checkpoint.'],
    visual: 'recap', accent: 'emerald', ...source(370, ['Review questions 3b–5', 'SISD/SIMD/MISD/MIMD', 'Pipelining', '9608 Paper 32 Q4 November 2015']),
  },
  {
    id: 'h15-review-circuit-kmap', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTION 6',
    title: 'The final problem connects circuit, expression, truth table, K-map and Boolean proof',
    lead: 'Starting from a three-input circuit, learners produce a Boolean expression, complete the truth table, group a K-map, write a simplified SoP and prove the simplification using an identity and De Morgan’s Laws.',
    bullets: ['The printed question is adapted from Cambridge 9608 Paper 32 Q3 June 2017.', 'It remains source-backed coursebook review rather than current live 9618 Past Paper practice.'],
    visual: 'recap', accent: 'amber', ...source(371, ['Review question 6', 'K-map', 'SoP', 'De Morgan', '9608 Paper 32 Q3 June 2017']),
  },
];

export const CHAPTER_15_FINAL: HodderLessonChapter = {
  number: 15,
  level: 'A Level',
  title: 'Hardware',
  subtitle: 'RISC/CISC and pipelining · parallel architectures · Boolean algebra · adders · flip-flops · Karnaugh maps',
  subtopics: ['15.1 Processors and parallel processing', '15.2 Boolean algebra and logic circuits'],
  sourceNote: 'Deep source-backed teaching route from the uploaded Hodder 9618 Chapter 15, printed pp.346–371. Every printed chapter page is represented in slide provenance and the source sequence, figures, examples, activities and terminology are preserved as teaching paraphrase.',
  coverage: '26/26 printed chapter pages represented (pp.346–371): RISC/CISC, pipeline stages and interrupts; SISD/SIMD/MISD/MIMD, clusters and massively parallel systems; Boolean laws and De Morgan; half/full adders; SR/JK flip-flops; circuit/truth-table/SoP conversion; K-map rules, grouping and wrap-around; activities and end-of-chapter review.',
  slides: CHAPTER_15_DEEP_SLIDES,
};
