import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 12 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_12_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h12-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 12 · SOFTWARE DEVELOPMENT',
    title: 'Develop software through a documented lifecycle, formal design, rigorous testing and maintenance',
    lead: 'The chapter connects the program development lifecycle to structure charts, state-transition diagrams, fault handling, testing strategies and maintenance categories.',
    richBlocks: [{ kind: 'steps', title: 'Chapter route', items: [
      'Explain why a program development lifecycle is used.',
      'Describe analysis, design, coding, testing and maintenance.',
      'Compare waterfall, iterative and RAD development models.',
      'Document modular design with structure charts.',
      'Document finite-state behaviour with state-transition tables/diagrams.',
      'Distinguish syntax, logic and run-time errors.',
      'Use dry runs, trace tables, test plans and multiple testing stages.',
      'Explain corrective, perfective and adaptive maintenance.',
    ] }],
    keyTerms: [
      { term: 'Program development lifecycle', definition: 'A five-stage process: analysis, design, coding, testing and maintenance.' },
      { term: 'Waterfall model', definition: 'A linear sequential lifecycle in which each stage is completed before the next begins.' },
      { term: 'Iterative model', definition: 'A lifecycle that develops a subset, then repeats the cycle to expand the system.' },
      { term: 'Rapid application development (RAD)', definition: 'Parallel development of different parts, often using prototypes for early user feedback.' },
    ],
    activity: { title: 'Prior-knowledge check', prompt: 'Name the main lifecycle stages, then compare at least two different development approaches you already know.' },
    visual: 'recap', accent: 'indigo', ...source(283, ['Chapter objectives', 'What you should already know', 'Lifecycle/model key terms']),
  },
  {
    id: 'h12-121-purpose-stages', section: '12.1 Program development lifecycle', subtopicCode: '12.1.1', eyebrow: '12.1.1–12.1.2 · PURPOSE + FIGURE 12.1',
    title: 'A lifecycle makes development ordered, documented and understandable to other developers',
    lead: 'The source frames software development as a continuing lifecycle because programs may need later alteration for new circumstances or newly discovered errors.',
    richBlocks: [{ kind: 'steps', title: 'Five stages', items: [
      'Analysis: investigate and specify what the program must do.',
      'Design: document how the required program will be built.',
      'Coding: write the program using a suitable language.',
      'Testing: execute the program with different test data and compare against the design.',
      'Maintenance: correct, improve or adapt the program throughout its useful life.',
    ] }],
    bullets: ['Analysis can start with feasibility work and fact finding.', 'Design can be documented with structure charts, state-transition diagrams and pseudocode.'],
    visual: 'recap', accent: 'cyan', ...source(284, ['12.1.1 purpose', '12.1.2 stages', 'Figure 12.1 lifecycle', 'Requirements specification']),
  },
  {
    id: 'h12-121-waterfall', section: '12.1 Program development lifecycle', subtopicCode: '12.1.3', eyebrow: 'WATERFALL · FIGURE 12.2 · TABLE 12.1',
    title: 'Waterfall is sequential, well documented and easiest when requirements are stable',
    lead: 'Each stage is completed and signed off before the next begins, with relatively low customer involvement after the initial requirements stage.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Benefits', rightTitle: 'Drawbacks', rows: [
      ['Easy to manage, understand and use.', 'Late requirement changes are difficult.'],
      ['Stages do not overlap and have clear deliverables.', 'Working software appears late in the lifecycle.'],
      ['Works well for smaller programs with known requirements.', 'Poor fit for long complex projects or evolving requirements.'],
    ] }],
    visual: 'recap', accent: 'indigo', ...source(285, ['Figure 12.2 waterfall model', 'Table 12.1 principles/benefits/drawbacks']),
  },
  {
    id: 'h12-121-iterative-rad-intro', section: '12.1 Program development lifecycle', subtopicCode: '12.1.3', eyebrow: 'ITERATIVE · FIGURE 12.3 · TABLE 12.2',
    title: 'Iterative development repeatedly extends working subsets of the final system',
    lead: 'A simple subset is developed first; further cycles expand or enhance it until the whole system is complete.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Benefits', rightTitle: 'Drawbacks', rows: [
      ['Working programs appear early.', 'The whole system still needs enough definition to divide it into pieces.'],
      ['Smaller parts can be easier to test/debug.', 'Strong overall and per-iteration planning is required.'],
      ['Customer feedback can influence each iteration.', 'Not a good fit for short simple projects.'],
    ] }],
    bullets: ['The source also introduces RAD on this page as multiple development cycles running in parallel.'],
    visual: 'recap', accent: 'emerald', ...source(286, ['Figure 12.3 iterative model', 'Table 12.2 iterative model', 'Figure 12.4 RAD']),
  },
  {
    id: 'h12-121-rad', section: '12.1 Program development lifecycle', subtopicCode: '12.1.3', eyebrow: 'RAD · TABLE 12.3',
    title: 'RAD trades heavier planning for parallel teams, prototypes and rapid customer feedback',
    lead: 'Different parts of the requirement are developed in parallel; prototypes are used to involve customers early and let requirements evolve.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Benefits', rightTitle: 'Drawbacks', rows: [
      ['Reduced overall development time.', 'The system must be modular.'],
      ['Frequent customer feedback shapes the work.', 'Strong skilled teams are required.'],
      ['Flexible when requirements evolve.', 'Not suited to short simple projects.'],
    ] }],
    activity: { title: 'Extension Activity 12A', prompt: 'Research four additional development methodologies and compare their principles with waterfall, iterative and RAD.' },
    visual: 'recap', accent: 'amber', ...source(287, ['Table 12.3 RAD principles/benefits/drawbacks', 'Extension Activity 12A', '12.2 Program design key terms']),
  },
  {
    id: 'h12-1221-structure-chart', section: '12.2 Program design', subtopicCode: '12.2.1', eyebrow: '12.2.1 · STRUCTURE CHARTS · FIGURES 12.5–12.6',
    title: 'Structure charts decompose a task into modules and show the parameters passed between them',
    lead: 'Each module is a box, arrows show values passed to receiving modules and each lower level refines the level above.',
    richBlocks: [{ kind: 'steps', title: 'Temperature-conversion model', items: [
      'Top-level task: Convert temperature.',
      'Sub-modules: input temperature, convert, output temperature.',
      'Selection can be shown by a condition controlling alternative modules.',
      'Parameters on arrows document data flow between modules.',
    ] }],
    activity: { title: 'Activity 12A', prompt: 'Draw a structure chart that inputs height and width of a right-angled triangle, calculates the hypotenuse and outputs it.' },
    visual: 'recap', accent: 'cyan', ...source(288, ['12.2.1 structure charts', 'Figure 12.5 Fahrenheit-to-Celsius chart', 'Figure 12.6 selection', 'Activity 12A']),
  },
  {
    id: 'h12-1221-repetition-sphere', section: '12.2 Program design', subtopicCode: '12.2.1', eyebrow: 'FIGURES 12.7–12.8 · ACTIVITIES 12B–12C',
    title: 'Structure charts can represent repetition as well as selection',
    lead: 'The source adds a labelled repetition arrow to the temperature task, then builds a sphere calculator that repeats until radius zero is entered.',
    bullets: ['Figure 12.7 repeats conversion until temperature = 999.', 'Figure 12.8 lets the sphere task select volume or surface area and repeat until radius = 0.', 'A completed chart can be used directly to derive pseudocode.'],
    activity: { title: 'Activities 12B–12C', prompt: 'First draw a sphere structure chart for either volume or surface area. Then extend it so calculations repeat until radius 0 is entered.' },
    visual: 'recap', accent: 'indigo', ...source(289, ['Figure 12.7 repetition', 'Activity 12B', 'Activity 12C', 'Figure 12.8 sphere chart']),
  },
  {
    id: 'h12-1221-sphere-modules', section: '12.2 Program design', subtopicCode: '12.2.1', eyebrow: 'TABLE 12.4 · FUNCTIONS + PROCEDURES',
    title: 'The sphere structure chart maps naturally to an identifier table, functions and procedures',
    lead: 'The calculation modules return values, so the source defines them as functions; input and output modules are modelled as procedures.',
    richBlocks: [
      { kind: 'table', table: { caption: 'Sphere identifiers', headers: ['Identifier', 'Purpose'], rows: [['radius', 'Input radius'], ['answer', 'Calculation result'], ['pi', 'Constant 3.142 in the source example']] } },
      { kind: 'steps', title: 'Module mapping', items: ['calculateVolume(radius) → function', 'calculateSurfaceArea(radius) → function', 'inputRadius → procedure', 'outputAnswer → procedure'] },
    ],
    visual: 'types', accent: 'emerald', ...source(290, ['Table 12.4', 'calculateVolume function', 'calculateSurfaceArea function', 'inputRadius/outputAnswer procedures']),
  },
  {
    id: 'h12-1221-whole-sphere', section: '12.2 Program design', subtopicCode: '12.2.1', eyebrow: 'WHOLE ALGORITHM · SELECTION + REPETITION',
    title: 'The complete pseudocode combines the chart’s modules with a loop and a volume/surface-area choice',
    lead: 'The whole algorithm repeatedly inputs radius, asks which calculation is required, calls the appropriate function and outputs the answer until radius zero ends the loop.',
    richBlocks: [{ kind: 'steps', title: 'Top-level control flow', items: ['Call inputRadius.', 'While radius is not zero, ask V or S.', 'Use IF to select the required calculation function.', 'Store the returned answer.', 'Call outputAnswer.', 'Call inputRadius again.'] }],
    visual: 'recap', accent: 'amber', ...source(291, ['Complete sphere pseudocode', 'WHILE radius <> 0', 'Function calls', 'Procedure calls']),
  },
  {
    id: 'h12-1222-fsm-table', section: '12.2 Program design', subtopicCode: '12.2.2', eyebrow: '12.2.2 · FSM · TABLE 12.5',
    title: 'A state-transition model records states, events and the next state after each event',
    lead: 'The source uses a three-digit door code 259: correct digits advance through states, while an incorrect digit returns the lock to its initial state.',
    richBlocks: [{ kind: 'table', table: { caption: 'State-transition notation', headers: ['Element', 'Meaning'], rows: [
      ['Node/circle', 'State'],
      ['Arrow', 'Transition'],
      ['Arrow label', 'Event'],
      ['[condition]', 'Optional transition condition'],
      ['Black-dot arrow', 'Initial state'],
      ['Double circle', 'Stopped state'],
    ] } }],
    activity: { title: 'Activity 12D', prompt: 'Extend temperature conversion to work in both directions and repeat until 999, then derive pseudocode from the structure chart.' },
    visual: 'recap', accent: 'cyan', ...source(292, ['Activity 12D', '12.2.2 state-transition diagrams', 'Table 12.5 entry code 259']),
  },
  {
    id: 'h12-1222-door-tv', section: '12.2 Program design', subtopicCode: '12.2.2', eyebrow: 'FIGURE 12.9 · ACTIVITY 12E',
    title: 'The diagram makes reset paths and the stopped state visible at a glance',
    lead: 'Figure 12.9 shows the code-259 door path. Activity 12E applies the same method to a television with off, standby and on states.',
    activity: { title: 'Activity 12E', prompt: 'Complete the television state-transition table for single/double presses, then draw the state-transition diagram.' },
    visual: 'recap', accent: 'indigo', ...source(293, ['Figure 12.9 door code state diagram', 'Activity 12E television FSM', '12.3 testing prior-knowledge prompt']),
  },
  {
    id: 'h12-123-faults-testing-keyterms', section: '12.3 Program testing and maintenance', subtopicCode: '12.3.1', eyebrow: '12.3 · TESTING + MAINTENANCE KEY TERMS',
    title: 'Testing terminology separates methods, data categories, lifecycle stages and maintenance goals',
    lead: 'The source introduces trace tables, dry runs, walkthroughs, test strategy/plan, test-data classes, white/black-box testing, integration/stub testing, alpha/beta/acceptance testing and three maintenance categories.',
    richBlocks: [{ kind: 'table', table: { caption: 'Test-data categories', headers: ['Type', 'Meaning'], rows: [
      ['Normal', 'Should be accepted'],
      ['Abnormal', 'Should be rejected'],
      ['Extreme', 'At the accepted limit'],
      ['Boundary', 'At an accepted limit and just outside that limit'],
    ] } }],
    bullets: ['Fault avoidance begins with a rigorous specification and formal design.', 'Testing can reveal faults but cannot prove that a large complex program is fault-free in every circumstance.'],
    visual: 'types', accent: 'rose', ...source(294, ['12.3 key terms', '12.3.1 fault avoidance/exposure', 'Testing and maintenance terminology']),
  },
  {
    id: 'h12-1232-syntax-logic', section: '12.3 Program testing and maintenance', subtopicCode: '12.3.2', eyebrow: '12.3.2 · SYNTAX + LOGIC ERRORS · FIGURES 12.10–12.11',
    title: 'Syntax errors prevent correct parsing; logic errors let the program run but produce wrong behaviour',
    lead: 'The source shows an IDE detecting a mistyped identifier as a syntax problem and a direction-update example whose wrong variable causes a logic error.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Syntax error', rightTitle: 'Logic error', rows: [
      ['Breaks the grammar/rules of the language.', 'Breaks the intended logic of the solution.'],
      ['Often exposed by compiler/interpreter/IDE before successful execution.', 'Often exposed during testing because output or state is wrong.'],
    ] }],
    bullets: ['Single stepping and trace tables help locate logic errors.', 'A trace table records variable values as a dry run proceeds.'],
    visual: 'recap', accent: 'amber', ...source(295, ['Extension Activity 12B', 'Figure 12.10 syntax error', 'Figure 12.11 logic error', 'Trace table', 'Dry run']),
  },
  {
    id: 'h12-1232-runtime-test-strategy', section: '12.3 Program testing and maintenance', subtopicCode: '12.3.2', eyebrow: 'RUN-TIME ERROR · PATCH · TEST STRATEGY',
    title: 'Run-time errors appear during execution and released software may require a patch',
    lead: 'The source demonstrates division by zero, then explains that released software can be updated or patched when run-time faults are discovered.',
    bullets: [
      'A run-time error can halt a program unexpectedly or lead to uncontrolled behaviour such as an infinite loop.',
      'A patch is a small update used with an existing program to correct an error or add functionality.',
      'A test strategy is an overview of what must be tested, how and when.',
      'A test plan lists the specific tests and can record results against expected outcomes.',
      'Testing starts during design: pseudocode can be dry-run manually before coding.',
    ],
    visual: 'recap', accent: 'indigo', ...source(296, ['Run-time divide-by-zero example', 'Patch', '12.3.3 Program testing', 'Test strategy', 'Test plan', 'Dry run']),
  },
  {
    id: 'h12-1233-dry-run', section: '12.3 Program testing and maintenance', subtopicCode: '12.3.3', eyebrow: 'TABLE 12.6 · ACTIVITIES 12F–12G',
    title: 'A dry run and trace table can expose errors in pseudocode before the routine is coded',
    lead: 'The calculation example traces +, -, *, /, an invalid operator and division by zero; the table reveals wrong subtraction logic and undefined output for zero division.',
    activity: { title: 'Activities 12F–12G', prompt: 'Correct the calculation pseudocode and dry-run it again. Then devise test data and a trace table for the sphere algorithm and compare results with another learner.' },
    visual: 'recap', accent: 'cyan', ...source(297, ['Calculation procedure', 'Table 12.6 trace table', 'Activity 12F', 'Activity 12G']),
  },
  {
    id: 'h12-1233-walkthrough-testdata', section: '12.3 Program testing and maintenance', subtopicCode: '12.3.3', eyebrow: 'WALKTHROUGH · TABLE 12.7 · TEST DATA',
    title: 'Walkthroughs formalise dry runs, while test plans compare expected and actual outcomes',
    lead: 'The source’s test-plan example demonstrates that a failed expected/actual comparison means the routine must be corrected and retested.',
    richBlocks: [{ kind: 'table', table: { caption: 'Range 12–32 example', headers: ['Data class', 'Examples', 'Expected'], rows: [
      ['Extreme', '12 and 32', 'Accepted'],
      ['Boundary', '11, 12, 32, 33', '12/32 accepted; 11/33 rejected'],
      ['Normal / abnormal', 'Values clearly inside / unsuitable inputs', 'Accept / reject as specified'],
    ] } }],
    visual: 'types', accent: 'emerald', ...source(298, ['Walkthrough', 'Table 12.7 test plan', 'Extension Activity 12C', 'Normal/abnormal/extreme/boundary data']),
  },
  {
    id: 'h12-1233-testing-levels-maintenance', section: '12.3 Program testing and maintenance', subtopicCode: '12.3.3', eyebrow: 'ACTIVITY 12H · WHITE/BLACK/INTEGRATION · ALPHA/BETA/ACCEPTANCE',
    title: 'Testing moves from module internals and interfaces to complete-system user/customer validation',
    lead: 'The source distinguishes development-time testing from completed-program testing, then introduces maintenance categories.',
    richBlocks: [
      { kind: 'table', table: { caption: 'Testing methods', headers: ['Method', 'Focus'], rows: [
        ['White-box', 'Internal structure and every path through a module'],
        ['Black-box', 'Inputs and outputs'],
        ['Integration', 'Modules working together; can use stubs for missing modules'],
        ['Alpha', 'Completed/nearly completed system tested in-house'],
        ['Beta', 'Completed system tested by a small group of users'],
        ['Acceptance', 'Customer confirms the completed system works as required in its target environment'],
      ] } },
      { kind: 'table', table: { caption: 'Maintenance categories', headers: ['Category', 'Role'], rows: [
        ['Corrective', 'Correct errors that appear during use'],
        ['Perfective', 'Improve performance or other existing behaviour'],
        ['Adaptive', 'Alter the program for new required tasks'],
      ] } },
    ],
    activity: { title: 'Activity 12H', prompt: 'Devise test data for a password that must be 8–15 characters, include a digit and uppercase letter, and contain only letters/digits.' },
    visual: 'types', accent: 'rose', ...source(299, ['Activity 12H', 'Extension Activity 12D', 'White-box', 'Black-box', 'Integration/stub', 'Alpha/Beta/Acceptance', '12.3.4 maintenance']),
  },
  {
    id: 'h12-review-start', section: 'Chapter review', eyebrow: 'ACTIVITIES 12I–12J · END-OF-CHAPTER QUESTION 1',
    title: 'The chapter closes by connecting improvements, error types, test data and maintenance back to modular design',
    lead: 'Activity 12J rehearses syntax-vs-logic, range-test data and maintenance; the first review question applies structure-chart reading to an insurance quotation system.',
    activity: { title: 'Activity 12J', prompt: 'Explain syntax versus logic errors, choose three kinds of test data for values over 10 and under 100, and describe corrective, perfective and adaptive maintenance.' },
    visual: 'recap', accent: 'indigo', ...source(300, ['Activity 12I', 'Activity 12J', 'End-of-chapter question 1 insurance structure chart']),
  },
  {
    id: 'h12-review-structure-errors', section: 'Chapter review', eyebrow: 'QUESTION 1 + QUESTION 2 START',
    title: 'Review questions test structure-chart labels and diagnosis of pseudocode faults',
    lead: 'The insurance chart requires module/data-flow labelling; the next problem gives an ArraySort bubble-sort attempt with deliberate errors.',
    bullets: ['Identify the correct module hierarchy and data passed between insurance-quotation modules.', 'Inspect the array-sort routine line by line for incorrect procedure name, types, bounds, substring length, indices and swap statements.'],
    visual: 'recap', accent: 'cyan', ...source(301, ['Question 1 structure-chart labels', 'Cambridge 9608 Paper 22 Q3 June 2015', 'Question 2 ArraySort start']),
  },
  {
    id: 'h12-review-array-sort', section: 'Chapter review', eyebrow: 'QUESTION 2 · FIND + CORRECT PSEUDOCODE ERRORS',
    title: 'The array-sort task requires identifying each distinct fault and stating the correction',
    lead: 'The source explicitly says lack of optimisation is not itself an error; learners must focus on correctness of the given pseudocode.',
    activity: { title: 'Error-audit task', prompt: 'For every distinct error in the printed ArraySort routine, record its line number, explain the fault and write the correction.' },
    visual: 'recap', accent: 'amber', ...source(302, ['Question 2 error table', 'Cambridge 9608 Paper 22 Q3 November 2017', 'Question 3 sales trace intro']),
  },
  {
    id: 'h12-review-trace', section: 'Chapter review', eyebrow: 'QUESTION 3 · SALES ARRAYS + TRACE TABLE',
    title: 'The final review combines array selection, a seven-day loop, conditional output and a trace table',
    lead: 'SalesX and SalesY are processed for seven days; dates are output when combined sales reach at least ten and a counter records how many days meet the condition.',
    activity: { title: 'Trace and describe', prompt: 'Complete the trace table for x, DayNumber and OUTPUT using the source data, then describe exactly what the algorithm does.' },
    visual: 'recap', accent: 'emerald', ...source(303, ['Question 3 SalesDate/SalesX/SalesY', 'Trace table', 'Cambridge 9608 Paper 22 Q5 June 2015']),
  },
];

export const CHAPTER_12_FINAL: HodderLessonChapter = {
  number: 12,
  level: 'AS Level',
  title: 'Software development',
  subtitle: 'Development lifecycles · structure charts · finite-state design · errors, testing and maintenance',
  subtopics: ['12.1 Program development lifecycle', '12.2 Program design', '12.3 Program testing and maintenance'],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 Chapter 12 in the connected full coursebook, printed pp.283–303. Every printed chapter page is represented in slide provenance and the source models, diagrams, activities, examples and testing terminology are preserved as teaching paraphrase.',
  coverage: '21/21 printed chapter pages represented (pp.283–303): five lifecycle stages; waterfall, iterative and RAD models; structure charts with selection/repetition and sphere pseudocode; finite-state tables/diagrams; fault avoidance; syntax/logic/run-time errors; dry runs, walkthroughs and trace tables; test strategies/plans/data; white/black-box, integration/stub, alpha/beta/acceptance testing; corrective/perfective/adaptive maintenance; source activities and complete chapter-review sequence.',
  slides: CHAPTER_12_DEEP_SLIDES,
};
