import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

export type Chapter3Lesson = Omit<HodderLessonChapter, 'number'> & { number: 3 };

const source = (printedPage: number | number[], elements: string[] = []) => {
  const pages = Array.isArray(printedPage) ? printedPage : [printedPage];
  return {
    sourcePages: pages,
    sourceLabel: `Hodder Chapter 3 · p.${pages.join('–')}`,
    sourceElements: pages.map(page => `Hodder p.${page}`).concat(elements),
  };
};

const slides: HodderLessonSlide[] = [
  {
    id: 'h3-overview',
    section: 'Chapter overview',
    eyebrow: 'CHAPTER 3 · HARDWARE',
    title: 'Hardware: memory, storage, devices and logic',
    lead: 'Hodder Chapter 3 moves from computer memory and storage through embedded systems and hardware devices to monitoring, control, logic gates, truth tables and logic circuits.',
    bullets: [
      'Primary storage/memory devices and secondary storage, including removable devices.',
      'Benefits and drawbacks of embedded systems.',
      'Hardware devices used as input, output and storage.',
      'RAM, ROM, SRAM, DRAM, PROM and EPROM, including where they are used.',
      'Monitoring and control systems.',
      'NOT, AND, OR, NAND, NOR and XOR gates; truth tables; logic circuits and expressions.',
    ],
    richBlocks: [{
      kind: 'steps',
      title: 'What you should already know',
      items: [
        'Distinguish memory from storage.',
        'Explain why internal and external memory/storage are both needed.',
        'Recognise common memory and storage devices.',
        'Distinguish online from offline storage.',
        'Distinguish data access time from data transfer rate.',
      ],
    }],
    visual: 'memory',
    accent: 'indigo',
    ...source(68, ['Chapter 3 learning objectives', 'What you should already know', 'Figure 3.1']),
  },
  {
    id: 'h3-311-memory-storage',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: '3.1.1 · TYPES OF MEMORY AND STORAGE',
    title: 'Memory is internal workspace; storage keeps data for longer',
    lead: 'The coursebook distinguishes directly accessible internal memory from larger, persistent storage used for applications, files and user data.',
    richBlocks: [{
      kind: 'comparison',
      leftTitle: 'Memory',
      rightTitle: 'Storage',
      rows: [
        ['Internal devices the computer can access directly', 'Used to store applications, data and files'],
        ['Workspace, temporary data and data needed to run the computer', 'User data is stored persistently and can be read or changed'],
        ['Includes registers and memory cache', 'Normally much larger than internal memory'],
        ['Fast access close to the processor', 'Can be removable for transfer or off-site backup'],
      ],
    }],
    visual: 'memory',
    accent: 'cyan',
    ...source(69, ['3.1.1 Types of memory and storage', 'Memory cache']),
  },
  {
    id: 'h3-311-memory-map',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: 'FIGURE 3.2 · MEMORY AND STORAGE DEVICES',
    title: 'Primary memory and secondary storage form two main branches',
    lead: 'Hodder Figure 3.2 organises RAM and ROM under primary memory, and HDD, SSD and removable media under secondary storage.',
    visual: 'memory',
    accent: 'indigo',
    ...source(70, ['Figure 3.2 Memory and storage devices']),
  },
  {
    id: 'h3-311-primary-tree',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: 'FIGURE 3.3 · PRIMARY MEMORY',
    title: 'Primary memory divides into RAM and ROM families',
    lead: 'The source tree places SRAM and DRAM under RAM, and PROM, EPROM and EEPROM under ROM.',
    bullets: [
      'RAM can be written to and read from, and is volatile.',
      'RAM holds data, files, applications and operating-system content currently in use.',
      'Any RAM location can be accessed independently of the previously used location.',
      'More RAM reduces repeated access to slower secondary storage when active memory pressure is high.',
    ],
    visual: 'memory',
    accent: 'emerald',
    ...source(70, ['Figure 3.3 Structure of primary memory', 'Primary memory']),
  },
  {
    id: 'h3-311-dram-sram',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: 'TABLE 3.1 · DRAM VS SRAM',
    title: 'DRAM trades speed for capacity and cost; SRAM is used where speed matters',
    lead: 'Hodder contrasts capacitor-based DRAM that must be refreshed with flip-flop-based SRAM that does not need refreshing.',
    richBlocks: [{
      kind: 'table',
      table: {
        caption: 'Table 3.1 · Differences between DRAM and SRAM',
        headers: ['DRAM', 'SRAM'],
        rows: [
          ['Transistors and capacitors', 'Flip-flops hold each bit'],
          ['Needs constant refreshing', 'Does not need constant refreshing'],
          ['Less expensive to manufacture', 'Faster data access'],
          ['Higher memory capacity', 'Used for processor memory cache'],
          ['Main memory commonly uses DRAM', 'High-frequency access can raise power usage'],
        ],
      },
    }],
    example: {
      title: 'Source timing example',
      lines: ['Typical SRAM access time: 25 ns', 'Typical DRAM access time: 60 ns', 'DRAM refresh interval described by Hodder: 15 microseconds'],
    },
    visual: 'memory',
    accent: 'amber',
    ...source(71, ['Table 3.1 Differences between DRAM and SRAM', 'Figures 3.4 and 3.5']),
  },
  {
    id: 'h3-311-ram-rom',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: 'TABLE 3.2 · RAM VS ROM',
    title: 'RAM is temporary and writable; ROM is permanent and non-volatile',
    lead: 'The coursebook uses Table 3.2 to contrast RAM and ROM, then introduces PROM and EPROM as programmable ROM technologies.',
    richBlocks: [{
      kind: 'comparison',
      leftTitle: 'RAM',
      rightTitle: 'ROM',
      rows: [
        ['Temporary memory device', 'Permanent memory device'],
        ['Volatile', 'Non-volatile'],
        ['Can be written to and read from', 'Stored data cannot normally be altered'],
        ['Stores active data, files, programs and part of the OS', 'Can store BIOS and other start-up data'],
      ],
    }],
    bullets: [
      'PROM can be programmed once by electrically altering a fuse matrix.',
      'EPROM can be programmed more than once and uses ultraviolet light through a quartz window.',
    ],
    visual: 'memory',
    accent: 'rose',
    ...source(72, ['Table 3.2 Differences between RAM and ROM', 'PROM and EPROM']),
  },
  {
    id: 'h3-311-embedded',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: 'TABLE 3.3 · EMBEDDED SYSTEMS',
    title: 'Embedded systems put dedicated processing inside everyday devices',
    lead: 'Hodder describes microprocessors embedded in devices such as cookers, refrigerators and central-heating systems, including web-enabled remote control.',
    richBlocks: [{
      kind: 'comparison',
      leftTitle: 'Pros',
      rightTitle: 'Cons',
      rows: [
        ['Small and relatively low cost', 'Difficult to upgrade'],
        ['Dedicated task can simplify the interface', 'Troubleshooting can require specialist skills'],
        ['Low power consumption', 'Interfaces can still become confusing'],
        ['Very fast reaction to changing input', 'Internet-connected devices are exposed to hacking and malware'],
        ['Mass production can improve reliability', 'Difficult repair or upgrade can increase waste'],
      ],
    }],
    visual: 'embedded',
    accent: 'emerald',
    ...source(72, ['Table 3.3 Pros and cons of controlling devices with embedded systems']),
  },
  {
    id: 'h3-311-hdd',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: 'SECONDARY STORAGE · HDD',
    title: 'Hard disk drives store magnetic data in tracks and sectors',
    lead: 'Secondary storage is non-volatile, much larger than primary memory and slower to access. Hodder groups it into magnetic, solid-state and optical storage.',
    bullets: [
      'HDD data is stored magnetically on spinning platters and read by read-write heads.',
      'The surface is organised into tracks and sectors.',
      'Latency is the delay while the required block rotates to the read-write head.',
      'Fragmentation can increase access time; defragmentation reorganises sectors.',
      'An HDD is a direct-access device, while data inside a selected sector is read sequentially.',
    ],
    richBlocks: [{
      kind: 'callout',
      tone: 'extension',
      title: 'Extension Activity 3A',
      text: 'Describe how ROM and RAM could be used in a microwave oven, refrigerator and remote-controlled model aeroplane.',
    }],
    visual: 'storage',
    accent: 'indigo',
    ...source(73, ['Figure 3.6 Tracks and sectors on a hard disk drive', 'Extension Activity 3A']),
  },
  {
    id: 'h3-311-ssd',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.1',
    eyebrow: 'SECONDARY STORAGE · SSD',
    title: 'Solid-state drives remove moving parts and reduce latency',
    lead: 'Hodder contrasts NAND-based flash storage with NOR-based EEPROM and explains why SSDs are fast, light and power-efficient.',
    richBlocks: [{
      kind: 'comparison',
      leftTitle: 'SSD advantages',
      rightTitle: 'Source caveats',
      rows: [
        ['No moving parts; more reliable', 'Endurance depends on write workload'],
        ['Lighter, thinner and cooler', 'Existing flash data must be erased before rewriting the same location'],
        ['Lower power consumption', 'EEPROM/NOR is faster but more expensive than NAND flash'],
        ['Faster data access', 'NAND works with blocks rather than single-byte erase/write'],
      ],
    }, {
      kind: 'callout',
      tone: 'extension',
      title: 'Extension Activity 3B',
      text: 'Investigate how HDD manufacturers handle shorter tracks nearer the centre of the disk while maintaining capacity and access performance.',
    }],
    visual: 'storage',
    accent: 'cyan',
    ...source(74, ['Solid state drives', 'Extension Activity 3B']),
  },
];

export const CHAPTER_3: Chapter3Lesson = {
  number: 3,
  level: 'AS Level',
  title: 'Hardware',
  subtitle: 'Computers and their components · Logic gates and logic circuits',
  subtopics: ['3.1 Computers and their components', '3.2 Logic gates and logic circuits'],
  sourceNote: 'Source-grounded from the connected Hodder 9618 Coursebook, printed pp.68–106. This first implementation batch covers pp.68–74; later pages remain explicitly unimplemented rather than inferred.',
  coverage: 'Opening source-complete batch: chapter objectives, prior knowledge, memory/storage structure, RAM/ROM families, DRAM/SRAM, embedded systems, HDD and SSD.',
  slides,
};
