import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 10 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_10_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h10-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 10 · DATA TYPES AND STRUCTURES',
    title: 'Choose suitable data types, organise related values, search and sort arrays, handle text files and reason about ADTs',
    lead: 'The chapter develops data organisation from basic and composite data types through arrays and files to stacks, queues and linked lists.',
    richBlocks: [{ kind: 'steps', title: 'Chapter route', items: [
      'Select and declare suitable basic data types.',
      'Define and use record types for related values of different types.',
      'Use 1D and 2D arrays with explicit lower and upper bounds.',
      'Trace linear search and bubble sort algorithms.',
      'Read, write and append text files in pseudocode.',
      'Explain and trace stack, queue and linked-list operations.',
    ] }],
    keyTerms: [
      { term: 'Data type', definition: 'A classification that determines the values an item can hold and how it can be used.' },
      { term: 'Record', definition: 'A composite data type containing related items that may have different data types.' },
      { term: 'Array', definition: 'A data structure containing several elements of the same data type.' },
      { term: 'Abstract data type (ADT)', definition: 'A collection of data together with the operations defined for that data.' },
    ],
    activity: { title: 'Prior knowledge check', prompt: 'Write pseudocode to input five numbers into an array and output the largest and smallest values.' },
    visual: 'types', accent: 'indigo', ...source(238, ['Chapter learning objectives', 'What you should already know', 'Chapter key terms', '10.1 Data types and records']),
  },
  {
    id: 'h10-1011-basic-types', section: '10.1 Data types and records', subtopicCode: '10.1.1', eyebrow: '10.1.1 · BASIC DATA TYPES · TABLE 10.1',
    title: 'A data type constrains the kind of value stored and the operations that make sense',
    lead: 'The source compares Boolean, character, date, integer, real and string data across pseudocode and the prescribed programming languages.',
    richBlocks: [{ kind: 'table', table: { caption: 'Basic data types to recognise', headers: ['Type', 'Use'], rows: [
      ['BOOLEAN', 'Logical true/false state'],
      ['CHAR', 'Single alphanumeric character'],
      ['DATE', 'A date value'],
      ['INTEGER', 'Positive or negative whole number'],
      ['REAL', 'Positive or negative number with a decimal point'],
      ['STRING', 'Sequence of alphanumeric characters'],
    ] } }],
    example: { title: 'Declaration pattern', lines: ['DECLARE <identifier> : <data type>', 'DECLARE myBirthday : DATE'] },
    activity: { title: 'Activities 10A–10B', prompt: 'Choose the most suitable type for a name, class size, race time, door state and birthday, then write declarations for the required values.' },
    visual: 'types', accent: 'cyan', ...source(239, ['Table 10.1 Basic data types', 'Activity 10A', 'Activity 10B', 'DECLARE statement']),
  },
  {
    id: 'h10-1012-records', section: '10.1 Data types and records', subtopicCode: '10.1.2', eyebrow: '10.1.2 · RECORDS · COMPOSITE DATA TYPES',
    title: 'A record groups a fixed set of related fields that do not have to share one data type',
    lead: 'The book example defines a user-defined book record containing text, integer and Boolean fields, then declares a variable of that record type.',
    richBlocks: [{ kind: 'code', title: 'Record-type pattern', lines: [
      'TYPE TbookRecord',
      '  DECLARE title : STRING',
      '  DECLARE author : STRING',
      '  DECLARE publisher : STRING',
      '  DECLARE noPages : INTEGER',
      '  DECLARE fiction : BOOLEAN',
      'ENDTYPE',
      'DECLARE Book : TbookRecord',
      'Book.author ← "David Watson"',
    ] }],
    activity: { title: 'Activity 10C', prompt: 'Define a student record containing name, date of birth, class and gender; declare myStudent and populate/output one sample student.' },
    visual: 'types', accent: 'emerald', ...source(240, ['10.1.2 Records', 'TbookRecord', 'Composite user-defined data type', 'Activity 10C']),
  },
  {
    id: 'h10-1021-1d-arrays', section: '10.2 Arrays', subtopicCode: '10.2.1', eyebrow: '10.2.1 · 1D ARRAYS · FIGURE 10.1',
    title: 'A 1D array stores same-type elements under one identifier and selects each value by index',
    lead: 'Figure 10.1 uses myList with nine integer elements indexed 0 to 8, making the lower and upper bounds explicit.',
    richBlocks: [
      { kind: 'table', table: { caption: 'Figure 10.1 myList', headers: ['Index', '0', '1', '2', '3', '4', '5', '6', '7', '8'], rows: [['Value', '27', '19', '36', '42', '16', '89', '21', '16', '55']] } },
      { kind: 'code', title: 'Declaration and access', lines: ['DECLARE myList : ARRAY[0:8] OF INTEGER', 'myList[7] ← 16'] },
    ],
    activity: { title: 'Activity 10D', prompt: 'Populate myList using a FOR … NEXT loop, then output all values. Check how your chosen language treats array bounds.' },
    visual: 'types', accent: 'indigo', ...source(241, ['Figure 10.1 Example of a 1D array', 'Lower bound', 'Upper bound', 'Index', 'Activity 10D']),
  },
  {
    id: 'h10-1022-2d-arrays', section: '10.2 Arrays', subtopicCode: '10.2.2', eyebrow: '10.2.2 · 2D ARRAYS · FIGURE 10.2',
    title: 'A 2D array adds a second index so row-and-column data can be addressed directly',
    lead: 'The source models a 9-row by 3-column integer table and shows both row and column bounds in the declaration.',
    richBlocks: [{ kind: 'code', title: '2D declaration and one element', lines: ['DECLARE myArray : ARRAY[0:8,0:2] OF INTEGER', 'myArray[7,0] ← 16'] }],
    bullets: [
      'The first index selects the row and the second selects the column.',
      'Nested FOR … NEXT loops can populate or traverse all elements.',
      'The chapter also asks learners to compare when arrays or records are the better structure.',
    ],
    activity: { title: 'Activities 10E–10F', prompt: 'Populate the 2D array with nested loops, then list three realistic uses for 1D arrays and three for 2D arrays. Decide where a record would be more appropriate.' },
    visual: 'types', accent: 'cyan', ...source(242, ['Figure 10.2 Example of a 2D array', 'Activity 10E', 'Extension 3D array', 'Activity 10F']),
  },
  {
    id: 'h10-1023-linear-search-core', section: '10.2 Arrays', subtopicCode: '10.2.3', eyebrow: '10.2.3 · LINEAR SEARCH',
    title: 'Linear search checks elements in order until the target is found or the upper bound is passed',
    lead: 'The source uses myList, a found flag and an index pointer so the loop can stop as soon as a match is detected.',
    richBlocks: [{ kind: 'steps', title: 'Source algorithm logic', items: [
      'Store lower and upper array bounds.',
      'Input the item to search for.',
      'Set found to FALSE and index to the lower bound.',
      'Compare item with myList[index].',
      'Set found to TRUE on a match; otherwise advance the index.',
      'Stop when found is TRUE or index passes the upper bound.',
    ] }],
    example: { title: 'Termination condition', lines: ['UNTIL (found = TRUE) OR (index > upperBound)'] },
    visual: 'recap', accent: 'emerald', ...source(243, ['10.2.3 Using a linear search', 'Linear-search pseudocode', 'found flag', 'upperBound/lowerBound']),
  },
  {
    id: 'h10-1023-linear-search-table', section: '10.2 Arrays', subtopicCode: '10.2.3', eyebrow: 'TABLE 10.2 · ACTIVITY 10G',
    title: 'An identifier table documents the purpose of every variable used by the search',
    lead: 'Table 10.2 records the item, array, bounds, current index and Boolean found flag so the search can be maintained or adapted later.',
    richBlocks: [{ kind: 'table', table: { caption: 'Linear-search identifiers', headers: ['Identifier', 'Purpose'], rows: [
      ['item', 'Integer value being searched for'],
      ['myList', 'Array being searched'],
      ['upperBound / lowerBound', 'Array limits'],
      ['index', 'Pointer to the current element'],
      ['found', 'Flag indicating whether the item has been located'],
    ] } }],
    activity: { title: 'Activity 10G', prompt: 'Extend the algorithm to output the index when a match is found. Populate Figure 10.1 data and search for 89 and 77.' },
    visual: 'recap', accent: 'amber', ...source(244, ['Table 10.2', 'Activity 10G', 'Extension repeated-item search']),
  },
  {
    id: 'h10-1024-bubble-algorithm', section: '10.2 Arrays', subtopicCode: '10.2.4', eyebrow: '10.2.4 · BUBBLE SORT · CORE ALGORITHM',
    title: 'Bubble sort compares adjacent elements and swaps them when they are in the wrong order',
    lead: 'After each pass, the largest remaining value reaches its final position, so the next pass can ignore one more element at the top end.',
    richBlocks: [{ kind: 'steps', title: 'Source algorithm pattern', items: [
      'Set top to the upper bound.',
      'Compare adjacent items from lowerBound to top - 1.',
      'Swap when myList[index] is greater than myList[index + 1].',
      'Use temp as temporary storage during a swap.',
      'Reduce top after each pass.',
      'Stop when no swap is made or the active range has only one element left.',
    ] }],
    example: { title: 'Stop condition', lines: ['UNTIL (NOT swap) OR (top = 0)'] },
    visual: 'recap', accent: 'rose', ...source(245, ['10.2.4 Using a bubble sort', 'Bubble-sort pseudocode', 'swap flag', 'temp', 'top']),
  },
  {
    id: 'h10-1024-bubble-passes-1-2', section: '10.2 Arrays', subtopicCode: '10.2.4', eyebrow: 'TABLE 10.3 · FIGURES 10.3–10.4',
    title: 'The first two passes show how the largest values settle at the right-hand end',
    lead: 'The source traces every comparison and swap using the same myList data and a shrinking top pointer.',
    richBlocks: [{ kind: 'table', table: { caption: 'Identifier roles', headers: ['Identifier', 'Purpose'], rows: [
      ['swap', 'Records whether a swap occurred in the current pass'],
      ['top', 'Index of the last element still needing comparison'],
      ['temp', 'Temporary storage during a swap'],
      ['index', 'Current comparison position'],
    ] } }],
    bullets: ['First pass: nine elements are involved and five swaps occur.', 'Second pass: eight elements remain active and three swaps occur.', 'The value already at the upper end is no longer reconsidered on later passes.'],
    visual: 'recap', accent: 'indigo', ...source(246, ['Table 10.3', 'Figure 10.3 first pass', 'Figure 10.4 second pass']),
  },
  {
    id: 'h10-1024-bubble-passes-3-5', section: '10.2 Arrays', subtopicCode: '10.2.4', eyebrow: 'FIGURES 10.5–10.7',
    title: 'Middle passes continue shrinking the active range while smaller values move left',
    lead: 'Figures 10.5, 10.6 and 10.7 make the repeated adjacent-comparison pattern visible and show the active top pointer moving toward the lower bound.',
    bullets: ['Third pass compares seven active elements.', 'Fourth pass compares six active elements.', 'Fifth pass compares five active elements.', 'Each completed pass fixes another high value in its final position.'],
    activity: { title: 'Trace task', prompt: 'Starting from the Figure 10.1 values, reproduce the list after the third, fourth and fifth passes and mark the top pointer after each pass.' },
    visual: 'recap', accent: 'cyan', ...source(247, ['Figure 10.5', 'Figure 10.6', 'Figure 10.7']),
  },
  {
    id: 'h10-1024-bubble-finish', section: '10.2 Arrays', subtopicCode: '10.2.4', eyebrow: 'FIGURES 10.8–10.10 · ACTIVITY 10H',
    title: 'The sort finishes when a pass makes no swaps',
    lead: 'The final figures trace the sixth, seventh and eighth passes; the eighth compares the last active pair and makes no swap, so the sorted list is complete.',
    example: { title: 'Final sorted list', lines: ['16, 16, 19, 21, 27, 36, 42, 55, 89'] },
    activity: { title: 'Activity 10H', prompt: 'Implement bubble sort in your chosen language using the Figure 10.1 sample data and output the completed sorted list.' },
    visual: 'recap', accent: 'emerald', ...source(248, ['Figure 10.8 sixth pass', 'Figure 10.9 seventh pass', 'Figure 10.10 eighth pass', 'Activity 10H']),
  },
  {
    id: 'h10-103-files', section: '10.3 Files', subtopicCode: '10.3', eyebrow: '10.3 · TEXT FILES · READ / WRITE / APPEND',
    title: 'Text files preserve data beyond one program run and are processed line by line in pseudocode',
    lead: 'The source introduces OPEN, READFILE, WRITEFILE, EOF and CLOSEFILE together with READ, WRITE and APPEND modes.',
    richBlocks: [{ kind: 'table', table: { caption: 'File operations', headers: ['Form', 'Purpose'], rows: [
      ['OPEN file FOR READ', 'Open an existing file for reading'],
      ['OPEN file FOR WRITE', 'Write a file; existing stored data is overwritten'],
      ['OPEN file FOR APPEND', 'Add new data at the end'],
      ['READFILE', 'Read one line into a STRING variable'],
      ['WRITEFILE', 'Write one STRING line'],
      ['EOF(file)', 'TRUE when end-of-file has been reached'],
      ['CLOSEFILE', 'Close a file after use'],
    ] } }],
    visual: 'files', accent: 'indigo', ...source(249, ['10.3 Files', 'OPEN', 'READ', 'WRITE', 'APPEND', 'READFILE', 'WRITEFILE', 'EOF', 'CLOSEFILE']),
  },
  {
    id: 'h10-103-file-routine-and-adt-intro', section: '10.3 Files', subtopicCode: '10.3', eyebrow: 'ACTIVITY 10I · TABLE 10.4 · 10.4 ADTs',
    title: 'A complete file routine writes until a blank line, closes, reopens for reading and continues until EOF',
    lead: 'The source then transitions to abstract data types: each ADT combines stored data with a defined set of operations.',
    richBlocks: [
      { kind: 'steps', title: 'File routine sequence', items: ['Open for WRITE.', 'Input lines until the blank-line sentinel is entered.', 'Write non-empty lines.', 'Close the file.', 'Open for READ.', 'Read and output lines until EOF.', 'Close again.'] },
      { kind: 'comparison', leftTitle: 'Stack', rightTitle: 'Queue', rows: [['Last in, first out (LIFO)', 'First in, first out (FIFO)'], ['push / pop', 'enqueue / dequeue']] },
    ],
    activity: { title: 'Activity 10I', prompt: 'Extend the routine so further lines can be appended to the existing file, then implement the routine in your chosen programming language.' },
    visual: 'files', accent: 'cyan', ...source(250, ['Activity 10I', 'Table 10.4', '10.4 Abstract data types', 'Table 10.5 uses of stacks/queues/linked lists']),
  },
  {
    id: 'h10-104-pointers', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4', eyebrow: 'FIGURES 10.11–10.12 · POINTERS',
    title: 'Pointers define where each ADT begins, ends and links to the next item',
    lead: 'Stacks, queues and linked lists all use pointers, but the pointers represent different structural roles.',
    richBlocks: [{ kind: 'table', table: { caption: 'Pointer roles', headers: ['ADT', 'Pointers'], rows: [
      ['Stack', 'basePointer points to the first item; topPointer points to the last item'],
      ['Queue', 'frontPointer points to the first item; rearPointer points to the last item'],
      ['Linked list', 'startPointer points to the first node; every node stores a pointer to the next node; the final pointer is null'],
    ] } }],
    bullets: ['When stack base and top pointers are equal, there is one item.', 'When queue front and rear pointers are equal, there is one item.', 'A linked-list node combines an item with its link to the next item.'],
    visual: 'types', accent: 'amber', ...source(251, ['Figure 10.11 Stack and queue', 'Figure 10.12 Linked list', 'Pointer roles', 'Node', 'Null pointer']),
  },
  {
    id: 'h10-1041-stack', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4.1', eyebrow: '10.4.1 · STACK OPERATIONS · FIGURE 10.13',
    title: 'Push moves the top pointer upward; pop returns the top item and moves the pointer downward',
    lead: 'The base pointer stays fixed. Because the implementation uses a finite array, the algorithm must detect both full and empty states.',
    richBlocks: [{ kind: 'steps', title: 'Source push/pop logic', items: [
      'Initialise basePointer, topPointer and stack capacity.',
      'Push: check capacity, increment topPointer, then store the new item.',
      'Pop: detect an empty stack, otherwise copy the top item and decrement topPointer.',
      'Report an error instead of reading beyond an empty stack or writing beyond a full stack.',
    ] }],
    activity: { title: 'Activity 10J', prompt: 'Trace the supplied stack after one pop, then pushing 67 followed by 92. Show the final values of topPointer and basePointer.' },
    visual: 'types', accent: 'rose', ...source(252, ['Figure 10.13 stack pop/push', 'Stack setup pseudocode', 'Stack full/empty checks', 'Activity 10J']),
  },
  {
    id: 'h10-1042-queue-circular', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4.2', eyebrow: '10.4.2 · QUEUE OPERATIONS · FIGURES 10.14–10.15',
    title: 'A finite array queue is managed as circular so unused positions can be reused without shifting every item',
    lead: 'Dequeue advances frontPointer; enqueue advances rearPointer. When a pointer reaches the upper bound it wraps to the lower bound.',
    bullets: [
      'The queue is FIFO: the oldest item is removed first.',
      'frontPointer changes after dequeue.',
      'rearPointer changes after enqueue.',
      'queueLength tracks the number of items currently stored.',
      'Circular wrap-around avoids moving all remaining items after every dequeue.',
    ],
    visual: 'types', accent: 'indigo', ...source(253, ['Figure 10.14 queue operations', 'Figure 10.15 circular queue operation', 'Circular queue', 'frontPointer', 'rearPointer']),
  },
  {
    id: 'h10-1042-queue-pseudocode', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4.2', eyebrow: 'QUEUE SETUP · ENQUEUE · DEQUEUE',
    title: 'Queue pseudocode combines capacity, wrap-around and queue-length checks',
    lead: 'The source sets up a 10-element queue and uses conditional pointer updates so the rear and front pointers wrap around correctly.',
    richBlocks: [{ kind: 'steps', title: 'Enqueue / dequeue decisions', items: [
      'Enqueue only when queueLength is below capacity.',
      'Advance rearPointer or wrap it to 1 when it has reached the upper bound.',
      'Store the new item and increase queueLength.',
      'Dequeue only when queueLength is not zero.',
      'Read the item at frontPointer, advance or wrap the front pointer, then reduce queueLength.',
    ] }],
    visual: 'types', accent: 'cyan', ...source(254, ['Queue setup pseudocode', 'Enqueue pseudocode', 'Dequeue pseudocode', 'queueLength', 'upperBound']),
  },
  {
    id: 'h10-1043-linked-list-start', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4.3', eyebrow: 'ACTIVITY 10K · 10.4.3 LINKED LIST OPERATIONS · FIGURE 10.16',
    title: 'A linked list can use two arrays: one for data and one for next-node pointers, plus a heap of free locations',
    lead: 'The source begins with an empty list: startPointer is -1 and heapPointer identifies the first free array position.',
    bullets: [
      'The list has finite capacity because the underlying arrays are finite.',
      'Removed positions must be managed so they can be reused.',
      'The free positions form a second linked list usually called the heap.',
      'Figure 10.16 initialises the pointer array so each free position points to the next free position.',
    ],
    activity: { title: 'Activity 10K', prompt: 'Before the linked-list section, trace the supplied circular queue after three removals and then enqueuing 25 followed by 75.' },
    visual: 'types', accent: 'emerald', ...source(255, ['Activity 10K', '10.4.3 Linked list operations', 'Figure 10.16 empty linked list and heap', 'heapPointer']),
  },
  {
    id: 'h10-1043-add-first-two', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4.3', eyebrow: 'FIGURES 10.17–10.18 · ADDING NODES',
    title: 'Adding to the start consumes one heap node and links it to the previous start',
    lead: 'The source first inserts 37, then inserts 45 at the front. Each insertion updates startPointer and advances heapPointer to the next free node.',
    richBlocks: [{ kind: 'steps', title: 'Front insertion pattern', items: [
      'Take the free location indicated by heapPointer.',
      'Store the new data in that array location.',
      'Make the new node point to the old start of the list.',
      'Set startPointer to the newly used location.',
      'Advance heapPointer using the free-list pointer that was stored in that location.',
    ] }],
    visual: 'types', accent: 'amber', ...source(256, ['Figure 10.17 add 37', 'Figure 10.18 add 45', 'startPointer', 'heapPointer', 'Node pointer']),
  },
  {
    id: 'h10-1043-add-third-setup', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4.3', eyebrow: 'FIGURE 10.19 · LINKED-LIST INITIALISATION',
    title: 'The third insertion repeats the same pointer pattern; setup creates the free-list chain in advance',
    lead: 'After adding 12, the source gives pseudocode that initialises the data array, pointer array, start pointer and heap start pointer.',
    example: { title: 'Initialisation ideas', lines: ['heapStartPointer ← 0', 'startPointer ← -1', 'FOR index ← 0 TO 11', '  myLinkedListPointers[index] ← index + 1', 'NEXT index', 'myLinkedListPointers[11] ← -1'] },
    bullets: ['startPointer = -1 denotes an empty linked list.', 'The last free-list pointer is -1 because there is no next free node.', 'The pointer array provides both list links and heap links depending on which locations are in use.'],
    visual: 'types', accent: 'indigo', ...source(257, ['Figure 10.19 add 12', 'Linked-list setup pseudocode', 'startPointer = -1', 'heapStartPointer']),
  },
  {
    id: 'h10-1043-identifiers-activity', section: '10.4 Abstract data types (ADTs)', subtopicCode: '10.4.3', eyebrow: 'TABLES 10.6–10.7 · ACTIVITY 10L',
    title: 'The linked-list identifier table separates stored data, link data and the pointers controlling used/free nodes',
    lead: 'Table 10.7 then shows the empty structure explicitly so learners can trace changes when nodes are removed and added.',
    richBlocks: [{ kind: 'table', table: { caption: 'Linked-list identifiers', headers: ['Identifier', 'Role'], rows: [
      ['myLinkedList', 'Array holding list data'],
      ['myLinkedListPointers', 'Array holding next-node pointers'],
      ['startPointer', 'Start of the used linked list'],
      ['heapStartPointer', 'Start of the free-list heap'],
      ['index', 'Current array position while initialising/tracing'],
    ] } }],
    activity: { title: 'Activity 10L', prompt: 'Trace removal of 37 from the supplied linked list, then add 18 followed by 75. Show the final list, startPointer and heapPointer.' },
    visual: 'types', accent: 'cyan', ...source(258, ['Table 10.6', 'Table 10.7', 'Activity 10L', 'Extension stack/queue implementation']),
  },
  {
    id: 'h10-review-core', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS 1–5',
    title: 'The first review combines ADT definitions, records, queue reversal, text-file processing and bubble-sort efficiency',
    lead: 'These tasks integrate the chapter rather than asking only for definitions.',
    richBlocks: [{ kind: 'steps', title: 'Review focus', items: [
      'Explain stack, queue and linked list.',
      'Explain a composite data type with an example.',
      'Use diagrams to explain reversing a queue using a stack.',
      'Write file pseudocode for one-record-per-line storage, append, find/delete and output-all operations.',
      'Analyse and improve a bubble sort that makes unnecessary comparisons.',
    ] }],
    activity: { title: 'Exam-style retrieval', prompt: 'For each of the five review areas, identify the key operation or invariant that your answer must mention before you begin writing.' },
    visual: 'recap', accent: 'rose', ...source(259, ['End-of-chapter questions 1–5', 'TstudentRecord', 'Bubble-sort improvement task']),
  },
  {
    id: 'h10-review-queue-linked-list', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTION 6 · QUEUE AS LINKED LIST',
    title: 'A queue can be implemented as linked nodes while still preserving FIFO behaviour',
    lead: 'The review sequence creates a queue, adds several names, removes names and asks learners to label the resulting linked-node state.',
    richBlocks: [{ kind: 'steps', title: 'Operation sequence to trace', items: ['CreateQueue', 'Add Ali', 'Add Jack', 'Add Ben', 'Add Ahmed', 'Remove one', 'Add Jatinder', 'Remove one'] }],
    activity: { title: 'Trace the final state', prompt: 'Use FIFO order to determine which names remain and in what linked-node order after the complete sequence.' },
    visual: 'types', accent: 'indigo', ...source(260, ['End-of-chapter question 6a', 'Queue ADT as linked list', 'CreateQueue/AddName/RemoveName sequence']),
  },
  {
    id: 'h10-review-node-record', section: 'Chapter review', eyebrow: 'QUESTION 6(b)(i) · NODE RECORD + FREE LIST',
    title: 'The queue implementation uses Node records plus HeadPointer, TailPointer and FreePointer',
    lead: 'The source declares an array of Node records and asks learners to complete the pointer state immediately after CreateQueue.',
    richBlocks: [{ kind: 'code', title: 'Node structure', lines: ['TYPE Node', '  DECLARE Name : STRING', '  DECLARE Pointer : INTEGER', 'ENDTYPE', 'DECLARE Queue : ARRAY[1:10] OF Node'] }],
    bullets: ['HeadPointer identifies the first queue node.', 'TailPointer identifies the last queue node.', 'FreePointer identifies the first free node available for reuse.'],
    visual: 'types', accent: 'cyan', ...source(261, ['Question 6(b)(i)', 'Node record', 'Queue array of Node', 'HeadPointer', 'TailPointer', 'FreePointer']),
  },
  {
    id: 'h10-review-addname', section: 'Chapter review', eyebrow: 'QUESTION 6(b)(ii) · AddName PROCEDURE',
    title: 'AddName consumes a node from the free list, stores the name and makes that node the new tail',
    lead: 'The supplied procedure shows the pointer-management pattern and provides the identifier table needed for the companion RemoveName task.',
    richBlocks: [{ kind: 'steps', title: 'AddName pointer changes', items: [
      'Reject the operation if FreePointer is zero.',
      'Take CurrentPointer from FreePointer.',
      'Store NewName in the selected node.',
      'Advance FreePointer using the selected node’s old pointer.',
      'Set HeadPointer if this is the first queue item.',
      'Set the new node pointer to zero and update TailPointer.',
    ] }],
    visual: 'types', accent: 'emerald', ...source(262, ['Question 6(b)(ii)', 'AddName procedure', 'Identifier table', 'CurrentPointer']),
  },
  {
    id: 'h10-review-removename', section: 'Chapter review', eyebrow: 'QUESTION 6(b)(ii) · COMPLETE RemoveName',
    title: 'RemoveName must update the queue head, handle the one-item case and return the released node to the free list',
    lead: 'The final printed task is a partially completed pseudocode procedure. The learning target is pointer reasoning, not memorising one code listing.',
    richBlocks: [{ kind: 'steps', title: 'Required reasoning', items: [
      'Detect and report an empty queue.',
      'Output the name stored at the head node.',
      'Store the old head in CurrentPointer.',
      'Advance HeadPointer to the next linked node.',
      'If the queue has become empty, update TailPointer appropriately.',
      'Link the released node back into the free-list chain and update FreePointer.',
    ] }],
    activity: { title: 'Complete the procedure', prompt: 'Fill the missing pseudocode statements using only the variables in the source identifier table, then trace one removal from a two-item queue.' },
    visual: 'recap', accent: 'amber', ...source(263, ['Question 6(b)(ii) RemoveName', 'Free-list reinsertion', 'Cambridge 9608 Paper 41 Q6 June 2015']),
  },
];

export const CHAPTER_10_FINAL: HodderLessonChapter = {
  number: 10,
  level: 'AS Level',
  title: 'Data types and structures',
  subtitle: 'Basic and composite data types · arrays · searching and sorting · files · stacks, queues and linked lists',
  subtopics: ['10.1 Data types and records', '10.2 Arrays', '10.3 Files', '10.4 Abstract data types (ADTs)'],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 Chapter 10 in the connected full coursebook, printed pp.238–263. Every printed chapter page is represented in slide provenance and the source examples, activities, figures, identifier tables and ADT pointer logic are preserved as teaching paraphrase.',
  coverage: '26/26 printed chapter pages represented (pp.238–263): basic data types and declarations; records; 1D/2D arrays; linear search; bubble sort with all traced passes; text-file READ/WRITE/APPEND handling; stack, circular queue and linked-list pointer models; source activities 10A–10L; and the complete end-of-chapter review route including the older 9608 linked-list queue exercise.',
  slides: CHAPTER_10_DEEP_SLIDES,
};
