import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 15 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_15_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h15-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 15 · HARDWARE',
    title: 'Processor architecture, parallel processing and digital logic',
    lead: 'The chapter develops RISC/CISC, pipelining and parallel architectures before moving to Boolean algebra, adders, flip-flops and Karnaugh maps.',
    bullets: ['RISC and CISC', 'Pipelining and interrupts', 'SISD, SIMD, MISD and MIMD', 'Boolean algebra and De Morgan’s Laws', 'Half/full adders', 'SR/JK flip-flops', 'Karnaugh maps'],
    visual: 'recap', accent: 'indigo', ...source(346, ['Chapter objectives', '15.1 prior knowledge']),
  },
  {
    id: 'h15-1511-risc-cisc', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: '15.1.1 · RISC AND CISC',
    title: 'CISC uses complex instructions; RISC uses a smaller optimised instruction set',
    lead: 'CISC aims to reduce the number of assembly statements, while RISC breaks work into simpler single-cycle instructions.',
    bullets: ['CISC: more instruction formats and complex multi-cycle work.', 'RISC: fewer simpler instructions and emphasis on execution speed.', 'Source example contrasts one complex ADD with LOAD/LOAD/ADD/STORE.'],
    visual: 'types', accent: 'cyan', ...source(347, ['CISC', 'RISC', 'ADD A,B example']),
  },
  {
    id: 'h15-1511-comparison-pipeline', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: 'TABLE 15.1 · PIPELINING',
    title: 'RISC features make pipelining easier to implement',
    lead: 'Table 15.1 compares instruction formats, addressing modes, cycle counts, instruction length, decoding and pipeline suitability.',
    bullets: ['CISC commonly uses multi-cycle variable-length instructions.', 'RISC commonly uses single-cycle fixed-length instructions.', 'Pipeline stages introduced: instruction fetch, instruction decode, operand fetch, instruction execution and writeback.'],
    visual: 'recap', accent: 'emerald', ...source(348, ['Table 15.1', 'Pipelining', 'instruction fetch', 'writeback', 'Extension Activity 15A']),
  },
  {
    id: 'h15-1511-pipeline-interrupt', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: 'FIGURE 15.1 · PIPELINE + INTERRUPTS',
    title: 'Pipelining overlaps stages from several instructions',
    lead: 'The source example completes six five-stage instructions in 10 clock cycles rather than 30 sequential cycles.',
    bullets: ['Registers store intermediate stages.', 'Several instructions can be in progress at once.', 'Interrupt handling must account for instructions already in the pipeline.'],
    visual: 'recap', accent: 'amber', ...source(349, ['Figure 15.1', '10 versus 30 cycles', 'Interrupts']),
  },
  {
    id: 'h15-1512-sisd-simd', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'SISD + SIMD',
    title: 'SISD is sequential; SIMD performs the same instruction on many data values',
    lead: 'The source uses image-brightness processing to show how SIMD can apply one calculation to many independent pixels at the same time.',
    bullets: ['SISD: one processor, one instruction stream, one data source.', 'SIMD: many processors, same instruction, different data.', 'SIMD applications include graphics and sound sampling.'],
    visual: 'types', accent: 'indigo', ...source(350, ['Figure 15.2 SISD', 'Figure 15.3 SIMD', 'pixel brightness']),
  },
  {
    id: 'h15-1512-misd-mimd', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'MISD + MIMD',
    title: 'MISD shares data across different instructions; MIMD gives processors independent work',
    lead: 'MISD is uncommon; MIMD is used in multicore systems and supercomputers.',
    bullets: ['MISD: several processors, different instructions, shared data.', 'MIMD: several processors with independently selected instructions and data.', 'Parallel systems need processor communication and suitable software.', 'Parallel processing can reduce the Von Neumann bottleneck but costs more hardware.'],
    visual: 'types', accent: 'cyan', ...source(351, ['Figure 15.4 MISD', 'Figure 15.5 MIMD', 'Von Neumann bottleneck']),
  },
  {
    id: 'h15-1512-cluster-massive', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'CLUSTER · MASSIVELY PARALLEL',
    title: 'Clusters network computers; massively parallel systems link many processors as one machine',
    lead: 'Massively parallel computers divide large scientific or mathematical workloads across thousands of processors connected by data pathways.',
    bullets: ['Cluster computers remain largely independent.', 'Massively parallel processors cooperate as parts of one large machine.', 'Interconnected data pathways support communication.'],
    visual: 'recap', accent: 'emerald', ...source(352, ['Cluster', 'Massively parallel', 'Figure 15.6']),
  },
  {
    id: 'h15-151-activity', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'ACTIVITY 15A · EXTENSION 15B',
    title: 'Section review combines architecture comparison with pipeline tracing',
    lead: 'Activity 15A reviews RISC/CISC, the Von Neumann bottleneck, cluster versus massive parallelism and a six-instruction pipeline.',
    activity: { title: 'Activity 15A', prompt: 'Trace LOAD A, LOAD B, LOAD C, ADD A,B,C, STORE D and OUT D through a pipeline and compare with sequential execution.' },
    visual: 'recap', accent: 'rose', ...source(353, ['Activity 15A', 'Extension Activity 15B', 'Figure 15.7']),
  },
  {
    id: 'h15-1521-boolean-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.1', eyebrow: '15.2.1 · BOOLEAN ALGEBRA',
    title: 'Boolean algebra represents logic using TRUE (1) and FALSE (0)',
    lead: 'The source refreshes truth tables and logic circuits and introduces combination/sequential circuits, adders, flip-flops, sum of products, Gray code and Karnaugh maps.',
    keyTerms: [
      { term: 'Sum of products', definition: 'AND product terms combined by OR.' },
      { term: 'Gray code', definition: 'Ordering where adjacent binary values differ by one bit.' },
      { term: 'Karnaugh map', definition: 'A Gray-code-based method for simplifying Boolean logic.' },
    ],
    visual: 'types', accent: 'indigo', ...source(354, ['15.2 prior knowledge', 'Boolean algebra', 'Gray code', 'Karnaugh maps']),
  },
  {
    id: 'h15-1521-laws', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.1', eyebrow: 'TABLES 15.2–15.3 · DE MORGAN',
    title: 'Boolean identities and De Morgan’s Laws simplify equivalent logic',
    lead: 'The source lists commutative, associative, distributive, idempotent, identity, null, inverse and absorption laws and proves De Morgan’s Laws with truth tables.',
    bullets: ['NOT(A AND B) = (NOT A) OR (NOT B).', 'NOT(A OR B) = (NOT A) AND (NOT B).', 'Equivalent truth-table columns prove the identities.'],
    visual: 'types', accent: 'cyan', ...source(355, ['Table 15.2', 'Table 15.3', 'De Morgan', 'Example 15.1']),
  },
  {
    id: 'h15-1521-half-adder', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'ACTIVITY 15B · HALF ADDER',
    title: 'A half adder adds two input bits and outputs Sum and Carry',
    lead: 'The source follows Boolean simplification with the half-adder truth table and its logic circuit.',
    bullets: ['Inputs A and B.', 'Outputs S (sum) and C (carry).', 'For 1 + 1, sum is 0 and carry is 1.'],
    activity: { title: 'Activity 15B', prompt: 'Simplify the source Boolean expressions and show each algebraic stage.' },
    visual: 'types', accent: 'emerald', ...source(356, ['Activity 15B', 'Table 15.4', 'Figure 15.10', 'half adder']),
  },
  {
    id: 'h15-1522-full-adder-build', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'FULL ADDER · FIGURES 15.11–15.13',
    title: 'A full adder accepts A, B and carry-in for multi-bit binary addition',
    lead: 'The source combines two half adders and an OR stage so carry from the previous bit position can be included.',
    bullets: ['Inputs A, B and Cin.', 'Outputs Sum and Cout.', 'One implementation uses XOR, AND and OR gates.'],
    visual: 'recap', accent: 'amber', ...source(357, ['Figure 15.11', 'Figure 15.12', 'Figure 15.13', 'full adder']),
  },
  {
    id: 'h15-1522-full-adder-truth', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'TABLE 15.5 · FIGURE 15.14',
    title: 'Full adders chain together to add wider binary values',
    lead: 'Table 15.5 lists all eight input combinations; Figure 15.14 chains four full adders to add two 4-bit values.',
    activity: { title: 'Activity 15C', prompt: 'Construct half- and full-adder circuits using NAND gates only and verify their truth tables.' },
    visual: 'types', accent: 'indigo', ...source(358, ['Table 15.5', 'Figure 15.14', 'Activity 15C', 'SR flip-flop introduction']),
  },
  {
    id: 'h15-1523-sr', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'SR FLIP-FLOP · TABLE 15.6',
    title: 'Cross-coupled NOR gates allow an SR flip-flop to remember one bit',
    lead: 'The source traces set/reset states and shows how cross-coupling creates positive feedback.',
    bullets: ['S means set and R means reset.', 'Q and NOT Q normally complement each other.', 'S=0,R=0 keeps the remembered state.', 'Cross-coupling supplies positive feedback.'],
    visual: 'recap', accent: 'cyan', ...source(359, ['Figures 15.15–15.17', 'Table 15.6', 'SR flip-flop']),
  },
  {
    id: 'h15-1523-jk-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'SR INVALID STATE → JK',
    title: 'JK adds clocked control to avoid the illegal SR condition',
    lead: 'The source identifies S=1,R=1 as invalid for the SR design and introduces JK with a clock and additional gates.',
    bullets: ['SR can store one bit and contribute to RAM.', 'JK synchronises changes with a clock.', 'JK supports no change and toggle as controlled states.'],
    visual: 'types', accent: 'rose', ...source(360, ['SR invalid state', 'RAM', 'JK flip-flop', 'Figure 15.18']),
  },
  {
    id: 'h15-1523-jk-uses', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'TABLE 15.7 · JK USES',
    title: 'JK behaviour supports shift registers and binary counters',
    lead: 'J=K=0 preserves state, one active input sets or resets Q, and J=K=1 toggles after the clock pulse.',
    bullets: ['Several JK flip-flops can form shift registers.', 'Toggle behaviour can be used to make a binary counter.', 'Section 15.2.4 then converts circuits and truth tables into Boolean expressions.'],
    visual: 'types', accent: 'emerald', ...source(361, ['Table 15.7', 'shift registers', 'binary counters', '15.2.4']),
  },
  {
    id: 'h15-1524-circuit-expression', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.4', eyebrow: 'EXAMPLES 15.3–15.4 · SUM OF PRODUCTS',
    title: 'Derive Boolean expressions either stage-by-stage from a circuit or from output-1 truth-table rows',
    lead: 'The source demonstrates circuit-first substitution and truth-table-first sum of products, followed by Boolean simplification.',
    bullets: ['Label intermediate gate results.', 'For SoP, select rows where output = 1.', 'Write one AND product per selected row.', 'OR the products and simplify.'],
    visual: 'recap', accent: 'amber', ...source(362, ['Example 15.3', 'Example 15.4', 'Table 15.8', 'sum of products']),
  },
  {
    id: 'h15-1525-kmap-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: '15.2.5 · K-MAPS',
    title: 'Karnaugh maps simplify Boolean expressions visually',
    lead: 'Example 15.5 starts from the NAND truth table and places output-1 combinations into a Gray-code-ordered map.',
    activity: { title: 'Activity 15D', prompt: 'Produce simplified Boolean expressions for the source circuits in Figures 15.21 and 15.22.' },
    visual: 'recap', accent: 'indigo', ...source(363, ['Example 15.5', 'Activity 15D', 'Gray code']),
  },
  {
    id: 'h15-1525-kmap-rules', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'K-MAP RULES',
    title: 'Group adjacent 1s as broadly as possible and retain only variables that stay constant',
    lead: 'The source lists Gray-code ordering, grouping, overlap and edge-wrap rules.',
    bullets: ['Use Gray-code order.', 'Group only cells containing 1.', 'Use the largest valid groups.', 'Groups can overlap and wrap around edges.', 'Single cells are allowed when necessary.', 'A simplified term contains only variables constant in the group.'],
    visual: 'recap', accent: 'cyan', ...source(364, ['Figure 15.23', 'Karnaugh map rules']),
  },
  {
    id: 'h15-1525-kmap-3var', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'EXAMPLE 15.6 · THREE-VARIABLE K-MAP',
    title: 'A three-variable K-map can replace several minterms with simpler grouped terms',
    lead: 'The source groups four output-1 cells and obtains the simplified expression A.C + B.C + A.B.',
    visual: 'recap', accent: 'emerald', ...source(365, ['Example 15.6', 'A.C + B.C + A.B']),
  },
  {
    id: 'h15-1525-kmap-4var', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'EXAMPLE 15.7 · FOUR-VARIABLE K-MAP',
    title: 'Four-variable K-maps remove changing variables through larger groups',
    lead: 'The source maps output-1 combinations on two Gray-code axes and simplifies by choosing large valid groups.',
    bullets: ['Both axes use Gray-code order.', 'Large groups produce fewer literals.', 'The map remains logically equivalent to the original truth table.'],
    visual: 'recap', accent: 'amber', ...source(366, ['Example 15.7', 'Four-variable K-map', 'SoP']),
  },
  {
    id: 'h15-1525-kmap-wrap', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'FIGURES 15.19–15.22 · WRAP-AROUND',
    title: 'Opposite K-map edges are adjacent',
    lead: 'The source demonstrates vertical/horizontal wrap-around and four-corner grouping.',
    bullets: ['Opposite edge columns can form one group.', 'The four corners can be one group.', 'Different valid groups may overlap.', 'Only variables constant throughout a group remain.'],
    visual: 'recap', accent: 'rose', ...source(367, ['Figures 15.19–15.22', 'wrap-around', 'corner groups']),
  },
  {
    id: 'h15-activity-15e', section: 'Chapter review', eyebrow: 'ACTIVITY 15E · END-OF-CHAPTER START',
    title: 'The final activity integrates expressions, truth tables, K-maps and circuits',
    lead: 'Learners construct truth tables and K-maps, derive simplified expressions and then draw efficient circuits.',
    activity: { title: 'Activity 15E', prompt: 'Take one source expression through truth table, K-map, simplified Boolean expression and final circuit.' },
    visual: 'recap', accent: 'indigo', ...source(368, ['Activity 15E', 'End of chapter questions']),
  },
  {
    id: 'h15-review-boolean-sr', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER · BOOLEAN + SR',
    title: 'Review: K-map derivation, Boolean simplification and SR states',
    lead: 'The page asks learners to derive a K-map from a four-input truth table, simplify expressions and complete/explain an SR flip-flop table.',
    visual: 'recap', accent: 'cyan', ...source(369, ['Review questions 2–3a', 'K-map', 'SR flip-flop']),
  },
  {
    id: 'h15-review-parallel-jk', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER · JK + PARALLEL',
    title: 'Review: JK, parallel architectures and pipelining',
    lead: 'The source reviews JK inputs/uses, SISD/SIMD/MISD/MIMD, massively parallel design and pipeline clock-cycle comparisons.',
    bullets: ['This printed page includes material adapted from Cambridge 9608 Paper 32 Q4 November 2015.', 'It remains coursebook review, not current live 9618 Past Paper practice.'],
    visual: 'recap', accent: 'emerald', ...source(370, ['Review questions 3b–5', '9608 Paper 32 Q4 November 2015']),
  },
  {
    id: 'h15-review-circuit-kmap', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTION 6',
    title: 'Review: circuit → Boolean expression → truth table → K-map → simplified SoP',
    lead: 'The final task asks for a circuit expression, complete truth table, K-map grouping and an algebraic simplification using an identity and De Morgan’s Laws.',
    bullets: ['The printed question is adapted from Cambridge 9608 Paper 32 Q3 June 2017.', 'It remains source-backed coursebook review rather than live 9618 practice.'],
    visual: 'recap', accent: 'amber', ...source(371, ['Review question 6', '9608 Paper 32 Q3 June 2017']),
  },
];

export const CHAPTER_15_FINAL: HodderLessonChapter = {
  number: 15,
  level: 'A Level',
  title: 'Hardware',
  subtitle: 'RISC/CISC and pipelining · parallel architectures · Boolean algebra · adders · flip-flops · Karnaugh maps',
  subtopics: ['15.1 Processors and parallel processing', '15.2 Boolean algebra and logic circuits'],
  sourceNote: 'Deep source-backed teaching route from the uploaded Hodder 9618 Chapter 15, printed pp.346–371. Every printed chapter page is represented in slide provenance and the source sequence, figures, examples, activities and terminology are preserved as teaching paraphrase.',
  coverage: '26/26 printed chapter pages represented (pp.346–371): RISC/CISC, pipeline stages and interrupts; SISD/SIMD/MISD/MIMD, clusters and massively parallel systems; Boolean laws and De Morgan; half/full adders; SR/JK flip-flops; circuit/truth-table/SoP conversion; K-map rules, grouping and wrap-around; activities and end-of-chapter review.',
  slides: CHAPTER_15_DEEP_SLIDES,
};
