import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const pageRange = (start: number, end: number) => Array.from({ length: end - start + 1 }, (_, index) => start + index);
const source = (start: number, end: number = start, elements: string[] = []) => ({
  sourcePages: pageRange(start, end),
  sourceLabel: `Hodder Chapter 20 · pp.${start}${end === start ? '' : `–${end}`}`,
  sourceElements: [`Hodder pp.${start}${end === start ? '' : `–${end}`}`, ...elements],
});

export const CHAPTER_20_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h20-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 20 · FURTHER PROGRAMMING',
    title: 'The final chapter connects programming paradigms with advanced file processing and robust exception handling',
    lead: 'The source compares low-level, imperative, object-oriented and declarative programming before applying record-oriented file operations and exception handling in complete programs.',
    bullets: [
      'Compare four programming paradigms and identify where each is useful.',
      'Use OOP terminology and implementation patterns: classes, objects, data hiding, inheritance, polymorphism, overloading, containment and object lifecycle methods.',
      'Use Prolog-style facts, rules and queries as a declarative-programming model.',
      'Store and retrieve records from serial, sequential and random files.',
      'Use hashing and random access to locate records efficiently.',
      'Trap predictable exceptional conditions so programs fail safely or continue in a controlled way.',
    ],
    visual: 'recap', accent: 'indigo', ...source(498, 499, ['Chapter objectives', 'Programming-paradigm key terms', 'File-processing/exception key terms']),
  },
  {
    id: 'h20-2011-low-level', section: '20.1 Programming paradigms', subtopicCode: '20.1.1', eyebrow: '20.1.1 · LOW-LEVEL PROGRAMMING',
    title: 'Low-level programming exposes the processor’s basic instruction set, registers and addresses directly',
    lead: 'Assembly language and machine code use low-level instructions; the source gives a printer driver as an example where direct control of addresses and registers can be important.',
    bullets: [
      'The paradigm works close to the computer’s instruction set rather than hiding hardware details behind high-level abstractions.',
      'Addressing modes determine how an instruction obtains its operand or effective address.',
      'Chapter 20 explicitly sends learners back to the Chapter 4 addressing-mode material before its low-level activity.',
    ],
    activity: { title: 'Activity 20A', prompt: 'Use the supplied memory values and the source addressing-mode rules to determine what values the assembly-language instructions access. Explain each step rather than giving only the final value.' },
    visual: 'types', accent: 'cyan', ...source(499, 500, ['Low-level programming', 'Addressing modes review', 'Activity 20A']),
  },
  {
    id: 'h20-2012-imperative', section: '20.1 Programming paradigms', subtopicCode: '20.1.2', eyebrow: '20.1.2 · IMPERATIVE → STRUCTURED PROGRAMMING',
    title: 'Imperative programming states actions in execution order; structured programming organises those actions into clearer modules',
    lead: 'The source presents imperative programming as a sequence of required steps and then links it to structured programming with procedures, functions and more disciplined variable scope.',
    bullets: [
      'The programmer explicitly specifies what operation happens next.',
      'For small programs this direct sequence can be simple to read and understand.',
      'As a program grows, procedures and functions provide a more logical structure than one long sequence using only global variables.',
      'The section points back to Chapter 11 structured programming before Activity 20B.',
    ],
    activity: { title: 'Activity 20B', prompt: 'Write the five-shape area algorithm first as basic imperative pseudocode with no procedures/functions and only global variables, then rewrite it in a more structured form and compare the two designs.' },
    visual: 'types', accent: 'emerald', ...source(500, 500, ['Imperative programming', 'Structured programming link', 'Activity 20B', 'Shape class diagram']),
  },
  {
    id: 'h20-2013-oop-foundations', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: '20.1.3 · OOP · CLASS · OBJECT · METHOD · ATTRIBUTE',
    title: 'Object-oriented programming groups state and behaviour inside communicating objects',
    lead: 'The source defines OOP as a methodology using self-contained objects that contain data and methods, and notes that Java, Python and Visual Basic can support procedural and object-oriented styles.',
    keyTerms: [
      { term: 'Class', definition: 'A template defining the methods and data of a certain type of object.' },
      { term: 'Attribute', definition: 'A data item defined in a class.' },
      { term: 'Method', definition: 'A programmed procedure defined as part of a class.' },
      { term: 'Object', definition: 'A self-contained instance of a class containing data and methods.' },
      { term: 'Encapsulation', definition: 'Putting data and methods together as one class unit.' },
    ],
    visual: 'types', accent: 'indigo', ...source(501, 502, ['OOP definition', 'Class/object terminology', 'Encapsulation']),
  },
  {
    id: 'h20-2013-class-implementations', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: 'CLASS DEFINITIONS · PYTHON · VB · JAVA',
    title: 'The class concept stays the same even though declaration syntax differs among the prescribed languages',
    lead: 'The source develops class definitions and object creation across Python, Visual Basic and Java so learners can separate the OOP concept from each language’s punctuation and keywords.',
    bullets: [
      'A class definition groups attributes and methods under one type.',
      'An object is created as an instance of that class.',
      'Method calls send work to the object rather than manipulating all data globally.',
      'The same object model can be expressed using different language-specific syntax.',
    ],
    activity: { title: 'Activity 20C', prompt: 'Declare a student class with private name, dateOfBirth and examMark attributes plus a public displayExamMark method. Create myStudent and use the method to display its mark.' },
    visual: 'types', accent: 'cyan', ...source(502, 505, ['Python/VB/Java class definitions', 'Object creation', 'Activity 20C']),
  },
  {
    id: 'h20-2013-data-hiding', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: 'DATA HIDING · PRIVATE ATTRIBUTES · ENCAPSULATION',
    title: 'Data hiding protects object integrity by restricting direct access to internal data and methods',
    lead: 'The source explicitly links data hiding with encapsulation and says this can reduce programming complexity while increasing data protection and security.',
    bullets: [
      'Private attributes should not be changed arbitrarily by outside code.',
      'Public methods provide controlled ways to inspect or change protected state.',
      'Encapsulation combines the data with the methods responsible for maintaining it.',
      'The source demonstrates private-attribute class definitions in Python, VB and Java.',
    ],
    visual: 'types', accent: 'amber', ...source(505, 507, ['Data hiding', 'Private attributes', 'Encapsulation', 'Python/VB/Java examples']),
  },
  {
    id: 'h20-2013-inheritance', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: 'INHERITANCE · SUPERCLASS · DERIVED CLASS',
    title: 'Inheritance copies the data and methods of a base/superclass into a derived class',
    lead: 'Figures 20.2 and 20.3 distinguish single inheritance from multiple inheritance, while the employee example develops partTime and fullTime derived classes.',
    bullets: [
      'Single inheritance gives a derived class one superclass.',
      'Multiple inheritance gives a derived class more than one superclass, although the source notes that not every language supports it.',
      'A derived class can add data or methods while retaining inherited behaviour.',
      'The employee hierarchy provides a concrete base-class/derived-class model.',
    ],
    activity: { title: 'Activity 20D', prompt: 'Extend the student class with fullTimeStudent and partTimeStudent derived classes, create an object of each and display their exam marks.' },
    visual: 'types', accent: 'emerald', ...source(507, 510, ['Figures 20.2–20.4', 'Single/multiple inheritance', 'Employee example', 'Activity 20D', 'Extension Activity 20A']),
  },
  {
    id: 'h20-2013-polymorphism-overloading', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: 'POLYMORPHISM · OVERLOADING',
    title: 'Polymorphism redefines inherited behaviour; overloading defines the same method more than once for different situations',
    lead: 'The source separates these two ideas: polymorphism changes a method for a derived class, while overloading provides multiple method definitions within a class.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Polymorphism', rightTitle: 'Overloading', rows: [
      ['A derived class redefines a method inherited from a base class.', 'A method name is defined more than once so it can handle different argument situations.'],
      ['Source example: area behaviour for shape-derived classes.', 'Source activity: greeting with zero, one or two name arguments.'],
    ] }],
    activity: { title: 'Activities 20E–20F', prompt: 'Implement the source polymorphism example, then create the greeting class whose hello method can be used without a name, with one name, or with first and last names.' },
    visual: 'types', accent: 'rose', ...source(510, 513, ['Polymorphism', 'Overloading', 'Shape area example', 'Activities 20E–20F']),
  },
  {
    id: 'h20-2013-containment', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: 'CONTAINMENT / AGGREGATION · HAS-A RELATIONSHIP',
    title: 'Containment models an object that is built from objects of other classes',
    lead: 'The source defines containment (aggregation) as one class containing other classes and illustrates an aeroplane containing seat, fuselage, wing and cockpit objects.',
    bullets: [
      'Containment differs from inheritance: it models “has-a” composition rather than “is-a” specialisation.',
      'A class diagram can show the classes that make up the containing object.',
      'The later binary-tree example uses a tree object containing node objects.',
    ],
    visual: 'types', accent: 'indigo', ...source(513, 514, ['Containment/aggregation', 'Aeroplane diagram']),
  },
  {
    id: 'h20-2013-accessors-lifecycle', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: 'GETTER · SETTER · CONSTRUCTOR · DESTRUCTOR',
    title: 'Accessor and lifecycle methods control how an object is read, changed, created and destroyed',
    lead: 'The chapter defines getters, setters, constructors and destructors as part of the practical OOP vocabulary required for class implementation.',
    richBlocks: [{ kind: 'table', table: { caption: 'OOP method roles', headers: ['Method type', 'Source-backed role'], rows: [
      ['Getter', 'Gets the value of a property.'],
      ['Setter', 'Controls changes to a variable/property.'],
      ['Constructor', 'Initialises a new object.'],
      ['Destructor', 'Is automatically invoked when an object is destroyed.'],
    ] } }],
    visual: 'types', accent: 'cyan', ...source(514, 517, ['Getter', 'Setter', 'Constructor', 'Destructor']),
  },
  {
    id: 'h20-2013-binary-tree-oop', section: '20.1 Programming paradigms', subtopicCode: '20.1.3', eyebrow: 'OOP + RECURSION · BINARY TREE',
    title: 'The binary-tree example combines objects, constructors, containment, functions, procedures and recursion',
    lead: 'The source explicitly maps the design: tree and node objects, a constructor for adding a node, containment because the tree contains nodes, a search function and an insertion procedure.',
    richBlocks: [{ kind: 'steps', title: 'Source design decomposition', items: [
      'Objects — tree and node.',
      'Constructor — add/create a new node.',
      'Containment — the tree contains nodes.',
      'Function — search the tree for an item.',
      'Procedure — insert a new item.',
      'Recursion — traverse/operate through the tree structure.',
    ] }],
    activity: { title: 'Activity 20H / Extension 20B', prompt: 'Implement a binary tree using objects and recursion, starting with root 27 and adding 19, 36, 42 and 16. Then perform pre-order and post-order traversals.' },
    visual: 'files', accent: 'emerald', ...source(518, 521, ['Tables 20.6–20.9', 'Binary-tree OOP implementation', 'Activity 20H', 'Extension Activity 20B']),
  },
  {
    id: 'h20-2014-declarative', section: '20.1 Programming paradigms', subtopicCode: '20.1.4', eyebrow: '20.1.4 · DECLARATIVE PROGRAMMING',
    title: 'Declarative programming states knowledge and goals rather than a fixed sequence of execution steps',
    lead: 'The source contrasts it with imperative programming: facts and rules can be stated in any order before a query asks the system to infer a result.',
    bullets: [
      'Declarative programs describe what is true and what relationship is required.',
      'The language runtime determines how to use the knowledge base to satisfy a query.',
      'The chapter links SQL query writing to the declarative style before introducing Prolog.',
    ],
    visual: 'types', accent: 'amber', ...source(521, 522, ['Declarative programming', 'SQL link', 'Imperative/declarative comparison']),
  },
  {
    id: 'h20-2014-prolog-facts-queries', section: '20.1 Programming paradigms', subtopicCode: '20.1.4', eyebrow: 'PROLOG · PREDICATE LOGIC · FACTS · QUERIES',
    title: 'Prolog stores facts in a knowledge base and answers queries by matching predicates and variables',
    lead: 'The source uses country/language facts to show lower-case atoms, full-stop-terminated facts and upper-case variables in queries.',
    example: { title: 'Source-style fact/query forms', lines: ['country(france).', 'language(france,french).', 'language(Country,english)', 'language(switzerland,Language)'] },
    bullets: [
      'Facts use predicate notation and are stored in the knowledge base.',
      'A variable begins with an upper-case letter in the source examples.',
      'A query can bind a variable to each matching result.',
      'Results are normally returned in the order supported by the stored facts/rules.',
    ],
    activity: { title: 'Activity 20I / Extension 20C', prompt: 'Write queries for the supplied country/language facts, then extend the knowledge base in SWI-Prolog and query it for additional countries and languages.' },
    visual: 'types', accent: 'indigo', ...source(522, 523, ['Prolog facts', 'Knowledge base', 'Queries', 'Activity 20I', 'Extension Activity 20C']),
  },
  {
    id: 'h20-2014-prolog-rules', section: '20.1 Programming paradigms', subtopicCode: '20.1.4', eyebrow: 'PROLOG · RULES · BANK-ACCOUNT KNOWLEDGE BASE',
    title: 'Rules derive new knowledge from stored facts, while queries test the resulting relationships',
    lead: 'The later source example uses bank-account facts, variables and rules before asking learners to query savings accounts and add new facts/rules.',
    activity: { title: 'Activity 20J / Extension 20D', prompt: 'Use the bank-account facts to query Laila’s interest rate and savings-account owners, then add Robert’s account and the requested interest-rate rule. Check the result in SWI-Prolog.' },
    bullets: [
      'Rules express relationships that can be satisfied when their component predicates are true.',
      'Queries can return values for one or more variables.',
      'Declarative order is about logical relationships rather than the execution order of an imperative statement list.',
    ],
    visual: 'types', accent: 'cyan', ...source(523, 525, ['Prolog rules', 'Bank-account knowledge base', 'Activity 20J', 'Extension Activity 20D', 'Activity 20K']),
  },
  {
    id: 'h20-2021-record-files', section: '20.2 File processing and exception handling', subtopicCode: '20.2.1', eyebrow: '20.2.1 · RECORD FILES · SERIAL / SEQUENTIAL / RANDOM',
    title: 'File organisation determines how records are physically stored and how efficiently particular records can be reached',
    lead: 'The source revisits serial, sequential and random organisations because Chapter 20 now writes complete records containing mixed data types rather than only text lines.',
    richBlocks: [{ kind: 'table', table: { caption: 'File organisations', headers: ['Organisation', 'Source-backed characteristic'], rows: [
      ['Serial', 'Records are physically stored one after another in the order they are added.'],
      ['Sequential', 'Records are physically stored one after another in a given key order.'],
      ['Random', 'Records can occupy available positions and their location is found from the key using a hashing algorithm.'],
    ] } }],
    visual: 'files', accent: 'indigo', ...source(525, 526, ['File organisation recap', 'Record type declaration', '20.2.1 heading']),
  },
  {
    id: 'h20-2021-put-get-record', section: '20.2 File processing and exception handling', subtopicCode: '20.2.1', eyebrow: 'PUTRECORD · GETRECORD · SERIAL STORAGE',
    title: 'Record-oriented pseudocode writes and reads a whole record with PUTRECORD and GETRECORD',
    lead: 'The source declares a student record and then develops a serial-file algorithm in which records are input, written and later read as complete structured values.',
    bullets: [
      'PUTRECORD writes a record to a data file.',
      'GETRECORD reads a record from a data file.',
      'The serial-storage algorithm appends input records in arrival order.',
      'Python, VB and Java examples show language-specific ways to persist equivalent student data.',
    ],
    activity: { title: 'Activity 20L', prompt: 'Input a student record and save it to a new serial file, read it back, then extend the program so more than one record can be stored and retrieved.' },
    visual: 'files', accent: 'cyan', ...source(526, 531, ['Student record', 'PUTRECORD', 'GETRECORD', 'Python/VB/Java file examples', 'Activity 20L']),
  },
  {
    id: 'h20-2021-sequential-update', section: '20.2 File processing and exception handling', subtopicCode: '20.2.1', eyebrow: 'SEQUENTIAL FILE · INSERT IN KEY ORDER',
    title: 'Adding to an ordered sequential file can require recreating the file so the new record is written in the correct place',
    lead: 'Unlike a serial file, where a record can simply be appended, the source sequential-file algorithm copies records around the insertion point into a new file and then replaces the old file.',
    richBlocks: [{ kind: 'steps', title: 'Source update pattern', items: [
      'Open the existing sequential file and a new output file.',
      'Read records in key order.',
      'Write the new record at the correct key position while copying existing records.',
      'Finish copying remaining records.',
      'Close both files, delete the old file and rename the new file to the original filename.',
    ] }],
    activity: { title: 'Extension 20E / Activity 20M', prompt: 'Sort records on registerNumber before storage, then write code to append/search records and detect the record-not-found condition where required.' },
    visual: 'files', accent: 'emerald', ...source(531, 533, ['Adding a record to a sequential file', 'DELETE', 'RENAME', 'Activity 20M', 'Extension Activity 20E']),
  },
  {
    id: 'h20-2021-random-write', section: '20.2 File processing and exception handling', subtopicCode: '20.2.1', eyebrow: 'RANDOM FILE · HASHING · SEEK · PUTRECORD',
    title: 'Random access hashes the key into a record address so the program can seek directly to the target position',
    lead: 'The source pseudocode applies a hash function to the key, seeks to the resulting file address and writes the record there instead of scanning all preceding records.',
    example: { title: 'Random-write route', lines: ['address ← hash(key)', 'SEEK studentFile, address', 'PUTRECORD studentFile, studentRecord', 'CLOSEFILE(studentFile)'] },
    activity: { title: 'Extension Activity 20G', prompt: 'In your chosen language, input a student record and save it to a random file using the source key-to-address method.' },
    visual: 'files', accent: 'amber', ...source(533, 535, ['Hashing function', 'SEEK', 'PUTRECORD', 'Extension Activity 20G']),
  },
  {
    id: 'h20-2021-random-read', section: '20.2 File processing and exception handling', subtopicCode: '20.2.1', eyebrow: 'RANDOM FILE LOOKUP · HASH → SEEK → GETRECORD',
    title: 'Finding a random-file record repeats the key hash and seeks directly to the computed position before reading',
    lead: 'The source uses the same deterministic mapping from key to address for lookup, avoiding a sequential scan through earlier records.',
    example: { title: 'Random-read route', lines: ['address ← hash(key)', 'SEEK studentFile, address', 'GETRECORD studentFile, studentRecord', 'OUTPUT studentRecord', 'CLOSEFILE(studentFile)'] },
    activity: { title: 'Extension Activity 20H', prompt: 'Find and output a student record from a random file using the key field to identify the record.' },
    visual: 'files', accent: 'rose', ...source(535, 536, ['Finding a record in a random file', 'GETRECORD', 'Extension Activity 20H']),
  },
  {
    id: 'h20-2022-exception-concept', section: '20.2 File processing and exception handling', subtopicCode: '20.2.2', eyebrow: '20.2.2 · EXCEPTION HANDLING · ROBUST PROGRAMS',
    title: 'An exception is an unexpected event that disrupts execution; a handler provides a controlled response',
    lead: 'The source defines exception handling as responding inside the program so execution does not halt unexpectedly, improving robustness by trapping the error and then recovering or shutting down cleanly.',
    bullets: [
      'Protected code executes normally when no exceptional event occurs.',
      'When the specified exception occurs, the handler outputs an appropriate message or performs recovery/cleanup.',
      'An orderly shutdown is preferable to an uncontrolled run-time failure when recovery is not possible.',
      'File operations are a key context because missing files and unexpected end-of-file conditions are predictable hazards.',
    ],
    visual: 'files', accent: 'indigo', ...source(536, 536, ['Exception definition', 'Exception handling definition', 'Robustness']),
  },
  {
    id: 'h20-2022-language-handlers', section: '20.2 File processing and exception handling', subtopicCode: '20.2.2', eyebrow: 'TRY / EXCEPT / CATCH · LANGUAGE COMPARISON',
    title: 'Python, VB and Java use different syntax but share the same protected-block and handler structure',
    lead: 'The source demonstrates exception handling with arithmetic input/division examples in the prescribed languages, including a divide-by-zero handler.',
    bullets: [
      'Place statements that may fail inside a protected try block.',
      'Catch/except the specific exceptional condition rather than assuming every operation succeeds.',
      'Keep the normal path separate from the error response so a successful calculation remains straightforward.',
    ],
    activity: { title: 'Activity 20N', prompt: 'Write a program in your chosen language that checks whether an input value is an integer using the source exception-handling approach.' },
    visual: 'types', accent: 'cyan', ...source(536, 537, ['Python/VB/Java exception examples', 'Divide-by-zero', 'Activity 20N']),
  },
  {
    id: 'h20-2022-file-exceptions', section: '20.2 File processing and exception handling', subtopicCode: '20.2.2', eyebrow: 'FILE EXCEPTIONS · EXISTS · END-OF-FILE',
    title: 'Exception handling completes the file-processing route by guarding predictable failures around external data',
    lead: 'Activity 20O asks learners to retrofit their Section 20.2.1 file programs so missing files and unexpected end-of-file conditions are handled rather than crashing the program.',
    activity: { title: 'Activity 20O', prompt: 'Extend your file-handling programs so they handle files that do not exist and unexpected end of file, then test both exceptional paths deliberately.' },
    visual: 'files', accent: 'emerald', ...source(537, 538, ['Activity 20O', 'File existence', 'Unexpected end of file']),
  },
  {
    id: 'h20-review', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER · PARADIGMS + PROLOG + FILES + EXCEPTIONS',
    title: 'The printed review integrates the chapter’s paradigms, declarative reasoning and advanced programming techniques',
    lead: 'The final printed questions include older Cambridge 9608 material; this route preserves them as Hodder coursebook review rather than presenting them as current live 9618 Past Paper checkpoints.',
    bullets: [
      'Identify and compare programming paradigms and OOP concepts.',
      'Trace or complete Prolog facts, goals and rules, including family/relationship reasoning.',
      'Apply file-processing and exception-handling ideas in program-design questions.',
      'Use the review as retrieval and exam-style practice while keeping its original source status explicit.',
    ],
    activity: { title: 'Source review', prompt: 'Complete one declarative-programming question and one file/exception question from pp.538–540. Annotate which chapter concept each mark point is testing.' },
    visual: 'recap', accent: 'rose', ...source(538, 540, ['End-of-chapter questions', 'Cambridge 9608 source material']),
  },
];

export const CHAPTER_20_FINAL: HodderLessonChapter = {
  number: 20,
  level: 'A Level',
  title: 'Further programming',
  subtitle: 'Programming paradigms · OOP · declarative programming · record file processing · exception handling',
  subtopics: [
    '20.1 Programming paradigms',
    '20.2 File processing and exception handling',
  ],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 full coursebook, printed pp.498–540. Every printed chapter page is represented in slide provenance; paradigm comparisons, OOP terminology/examples, Prolog facts/rules/queries, serial/sequential/random record operations, hashing/random access, exception-handling examples, activities and printed review are preserved as teaching paraphrase.',
  coverage: '43/43 printed chapter pages represented (pp.498–540): low-level and imperative programming; OOP class/object/encapsulation/data-hiding/inheritance/polymorphism/overloading/containment/accessor/lifecycle concepts; binary-tree OOP/recursion; declarative programming and Prolog; record storage in serial, sequential and random files; PUTRECORD/GETRECORD, hashing and SEEK; exception handling and end-of-chapter review.',
  slides: CHAPTER_20_DEEP_SLIDES,
};
