import type { HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 4 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_4_FETCH_ASSEMBLY_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h4-415-ports-compare',
    section: '4.1 Central processing unit (CPU) architecture',
    subtopicCode: '4.1.5',
    eyebrow: '4.1.5 · USB / HDMI / VGA · TABLES 4.2–4.3',
    title: 'USB became the industry standard; HDMI replaced VGA for modern digital displays',
    lead: 'Hodder completes the ports section by comparing USB advantages and limitations, then contrasts HDMI with the older analogue VGA system.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Table 4.2 · Pros and cons of the USB system',
          headers: ['Pros', 'Cons'],
          rows: [
            ['devices are automatically detected and device drivers automatically loaded', 'present transmission rate is limited to less than 500 megabits per second'],
            ['connectors can only fit one way', 'maximum cable length is presently about five metres'],
            ['industry standard with considerable support', 'older USB standards such as 1.1 may not be supported in the near future'],
            ['several data transmission rates are supported', ''],
            ['newer USB standards are backward compatible with older standards', ''],
          ],
        },
      },
      {
        kind: 'comparison',
        leftTitle: 'HDMI',
        rightTitle: 'VGA',
        rows: [
          ['digital output carrying audio and visual data', 'analogue technology introduced at the end of the 1980s'],
          ['supports high-definition signals and increased bandwidth', 'supports 640 × 480 pixels; up to 60 Hz with 16 colours'],
          ['modern HD example: 16:9, 1920 × 1080, 120 Hz', 'at 200 × 320 it can support up to 256 colours'],
          ['HDCP can authenticate a connected device before transmission', 'being phased out as modern digital display requirements increase'],
        ],
      },
    ],
    example: {
      title: 'Source bandwidth context',
      lines: [
        'Modern HD screens may require around 10 gigabits per second.',
        'HDMI increases bandwidth for high-quality sound and visual effects.',
        'Table 4.3: HDMI is fast and digital; VGA is simpler and has a secure physical connection but is outdated analogue technology.',
      ],
    },
    visual: 'types',
    accent: 'cyan',
    ...source(115, ['Table 4.2 Pros and cons of the USB system', 'High-definition multimedia interface (HDMI)', 'Video Graphics Array (VGA)', 'Table 4.3 Pros and cons of HDMI and VGA']),
  },
  {
    id: 'h4-416-fetch-cycle',
    section: '4.1 Central processing unit (CPU) architecture',
    subtopicCode: '4.1.6',
    eyebrow: '4.1.6 · FETCH-EXECUTE CYCLE · FIGURE 4.5',
    title: 'Fetch the next instruction, decode it, then execute it',
    lead: 'The processor fetches data and instructions from memory into suitable registers. Each instruction is decoded before the processor executes it.',
    richBlocks: [{
      kind: 'steps',
      title: 'Figure 4.5 · Von Neumann fetch-execute sequence',
      items: [
        'PC contains the address of the next instruction to be fetched.',
        'Copy the address from PC to MAR using the address bus.',
        'Copy the contents at the address in MAR temporarily into MDR.',
        'Copy the instruction from MDR into CIR.',
        'Increment PC by one so it points to the next instruction.',
        'Decode and execute the instruction by sending signals via the control bus.',
        'At the cycle boundary, check whether an interrupt needs servicing.',
      ],
    }],
    visual: 'types',
    accent: 'emerald',
    ...source(116, ['4.1.6 Fetch-execute cycle', 'Figure 4.5 How the fetch-execute cycle is carried out in the Von Neumann computer model']),
  },
  {
    id: 'h4-416-rtn',
    section: '4.1 Central processing unit (CPU) architecture',
    subtopicCode: '4.1.6',
    eyebrow: 'REGISTER TRANSFER NOTATION · RTN',
    title: 'RTN expresses the same fetch sequence with register transfers',
    lead: 'Hodder introduces Register Transfer Notation as a compact way to describe transfers between the registers used in Figure 4.5.',
    richBlocks: [{
      kind: 'table',
      table: {
        caption: 'Register Transfer Notation from p.117',
        headers: ['RTN', 'Meaning'],
        rows: [
          ['MAR ← [PC]', 'contents of PC copied into MAR'],
          ['PC ← [PC] + 1', 'PC is incremented by 1'],
          ['MDR ← [[MAR]]', 'data stored at the address shown in MAR is copied into MDR'],
          ['CIR ← [MDR]', 'contents of MDR copied into CIR'],
        ],
      },
    }],
    example: {
      title: 'Why double brackets?',
      lines: ['[[MAR]] means the data stored at the address held in MAR, not the contents of MAR itself.', 'Hodder notes that RTN may be abstract (generic) or concrete (specific to a particular machine).'],
    },
    visual: 'types',
    accent: 'indigo',
    ...source(117, ['Register Transfer Notation (RTN)', 'MAR ← [PC]', 'PC ← [PC] + 1', 'MDR ← [[MAR]]', 'CIR ← [MDR]']),
  },
  {
    id: 'h4-416-interrupt-cycle',
    section: '4.1 Central processing unit (CPU) architecture',
    subtopicCode: '4.1.6',
    eyebrow: 'INTERRUPT REGISTER · FIGURE 4.6',
    title: 'An interrupt is checked at the cycle boundary and handled by an ISR',
    lead: 'A special interrupt register records an interrupt while the fetch-execute cycle is running. The CPU checks it during the next cycle and decides whether to service the interrupt according to priority.',
    bullets: [
      'Source example: interrupt register changes from 0000 0000 to 0000 1000 after a hard-drive write fault.',
      'If the interrupt is serviced, the CPU stops its current task and saves register contents.',
      'Control transfers to the interrupt handler, also called the interrupt service routine (ISR).',
      'After servicing, the interrupt register is reset and saved register contents are restored.',
    ],
    visual: 'types',
    accent: 'rose',
    ...source(118, ['Figure 4.6 The interrupt process during the fetch-execute cycle', 'interrupt register', 'interrupt service routine (ISR)', '0000 0000', '0000 1000']),
  },
  {
    id: 'h4-417-interrupts',
    section: '4.1 Central processing unit (CPU) architecture',
    subtopicCode: '4.1.7',
    eyebrow: '4.1.7 · INTERRUPTS',
    title: 'Interrupts let the processor respond to events without losing the current task state',
    lead: 'An interrupt is a signal from a device or software that can make the processor temporarily stop its current work and service the event.',
    richBlocks: [{
      kind: 'table',
      table: {
        caption: 'Interrupt causes listed by Hodder',
        headers: ['Cause', 'Source example'],
        rows: [
          ['timing signal', 'a timing event'],
          ['input/output process', 'a disk drive is ready to receive more data'],
          ['hardware fault', 'paper jam in a printer'],
          ['user interaction', 'a user presses a key combination to interrupt the current process'],
          ['software error that cannot be ignored', 'an .exe file cannot be found or an attempt is made to divide by zero'],
        ],
      },
    }],
    bullets: [
      'The computer identifies the interrupt type and establishes its priority.',
      'Before an ISR runs, the current task state including PC and other registers is saved.',
      'The ISR start address is loaded into PC.',
      'When servicing finishes, the saved state is restored and the interrupted task continues.',
    ],
    visual: 'types',
    accent: 'amber',
    ...source(119, ['4.1.7 Interrupts', 'interrupt priority', 'interrupt service routine (ISR)']),
  },
  {
    id: 'h4-41-activity4a',
    section: '4.1 Central processing unit (CPU) architecture',
    eyebrow: 'ACTIVITY 4A · PP.119–120',
    title: 'Retrieve the complete CPU-architecture chain before assembly language',
    lead: 'Activity 4A consolidates registers, status flags, buses, ports and the fetch-execute cycle before the chapter moves to assembly language.',
    richBlocks: [{
      kind: 'steps',
      title: 'Activity 4A · source tasks',
      items: [
        'Describe CIR, MAR and PC; explain N, C and V flags and give an example use for each.',
        'Name the three Von Neumann buses, describe their functions, and explain how bus width and clock speed can affect performance.',
        'Connect HDMI/VGA features: analogue or digital interface, piracy protection, signal splitting, and the stated maximum refresh-rate features.',
        'Define the fetch-execute cycle and show its main stages using register transfer notation.',
        'Complete the source paragraph using chapter terms for processor, registers, buses, decoding/execution and ALU work.',
      ],
    }],
    example: {
      title: 'Source fidelity note',
      lines: ['The printed activity states “maximum refresh rate of 60 GHz” and “up to 120 GHz”. These units are preserved as printed rather than silently corrected.'],
    },
    visual: 'types',
    accent: 'indigo',
    ...source(120, ['Activity 4A', 'HDMI', 'VGA', 'fetch-execute cycle', 'register transfer notation']),
  },
  {
    id: 'h4-42-prior-keyterms',
    section: '4.2 Assembly language',
    subtopicCode: '4.2',
    eyebrow: '4.2 · ASSEMBLY LANGUAGE · WHAT YOU SHOULD ALREADY KNOW',
    title: 'Assembly language sits close to machine code and uses machine-specific mnemonics',
    lead: 'Hodder starts the second half of the chapter with prior-knowledge questions and a key-term set that frames machine code, assembly language, translation and addressing modes.',
    richBlocks: [
      {
        kind: 'steps',
        title: 'Prior knowledge',
        items: [
          'Name two types of low-level programming language.',
          'Name the only programming language recognised by a CPU and explain why programmers find it difficult to write.',
          'Find CPU types and the language they use; inspect the programming languages used by your computer, laptop or phone.',
        ],
      },
      {
        kind: 'callout',
        tone: 'tip',
        title: 'Key terms introduced on p.121',
        text: 'machine code · instruction · assembly language · opcode · operand · source code · assembler · instruction set · object code · addressing modes · absolute/direct · indirect · indexed · immediate · relative · symbolic',
      },
    ],
    visual: 'types',
    accent: 'cyan',
    ...source(121, ['4.2 Assembly language', 'What you should already know', 'Key terms']),
  },
  {
    id: 'h4-421-machine-assembly',
    section: '4.2 Assembly language',
    subtopicCode: '4.2.1',
    eyebrow: '4.2.1 · ASSEMBLY LANGUAGE AND MACHINE CODE',
    title: 'Opcode and operand structure is shared; assembly replaces binary with mnemonics',
    lead: 'Machine code is the only programming language a CPU can use. Each processor/chip has its own machine-code instruction set; assembly language is closely related but uses mnemonics.',
    richBlocks: [{
      kind: 'table',
      table: {
        caption: 'Source instruction examples',
        headers: ['Assembly mnemonic', 'Machine code hexadecimal', 'Machine code binary'],
        rows: [
          ['LDD Total', '0140', '00000000110000000'],
          ['ADD 20', '0214', '00000001000011000'],
          ['STO Total', '0340', '00000001110000000'],
        ],
      },
    }],
    bullets: [
      'The opcode identifies the operation to be carried out by the CPU.',
      'Most instructions also have an operand identifying the data used by the opcode.',
      'Programs not written in machine code require translation before the CPU can execute them.',
    ],
    visual: 'types',
    accent: 'emerald',
    ...source(122, ['4.2.1 Assembly language and machine code', 'Opcode', 'Operand', 'LDD Total', 'ADD 20', 'STO Total']),
  },
  {
    id: 'h4-422-two-pass-assembler',
    section: '4.2 Assembly language',
    subtopicCode: '4.2.2',
    eyebrow: '4.2.2 · STAGES OF ASSEMBLY · TWO PASS ASSEMBLER',
    title: 'Pass 1 builds addresses and a symbol table; Pass 2 generates object code',
    lead: 'An assembler translates each assembly-language instruction into a machine-code instruction and checks that opcodes belong to the appropriate instruction set.',
    richBlocks: [{
      kind: 'comparison',
      leftTitle: 'Pass 1',
      rightTitle: 'Pass 2',
      rows: [
        ['read source one line at a time; ignore comments', 'read source one line at a time'],
        ['allocate a memory address and check the opcode', 'generate object code: opcode + operand'],
        ['add labels and known addresses to the symbol table', 'use the symbol table generated in Pass 1'],
        ['record the address of labelled instructions', 'save or execute the program'],
      ],
    }],
    example: {
      title: 'Hodder forward-reference example',
      lines: [
        'Notfound: LDD 200 · CMP #0 · JPN Found · JPE Notfound',
        'Found: OUT',
        'If loaded at address 100 with 16-bit memory locations: Notfound → 100; Found → 104.',
        'Found is a forward reference when JPN Found is first read; its address becomes available through the two-pass symbol-table process.',
      ],
    },
    visual: 'types',
    accent: 'rose',
    ...source(123, ['4.2.2 Stages of assembly', 'Pass 1', 'Pass 2', 'symbol table', 'forward reference', 'Notfound', 'Found']),
  },
];
