import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 15 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_15_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h15-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 15 · HARDWARE',
    title: 'From processor architecture and parallelism to Boolean algebra, adders, flip-flops and Karnaugh maps',
    lead: 'The chapter connects processor design with digital logic: first compare RISC/CISC and parallel architectures, then simplify and implement logic with Boolean algebra, adders, sequential circuits and K-maps.',
    richBlocks: [{ kind: 'steps', title: 'Chapter route', items: [
      'Compare RISC and CISC processor philosophies.',
      'Explain pipelining, registers and interrupt handling.',
      'Distinguish SISD, SIMD, MISD and MIMD architectures.',
      'Explain clusters and massively parallel computers.',
      'Use Boolean laws including De Morgan’s Laws.',
      'Understand half/full adders and SR/JK flip-flops.',
      'Derive Boolean expressions from circuits and truth tables.',
      'Simplify logic with Karnaugh maps using Gray-code ordering.',
    ] }],
    visual: 'recap', accent: 'indigo', ...source(346, ['Chapter 15 objectives', '15.1 prior knowledge', 'processor flags/fetch-execute/buses/interrupts']),
  },
  {
    id: 'h15-1511-risc-cisc-philosophy', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: '15.1.1 · RISC VS CISC',
    title: 'CISC favours complex hardware-supported instructions; RISC favours a smaller optimised instruction set',
    lead: 'The source presents two design philosophies: CISC aims to complete a task using fewer assembly statements, whereas RISC breaks work into simpler instructions that are easier to optimise.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'CISC', rightTitle: 'RISC', rows: [
      ['More instruction formats and complex instructions.', 'Fewer, simpler instruction formats.'],
      ['A complex instruction may require several internal sub-instructions.', 'Instructions are designed as simpler single-cycle operations.'],
      ['Design emphasis is more hardware-oriented.', 'Design emphasis is more software/instruction-set oriented.'],
    ] }],
    example: { title: 'Addition idea', lines: ['CISC: ADD A, B as one complex multi-cycle instruction', 'RISC: LOAD A, LOAD B, ADD, STORE as simpler steps'] },
    visual: 'types', accent: 'cyan', ...source(347, ['CISC', 'RISC', 'Key terms', 'ADD A,B example']),
  },
  {
    id: 'h15-1511-risc-cisc-table-pipeline-start', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: 'TABLE 15.1 · PIPELINING START',
    title: 'Fixed-length single-cycle instructions and general-purpose registers make RISC friendlier to pipelining',
    lead: 'Table 15.1 contrasts instruction formats, addressing modes, instruction length, execution time, decoding, pipelining and transistor requirements.',
    richBlocks: [{ kind: 'table', table: { caption: 'Table 15.1 highlights', headers: ['CISC feature', 'RISC feature'], rows: [
      ['Many instruction formats', 'Fewer instruction formats'],
      ['More addressing modes', 'Fewer addressing modes'],
      ['Multi-cycle instructions', 'Single-cycle instructions'],
      ['Variable instruction length', 'Fixed instruction length'],
      ['More complex decoding', 'General multi-purpose registers'],
      ['Pipelining is more difficult', 'Pipelining is easier'],
    ] } }],
    richBlocks: [{ kind: 'steps', title: 'Five pipeline stages introduced', items: ['IF — instruction fetch', 'ID — instruction decode', 'OF — operand fetch', 'IE — instruction execution', 'WB — writeback'] }],
    visual: 'recap', accent: 'emerald', ...source(348, ['Table 15.1', 'Extension Activity 15A', 'Pipelining', 'IF/ID/OF']),
  },
  {
    id: 'h15-1511-pipelining-interrupts', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.1', eyebrow: 'FIGURE 15.1 · PIPELINE + INTERRUPTS',
    title: 'Pipelining overlaps stages from different instructions, reducing six five-stage instructions from 30 cycles to 10 in the source example',
    lead: 'Registers hold intermediate pipeline stages. Interrupt handling is more complex because several instructions may already be in flight.',
    richBlocks: [{ kind: 'steps', title: 'Figure 15.1 reasoning', items: [
      'Clock 1 starts IF for instruction A.',
      'Clock 2 performs ID for A while starting IF for B.',
      'Each later clock overlaps more stages until the pipeline fills.',
      'Six instructions complete in 10 cycles instead of 30 sequential cycles in this example.',
      'On an interrupt, one common strategy discards pipeline instructions except the one already in WB; another less common strategy stores all stage contents in registers.',
    ] }],
    visual: 'recap', accent: 'amber', ...source(349, ['Figure 15.1 pipeline', '10 versus 30 clock cycles', 'Interrupt handling in a pipeline']),
  },
  {
    id: 'h15-1512-sisd-simd', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: '15.1.2 · SISD + SIMD · FIGURES 15.2–15.3',
    title: 'SISD is sequential; SIMD applies one instruction to many independent data items at once',
    lead: 'The source uses image-brightness adjustment to show why SIMD is effective when many independent values need the same operation.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'SISD', rightTitle: 'SIMD', rows: [
      ['One processor, one instruction stream, one data source.', 'Many processors execute the same instruction on different data.'],
      ['Tasks are processed sequentially.', 'Supports parallel processing of independent items.'],
      ['Typical of early personal computers.', 'Useful for graphics/image pixels, sound sampling and array-style workloads.'],
    ] }],
    visual: 'types', accent: 'indigo', ...source(350, ['15.1.2 Parallel processing', 'Figure 15.2 SISD', 'Figure 15.3 SIMD', '4000-pixel brightness example']),
  },
  {
    id: 'h15-1512-misd-mimd-factors', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'MISD + MIMD · FIGURES 15.4–15.5',
    title: 'MISD shares one data source across different instructions; MIMD gives processors independent instructions and data',
    lead: 'MISD is uncommon; MIMD is used in multicore systems and supercomputers. Successful parallel processing also depends on communication, suitable software and independent data.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'MISD', rightTitle: 'MIMD', rows: [
      ['Several processors use different instructions on a shared data source.', 'Several processors independently execute different instructions.'],
      ['Uncommon; the source cites Space Shuttle flight control.', 'Used in multicore systems and supercomputers.'],
      ['Single shared data stream.', 'Processors may use separate or partitioned data sources.'],
    ] }],
    bullets: ['Processors must communicate and transfer processed data.', 'Software/languages must support multi-processor work.', 'Dependent data is less suitable because one operation waits for another.', 'Parallelism helps overcome the Von Neumann bottleneck but increases hardware cost.'],
    visual: 'types', accent: 'cyan', ...source(351, ['Figure 15.4 MISD', 'Figure 15.5 MIMD', 'Parallel-processing factors', 'Von Neumann bottleneck']),
  },
  {
    id: 'h15-1512-cluster-massive', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'CLUSTERS · MASSIVELY PARALLEL · FIGURE 15.6',
    title: 'A cluster networks computers that remain largely independent; a massively parallel system behaves more like one machine with thousands of processors',
    lead: 'Massively parallel computers split large scientific/mathematical problems across many processors connected by data pathways.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Cluster', rightTitle: 'Massively parallel computer'], rows: [
      ['Networked computers combine processing capacity.', 'Many linked processors effectively form one machine.'],
      ['Individual computers remain largely independent.', 'Each processor carries out part of the same large processing task.'],
      ['Can act like a supercomputer/pseudo-parallel system.', 'Communication occurs through interconnected data pathways.'],
    ] }],
    visual: 'recap', accent: 'emerald', ...source(352, ['Cluster', 'Massively parallel computers', 'Figure 15.6 interconnected pathways']),
  },
  {
    id: 'h15-151-review-activity', section: '15.1 Processors and parallel processing', subtopicCode: '15.1.2', eyebrow: 'ACTIVITY 15A · EXTENSION 15B',
    title: 'The source consolidates processor architecture with comparison, bottleneck, cluster/massive and pipeline tracing tasks',
    lead: 'Activity 15A asks learners to explain RISC/CISC, the Von Neumann bottleneck, cluster versus massively parallel systems and a six-instruction pipeline.',
    activity: { title: 'Activity 15A', prompt: 'Draw a pipeline diagram for LOAD A, LOAD B, LOAD C, ADD A,B,C, STORE D, OUT D and compare the required cycles with sequential processing.' },
    bullets: ['Extension 15B suggests applications in seismology, astronomy, climate modelling, nuclear physics and weather forecasting.', 'Figure 15.7 invites research into historical growth in calculations per second.'],
    visual: 'recap', accent: 'rose', ...source(353, ['Activity 15A', 'Extension Activity 15B', 'Figure 15.7']),
  },
  {
    id: 'h15-1521-boolean-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.1', eyebrow: '15.2.1 · BOOLEAN ALGEBRA',
    title: 'Boolean algebra models logic circuits using only TRUE (1) and FALSE (0)',
    lead: 'The second half of the chapter begins by revisiting truth tables and logic circuits, then defines adders, combination/sequential circuits, flip-flops, SoP, Gray code and K-maps.',
    keyTerms: [
      { term: 'Combination circuit', definition: 'Output depends entirely on current input values.' },
      { term: 'Sequential circuit', definition: 'Output depends on current inputs and a previous output/state.' },
      { term: 'Sum of products (SoP)', definition: 'A Boolean expression containing AND terms combined by OR.' },
      { term: 'Gray code', definition: 'An ordering where adjacent binary values differ by one bit.' },
      { term: 'Karnaugh map', definition: 'A Gray-code-based method for simplifying Boolean expressions/circuits.' },
    ],
    visual: 'types', accent: 'indigo', ...source(354, ['15.2 prior knowledge', 'Figure 15.8', 'Figure 15.9', '15.2.1 Boolean algebra', 'Key terms']),
  },
  {
    id: 'h15-1521-laws-demorgan', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.1', eyebrow: 'TABLES 15.2–15.3 · DE MORGAN',
    title: 'Boolean simplification uses algebraic laws, and De Morgan’s Laws convert complemented AND/OR structures',
    lead: 'The source summarises commutative, associative, distributive, idempotent, identity, null, inverse and absorption laws and proves De Morgan’s Laws using truth tables.',
    richBlocks: [{ kind: 'steps', title: 'De Morgan forms', items: ['NOT(A AND B) = (NOT A) OR (NOT B)', 'NOT(A OR B) = (NOT A) AND (NOT B)', 'Equivalent columns in the truth table confirm the identities.'] }],
    example: { title: 'Example 15.1', lines: ['Rearrange with associative laws.', 'Use inverse laws on A + NOT A and B + NOT B.', 'The result simplifies to 1.'] },
    visual: 'types', accent: 'cyan', ...source(355, ['Table 15.2 Boolean laws', 'Table 15.3 De Morgan proof', 'Example 15.1']),
  },
  {
    id: 'h15-1521-simplification-half-adder', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.1', eyebrow: 'EXAMPLE 15.2 · ACTIVITY 15B · HALF ADDER',
    title: 'Algebraic factorisation removes redundant terms; a half adder turns two input bits into Sum and Carry',
    lead: 'Example 15.2 factors a four-term expression to a three-term result. The chapter then introduces the half adder truth table.',
    example: { title: 'Example 15.2 result', lines: ['A.B.C + A.B.C + A.B.C + A.B.C', 'Factor paired terms using inverse complements.', 'Simplified form: B.C + A.C + A.B'] },
    richBlocks: [{ kind: 'table', table: { caption: 'Half-adder truth table', headers: ['A','B','S','C'], rows: [['0','0','0','0'],['0','1','1','0'],['1','0','1','0'],['1','1','0','1']] } }],
    activity: { title: 'Activity 15B', prompt: 'Simplify the five Boolean expressions in the source, showing each law used.' },
    visual: 'types', accent: 'emerald', ...source(356, ['Example 15.2', 'Activity 15B', '15.2.2 Further logic circuits', 'Table 15.4 half adder', 'Figure 15.10']),
  },
  {
    id: 'h15-1522-full-adder-build', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'FULL ADDER · FIGURES 15.11–15.13',
    title: 'A full adder handles A, B and a carry-in by combining two half adders and an OR stage',
    lead: 'Multi-bit addition needs to accept the carry from the previous column, so the source joins two half adders to create a full adder.',
    bullets: ['Inputs: A, B and Cin.', 'Outputs: Sum and Cout.', 'Two half adders plus an OR gate are one standard construction.', 'The logic circuit may be implemented with OR, AND and XOR gates.'],
    visual: 'recap', accent: 'amber', ...source(357, ['Figure 15.11 multi-bit addition', 'Figure 15.12 two half adders', 'Figure 15.13 full-adder logic']),
  },
  {
    id: 'h15-1522-full-adder-truth-sr-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.2', eyebrow: 'TABLE 15.5 · FIGURE 15.14 · SR INTRO',
    title: 'Full adders are chained for multi-bit sums; sequential circuits introduce stored state',
    lead: 'Table 15.5 lists all eight full-adder input combinations. Figure 15.14 chains four full adders to add two 4-bit values before the chapter moves to SR flip-flops.',
    richBlocks: [{ kind: 'table', table: { caption: 'Full-adder key cases', headers: ['A','B','Cin','S','Cout'], rows: [['0','0','0','0','0'],['0','1','1','0','1'],['1','0','1','0','1'],['1','1','1','1','1']] } }],
    activity: { title: 'Activity 15C', prompt: 'Construct half- and full-adder circuits using NAND gates only and verify each against the source truth tables.' },
    visual: 'types', accent: 'indigo', ...source(358, ['Table 15.5 full adder', 'Figure 15.14 four full adders', 'Activity 15C', '15.2.3 Flip-flop circuits', 'SR flip-flop intro']),
  },
  {
    id: 'h15-1523-sr-cross-coupling', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'SR FLIP-FLOP · FIGURES 15.15–15.17 · TABLE 15.6',
    title: 'Cross-coupled NOR gates create positive feedback, so an SR flip-flop can remember a one-bit state',
    lead: 'The output of each gate feeds the other gate. The source traces set/reset sequences and derives the SR truth table.',
    bullets: ['Inputs are S (set) and R (reset).', 'Outputs Q and NOT Q should normally be complements.', 'S=0, R=0 preserves the remembered state.', 'The cross-coupling provides positive feedback.'],
    visual: 'recap', accent: 'cyan', ...source(359, ['Figure 15.15 SR flip-flop', 'Figures 15.16–15.17 state trace', 'Table 15.6']),
  },
  {
    id: 'h15-1523-sr-invalid-jk', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'SR INVALID STATE → JK FLIP-FLOP',
    title: 'SR can enter an invalid state; JK adds a clock and logic so the forbidden case becomes a controlled toggle',
    lead: 'The source notes the illegal S=1, R=1 state and timing instability, then introduces JK to synchronise inputs and remove the invalid condition.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'SR', rightTitle: 'JK'], rows: [
      ['S=1,R=1 can make Q and NOT Q conflict.', 'Clocked design prevents the illegal SR condition.'],
      ['Can remember one bit and can contribute to RAM/storage.', 'Supports no-change, set/reset behaviour and toggle.'],
      ['Input timing can create instability.', 'Clock synchronises state changes.'],
    ] }],
    visual: 'types', accent: 'rose', ...source(360, ['SR set/reset/remember states', 'RAM one-bit storage', 'JK flip-flop introduction', 'Figure 15.18']),
  },
  {
    id: 'h15-1523-jk-uses-logic-expression', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.3', eyebrow: 'TABLE 15.7 · JK USES · 15.2.4',
    title: 'JK truth-table behaviour supports shift registers and binary counters; the chapter then returns to circuit-to-expression conversion',
    lead: 'When J=K=0 the state is unchanged; J=1,K=0 sets Q; J=0,K=1 resets Q; J=K=1 toggles Q after each clock pulse.',
    richBlocks: [{ kind: 'table', table: { caption: 'JK behaviour', headers: ['J','K','Effect'], rows: [['0','0','No change'],['1','0','Q becomes 1'],['0','1','Q becomes 0'],['1','1','Toggle']] } }],
    bullets: ['Multiple JK flip-flops can form shift registers.', 'Linked JK stages can form binary counters using toggle behaviour.', 'Section 15.2.4 derives Boolean expressions directly from circuits or from truth tables using SoP.'],
    visual: 'types', accent: 'emerald', ...source(361, ['Table 15.7 JK truth table', 'Shift registers', 'Binary counters', '15.2.4 Boolean algebra and logic circuits', 'Example 15.3']),
  },
  {
    id: 'h15-1524-expressions-sop', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.4', eyebrow: 'EXAMPLES 15.3–15.4 · SUM OF PRODUCTS',
    title: 'A complex circuit can be translated stage by stage, or reconstructed from truth-table rows where output = 1',
    lead: 'Example 15.3 labels intermediate stages; Example 15.4 forms an SoP expression from the truth table and simplifies it algebraically.',
    richBlocks: [{ kind: 'steps', title: 'Two source methods', items: [
      'Circuit-first: write an expression for each intermediate gate and substitute forward.',
      'Truth-table-first: select rows where X=1 and write one AND product for each row.',
      'OR the product terms to form SoP.',
      'Apply Boolean laws to simplify while preserving the same truth table.',
    ] }],
    visual: 'recap', accent: 'amber', ...source(362, ['Example 15.3 staged circuit expression', 'Example 15.4 truth table', 'Table 15.8', 'SoP simplification']),
  },
  {
    id: 'h15-1525-kmap-intro', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: '15.2.5 · K-MAPS · EXAMPLE 15.5',
    title: 'Karnaugh maps provide a visual alternative to lengthy Boolean-algebra simplification',
    lead: 'The source starts with the NAND truth table and maps its output-1 rows into a K-map using Gray-code ordering.',
    activity: { title: 'Activity 15D', prompt: 'Produce simplified Boolean expressions for the source logic circuits in Figures 15.21 and 15.22, using either direct circuit analysis or truth tables.' },
    visual: 'recap', accent: 'indigo', ...source(363, ['15.2.5 K-maps', 'Example 15.5 NAND truth table', 'Activity 15D', 'Extension Activity 15E Gray codes']),
  },
  {
    id: 'h15-1525-kmap-rules', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'K-MAP RULES · FIGURE 15.23',
    title: 'Group output-1 cells in the largest valid Gray-code-adjacent groups and keep only variables that remain constant',
    lead: 'The source simplifies NAND to NOT A + NOT B by grouping cells rather than expanding and manipulating every product term.',
    richBlocks: [{ kind: 'steps', title: 'Source K-map rules', items: [
      'Use Gray-code ordering around the map.',
      'Only cells containing 1 are included.',
      'Groups may be rows, columns or rectangles and should be as large as possible.',
      'Groups may overlap and can wrap across edges.',
      'Single 1s are allowed when no larger valid group is possible.',
      'A simplified term contains only variables that stay constant inside the group.',
    ] }],
    visual: 'recap', accent: 'cyan', ...source(364, ['Figure 15.23', 'Karnaugh map rules', 'NAND simplification']),
  },
  {
    id: 'h15-1525-kmap-3var', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'EXAMPLE 15.6 · THREE-VARIABLE K-MAP',
    title: 'A three-variable K-map turns four minterms into three simpler product terms',
    lead: 'The source’s grouped map keeps only variables constant within each ring, producing A.C + B.C + A.B.',
    richBlocks: [{ kind: 'steps', title: 'Read each group', items: ['Green group → A.C', 'Purple group → B.C', 'Red group → A.B', 'OR the group terms to obtain the simplified expression.'] }],
    visual: 'recap', accent: 'emerald', ...source(365, ['Example 15.6', 'Three-variable K-map', 'Simplified A.C + B.C + A.B']),
  },
  {
    id: 'h15-1525-kmap-4var', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'EXAMPLE 15.7 · FOUR-VARIABLE K-MAP',
    title: 'A four-variable map can collapse six minterms into just two product terms',
    lead: 'Example 15.7 maps the listed SoP values and simplifies the result to NOT A.NOT B + NOT C.D in the source notation.',
    bullets: ['Four-variable K-maps use Gray-code ordering on both axes.', 'Large groups remove changing variables.', 'The source result is obtained directly from two groups rather than repeated algebraic manipulation.'],
    visual: 'recap', accent: 'amber', ...source(366, ['Example 15.7', 'Four-variable K-map', 'SoP column', 'Simplified expression']),
  },
  {
    id: 'h15-1525-kmap-wrap', section: '15.2 Boolean algebra and logic circuits', subtopicCode: '15.2.5', eyebrow: 'FIGURES 15.19–15.22 · WRAP-AROUND GROUPS',
    title: 'K-map adjacency wraps across opposite edges, allowing cylinders and corner groups',
    lead: 'The source illustrates groups spanning columns 1 and 4, a horizontal wrap and the four corners; only variables constant across the chosen group remain in the term.',
    bullets: ['An eight-cell group can leave only one constant variable.', 'Opposite edge columns are adjacent under Gray-code ordering.', 'The four corners are mutually adjacent as a wrap-around group.', 'Different legal groupings can yield different intermediate terms while preserving equivalent logic.'],
    visual: 'recap', accent: 'rose', ...source(367, ['Figures 15.19–15.22', 'Vertical cylinder', 'Horizontal cylinder', 'Four-corner group']),
  },
  {
    id: 'h15-activity-kmap-review-start', section: 'Chapter review', eyebrow: 'ACTIVITY 15E · END-OF-CHAPTER START',
    title: 'The final activity combines truth tables, K-maps, simplified expressions and efficient circuit design',
    lead: 'Activity 15E asks learners to move both directions between expressions, truth tables, K-maps and circuits, including a four-input hexadecimal-condition problem.',
    activity: { title: 'Activity 15E', prompt: 'Choose one source expression, construct its truth table and K-map, derive the simplified expression and draw the corresponding AND/OR/NOT circuit.' },
    visual: 'recap', accent: 'indigo', ...source(368, ['Activity 15E', 'End of chapter questions', 'K-map/circuit conversion']),
  },
  {
    id: 'h15-review-boolean-flipflop', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS · BOOLEAN + FLIP-FLOPS',
    title: 'Review questions test K-map derivation, Boolean-law simplification and SR invalid-state reasoning',
    lead: 'The source asks learners to build a K-map from a four-input truth table, simplify two expressions and complete/explain an SR flip-flop truth table.',
    richBlocks: [{ kind: 'steps', title: 'Review focus', items: ['Truth table → K-map → Boolean expression.', 'Simplify with Boolean laws.', 'Complete SR set/reset/remember states.', 'Explain why one S,R combination must not be allowed.'] }],
    visual: 'recap', accent: 'cyan', ...source(369, ['End-of-chapter questions 2–3a', 'K-map', 'Boolean simplification', 'SR flip-flop truth table']),
  },
  {
    id: 'h15-review-parallel-jk', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS · JK + PARALLEL PROCESSING',
    title: 'The next review links JK behaviour to processor architectures, pipelining and massively parallel design',
    lead: 'Learners explain JK inputs/advantages/uses, classify SISD/SIMD/MISD/MIMD, discuss hardware/software constraints and compare pipelined versus sequential clock cycles.',
    bullets: ['The printed questions include material adapted from older Cambridge 9608 papers.', 'They remain coursebook review here rather than current live 9618 Past Paper checkpoints.'],
    visual: 'recap', accent: 'emerald', ...source(370, ['End-of-chapter questions 3b–5', 'SISD/SIMD/MISD/MIMD matching', 'Massively parallel', 'Pipelining', 'Cambridge 9608 Paper 32 Q4 November 2015']),
  },
  {
    id: 'h15-review-circuit-kmap', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTION 6 · CIRCUIT → TRUTH TABLE → K-MAP',
    title: 'The final review integrates every Boolean representation used in the chapter',
    lead: 'Starting from a three-input logic circuit, the task asks for its Boolean expression, full truth table, K-map, grouped SoP simplification and an algebraic proof using the stated identity plus De Morgan’s Laws.',
    richBlocks: [{ kind: 'steps', title: 'Representation chain', items: ['Logic circuit', 'Boolean expression', 'Truth table', 'K-map', 'Grouped sum of products', 'Simplified expression', 'Boolean-algebra proof'] }],
    visual: 'recap', accent: 'amber', ...source(371, ['End-of-chapter question 6', 'K-map', 'SoP', 'De Morgan’s Laws', 'Cambridge 9608 Paper 32 Q3 June 2017']),
  },
];

export const CHAPTER_15_FINAL: HodderLessonChapter = {
  number: 15,
  level: 'A Level',
  title: 'Hardware',
  subtitle: 'RISC/CISC and pipelining · parallel architectures · Boolean algebra · adders · flip-flops · Karnaugh maps',
  subtopics: ['15.1 Processors and parallel processing', '15.2 Boolean algebra and logic circuits'],
  sourceNote: 'Deep source-backed teaching route from the uploaded Hodder 9618 Chapter 15, printed pp.346–371. Every printed chapter page is represented in slide provenance and the source sequence, figures, examples, activities, truth tables and Boolean terminology are preserved as teaching paraphrase.',
  coverage: '26/26 printed chapter pages represented (pp.346–371): RISC/CISC, pipeline stages and interrupts; SISD/SIMD/MISD/MIMD, clusters and massively parallel systems; Boolean laws and De Morgan; half/full adders; SR/JK flip-flops; circuit/truth-table/SoP conversion; K-map rules, grouping and wrap-around examples; activities and end-of-chapter review.',
  slides: CHAPTER_15_DEEP_SLIDES,
};
