import type { LessonSourceAtom } from './lesson-source-atoms';

const detail = (
  id: string,
  chapter: 1 | 13,
  page: number,
  kind: LessonSourceAtom['kind'],
  sourceRef: string,
  targetSlideId: string,
  needles: string[],
): LessonSourceAtom => ({ id, chapter, page, kind, sourceRef, targetSlideId, needles });

/**
 * Additive source-detail layer for the exact user-supplied Hodder extracts.
 *
 * Existing lesson slides remain the primary classroom route. These atoms keep
 * source-specific definitions, explanatory relationships, worked constants,
 * lookup-table content and source-only nuances available in the presenter
 * source drawer so the PDF is not reduced to topic labels or a generic summary.
 */
export const SUPPLIED_PDF_DETAIL_ATOMS: LessonSourceAtom[] = [
  detail('ch1-p1-file-objectives',1,1,'concept','In this chapter, you will learn about','h1-prior',[
    'binary magnitudes, binary prefixes and decimal prefixes',
    'binary, denary and hexadecimal number systems',
    'how to carry out binary addition and subtraction',
    'the use of hexadecimal and binary coded decimal (BCD) number systems',
    'the representation of character sets (such as ASCII and Unicode)',
    'how data for a bit-mapped image is encoded',
    'how to estimate the file size for a bit-map image',
    'image resolution and colour depth',
    'encoding of vector graphics',
    'the representation of sound in a computer',
    'the effects of changing sampling rate and resolution on sound quality',
    'the need for file compression methods (such as lossy and lossless formats)',
    'how to compress common file formats (such as text files, bit-map images, vector graphics, sound files and video files)',
  ]),
  detail('ch1-p2-file-keyterms',1,2,'concept','1.1 Key terms','h1-111-number-systems',[
    'Binary – base two number system based on the values 0 and 1 only.',
    'Bit – abbreviation for binary digit.',
    'One’s complement – each binary digit in a number is reversed to allow both negative and positive numbers to be represented.',
    'Two’s complement – each binary digit is reversed and 1 is added in right-most position to produce another method of representing positive and negative numbers.',
    'Sign and magnitude – binary number system where left-most bit is used to represent the sign (0 = + and 1 = –); the remaining bits represent the binary value.',
    'Hexadecimal – a number system based on the value 16 (uses the denary digits 0 to 9 and the letters A to F).',
    'Memory dump – contents of a computer memory output to screen or printer.',
    'Binary-coded decimal (BCD) – number system that uses 4 bits to represent each denary digit.',
    'ASCII code – coding system for all the characters on a keyboard and control codes.',
    'Character set – a list of characters that have been defined by computer hardware and software; a coding method is needed so the computer can understand human characters.',
    'Unicode – coding system which represents all the languages of the world (first 128 characters are the same as ASCII code).',
  ]),
  detail('ch1-p2-file-number-model',1,2,'concept','1.1.1–1.1.2 Number systems','h1-111-number-systems',[
    'denary uses digits 0 to 9 in weighted columns',
    '31421 = 3×10000 + 1×1000 + 4×100 + 2×10 + 1',
    'decimal fractions are deferred to Chapter 13 because they are more complex',
    'computer switches map naturally to ON = 1 and OFF = 0',
    '8-bit binary column weights: 128, 64, 32, 16, 8, 4, 2, 1',
    '11101110 = 128 + 64 + 32 + 8 + 4 + 2 = 238',
  ]),
  detail('ch1-p3-file-conversion-complements',1,3,'concept','Denary↔binary and complements','h1-112-convert',[
    '107 by column selection → 01101011',
    '107 by successive division by 2 → remainders read from bottom to top → 01101011',
    'one’s complement example: 01011010 (+90) → 10100101 (−90)',
    'two’s complement example: 01011010 → invert 10100101 → add 1 → 10100110 (−90)',
    'the remainder of the chapter uses two’s complement because addition and subtraction are more straightforward',
    '8-bit two’s-complement weights: −128, 64, 32, 16, 8, 4, 2, 1',
  ]),
  detail('ch1-p4-file-signed-examples',1,4,'example','Signed-value source examples','h1-112-signed',[
    '11011010 = −128 + 64 + 16 + 8 + 2 = −38',
    '00100110 = 32 + 4 + 2 = 38',
    '104 = 01101000',
    'invert 01101000 → 10010111; add 1 → 10011000 = −104',
    'Example 1.1: 00100101 + 00111010 = 01011111 = 95',
  ]),
  detail('ch1-p5-file-overflow-subtraction',1,5,'concept','Overflow and subtraction source logic','h1-112-arithmetic',[
    '82 + 69 should be positive, but 01010010 + 01000101 = 10010111, interpreted as −105',
    '8-bit two’s complement has a maximum positive value of +127',
    '82 + 69 = 151, so the mathematical result is outside the available range and overflow occurs',
    'binary subtraction is performed by converting the number being subtracted to its two’s-complement negative and then adding',
    '95 − 68: 68 → 10111100 (−68); 01011111 + 10111100 produces a ninth carry bit',
    'the ninth bit is ignored in the fixed 8-bit result, leaving 00011011 = 27',
  ]),
  detail('ch1-p6-file-example-memory',1,6,'concept','Example 1.4 and memory-size introduction','h1-memory-units',[
    '49 − 80 = −31',
    '49 = 00110001; 80 = 01010000; −80 = 10110000; result = 11100001',
    'the source calls the byte the smallest unit of memory and describes larger 16-bit and 32-bit systems as multiples of 8',
    'memory size is discussed in larger multiples because one byte stores very little information',
  ]),
  detail('ch1-p7-file-prefix-tables',1,7,'table','Tables 1.1–1.2 · SI and IEC memory units','h1-memory-units',[
    '1 KB = 1,000 bytes; 1 MB = 1,000,000; 1 GB = 1,000,000,000; 1 TB = 1,000,000,000,000; 1 PB = 1,000,000,000,000,000',
    '1 KiB = 2^10 = 1,024 bytes; 1 MiB = 2^20 = 1,048,576; 1 GiB = 2^30 = 1,073,741,824',
    '1 TiB = 2^40 = 1,099,511,627,776; 1 PiB = 2^50 = 1,125,899,906,842,624',
    'the source distinguishes the SI base-10 storage convention from the IEC binary convention',
    '64 GiB = 64 × 2^30 = 68,719,476,736 bytes',
  ]),
  detail('ch1-p7-file-hex-weights',1,7,'concept','1.1.3 Hexadecimal number system','h1-113-hex',[
    'hexadecimal is base 16',
    'hex column weights: 16^5 = 1,048,576; 16^4 = 65,536; 16^3 = 4,096; 16^2 = 256; 16^1 = 16; 16^0 = 1',
    'A=10, B=11, C=12, D=13, E=14, F=15',
    'because 16 = 2^4, one hexadecimal digit corresponds exactly to four binary bits',
  ]),
  detail('ch1-p8-file-hex-table',1,8,'table','Table 1.3 · binary/hex/denary mapping','h1-113-hex',[
    '0000=0=0; 0001=1=1; 0010=2=2; 0011=3=3',
    '0100=4=4; 0101=5=5; 0110=6=6; 0111=7=7',
    '1000=8=8; 1001=9=9; 1010=A=10; 1011=B=11',
    '1100=C=12; 1101=D=13; 1110=E=14; 1111=F=15',
    'binary→hex: split from the right into groups of four; pad the left-most group with leading zeros if needed',
  ]),
  detail('ch1-p9-file-hex-memorydump',1,9,'concept','Hexadecimal conversion and memory dumps','h1-hex-uses',[
    'hex→binary: replace each hexadecimal digit with its four-bit binary code and join the groups',
    'B5A41AFC is more manageable for a human than 10110101101001000001101011111100',
    'memory contents output to a printer or monitor are called a memory dump',
    'hexadecimal is used in software development and fault tracing because it is a compact human-readable view of binary',
  ]),
  detail('ch1-p10-file-memorydump-table',1,10,'table','Table 1.4 · memory dump rows','h1-hex-uses',[
    '00990F60: 54 68 69 73 20 69 73 20 61 6E 20 65 78 61 6D 70 6C 65 20 6F 66',
    '00990F77: 61 20 6D 65 6D 6F 72 79 20 64 75 6D 70 20 66 72 6F 6D 20 20 61',
    '00990E8E: 74 79 70 69 63 61 6C 20 20 63 6F 6D 70 75 74 65 72 20 20 6D 85',
    '00990EA5: 6D 6F 72 79 20 73 68 6F 77 69 6E 67 20 74 68 65 20 20 63 6F 6E',
    '00990EBC: 74 65 6E 74 73 20 6F 66 20 61 20 6E 75 6D 62 65 72 20 20 6F 66',
    '00990ED3: 6C 6F 63 61 74 69 6F 6E 73 20 20 69 6E 20 20 68 65 78 20 20 20',
    '00990EEA: 6E 6F 74 61 74 69 6F 6E 20 20 00 00 00 00 00 00 00 00 00 00 00',
    'the far-left value is the memory location, allowing a developer to locate the fault precisely',
  ]),
  detail('ch1-p10-file-bcd-map',1,10,'table','1.1.4 BCD digit map','h1-114-bcd',[
    '0000=0; 0001=1; 0010=2; 0011=3; 0100=4',
    '0101=5; 0110=6; 0111=7; 1000=8; 1001=9',
    '3165 in BCD = 0011 0001 0110 0101',
    'BCD can be stored as one digit in a byte or packed as two four-bit digits in one byte',
  ]),
  detail('ch1-p11-file-bcd-use-correction',1,11,'concept','Uses of BCD and decimal correction','h1-bcd-uses',[
    'BCD is used for calculator/clock displays because each denary digit maps directly to a four-bit code',
    'the source motivates BCD for accounting because exact fixed-point monetary digits should not accumulate binary-representation error',
    '$0.37 + $0.94 should equal $1.31',
    'ordinary binary addition produces invalid BCD digit values 12 and 11 for the decimal columns',
    'when a four-bit BCD digit result is not a valid denary digit, add 0110 (denary 6)',
    'a fifth bit generated by the correction is carried into the next decimal digit position',
  ]),
  detail('ch1-p12-file-bcd-ascii-history',1,12,'concept','BCD completion and ASCII history','h1-115-ascii',[
    'the worked BCD correction finishes at 00000001.00110001, which represents 1.31',
    'ASCII = American Standard Code for Information Interchange',
    'the source dates ASCII setup to 1963 and a newer version to 1986',
    'standard ASCII uses 7-bit codes 0–127 denary (00–7F hex)',
    'codes 0–31 denary are 32 control codes',
  ]),
  detail('ch1-p13-file-ascii-table',1,13,'table','Table 1.5 · standard ASCII visible range','h1-115-ascii',[
    '32/20 SPACE through 63/3F ?',
    '64/40 @; 65/41 A through 90/5A Z; 91/5B [; 92/5C \\; 93/5D ]; 94/5E ^; 95/5F _',
    '96/60 `; 97/61 a through 122/7A z; 123/7B {; 124/7C |; 125/7D }; 126/7E ~; 127/7F DELETE',
    'a=61 hex and A=41 hex; y=79 hex and Y=59 hex',
    'the sixth bit changes from 1 to 0 between the shown lower/upper-case pairs',
    'alphabetic and numeric character sets are grouped in sequence, which makes processing easier',
    'extended ASCII uses 8-bit values 128–255 (80–FF hex)',
  ]),
  detail('ch1-p14-file-unicode-detail',1,14,'concept','Extended ASCII and Unicode source detail','h1-115-unicode',[
    'extended ASCII adds non-English and drawing characters in the range 128–255',
    'Unicode supports characters for languages worldwide and overlaps standard ASCII for the first 128 characters',
    'the source contrasts ASCII as one byte per character with Unicode supporting up to four bytes per character',
    'Unicode Consortium set up in 1991',
    'Version 1.0 goals: universal coverage; greater efficiency than ASCII; uniform 16/32-bit codes; unambiguous values; private-use allocation',
    'the source explicitly notes that ASCII tables/extensions are not fully standardised and variants exist',
  ]),
  detail('ch1-p15-file-multimedia-keyterms',1,15,'concept','1.2 Multimedia key terms','h1-bitmap-resolution',[
    'Bit-map image – system that uses pixels to make up an image.',
    'Pixel – smallest picture element that makes up an image.',
    'Colour depth – number of bits used to represent the colours in a pixel; 8-bit colour depth can represent 2^8 = 256 colours.',
    'Bit depth – number of bits used to represent the smallest unit in a sound or image file; larger bit depth gives better sound/colour quality.',
    'Image resolution – number of pixels that make up an image; 4096 × 3192 = 12,738,656 pixels.',
    'Screen resolution – number of horizontal and vertical pixels in a screen display.',
    'Resolution – number of pixels per column and per row on a monitor or television screen.',
    'Pixel density – number of pixels per square centimetre.',
    'Vector graphics – images using 2D points to describe lines/curves and their properties, grouped into geometric shapes.',
    'Sampling resolution – number of bits used to represent sound amplitude (bit depth).',
    'Sampling rate – number of sound samples taken per second.',
    'Frame rate – number of video frames that make up a video per second.',
  ]),
  detail('ch1-p16-file-bitmap-detail',1,16,'concept','1.2.1 Bitmap source detail','h1-bitmap-resolution',[
    'at least 8 bits (1 byte) per pixel gives 256 possible colours in the source example',
    'true colour is described as 3 bytes / 24 bits per pixel',
    '8 bits per pixel → 256 colours; 32 bits per pixel → 4,294,967,296 possible values',
    'image resolution refers to the pixel dimensions of the image; screen resolution refers to the display pixel dimensions',
    'Figure 1.1 image resolution = 4096 × 3192; example screen = 1920 × 1080',
    'software may remove pixels, crop the image or rotate/crop it to fit the screen',
  ]),
  detail('ch1-p17-file-scaling-size-detail',1,17,'concept','Pixel density and bitmap file size','h1-bitmap-size',[
    'a lower-resolution 1024 × 798 copy can fit a 1920 × 1080 display, but enlargement can make it pixelated',
    'magnifying a bitmap does not create more stored pixels; each pixel covers a larger physical area and sharpness can decrease',
    'Figure 1.3 shows the same wheel enlarged from A to E until pixels become visually obvious',
    'higher resolution increases file size, storage demand, download time and device-to-device transfer time',
    'the source links tolerable resolution reduction to properties of human vision',
    '1920 × 1080 × 24 = 49,766,400 bits = 6,220,800 bytes ≈ 6.222 MB or 5.933 MiB',
  ]),
  detail('ch1-p18-file-vector-detail',1,18,'concept','1.2.2 Vector graphics source detail','h1-122-vector',[
    'bitmap header examples: file type (.bmp/.jpeg), file size, image resolution, bit depth, compression method',
    'vector graphics use 2D points for lines/curves grouped into geometric shapes',
    'a drawing list contains each object command plus attributes such as centres/radius, line thickness/style/colour and fill colour',
    'relative positions between objects are stored so a vector graphic can scale without loss of quality',
    'vector graphics are commonly converted to a bitmap before printing to match printer formats',
    'vector formats listed: .svg, .cgm, .odg; bitmap formats listed: .jpeg, .bmp, .png',
    'choice questions: resize? draw to scale? realism? file restrictions?',
  ]),
  detail('ch1-p19-file-sound-physics',1,19,'concept','1.2.3 Sound files source detail','h1-123-sound-wave',[
    'sound needs a medium and cannot travel in a vacuum',
    'sound is transmitted by oscillations of particles / pressure changes in the medium',
    'frequency and wavelength describe a sound wave; amplitude specifies loudness',
    'sound is analogue and must be digitised for computer storage using an analogue-to-digital converter (ADC)',
    'music input may be filtered to remove frequencies outside the human hearing range before digitisation',
    'sampling measures amplitude at set time intervals and stores approximate values',
  ]),
  detail('ch1-p20-file-sampling-editing-video',1,20,'concept','Sampling, editing and video source detail','h1-sampling-quality',[
    'Figure 1.6 uses time intervals 0–20 and an amplitude range 0–10; values above 10 and below 0 are filtered in the example',
    'time interval 1 ≈ amplitude 9; time interval 2 ≈ amplitude 4; 9 is represented as 1001',
    'a larger amplitude range such as 0–127 gives a more accurate sampled representation than 0–10',
    'higher sampling rate and/or sampling resolution increases file size',
    '16-bit sampling resolution is given as the CD recording example',
    'sampling sequence: determine amplitude at set intervals → obtain an approximation → encode the samples as binary',
    'Table 1.9 pros: larger dynamic range, better sound quality, less distortion; cons: larger file, longer transfer, more processing power',
    'editing features include timing edits, extraction/deletion, frequency/amplitude changes, fade, mix/merge, noise removal and format conversion',
    '1.2.4 Video is explicitly beyond the syllabus; source example uses motion JPEG at 25 MB per second',
  ]),
  detail('ch1-p21-file-compression-keyterms',1,21,'concept','1.3 File compression key terms','h1-131-mp3-jpeg',[
    'Lossless file compression – original file can be restored following decompression.',
    'Lossy file compression – parts of the original file cannot be recovered during decompression.',
    'JPEG – lossy photographic compression based on the eye not spotting certain colour changes and hues.',
    'MP3/MP4 files – compression formats used for music and multimedia files.',
    'Audio compression – method used to reduce sound-file size using perceptual music shaping.',
    'Perceptual music shaping – removes sounds such as those outside normal human hearing during compression.',
    'Bit rate – number of bits per second transmitted over a network; a data-transfer-rate measure.',
    'Run length encoding (RLE) – a lossless technique used particularly for text and photo files.',
    'file compression reduces storage space and/or transmission/streaming time',
    'MP3 source example: an 80 MB CD music file reduced to 8 MB, about 90%',
  ]),
  detail('ch1-p22-file-codec-rle-detail',1,22,'concept','MP3/MP4/JPEG/SVG/RLE source detail','h1-131-mp3-jpeg',[
    'perceptual shaping can remove frequencies outside human hearing and the softer of two simultaneous sounds when it is masked by the louder sound',
    'MP3 is lossy; the original file cannot be reconstructed exactly',
    'MP3 bit-rate range in the source: 80–320 kbit/s; around 200 kbit/s or higher is described as close to normal-CD quality',
    'MP4 can hold music, video, photos and animation and can be used for internet video streaming',
    'JPEG is lossy; source gives a simplified raw-bitmap reduction factor of about 5–15 depending on quality',
    'SVG is defined in XML text and can therefore be compressed',
    'RLE is lossless/reversible and stores a repeated run as count + data-item code',
    'RLE is effective only where there are sufficiently long runs of adjacent identical data',
  ]),
  detail('ch1-p23-file-rle-detail',1,23,'concept','RLE text and black/white image details','h1-rle-text',[
    'aaaaabbbbccddddd → 05 97 04 98 02 99 05 100; 16 bytes → 8 bytes',
    'poor-run example cdcdcdcdcd motivates use of a flag',
    'flag example uses 255 before an encoded run; unflagged bytes are interpreted at face value',
    'aaaaaaaa bbbbbbbbbb cdcdcd eeeeeeee: original 32 bytes; unflagged coding 18 values; flagged coding 15 values ≈ 53% reduction',
    'Figure 1.7 uses an 8×8 black/white grid, W=1 and B=0',
    '64 uncompressed cells versus 30 RLE values in the simplified Figure 1.7 model',
  ]),
  detail('ch1-p24-file-colour-rle-general',1,24,'concept','Colour RLE and general file-size reduction','h1-rle-images',[
    'Figure 1.8 four-colour RGB codes: black 0,0,0; white 255,255,255; green 0,255,0; red 255,0,0',
    '8 × 8 × 3 = 192 uncompressed RGB values/bytes in the source classroom model',
    'RLE code uses 92 values, giving about 52% reduction',
    'real compressed files save less because additional data such as a file header must also be stored',
    'general reduction methods: reduce sampling rate; reduce sampling resolution; reduce frame rate; crop image; decrease colour/bit depth; reduce image resolution',
  ]),
  detail('ch1-p25-file-review-scope',1,25,'review','Activity 1I and end-of-chapter Q1–Q2 source scope','h1-hodder-review',[
    'Activity 1I revisits lossless/lossy compression, microphone digitisation, RLE and bitmap-versus-vector choice',
    'Q1 assesses two’s-complement interpretation/range plus BCD representation and use',
    'Q2 assesses sampling resolution, image resolution, 16-colour bit depth, a 16,384 × 512 256-colour bitmap size in GiB, bitmap header items and sound-editing features',
  ]),
  detail('ch1-p26-file-review-scope',1,26,'review','End-of-chapter Q3–Q6 source scope','h1-hodder-review',[
    'Q3 combines sound sampling, email compression choice and RLE on a grey/white image with grey=85 and white=255',
    'Q4 uses 60, 27 and −27 in 8-bit two’s complement and asks why 01011001 + 01100001 does not give the expected signed result',
    'Q5 uses 0.52 + 0.83 in BCD plus hexadecimal definition/uses and 0111111011110010 conversion',
    'Q6 converts 95 to BCD, evaluates 00100011 − 01000100 using two’s complement, and converts 506 to hexadecimal',
  ]),

  detail('ch13-p1-file-objectives',13,1,'concept','In this chapter, you will learn about','h13-prior-131',[
    'user-defined data types',
    'the definition and use of non-composite and composite data types',
    'the choice and design of an appropriate user-defined data type for a given problem',
    'methods of file organisation, such as serial, sequential and random',
    'methods of file access, such as sequential and direct access',
    'hashing algorithms',
    'binary floating-point real numbers',
    'converting binary floating-point real numbers into denary numbers',
    'converting denary numbers into binary floating-point real numbers',
    'the normalisation of binary floating-point numbers',
    'how underflow and overflow can occur',
    'how binary representation can lead to rounding errors',
  ]),
  detail('ch13-p2-file-keyterms-enum',13,2,'concept','13.1 Key terms and enumerated type','h13-enum',[
    'User-defined data type – a data type based on an existing data type or other data types that have been defined by a programmer.',
    'Non-composite data type – a data type that does not reference any other data types.',
    'Enumerated data type – a non-composite data type defined by a given list of all possible values that has an implied order.',
    'Pointer data type – a non-composite data type that uses the memory address of where the data is stored.',
    'Set – a given list of unordered elements that can use set theory operations such as intersection and union.',
    'TYPE <identifier> = (value1, value2, value3, ...)',
    'type names usually begin with T to aid the programmer',
    'enumeration values are not strings, so the source does not enclose them in quotation marks',
    'TYPE Tmonth = (January, February, March, April, May, June, July, August, September, October, November, December)',
    'thisMonth ← January; nextMonth ← thisMonth + 1; nextMonth is now February',
  ]),
  detail('ch13-p3-file-pointer-detail',13,3,'concept','Pointer data type and dereferencing','h13-pointer',[
    'a pointer references a memory location and must specify the type of data expected there',
    'TYPE <pointer> = ^<Typename>',
    'TYPE TmonthPointer = ^Tmonth',
    'monthPointer ← ^thisMonth stores the address of thisMonth',
    'myMonth ← monthPointer^ dereferences the pointer and obtains the contents of the referenced location',
    'a composite data type refers to another data type in its type definition',
  ]),
  detail('ch13-p4-file-composite-detail',13,4,'concept','Records, sets and classes source detail','h13-sets-classes',[
    'printed TbookRecord shows title, author, publisher, noPages and fiction fields; printed noPages and fiction are STRING',
    'TYPE <set-identifier> = SET OF <Basetype>',
    'DEFINE <identifier> (value1, value2, value3, ... ) : <set-identifier>',
    "TYPE Sletter = SET OF CHAR; printed example: DEFINE vowel ('a', 'e', 'i', 'o', 'u') : letters",
    'a class contains variables of given types plus methods; an object is defined from a class and several objects can share one class definition',
    'classes and objects are considered in more depth in Chapter 20',
  ]),
  detail('ch13-p5-file-keyterms-serial',13,5,'concept','13.2 Key terms and serial organisation','h13-file-terms',[
    'Serial file organisation – records are physically stored one after another in the order they were added.',
    'Sequential file organisation – records are physically stored one after another in a given order.',
    'Random file organisation – records are stored in any available position and located using a hashing algorithm on the key field.',
    'Hashing algorithm (file access) – a mathematical formula on the key field whose result gives the address where the record should be found.',
    'File access – the method used to physically find a record in the file.',
    'Sequential access – records searched one after another from the physical start until the required record is found.',
    'Direct access – a record can be physically found without physically reading other records.',
    'serial files append new records to the end and are useful for temporary transaction files such as gas/electricity meter readings',
    'arrival order makes the serial transaction records chronological',
  ]),
  detail('ch13-p6-file-org-access-detail',13,6,'concept','Sequential/random organisation and sequential access','h13-sequential',[
    'sequential organisation usually orders records by a unique key field, such as ascending customer number',
    'new sequential records must be inserted in the correct physical position',
    'random organisation stores a new record in any empty position and uses a hash of the key to locate it',
    'sequential access is used with serial and sequential files',
    'serial search continues until the record is found or the whole file has been searched',
    'ordered sequential search can stop when the current key becomes greater than the target key',
  ]),
  detail('ch13-p7-file-access-hash-detail',13,7,'concept','Sequential/direct access and hashing','h13-direct-access',[
    'Customer 6 search stops at Customer 7, proving Customer 6 is absent from an ascending sequential file',
    'sequential access is efficient for high-hit-rate processing such as monthly billing or payroll',
    'direct access is useful for low-hit-rate work such as updating one customer telephone number',
    'a sequential file may use an index of key fields to physical addresses for direct access',
    'a random file uses a hashing algorithm on the key to calculate a physical address',
    'simple source hash example: 2000 record slots, key range 1–9999, key 3024 → remainder 1024 → address 1024',
    'more complex hashing algorithms are also used in data encryption',
  ]),
  detail('ch13-p8-file-collision-detail',13,8,'concept','Hash collision and retrieval checks','h13-hash-collision',[
    'key 5024 gives the same remainder/address 1024 as key 3024, creating a collision',
    'open hash: store the record in the next free space',
    'closed hash: use a separate overflow area and store in its next free space',
    'when reading by direct access, the key stored at the calculated address must be checked against the requested key before the record is accepted',
    'for an open hash, continue through following records until the matching key is found; for a closed hash, search the overflow area',
    'names can be hashed by adding character ASCII values and using a modulus-style calculation',
  ]),
  detail('ch13-p9-file-prior-full',13,9,'prior','13.3 complete prior-knowledge set','h13-prior-133',[
    'Q1 denary→binary: +48, +122, −100, −55, −2',
    'Q2 binary→denary: 00110011, 01111110, 10110011, 11110010, 11111111',
    'Q3 two’s-complement negatives: 00110100, 00011101, 01001100, 00111111, 01111110',
    'Q4 additions: 00110001+00011110; 01000001+00111111; 00111100+01000101; 01111101+01011100; 11101100+01100000',
    'Q4 continued: 10001111+10011111; 01000101+10111100; 01111110+01111110; 11111100+11100011; 11001100+00011111',
    'Q5 standard form: 123000000; 2505000000000000; −1200; 0.000000002341; −0.0000124005',
    'Q6 improper denary fractions: 21/5; 117/4; 558/20; improper binary fractions: 11/2; 41/4; 52/4',
  ]),
  detail('ch13-p10-file-float-keyterms',13,10,'concept','13.3 Key terms and representation model','h13-float-format',[
    'Mantissa – the fractional part of a floating-point number.',
    'Exponent – the power of 2 that the mantissa is raised to in a floating-point number.',
    'Normalisation (floating-point) – a method to improve precision; positive mantissas should begin 0.1 and negative mantissas 1.0.',
    'Overflow – a calculation produces a value too large for the allocated word size.',
    'Underflow – a calculation produces a value too small for the allocated word size.',
    'Binary floating-point number – a binary number written in the form M × 2^E.',
    'fixed-point examples: 8-bit two’s-complement range −128..+127; 16-bit source example −16,384..+16,383',
    'chapter examples use an 8-bit mantissa and 8-bit exponent with an assumed binary point between the first and second mantissa bits',
  ]),
  detail('ch13-p11-file-example131-detail',13,11,'example','Example 13.1 source methods','h13-float-to-denary',[
    '01011010 00000100',
    'mantissa M = 45/64; exponent E = 4; M × 2^E = 11.25',
    'Method 2: write mantissa 0.1011010 and move the binary point four places right → 01011.010 → 11.25',
    'Example 13.2 begins with 00101000 00000011',
  ]),
  detail('ch13-p12-file-example132133-detail',13,12,'example','Examples 13.2–13.3 source methods','h13-float-to-denary',[
    'Example 13.2: 00101000 00000011 → M = 5/16, E = 3 → 2.5',
    'Method 2 for Example 13.2: 0.0101000 moved three places right → 0010.1000 → 2.5',
    'Example 13.3 introduces a negative mantissa: 11001100 00001100',
    'M = −13/32, E = 12 → −1664',
  ]),
  detail('ch13-p13-file-negative-float-detail',13,13,'example','Examples 13.3–13.4 negative conversion detail','h13-float-to-denary',[
    'negative mantissa Method 2 first converts the mantissa magnitude using two’s complement',
    'Example 13.3: 11001100 → 00110100 magnitude form, interpreted as −0.0110100; exponent 12 moves the point 12 places right → −1664',
    'Example 13.4: 11001100 11111100',
    'Example 13.4 exponent = −4, so the binary point moves four places left',
    'Example 13.4 denary value = −0.025390625',
  ]),
  detail('ch13-p14-file-activity13f-example135',13,14,'example','Activity 13F and Example 13.5 start','h13-denary-to-float',[
    'Activity 13F uses ten 8-bit-mantissa / 8-bit-exponent values and asks for denary conversion',
    'Example 13.5 converts +4.5 to binary floating point',
    'Method 1: 4.5 = 9/2; divide the denominator by successive powers of 2 until 9/16 < 1',
    '9/16 × 2^3 gives mantissa 0.1001 and exponent 3',
  ]),
  detail('ch13-p15-file-example135136-detail',13,15,'example','Examples 13.5–13.6 source methods','h13-denary-to-float',[
    '+4.5 → 01001000 00000011',
    'Method 2 for +4.5: 0100.1 → move point three places left → 0.1001 × 2^3',
    '+0.171875 = 11/64',
    'Method 1 gives mantissa 0.0010110 and exponent 0 before normalising-style point movement',
    'Method 2: 0.001011 moved two places right to 0.1011, so exponent is −2',
  ]),
  detail('ch13-p16-file-example136137-detail',13,16,'example','Examples 13.6–13.7 source detail','h13-denary-to-float',[
    '−2 in 8-bit two’s complement: 00000010 → 11111101 + 1 = 11111110',
    'Example 13.6 final value: 01011000 11111110',
    'Example 13.7 converts −10.375 = −83/8',
    '−83/8 → −83/128 × 2^4; mantissa = 1.0101101; exponent = 4',
    'Example 13.7 final value: 10101101 00000100',
  ]),
  detail('ch13-p17-file-activity13g-approx',13,17,'concept','Activity 13G and approximation introduction','h13-approximation',[
    'Activity 13G part 1 asks for supplied M × 2^E values in 8-bit mantissa/exponent form',
    'Activity 13G part 2 values: +3.5, 0.3125, 15.375, 41/64, 9.125, −15/32, −3.5, −10.25, −1.046875, −3 11/32',
    'fractions linked to powers of two can be represented exactly in the worked system',
    '5.88 cannot be represented exactly with the 8-bit mantissa used in the example',
    'the source notes that a 16-bit mantissa could approximate 5.88 as 5.875, better than the 8-bit example',
  ]),
  detail('ch13-p18-file-588-detail',13,18,'example','5.88 repeated-doubling approximation','h13-approximation',[
    'fraction .88 is repeatedly multiplied by 2 to obtain successive binary fraction bits',
    '.88×2=1.76 → 1; .76×2=1.52 → 1; .52×2=1.04 → 1; .04×2=0.08 → 0',
    '.08×2=0.16 → 0; .16×2=0.32 → 0; .32×2=0.64 → 0; .64×2=1.28 → 1',
    '5.88 ≈ 0101.11100001; with the 8-bit mantissa limit this is stored as 0.1011100 00000011',
    'stored value = 23/32 × 2^3 = 23/4 = 5.75',
    'Extension Activity 13D values: 1.63, 8.13, 12.32, 5.90, 7.40',
  ]),
  detail('ch13-p19-file-normalisation-rules',13,19,'concept','Normalisation rules and worked examples','h13-normalisation',[
    'multiple bit patterns can represent the same value, motivating normalisation',
    'positive normalised mantissa must begin 0.1',
    'negative normalised mantissa must begin 1.0',
    'shift mantissa bits left until the required leading pattern is reached and reduce the exponent by one for each left shift',
    'Example 13.8: 0.0011100 00000101 → 0.1110000 00000011',
    'Example 13.9: 1.1101100 00001010 → 1.0110000 00001000',
  ]),
  detail('ch13-p20-file-precision-range-extremes',13,20,'concept','Figures 13.10–13.13 · 8/8 precision and range','h13-precision-range',[
    'maximum positive: 01111111 01111111 = 127/128 × 2^127',
    'smallest positive: 01000000 10000000 = 1/2 × 2^−128',
    'smallest-magnitude negative: 10111111 10000000 = −65/128 × 2^−128',
    'largest-magnitude negative: 10000000 01111111 = −1 × 2^127',
    'more mantissa bits increase accuracy/precision',
    'more exponent bits increase range',
    'with fixed word size, precision and range trade off against each other',
  ]),
  detail('ch13-p21-file-allocation-rounding',13,21,'concept','Figures 13.14–13.16 and rounding-error discussion','h13-precision-range',[
    '12-bit mantissa + 4-bit exponent → high accuracy but small range',
    '8-bit mantissa + 8-bit exponent → reduced accuracy but increased range',
    '4-bit mantissa + 12-bit exponent → poor accuracy but extremely high range',
    'finite mantissa size makes some stored values approximate',
    'double precision and quadruple precision can reduce approximation problems where supported',
    'Extension Activity 13E repeatedly adds 0.1 and asks why values such as 0.399999 may appear instead of 0.4',
  ]),
  detail('ch13-p22-file-over-under-zero-detail',13,22,'concept','Overflow, underflow and normalised zero','h13-over-under-zero',[
    'overflow occurs when a calculation exceeds the largest representable mantissa/exponent value; dividing by a very small number or zero can trigger it',
    'underflow occurs when division by a very large number produces a result smaller than the smallest representable value',
    'the source notes a normalised-zero problem because positive mantissas must begin 0.1 and negative mantissas 1.0',
    'Activity 13I asks largest positive/smallest magnitude for 10-bit mantissa + 6-bit exponent',
    'Activity 13I also asks about a 32-bit mantissa/exponent allocation, 1.21×10^100 versus a 10^99 maximum, possible y=0 in x/y, and approximate storage of 2.88 and −5.38',
  ]),
  detail('ch13-p23-file-review-detail',13,23,'review','End-of-chapter Q1–Q4a source detail','h13-hodder-review-1',[
    'Q1 uses a 24-bit floating word and asks values A/B/C, which value is not normalised, why normalise, accuracy/range and zero representation',
    'Q2 uses 12-bit mantissa + 6-bit exponent: 011100100000 000111 and 101001110000 111100; then +4.75 and −8.375',
    'Q3 uses 8-bit mantissa + 8-bit exponent, both two’s complement, to represent +3.5 and −3.5',
    'Q4a uses TYPE Tseason = (Spring, Summer, Autumn, Winter) and TJournalRecord and asks for enumerated/composite/non-composite/user-defined identification',
  ]),
  detail('ch13-p24-file-review-detail',13,24,'review','End-of-chapter Q4b–Q5 source detail','h13-hodder-review-2',[
    'Q4b declares Journal : TJournalRecord and assigns Spring Flowers; H Williams; XYZ Press; 40; Spring',
    'Q5a connects random/sequential/serial organisation to direct/sequential access methods',
    'Q5b energy-company File A: account number + current-month meter readings; each submitted reading adds a new record',
    'File B: customer personal data used at month end to create electricity/cost statements',
    'File C: usernames + encrypted passwords used when customers log in',
    'all three file organisation methods must be different and each choice justified',
  ]),
];
