import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 11 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

export const CHAPTER_11_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h11-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 11 · PROGRAMMING',
    title: 'Turn a designed algorithm into clear program structure using identifiers, constructs, procedures and functions',
    lead: 'The chapter moves from variables/constants and library routines to selection, loops and reusable subroutines, always comparing pseudocode with Python, VB.NET and Java.',
    richBlocks: [{ kind: 'steps', title: 'Chapter route', items: [
      'Declare and initialise constants and variables.',
      'Use built-in and standard-library routines.',
      'Choose IF/CASE selection structures.',
      'Choose count-controlled, post-condition and pre-condition loops.',
      'Define and call procedures.',
      'Pass parameters by value or by reference where supported.',
      'Define and use functions that return values.',
    ] }],
    keyTerms: [
      { term: 'Constant', definition: 'A named value that cannot change during execution.' },
      { term: 'Variable', definition: 'A named value that can change during execution.' },
      { term: 'Procedure', definition: 'A reusable group of statements called when needed.' },
      { term: 'Function', definition: 'A reusable group of statements that returns a value.' },
      { term: 'Library routine', definition: 'A tested ready-to-use routine supplied by a programming-language development system.' },
    ],
    activity: { title: 'Prior knowledge check', prompt: 'Design an algorithm to input ten numbers, sort them, search for 27 and output both the sorted list and whether 27 was found.' },
    visual: 'types', accent: 'indigo', ...source(264, ['Chapter learning objectives', 'What you should already know', '11.1 Programming basics', 'Chapter key terms']),
  },
  {
    id: 'h11-111-constants-variables', section: '11.1 Programming basics', subtopicCode: '11.1.1', eyebrow: '11.1.1 · CONSTANTS + VARIABLES · EXAMPLE 11.1',
    title: 'Declare identifiers before use and make the starting state explicit',
    lead: 'The source distinguishes constants from variables and recommends an identifier list so every required item has a declaration and a starting value before data manipulation begins.',
    richBlocks: [{ kind: 'table', table: { caption: 'Sphere example identifiers', headers: ['Identifier', 'Role'], rows: [
      ['radius', 'Stores the input radius'],
      ['volume', 'Stores calculated volume'],
      ['surfaceArea', 'Stores calculated surface area'],
      ['pi', 'Constant set to 3.142 in the source example'],
    ] } }],
    example: { title: 'Pseudocode declarations', lines: ['DECLARE radius : REAL', 'DECLARE volume : REAL', 'DECLARE surfaceArea : REAL', 'CONSTANT pi ← 3.142'] },
    visual: 'types', accent: 'cyan', ...source(265, ['11.1.1 Constants and variables', 'Example 11.1', 'Identifier table', 'Sphere problem']),
  },
  {
    id: 'h11-111-sphere-algorithm', section: '11.1 Programming basics', subtopicCode: '11.1.1', eyebrow: 'EXAMPLE 11.1 · INPUT → VALIDATE → PROCESS → OUTPUT',
    title: 'The sphere example demonstrates a complete algorithm pipeline before language-specific code',
    lead: 'The radius is prompted for and validated as positive, then the volume and surface area are calculated and output.',
    richBlocks: [{ kind: 'steps', title: 'Sphere algorithm', items: [
      'Prompt for radius and input it.',
      'Use a WHILE loop to reject values less than or equal to zero.',
      'Calculate volume from radius and pi.',
      'Calculate surface area from radius and pi.',
      'Output both results.',
    ] }],
    example: { title: 'Core processing', lines: ['volume ← (4 / 3) * pi * radius * radius * radius', 'surfaceArea ← 4 * pi * radius * radius'] },
    visual: 'recap', accent: 'emerald', ...source(266, ['Sphere validation pseudocode', 'Table 11.1 constants/variables across languages', 'Python/VB.NET/Java declarations']),
  },
  {
    id: 'h11-111-language-io-processing', section: '11.1 Programming basics', subtopicCode: '11.1.1', eyebrow: 'TABLES 11.2–11.4 · INPUT + VALIDATION + PROCESSING',
    title: 'Python, VB.NET and Java use different syntax while preserving the same algorithmic intent',
    lead: 'The source compares how each language handles input, a radius-validation loop and the sphere calculations.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Algorithm concept', rightTitle: 'Language-specific detail', rows: [
      ['Input radius', 'Python combines prompt/conversion; VB.NET and Java use separate prompt/input steps.'],
      ['Validate positive input', 'Each language provides a loop form that can repeat until the radius is valid.'],
      ['Calculate results', 'Operators are similar, but declarations and numeric types differ.'],
    ] }],
    visual: 'types', accent: 'amber', ...source(267, ['Table 11.2 input statements', 'Table 11.3 radius checking', 'Table 11.4 volume/surface-area calculations']),
  },
  {
    id: 'h11-111-output-programs', section: '11.1 Programming basics', subtopicCode: '11.1.1', eyebrow: 'TABLE 11.5 · COMPLETE PROGRAMS',
    title: 'Output syntax and program scaffolding differ even when the same values are displayed',
    lead: 'The source compares output statements and then presents full Python and VB.NET versions of the sphere solution.',
    bullets: [
      'Python output examples separate text and values with commas.',
      'VB.NET combines text and values using its string-concatenation syntax.',
      'Java uses its own concatenation syntax in System.out.println.',
      'The important teaching point is to preserve the same input-validation-processing-output logic across languages.',
    ],
    visual: 'types', accent: 'indigo', ...source(268, ['Table 11.5 output statements', 'Complete Python sphere program', 'Complete VB.NET sphere program']),
  },
  {
    id: 'h11-111-java-builtins', section: '11.1 Programming basics', subtopicCode: '11.1.1', eyebrow: 'JAVA PROGRAM · ACTIVITY 11A · DIV + MOD',
    title: 'The chapter closes the sphere example with Java, then introduces useful built-in operations',
    lead: 'Activity 11A asks learners to extend the solution to repeat calculations and stop on -1; the page also introduces DIV and MOD before moving to string processing.',
    richBlocks: [{ kind: 'table', table: { caption: 'Built-in examples from the source', headers: ['Routine', 'Meaning'], rows: [['DIV(10,3)', 'Integer part of the division → 3'], ['MOD(10,3)', 'Remainder → 1']] } }],
    activity: { title: 'Activity 11A', prompt: 'Implement the sphere algorithm, then extend it so calculations repeat and stop when -1 is input. Test 4.7, 34, -11, 0 and -1.' },
    visual: 'types', accent: 'rose', ...source(269, ['Complete Java sphere program', 'Activity 11A', 'DIV', 'MOD', 'String manipulation introduction']),
  },
  {
    id: 'h11-111-password-functions', section: '11.1 Programming basics', subtopicCode: '11.1.1', eyebrow: 'EXAMPLE 11.2 · LENGTH / LEFT / RIGHT / MID',
    title: 'String functions make a nested password check precise and testable',
    lead: 'Example 11.2 checks the input length and then compares the first and last characters with the stored password.',
    richBlocks: [{ kind: 'table', table: { caption: 'String functions introduced', headers: ['Function', 'Purpose'], rows: [
      ['LENGTH', 'Return string length'],
      ['LEFT', 'Return characters from the left'],
      ['RIGHT', 'Return characters from the right'],
      ['MID', 'Return a substring from a stated position and length'],
    ] } }],
    example: { title: 'Nested selection idea', lines: ['IF size = LENGTH(storedPassword)', '  THEN compare LEFT(...) and RIGHT(...)', '  ELSE reject input', 'ENDIF'] },
    visual: 'types', accent: 'cyan', ...source(270, ['Example 11.2', 'Password identifier table', 'LENGTH', 'RIGHT', 'LEFT', 'MID', 'Nested IF']),
  },
  {
    id: 'h11-112-library-routines', section: '11.1 Programming basics', subtopicCode: '11.1.2', eyebrow: 'TABLE 11.6 · 11.1.2 LIBRARY ROUTINES',
    title: 'Standard libraries provide tested routines that can be incorporated instead of rewritten',
    lead: 'The source compares string operations in Python, VB.NET and Java and explains that an IDE normally includes standard routines for common tasks such as input/output.',
    bullets: [
      'A library routine is ready to use and already tested.',
      'Language development systems can supply standard functions and procedures.',
      'The same conceptual string operation can have different syntax in different languages.',
    ],
    activity: { title: 'Activities 11B–11C', prompt: 'Test the password example with Sad, Cheese, Secret and secret, then identify at least six routines in your programming language’s standard library.' },
    visual: 'types', accent: 'emerald', ...source(271, ['Table 11.6 string manipulation by language', 'Activity 11B', '11.1.2 Library routines', 'Activity 11C', '11.2.1 CASE and IF intro']),
  },
  {
    id: 'h11-1121-case-model', section: '11.2 Programming constructs', subtopicCode: '11.2.1', eyebrow: '11.2.1 · CASE + IF · FIGURE 11.1',
    title: 'CASE improves clarity when one identifier can lead to several distinct choices',
    lead: 'Figure 11.1 shows that alternatives may be based on a condition, a range, an exact value, or an OTHERWISE branch.',
    richBlocks: [{ kind: 'steps', title: 'Menu example logic', items: ['Input choice.', 'Match exact values 1, 2 and 3 to individual routines.', 'Match a range such as 4…6 to a shared action.', 'Handle 10 as Exit.', 'Use OTHERWISE for any unmatched value.'] }],
    example: { title: 'CASE pattern', lines: ['CASE choice OF', '  1 : OUTPUT "Routine 1"', '  4 … 6 : OUTPUT "Routine not written"', '  10 : Exit', '  OTHERWISE OUTPUT "Incorrect choice"', 'ENDCASE'] },
    visual: 'recap', accent: 'indigo', ...source(272, ['Figure 11.1', 'CASE choice menu example', 'Condition/range/value/OTHERWISE']),
  },
  {
    id: 'h11-1121-case-languages', section: '11.2 Programming constructs', subtopicCode: '11.2.1', eyebrow: 'TABLE 11.7 · VB + JAVA CASE FORMS',
    title: 'VB.NET and Java implement the same multi-choice idea using different keywords',
    lead: 'The source contrasts VB.NET Select Case with Java switch, including Java break and default versus VB.NET Case Else.',
    bullets: [
      'VB.NET uses Select Case and Case Else.',
      'Java uses switch, case labels, break and default.',
      'The book notes that the Python version used for the course does not use this construct in the same way.',
    ],
    visual: 'types', accent: 'cyan', ...source(273, ['Table 11.7 case statements', 'VB.NET Select Case', 'Java switch', 'break', 'default']),
  },
  {
    id: 'h11-1122-loops', section: '11.2 Programming constructs', subtopicCode: '11.2.2', eyebrow: 'ACTIVITY 11D · 11.2.2 LOOPS · TABLE 11.8',
    title: 'Select a loop according to whether repetition count is known and when the condition should be tested',
    lead: 'The source distinguishes count-controlled FOR, post-condition REPEAT–UNTIL and pre-condition WHILE–DO–ENDWHILE loops.',
    richBlocks: [{ kind: 'table', table: { caption: 'Loop choice', headers: ['Loop', 'Best fit'], rows: [
      ['FOR … NEXT', 'Number of repetitions is known'],
      ['REPEAT … UNTIL', 'Body must run at least once; useful for validation'],
      ['WHILE … DO … ENDWHILE', 'Condition must be tested before the body runs'],
    ] } }],
    activity: { title: 'Activity 11D', prompt: 'Design a four-operation calculator for +, -, * and /, rejecting any other operator, then implement it using the same identifiers.' },
    visual: 'recap', accent: 'amber', ...source(274, ['Activity 11D', '11.2.2 Loops', 'FOR/REPEAT/WHILE comparison', 'Table 11.8 post-condition loops']),
  },
  {
    id: 'h11-113-procedure-basics', section: '11.3 Structured programming', subtopicCode: '11.3.1', eyebrow: 'TABLE 11.9 · 11.3 STRUCTURED PROGRAMMING · PROCEDURES',
    title: 'Structured programming replaces repeated statement groups with named reusable procedures',
    lead: 'The page introduces procedure-related terms and defines a procedure once so it can be called many times.',
    keyTerms: [
      { term: 'Parameter', definition: 'A variable in a procedure/function interface used to receive a value.' },
      { term: 'Argument', definition: 'The actual value supplied in a call.' },
      { term: 'By value', definition: 'The called routine receives a value without changing the caller’s variable through that parameter.' },
      { term: 'By reference', definition: 'The called routine can change the caller’s variable through the parameter.' },
      { term: 'Header', definition: 'The first line of the routine definition containing its name, parameters and, for a function, return type.' },
    ],
    example: { title: 'Procedure definition pattern', lines: ['PROCEDURE <identifier>', '  <statements>', 'ENDPROCEDURE'] },
    activity: { title: 'Activity 11E', prompt: 'Write and test a program that accepts only input values from 0 to 10 inclusive.' },
    visual: 'types', accent: 'emerald', ...source(275, ['Table 11.9 pre-condition loops', 'Activity 11E', '11.3 Structured programming key terms', '11.3.1 Procedures']),
  },
  {
    id: 'h11-1131-calls-parameters', section: '11.3 Structured programming', subtopicCode: '11.3.1', eyebrow: 'TABLES 11.10–11.11 · PROCEDURE CALLS',
    title: 'A procedure call reuses the definition; parameters make one procedure useful for many values',
    lead: 'The stars example shows a procedure definition, language-specific equivalents and the syntax for calling a procedure repeatedly.',
    richBlocks: [{ kind: 'steps', title: 'Procedure progression', items: ['Define a stars procedure.', 'Call it whenever the output is needed.', 'Add a Number parameter when the number of stars must vary.', 'Match call arguments to definition parameters by count, position and type.'] }],
    activity: { title: 'Activity 11F', prompt: 'Write a short program in your chosen language to define and call a procedure that outputs a line of stars.' },
    visual: 'types', accent: 'indigo', ...source(276, ['Table 11.10 procedure definitions', 'Activity 11F', 'Table 11.11 procedure calls', 'Parameterized procedure syntax']),
  },
  {
    id: 'h11-1131-parameter-passing', section: '11.3 Structured programming', subtopicCode: '11.3.1', eyebrow: 'TABLE 11.12 · BY VALUE VS BY REFERENCE',
    title: 'The procedure interface must match, and the passing method determines whether the caller’s variable can change',
    lead: 'The source extends stars(Number) and then distinguishes by-value from by-reference parameters.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'By value', rightTitle: 'By reference', rows: [
      ['The routine receives a value.', 'The routine can work through a reference to the caller’s variable.'],
      ['Changing the parameter does not change the caller’s variable through that parameter.', 'Changing the parameter can change the caller’s variable.'],
    ] }],
    activity: { title: 'Activity 11G', prompt: 'Extend your program so the stars procedure accepts a parameter controlling how many stars are printed.' },
    visual: 'types', accent: 'cyan', ...source(277, ['Table 11.12 procedure with parameter', 'Activity 11G', 'By value', 'By reference']),
  },
  {
    id: 'h11-1131-byref-functions-intro', section: '11.3 Structured programming', subtopicCode: '11.3.1', eyebrow: 'TABLE 11.13 · BYREF · 11.3.2 FUNCTIONS',
    title: 'A BYREF procedure can modify its argument; a function is different because it always returns a value',
    lead: 'The Celsius procedure demonstrates BYREF in pseudocode, then the chapter transitions to functions and their role on the right-hand side of expressions.',
    example: { title: 'BYREF temperature conversion', lines: ['PROCEDURE celsius(BYREF temperature : REAL)', '  temperature ← (temperature - 32) / 1.8', 'ENDPROCEDURE', 'CALL celsius(myTemp)'] },
    activity: { title: 'Activity 11H', prompt: 'Write pseudocode for a procedure with a parameter passed by reference that converts Celsius to Fahrenheit.' },
    visual: 'types', accent: 'amber', ...source(278, ['Table 11.13 parameter passing', 'Activity 11H', '11.3.2 Functions', 'Function key concept']),
  },
  {
    id: 'h11-1132-functions', section: '11.3 Structured programming', subtopicCode: '11.3.2', eyebrow: 'FUNCTION · RETURNS · RETURN',
    title: 'Functions return typed values and are used as part of expressions',
    lead: 'The source gives generic function forms with and without parameters, then a substring example with alternative RETURN paths and a Celsius conversion function.',
    richBlocks: [{ kind: 'code', title: 'Function patterns', lines: [
      'FUNCTION <identifier> RETURNS <data type>',
      '  <statements>',
      '  RETURN <value>',
      'ENDFUNCTION',
      '',
      'FUNCTION celsius(temperature : REAL) RETURNS REAL',
      '  RETURN (temperature - 32) / 1.8',
      'ENDFUNCTION',
      'myTemp ← celsius(myTemp)',
    ] }],
    bullets: ['RETURN specifies the function result.', 'A function call can appear inside a larger expression.', 'Arguments must match the header parameters in position and type.'],
    visual: 'types', accent: 'rose', ...source(279, ['Function without parameters', 'Function with parameters', 'RETURN', 'substring example', 'Celsius function']),
  },
  {
    id: 'h11-1132-language-functions-review-start', section: '11.3 Structured programming', subtopicCode: '11.3.2', eyebrow: 'TABLE 11.14 · ACTIVITY 11I · ROUTINE HEADERS',
    title: 'The procedure/function distinction is visible in both the header and how the routine is called',
    lead: 'Table 11.14 compares the Celsius function across languages, and Activity 11I asks learners to choose whether a procedure or function is the better design.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Procedure call', rightTitle: 'Function call', rows: [['Standalone statement', 'Forms part of an expression'], ['May change state or perform actions', 'Always returns a value']] }],
    activity: { title: 'Activity 11I', prompt: 'Rewrite the Celsius-to-Fahrenheit task as a function with a parameter, test it, and justify whether procedure or function is the better structure.' },
    visual: 'types', accent: 'indigo', ...source(280, ['Table 11.14 functions by language', 'Activity 11I', 'Procedure/function headers and arguments', 'End-of-chapter question 1']),
  },
  {
    id: 'h11-review-triangle-library-subroutines', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS 2–7',
    title: 'The main review combines validation, calculations, menus, library routines and subroutine terminology',
    lead: 'The right-angled-triangle tasks require input validation and the SQUAREROOT library routine, then the review tests distinctions among procedures, functions, parameters and headers.',
    richBlocks: [{ kind: 'steps', title: 'Review route', items: [
      'Validate height and width against positive maximum values.',
      'Use SQUAREROOT to calculate a hypotenuse.',
      'Calculate area and perimeter.',
      'Provide a menu for selecting calculations.',
      'Explain library routines and give two uses.',
      'Explain procedure, function, parameter and header.',
      'Compare procedure vs function, by value vs by reference, and definition vs call.',
    ] }],
    visual: 'recap', accent: 'cyan', ...source(281, ['End-of-chapter questions 2–7', 'SQUAREROOT', 'Triangle calculations', 'Library routine', 'Procedure/function comparisons', 'Car depreciation question 7a']),
  },
  {
    id: 'h11-review-car-depreciation', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTION 7(b) · CAR VALUE LOOP',
    title: 'The final review integrates variables, WHILE conditions and first-year versus later-year selection',
    lead: 'The incomplete algorithm predicts a car’s value, applying a 40% first-year reduction and 20% later reductions until age or value termination criteria are reached.',
    richBlocks: [{ kind: 'steps', title: 'Reasoning required', items: [
      'Initialise CurrentValue from PurchasePrice.',
      'Start YearCount at 1.',
      'Continue only while both the age and minimum-value conditions allow another year.',
      'Use IF to distinguish the first year from later years.',
      'Output year and value after each calculation.',
      'Advance the year counter.',
    ] }],
    activity: { title: 'Complete and trace', prompt: 'Complete the missing pseudocode from the printed design, then trace the first three years for a sample purchase price.' },
    visual: 'recap', accent: 'amber', ...source(282, ['End-of-chapter question 7b', 'Car depreciation pseudocode', 'Cambridge 9608 Paper 21 Q5 November 2015']),
  },
];

export const CHAPTER_11_FINAL: HodderLessonChapter = {
  number: 11,
  level: 'AS Level',
  title: 'Programming',
  subtitle: 'Constants and variables · library routines · selection and loops · procedures, parameters and functions',
  subtopics: ['11.1 Programming basics', '11.2 Programming constructs', '11.3 Structured programming'],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 Chapter 11 in the connected full coursebook, printed pp.264–282. Every printed chapter page is represented in slide provenance and the source examples, activities, language comparisons and structured-programming terminology are preserved as teaching paraphrase.',
  coverage: '19/19 printed chapter pages represented (pp.264–282): constants/variables and the sphere example; language-specific declaration/input/validation/output; DIV/MOD and password string functions; library routines; CASE and loop selection; procedures and calls; parameters by value/reference; functions and RETURN; Activities 11A–11I; and the complete chapter-review sequence including the older printed 9608 car-depreciation problem.',
  slides: CHAPTER_11_DEEP_SLIDES,
};
