import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const pageRange = (start: number, end: number) => Array.from({ length: end - start + 1 }, (_, index) => start + index);
const source = (start: number, end: number = start, elements: string[] = []) => ({
  sourcePages: pageRange(start, end),
  sourceLabel: `Hodder Chapter 19 · pp.${start}${end === start ? '' : `–${end}`}`,
  sourceElements: [`Hodder pp.${start}${end === start ? '' : `–${end}`}`, ...elements],
});

export const CHAPTER_19_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h19-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 19 · COMPUTATIONAL THINKING AND PROBLEM SOLVING',
    title: 'The chapter moves from core algorithms to data structures, complexity and recursion',
    lead: 'The source revisits search/sort algorithms, then implements ADTs in code, compares algorithmic performance with Big O notation and finishes with recursive problem solving and compiler stack behaviour.',
    bullets: [
      'Implement linear and binary search and state the condition required for binary search.',
      'Implement bubble and insertion sort and compare their behaviour.',
      'Find, insert and delete data in stacks, queues, linked lists and binary trees.',
      'Explain graphs and dictionaries and how one ADT can be built from another.',
      'Compare time and space complexity using Big O notation.',
      'Write and trace recursive algorithms and explain winding/unwinding and stack use.',
    ],
    visual: 'recap', accent: 'indigo', ...source(450, 451, ['Chapter objectives', 'Prior knowledge', 'Key terms']),
  },
  {
    id: 'h19-1911-linear-search', section: '19.1 Algorithms', subtopicCode: '19.1.1', eyebrow: '19.1.1 · LINEAR SEARCH · TABLE 19.1',
    title: 'Linear search checks items in order and does not require the list to be sorted',
    lead: 'The source repeats the Chapter 10 pseudocode and identifier table, then implements the same routine in Python, VB and Java.',
    bullets: [
      'Start at the lower bound and compare each element with the item being searched for.',
      'Stop when the item is found or the upper bound is passed.',
      'The found flag records whether a match occurred.',
      'As the list grows, average retrieval time grows correspondingly.',
    ],
    activity: { title: 'Activity 19A', prompt: 'Write the linear search in your chosen language, then change it to use a loop structure similar to the source pseudocode.' },
    visual: 'recap', accent: 'cyan', ...source(451, 454, ['Table 19.1', 'Python/VB/Java linear search', 'Activity 19A']),
  },
  {
    id: 'h19-1911-binary-search', section: '19.1 Algorithms', subtopicCode: '19.1.1', eyebrow: 'BINARY SEARCH · FIGURE 19.2 · TABLES 19.2–19.4',
    title: 'Binary search repeatedly discards half of an ordered list',
    lead: 'The alphabet example contrasts up to 23 linear comparisons for W with only three binary-search comparisons in the illustrated route.',
    bullets: [
      'Binary search requires the data to be sorted.',
      'Test the middle item; if the target is larger, raise lowerBound; if smaller, lower upperBound.',
      'Repeat until the item is found or the remaining search interval is exhausted.',
      'The chapter notes that a list of 1024 elements may need only a small number of binary comparisons compared with up to 1024 linear comparisons.',
    ],
    activity: { title: 'Activities 19B–19C', prompt: 'Compare linear/binary comparisons for letters, then implement the binary search and test it with the source data for one present and one absent value.' },
    visual: 'recap', accent: 'emerald', ...source(454, 457, ['Figure 19.2', 'Tables 19.2–19.4', 'Activities 19B–19C']),
  },
  {
    id: 'h19-1912-bubble-sort', section: '19.1 Algorithms', subtopicCode: '19.1.2', eyebrow: '19.1.2 · BUBBLE SORT · TABLE 19.5',
    title: 'Bubble sort repeatedly compares adjacent items and swaps those in the wrong order',
    lead: 'The source uses a swap flag and a shrinking top boundary to avoid rechecking the already-sorted end of the array.',
    bullets: [
      'Adjacent elements are exchanged when the left value is greater than the right value.',
      'swap records whether the current pass made any change.',
      'top moves left after each pass because the largest unsorted value has moved to its final region.',
      'The loop can terminate early when no swaps occur.',
    ],
    visual: 'types', accent: 'indigo', ...source(458, 460, ['Table 19.5', 'Python/VB/Java bubble sort']),
  },
  {
    id: 'h19-1912-insertion-sort', section: '19.1 Algorithms', subtopicCode: '19.1.2', eyebrow: 'INSERTION SORT · FIGURE 19.3 · TABLE 19.7',
    title: 'Insertion sort places each new element into its correct position within the already-sorted prefix',
    lead: 'The source highlights insertion sort as useful for incremental or partially sorted data and traces every array change in Figure 19.3.',
    bullets: [
      'Take the current key and compare it with earlier elements.',
      'Move larger earlier values right until the correct insertion position is available.',
      'Insert the key at place + 1.',
      'For the source array, insertion sort performs fewer swaps than the referenced bubble-sort trace.',
    ],
    activity: { title: 'Activity 19D', prompt: 'Implement insertion sort in your chosen programming language. The extension asks groups to investigate and compare other sorting methods.' },
    visual: 'types', accent: 'amber', ...source(461, 464, ['Figure 19.3', 'Table 19.7', 'Activity 19D', 'Extension Activity 19A']),
  },
  {
    id: 'h19-1913-stack', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: '19.1.3 · ADTs · STACK',
    title: 'A stack implementation combines a fixed array with pointers and push/pop subroutines',
    lead: 'The source gives equivalent data structures and operations in Python, VB and Java, including empty/full checks.',
    bullets: [
      'topPointer identifies the top of the stack; basePointer identifies the base.',
      'push first checks capacity, increments topPointer and stores the item.',
      'pop first checks for an empty stack, retrieves the top item and decrements topPointer.',
      'Stack overflow/underflow conditions are handled explicitly in the example code.',
    ],
    activity: { title: 'Activity 19E', prompt: 'Implement a 10-element stack, test normal push/pop operations, then deliberately test empty-pop and full-push boundary cases.' },
    visual: 'types', accent: 'cyan', ...source(464, 466, ['Tables 19.8–19.10', 'Activity 19E']),
  },
  {
    id: 'h19-1913-queue', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'CIRCULAR QUEUE · ENQUEUE · DEQUEUE',
    title: 'A circular queue reuses array positions by wrapping its front and rear pointers',
    lead: 'The source implementation tracks frontPointer, rearPointer, queueLength and queueFull, with separate enqueue/dequeue routines in all three languages.',
    bullets: [
      'enqueue checks that the queue is not full before advancing/wrapping rearPointer.',
      'dequeue checks that the queue is not empty before reading the front item and advancing/wrapping frontPointer.',
      'queueLength distinguishes empty/full state even when pointer positions wrap around.',
    ],
    activity: { title: 'Activity 19F', prompt: 'Implement the 10-element queue and test normal enqueue/dequeue, empty removal and full insertion exactly as the source specifies.' },
    visual: 'types', accent: 'emerald', ...source(466, 469, ['Tables 19.11–19.13', 'Activity 19F']),
  },
  {
    id: 'h19-1913-linked-list-find', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'LINKED LIST · START POINTER · HEAP POINTER',
    title: 'The linked-list representation separates stored values from the pointers that define logical order',
    lead: 'The source initialises a pointer heap, shows empty and populated diagrams, then traverses from startPointer until an item or nullPointer is reached.',
    bullets: [
      'myLinkedList stores values while myLinkedListPointers stores links.',
      'startPointer identifies the first logical node.',
      'heapStartPointer identifies the first free node in the free-space list.',
      'The find function returns the node pointer when found or the null pointer when absent.',
    ],
    activity: { title: 'Activity 19G', prompt: 'Create the populated linked list in your chosen language and use the source find routine to locate an item.' },
    visual: 'files', accent: 'indigo', ...source(469, 474, ['Figures 19.5–19.6', 'Table 19.14', 'Activity 19G']),
  },
  {
    id: 'h19-1913-linked-list-insert', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'LINKED-LIST INSERTION · FIGURES 19.7–19.8',
    title: 'Insertion takes the next free heap node, stores the value and rewires pointers without moving the other data',
    lead: 'The procedure preserves the old start pointer, promotes the heap head to become the new list head and advances heapStartPointer.',
    bullets: [
      'First check for a full list: heapStartPointer equals nullPointer.',
      'Save the old start pointer in a temporary pointer.',
      'Take the first free node from the heap and update heapStartPointer.',
      'Store the item and link the new node to the previous list head.',
    ],
    activity: { title: 'Activity 19H', prompt: 'Trace insertion of 25, show the linked list and pointer arrays before/after, then add the insert procedure to your program.' },
    visual: 'files', accent: 'cyan', ...source(474, 477, ['Tables 19.16–19.17', 'Figures 19.7–19.8', 'Activity 19H']),
  },
  {
    id: 'h19-1913-linked-list-delete', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'LINKED-LIST DELETION · RETURN NODE TO HEAP',
    title: 'Deletion bypasses the target node and returns that node to the free-space heap',
    lead: 'The source search keeps both the current index and the previous index so the predecessor can be linked directly to the target’s successor.',
    bullets: [
      'Check for an empty list and search for the requested value.',
      'Keep oldIndex so the previous node can be rewired.',
      'Move the deleted node to the front of the heap/free list.',
      'Update the predecessor pointer to bypass the removed node.',
    ],
    activity: { title: 'Activity 19I', prompt: 'Trace removal of 16 and add the delete procedure to your program, printing values and pointers before and after deletion.' },
    visual: 'files', accent: 'rose', ...source(477, 481, ['Linked-list delete pseudocode', 'Python/VB/Java delete code', 'Activity 19I']),
  },
  {
    id: 'h19-1913-binary-tree-model', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'BINARY TREE · ROOT · LEFT/RIGHT CHILD',
    title: 'An ordered binary tree stores each item at a node with at most two child branches',
    lead: 'Values smaller than the current node branch left; values greater than or equal branch right. The source also represents an arithmetic expression as a binary tree.',
    bullets: [
      'Root node begins the hierarchy; leaf nodes have no children.',
      'Left and right subtrees preserve the source ordering rule.',
      'Binary trees are used in syntax analysis, compression and 3D games in the source examples.',
      'Figure 19.11 shows how operators and operands form an expression tree.',
    ],
    activity: { title: 'Activities 19J–19K', prompt: 'Draw the requested expression tree, then define a binary-tree data structure capable of storing at least 50 names.' },
    visual: 'files', accent: 'indigo', ...source(481, 482, ['Figures 19.10–19.12', 'Activities 19J–19K', 'Extension Activity 19B']),
  },
  {
    id: 'h19-1913-binary-tree-find', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'BINARY-TREE SEARCH · TABLES 19.20–19.21',
    title: 'Tree search follows left/right pointers according to the ordering relation',
    lead: 'The find function starts at rootPointer and follows only one branch at each comparison until the item is found or a null pointer is reached.',
    activity: { title: 'Activity 19L', prompt: 'Use the source algorithm to search for 55 and 75 in myTree and record each step in a trace table.' },
    visual: 'files', accent: 'cyan', ...source(482, 483, ['Table 19.20', 'Table 19.21', 'Activity 19L']),
  },
  {
    id: 'h19-1913-binary-tree-insert', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'BINARY-TREE INSERTION · FREE-NODE HEAP',
    title: 'Tree insertion follows the ordering path to a null branch, then attaches the next free node as a leaf',
    lead: 'The source expands myTree with free nodes chained through a pointer field, then traces insertion of 18.',
    bullets: [
      'Take itemAddPointer from nextFreePointer.',
      'Walk down the tree while remembering oldPointer and whether the final branch is left or right.',
      'Attach the free node to that branch and initialise both child pointers to null.',
      'Store itemAdd in the new leaf and advance the free-node pointer.',
    ],
    activity: { title: 'Activity 19M', prompt: 'Trace insertion of 25 into myTree and show the final tree data structure.' },
    visual: 'files', accent: 'emerald', ...source(484, 487, ['Figures 19.13–19.14', 'Tables 19.22–19.23', 'Activity 19M']),
  },
  {
    id: 'h19-1913-graphs', section: '19.1 Algorithms', subtopicCode: '19.1.3', eyebrow: 'GRAPH · NODE · EDGE · PATH · CYCLE · WEIGHT',
    title: 'Graphs model networks with nodes and edges, optionally adding direction and weight',
    lead: 'The source relates graphs to bus routes, websites and social networks and links back to the shortest-path work in Chapter 18.',
    bullets: [
      'An undirected edge works in both directions; a directed edge has a direction.',
      'A weight can represent distance, cost or another quantity associated with an edge.',
      'A path is a sequence of connected nodes; a cycle returns to the starting node.',
    ],
    activity: { title: 'Activity 19N', prompt: 'Use the source bus-route graph to find another School-to-Gardens path, the shortest Town-centre-to-Train-station path and the shortest cycle from Town centre.' },
    visual: 'recap', accent: 'amber', ...source(487, 487, ['Figures 19.15–19.16', 'Activity 19N']),
  },
  {
    id: 'h19-1914-adt-from-adt', section: '19.1 Algorithms', subtopicCode: '19.1.4', eyebrow: '19.1.4 · IMPLEMENTING ONE ADT FROM ANOTHER',
    title: 'An ADT definition can embed other data types or ADTs as part of its representation',
    lead: 'The source defines a linked-list type and then uses it as part of a dictionary representation, reinforcing that an ADT combines data with operations.',
    activity: { title: 'Activity 19O', prompt: 'Declare a linked list that stores names, set it up for 30 names and write a program to store/display those names.' },
    visual: 'types', accent: 'indigo', ...source(488, 488, ['Linked-list type', 'Dictionary from another ADT', 'Activity 19O']),
  },
  {
    id: 'h19-1914-dictionary', section: '19.1 Algorithms', subtopicCode: '19.1.4', eyebrow: 'DICTIONARY · KEY/VALUE PAIRS · TABLE 19.24',
    title: 'A dictionary retrieves a value by a unique key; values themselves may repeat',
    lead: 'The source contrasts the abstract definition with built-in/high-level implementations in the prescribed languages.',
    bullets: [
      'Keys are unique and the dictionary is not treated as an ordered list.',
      'The same value may be associated with more than one different key.',
      'The chapter notes implementation differences among Python, VB and Java/hash-table approaches.',
    ],
    activity: { title: 'Activity 19P', prompt: 'Store student names as keys and examination scores as values, then find, add and delete dictionary entries.' },
    visual: 'types', accent: 'cyan', ...source(488, 489, ['Table 19.24', 'Activity 19P']),
  },
  {
    id: 'h19-1915-big-o-time', section: '19.1 Algorithms', subtopicCode: '19.1.5', eyebrow: '19.1.5 · BIG O · TIME COMPLEXITY',
    title: 'Big O describes how worst-case resource growth changes with input size rather than measuring one run time',
    lead: 'The source compares standard growth orders so learners can reason about scalability as the input size increases.',
    richBlocks: [{ kind: 'table', table: { caption: 'Source time-complexity examples', headers: ['Order', 'Source example'], rows: [
      ['O(1)', 'A task taking constant time, such as testing whether a number is odd/even.'],
      ['O(N)', 'Linear search.'],
      ['O(N²)', 'Bubble sort and insertion sort.'],
      ['O(2^N)', 'The recursive Fibonacci example in the source table.'],
      ['O(log N)', 'Binary search.'],
    ] } }],
    visual: 'recap', accent: 'emerald', ...source(489, 489, ['Table 19.25', 'Big O time complexity']),
  },
  {
    id: 'h19-1915-big-o-space', section: '19.1 Algorithms', subtopicCode: '19.1.5', eyebrow: 'BIG O · SPACE COMPLEXITY · ACTIVITY 19Q',
    title: 'Space complexity describes how memory requirements grow as input size grows',
    lead: 'The chapter separates memory growth from execution-time growth and uses fixed versus input-sized storage as the key contrast.',
    bullets: [
      'O(1) space: the algorithm uses a fixed amount of working storage.',
      'O(N) space: storage grows in direct proportion to the number of items, such as an N-element array.',
      'Activity 19Q asks learners to connect ADT structure with Big O search comparison.',
    ],
    activity: { title: 'Activity 19Q', prompt: 'Draw and explain a binary tree and linked list, explain a dictionary built from a linked list, and compare linear versus binary search with Big O notation.' },
    visual: 'recap', accent: 'amber', ...source(490, 490, ['Table 19.26', 'Activity 19Q']),
  },
  {
    id: 'h19-1921-recursion-basics', section: '19.2 Recursion', subtopicCode: '19.2.1', eyebrow: '19.2.1 · RECURSION · BASE CASE · GENERAL CASE',
    title: 'A recursive routine defines a terminating base case and a general case that calls itself on a smaller/subproblem value',
    lead: 'The factorial example uses 0! = 1 as the base case and n! = n × (n−1)! as the general case.',
    keyTerms: [
      { term: 'Winding', definition: 'Recursive calls accumulate until the base case is reached.' },
      { term: 'Unwinding', definition: 'Return values are resolved after the base case has been reached.' },
    ],
    visual: 'recap', accent: 'indigo', ...source(490, 491, ['Recursion key terms', 'Factorial base/general cases']),
  },
  {
    id: 'h19-1921-factorial-trace', section: '19.2 Recursion', subtopicCode: '19.2.1', eyebrow: 'FACTORIAL TRACE · TABLE 19.27',
    title: 'Tracing 3! makes winding and unwinding visible as separate phases',
    lead: 'Calls for 3, 2, 1 and 0 wind toward the base case; returned values then unwind to produce 1, 2 and 6.',
    bullets: ['The chapter provides equivalent recursive factorial functions in Python, VB and Java.'],
    activity: { title: 'Activity 19R', prompt: 'Implement factorial recursively, test 0! and 5!, then complete trace tables and compare them with the program outputs.' },
    visual: 'recap', accent: 'cyan', ...source(491, 492, ['Table 19.27', 'Python/VB/Java factorial', 'Activity 19R']),
  },
  {
    id: 'h19-1921-recursive-examples', section: '19.2 Recursion', subtopicCode: '19.2.1', eyebrow: 'COMPOUND INTEREST · FIBONACCI · BENEFITS/RISKS',
    title: 'The source extends recursion beyond factorial to compound interest and Fibonacci',
    lead: 'These examples reinforce how a base case stops recursion while the general case reduces the problem and builds a chain of calls.',
    bullets: [
      'Compound interest is expressed with a years=0 base case and a recursive general case.',
      'Activity 19S asks learners to identify Fibonacci base/general cases and trace the fourth term.',
      'Recursive solutions can be shorter and can express complex self-similar problems clearly.',
      'Repeated recursive calls heavily use the stack and can cause stack overflow.',
    ],
    activity: { title: 'Activity 19S / Extension 19C', prompt: 'Write the Fibonacci recursive pseudocode, trace a small term, then implement and test the source-specified terms in your chosen language.' },
    visual: 'recap', accent: 'emerald', ...source(493, 493, ['Tables 19.28–19.29', 'Activity 19S', 'Extension Activity 19C']),
  },
  {
    id: 'h19-1922-compiler-stack', section: '19.2 Recursion', subtopicCode: '19.2.2', eyebrow: '19.2.2 · COMPILER IMPLEMENTATION · STACK',
    title: 'Compiled recursive code pushes return addresses and local state while winding, then pops them while unwinding',
    lead: 'Each recursive call needs its own saved execution context so the earlier call can resume correctly after the deeper call returns.',
    activity: { title: 'Activity 19T', prompt: 'Explain recursion and its benefits, then explain why compiler-generated recursive code requires a stack.' },
    visual: 'recap', accent: 'rose', ...source(494, 494, ['Activity 19T', 'Compiler recursion stack']),
  },
  {
    id: 'h19-review', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS · ALGORITHMS + ADTs',
    title: 'The printed review integrates insertion/bubble sort, queue-as-linked-list operations and pointer manipulation',
    lead: 'The final pages contain coursebook review questions adapted from the older Cambridge 9608 syllabus; they are retained as source study material rather than relabelled as current live 9618 checkpoints.',
    bullets: [
      'Complete and analyse insertion-sort pseudocode.',
      'Improve a bubble sort to remove unnecessary comparisons.',
      'Trace a queue ADT implemented as a linked list of nodes.',
      'Complete pointer initialisation and AddName/RemoveName queue procedures.',
    ],
    activity: { title: 'Review practice', prompt: 'Choose one sorting question and one pointer/queue question from pp.494–497 and complete all pseudocode with a trace or diagram.' },
    visual: 'recap', accent: 'indigo', ...source(494, 497, ['End-of-chapter questions', 'Cambridge 9608 review material']),
  },
];

export const CHAPTER_19_FINAL: HodderLessonChapter = {
  number: 19,
  level: 'A Level',
  title: 'Computational thinking and problem solving',
  subtitle: 'Search and sort · ADTs · graphs and dictionaries · Big O · recursion',
  subtopics: [
    '19.1 Algorithms',
    '19.2 Recursion',
  ],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 full coursebook, printed pp.450–497. Every printed chapter page is represented in slide provenance; search/sort code, stack/queue/list/tree pointer operations, graph/dictionary material, Big O tables, recursion traces and printed review are preserved as teaching paraphrase.',
  coverage: '48/48 printed chapter pages represented (pp.450–497): linear/binary search; bubble/insertion sort; stack and circular queue implementations; linked-list find/insert/delete; binary-tree model/search/insert; graphs; ADTs implemented from other ADTs and dictionaries; Big O time/space complexity; recursion with factorial, compound interest and Fibonacci; compiler stack behaviour and end-of-chapter review.',
  slides: CHAPTER_19_DEEP_SLIDES,
};
