import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[] = []) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 7 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

const sourceRange = (from: number, to: number, elements: string[] = []) => ({
  sourcePages: Array.from({ length: to - from + 1 }, (_, index) => from + index),
  sourceLabel: `Hodder Chapter 7 · pp.${from}–${to}`,
  sourceElements: [`Hodder pp.${from}–${to}`, ...elements],
});

export const CHAPTER_7_DEEP_SLIDES: HodderLessonSlide[] = [
  {
    id: 'h7-overview', section: 'Chapter overview', eyebrow: 'CHAPTER 7 · ETHICS AND OWNERSHIP',
    title: 'Professional ethics, intellectual ownership and the wider impact of AI',
    lead: 'Chapter 7 asks computer scientists to separate legal, moral, ethical and cultural questions, respect intellectual property and copyright, and evaluate how AI can affect society, the economy and the environment.',
    richBlocks: [{ kind: 'steps', title: 'Chapter route', items: [
      'Distinguish legal, moral, ethical and cultural implications.',
      'Apply professional codes of conduct to realistic computing scenarios.',
      'Evaluate the effect of software and hardware decisions on the public.',
      'Explain copyright, piracy, DRM and software-licensing models.',
      'Evaluate benefits and drawbacks of AI across employment, environment, transport, justice and data use.',
    ] }],
    activity: { title: 'Prior-knowledge check', prompt: 'Review expert systems, copyright and plagiarism, social impacts of computers, environmental effects, online shopping/banking and the influence of social media.' },
    visual: 'types', accent: 'indigo', ...source(178, ['Chapter 7 learning objectives', 'What you should already know']),
  },
  {
    id: 'h7-71-foundations', section: '7.1 Legal, moral, ethical and cultural implications', eyebrow: '7.1 · LEGAL · MORALITY · ETHICS · CULTURE',
    title: 'The same computing action can raise different legal, moral, ethical and cultural questions',
    lead: 'The coursebook treats law, personal ideas of right and wrong, professional conduct and shared cultural values as related but distinct lenses.',
    richBlocks: [{ kind: 'table', table: { caption: 'Four lenses for analysing behaviour', headers: ['Lens', 'Source-grounded meaning'], rows: [
      ['Legal', 'whether an action is permitted or prohibited by law'],
      ['Morality', 'personal or social understanding of right and wrong'],
      ['Ethics', 'principles or professional codes governing behaviour'],
      ['Culture', 'attitudes, values and practices shared by a group or society'],
    ] } }],
    keyTerms: [
      { term: 'Intellectual property rights', definition: 'Rules protecting ownership of creations and ideas, including software.' },
      { term: 'Privacy', definition: 'The right to keep personal information from unauthorised access or disclosure.' },
      { term: 'Plagiarism', definition: 'Taking another person’s work and presenting it as one’s own.' },
    ],
    bullets: [
      'An immoral action is not automatically illegal, and an illegal action is not defined only by whether somebody considers it immoral.',
      'Unethical professional behaviour means breaking accepted professional standards or a code of conduct.',
      'Cultural expectations can affect how software, games and online content are received even where no law or professional rule is broken.',
    ],
    visual: 'types', accent: 'cyan', ...source(179, ['7.1 Legal, moral, ethical and cultural implications', 'Key terms']),
  },
  {
    id: 'h7-711-computer-ethics', section: '7.1 Legal, moral, ethical and cultural implications', subtopicCode: '7.1.1', eyebrow: '7.1.1 · COMPUTER ETHICS',
    title: 'Computer ethics concentrates on ownership, privacy and effects on society',
    lead: 'The chapter defines computer ethics as principles regulating computer use and groups its concerns into intellectual property, privacy and the effect of computers on society.',
    bullets: [
      'Copying software without the owner’s permission raises intellectual-property issues.',
      'Hacking or other unauthorised access to personal information raises privacy issues.',
      'Job loss and wider social change are examples of computing’s impact on society.',
      'Internet access makes plagiarism easier, so borrowed ideas and quotations should be acknowledged through references or footnotes.',
      'Plagiarism-detection software can compare submitted text with material published online.',
    ],
    activity: { title: 'Classify the issue', prompt: 'For three computing scenarios, decide whether the main concern is intellectual property, privacy or social impact, then justify the classification.' },
    visual: 'recap', accent: 'emerald', ...source(180, ['7.1.1 Computer ethics', 'Plagiarism']),
  },
  {
    id: 'h7-712-bcs-ieee', section: '7.1 Legal, moral, ethical and cultural implications', subtopicCode: '7.1.2', eyebrow: '7.1.2 · PROFESSIONAL ETHICAL BODIES · BCS · IEEE',
    title: 'Professional bodies turn broad ethical expectations into codes of conduct',
    lead: 'Membership of a professional body indicates a commitment to standards of competence, integrity, responsibility and public interest.',
    richBlocks: [
      { kind: 'steps', title: 'BCS Code of Conduct: four areas named by the source', items: [
        'The Public Interest',
        'Professional Competence and Integrity',
        'Duty to Relevant Authority',
        'Duty to the Profession',
      ] },
      { kind: 'bullets', items: [
        'The IEEE aims to raise awareness of ethical issues and promote ethical behaviour among electronics and computing professionals.',
        'Its code emphasises public safety and welfare, honest claims, avoidance of conflicts of interest and bribery, technical competence, fair treatment, acknowledgement of errors and support for colleagues.',
      ] },
    ],
    visual: 'types', accent: 'amber', ...sourceRange(180, 181, ['BCS Code of Conduct', 'IEEE Code of Ethics']),
  },
  {
    id: 'h7-712-software-code', section: '7.1 Legal, moral, ethical and cultural implications', subtopicCode: '7.1.2', eyebrow: 'IEEE + ACM · SOFTWARE ENGINEERING CODE OF ETHICS',
    title: 'The software-engineering code groups professional responsibility into eight principles',
    lead: 'The IEEE and ACM code organises software-engineering responsibilities into eight areas that can be applied to project decisions and workplace behaviour.',
    richBlocks: [{ kind: 'table', table: { caption: 'Eight software-engineering principles', headers: ['Principle', 'Professional focus'], rows: [
      ['PUBLIC', 'act consistently with the public interest'],
      ['CLIENT AND EMPLOYER', 'serve client and employer interests consistently with the public interest'],
      ['PRODUCT', 'maintain high professional standards in software products and modifications'],
      ['JUDGEMENT', 'maintain integrity and independence in professional judgement'],
      ['MANAGEMENT', 'promote ethical software-development and maintenance management'],
      ['PROFESSION', 'support the integrity and reputation of the profession'],
      ['COLLEAGUES', 'be fair to and supportive of colleagues'],
      ['SELF', 'continue learning and practise software engineering ethically'],
    ] } }],
    teacherPrompt: 'Give a workplace scenario and ask students which of the eight principles is most directly involved and why.',
    visual: 'recap', accent: 'rose', ...source(181, ['IEEE/ACM Software Engineering Code of Ethics', 'Eight principles']),
  },
  {
    id: 'h7-712-mikhail', section: '7.1 Legal, moral, ethical and cultural implications', subtopicCode: '7.1.2', eyebrow: 'ETHICALGAMZ / MIKHAILSOFT CASE STUDY · EXTENSION ACTIVITY 7A',
    title: 'A single project can break several ethical duties at the same time',
    lead: 'The Mikhail scenario combines employer code reuse, weak control of outsourced development, confidential access, unfair treatment and failure to credit colleagues.',
    richBlocks: [{ kind: 'steps', title: 'Issues to trace through the code', items: [
      'Safety, testing and specification quality of outsourced software.',
      'Use of software or code obtained or retained illegally or unethically.',
      'Responsibility for choosing appropriate development methods.',
      'Endorsing work only where supervision and competence are sufficient.',
      'Protecting employer passwords, files and confidential information.',
      'Avoiding personal gain at the expense of employer, client or profession.',
      'Giving proper credit for the work of others.',
      'Avoiding unfair treatment based on irrelevant prejudice.',
    ] }],
    activity: { title: 'Extension Activity 7A', prompt: 'Apply further code clauses to the Mikhail scenario and decide which actions breach professional responsibilities. Explain each decision rather than naming a principle only.' },
    visual: 'recap', accent: 'indigo', ...sourceRange(182, 183, ['Mikhail / EthicalGamz scenario', 'Extension Activity 7A']),
  },
  {
    id: 'h7-713-public-impact', section: '7.1 Legal, moral, ethical and cultural implications', subtopicCode: '7.1.3', eyebrow: '7.1.3 · IMPACT ON THE PUBLIC · FIGURE 7.1',
    title: 'Public well-being combines safety, public interest, benefits and public concerns',
    lead: 'Figure 7.1 frames professional responsibility around the public consequences of software and hardware, then the chapter uses real incidents to show how technical failures can become social and economic problems.',
    richBlocks: [{ kind: 'table', table: { caption: 'Case studies used by the coursebook', headers: ['Case', 'Lesson'], rows: [
      ['LA airport shutdown', 'a network/device fault can disrupt critical operations, travel and business'],
      ['Overheating laptop batteries', 'hardware defects can create safety risk and large-scale recall costs'],
      ['Airbus A380 software incompatibility', 'incompatible engineering software versions can create manufacturing errors and potential safety consequences'],
    ] } }],
    bullets: [
      'Other public concerns include insecure software, attempts to conceal security problems and leaks of private data.',
      'The chapter also raises social-media responsibility for hate or cyberbullying and questions whether paid influence can distort search results.',
    ],
    visual: 'recap', accent: 'cyan', ...sourceRange(183, 185, ['Figure 7.1 Public well-being', 'LA airport case', 'Laptop battery case', 'Airbus A380 case', 'Extension Activity 7B', 'Activity 7A']),
  },
  {
    id: 'h7-71-internet-debate', section: '7.1 Legal, moral, ethical and cultural implications', eyebrow: 'ACTIVITY 7A · EXTENSION ACTIVITY 7B',
    title: 'Internet policing creates a direct conflict between protection and freedom',
    lead: 'The source asks learners to weigh controls on harmful or illegal online material against freedom of information and freedom of speech.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Arguments for stronger policing', rightTitle: 'Arguments against stronger policing', rows: [
      ['May reduce illegal or harmful material.', 'Can restrict freedom of information and expression.'],
      ['May protect children and vulnerable users.', 'Material may remain accessible through other channels.'],
      ['Can impose accountability on platforms that do not remove dangerous content.', 'Raises difficult questions about who decides what is unacceptable.'],
    ] }],
    activity: { title: 'Structured debate', prompt: 'Should governments be allowed to require removal of harmful content or close services that refuse? Build a reasoned conclusion using both sides.' },
    visual: 'types', accent: 'emerald', ...source(185, ['Extension Activity 7B', 'Activity 7A']),
  },
  {
    id: 'h7-72-copyright-terms', section: '7.2 Copyright issues', eyebrow: '7.2 · COPYRIGHT ISSUES · KEY TERMS',
    title: 'Copyright protection combines law, licensing and technical controls',
    lead: 'The chapter introduces piracy, product keys, DRM and software-licensing organisations before applying them to software ownership.',
    keyTerms: [
      { term: 'Piracy', definition: 'Using or making illegal copies of software or other protected material.' },
      { term: 'Product key', definition: 'A reference used to restrict illegal installation or use.' },
      { term: 'Digital rights management (DRM)', definition: 'Technical restrictions controlling access to and permitted use of copyrighted digital material.' },
      { term: 'Free Software Foundation', definition: 'Organisation promoting freedoms to run, copy, study, change and adapt software.' },
      { term: 'Open Source Initiative', definition: 'Organisation promoting open-source freedoms with emphasis on practical collaborative development.' },
      { term: 'Freeware', definition: 'Software available without charge but still protected by copyright restrictions.' },
      { term: 'Shareware', definition: 'Software offered initially for trial, with payment required for continued or full use.' },
    ],
    visual: 'types', accent: 'amber', ...source(186, ['7.2 Copyright issues', 'Key terms']),
  },
  {
    id: 'h7-721-software-copyright', section: '7.2 Copyright issues', subtopicCode: '7.2.1', eyebrow: '7.2.1 · SOFTWARE COPYRIGHT AND PIRACY',
    title: 'Buying software gives licence rights, not unlimited ownership rights',
    lead: 'Copyright restricts unauthorised copying, redistribution, multi-computer use, code reuse, rental and misleading use of protected software names.',
    richBlocks: [{ kind: 'steps', title: 'Anti-piracy controls named in the chapter', items: [
      'Require a unique product key during installation.',
      'Require acceptance of the licence agreement.',
      'Use genuine-product labels or holograms.',
      'Require original media to be present for execution where appropriate.',
      'Require a hardware dongle for authorised use in some systems.',
      'Use legal enforcement against copyright infringement.',
    ] }],
    activity: { title: 'Licence scenario', prompt: 'A user buys one copy of an application and installs it across a whole company network. Explain which copyright/licensing issue is raised and what kind of licence would be required.' },
    visual: 'files', accent: 'rose', ...source(186, ['7.2.1 Software copyright and privacy', 'Product keys', 'Licence agreement', 'Hologram', 'Dongle', 'FAST']),
  },
  {
    id: 'h7-722-drm', section: '7.2 Copyright issues', subtopicCode: '7.2.2', eyebrow: '7.2.2 · INTERNET / WWW · DIGITAL RIGHTS MANAGEMENT',
    title: 'DRM restricts how a user can access, copy or transfer protected digital material',
    lead: 'DRM can allow an action such as streaming while preventing copying, restrict a work to an authorised device or require online authorisation before use.',
    bullets: [
      'DRM originally controlled how protected media could be played and was extended to music, video, ebooks and software.',
      'A protected product can be tied to a registered key, account or device.',
      'The technical goal is to make unauthorised use or copying difficult or unusable while preserving licensed use.',
    ],
    activity: { title: 'Permitted use versus ownership', prompt: 'Explain why being allowed to stream, read or run a digital product does not automatically give the user permission to copy or redistribute it.' },
    visual: 'files', accent: 'indigo', ...source(187, ['7.2.2 The internet and the World Wide Web', 'Digital rights management']),
  },
  {
    id: 'h7-723-commercial-free-open', section: '7.2 Copyright issues', subtopicCode: '7.2.3', eyebrow: '7.2.3 · COMMERCIAL · FREE SOFTWARE · OPEN SOURCE',
    title: 'Licences differ in the permissions they grant for use, source code, modification and redistribution',
    lead: 'Commercial software normally grants use under a paid licence, while the Free Software Foundation and Open Source Initiative promote freedoms to run, study, modify and redistribute software under licence conditions.',
    richBlocks: [
      { kind: 'comparison', leftTitle: 'Commercial software', rightTitle: 'Free / open-source software', rows: [
        ['Usually supplied for a fee under single-user or multi-use licence conditions.', 'Users may run software for legal purposes and inspect source code.'],
        ['Copyright owner controls copying and source-code reuse.', 'Users may modify source code under the licence.'],
        ['Code cannot be reused without owner consent.', 'Copies and modified versions may be redistributed under the applicable licence terms.'],
      ] },
      { kind: 'bullets', items: [
        'The Open Source Initiative emphasises free redistribution, source-code availability and derived works.',
        'Its principles also address source integrity, non-discrimination, licence portability, compatibility with other software and technology neutrality.',
      ] },
    ],
    visual: 'files', accent: 'cyan', ...sourceRange(187, 188, ['Commercial software', 'Free Software Foundation', 'Open Source Initiative', 'Four freedoms', 'Open-source principles']),
  },
  {
    id: 'h7-723-freeware-shareware', section: '7.2 Copyright issues', subtopicCode: '7.2.3', eyebrow: 'FREEWARE ↔ SHAREWARE · ACTIVITY 7B',
    title: 'Free of charge is not the same as free to modify',
    lead: 'Freeware can be used without a purchase fee but remains copyright protected. Shareware offers an initial trial and normally requires payment for continued or full-feature use.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Freeware', rightTitle: 'Shareware', rows: [
      ['Downloaded and used without a fee.', 'Used without charge for an initial trial period.'],
      ['Still protected by copyright.', 'Still protected by copyright.'],
      ['Source code is not automatically available for study or modification.', 'Full features, continued use, support or updates may depend on registration/payment.'],
    ] }],
    activity: { title: 'Activity 7B', prompt: 'Explain software piracy, propose three anti-copying measures, then evaluate the benefits of a shareware model for both the software company and the customer.' },
    visual: 'files', accent: 'emerald', ...sourceRange(188, 189, ['Freeware', 'Shareware', 'Activity 7B']),
  },
  {
    id: 'h7-731-ai-definition', section: '7.3 Artificial intelligence (AI)', subtopicCode: '7.3.1', eyebrow: '7.3.1 · WHAT IS AI?',
    title: 'AI performs tasks that require some degree of intelligence when performed by a human',
    lead: 'The chapter introduces AI through human-like task requirements rather than through robotics alone.',
    bullets: [
      'Examples include language use and mathematical functions.',
      'AI can recognise a person’s face.',
      'AI can operate machinery such as cars, aircraft or trains.',
      'AI can analyse data to predict future events such as weather.',
      'The common thread is decision-making and problem solving in tasks that would otherwise require human intelligence.',
    ],
    keyTerms: [{ term: 'Artificial intelligence (AI)', definition: 'A machine or application carrying out a task that requires some degree of intelligence when a human performs it.' }],
    visual: 'types', accent: 'amber', ...sourceRange(189, 190, ['7.3 Artificial intelligence', '7.3.1 What is AI?', 'Figure 7.2']),
  },
  {
    id: 'h7-732-ai-impact', section: '7.3 Artificial intelligence (AI)', subtopicCode: '7.3.2', eyebrow: '7.3.2 · THE IMPACT OF AI',
    title: 'AI extends far beyond fictional robots',
    lead: 'The source uses robotics as a familiar starting point, then broadens AI to autonomous transport, assistive technology, hazardous work, climate prediction and precision medicine.',
    bullets: [
      'The chapter references Asimov’s three laws of robotics as a discussion device about safety, obedience and self-protection.',
      'Autonomous vehicles make navigation and driving decisions without a human driver controlling every action.',
      'Artificial limbs use advanced control to assist human movement.',
      'Drones can perform dangerous or unpleasant tasks such as bomb disposal, welding or entering disaster zones.',
      'AI can support climate prediction and medical procedures where high precision is required.',
    ],
    visual: 'recap', accent: 'rose', ...source(190, ['7.3.2 The impact of AI', 'Asimov robotics laws', 'Autonomous vehicles', 'Artificial limbs', 'Drones', 'Climate prediction', 'Medical procedures']),
  },
  {
    id: 'h7-733-jobs-economy', section: '7.3 Artificial intelligence (AI)', subtopicCode: '7.3.3', eyebrow: '7.3.3 · SOCIETY + ECONOMY · AUTOMATION + EMPLOYMENT',
    title: 'Automation can remove existing roles while creating pressure for retraining and new kinds of work',
    lead: 'The chapter presents job displacement as a major possible social and economic impact, while also noting the historical pattern in which technological change creates new roles and increases productivity.',
    bullets: [
      'Medium- and low-skilled work is especially exposed to automation, but some high-skilled roles can also change.',
      'Large-scale displacement would create a need for retraining, new skills and potentially new approaches to distribution of wealth.',
      'Automation can increase production speed and efficiency while creating jobs in tasks not yet automated.',
      'The source asks learners to evaluate competing predictions rather than treating one forecast as certain.',
      'More automation may also create more leisure time, but countries and companies face competitive pressure to adopt new technology.',
    ],
    activity: { title: 'Evidence-based evaluation', prompt: 'Build one argument that AI will reduce employment and one argument that it will transform or create employment. Then state what evidence would be needed to judge the claims.' },
    visual: 'types', accent: 'indigo', ...source(191, ['Employment predictions', 'Automation', 'Retraining', 'Economic impact']),
  },
  {
    id: 'h7-733-environment', section: '7.3 Artificial intelligence (AI)', subtopicCode: '7.3.3', eyebrow: 'AI + ENVIRONMENT · RESOURCE CONSERVATION · POLLUTION · RENEWABLE ENERGY',
    title: 'AI can analyse complex environmental data faster than humans can inspect it manually',
    lead: 'The source emphasises AI’s ability to find patterns and relationships across very large environmental data sets and use them to support faster prediction and response.',
    richBlocks: [{ kind: 'steps', title: 'Environmental applications identified in the chapter', items: [
      'Support conservation of scarce natural resources such as water.',
      'Detect and locate air or sea pollution more quickly and accurately.',
      'Combine weather prediction with renewable-energy forecasting for solar, tidal, thermal and wind sources.',
      'Monitor and model ecosystems in real time so harmful change can be recognised earlier.',
    ] }],
    visual: 'recap', accent: 'cyan', ...sourceRange(191, 192, ['AI environmental impact', 'Natural resources', 'Pollution', 'Renewable energy', 'Ecosystem monitoring']),
  },
  {
    id: 'h7-733-transport-justice', section: '7.3 Artificial intelligence (AI)', subtopicCode: '7.3.3', eyebrow: 'TRANSPORT · CRIMINAL JUSTICE · PRIVACY · BIAS',
    title: 'AI can improve efficiency while creating accountability, privacy and fairness questions',
    lead: 'Driverless transport and automated legal decision making illustrate why an efficient technical system still needs social, legal and ethical scrutiny.',
    richBlocks: [{ kind: 'comparison', leftTitle: 'Potential value', rightTitle: 'Questions raised by the source', rows: [
      ['Driverless transport can automate booking, payment, routing and vehicle operation.', 'Automation can displace drivers and remove humans from the service chain.'],
      ['Facial recognition can support forensic identification.', 'Government use can raise surveillance and privacy concerns.'],
      ['AI can assist legal work or parole/sentencing decisions.', 'How can people challenge an AI-influenced decision or detect unfair bias?'],
    ] }],
    teacherPrompt: 'Ask whether a system should be considered acceptable if it is more efficient but its decision process cannot be challenged fairly.',
    visual: 'types', accent: 'emerald', ...source(192, ['Transport', 'Autonomous taxis', 'Criminal justice system', 'Facial recognition', 'Bias', 'Privacy questions']),
  },
  {
    id: 'h7-733-advertising-data', section: '7.3 Artificial intelligence (AI)', subtopicCode: '7.3.3', eyebrow: 'ADVERTISING + USE OF DATA · ACTIVITY 7C · ACTIVITY 7D',
    title: 'Machine learning can personalise advertising by building profiles from online behaviour',
    lead: 'The chapter connects AI to large-scale monitoring and targeted advertising, using search, social-media and website-visit data to build personality or interest profiles.',
    bullets: [
      'Automated monitoring can potentially identify problematic data use more quickly than manual review.',
      'The same profiling ability can also raise privacy, consent and influence concerns.',
      'The source asks learners to evaluate AI’s overall impact rather than label it simply beneficial or harmful.',
    ],
    activity: { title: 'Activities 7C–7D', prompt: 'Prepare a balanced AI impact argument using social, economic and environmental examples. Include three different AI applications and give one public benefit and one public drawback for each.' },
    visual: 'networking', accent: 'amber', ...source(193, ['Advertising and use of data', 'Machine-learning profiles', 'Activity 7C', 'Activity 7D']),
  },
  {
    id: 'h7-review-ethics-ai', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS · p.194',
    title: 'Review professional conduct, licensing and core AI concepts',
    lead: 'The first review questions combine professional competence and IEEE principles with software-licensing distinctions and basic AI concepts.',
    richBlocks: [{ kind: 'steps', title: 'Exam-practice themes', items: [
      'Explain ethics and distinguish unethical behaviour from illegal behaviour.',
      'Apply professional principles to a manager who lacks experience or needs further training and support.',
      'Name software-licensing types and distinguish their features and copyright implications.',
      'Identify AI-related concepts such as intelligent machine behaviour, heuristics and iterative refinement.',
    ] }],
    visual: 'recap', accent: 'rose', ...source(194, ['End-of-chapter questions 1–3']),
  },
  {
    id: 'h7-review-code-classification', section: 'Chapter review', eyebrow: 'END-OF-CHAPTER QUESTIONS · p.195',
    title: 'Classify workplace incidents as ethical or unethical and map them to professional principles',
    lead: 'The final source question provides six workplace incidents and asks learners first to judge the behaviour, then connect ethical examples to the appropriate software-engineering principle.',
    bullets: [
      'Reporting suspicious phishing is considered through professional responsibility.',
      'Requesting training links professional development to competence and self-improvement.',
      'Copying and selling beta software creates a clear ownership and employer-interest problem.',
      'Joining a professional computing body can demonstrate commitment to the profession.',
      'Refusing to communicate with a colleague raises fairness and colleague-support concerns.',
      'Reporting remaining software bugs even after management considered testing complete raises product quality and professional judgement issues.',
    ],
    activity: { title: 'Final synthesis', prompt: 'For each incident, decide ethical or unethical, select the most relevant professional principle, and justify the decision from the facts rather than from personal preference.' },
    visual: 'recap', accent: 'indigo', ...source(195, ['End-of-chapter Question 4', 'Incidents A–F', 'Software Engineering Code of Ethics']),
  },
];

export const CHAPTER_7_FINAL: HodderLessonChapter = {
  number: 7,
  level: 'AS Level',
  title: 'Ethics and ownership',
  subtitle: 'Legal, moral, ethical and cultural implications · copyright and licensing · AI impacts',
  subtopics: [
    '7.1 Legal, moral, ethical and cultural implications',
    '7.2 Copyright issues',
    '7.3 Artificial intelligence (AI)',
  ],
  sourceNote: 'Deep source-backed teaching route from the exact Hodder 9618 Chapter 7, printed pp.178–195, preserving the chapter sequence, terminology, case studies, activities and source-page provenance.',
  coverage: '18/18 printed chapter pages represented (pp.178–195): ethical foundations; computer ethics; BCS, IEEE and ACM professional codes; professional case studies and public impact; copyright, piracy and DRM; commercial, free/open-source, freeware and shareware licensing; AI definition and applications; social, employment, economic, environmental, transport, justice, privacy and advertising impacts; activities and end-of-chapter exam practice.',
  slides: CHAPTER_7_DEEP_SLIDES,
};
