import type { HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[]) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 3 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

/** Source-specific continuation of Hodder 9618 Chapter 3, printed pp.90–106. */
export const CHAPTER_3_LOGIC_SLIDES: readonly HodderLessonSlide[] = [
  {
    id: 'h3-322-truth-table-not', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.2', eyebrow: '3.2.2 · TABLE 3.9 · FIGURE 3.23 · TABLE 3.10',
    title: 'Truth tables list every binary input combination before the output is traced',
    lead: 'Hodder starts with the number of possible input combinations, then introduces the one-input NOT gate and its two-row truth table.',
    bullets: ['NOT is the only gate in this section with one input: 2¹ = 2 possible combinations.','The other five gates have two inputs: 2² = 4 possible combinations.','Three inputs give 2³ = 8 combinations; four inputs give 2⁴ = 16.','NOT rule: output X is 1 if input A is NOT 1.','Logic notation: X = NOT A. Boolean algebra: X = A̅.'],
    richBlocks: [{ kind: 'table', table: { caption: 'Table 3.10 · NOT gate', headers: ['A', 'X'], rows: [['0', '1'], ['1', '0']] } }], visual: 'types', accent: 'cyan',
    ...source(90, ['3.2.2 Truth tables','Table 3.9','2¹ = 2','2² = 4','2³ = 8','2⁴ = 16','Figure 3.23 NOT gate','Table 3.10']),
  },
  {
    id: 'h3-323-and-or-nand-nor', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.3', eyebrow: 'FIGURES 3.24–3.27 · TABLES 3.11–3.14',
    title: 'AND, OR, NAND and NOR use the same symbol → rule → notation → truth-table pattern',
    lead: 'Hodder presents four two-input gates together on p.91. Their truth tables make the inverse relationships between AND/NAND and OR/NOR visible.',
    richBlocks: [{ kind: 'table', table: { caption: 'Gate rules on Hodder p.91', headers: ['Gate','Output X is 1 when…','Logic notation'], rows: [['AND','A is 1 and B is 1','X = A AND B'],['OR','A is 1 or B is 1','X = A OR B'],['NAND (NOT AND)','A is NOT 1 or B is NOT 1','X = A NAND B'],['NOR (NOT OR)','A is NOT 1 and B is NOT 1','X = A NOR B']] } }], visual: 'types', accent: 'indigo',
    ...source(91, ['Figure 3.24 AND gate','Table 3.11','Figure 3.25 OR gate','Table 3.12','Figure 3.26 NAND gate','Table 3.13','Figure 3.27 NOR gate','Table 3.14']),
  },
  {
    id: 'h3-323-xor-example31', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.4', eyebrow: 'FIGURE 3.28 · TABLE 3.15 · EXTENSION 3G · EXAMPLE 3.1',
    title: 'XOR completes the six-gate set, then Hodder moves directly into tracing a logic circuit',
    lead: 'XOR outputs 1 when the two inputs differ. The page then defines the Boolean symbols and introduces Example 3.1, a three-part circuit traced with intermediate values P, Q and R.',
    bullets: ['XOR: X is 1 when A = 1 and B = 0, or A = 0 and B = 1.','Logic notation: X = A XOR B.','Boolean symbols introduced: dot for AND, plus sign for OR, and a bar above a letter for NOT.','A logic circuit combines gates to carry out a particular function; its output is checked with a truth table.','Example 3.1 circuit: P comes from AND(A,B); Q from NOR(B,C); R combines P and Q with OR; final X combines R and C with XOR.'],
    richBlocks: [{ kind: 'table', table: { caption: 'Table 3.15 · XOR gate', headers: ['A','B','X'], rows: [['0','0','0'],['0','1','1'],['1','0','1'],['1','1','0']] } },{ kind: 'callout', tone: 'extension', title: 'Extension Activity 3G', text: 'Use truth tables to show that the two Boolean expressions printed in the source both represent the XOR logic gate.' }], visual: 'types', accent: 'rose',
    ...source(92, ['Figure 3.28 XOR gate','Table 3.15','Extension Activity 3G','3.2.4 Logic circuits','Example 3.1','P = AND(A,B)','Q = NOR(B,C)','R = OR(P,Q)','X = XOR(R,C)']),
  },
  {
    id: 'h3-324-example31-parts12', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.4', eyebrow: 'EXAMPLE 3.1 · PART 1 + PART 2',
    title: 'Trace the circuit in stages: first P and Q, then R', lead: 'With three inputs there are eight input rows. Hodder reduces errors by splitting the circuit and carrying intermediate values forward.',
    richBlocks: [{ kind: 'table', table: { caption: 'Part 1 · P = A AND B; Q = B NOR C', headers: ['A','B','C','P','Q'], rows: [['0','0','0','0','1'],['0','0','1','0','0'],['0','1','0','0','0'],['0','1','1','0','0'],['1','0','0','0','1'],['1','0','1','0','0'],['1','1','0','1','0'],['1','1','1','1','0']] } },{ kind: 'table', table: { caption: 'Part 2 · R = P OR Q', headers: ['P','Q','R'], rows: [['0','1','1'],['0','0','0'],['0','0','0'],['0','0','0'],['0','1','1'],['0','0','0'],['1','0','1'],['1','0','1']] } }], visual: 'types', accent: 'amber',
    ...source(93, ['Example 3.1 Solution','Part 1','P = AND(A,B)','Q = NOR(B,C)','Part 2','R = OR(P,Q)','eight binary values']),
  },
  {
    id: 'h3-324-example31-part3-activity3b', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.4', eyebrow: 'EXAMPLE 3.1 · PART 3 · ACTIVITY 3B',
    title: 'Finish the trace with XOR, then practise the same intermediate-value method', lead: 'Part 3 combines R and C to produce X. Hodder then joins all intermediate columns into the final truth table and asks students to repeat the method on five circuits.',
    richBlocks: [{ kind: 'table', table: { caption: 'Example 3.1 · final truth table', headers: ['A','B','C','P','Q','R','X'], rows: [['0','0','0','0','1','1','1'],['0','0','1','0','0','0','1'],['0','1','0','0','0','0','0'],['0','1','1','0','0','0','1'],['1','0','0','0','1','1','1'],['1','0','1','0','0','0','1'],['1','1','0','1','0','1','1'],['1','1','1','1','0','1','0']] } },{ kind: 'callout', tone: 'extension', title: 'Activity 3B', text: 'Produce truth tables for each of the five logic circuits. Split each circuit into intermediate parts to help eliminate errors.' }], visual: 'types', accent: 'emerald',
    ...source(94, ['Example 3.1 Part 3','X = XOR(R,C)','final truth table','Activity 3B','five logic circuits','intermediate parts']),
  },
  {
    id: 'h3-324-example32', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.4', eyebrow: 'EXAMPLE 3.2 · LOGIC STATEMENT → BOOLEAN ALGEBRA → CIRCUIT',
    title: 'Translate a safety rule into three circuit parts before building the truth table',
    lead: 'The alarm sounds when A is ON and B is OFF, or when B is ON and C is OFF. Hodder first rewrites the words as logic, then as Boolean algebra.',
    bullets: ['ON = 1 and OFF = 0; OFF is therefore treated as NOT 1.','Part 1: A = 1 AND B = NOT 1.','Part 2 joins the two conditions with OR.','Part 3: B = 1 AND C = NOT 1.','Boolean algebra printed in the source: (A.B̅) + (B.C̅).'],
    visual: 'types', accent: 'cyan',
    ...source(95, ['Example 3.2','safety system','ON = 1','OFF = 0','Part 1','Part 2','Part 3','(A.B̅) + (B.C̅)','logic circuit']),
  },
  {
    id: 'h3-324-example32-truth-activity3c', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.4', eyebrow: 'EXAMPLE 3.2 · TRUTH TABLE · ACTIVITY 3C · EXAMPLE 3.3',
    title: 'Check the safety circuit from the original logic statement',
    lead: 'Hodder uses the second of two checking methods: evaluate the original statement and compare it with the circuit.',
    richBlocks: [{ kind: 'table', table: { caption: 'Example 3.2 · output X', headers: ['A','B','C','A AND NOT B','B AND NOT C','X'], rows: [['0','0','0','0','0','0'],['0','0','1','0','0','0'],['0','1','0','0','1','1'],['0','1','1','0','0','0'],['1','0','0','1','0','1'],['1','0','1','1','0','1'],['1','1','0','0','1','1'],['1','1','1','0','0','0']] } },{ kind: 'callout', tone: 'extension', title: 'Activity 3C', text: 'Draw logic circuits and complete truth tables for the five printed logic/Boolean statements before moving to the wind-turbine worked example.' }],
    bullets: ['Example 3.3 monitors turbine speed S, bearing temperature T and wind velocity W.','S = 0 means speed ≤ 1000 rpm; S = 1 means speed > 1000 rpm.','T = 0 means temperature ≤ 80 °C; T = 1 means temperature > 80 °C.','W = 0 means velocity ≤ 120 kph; W = 1 means velocity > 120 kph.'], visual: 'types', accent: 'indigo',
    ...source(96, ['Example 3.2 truth table','Activity 3C','five statements','Example 3.3','wind turbine','S ≤ 1000 rpm','T ≤ 80 °C','W ≤ 120 kph']),
  },
  {
    id: 'h3-324-example33-stage1', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.4', eyebrow: 'EXAMPLE 3.3 · STAGE 1 + STAGE 2',
    title: 'Convert the wind-turbine conditions into three intermediate logic circuits',
    lead: 'For a real scenario, Hodder recommends building the circuit and truth table separately and checking them against each other.',
    bullets: ['① S = NOT 1 AND T = 1.','② S = 1 AND W = 1.','③ T = NOT 1 AND W = 1.','The key words AND, OR and NOT identify how the monitored conditions connect.','Because the three original conditions are joined by OR, two OR gates combine the three intermediate circuits.'], visual: 'types', accent: 'rose',
    ...source(97, ['Example 3.3 Solution','Stage 1','Stage 2','S = NOT 1 AND T = 1','S = 1 AND W = 1','T = NOT 1 AND W = 1','two OR gates']),
  },
  {
    id: 'h3-324-example33-truth-activity3d', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.4', eyebrow: 'EXAMPLE 3.3 · FINAL CIRCUIT · TRUTH TABLE · ACTIVITY 3D',
    title: 'Combine the three conditions and verify the final output X',
    lead: 'The source evaluates three intermediate conditions, ORs ① and ② into ④, then ORs ③ and ④ to obtain X.',
    richBlocks: [{ kind: 'table', table: { caption: 'Example 3.3 · final truth table', headers: ['S','T','W','①','②','③','④','X'], rows: [['0','0','0','0','0','0','0','0'],['0','0','1','0','0','1','0','1'],['0','1','0','1','0','0','1','1'],['0','1','1','1','0','0','1','1'],['1','0','0','0','0','0','0','0'],['1','0','1','0','1','1','1','1'],['1','1','0','0','0','0','0','0'],['1','1','1','0','1','0','1','1']] } },{ kind: 'callout', tone: 'extension', title: 'Activity 3D', text: 'Build a circuit and truth table for each of the two real-world safety scenarios: a chemical process and a power station.' }], visual: 'types', accent: 'amber',
    ...source(98, ['Example 3.3 final logic circuit','truth table','intermediate ④','Activity 3D','chemical process','power station']),
  },
  {
    id: 'h3-325-real-world-design', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.5', eyebrow: '3.2.5 · LOGIC CIRCUITS IN THE REAL WORLD',
    title: 'Real circuit design balances components, fabrication, time and physical space',
    lead: 'Hodder moves from syllabus fundamentals to two practical design strategies used by electronics companies.',
    bullets: ['Review cost of components, ease of fabrication and time constraints.','Use off-the-shelf logic units as reusable building blocks.','Simplify the circuit as far as possible.','Simplification matters where room is at a premium, such as circuit boards used in satellites.'], visual: 'types', accent: 'emerald',
    ...source(99, ['3.2.5 Logic circuits in the real world','cost of components','ease of fabrication','time constraints','off-the-shelf logic units','building blocks','simplifying the logic circuit','satellites']),
  },
  {
    id: 'h3-325-nand-building-blocks', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.5', eyebrow: 'FIGURES 3.29–3.31 · ACTIVITY 3E',
    title: 'A NAND gate can be used as a universal building block',
    lead: 'The source shows AND, OR and NOT equivalents made only from NAND gates, then asks students to prove equivalence with truth tables.',
    richBlocks: [{ kind: 'callout', tone: 'extension', title: 'Activity 3E', text: 'Prove the three printed NAND constructions, rebuild a larger circuit using NAND only, build XOR from NAND only, and identify the single gate equivalent to the final NAND-only circuit.' }], visual: 'types', accent: 'cyan',
    ...source(100, ['Using logic building blocks','NAND gate','Figure 3.29 AND gate made from NAND gates','Figure 3.30 OR gate made from NAND gates','Figure 3.31 NOT gate made from NAND gates','Activity 3E','XOR from NAND gates only']),
  },
  {
    id: 'h3-326-multi-input-and', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.6', eyebrow: 'SIMPLIFICATION · EXTENSION 3H · FIGURE 3.32 · TABLE 3.16',
    title: 'Simplification reduces components; multi-input gates can simplify a circuit further',
    lead: 'Hodder notes that fewer components can reduce production cost, improve reliability and make fault tracing easier, then introduces multi-input logic gates as extension material.',
    bullets: ['Simplification is covered in more depth in Chapter 15.','Extension Activity 3H asks which single gate matches a printed two-input circuit.','Multi-input gates are included for completeness and are not expected at Cambridge International AS Level.','A three-input AND gate is equivalent to linked two-input AND gates and has output A.B.C.'], visual: 'types', accent: 'indigo',
    ...source(101, ['Simplification of logic circuits','cost of production','reliability','trace faults','Extension Activity 3H','3.2.6 Multi-input logic gates','Figure 3.32 Multi-input AND gate','Table 3.16','A.B.C']),
  },
  {
    id: 'h3-326-four-input-and-or', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.6', eyebrow: 'FIGURES 3.33–3.34 · TABLES 3.17–3.18',
    title: 'Three- and four-input gates preserve the same AND/OR rule',
    lead: 'The source compares a single multi-input symbol with equivalent networks of two-input gates and locks the equivalence with truth tables.',
    bullets: ['4-input AND output: A.B.C.D; only 1111 produces 1.','3-input OR output: A + B + C; only 000 produces 0.','The multi-input symbol and the linked two-input network share identical truth tables.'], visual: 'types', accent: 'rose',
    ...source(102, ['Figure 3.33 4-input AND gate','Table 3.17','A.B.C.D','Multi-input OR gates','Figure 3.34 Multi-input OR gate','Table 3.18','A + B + C']),
  },
  {
    id: 'h3-326-four-input-or-activity3f', section: '3.2 Logic gates and logic circuits', subtopicCode: '3.2.6', eyebrow: 'FIGURE 3.35 · TABLE 3.19 · ACTIVITY 3F',
    title: 'A four-input OR gate is equivalent to a cascade of two-input OR gates',
    lead: 'Both forms have output A + B + C + D and identical 16-row truth tables. Hodder then asks learners to repeat the equivalence reasoning for NAND and NOR.',
    richBlocks: [{ kind: 'callout', tone: 'extension', title: 'Activity 3F', text: 'Rebuild the printed 4-input NAND and 3-/4-input NOR gates using only two-input gates, construct truth tables, and confirm the paired circuits are identical.' }], visual: 'types', accent: 'amber',
    ...source(103, ['Figure 3.35 4-input OR gate','Table 3.19','A + B + C + D','16-row truth table','Activity 3F','4-input NAND','3-input NOR','4-input NOR']),
  },
  {
    id: 'h3-end-questions-1-3', section: 'End of chapter questions', subtopicCode: '3', eyebrow: 'END OF CHAPTER · QUESTIONS 1–3',
    title: 'Consolidate displays, memory, USB, 3D printing and process control',
    lead: 'The first three questions revisit the chapter through explanation and application rather than isolated recall.',
    bullets: ['Q1: reasons manufacturers move to OLED and evaluate the “over one million vivid colours” claim.','Q2: ROM for a finished game, EPROM during development, RAM on the circuit board, USB ports, and 3D-printed prototype parts.','Q3: distinguish monitoring from control, then explain a microprocessor-controlled car air-conditioning system using at least two sensors and positive feedback.'], visual: 'types', accent: 'emerald',
    ...source(104, ['End of chapter questions','Question 1 OLED','one million vivid colours','Question 2 games console','ROM','EPROM','RAM','USB ports','3D printer','Question 3 air conditioning','control and monitoring','positive feedback']),
  },
  {
    id: 'h3-end-questions-4-5', section: 'End of chapter questions', subtopicCode: '3', eyebrow: 'END OF CHAPTER · QUESTIONS 4–5',
    title: 'Sequence inkjet printing, then compare DRAM/SRAM and RAM/ROM',
    lead: 'Question 4 presents the nine inkjet stages out of order; Question 5 returns to primary-memory distinctions and storage technology.',
    bullets: ['Q4: reorder stages A–I of the nine-stage inkjet printing process.','Q5a: connect five statements to DRAM or SRAM.','Q5b: give three differences between RAM and ROM.'], visual: 'types', accent: 'cyan',
    ...source(105, ['Question 4','nine stages','inkjet printer','printer buffer','printer driver','interrupt','Question 5','DRAM','SRAM','RAM and ROM']),
  },
  {
    id: 'h3-end-questions-5c-6', section: 'End of chapter questions', subtopicCode: '3', eyebrow: 'END OF CHAPTER · QUESTION 5c + QUESTION 6',
    title: 'Finish with storage-device comparison and a full logic-circuit exam problem',
    lead: 'The chapter closes with Cambridge-style application: compare DVD-RAM with flash memory, then turn sensor conditions into a circuit, truth table and logic statement.',
    bullets: ['Q5c: describe two operational differences between DVD-RAM and flash memory.','Q6a: draw the circuit for A = 1 OR B = 0, or B = 1 AND C = 0.','Q6b: complete the eight-row truth table.','Q6c: write a logic statement for the printed circuit.','The source attributes these items to Cambridge International AS & A Level Computer Science 9608, June 2015.'], visual: 'types', accent: 'indigo',
    ...source(106, ['Question 5c','DVD-RAM','flash memory','9608 Paper 13 Q4 June 2015','Question 6','three digital sensors A B C','logic circuit','truth table','logic statement','9608 Paper 13 Q6 June 2015']),
  },
];
