import type { HodderLessonChapter, HodderLessonSlide } from './lesson-content-hodder-types';
import { checkpoint } from './lesson-content-hodder-types';

export type Chapter2Lesson = Omit<HodderLessonChapter, 'number'> & { number: 2 };

const source = (printedPage: number | number[], elements: string[] = []) => {
  const pages = Array.isArray(printedPage) ? printedPage : [printedPage];
  return {
    sourcePages: pages,
    sourceLabel: `Hodder Chapter 2 · p.${pages.join('–')}`,
    sourceElements: pages.map(page => `Hodder p.${page}`).concat(elements),
  };
};

const slides: HodderLessonSlide[] = [
  // ─── CHAPTER OVERVIEW ─────────────────────────────────────────────────────
  {
    id: 'h2-overview',
    section: 'Chapter overview',
    eyebrow: 'CHAPTER 2 · COMMUNICATION',
    title: 'Communication and networking',
    lead: 'This chapter explains how computers communicate through networks and the internet: network devices and models, topologies, cloud computing, wired and wireless links, Ethernet, bit streaming, IP addressing, URLs, DNS and web scripting.',
    bullets: [
      'Explain the benefits of networking devices and the characteristics of LANs and WANs.',
      'Compare client-server with peer-to-peer networking, and thin clients with thick clients.',
      'Describe bus, star, mesh and hybrid network topologies.',
      'Compare public and private cloud computing.',
      'Compare wired and wireless networks, including cable types and wireless technologies.',
      'Describe the hardware needed for a LAN and explain the function of routers.',
      'Explain Ethernet and how data collisions are detected and resolved.',
      'Explain bit streaming, buffering, bit rate, real-time streaming and on-demand streaming.',
      'Distinguish the internet from the World Wide Web and describe the hardware that supports internet access.',
      'Explain IPv4, IPv6, public and private IP addresses, CIDR, zero compression and sub-netting.',
      'Explain how URLs locate resources and how DNS resolves a domain name.',
      'Explain client-side JavaScript and server-side PHP used with HTML pages.',
    ],
    richBlocks: [
      {
        kind: 'steps',
        title: 'What you should already know',
        items: [
          'Q1: Define MAC address and IP address; explain why an internet-connected device needs both. Then distinguish a web browser from an internet service provider (ISP).',
          'Q2: A college will network 20 stand-alone computers. Describe the hardware and software it may need.',
          'Q3: Explain the software that lets phones and tablets access the internet from different locations, then compare mobile web access with a desktop PC.',
        ],
      },
    ],
    visual: 'networking',
    accent: 'indigo',
    ...source(27, ['Chapter 2 learning objectives', '2.1 What you should already know']),
  },

  // ─── 2.1 NETWORKING ────────────────────────────────────────────────────────
  // ─── NETWORK INFRASTRUCTURE ────────────────────────────────────────────────
  {
    id: 'h2-21-infra',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1 · NETWORK INFRASTRUCTURE',
    title: 'Networked computers need hardware, software and services',
    lead: 'The coursebook describes three categories of infrastructure required for networked computers: Hardware, Software and Services.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Network infrastructure categories',
          headers: ['Category', 'Examples', 'Purpose'],
          rows: [
            ['Hardware', 'LAN cards, routers, switches, wireless routers and cabling', 'Physical components that connect devices'],
            ['Software', 'Network operation/management, firewall operation and security utilities', 'Controls the network and protects its traffic'],
            ['Services', 'DSL, satellite communication channels, wireless protocols and IP addressing', 'Carries data and identifies networked devices'],
          ],
        },
      },
    ],
    visual: 'networking',
    accent: 'indigo',
    ...source(30, ['Networked computers · hardware, software and services']),
  },

  // ─── BENEFITS AND DRAWBACKS OF NETWORKING ──────────────────────────────────
  {
    id: 'h2-21-benefits',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1 · BENEFITS OF NETWORKING',
    title: 'Networking provides significant advantages for organisations',
    lead: 'The coursebook lists several benefits of networking computers together.',
    bullets: [
      'Devices such as printers can be shared, reducing hardware cost.',
      'Network software licences can cost less than equivalent stand-alone licences.',
      'Users can share files and data and access reliable data from a central file server.',
      'Data and files can be backed up centrally at the end of each day.',
      'Users can communicate through email and instant messaging.',
      'A network manager can apply file access rights and restrict access to external networks.',
    ],
    visual: 'networking',
    accent: 'emerald',
    ...source(30, ['Benefits of networking']),
  },

  {
    id: 'h2-21-drawbacks',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1 · DRAWBACKS OF NETWORKING',
    title: 'Networking introduces risks and costs',
    lead: 'The coursebook identifies several drawbacks that must be considered.',
    bullets: [
      'Cabling and servers can require an expensive initial outlay.',
      'Managing a large network can be complex and difficult.',
      'Failure of a device such as a file server can affect the whole network.',
      'Malware and hacking can spread across an entire network; firewalls provide some protection.',
    ],
    visual: 'networking',
    accent: 'rose',
    ...source(30, ['Drawbacks of networking']),
  },

  // ─── CLIENT-SERVER AND PEER-TO-PEER ────────────────────────────────────────
  {
    id: 'h2-212-client-server',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.2 · CLIENT-SERVER MODEL',
    title: 'A central server provides services to multiple clients',
    lead: 'In the client-server model, clients request services and the server provides them. This is the most common network model for businesses and organisations.',
    keyTerms: [
      { term: 'Client-server', definition: 'A network model where clients request services from a centralised server.' },
      { term: 'Server', definition: 'A powerful computer that stores data, runs applications and manages network resources.' },
      { term: 'Client', definition: 'A computer that sends requests to the server and receives responses.' },
    ],
    bullets: [
      'The server is a powerful computer that stores data and runs applications.',
      'Clients send requests to the server and receive responses.',
      'The server manages access to shared resources (files, printers, internet).',
      'Multiple clients can access the server simultaneously.',
      'Examples include web servers, email servers and file servers.',
    ],
    richBlocks: [
      {
        kind: 'figure',
        figure: {
          kind: 'sequence',
          title: 'Client-server communication process',
          items: [
            { label: '1. Client sends request', note: 'The client initiates communication by requesting a service (e.g., loading a web page).' },
            { label: '2. Server processes request', note: 'The server receives the request, processes it and prepares the response.' },
            { label: '3. Server sends response', note: 'The server sends the requested data back to the client.' },
            { label: '4. Client receives response', note: 'The client receives and displays the data (e.g., renders the web page).' },
          ],
          caption: 'Client-server request-response cycle. Every time you load a web page, this cycle happens.',
        },
      },
    ],
    example: {
      title: 'Real-world client-server examples',
      lines: [
        'Web browsing: Browser (client) ↔ Web server (server)',
        'Email: Email app (client) ↔ Mail server (server)',
        'Online gaming: Game app (client) ↔ Game server (server)',
        'File sharing: Explorer (client) ↔ File server (server)',
        'Amazon: Customer browser (client) ↔ Amazon servers (server)',
      ],
    },
    teacherPrompt: 'Ask: "Why would a school use a client-server network instead of peer-to-peer?" Expected answer: Centralised control, easier security management, shared resources, backup management.',
    visual: 'networking',
    accent: 'indigo',
    ...source([32,33], ['Figure 2.4', '2.1.2 Client-server model']),
  },

  {
    id: 'h2-212-p2p',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.2 · PEER-TO-PEER MODEL',
    title: 'Every peer can act as both client and server',
    lead: 'In a peer-to-peer network, each computer can share resources directly with other computers. There is no central server.',
    keyTerms: [
      { term: 'Peer-to-peer (P2P)', definition: 'A network model where each computer has equal status and can act as both client and server.' },
      { term: 'Decentralised', definition: 'No single point of control; resources are distributed across all peers.' },
    ],
    bullets: [
      'Each peer has equal status and can act as both client and server.',
      'There is no central server for managing the network.',
      'Resources are distributed across all peers.',
      'Easier to set up than client-server networks.',
      'Security is harder to manage without central control.',
      'The coursebook recommends this model for a small group, normally no more than ten nodes, where robust central security is unnecessary.',
    ],
    example: {
      title: 'Real-world P2P analogy',
      lines: [
        'Builder with workers: The builder (peer) can both give tasks and receive updates',
        'Each worker can also assign tasks to other workers',
        'No single person controls all communication',
        'Resources (tools, information) are shared directly between workers',
      ],
    },
    visual: 'networking',
    accent: 'cyan',
    ...source([34,35], ['Figure 2.5', 'Peer-to-peer model', 'builder and workers example']),
  },

  {
    id: 'h2-212-comparison',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.2 · CLIENT-SERVER VS PEER-TO-PEER',
    title: 'Compare the two network models',
    lead: 'The coursebook provides a detailed comparison of client-server and peer-to-peer networks.',
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'Client-Server',
        rightTitle: 'Peer-to-Peer',
        rows: [
          ['Centralised server manages resources', 'Resources distributed across peers'],
          ['More secure with centralised control', 'Less secure without central management'],
          ['Scalable but expensive', 'Easy to set up but limited scalability'],
          ['Server failure affects all clients', 'Individual peer failure does not affect others'],
          ['Used for large networks (businesses)', 'Used for small networks (homes)'],
          ['Easier to maintain and update', 'Harder to maintain across all peers'],
          ['Requires dedicated server hardware', 'No dedicated server needed'],
          ['User access controlled by network manager', 'Each user controls their own resources'],
        ],
      },
    ],
    visual: 'networking',
    accent: 'emerald',
    ...source([33,35], ['Client-server vs peer-to-peer comparison']),
  },

  checkpoint('h2-cp-models', '2.1 Networking', 'Past papers: client-server and peer-to-peer models', ['2.1.2'], [34], 'indigo'),

  // ─── NETWORK TOPOLOGIES ────────────────────────────────────────────────────
  {
    id: 'h2-213-topologies',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.3 · NETWORK TOPOLOGIES',
    title: 'Different physical layouts suit different network requirements',
    lead: 'The coursebook describes bus, star, mesh and hybrid topologies. Each layout changes how packets travel, where faults occur and how easily the network can grow.',
    keyTerms: [
      { term: 'Bus network topology', definition: 'All devices connect to one central cable; data travels in one direction and only one device transmits at a time.' },
      { term: 'Star network topology', definition: 'Every device has a dedicated connection to a central hub or switch.' },
      { term: 'Mesh network topology', definition: 'Interlinked devices use routing or flooding to carry packets through the network.' },
      { term: 'Hybrid network', definition: 'A combination of two or more network topologies.' },
    ],
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Network topologies comparison',
          headers: ['Topology', 'Advantages', 'Disadvantages'],
          rows: [
            ['Bus', 'Little cabling; easy to add nodes; one node failure does not stop the rest', 'Main cable failure stops all; performance falls under load; every node sees each packet'],
            ['Star', 'Few collisions; central security; easy upgrade; one broken link affects one node', 'High installation cost; central hub/switch failure stops the network'],
            ['Mesh', 'Broken links do not stop other nodes; faults are easy to locate; private dedicated routes', 'Much cabling; complex and costly setup and maintenance'],
            ['Hybrid', 'Handles high traffic; supports large networks; faults can be located', 'Complex to install, configure and maintain'],
          ],
        },
      },
    ],
    example: {
      title: 'Choosing a topology for a scenario',
      lines: [
        'Bus: small office with light traffic; terminators stop signal reflection at both ends.',
        'Star: an evolving network with heavy traffic and devices often added or removed.',
        'Mesh: hospital monitoring, industrial control, vehicles, WANs and the internet.',
        'Hybrid: three hotel chains using bus, star and mesh can be joined and expanded.',
      ],
    },
    visual: 'networking',
    accent: 'emerald',
    ...source([37,38], ['2.1.3 Network topologies', 'Figures 2.6–2.8', 'routing and flooding']),
  },

  // ─── NETWORK SIZES ─────────────────────────────────────────────────────────
  {
    id: 'h2-214-sizes',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.1 · NETWORK SIZES',
    title: 'Networks are classified by their geographical extent',
    lead: 'The coursebook classifies networks into four categories based on their size and geographical coverage.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Network size classification',
          headers: ['Type', 'Full Name', 'Typical Distance', 'Example'],
          rows: [
            ['WAN', 'Wide Area Network', '100 km+', 'Internet, corporate networks spanning countries'],
            ['MAN', 'Metropolitan Area Network', '1–100 km', 'City-wide network, university campus'],
            ['LAN', 'Local Area Network', '10 m–1 km', 'Office building, school, home'],
            ['PAN', 'Personal Area Network', '1–10 m', 'Bluetooth devices, USB connections'],
          ],
        },
      },
    ],
    visual: 'networking',
    accent: 'cyan',
    ...source(32, ['WAN, MAN, LAN and PAN distance guide']),
  },

  // ─── CLOUD COMPUTING ───────────────────────────────────────────────────────
  {
    id: 'h2-215-cloud',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.4 · PUBLIC AND PRIVATE CLOUD COMPUTING',
    title: 'Cloud systems store data and provide software on remote servers',
    lead: 'The coursebook distinguishes public, private and hybrid clouds, then examines cloud storage, data redundancy, security, potential data loss and cloud software.',
    keyTerms: [
      { term: 'Cloud storage', definition: 'A method in which data is stored on off-site servers.' },
      { term: 'Data redundancy', definition: 'The same data is stored on several servers so it remains available during maintenance or repair.' },
      { term: 'Public cloud', definition: 'The customer and cloud provider are separate companies and the provider supplies the storage environment.' },
      { term: 'Private cloud', definition: 'Storage is provided in a dedicated environment behind an organisation’s firewall.' },
      { term: 'Hybrid cloud', definition: 'Sensitive data remains in a private cloud while less sensitive data can use a public provider.' },
    ],
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'Public Cloud',
        rightTitle: 'Private Cloud',
        rows: [
          ['Customer and provider are separate', 'Dedicated environment integrated with the customer'],
          ['Provider controls the storage infrastructure', 'Organisation retains tighter control behind its firewall'],
          ['Suitable for less sensitive data', 'Suitable for sensitive or commercially valuable data'],
          ['Broad remote access', 'Access follows the organisation’s own security policy'],
        ],
      },
    ],
    visual: 'internet',
    accent: 'rose',
    ...source(39, ['2.1.4 Public and private cloud computing', 'Figure 2.9']),
  },

  {
    id: 'h2-215-cloud-storage',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.4 · CLOUD STORAGE',
    title: 'Cloud storage has specific advantages and disadvantages',
    lead: 'The coursebook provides a detailed comparison of cloud storage benefits and risks.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Table 2.3 · Pros and cons of cloud storage',
          headers: ['Pros', 'Cons'],
          rows: [
            ['Files are available from any device and location with internet access', 'Slow or unstable internet makes access and downloads difficult'],
            ['No external storage device or one specific computer is required', 'Large storage capacity can be expensive'],
            ['Remote backup supports disaster recovery', 'High upload/download limits can cost more through the ISP'],
            ['Data can be recovered after a local disk or backup-device failure', 'Provider failure can put every backup at risk'],
            ['Almost unlimited storage capacity', 'Control of confidential data security passes to the provider'],
          ],
        },
      },
    ],
    teacherPrompt: 'Ask: "Would you store your school coursework on a public cloud or a private cloud? Justify your choice." Expected answer: Public cloud is cheaper and accessible from anywhere; private cloud offers more security for sensitive data.',
    visual: 'internet',
    accent: 'amber',
    ...source(40, ['Table 2.3', 'Data security and potential data loss']),
  },

  // ─── WIRED AND WIRELESS ────────────────────────────────────────────────────
  {
    id: 'h2-216-wired',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.5 · WIRED NETWORKING',
    title: 'Wired connections use copper or fibre optic cables',
    lead: 'The coursebook compares copper cables with fibre optic cables for wired networking.',
    keyTerms: [
      { term: 'Twisted-pair cable', definition: 'A type of copper cable consisting of pairs of wires twisted together to reduce interference.' },
      { term: 'Fibre optic cable', definition: 'A cable that transmits data as light pulses through glass or plastic fibres, offering high speed and distance.' },
      { term: 'Coaxial cable', definition: 'A cable with a central conductor surrounded by insulation and a metallic shield.' },
    ],
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Copper vs fibre optic cables',
          headers: ['Feature', 'Copper (Twisted-pair)', 'Fibre Optic'],
          rows: [
            ['Signal', 'Electrical pulses through twisted-pair or coaxial copper', 'Light pulses through glass fibres'],
            ['Transfer rate', 'Twisted pair is lowest; coaxial is higher', 'Highest of the three cable types'],
            ['Attenuation', 'Coaxial has the greatest attenuation', 'Smallest attenuation; suited to long distances'],
            ['Interference', 'Twisted pair suffers most; coaxial has strong anti-jamming', 'Very high resistance to external interference'],
            ['Cost', 'Twisted pair is cheapest; coaxial costs more', 'Highest cost'],
            ['Capacity', 'Coaxial is about 80× twisted pair', 'About 26,000× twisted-pair capacity'],
          ],
        },
      },
    ],
    visual: 'networking',
    accent: 'indigo',
    ...source(44, ['2.1.5 Wired networking', 'Figure 2.12']),
  },

  {
    id: 'h2-216-attenuation',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.5 · BANDWIDTH, PENETRATION AND ATTENUATION',
    title: 'Wireless media must be compared using three separate properties',
    lead: 'Bandwidth measures capacity, penetration measures passage through materials, and attenuation is the reduction in signal amplitude.',
    bullets: [
      'Bandwidth: infrared > microwaves > radio waves.',
      'Penetration: radio waves > microwaves > infrared.',
      'The coursebook ranks attenuation as radio waves > microwaves > infrared.',
      'Infrared is useful indoors because walls stop it and reduce interference elsewhere.',
      'Microwaves provide a compromise between bandwidth, penetration and attenuation.',
    ],
    example: {
      title: 'Coursebook comparison',
      lines: [
        'Table 2.4 links wavelength and frequency across the electromagnetic spectrum.',
        'Table 2.5 compares radio waves, microwaves and infrared.',
        'Figures 2.10 and 2.11 show why satellites overcome the Earth’s curvature.',
      ],
    },
    visual: 'networking',
    accent: 'cyan',
    ...source(43, ['Tables 2.4–2.5', 'Figures 2.10–2.11']),
  },

  {
    id: 'h2-216-fibre-modes',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.5 · FIBRE OPTIC MODES',
    title: 'Single-mode and multi-mode fibre serve different purposes',
    lead: 'The coursebook distinguishes between single-mode and multi-mode fibre optic cables.',
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'Single-mode Fibre',
        rightTitle: 'Multi-mode Fibre',
        rows: [
          ['Single-mode light source', 'Multi-mode light source'],
          ['Smaller central core', 'Construction creates more reflection in the core'],
          ['Less reflection', 'Higher reflection'],
          ['Data travels faster and further', 'Best over shorter distances'],
          ['CATV and telecommunications', 'LAN connections'],
        ],
      },
    ],
    visual: 'networking',
    accent: 'emerald',
    ...source(43, ['Single-mode vs multi-mode fibre']),
  },

  {
    id: 'h2-216-wireless',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.5 · WIRELESS NETWORKING',
    title: 'Wireless networks use radio waves for communication',
    lead: 'The coursebook describes WiFi and Bluetooth as the main wireless technologies.',
    keyTerms: [
      { term: 'WiFi', definition: 'Wireless networking technology using IEEE 802.11 standards.' },
      { term: 'Bluetooth', definition: 'Wireless connectivity that uses radio waves in the 2.45 GHz frequency band.' },
      { term: 'WAP', definition: 'Wireless Access Point: a device that allows wireless devices to connect to a wired network.' },
    ],
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Wired vs wireless comparison',
          headers: ['Feature', 'Wired networking', 'Wireless networking'],
          rows: [
            ['Expansion', 'Cables must be bought and installed', 'Easier to expand because cables are unnecessary'],
            ['Mobility', 'Devices must remain close enough for their cable connection', 'Devices are mobile while they remain within WAP range'],
            ['Reliability', 'More reliable and stable; no wireless interference or dead spots', 'External interference, thick walls and signal drop-out can affect the connection'],
            ['Security', 'Cable traffic is harder to intercept', 'Radio and microwave signals are easier to intercept, so encryption such as WEP or WPA2 is essential'],
            ['Data transfer', 'Rates tend to be faster', 'Rates are slower, although improving'],
            ['Cost and safety', 'Usually cheaper overall, but wires can cause trips, overheating or accidental disconnection', 'No network cabling is needed'],
          ],
        },
      },
    ],
    visual: 'networking',
    accent: 'cyan',
    ...source([41, 45], ['2.1.5 Wi-Fi and Bluetooth', 'Wireless and wired networking comparison']),
  },

  {
    id: 'h2-216-spread-spectrum',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.5 · SPREAD SPECTRUM',
    title: 'Spread spectrum frequency hopping reduces interference',
    lead: 'The coursebook explains that Bluetooth uses spread spectrum frequency hopping to avoid interference.',
    bullets: [
      'Spread spectrum technology spreads signals across multiple frequencies.',
      'Frequency hopping rapidly switches between different frequencies.',
      'This reduces interference from other devices using the same frequency band.',
      'Bluetooth communicating pairs change channels several times per second.',
      'Multiple Bluetooth devices can operate in the same area without interfering.',
    ],
    visual: 'networking',
    accent: 'amber',
    ...source(44, ['Spread spectrum frequency hopping']),
  },

  {
    id: 'h2-216-wnic',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · WIRELESS NETWORK INTERFACE CARD',
    title: 'WNICs operate in infrastructure or ad-hoc mode',
    lead: 'The coursebook describes two modes of operation for wireless network interface cards.',
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'Infrastructure Mode',
        rightTitle: 'Ad-hoc Mode',
        rows: [
          ['Requires WAPs (wireless access points)', 'No WAPs needed'],
          ['All data transferred via WAP and hub/switch', 'Devices communicate directly'],
          ['All devices connect to the WAP and use the same security and authentication techniques', 'Devices interface with each other directly'],
        ],
      },
    ],
    visual: 'networking',
    accent: 'emerald',
    ...source(50, ['WNIC infrastructure mode and ad hoc mode']),
  },

  {
    id: 'h2-216-softmodem',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · SOFTMODEM',
    title: 'A softmodem uses software instead of dedicated hardware',
    lead: 'The coursebook describes a softmodem (software modem) that uses minimal hardware and host computer resources.',
    bullets: [
      'A softmodem uses software that runs on the host computer.',
      'The computer\'s processor and RAM replace the hardware of a conventional modem.',
      'Only minimal modem hardware is required.',
    ],
    visual: 'networking',
    accent: 'indigo',
    ...source(49, ['Softmodem description']),
  },

  // ─── NETWORK DEVICES ───────────────────────────────────────────────────────
  {
    id: 'h2-217-devices',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · NETWORK DEVICES',
    title: 'Different devices serve different roles in a network',
    lead: 'The coursebook describes hubs, switches, routers, bridges, gateways, modems and NICs as the main networking devices.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Network devices comparison',
          headers: ['Device', 'Function', 'Addressing'],
          rows: [
            ['Hub', 'Broadcasts incoming data to all connected ports', 'None'],
            ['Switch', 'Forwards data only to the intended recipient using MAC addresses', 'MAC address'],
            ['Router', 'Routes data between different networks using IP addresses', 'IP address'],
            ['Bridge', 'Connects two network segments and filters traffic', 'MAC address'],
            ['Gateway', 'Converts data from one protocol to another', 'Protocol conversion'],
            ['Modem', 'Converts digital data to analogue and vice versa', 'Signal conversion'],
            ['NIC', 'Allows a device to connect to a network', 'MAC address'],
          ],
        },
      },
    ],
    visual: 'networking',
    accent: 'indigo',
    ...source(45, ['2.1.6 Hardware requirements of networks', 'Figure 2.13']),
  },

  {
    id: 'h2-217-repeaters',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · REPEATERS',
    title: 'Repeaters regenerate signals to extend network distance',
    lead: 'The coursebook explains that repeaters are used to overcome attenuation.',
    bullets: [
      'A repeater boosts an attenuated signal so it can travel further.',
      'It can amplify analogue signals on copper and digital signals on fibre-optic links.',
      'A wireless repeater boosts Wi-Fi signals to reduce dead spots.',
      'It is a non-logical device: it boosts every detected signal and does not select between them.',
      'A repeating hub combines hub distribution with signal boosting but still has one collision domain.',
    ],
    visual: 'networking',
    accent: 'cyan',
    ...source(46, ['Repeater description']),
  },

  {
    id: 'h2-217-hubs',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · HUBS',
    title: 'Hubs broadcast data to all connected devices',
    lead: 'The coursebook describes hubs as simple devices that send all incoming data to every port.',
    bullets: [
      'A hub broadcasts incoming data to all connected ports.',
      'Every computer on the network receives each data packet.',
      'This method is insecure and wastes network bandwidth.',
      'Hubs can be wired or wireless devices.',
    ],
    richBlocks: [
      {
        kind: 'callout',
        tone: 'warning',
        title: 'Hub limitation',
        text: 'A hub sends every packet to every computer. A switch checks the destination address and sends the packet only to the appropriate computer or computers.',
      },
    ],
    visual: 'networking',
    accent: 'amber',
    ...source([45, 46], ['Hub description', 'Figure 2.13']),
  },

  {
    id: 'h2-217-switches',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · SWITCHES',
    title: 'Switches forward data only to the intended recipient',
    lead: 'The coursebook explains that a switch checks each packet and uses its destination address to select the appropriate recipient.',
    bullets: [
      'Like a hub, a switch connects devices or computers to form a LAN.',
      'The switch checks the received data packet and works out its destination address or addresses.',
      'It sends the packet only to the appropriate computer or computers.',
      'Packets carry the source MAC address and the MAC address of each intended recipient.',
      'This makes distribution more secure and efficient than using a hub.',
      'Switches can be wired or wireless devices.',
    ],
    visual: 'networking',
    accent: 'emerald',
    ...source(46, ['Switch description', 'Figure 2.14']),
  },

  {
    id: 'h2-217-bridges',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · BRIDGES',
    title: 'Bridges connect LANs that use the same protocol',
    lead: 'The coursebook describes bridges as devices that connect one LAN to another LAN using the same protocol.',
    bullets: [
      'A bridge connects one LAN to another LAN that uses the same communication protocol.',
      'It can connect different parts of a LAN so that they function as a single LAN.',
      'Interconnecting LANs with a bridge avoids sending every packet to every possible destination and reduces unnecessary traffic.',
      'Bridges can be wired or wireless devices.',
    ],
    visual: 'networking',
    accent: 'cyan',
    ...source(47, ['Bridge description', 'Figure 2.15']),
  },

  {
    id: 'h2-217-routers',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · ROUTERS',
    title: 'Routers connect different networks and route data packets',
    lead: 'The coursebook explains that routers enable data packets to be routed between different networks.',
    bullets: [
      'Routers restrict broadcasts to a LAN.',
      'They act as a default gateway.',
      'Routers can perform protocol translation (e.g., Ethernet to wireless).',
      'They can move data between networks.',
      'Routers calculate the best route to a network destination address.',
    ],
    richBlocks: [
      {
        kind: 'steps',
        title: 'Router functions',
        items: [
          'Restrict broadcasts to a LAN',
          'Act as a default gateway',
          'Perform protocol translation (e.g., Ethernet to wireless)',
          'Move data between networks',
          'Calculate the best route to a network destination address',
        ],
      },
    ],
    visual: 'networking',
    accent: 'emerald',
    ...source([47, 48], ['Router description', 'Figure 2.16']),
  },

  {
    id: 'h2-217-gateways',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · GATEWAYS',
    title: 'Gateways connect networks using different protocols',
    lead: 'The coursebook describes gateways as network points that act as entrances to other networks.',
    bullets: [
      'A gateway is a network point (node) that acts as an entrance to another network.',
      'It can connect two or more dissimilar LANs (LANs using different protocols).',
      'The gateway converts data packets from one protocol to another.',
      'Gateways can also act as routers, firewalls or servers.',
      'All networks have boundaries; gateways allow communication outside the network.',
    ],
    visual: 'networking',
    accent: 'indigo',
    ...source(48, ['Gateway description']),
  },

  {
    id: 'h2-217-routers-gateways',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · ROUTERS VS GATEWAYS',
    title: 'Compare the differences between routers and gateways',
    lead: 'The coursebook provides a detailed comparison table of routers and gateways.',
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'Routers',
        rightTitle: 'Gateways',
        rows: [
          ['Forward packets from one network to another', 'Convert one protocol to another protocol'],
          ['Read each incoming packet and decide where to forward', 'Convert data packets from one protocol to another'],
          ['Can route traffic from one network to another', 'Act as entry and exit point to networks'],
          ['Can join LANs to form a WAN', 'Can translate from one protocol to another'],
          ['Offer additional features like dynamic routing', 'Do not support dynamic routing'],
        ],
      },
    ],
    visual: 'networking',
    accent: 'amber',
    ...source(49, ['Table 2.6 · Routers vs gateways']),
  },

  {
    id: 'h2-217-modems',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · MODEMS',
    title: 'Modems convert digital data to analogue for transmission',
    lead: 'The coursebook explains that modems (modulator-demodulator) convert digital data to analogue and vice versa.',
    bullets: [
      'Modern computers work with digital data, but public communication channels often use analogue.',
      'A modem converts digital data to analogue for transmission.',
      'It also converts received analogue data back to digital.',
      'Wireless modems transmit data in a modulated form.',
      'Routers and modems can be combined into one unit.',
    ],
    example: {
      title: 'Modem connection path',
      lines: [
        'Computer → Router → Modem → ISP → Internet',
        'Modem connects to public infrastructure (cable, telephone, fibre-optics or satellite)',
        'Supplies standard Ethernet output for router connection',
      ],
    },
    visual: 'networking',
    accent: 'cyan',
    ...source(49, ['Modem description']),
  },

  {
    id: 'h2-217-nic-wnic',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.6 · NETWORK INTERFACE CARDS',
    title: 'NICs and WNICs allow devices to connect to networks',
    lead: 'The coursebook describes NICs and WNICs as essential hardware for network connectivity.',
    bullets: [
      'A Network Interface Card (NIC) allows a device to connect to a network.',
      'It usually contains the MAC address generated at manufacturing.',
      'Wireless Network Interface Cards (WNICs) use an antenna to communicate via microwaves.',
      'WNICs normally plug into a USB port or can be internal.',
      'WNICs work on layers 1 and 2 of the OSI model.',
    ],
    visual: 'networking',
    accent: 'emerald',
    ...source(50, ['NIC and WNIC description']),
  },

  checkpoint('h2-cp-devices', '2.1 Networking', 'Past papers: network devices and their functions', ['2.1.7'], [50], 'indigo'),

  // ─── ETHERNET ───────────────────────────────────────────────────────────────
  {
    id: 'h2-218-ethernet',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.7 · ETHERNET',
    title: 'Ethernet defines how data is formatted and transmitted on a LAN',
    lead: 'The coursebook explains that Ethernet is a protocol used by many wired LANs, adopted as IEEE 802.3.',
    keyTerms: [
      { term: 'Ethernet', definition: 'A family of networking technologies for local area networks using CSMA/CD.' },
      { term: 'IEEE 802.3', definition: 'The standard that defines Ethernet protocols.' },
      { term: 'Node', definition: 'Any device on the LAN.' },
      { term: 'Frame', definition: 'Data transmitted in frames made up of source and destination addresses.' },
    ],
    bullets: [
      'Ethernet is a protocol used by many wired LANs.',
      'It was adopted as a standard by the IEEE (Institute of Electrical and Electronic Engineers).',
      'Ethernet is also known as IEEE 802.3.',
      'A network using Ethernet is made up of: a node, medium (cable), and frame.',
      'Frames contain source address and destination address (often MAC addresses).',
    ],
    visual: 'networking',
    accent: 'indigo',
    ...source(50, ['2.1.7 Ethernet', 'Figures 2.18–2.19']),
  },

  {
    id: 'h2-218-conflicts',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.7 · IP ADDRESS CONFLICTS',
    title: 'Conflicts occur when devices share the same IP address',
    lead: 'The coursebook explains that IP address conflicts can occur on networks using dynamic IP addresses.',
    bullets: [
      'IP address conflicts occur when devices on the same network have the same IP address.',
      'Without a unique IP address, it is not possible to connect to a network.',
      'This is most likely to occur on a LAN where dynamic IP addresses may have been used.',
      'Dynamic IP addresses are temporary and may have been assigned to a device.',
      'Another device using static IP addresses may already have the same IP address.',
      'This can be resolved by re-starting the router.',
    ],
    visual: 'networking',
    accent: 'amber',
    ...source(51, ['IP address conflict description']),
  },

  {
    id: 'h2-218-collisions',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.7 · DATA COLLISIONS',
    title: 'Collisions occur when two devices transmit simultaneously',
    lead: 'The coursebook explains that Ethernet supports broadcast transmission and the risk of collisions.',
    bullets: [
      'Ethernet supports broadcast transmission (data sent from sender to receiver).',
      'The risk is that two messages using the same data channel could be sent at the same time.',
      'This leads to a collision where data is corrupted.',
      'CSMA/CD (Carrier Sense Multiple Access with Collision Detection) was developed to resolve this.',
      'Collision detection depends on simple physics: a frame causes a voltage change on the cable.',
    ],
    visual: 'networking',
    accent: 'rose',
    ...source(51, ['Data collision description']),
  },

  {
    id: 'h2-218-csma-cd',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.7 · CSMA/CD PROTOCOL',
    title: 'CSMA/CD manages access to the shared Ethernet medium',
    lead: 'The coursebook provides a detailed flow diagram of how CSMA/CD handles collisions.',
    richBlocks: [
      {
        kind: 'steps',
        title: 'CSMA/CD process',
        items: [
          'Device listens to the cable (carrier sense).',
          'If the cable is free, device starts transmitting.',
          'If a collision is detected, both devices stop.',
          'Both devices send a jam signal to notify others.',
          'Each device waits a random backoff time.',
          'Devices retry transmission after the backoff period.',
        ],
      },
      {
        kind: 'table',
        table: {
          caption: 'CSMA/CD transmission counters',
          headers: ['Counter Value', 'Action'],
          rows: [
            ['1', 'First transmission attempt'],
            ['2', 'First collision detected, wait random time'],
            ['3', 'Second collision detected, wait longer random time'],
            ['Max', 'Abort transmission after maximum retries'],
          ],
        },
      },
    ],
    example: {
      title: 'CSMA/CD in action',
      lines: [
        'Step 1: Device A wants to send data to Device B',
        'Step 2: Device A listens — cable is free',
        'Step 3: Device A starts transmitting',
        'Step 4: Device C also wants to send — listens — cable is busy',
        'Step 5: Device A finishes — Device C now transmits',
      ],
    },
    activity: {
      title: 'Trace a collision',
      prompt: 'Two devices on the same Ethernet network try to transmit at exactly the same time. Describe what happens step by step, including the role of CSMA/CD.',
      reveal: '(1) Both devices detect the cable is free. (2) Both start transmitting simultaneously. (3) A collision occurs and data is corrupted. (4) Both devices detect the collision and stop. (5) Both send a jam signal. (6) Both wait a random backoff time. (7) After the backoff, one device retries first.',
    },
    visual: 'networking',
    accent: 'emerald',
    ...source(51, ['CSMA/CD flow diagram', 'Figure 2.20']),
  },

  checkpoint('h2-cp-ethernet', '2.1 Networking', 'Past papers: Ethernet, CSMA/CD and frame structure', ['2.1.8'], [53], 'emerald'),

  // ─── BIT STREAMING ──────────────────────────────────────────────────────────
  {
    id: 'h2-219-bitstreaming',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.8 · BIT STREAMING',
    title: 'Bit streaming sends a contiguous sequence of digital bits',
    lead: 'The coursebook defines bit streaming as a contiguous sequence of digital bits sent over the internet or a network that requires high speed data communication.',
    keyTerms: [
      { term: 'Bit streaming', definition: 'A contiguous sequence of digital bits sent over the internet or a network that requires high speed data communication.' },
      { term: 'Buffer', definition: 'A temporary storage area that ensures smooth playback of media files.' },
      { term: 'Data compression', definition: 'Reducing the size of files before transmission.' },
    ],
    bullets: [
      'Bit streaming often involves very large files (such as video).',
      'Files undergo data compression before transmission.',
      'Buffering ensures smooth playback of media files.',
      'The data transmission rate from the file server must be greater than the rate from buffer to media player.',
      'The larger the buffer, the better the control over the bit rate.',
    ],
    richBlocks: [{
      kind: 'figure',
      figure: {
        kind: 'sequence',
        title: 'Figure 2.21 reconstructed · bit streaming path',
        items: [
          { label: 'File server', note: 'Compressed media stream' },
          { label: 'Network link', note: 'Incoming rate must sustain playback' },
          { label: 'Buffer', note: 'Low and high water marks' },
          { label: 'Media player', note: 'Consumes the stream' },
        ],
        caption: 'Temporary buffering absorbs changes in arrival rate so playback remains smooth.',
      },
    }],
    visual: 'internet',
    accent: 'amber',
    ...source(52, ['2.1.8 Bit streaming', 'Figure 2.21']),
  },

  {
    id: 'h2-219-buffering',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.8 · BUFFER MANAGEMENT',
    title: 'Buffers ensure smooth playback by managing data flow',
    lead: 'The coursebook explains how buffers work with low and high water marks.',
    bullets: [
      'The media player checks to ensure data lies between a minimum value (low water mark) and a maximum value (high water mark).',
      'The difference between the two values is usually about 80% of the total buffer capacity.',
      'The buffer is a temporary storage area of the computer.',
      'Data is streamed from server to buffer to media player.',
      'The buffer size determines how much data is stored before playback begins.',
    ],
    visual: 'internet',
    accent: 'cyan',
    ...source(52, ['Buffer management description']),
  },

  {
    id: 'h2-219-pros-cons',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.8 · PROS AND CONS OF BIT STREAMING',
    title: 'Bit streaming has specific advantages and disadvantages',
    lead: 'The coursebook provides a detailed comparison table of bit streaming benefits and drawbacks.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Table 2.7 · Pros and cons of bit streaming',
          headers: ['Pros', 'Cons'],
          rows: [
            ['No need to wait for whole file to download', 'Cannot stream if broadband connection is lost'],
            ['No need to store large files on device', 'Files will pause if insufficient buffer or slow connection'],
            ['Allows video/music to be played on demand', 'Streaming uses up a lot of bandwidth'],
            ['No need for specialist hardware', 'Security risks from downloading files'],
            ['Affords piracy protection', 'Copyright issues'],
          ],
        },
      },
    ],
    visual: 'internet',
    accent: 'emerald',
    ...source(52, ['Table 2.7 · Bit streaming pros/cons']),
  },

  {
    id: 'h2-219-on-demand',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.8 · ON-DEMAND BIT STREAMING',
    title: 'On-demand streaming broadcasts files as and when required',
    lead: 'The coursebook describes the process for on-demand bit streaming.',
    bullets: [
      'Digital files stored on a server are converted to a bit streaming format.',
      'Encoding takes place and the encoded files are uploaded to a server.',
      'A link to the encoded video/music file is placed on the web server.',
      'The user clicks on the link and the file is downloaded in a contiguous bit stream.',
      'The streamed video/music is broadcast to the user as and when required.',
      'It is possible to pause, rewind and fast forward the video/music.',
    ],
    visual: 'internet',
    accent: 'indigo',
    ...source(53, ['On-demand bit streaming process']),
  },

  {
    id: 'h2-219-real-time',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: '2.1.8 · REAL-TIME BIT STREAMING',
    title: 'Real-time streaming broadcasts live events',
    lead: 'The coursebook describes the process for real-time bit streaming.',
    bullets: [
      'An event is captured by camera and microphone and sent to a computer.',
      'The video signal is converted (encoded) to a streaming media file.',
      'The encoded file is uploaded to a dedicated video streaming server.',
      'The server sends the encoded live video to the user\'s device.',
      'Since the video footage is live it is not possible to pause, rewind or fast forward.',
    ],
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'On-demand',
        rightTitle: 'Real-time',
        rows: [
          ['Files stored on server', 'Live event captured'],
          ['Can pause, rewind, fast forward', 'Cannot pause, rewind, fast forward'],
          ['User chooses when to watch', 'Watch as it happens'],
          ['Pre-recorded content', 'Live content'],
        ],
      },
    ],
    visual: 'internet',
    accent: 'cyan',
    ...source(53, ['Real-time bit streaming process']),
  },

  // ─── 2.2 THE INTERNET ─────────────────────────────────────────────────────
  // ─── INTERNET VS WEB ────────────────────────────────────────────────────────
  {
    id: 'h2-221-internet',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.1 · THE INTERNET',
    title: 'The internet is a massive network of networks',
    lead: 'The coursebook defines the internet as a massive network of networks made up of various computers and other electronic devices.',
    keyTerms: [
      { term: 'Internet', definition: 'A massive network of networks, made up of computers and other electronic devices; uses TCP/IP communication protocols.' },
      { term: 'TCP/IP', definition: 'Transmission Control Protocol/Internet Protocol: the fundamental protocols of the internet.' },
    ],
    bullets: [
      'The internet stands for interconnected network.',
      'It is a massive network of networks.',
      'The internet makes use of TCP/IP protocols.',
      'It connects computers and electronic devices worldwide.',
      'The internet is not necessarily a WAN (it connects many different network types).',
    ],
    visual: 'internet',
    accent: 'indigo',
    ...source(54, ['2.2.1 The internet definition']),
  },

  {
    id: 'h2-221-web',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.1 · THE WORLD WIDE WEB',
    title: 'The WWW is a collection of multimedia web pages',
    lead: 'The coursebook defines the World Wide Web as a collection of multimedia web pages and other documents stored on websites.',
    keyTerms: [
      { term: 'World Wide Web (WWW)', definition: 'Collection of multimedia web pages stored on a website, which uses the internet to access information from servers and other computers.' },
      { term: 'HTML', definition: 'HyperText Mark-up Language: used to design web pages and write http(s) protocols.' },
      { term: 'URL', definition: 'Uniform Resource Locator: specifies location of a web page.' },
      { term: 'Web browser', definition: 'Software that connects to DNS to locate IP addresses; interprets web pages.' },
      { term: 'ISP', definition: 'Internet Service Provider: company which allows a user to connect to the internet.' },
    ],
    bullets: [
      'The WWW is a collection of multimedia web pages and documents stored on websites.',
      'http(s) protocols are written using HTML.',
      'Uniform resource locators (URLs) specify the location of all web pages.',
      'Web resources are accessed by web browsers.',
      'The WWW uses the internet to access information from servers.',
    ],
    visual: 'internet',
    accent: 'cyan',
    ...source(55, ['2.2.1 The World Wide Web definition']),
  },

  {
    id: 'h2-221-comparison',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.1 · INTERNET VS WORLD WIDE WEB',
    title: 'The internet is the infrastructure; the web is a service on it',
    lead: 'The coursebook clearly distinguishes the physical network (internet) from the information system (World Wide Web).',
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'Internet',
        rightTitle: 'World Wide Web',
        rows: [
          ['Physical infrastructure', 'Information service'],
          ['Created in 1969 (ARPANET)', 'Created in 1991 (Tim Berners-Lee)'],
          ['Uses TCP/IP protocols', 'Uses HTTP/HTTPS protocols'],
          ['Includes email, FTP, streaming', 'Only hypertext documents'],
          ['Hardware and network layer', 'Application layer'],
          ['Massive network of networks', 'Collection of multimedia web pages'],
        ],
      },
      {
        kind: 'callout',
        tone: 'warning',
        title: 'Common exam mistake',
        text: 'Do NOT confuse the internet with the World Wide Web. The internet is the physical infrastructure (cables, routers, servers). The web is a service that runs on the internet. The internet existed before the web (1969 vs 1991).',
      },
    ],
    teacherPrompt: 'Ask: "If the internet is the infrastructure, what would happen to the web if the internet went down?" Expected answer: The web would be inaccessible because it depends on the internet infrastructure to deliver documents.',
    visual: 'internet',
    accent: 'emerald',
    ...source(54, ['Internet vs WWW comparison']),
  },

  // ─── INTERNET INFRASTRUCTURE ────────────────────────────────────────────────
  {
    id: 'h2-222-hardware',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.2 · INTERNET INFRASTRUCTURE',
    title: 'Multiple hardware and software components support internet access',
    lead: 'The coursebook lists the essential components for connecting to the internet.',
    bullets: [
      'A device (such as a computer, tablet or mobile phone).',
      'A telephone line connection or a mobile phone network connection.',
      'A router (which can be wired or wireless) or router and modem.',
      'An internet service provider (ISP) (combination of hardware and software).',
      'A web browser.',
    ],
    richBlocks: [
      {
        kind: 'steps',
        title: 'How your computer connects to the internet',
        items: [
          'Your computer connects to a router (wired or wireless).',
          'The router connects to a modem.',
          'The modem connects to your ISP.',
          'The ISP connects to the internet backbone.',
          'Data travels through multiple routers to reach its destination.',
        ],
      },
    ],
    visual: 'internet',
    accent: 'cyan',
    ...source(55, ['2.2.2 Hardware and software needed']),
  },

  {
    id: 'h2-222-pstn',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.2 · PUBLIC SWITCHED TELEPHONE NETWORK',
    title: 'PSTN uses circuit switching for telephone calls',
    lead: 'The coursebook explains how PSTN works for traditional telephone calls.',
    bullets: [
      'PSTN uses a standard telephone connected to a telephone line.',
      'The telephone line connection is always open whether or not anybody is talking.',
      'The link is not terminated until the receivers are replaced by both parties.',
      'Telephone lines remain active even during a power cut.',
      'Modern phones use fibre optic cables.',
      'PSTN uses circuit switching (connection maintained throughout the call).',
    ],
    visual: 'internet',
    accent: 'indigo',
    ...source(56, ['PSTN description']),
  },

  {
    id: 'h2-222-voip',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.2 · VOICE OVER INTERNET PROTOCOL',
    title: 'VoIP converts voice to digital packets for internet transmission',
    lead: 'The coursebook explains how VoIP works for internet-based phone calls.',
    bullets: [
      'VoIP converts voice and webcam images into digital packages.',
      'The internet connection is only "live" while data is being transmitted.',
      'VoIP uses packet switching (no dedicated line).',
      'Data is routed through thousands of possible pathways.',
      'The fastest route is determined for each packet.',
      'VoIP carries out file compression to reduce data transmission.',
    ],
    example: {
      title: 'Efficiency comparison',
      lines: [
        'PSTN 10-minute call: ~10 MB of data (line always open)',
        'VoIP 10-minute call: ~3 MB of data (only 3 minutes of actual talking)',
        'VoIP is much more efficient than PSTN',
      ],
    },
    visual: 'internet',
    accent: 'cyan',
    ...source(56, ['VoIP description']),
  },

  {
    id: 'h2-222-pstn-voip',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.2 · PSTN VS VOIP',
    title: 'Compare the differences between PSTN and VoIP',
    lead: 'The coursebook provides a detailed comparison of PSTN and internet-based phone calls.',
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'PSTN',
        rightTitle: 'VoIP (Internet)',
        rows: [
          ['Uses standard telephone and line', 'Uses internet phone or microphone/speakers'],
          ['Line always open during call', 'Connection only live while data transmitted'],
          ['Circuit switching', 'Packet switching'],
          ['~10 MB for 10-minute call', '~3 MB for 10-minute call'],
          ['Active during power cut', 'Requires power and internet'],
          ['Dedicated connection', 'No dedicated line'],
        ],
      },
    ],
    visual: 'internet',
    accent: 'emerald',
    ...source(56, ['PSTN vs VoIP comparison']),
  },

  {
    id: 'h2-222-satellites',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.2 · SATELLITES',
    title: 'Satellites are classified by their orbital height',
    lead: 'The coursebook describes three types of satellite orbits for different communication purposes.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Satellite classification',
          headers: ['Type', 'Full Name', 'Orbital Height', 'Period', 'Use'],
          rows: [
            ['GEO', 'Geostationary Earth Orbit', '35,800 km', '24 hours', 'Long distance telephone and computer network communications'],
            ['MEO', 'Medium Earth Orbit', '5,000–12,000 km', '2–12 hours', 'GPS systems (about 10 MEO satellites currently orbiting)'],
            ['LEO', 'Low Earth Orbit', '500–2,500 km', '80 mins–2 hours', 'Mobile phone networks (more than 100 LEO satellites currently)'],
          ],
        },
      },
    ],
    bullets: [
      'Satellites have the advantage of complete coverage.',
      'They don\'t suffer from signal attenuation to the same extent as cables.',
      'It is difficult to isolate and resolve faults in cables on the sea bed.',
    ],
    visual: 'internet',
    accent: 'amber',
    ...source(57, ['Satellite classification', 'Figure 2.22']),
  },

  // ─── IP ADDRESSES ───────────────────────────────────────────────────────────
  {
    id: 'h2-223-ipv4',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · IP ADDRESSES',
    title: 'Every device on the internet needs a unique IP address',
    lead: 'The coursebook explains that the internet is based on TCP/IP protocols and describes IPv4 addressing.',
    keyTerms: [
      { term: 'IPv4', definition: 'Internet Protocol version 4: uses 32-bit addresses written as four decimal numbers (e.g., 254.0.128.77).' },
      { term: 'IPv6', definition: 'Internet Protocol version 6: uses 128-bit addresses written in hexadecimal (e.g., A8FB:7A88:FFF0:0FFF:3D21:2085:66FB:F0FA).' },
      { term: 'netID', definition: 'Network identifier portion of an IP address.' },
      { term: 'hostID', definition: 'Host identifier portion of an IP address.' },
    ],
    bullets: [
      'The most common type of addressing is IPv4.',
      'IPv4 is based on 32 bits giving 2^32 (4,294,967,296) possible addresses.',
      'The 32 bits are split into four groups of 8 bits (range 0 to 255).',
      'The system uses groups of bits to define network (netID) and host (hostID).',
      'Networks are split into five different classes (A, B, C, D, E).',
    ],
    visual: 'internet',
    accent: 'indigo',
    ...source(57, ['2.2.3 IP addresses']),
  },

  {
    id: 'h2-223-classes',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · NETWORK CLASSES',
    title: 'IPv4 addresses are divided into five classes',
    lead: 'The coursebook provides a detailed table of the five network classes.',
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Table 2.8 · The five network classes',
          headers: ['Class', 'IPv4 Range', 'netID bits', 'hostID bits', 'Network Type'],
          rows: [
            ['A', '0.0.0.0 to 127.255.255.255', '8', '24', 'Very large'],
            ['B', '128.0.0.0 to 191.255.255.255', '16', '16', 'Medium size'],
            ['C', '192.0.0.0 to 223.255.255.255', '24', '8', 'Small networks'],
            ['D', '224.0.0.0 to 239.255.255.255', '–', '–', 'Multi-cast'],
            ['E', '240.0.0.0 to 255.255.255.255', '–', '–', 'Experimental'],
          ],
        },
      },
    ],
    visual: 'internet',
    accent: 'cyan',
    ...source(57, ['Table 2.8 · Network classes']),
  },

  {
    id: 'h2-223-binary',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · BINARY EXAMPLES',
    title: 'IP addresses can be represented in binary',
    lead: 'The coursebook provides examples of converting IP addresses to binary.',
    example: {
      title: 'Binary IP address examples',
      lines: [
        'Class C: 190.15.25.240',
        '  Binary: 10111110 00001111 00011001 11110000',
        '  netID: 190.15.25, hostID: 240',
        '',
        'Class B: 128.148.12.14',
        '  Binary: 10000000 10010100 00001100 00001110',
        '  netID: 128.148, hostID: 12.14',
        '',
        'Class A: 29.68.0.43',
        '  Binary: 00011101 01000100 00000000 00101011',
        '  netID: 29, hostID: 68.0.43',
      ],
    },
    visual: 'internet',
    accent: 'emerald',
    ...source(58, ['Binary IP address examples']),
  },

  {
    id: 'h2-223-cidr',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · CLASSLESS INTER-DOMAIN ROUTING',
    title: 'CIDR increases the flexibility of IPv4 addressing',
    lead: 'The coursebook explains that CIDR reduces address wastage by allowing more flexible netID/hostID boundaries.',
    bullets: [
      'CIDR reduces the problem of wasted IP addresses.',
      'A suffix is used, such as 192.30.250.00/18.',
      'This means 18 bits will be used for the netID and the last 14 bits for the hostID.',
      'This is more flexible than the normal class-based allocation.',
      'The suffix clearly increases flexibility regarding which bits represent netID and hostID.',
    ],
    visual: 'internet',
    accent: 'amber',
    ...source(58, ['CIDR explanation']),
  },

  {
    id: 'h2-223-ipv6',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · IPV6 ADDRESSING',
    title: 'IPv6 uses 128-bit addressing to overcome IPv4 limitations',
    lead: 'The coursebook explains that IPv6 was developed to address IPv4 exhaustion.',
    bullets: [
      'IPv6 uses 128-bit addressing.',
      'It adopts hexadecimal notation.',
      'IPv6 addresses are broken into 16-bit chunks.',
      'A colon (:) is used instead of a decimal point (.).',
      'Example: A8FB:7A88:FFF0:0FFF:3D21:2085:66FB:F0FA',
    ],
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'IPv4',
        rightTitle: 'IPv6',
        rows: [
          ['32-bit address', '128-bit address'],
          ['About 4.3 billion addresses', 'About 340 undecillion addresses'],
          ['Dotted decimal (192.168.1.1)', 'Hexadecimal (2001:0db8::1)'],
          ['Broadcast messaging', 'No broadcast messaging'],
          ['Optional security', 'Built-in security (IPsec)'],
          ['NAT commonly used', 'No NAT needed'],
        ],
      },
    ],
    visual: 'internet',
    accent: 'indigo',
    ...source(59, ['IPv6 addressing description']),
  },

  {
    id: 'h2-223-ipv6-compression',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · ZERO COMPRESSION',
    title: 'IPv6 addresses can be shortened using zero compression',
    lead: 'The coursebook explains that zero compression replaces groups of zeroes with a double colon.',
    bullets: [
      'IPv6 addresses can be quite long.',
      'Zero compression replaces groups of 0000:0000 with ::.',
      'This can only be applied ONCE to an address.',
      'Example: 900B:3E4A:AE41:0000:0000:AFF7:DD44:F1FF',
      'Can be written as: 900B:3E4A:AE41::AFF7:DD44:F1FF',
    ],
    example: {
      title: 'Zero compression rules',
      lines: [
        'Original: 8055:F2F2:0000:0000:FFF1:0000:0000:DD04',
        'Valid: 8055:F2F2::FFF1:0000:0000:DD04',
        'Valid: 8055:F2F2:0000:0000:FFF1::DD04',
        'INVALID: 8055:F2F2::FFF1::DD04 (two ::)',
        'Only one :: is allowed to avoid ambiguity',
      ],
    },
    visual: 'internet',
    accent: 'cyan',
    ...source(59, ['Zero compression explanation']),
  },

  {
    id: 'h2-223-subnetting',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · SUB-NETTING',
    title: 'Sub-netting divides a LAN into smaller networks',
    lead: 'The coursebook provides a university example to explain sub-netting.',
    example: {
      title: 'University network example',
      lines: [
        'University has 8 departments with netID 192.200.20',
        'HostIDs split: 000 00000 (3 bits for subnet, 5 bits for host)',
        '',
        'Admin and finance: netID 192.200.20.0, hostID 00001-11110',
        'Humanities: netID 192.200.20.1, hostID 00001-11110',
        'Maths: netID 192.200.20.2, hostID 00001-11110',
        'Science: netID 192.200.20.3, hostID 00001-11110',
        'Arts: netID 192.200.20.4, hostID 00001-11110',
        'Engineering: netID 192.200.20.5, hostID 00001-11110',
        'Computing: netID 192.200.20.6, hostID 00001-11110',
        'Business: netID 192.200.20.7, hostID 00001-11110',
      ],
    },
    bullets: [
      'Sub-netting divides a LAN into two or more smaller networks.',
      'This helps reduce network traffic.',
      'It can also hide the complexity of the overall network.',
      'The hostID is split into subnet expansion and host portions.',
      'To obtain the netID from the IP address, apply the AND mask.',
    ],
    visual: 'internet',
    accent: 'emerald',
    ...source(60, ['Sub-netting university example', 'Table 2.9']),
  },

  {
    id: 'h2-223-private-public',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.3 · PRIVATE VS PUBLIC IP ADDRESSES',
    title: 'Private IP addresses are for internal use; public IPs are for internet access',
    lead: 'The coursebook distinguishes between private and public IP addresses.',
    bullets: [
      'Private IP addresses are reserved for internal use behind a router.',
      'They allow access to the network without taking up public IP address space.',
      'Devices using private IP addresses cannot be reached by internet users.',
      'Public IP addresses are allocated by the user\'s ISP.',
      'Public IP addresses are used by DNS servers, network routers and directly-controlled computers.',
    ],
    richBlocks: [
      {
        kind: 'table',
        table: {
          caption: 'Table 2.10 · Private IP address ranges',
          headers: ['Class', 'Range', 'Possible Addresses'],
          rows: [
            ['A', '10.0.0.0 to 10.255.255.255', '16 million'],
            ['B', '172.16.0.0 to 172.31.255.255', '1 million'],
            ['C', '192.168.0.0 to 192.168.255.255', '65,600'],
          ],
        },
      },
    ],
    visual: 'internet',
    accent: 'indigo',
    ...source(61, ['Private vs public IP addresses', 'Table 2.10']),
  },

  checkpoint('h2-cp-ip', '2.2 The internet', 'Past papers: IP addresses, IPv4, IPv6', ['2.2.3'], [61], 'indigo'),

  // ─── URLS ────────────────────────────────────────────────────────────────────
  {
    id: 'h2-224-urls',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.4 · UNIFORM RESOURCE LOCATORS',
    title: 'A URL identifies the exact location of a web resource',
    lead: 'The coursebook breaks down the parts of a URL. You must be able to identify each component.',
    keyTerms: [
      { term: 'URL', definition: 'Uniform Resource Locator: the complete address of a resource on the web.' },
    ],
    richBlocks: [
      {
        kind: 'code',
        title: 'URL structure breakdown',
        lines: [
          'protocol://website address/path/filename',
          '',
          'Protocol: usually http or https',
          'Website address: domain host (www) + domain name + domain type (.com, .org, .net, .gov)',
          'Path: the web page (if omitted, root directory)',
          'Filename: the item from the web page',
          '',
          'Example: http://www.hoddereducation.co.uk/computerscience',
          '  protocol: http',
          '  website address: www.hoddereducation.co.uk',
          '  path: /computerscience',
        ],
      },
    ],
    example: {
      title: 'URL examples',
      lines: [
        'https://www.bbc.co.uk/news/article',
        '  protocol: https (secure)',
        '  domain: www.bbc.co.uk',
        '  path: /news/article',
        '',
        'ftp://files.school.edu/documents',
        '  protocol: ftp (file transfer)',
        '  domain: files.school.edu',
        '  path: /documents',
      ],
    },
    visual: 'html',
    accent: 'cyan',
    ...source(61, ['2.2.4 URLs']),
  },

  // ─── DNS ─────────────────────────────────────────────────────────────────────
  {
    id: 'h2-225-dns',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.5 · DOMAIN NAME SYSTEM',
    title: 'DNS translates human-readable domain names to IP addresses',
    lead: 'The coursebook explains that DNS gives domain names for internet hosts and is a system for finding IP addresses.',
    keyTerms: [
      { term: 'DNS', definition: 'Domain Name Service: gives domain names for internet hosts and is a system for finding IP addresses of a domain name.' },
    ],
    bullets: [
      'DNS eliminates the need for users to memorise IP addresses.',
      'The process involves converting a host name into an IP address.',
      'DNS servers contain a database of URLs with matching IP addresses.',
      'The web browser asks the DNS server for the IP address.',
      'If the DNS server cannot find it, it sends a request to another DNS server.',
    ],
    richBlocks: [
      {
        kind: 'steps',
        title: 'DNS lookup process (5 steps)',
        items: [
          'User opens browser and types URL (e.g., www.hoddereducation.co.uk).',
          'Browser asks DNS server (1) for the IP address.',
          'DNS server (1) cannot find it, sends request to DNS server (2).',
          'DNS server (2) finds the URL and maps it to IP address (e.g., 107.162.140.19).',
          'IP address is sent back to user\'s computer, which connects to the website server.',
        ],
      },
    ],
    example: {
      title: 'DNS lookup example',
      lines: [
        'You type: www.hoddereducation.co.uk',
        'Browser asks DNS server for IP address',
        'DNS server responds: 107.162.140.19',
        'Browser connects to 107.162.140.19',
        'Web page loads!',
      ],
    },
    visual: 'internet',
    accent: 'emerald',
    ...source(62, ['2.2.5 DNS', 'Figure 2.25']),
  },

  checkpoint('h2-cp-dns', '2.2 The internet', 'Past papers: DNS and URL structure', ['2.2.4', '2.2.5'], [63], 'cyan'),

  // ─── HTML ────────────────────────────────────────────────────────────────────
  {
    id: 'h2-226-html',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.6 · SCRIPTING IN HTML',
    title: 'HTML uses tags to structure web page content',
    lead: 'The coursebook introduces basic HTML elements and their purposes. HTML is the standard language for creating web pages.',
    keyTerms: [
      { term: 'HTML', definition: 'HyperText Markup Language: the standard language for creating web pages.' },
      { term: 'Tag', definition: 'An HTML element that defines the structure or content of a web page (e.g., <html>, <p>).' },
      { term: 'Element', definition: 'A complete tag including opening tag, content and closing tag (e.g., <p>Hello</p>).' },
    ],
    richBlocks: [
      {
        kind: 'code',
        title: 'Basic HTML structure',
        lines: [
          '<html>',
          '<body>',
          '<p> Example <p/>',
          '[program code]',
          '</html>',
        ],
      },
    ],
    bullets: [
      'HTML tags are enclosed in angle brackets (e.g., <html>, <body>).',
      'Most tags come in pairs: an opening tag and a closing tag.',
      'Between the HTML tags, JavaScript or PHP can be included.',
      'HTML is used to create web pages.',
      'Web browsers interpret HTML and display the results.',
    ],
    visual: 'html',
    accent: 'indigo',
    ...source(63, ['2.2.6 Scripting in HTML']),
  },

  {
    id: 'h2-226-javascript',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.6 · JAVASCRIPT',
    title: 'JavaScript runs on the client-side to enhance web pages',
    lead: 'The coursebook provides a JavaScript example that processes temperature input.',
    keyTerms: [
      { term: 'JavaScript', definition: 'Object-orientated (or scripting) programming language used mainly on the web to enhance HTML pages.' },
      { term: 'Client-side', definition: 'The script runs on the computer making the request, processing web page data from the server.' },
      { term: 'Server-side', definition: 'The script runs on the web server and results are sent to the computer that made the request.' },
    ],
    richBlocks: [
      {
        kind: 'code',
        title: 'JavaScript temperature example',
        lines: [
          '01  <html>',
          '02  <body>',
          '03  <p>Enter the temperature</p>',
          '04  <input id="Temp" value="0"',
          '05  <button onclick="checkReading()">Enter</button>',
          '06  <script>',
          '07    function checkReading() {',
          '08      var temp, result;',
          '09      temp = document.getElementById("Temp").value;',
          '10      if (temp >= 200) {',
          '11        result = "HIGH"',
          '12      } else if (temp >= 100) {',
          '13        result = "OK"',
          '14      } else {',
          '15        result = "LOW"',
          '16      }',
          '17      alert("The result is " + result)',
          '18    }',
          '19  </script>',
          '20  </body>',
          '21  </html>',
        ],
      },
    ],
    visual: 'html',
    accent: 'cyan',
    ...source(63, ['JavaScript example']),
  },

  {
    id: 'h2-226-php',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.6 · PHP',
    title: 'PHP is processed on the server-side',
    lead: 'The coursebook provides a PHP example that processes temperature input on the server.',
    keyTerms: [
      { term: 'PHP', definition: 'Hypertext processor: an HTML-embedded scripting language used to write web pages.' },
    ],
    richBlocks: [
      {
        kind: 'code',
        title: 'PHP temperature example',
        lines: [
          '01  <?php',
          '02    if(isset($_GET[\'temp\'])) {',
          '03      echo "Result: " . checkReading($_GET[\'temp\']);',
          '04    } else {',
          '05  ?>',
          '06  <form action="#" method="get">',
          '07    Enter Temp: <input type="text" name="temp" /><br />',
          '08    <input type="submit" value="Calculate" />',
          '09    </form>',
          '10  <?php',
          '11    }',
          '12      function checkReading($inputTemp) {',
          '13        $resultChar = "L";',
          '14        if($inputTemp >= 200) $resultChar = "H";',
          '15        else if($inputTemp >= 100) $resultChar = "O";',
          '16        return $resultChar;',
          '17      }',
          '18  ?>',
        ],
      },
    ],
    bullets: [
      'PHP is processed on the server-side.',
      'Variables begin with $ and are case-sensitive.',
      'The code is sandwiched inside HTML.',
      'PHP files are stored with .php extension.',
    ],
    visual: 'html',
    accent: 'emerald',
    ...source(64, ['PHP example']),
  },

  {
    id: 'h2-226-client-server-side',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: '2.2.6 · CLIENT-SIDE VS SERVER-SIDE',
    title: 'Scripts can run on the client or server',
    lead: 'The coursebook distinguishes between client-side and server-side script execution.',
    richBlocks: [
      {
        kind: 'comparison',
        leftTitle: 'Client-side (JavaScript)',
        rightTitle: 'Server-side (PHP)',
        rows: [
          ['Runs on the user\'s computer', 'Runs on the web server'],
          ['Processes data from the server', 'Processes data and sends results'],
          ['Faster response (no server call)', 'Slower (requires server communication)'],
          ['Less secure (code visible to user)', 'More secure (code hidden on server)'],
          ['Cannot access server files', 'Can access server files and databases'],
        ],
      },
    ],
    visual: 'html',
    accent: 'amber',
    ...source(64, ['Client-side vs server-side comparison']),
  },

  // ─── ACTIVITIES ─────────────────────────────────────────────────────────────
  {
    id: 'h2-activity-2a',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: 'ACTIVITY 2A',
    title: 'Choose the right network model for two companies',
    lead: 'Use the size of the group, the need to share data and the required level of control and security to justify each decision.',
    richBlocks: [
      {
        kind: 'steps',
        title: 'Coursebook Activity 2A · p.36',
        items: [
          'A company has 20 employees developing a new mobile-phone battery. Decide whether client-server or peer-to-peer is more suitable and give reasons.',
          'A group of financial consultants advises other companies on taxation and overseas exports. Decide which network model is more suitable and justify the choice.',
        ],
      },
    ],
    visual: 'recap',
    accent: 'indigo',
    ...source(36, ['ACTIVITY 2A · both company scenarios']),
  },

  {
    id: 'h2-activity-2b',
    section: '2.1 Networking',
    subtopicCode: '2.1',
    eyebrow: 'ACTIVITY 2B',
    title: 'Apply your knowledge of networking',
    lead: 'These activities test your understanding of the networking section.',
    richBlocks: [
      {
        kind: 'steps',
        title: 'Activity 2B questions',
        items: [
          'a) Explain the differences between LAN, MAN and WAN.',
          'b) Give three benefits of networking computers.',
          'c) Explain: (i) Thick client, (ii) Thin client.',
          'a) Draw diagrams of bus, star and mesh topologies.',
          'b) Give one benefit and one drawback of each.',
          'a) Explain differences between public and private cloud computing.',
          'b) Give two benefits of cloud computing.',
          'c) Give two drawbacks of cloud computing.',
          'Write a report on whether a LAN in a 20-floor building should use wired or wireless connectivity.',
          'a) What is bit streaming?',
          'b) Why are buffers necessary?',
          'c) Explain differences between on-demand and real-time bit streaming.',
        ],
      },
    ],
    visual: 'recap',
    accent: 'cyan',
    ...source(53, ['Activity 2B']),
  },

  {
    id: 'h2-activity-2c',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: 'ACTIVITY 2C',
    title: 'Apply your knowledge of the internet',
    lead: 'These activities test your understanding of the internet section.',
    richBlocks: [
      {
        kind: 'steps',
        title: 'Activity 2C questions',
        items: [
          'a) Describe what happens when a telephone call is made using PSTN.',
          'b) Describe what happens when a computer makes a call over the internet.',
          'c) Explain differences between GEO, MEO and LEO satellites.',
          'a) Write starting IP addresses in binary format.',
          'b) Write down upper IP addresses of classes A, B and C.',
          'c) Given IP address 10111110 00001111 00011001 11110000: (i) Which class? (ii) Which bits are netID/hostID?',
          'd) Give two differences between IPv4 and IPv6.',
          'a) Describe differences between private and public IP addresses.',
          'b) Identify protocol, domain name and file name in a URL.',
          'c) Describe how DNS retrieves a web page.',
          'a) Explain differences between internet and WWW.',
          'b) Is "The internet is not necessarily a type of WAN" correct?',
          'c) Explain: (i) Web browser, (ii) ISP.',
        ],
      },
    ],
    visual: 'recap',
    accent: 'emerald',
    ...source([64,65], ['Activity 2C']),
  },

  // ─── END OF CHAPTER QUESTIONS ──────────────────────────────────────────────
  {
    id: 'h2-end-questions',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: 'END OF CHAPTER QUESTIONS',
    title: 'Practice exam questions from the coursebook',
    lead: 'These questions are from the end of chapter and test your understanding of all topics.',
    richBlocks: [
      {
        kind: 'steps',
        title: 'Question 1: Network topologies',
        items: [
          'Star and mesh are two types of network topology.',
          'a) State one benefit and one drawback of the star network topology.',
          'b) State one benefit and one drawback of the mesh network topology.',
          'c) Connect each description to either client-server or peer-to-peer network.',
        ],
      },
      {
        kind: 'steps',
        title: 'Question 2: PSTN and cabling',
        items: [
          'a) Explain the difference between copper cabling and fibre optic cabling.',
          'b) Describe two benefits and two drawbacks of both types of cabling.',
          'c) Compare the differences between GEO, MEO and LEO satellites.',
          'd) Explain: (i) Attenuation of a signal, (ii) Spread spectrum frequency hopping.',
        ],
      },
      {
        kind: 'steps',
        title: 'Question 3: Bit streaming',
        items: [
          'a) Explain the term bit streaming.',
          'b) Give two benefits and two potential problems of using bit streaming.',
          'c) Explain the terms on-demand bit streaming and real-time bit streaming.',
        ],
      },
      {
        kind: 'steps',
        title: 'Question 4: Buffer calculation',
        items: [
          'A buffer is 2 MiB in size. Lower limit: 200 KiB, higher limit: 1.8 MiB.',
          'Data streamed at 1.5 Mbps, media player taking data at 600 kbps.',
          'a) Explain why the buffer is needed.',
          'b) Calculate data in buffer after 2 seconds of streaming.',
          'c) Determine how long to reach higher limit.',
          'd) Describe how to overcome the problem for a 30-minute video.',
        ],
      },
      {
        kind: 'steps',
        title: 'Question 5: CSMA/CD and network devices',
        items: [
          'a) Explain the term data collision.',
          'b) Describe how CSMA/CD detects collisions.',
          'c) Explain how CSMA/CD resolves data collision.',
          'd) Connect each network device to its description.',
        ],
      },
    ],
    visual: 'recap',
    accent: 'indigo',
    ...source([65,66,67], ['End of chapter questions 1–5']),
  },

  // ─── CHAPTER REVIEW ─────────────────────────────────────────────────────────
  {
    id: 'h2-review-terms',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: 'CHAPTER 2 · KEY TERMS REVIEW',
    title: 'Review all key terms from this chapter',
    lead: 'These terms appear throughout the chapter and in exam questions. Make sure you can define each one.',
    keyTerms: [
      { term: 'Hub', definition: 'Broadcasts data to all ports.' },
      { term: 'Switch', definition: 'Forwards data to specific MAC address.' },
      { term: 'Router', definition: 'Routes between networks using IP.' },
      { term: 'Gateway', definition: 'Converts data from one protocol to another.' },
      { term: 'Client-server', definition: 'Centralised server provides services.' },
      { term: 'Peer-to-peer', definition: 'Each device has equal status.' },
      { term: 'Star topology', definition: 'All devices connect to central hub/switch.' },
      { term: 'CSMA/CD', definition: 'Collision detection in Ethernet.' },
      { term: 'IPv4', definition: '32-bit IP address.' },
      { term: 'IPv6', definition: '128-bit IP address.' },
      { term: 'DNS', definition: 'Translates domain names to IP addresses.' },
      { term: 'URL', definition: 'Web resource address.' },
      { term: 'HTML', definition: 'Language for creating web pages.' },
      { term: 'JavaScript', definition: 'Client-side scripting language.' },
      { term: 'PHP', definition: 'Server-side scripting language.' },
      { term: 'Bit streaming', definition: 'Contiguous sequence of digital bits sent over network.' },
      { term: 'Buffer', definition: 'Temporary storage for smooth playback.' },
      { term: 'VoIP', definition: 'Voice over Internet Protocol for phone calls.' },
    ],
    visual: 'recap',
    accent: 'indigo',
    ...source(67, ['Chapter 2 key terms review']),
  },

  {
    id: 'h2-review-activity',
    section: '2.2 The internet',
    subtopicCode: '2.2',
    eyebrow: 'CHAPTER 2 · REVIEW ACTIVITIES',
    title: 'Apply what you have learned',
    lead: 'These activities test your understanding of the key concepts. Try them before looking at the answers.',
    richBlocks: [
      {
        kind: 'steps',
        title: 'Consolidation tasks',
        items: [
          'Draw a network with 5 computers using star topology. Label the central device and explain its role.',
          'List 3 examples of client-server networks and 3 examples of peer-to-peer networks.',
          'Explain the difference between a hub and a switch. Which is better for a large network and why?',
          'Trace what happens when you type www.example.com into a browser. Include DNS, IP addresses and protocols.',
          'Write HTML for a page with a heading, a paragraph and a link.',
          'Compare IPv4 and IPv6. Why was IPv6 developed?',
          'Explain the difference between on-demand and real-time bit streaming.',
          'Describe the differences between PSTN and VoIP for making phone calls.',
        ],
      },
      {
        kind: 'callout',
        tone: 'activity',
        title: 'Exam practice',
        text: 'Past paper questions often ask you to: compare network devices, explain topologies, describe DNS lookup, compare client-server with peer-to-peer, explain CSMA/CD, compare IPv4 and IPv6, and write basic HTML. Practice these skills regularly.',
      },
    ],
    teacherPrompt: 'Work through each task and explain your reasoning. Focus on the "why" not just the "what".',
    visual: 'recap',
    accent: 'indigo',
    ...source(67, ['Chapter 2 review activities']),
  },
];

export const CHAPTER_2: Chapter2Lesson = {
  number: 2,
  level: 'AS Level',
  title: 'Communication',
  subtitle: 'Complete Hodder Chapter 2 teaching route with networking and internet technologies, including worked examples, activities and teacher prompts.',
  subtopics: ['2.1 Networking', '2.2 The internet'],
  sourceNote: 'Uploaded Hodder Education Chapter 2 extract, 41 pages. Content is pedagogically reformatted rather than reproduced as page images.',
  coverage: '41/41 source pages · objectives · prior knowledge · key terms · worked examples · activities · teacher prompts · tables · figures · callouts · end-of-chapter review',
  slides,
};
