import type { HodderLessonSlide } from './lesson-content-hodder-types';

const source = (page: number, elements: string[]) => ({
  sourcePages: [page],
  sourceLabel: `Hodder Chapter 3 · p.${page}`,
  sourceElements: [`Hodder p.${page}`, ...elements],
});

/** Source-specific continuation of Hodder 9618 Chapter 3, printed pp.84–89. */
export const CHAPTER_3_SENSOR_SLIDES: readonly HodderLessonSlide[] = [
  {
    id: 'h3-312-sensors-adc-dac',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.2',
    eyebrow: 'FIGURE 3.19 · SENSORS + ADC/DAC',
    title: 'Sensors measure analogue physical properties; computers work with discrete digital values',
    lead: 'Hodder defines sensors as input devices that read or measure physical properties such as temperature, pressure and acidity. Real-world data is analogue and normally needs an ADC before a computer can process it.',
    bullets: [
      'Analogue data is constantly changing and does not have a discrete value.',
      'An analogue-to-digital converter (ADC) converts physical values into discrete digital values.',
      'Control outputs such as motors and valves may require a digital-to-analogue converter (DAC).',
      'An actuator is an electromechanical device such as a relay, solenoid or motor.',
      'A solenoid can act as a digital actuator; motors and valves may require a DAC and an electric current.',
      'In a control system, output can affect the next sensor input: Hodder describes this as positive feedback.',
    ],
    visual: 'types',
    accent: 'cyan',
    ...source(84, ['Figure 3.19 Converting analogue data into digital data', 'sensor', 'ADC', 'DAC', 'actuator', 'relay', 'solenoid', 'motor', 'positive feedback']),
  },
  {
    id: 'h3-312-sensor-applications',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.2',
    eyebrow: 'TABLE 3.7 · COMMON SENSORS',
    title: 'Different sensors map physical properties to monitoring and control applications',
    lead: 'Table 3.7 links nine common sensor types to practical applications.',
    richBlocks: [{
      kind: 'table',
      table: {
        caption: 'Table 3.7 · Common sensors and examples of applications',
        headers: ['Sensor', 'Examples from Hodder'],
        rows: [
          ['temperature', 'central heating · chemical process · greenhouse temperature'],
          ['moisture/humidity', 'greenhouse soil/air · dampness in industrial applications'],
          ['light', 'street lighting · greenhouse light · automatic car headlights'],
          ['infrared/motion', 'windscreen wipers · burglar alarm · people counting'],
          ['pressure', 'burglar alarm · vehicle weight · gas-pressure process'],
          ['acoustic/sound', 'burglar alarm noise · dripping-liquid detection'],
          ['gas (O₂ or CO₂)', 'river/air pollution · greenhouse gases · power-station leaks'],
          ['pH', 'soil acidity/alkalinity · river pollution'],
          ['magnetic field', 'cell phones/CD players · anti-lock braking systems'],
        ],
      },
    }],
    visual: 'types',
    accent: 'indigo',
    ...source(85, ['Table 3.7 Common sensors and examples of applications']),
  },
  {
    id: 'h3-312-monitor-control',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.2',
    eyebrow: 'FIGURE 3.20 + TABLE 3.8 · MONITORING VS CONTROL',
    title: 'Monitoring watches a process; control changes the process and creates a feedback loop',
    lead: 'Both paths begin with sensors, optional ADC conversion and comparison with stored values. They diverge when data falls outside the acceptable range.',
    richBlocks: [{
      kind: 'comparison',
      leftTitle: 'Monitoring system',
      rightTitle: 'Control system',
      rows: [
        ['Outside range → warning message or alarm', 'Outside range → signals sent to valves, motors and other devices'],
        ['Microprocessor/computer has no effect on what is monitored', 'System output affects the next sensor inputs'],
        ['Examples: hospital vital signs, burglar alarm, car-engine temperature, river pollution', 'Examples: street lights, central heating/air conditioning, traffic lights, ABS, greenhouse environment'],
      ],
    }],
    visual: 'types',
    accent: 'emerald',
    ...source(86, ['Figure 3.20 Sensors for monitoring and controlling systems', 'Table 3.8 Examples of monitoring and control applications of sensors', 'feedback loop']),
  },
  {
    id: 'h3-312-abs-control',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1.2',
    eyebrow: 'FIGURE 3.21 · ABS CONTROL LOOP',
    title: 'ABS repeatedly compares wheel speeds and adjusts braking pressure',
    lead: 'Hodder uses anti-lock braking as an in-depth sensor-control example built around magnetic field sensors and continuous feedback.',
    richBlocks: [{
      kind: 'steps',
      title: 'Source sequence',
      items: [
        'A wheel rotating too slowly sends magnetic-field-sensor data to the microprocessor.',
        'The microprocessor checks the rotation speed of the other three wheels.',
        'If the affected wheel is slower, braking pressure to that wheel is reduced.',
        'Its rotational speed increases to match the other wheels.',
        'Checks happen several times a second; braking pressure can change constantly to prevent locking.',
        'The driver may feel this rapid switching as a “judder” on the brake pedal.',
        'If a wheel rotates too quickly, braking pressure is increased until it matches the other three.',
      ],
    }],
    visual: 'types',
    accent: 'rose',
    ...source(87, ['Figure 3.21 Sensors on a typical modern car', 'Anti-lock braking systems (ABS)', 'magnetic field sensors', 'judder']),
  },
  {
    id: 'h3-31-activity-3a-3e',
    section: '3.1 Computers and their components',
    subtopicCode: '3.1',
    eyebrow: 'ACTIVITY 3A + EXTENSION ACTIVITY 3E',
    title: 'Book practice: consolidate memory, storage, printers, 3D printing and sensor control',
    lead: 'The Hodder activity set closes section 3.1 with comparison, explanation and control-system reasoning.',
    richBlocks: [
      {kind: 'steps', title: 'Activity 3A', items: [
        '1a · Describe three differences between RAM and ROM; compare SRAM and DRAM, including where each is used.',
        '1b · For magnetic, optical and solid-state secondary storage, describe two differentiating features of each.',
        '2a · Explain the main differences in operation of a laser printer and an inkjet printer.',
        '2b · Name one application for each printer and justify why each is suitable.',
        '3 · Explain why an art gallery might create a 3D replica of a valuable, fragile painting from photographs.',
        '4 · Explain how a microprocessor-controlled street light uses sensor → ADC → microprocessor → DAC, including a method to prevent flicker under brief light changes.',
      ]},
      {kind: 'callout', tone: 'extension', title: 'Extension Activity 3E', text: 'Explain how pressing H on the simplified keyboard is recognised and how the computer handles slow keyboard input; then explain mechanical and optical mice and compare USB-cable with wireless connectivity.'},
    ],
    visual: 'types',
    accent: 'amber',
    ...source(88, ['Activity 3A', 'Extension Activity 3E', 'microprocessor-controlled street lighting system', 'keyboard conductive layers', 'mechanical mouse', 'optical mouse', 'USB', 'wireless']),
  },
  {
    id: 'h3-32-logic-gates-intro',
    section: '3.2 Logic gates and logic circuits',
    subtopicCode: '3.2.1',
    eyebrow: '3.2.1 · FIGURE 3.22 · SIX LOGIC GATES',
    title: 'Logic gates take binary inputs and produce a binary output',
    lead: 'Hodder introduces logic gates, logic circuits, truth tables and Boolean algebra, then names the six gates used in this section.',
    bullets: [
      'Logic gates are electronic circuits that rely on on/off logic.',
      'A logic circuit combines gates to carry out a particular task; its output is 0 or 1.',
      'A truth table checks outputs for every possible binary input combination.',
      'Two inputs give 2² = 4 combinations; three inputs give 2³ = 8 combinations.',
      'Boolean algebra is linked to logic circuits and is based on TRUE and FALSE.',
      'The six gates introduced are NOT, AND, OR, NAND, NOR and XOR.',
    ],
    richBlocks: [{kind: 'callout', tone: 'extension', title: 'Extension Activity 3F', text: 'Investigate the main differences between QLED and OLED technologies.'}],
    visual: 'types',
    accent: 'indigo',
    ...source(89, ['Extension Activity 3F', '3.2 Logic gates and logic circuits', 'Key terms', '3.2.1 Logic gates', 'Figure 3.22 Six types of logic gate', 'NOT', 'AND', 'OR', 'NAND', 'NOR', 'XOR']),
  },
];
